### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by amcdnl** [ceolter/ag-grid#10]
Need both unit and e2e tests.  Protractor and Jasmine.

**Comment by vitvad** [comment]
+1
@ceolter, this have to be the first priority, also add performance tests.

Cool component. Not written in angular, but worse to check their approach [handsontable](https://github.com/handsontable/handsontable) 

some advises:
- cache DOM dimensions
- render and perform heavy operations with requestAnimationFrame
- IE10-11 rendering optimizations need

**Comment by ceolter** [comment]
Thanks @vitvad, testing is deffo on my plan. However I've purposely left it aside for the first few iterations, it's my style of programming, as the grid is constantly undergoing major re-designs and re-factorings. Once the design has settled down, I'll be introducing tests. Thanks also for the pointers, I'll check all those out.

**Comment by ceolter** [comment]
closing this issue as whether we use tests or not is a project decision, not an issue with the codebase :)
