### ISSUE TITLE
[Perf] Tweak queuing of network requests to improve load times

### ISSUE THREAD

**Issue by pauljoey** [ceolter/ag-grid#1003]
Hi! First off, ag-grid is the shit. You know, like the kids say. Many thanks for all the effort - and most especially for wading through the never-ending bug reports, feature requests and misc issues. 

So, on to my misc issue. 

We exclusively use ag-grid with custom back-end datasources with tables of varying sizes (100, 10K, 1M records, etc). We typically calculate the size of each table and pass this information to agGrid so that it can render the entire table and use virtual paging and the datasource as needed because it creates a nice UX. This works well.

We use `maxConcurrentRequests: 3` to prevent the server from being swarmed. However, if the user quickly scrolls through many pages of data (say, 20) then stops, this creates a backlog of network requests in agGrid that are all executed in sequence (FIFO). While this works and is "correct", the result is that the rows that are currently of interest to the user (ie, in the viewport) take the longest to load. For us, in practical terms, this can create appreciable delays.

I suggest that it may be a worthwhile optimization to consider some of the following:
1. Cap the number of backlogged network requests
2. Use LIFO rather than FIFO  for network requests
3. Add debounce timer option on scroll specifically for network requests
4. Replace `maxConcurrentRequests` with alternative option to limit the number of concurrent requests whereby new requests actually interrupt and replace older ones.

**Comment by ceolter** [comment]
good idea. i've taken note. i'll try and get this in soon.

**Comment by ceolter** [comment]
we reworked how infinate pagination works. the load queue now has a max size where oldest requests get chucked out, to avoid them building up.

**Comment by pauljoey** [comment]
ag-grid is so hot right now.

**Comment by foxmulder900** [comment]
@ceolter Is the load queue size configurable or documented anywhere? I'm still seeing quite a few requests building up.

Thanks a ton for your efforts, ag-grid rules!
