### ISSUE TITLE
textFilter

### ISSUE THREAD

**Issue by tonyeung** [ceolter/ag-grid#1007]
Right now the text filter options are hard coded.
It would be nice to be able to limit it to `contains` so devs don't have to implement each type of search on the server side.

**Comment by samuba** [comment]
I would strongly suggest that you make it configurable which textfilter-types are available.
For my usecase only `equals` would make sense.

**Comment by ceolter** [comment]
the text filter is really only supplied as an example on how you can do filtering. what i suggest is you build your own filter. if i was to make the text filter configurable, not just with this, but with all the other requests i get, then you would have something more complex.

so please copy / paste from this filter, make your own, and then 'make it your own' :)
https://github.com/ceolter/ag-grid/blob/master/src/ts/filter/textFilter.ts

**Comment by don-bluelinegrid** [comment]
@ceolter 

Niall,

Can you provide an example or a bit more explanation, on how to "make it your own"?  I'm assuming that you mean we can plug in an instance of a filter that matches a particular interface.

Thanks,
Don

**Comment by ceolter** [comment]
how to write your own filters explained here: https://www.ag-grid.com/javascript-grid-filtering/index.php

**Comment by don-bluelinegrid** [comment]
Got it, perfect.

Thank you,
Don
