### ISSUE TITLE
how to disable row selection? 

### ISSUE THREAD

**Issue by shikelong** [ceolter/ag-grid#1010]
I have a grid has the multi-checkbox-selection pattern.
I find the checkbox is  just some img.  I want to know how to disable the selection checkbox?

Regards.

**Comment by adduss** [comment]
@shikelong you can create your own cell renderer. Just extend Component and implement ICellRenderer.
After that pass it in ColDef object to cellRenderer property.

`import {ICellRenderer, Component} from 'ag-grid/main';

export class CustomCellRenderer extends Component implements ICellRenderer {
    private static CELL_TEMPLATE =
      '<div>' +
      '<input type="checkbox" >' +
      '</div>';

    constructor() {
        super(CustomCellRenderer.CELL_TEMPLATE);
    }

    public init(params: any): void {
        // set initial state
    }

    public refresh(params: any): void {
        // render on refresh
    }
}
`
read also doc page for cell rederer:
https://www.ag-grid.com/javascript-grid-cell-rendering/index.php

**Comment by adduss** [comment]
I added spaces between html elements because github editor not display them at all :/
