### ISSUE TITLE
dragStopped event parameter is empty object

### ISSUE THREAD

**Issue by ataft** [ceolter/ag-grid#1015]
dragStopped gives me an empty object. I would expect it to behave like columnMoved and give us an object like this:
{
	type: dragStopped,
	column: Employee,
	toIndex: 3
}

Also, it'd be great if dragStopped fired when a column was dragged off the grid, perhaps the object would have a "toIndex: -1". The columnVisible event doesn't work because a person could drag is visible/not visible a lot of times before finally dropping it. We need to be able to take action on the final drag stop.

**Comment by ramoncarreras** [comment]
+1

**Comment by ceolter** [comment]
not possible - the drag events are coming from a drag service - it isn't aware that it is used for dragging columns and making them visible or not.

the columns fire their own events for moving, visible etc.

what you could do is have a listener for drag events in your application, so you have a flag in your application that makes you aware if a drag is underway or not, thus ignoring column events while the drag is underway.

**Comment by shivekundefined** [comment]
Please provide an example that how did you do that?
