### ISSUE TITLE
pagination button disable state with bootstrap

### ISSUE THREAD

**Issue by liuzhongshu** [ceolter/ag-grid#1016]
when using with bootstrap, the disabled button in pagination bar is no difference with enabled button. but  without bootstrap, the disabled button will be grayed.   

for example
![image](https://cloud.githubusercontent.com/assets/458996/16826627/6bd47904-49b1-11e6-905a-41714782730e.png)

the button "last" is disabled, should be grayed, but still like normal button.

**Comment by ceolter** [comment]
the button is disabled. if a library you are using, such as bootstrap, is styling disabled buttons in a way you don't like, the issue is with the other library, not ag-Grid.
