### ISSUE TITLE
Saving/restoring user-selected aggregation state.

### ISSUE THREAD

**Issue by tloten** [ceolter/ag-grid#1017]
The columnApi.getColumnState() method returns the aggregation function initially set on the column defs - rather than the actual user-selected aggregation (if any at all).

I see there is a columnApi.getAggregationColumns() method, which, along with removeAggregationColumns(..), and addAggregationColumns(...) could be used to load & save the current aggregation state. But it doesn't JSON.Stringify out-of-the-box, and doesn't have same nice API as get/setColumnState().

Also, the current docs call it getValueXXXX(), even though that has been deprecated in favor of getAggregationXXXX().

**Comment by ceolter** [comment]
```The columnApi.getColumnState() method returns the aggregation function initially set on the column defs - rather than the actual user-selected aggregation (if any at all).``` -> I just tested this. I used the example on page https://www.ag-grid.com/javascript-grid-column-api/index.php (i updated it to enterprise from free ag-Grid) - I made 'Total' an value column, then changed using toolPanel to 'first' aggregation, and then printed the column state and it showed 'first' associated with the 'total' column.

```Also, the current docs call it getValueXXXX(), even though that has been deprecated in favor of getAggregationXXXX().``` -> correct, the docs are right, the code is wrong. i have changed this and gone back to 'value' in the method names. for a while i was calling in aggregation in the code, however i changed it as in the GUI (ie toolpanel) it's called value, and wanted to keep code and gui consistent.

**Comment by tloten** [comment]
I did some more in-depth testing - I mislead you on the issue, sorry :(
 It seems to be that if you **remove** the aggregation from a column in the tool panel, then getColumnState() still shows an aggFunc on that column. 

I replicated it here (based off your example): https://embed.plnkr.co/6NqQ9K/

Remove one of the aggregations, click 'Print col state', and you'll see the columns still have their last aggFunc.

**Comment by ceolter** [comment]
ok just fixed. will be in next release. thanks for raising.
