### ISSUE TITLE
Calling setHeaderHeight updates ag-header but not ag-header-row

### ISSUE THREAD

**Issue by leerons** [ceolter/ag-grid#1018]
When calling **setHeaderHeight** on the api, a new height value is set inline on the **_ag-header_** div but  **_ag-header-row_** still have the default value (25px) set as inline style.

This is a new behavior introduced in version **5.0.1** (and persists on **v5.0.2**), where on **v4.2.5** both divs are updated with the newly set value.

This new behavior results in a visual bug, where the header column divider lines (header cells right borders) are cut midway through the header. (see attached image)

![ag-grid-header-bug](https://cloud.githubusercontent.com/assets/485525/16835688/16b02d84-49ba-11e6-8dc7-5fc25124c9a2.jpg)

**Comment by ceolter** [comment]
thanks for raising. fixed for next release.
