### ISSUE TITLE
Filter state is not restored after rendering the page fetched from the data source

### ISSUE THREAD

**Issue by DaQuirm** [ceolter/ag-grid#1019]
1. Use a data source with `getRows` to fetch pages of data
2.  Set the `enableServerSideFilter` to `true`.
3. Open any Filter and type/change anything to trigger page loading
4. Once the page is loaded and rendered Filter's input is empty, that is, the value typed in previously is not restored.

**Comment by ceolter** [comment]
use newRowsAction
```filterParams: {newRowsAction: 'keep'}```

http://localhost/javascript-grid-filtering/index.php
