### ISSUE TITLE
autoSizeColumns() calculate only visible rows + very slow

### ISSUE THREAD

**Issue by adduss** [ceolter/ag-grid#1020]
AG version:
"ag-grid": "5.0.3",
"ag-grid-ng2": "5.0.0"

When I try to auto size columns it takes into consideration only visible elements, plus some kind of small offset. Excellent example of this behavior you can find on yours docs pages.
Steps to reproduce:
1. open: https://ag-grid.com/angular-grid-resizing/index.php
2. click "Auto-Size All" button
3. scroll a little bit, you can see athlete - "Leontien Zijlaard-van Moorsel"  displayed as "Leontien Zijlaard-va..."
4. click "Auto-Size All" button again - now it column size is proper

Additionally when I added more columns (around 40) this operation freeze my browser for around 3 seconds. In previous version ("ag-grid": "4.2.7", "ag-grid-ng2": "4.2.0") it was working fast.

**Comment by ceolter** [comment]
this is behaving as expected. i'll update the docs.

v5 introduced virtualised columns - so only columns visible in the viewport are rendered. it's a performance enhancement, so your grid can have 1000 columns and still work blazing fast, as it's only rendering the (approx) 10 visible on the screen.

sizeColumnsToFit looks at the columns on the screen, and works out the width based on what it sees. it cannot see the columns that are not rendered, so these are left out. what you are left with is enough 'packed' columns to fix your current page.

to get around this, you can turn off column virtualisation by setting grid property suppressColumnVirtualisation=true

i'll update the docs so everyone knows.

regards second issue, i have no idea, not seen this. if you can reproduce in a plunker, can take a look.

**Comment by ildarnm** [comment]
autoSizeColumns does not calculate columns size if ag-grid is hidden (display: none). For example within the component tab.

I understand that this is because the calculation of a size of a columns using a dummy container.

**Comment by tamarshankolevsky** [comment]
i wrote this property and it not work! [suppressColumnVirtualisation]="true"
The func "autoSize"... not work on columns that wasn't visible before

**Comment by Kenzohfs** [comment]
I had the same problem, setting suppressColumnVirtualisation=true worked for me. I'm using react ag-grid
