### ISSUE TITLE
enableServerSideSorting not working

### ISSUE THREAD

**Issue by stevez86** [ceolter/ag-grid#1021]
I'm getting the following error on the version 5.0.3 of ag-grid and not sure why: 

`columnController.js:783Uncaught (in promise) TypeError: Cannot read property 'slice' of undefined(…)ColumnController.getPrimaryAndSecondaryAndAutoColumns @ columnController.js:783`

Removing the property, `enableServerSideSorting: true` from grid options fixes the error.  I'm working in react.

`columnController.js:783Uncaught (in promise) TypeError: Cannot read property 'slice' of undefined(…)ColumnController.getPrimaryAndSecondaryAndAutoColumns @ columnController.js:783SortController.getColumnsWithSortingOrdered @ sortController.js:134SortController.getSortModel @ sortController.js:91VirtualPageRowModel.loadPage @ virtualPageRowModel.js:278VirtualPageRowModel.doLoadOrQueue @ virtualPageRowModel.js:220VirtualPageRowModel.reset @ virtualPageRowModel.js:113VirtualPageRowModel.setDatasource @ virtualPageRowModel.js:62VirtualPageRowModel.init @ virtualPageRowModel.js:50(anonymous function) @ context.js:194(anonymous function) @ context.js:194Context.postConstruct @ context.js:191Context.wireBeans @ context.js:70Context @ context.js:23Grid @ grid.js:69componentDidMount @ agGridReact.js:15notifyAll @ CallbackQueue.js:65close @ ReactReconcileTransaction.js:81closeAll @ Transaction.js:202perform @ Transaction.js:149perform @ Transaction.js:136perform @ ReactUpdates.js:86flushBatchedUpdates @ ReactUpdates.js:147ReactUpdates_flushBatchedUpdates @ ReactPerf.js:66close @ ReactUpdates.js:45closeAll @ Transaction.js:202perform @ Transaction.js:149perform @ ReactUpdates.js:86flushBatchedUpdates @ ReactUpdates.js:147ReactUpdates_flushBatchedUpdates @ ReactPerf.js:66closeAll @ Transaction.js:202perform @ Transaction.js:149batchedUpdates @ ReactDefaultBatchingStrategy.js:62enqueueUpdate @ ReactUpdates.js:176enqueueUpdate @ ReactUpdateQueue.js:24enqueueSetState @ ReactUpdateQueue.js:190ReactComponent.setState @ ReactComponent.js:65(anonymous function) @ Router.js:115(anonymous function) @ createTransitionManager.js:278(anonymous function) @ createTransitionManager.js:110done @ AsyncUtils.js:81(anonymous function) @ AsyncUtils.js:87getComponentsForRoute @ getComponents.js:9(anonymous function) @ getComponents.js:28(anonymous function) @ AsyncUtils.js:86mapAsync @ AsyncUtils.js:85getComponents @ getComponents.js:27(anonymous function) @ createTransitionManager.js:104next @ AsyncUtils.js:54(anonymous function) @ TransitionUtils.js:75checkAuth @ routes.js:34`

**Comment by ceolter** [comment]
this should be fixed in next release.

in the mean time, the grid is looking for columns (to work out the sorting) before the columns are set - you can get around it by not setting the datasource until AFTER the grid is initialised, that way you are guaranteed to have the columns in place before the first page request is done.

**Comment by MangeshTak** [comment]
Hi,
Is the issue is fixed?
