### ISSUE TITLE
Bind a cell value based on other cell value.

### ISSUE THREAD

**Issue by santosh-k1** [ceolter/ag-grid#1022]
Hi,

I have a requirement to add multiple select boxes in ag grid. I am able to do that by cellrenderer function.  I am also able to load the data dynamically in each select box on page load. But i need to populate the values in select box of a column, based on change of a select box value in other column. 

I am not able to find any help for achieving this in ag grid document. Please help.

Thanks.
Santoshk

**Comment by adduss** [comment]
@santosh-k1 check probably modelUpdated event will fire, just handle it there:

 (modelUpdated)="onModelUpdated()"

protected onModelUpdated() {
   // calculate your select
  }

**Comment by santosh-k1** [comment]
**@adduss**   Thanks for your reply. I think this event is available in aggrid with Angular 2.0. But we are using Angular 1.x. Is this event available for Angular 1.x? 

Please let us know where we will use this event, in Coldef ?

Thanks,
Santoshk

**Comment by adduss** [comment]
@santosh-k1 you can register any event listed here:
https://www.ag-grid.com/javascript-grid-events/index.php
using gridOptions, api and than addEventListener(eventType, listener), where type in this case will be 'modelUpdated' and handler onModelUpdated:

`gridOptions.api.addEventListener('modelUpdated', onModelUpdated);`

**Comment by ceolter** [comment]
all events are available in all flavours - there is nothing missing in the grid in ng1 or ng2.

if you are updating data in the grid, listen for ```cellValueChanged```, then call one of the fresh method to get the other cells to refresh.
