### ISSUE TITLE
How to get the value of selected row directly in HTML

### ISSUE THREAD

**Issue by darkmanAmazigh** [ceolter/ag-grid#1023]
i try to get the the value of number row selected, and print it in HTML using Angularjs, but no issue,
i have the count only when i clic in the grid column header.
The value of " selectedRowsCounter " is 0 in html, when i dosn't clic in the grid header

my code is like

       var activeButtons = function() {
		        var countRowsSelected =    $scope.gridOptions.api.getSelectedRows().length;
			$scope.selectedRowsCounter = countRowsSelected;
			console.log($scope.selectedRowsCounter);
			$rootScope.count.selectedRows = countRowsSelected;
		};

                $scope.gridOptions = {
				rowData: null,
			        angularCompileRows: true,
			        onSelectionChanged: activeButtons,
                }

there is a screenshot

http://www.hostingpics.net/viewer.php?id=926646afrikuss.png

Thank you

**Comment by darkmanAmazigh** [comment]
i have added this line to activeButtons function and it work fine

    $scope.gridOptions.api.refreshView();

**Comment by ceolter** [comment]
maybe you have to apply your scope?
