### ISSUE TITLE
Custom Column Aggregation

### ISSUE THREAD

**Issue by JonahJ** [ceolter/ag-grid#1024]
I have a grid with transaction data, many of which may be in different currencies. I would like to enable aggregations to work in groups / pivots, but there's a problem. the `aggFunc` value only sends the data for this column. In order to tell the currency, I will need access to the rowNodes. 

Anyway to do this cleanly (using angular1)?

Ideally a second callback would be added like `aggFuncRaw` which would pass in all of the rowModels for this aggregation.

**Comment by JonahJ** [comment]
Also since values are currency, is there anyway to apply a formatter function to the aggregate like there are for `cellRenderer` and `filterCellRenderer`? I would like to change precision and add currency to it.

**Comment by JonahJ** [comment]
Update on last comment: When I use `groupRowAggNodes` and return a string of the currency + value the grid hides the values.

Is it possible to allow non numeric types thru `groupRowAggNodes`

**Comment by ceolter** [comment]
few questions above

the agg functions will work on any type, not just number. the examples online shows ``'xyz' on Bronze``` a string value

if you want to use more than one column in your agg func, consider having an object as the value, eg
```
data.value = {
  currency: 'EUR',
  amount: 33.22
}
```
then you get it all in your agg func. you will either need a cellRenderer (to render to object) or you can cheat and have toString on your object
```
data.value = {
  currency: 'EUR',
  amount: 33.22,
  toString: function {
    return this.amount.toString();
  }
}
```
