### ISSUE TITLE
Get Distinct / Unique values for column

### ISSUE THREAD

**Issue by JonahJ** [ceolter/ag-grid#1025]
I cannot find any documentation on this. It must exist for the filtering ability on the columns. I just want to get the unique values on a column for `groupRowAggNodes`.

Use case is converting FX rates quickly for only those which exist in this aggregate.

**Comment by ceolter** [comment]
use one of the api.forEachNode methods to go through the rows. that's what the set filter does. you can then use api.getValue to get the value using the column.
