### ISSUE TITLE
date format filter using ag-grid

### ISSUE THREAD

**Issue by darkmanAmazigh** [ceolter/ag-grid#1029]
thats existing a format filter in ag-grid like this  ?

      field : 'replacementPieceDesignation.replacementPiece.maxDate',
      headerName  : "Date (max)",
      cellFilter: 'date:\'MM/dd/yyyy\'',`

Thank you

**Comment by ceolter** [comment]
such doesn't exist. if you want to format dates, either use cellFormatter or create your own cellRenderer for displaying dates.

**Comment by abhishek2016** [comment]
Hi Niall,
             Can you please share me the link of documentation about **cellFormatter** as you are mentioning about it in the above post. I am aware of cellRenderer. I just need the documentation for **cellFormatter**

**Comment by ceolter** [comment]
@abhishek2016 
mentioned here:
https://www.ag-grid.com/javascript-grid-column-definitions/index.php
shown in example here:
https://www.ag-grid.com/javascript-grid-viewport/index.php

**Comment by SanyaZoom** [comment]
@ceolter Hello, can me explain, why my code not correctly work:
`
...
columnDefs = [
    ...
    {headerName: 'dbegin', field: 'dbegin', type: 'date', cellFilter: 'date:"yyyy-MM-dd HH:mm"'},
    ...
  ];
...
  gridOptions = {
    rowData: this.rowData,
    columnDefs: this.columnDefs,
    rowSelection: 'single',
    enableColResize: true,
    enableSorting: true,
    enableFilter: true
  };
}
`

**Comment by ceolter** [comment]
@SanyaZoom ```type: 'date'``` - we don't support types, maybe you have us mix up with another grid!

**Comment by mlozanno** [comment]
@abhishek2016  you can use momentjs to format dates:

```
{headerName: "Updated at", field: "updated_at", hide: true, cellFormatter: function(data) {
    return moment(data.value).format('L');
}}
```

**Comment by jimbh** [comment]
how can we get time along with date filter ?

**Comment by FabricioCollins** [comment]
@ceolter how are you? I have a problem and maybe you can give me an idea. I need to filter my columns and my date filter component needs to consider date, date with time or just time. I can create my custom component for my **dateComponent** and receive parameter to build dynamically, however the object **params** passed to my component via Interface **IDate** can not pass information from the columns, and using the **IDateParams dateComponentParams** also can not pass column information to mount My component dynamically. Would you have an idea to help me? Note: My license is PRO. Grateful!

**Comment by LinnykS** [comment]
@ceolter Hi. Discovering `Value Getters and Value Formatters` chapter I found that 'cellFormatter' property mentioned only once and presents with not a lot of information, plus is this 'valueFormatter' property applicable at all? Because it looks like 'valueFormatter' property does not work as needed and 'cellFormatter', on the other hand, works fine instead of it.

**Comment by dneuer** [comment]
Yes, it looks like the Angular ValueFormatterService provided by ag-grid-angular looks for colDef.cellFormatter, not colDef.valueFormatter, which is therefore ignored.

**Comment by allanpichler** [comment]
Is there any way to change the order of the date filter, so that it is in the format dd/mm/yyyy rather than mm/dd/yyyy????
![capture](https://user-images.githubusercontent.com/16302352/40785583-22c4e2c6-64e9-11e8-8f72-c3d383ae8e75.PNG)

**Comment by FabricioCollins** [comment]
My solution has been, create a new custom filter component using a single file component with VueJS.
I used a template and integrated with a bootstrap datepicker component.
After then, passed my DateFilterComponent in the "filterFramework", attribute of ag-grid columnDefinition.
Worked very fine for me. Do your tests and tell me if it works for you.

Follow the complete example:

**- Importing the DateFilterComponent** 
`import DateFilterComponent from './DateFilterComponent.vue';`

**- On your columnDefinition**
`filterFramework: DateFilterComponent,`

**- The DateFilterComponent.vue** 

```
<template>
    <div>
        <select v-model="filter" class="ag-filter-select" id="filterType" @change="filterChange($event)">
            <option value="equals">{{vueInstance.$t("grid.equals")}}</option>
            <option value="notEqual">{{vueInstance.$t("grid.notEqual")}}</option>
            <option value="lessThan">{{vueInstance.$t("grid.lessThan")}}</option>
            <option value="lessThanOrEqual">{{vueInstance.$t("grid.lessThanOrEqual")}}</option>
            <option value="greaterThan">{{vueInstance.$t("grid.greaterThan")}}</option>
            <option value="greaterThanOrEqual">{{vueInstance.$t("grid.greaterThanOrEqual")}}</option>
            <option value="inRange">{{vueInstance.$t("grid.inRange")}}</option>
            <option value="nullValues">{{vueInstance.$t("grid.nullValues")}}</option>
            <option value="notNullValues">{{vueInstance.$t("grid.notNullValues")}}</option>
        </select>

        <div class="ag-filter-body">
            <div class="ag-filter-date-from" id="filterDateFromPanel">
                <div class="filter">
                    <datetime-picker v-model="date" :format="format" inputClass="ag-filter-filter ag-filter-input" :placeholder="format" :locale="locale" />
                </div>
            </div>
            <div class="ag-filter-date-to ag-hidden" id="filterDateToPanel">
                <div class="filter">
                    <datetime-picker v-model="dateTo" :format="format" inputClass="ag-filter-filter ag-filter-input" :placeholder="format" :locale="locale" />
                </div>
            </div>
        </div>

        <div class="ag-filter-apply-panel" id="applyPanel">
            <button type="button" id="clearButton" @click="clearFilter($event)">{{vueInstance.$t("grid.clearFilter")}}</button>
            <button type="button" id="applyButton" @click="applyFilter($event)">{{vueInstance.$t("grid.applyFilter")}}</button>
        </div>

    </div>
</template>

<script>
    import Vue from 'vue';
    import DatetimePicker from '../calendar/DatetimePicker.vue';

    export default Vue.extend({
        data () {
            return {
                el: null,
                date: '',
                dateTo: '',
                filter: 'equals',
                format: 'DD/MM/YYYY',
                valueGetter: null,
                rangeFieldObject: null,
                locale: ''
            };
        },
        props: {
            applyButton: {
                type: Boolean,
                default: true
            },
            clearButton: {
                type: Boolean,
                default: true
            }
        },
        computed: {
            vueInstance: function () {
                return this.params.colDef.filterParams.vueInstance;
            }
        },
        components: { DatetimePicker },
        methods: {
            applyFilter ($event) {
                this.params.filterChangedCallback();
            },

            clearFilter ($event) {
                this.date = null;
                this.dateTo = null;
                this.filter = 'equals';
                this.rangeFieldObject.addClass('ag-hidden');
                this.applyFilter();
            },

            filterChange ($event) {
                var filterValue = $event.target.value;
                if (filterValue === 'inRange') {
                    this.rangeFieldObject.removeClass('ag-hidden');
                }
                else {
                    this.rangeFieldObject.addClass('ag-hidden');
                }
            },

            isFilterActive() {
                return this.date !== null && this.date !== undefined && this.date !== '';
            },

            doesFilterPass(params){
                return !this.date || this.date.toLowerCase()
                    .split(" ")
                    .every((filterWord) => {
                        return this.valueGetter(params.node).toString().toLowerCase().indexOf(filterWord) >= 0;
                    });
            },

            getModel() {
                if (this.date === null) return null;
                var model = {
                    type: this.filter,
                    filter: this.date,
                    filterTo: this.dateTo
                };
                return model;
            },

            setModel(model) {
                this.date = model.value;
            },

            afterGuiAttached() {},

            componentMethod(message) {
                alert('Filter component: ${message}');
            }
        },
        created () {
            var store = this.params.column.colDef.parentData.store;
            var locale = store.getters.currentLanguage.toLowerCase();

            this.valueGetter = this.params.valueGetter;
            this.format = this.params.colDef.filterParams.dateFormat;
            this.applyButton = this.params.applyButton;
            this.clearButton = this.params.clearButton;
            this.locale=locale;
        },
        mounted: function () {
            this.rangeFieldObject = $(this.$el).find('#filterDateToPanel');
            this.clearFilter();
        }
    });
</script>

<style scoped>
    .input-group {
        padding: 4px;
        width: 100%;
    }
    .ag-filter-input {
        width: 96% !important;
        margin: 5px 0px 5px 2%;
    }
</style>
```

**Comment by hitu4233** [comment]
> Is there any way to change the order of the date filter, so that it is in the format dd/mm/yyyy rather than mm/dd/yyyy????
> ![capture](https://user-images.githubusercontent.com/16302352/40785583-22c4e2c6-64e9-11e8-8f72-c3d383ae8e75.PNG)

I want like this format MM/DD/YYYY can you explain me how it is posible to get in MM/DD/YYYY formate

**Comment by usmanilyas14** [comment]
Hi,
Can you please update on the datetime filter in ag-grid using javascript.

**Comment by altsanz** [comment]
+1

**Comment by Bronzato1** [comment]
Me too: I need the dd/mm/yyyy format on the date filter.

**Comment by lakmalsathyajith** [comment]
any update on this @ceolter ?? want to change this placeholder format to something else.

**Comment by RajeevKashyap** [comment]
> Is there any way to change the order of the date filter, so that it is in the format dd/mm/yyyy rather than mm/dd/yyyy????
> ![capture](https://user-images.githubusercontent.com/16302352/40785583-22c4e2c6-64e9-11e8-8f72-c3d383ae8e75.PNG)

Inside gridoptions you can change the order of tabs like  menuTabs: ["filterMenuTab", "generalMenuTab", "columnsMenuTab"],

**Comment by repeat760** [comment]
> [@ceolter](https://github.com/ceolter) Hi. Discovering `Value Getters and Value Formatters` chapter I found that 'cellFormatter' property mentioned only once and presents with not a lot of information, plus is this 'valueFormatter' property applicable at all? Because it looks like 'valueFormatter' property does not work as needed and 'cellFormatter', on the other hand, works fine instead of it.





https://preprocessor.space/questions/how-come-the-jquery-new-date-function-is-replacing-the-passed-parameter
