### ISSUE TITLE
[FEAT] Display sorting flag in column

### ISSUE THREAD

**Issue by z-boy** [ceolter/ag-grid#103]
At the moment it's not obvious to users that sorting is activated since no icon is displayed in the default sorting state. The user should directly see from a usability point of view if sorting is possible. Would it be possible to have a third sorting state e.g. "sort none" besides "sort asc" and "sort desc" that displays an initial icon like http://fortawesome.github.io/Font-Awesome/icon/sort/

In order to avoid cluttering of the header columns a general sorting icon can be displayed `onhover()` as currently is done with the sorting icon. It would minimize the cluttering and improve the usability here.

**Comment by ceolter** [comment]
interesting proposal. i think this needs to at least be an option (as my preference is to no show the icon). also could leave to both filter & sort icons showing on hover (and click filter to filter, sort to sort, and menu for everything else). also need to consider how it all works on touch devices.

**Comment by Wingie** [comment]
this feature is important to me from a usability perspective..
is there a way to configure it via the gridoptions or must we attach a customHeaderCellTemplate for every header that is sortable...

**Comment by ceolter** [comment]
this is already implemented. closing the issue.

see year column in the first example on this page:
https://www.ag-grid.com/angular-grid-sorting/index.php
