### ISSUE TITLE
Multiple row selection without pressing control  button

### ISSUE THREAD

**Issue by tonytomk** [ceolter/ag-grid#1030]
currently for selecting multiple rows we have to press control button along with click.
Is there any way we can get multiple row selection by only on mouse click ?

current behavior
https://www.ag-grid.com/javascript-grid-selection/index.php

**Comment by rsmything** [comment]
suppressRowClickSelection: true
suppressCellSelection: true
```
  gridDiv = document.getElementById 'table'

  observer = new MutationObserver (mutations) ->
    mutations.forEach (mutation) ->
      if mutation.type == 'childList' && mutation.target.className.split(' ')[0] == 'ag-row'
        $(gridDiv).delegate '.ag-row', 'click', ->
          console.log @
          #  How to toggle class 'ag-row-selected' for selected row?
  config =
    subtree: true
    childList: true
  observer.observe gridDiv, config
```

**Comment by rsmything** [comment]
Solution:

```
gridDiv = document.getElementById 'table'
$(gridDiv).delegate '.ag-row', 'click', ->
    $(@).toggleClass 'ag-row-selected'

gridOptions =
  suppressRowClickSelection: true
```

**Comment by ceolter** [comment]
there is no way in the grid to have row click select multiple rows.

what you can do is turn selection off, and then do the selection yourself (using the api). the selection will still work through the api, but the grid will not do selection when you click.

then add rowClicked listener to ag-grid, and the select or unselect using the api.

**Comment by ceolter** [comment]
or use checkbox selection.

**Comment by rsmything** [comment]
Select by click and deselect by second click the same rows.

.coffee
```
gridDiv = document.getElementById 'tracker-table'

$(gridDiv).delegate '.ag-row', 'click', ->
  $(@).toggleClass 'ag-row-selected'
  select = $(@).hasClass 'ag-row-selected'
  gridOptions.api.rowModel.rowRenderer.renderedRows[@.getAttribute('row')].rowNode.setSelected select`


gridOptions =
  rowSelection: 'multiple'
  suppressRowClickSelection: true
  suppressCellSelection: true
  suppressMenuHide: true
```

**Comment by tonytomk** [comment]
Hi Niall Crosby,
Thanks for the suggestion
