### ISSUE TITLE
Add/Remove row in ag-grid

### ISSUE THREAD

**Issue by darkmanAmazigh** [ceolter/ag-grid#1032]
How to add or remove a row in ag-grid
i try this, but not work

    $scope.gridOptions.rowData.puch(data);

this not working too

    $scope.gridOptions.api.setRowData(vehicle);

Thank's

**Comment by ceolter** [comment]
not supported. you have to set the entire set again. this is something i plan on introducing, possibly next week.

**Comment by DzmitryShylovich** [comment]
@ceolter I face the similar issue but with grouping. I need to update a table in real-time with data coming from the websocket. `grid.api.setRowData()` works fine but in this case I'll lose all grid state (selected and expanded rows). Is there a way to insert/update rows and persist state between updates? 
I think my question is related to https://www.ag-grid.com/forum/showthread.php?tid=2257&pid=9389#pid9389

**Comment by nidanaz168** [comment]
Hi,

Is this is supported now?

**Comment by harshitgupta** [comment]
+1
