### ISSUE TITLE
Add callback to sizeColumnsToFit()

### ISSUE THREAD

**Issue by roberteles** [ceolter/ag-grid#1033]
I would like to propose adding a callback function for `sizeColumnsToFit()` as a quick solution for the auto width functionality. 

In this way, users could more precisely animate in or out the views needed to hide the snapping/jumping of columns that happens with the grid.

On another note, thank you very much for all your hard work you've done - you have saved countless of developer hours for so many people!

**Comment by ceolter** [comment]
i don't understand what you mean. what would this callback function look like?

"On another note, thank you very much for all your hard work you've done - you have saved countless of developer hours for so many people!"
=> thanks!!! don't forget to buy a license for the enterprise version!!

**Comment by roberteles** [comment]
No need to check this anymore, as it seems that `sizeColumnsToFit` works a lot better in conjunction with `onGridReady` within the latest releases.

The callback I was referring to was a function passed as a parameter to `sizeColumnsToFit` (the reason of it being to have a clear indication of when `sizeColumnsToFit` actually ended - in my personal example, I used to fade out an overlay that was hiding the whole grid).
