### ISSUE TITLE
Add/Remove Column

### ISSUE THREAD

**Issue by randdusing** [ceolter/ag-grid#1034]
Is it possible to add these methods to the column API?

I know I can just reset the column definitions, but this means saving general state, filter state, sorting state, etc. I'd like to be able to add some columns, put the grid into edit mode, submit the form, remove the columns / return back to the original grid state with ordering, filtering, etc intact.

**Comment by ceolter** [comment]
that's what setting columns visible / hidden is intended for.

**Comment by randdusing** [comment]
My grid dynamically adds columns based on search results. If I just use show/hide, the column list will grow way too big.

**Comment by ceolter** [comment]
not a simple change, so afraid i can't just 'add it in', as the columns have their fingers everywhere eg pivot, group, sort, filter, pin, virtualisation, more, more,  . . . . . so it's more than 10minutes work :(

right now i'm trying to do a sweep and pick up easy items to fix, before i launch into the next large item, which is revamp the infinate pagination. an items such as 'add / remove colums at will' is a larger item i'd need to priorities with other items.

**Comment by hi2u** [comment]
Is there still no way to delete a column?

**Comment by MarkoCen** [comment]
I used `gridApi.setColumnDefs(newDefs)` to pass in new column definitions

**Comment by aadithya68** [comment]
Using gridApi.setColumnDefs(newDefs) appends new columns and does not replace the set
