### ISSUE TITLE
Grouped Row Doesn't have data object

### ISSUE THREAD

**Issue by randdusing** [ceolter/ag-grid#1039]
I'm using the data object to store properties on ungrouped rows and would like to do the same on grouped rows. But it looks like a grouped rows data object is set to null. Even after modifying this value in code, Angular isn't able to pick up the changes. Any reason the whole rowNode object can't be added to the $scope rather than just the data property?

**Comment by ceolter** [comment]
fair point. i've just added rowNode to the scope, will be in the next release.

**Comment by randdusing** [comment]
Awesome thanks!
