### ISSUE TITLE
[FEAT] Make column headers template based

### ISSUE THREAD

**Issue by z-boy** [ceolter/ag-grid#104]
Developers might want to have e.g. the sorting icons displayed after the colmuns "displayName" instead of before. If the sorting header would be e.g. "template based", developers would have more flexability in order to be able to overwrite such templates to change the desired layout.

**Comment by ceolter** [comment]
Template for header, or something similar, sounds good to me.

**Comment by wrybit** [comment]
Hi, would this enable me to rearrange/modify the parts inside of a header cell?
[Name] [orderIcon] [-dynamic space-] [filter (contect menu+active info) at one icon]

Greez Jens

**Comment by ceolter** [comment]
yes

**Comment by ceolter** [comment]
header templates were released a few months ago.
