### ISSUE TITLE
Side scrolling and render bug

### ISSUE THREAD

**Issue by Ruud-cb** [ceolter/ag-grid#1041]
Hi,
I see you just released v5.0.6, I'm just switching to this from angular ui grid, sad to see it has bugs.

I think the plunker explains everything, when scrolling from left to right the data disappears. Same goes for initial rendering of the items, not everything is rendered until scrolled a bit.
https://embed.plnkr.co/w9ppmvKejR0QVr7CFAMb/

V5.0.0 seems to have the same issue.
tracking it down, with the current angular/jquery versions in the plunker, there is a difference between release of 5.0.0-alpha.3 and release of 5.0.0-alpha.1
On alpha 1, all columns are stacked on the left, on top of each other, but the data renders correctly.
On alpha 3 the issue started to appear, where the columns are correct but the rows are not rendered correctly when side scrolling.
Since it is working on your website I guess it has to do with a angular release.

**Comment by Ruud-cb** [comment]
Oh wauw, as you see in my plunker, I've set colId for every column, seems like it conflicts with something. removing or changing it's name resolved the issue.
I'll leave it open if you think it is necessary to write a fix or console error for this?

**Comment by outofgamut** [comment]
What exactly is "colld"? I'm having the same issue and would love to know your resolution. Thanks!

**Comment by Ruud-cb** [comment]
The library adds a colid to each header column, assigning my own colid gave errors because it probably doesn't know anymore where to put the data. So just don't define a `colid` in your colDefs objects.

**Comment by ceolter** [comment]
colId should be strings, not numbers. update your plunker to use strings and it works perfect.
