### ISSUE TITLE
[sort] Multiple Sort Icons

### ISSUE THREAD

**Issue by randdusing** [ceolter/ag-grid#1042]
Could numbers be added to the sort icon to show what order the columns are being sorted in?

**Comment by ceolter** [comment]
it's on my list of things to do. not necessarily numbers, but configurable icons, you can add numbers if you wish, or multiple arrows. anyway - not sure when, but will get to it.

**Comment by randdusing** [comment]
Cool, thanks for the update.

**Comment by seanlandsman** [comment]
tracked by AG-132
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by ceolter** [comment]
this is now done. will be in next release. numbers appear beside the sort icons. if you want something else (eg icons) then you can achieve this using your own header component.
