### ISSUE TITLE
error when tabbing to off-screen cell in edit mode

### ISSUE THREAD

**Issue by scott-census** [ceolter/ag-grid#1044]
Plunker here: https://plnkr.co/edit/Yk3mbUCJBoqsK6LWAVfZ?p=info

The problem seems to be in RowRenderer.moveFocusToNextCell, when there is a virtual column that has a null value. It gets nextRenderedCell when the cell is not rendered, and then tries to check isCellEditable of that null object.

Works to tab across as long as you are not in edit mode.

I could work around, I think, by insuring that cell values are never null, but that is a valid value in other cases.

Great library, by the way. We are working on getting the Enterprise license, not because we need the features, but because it's worth supporting.

**Comment by ceolter** [comment]
i can reproduce this on the main demo page - when you tab on the last column, it should wrap to the first column of the next row. if it's the same issue, then it's not related to null values.

**Comment by ceolter** [comment]
workaround for now would be to disable column virtualisation

**Comment by ceolter** [comment]
ok fixed. will be released soon (today or tomorrow). i'm just finishing a sweep of bug fixes.

**Comment by ceolter** [comment]
```Great library, by the way. We are working on getting the Enterprise license, not because we need the features, but because it's worth supporting.``` thank you very much, I look forward to your order :)
