### ISSUE TITLE
Column Header Sizing

### ISSUE THREAD

**Issue by randdusing** [ceolter/ag-grid#1045]
Autosized column headers become cut off when sorting or filtering icons are added. It would be nice if we had one of the options below:

1. A padding parameter to manually adjust for this
2. Ag-grid automatically pads for this (or a flag to enable it)
3. Automatic resize on header size change. I'll probably use the onFilterChanged and onSortChanged events to make this work in the meantime.

![image](https://cloud.githubusercontent.com/assets/6188656/17263490/004d36c4-55a7-11e6-9b79-1f5b26e5e141.png)

**Comment by ceolter** [comment]
will be in next release. 

added gridOption.autoSizePadding, to specify number of pixels to add to calculated width.

**Comment by randdusing** [comment]
I think it would be better to just have a flag for whether filter and sort icon widths should be included. If I resize the column after the icons appear, the column width increases even more with the new option.
