### ISSUE TITLE
Off-screen columns not autosizing

### ISSUE THREAD

**Issue by nareshbhatia** [ceolter/ag-grid#1047]
I took the auto sizing code right off of [this example](https://www.ag-grid.com/javascript-grid-resizing/index.php):

```
function autoSizeAll() {
    var allColumnIds = [];
    columnDefs.forEach( function(columnDef) {
        allColumnIds.push(columnDef.field);
    });
    gridOptions.columnApi.autoSizeColumns(allColumnIds);
}
```

However, unlike the example, which has only 10 columns, my grid has 30 columns - so there is a horizontal scrollbar. What I am finding is that the code above autosizes the columns that are on the screen, but the columns that are off-screen are not autosized. Am I missing something?

**Comment by Fudoshiki** [comment]
same issue

**Comment by tystol** [comment]
The docs need updating. But @ceolter is doing a damn good job with his limited time. I think the least we can all do is search the issues before opening new questions:
https://github.com/ceolter/ag-grid/issues/1020

**Comment by nareshbhatia** [comment]
@tystol, I did a search before logging the issue, but missed #1020 - my bad. Will be more careful in the future. Really appreciate your help on this. Thanks.

**Comment by ceolter** [comment]
All good in the hood :)
