### ISSUE TITLE
FilterParams columnRenderer and Searching in older version 

### ISSUE THREAD

**Issue by santosh-k1** [ceolter/ag-grid#1048]
Hi, Is it possible to use enableFilter: true for column hide show/ Sorting... i want to filter grid column name .. it could be use for hide and how.. if yes than i can do this.

**Comment by santosh-k1** [comment]
instead of 25, 30, 40, 50 in the box i want to display the column name and checked and unchecked filter / hide show the column list ![ag-grid-sorting](https://cloud.githubusercontent.com/assets/4470369/17319216/b6e550f6-58a9-11e6-8c1c-2b859a7095ca.gif)

**Comment by ceolter** [comment]
i think you are asking about create your own custom filter??

what you are asking for is not possible with the provided filters. however you can build your own one following the documentation here:
https://www.ag-grid.com/javascript-grid-filtering/index.php
