### ISSUE TITLE
groupHideGroupColumns not always respected when grouping

### ISSUE THREAD

**Issue by RobHarrisAZ** [ceolter/ag-grid#1050]
When grouping via the column menu or the tool panel, this setting is respected and the column is left visible in the grid.  When grouping via drag and drop, the column is hidden, counter to the setting on the grid properties.

**Comment by RobHarrisAZ** [comment]
Possibly related but if you drag a column that is not enabled for grouping into the grouping drop target, it hides the column.  In fact, if you drag a column away from the column header it seems to hide the column.

**Comment by ceolter** [comment]
change is v4.0.x, see change log

```Took out property groupHideGroupColumns, if you don't want a column to be shown, just hide it. This feature was not necessary and caused complexity in the design.```

this property is not mentioned in any of the docs.

re the second query, if you drag a column out of the grid, it hides. regardless of where you drag it to. you can override this with property ```suppressDragLeaveHidesColumns```
