### ISSUE TITLE
Groups are not recomputed upon inline edit

### ISSUE THREAD

**Issue by SoyYoRafa** [ceolter/ag-grid#1055]
Hi,

Groups are not recomputed if the field changes via inline editing. I didn't dig deep but it must be because groups are not recomputed during a view refresh. I am happy to make an API call to have groups recomputed in the cellValueChanged event handler. I found refreshGroup() in the [API documentation](https://www.ag-grid.com/javascript-grid-api/index.php). However, no such function exists either. Issue occurs in 5.0.7 and 4.2.9.

**Comment by ceolter** [comment]
see the last example on this page on the expected way to do it:
https://www.ag-grid.com/javascript-grid-refresh/index.php

```api.recomputeAggregates();```
