### ISSUE TITLE
Bottom of the grid dances non-stop

### ISSUE THREAD

**Issue by derekperkins** [ceolter/ag-grid#1056]
For months now, the options at the bottom of my grid are in constant motion and I can't figure out why.

![image](https://media.giphy.com/media/3o7TKuXMtxVNqPFEsM/giphy.gif)

**Comment by derekperkins** [comment]
@tannerlinsley

**Comment by outofgamut** [comment]
I've noticed this as well, but I adjusted my browser's zoom to 100% and it stopped.

**Comment by derekperkins** [comment]
@outofgamut Interesting, that solved it for me too. I'm guessing that there is some kind of rounding error causing that on different zoom levels? This still is an issue that should be handled by the grid.

**Comment by ceolter** [comment]
this happens at zoom levels for me also. i believe it is a scaling issue inside chrome, where chrome is reporting the wrong height when it is scaling. i am not able to fix - but welcome if anyone has any insight?

to see the problem, put a print statement into the code as follows (it's just a print, so if you are not building ag-Grid, then just hack in the print statement):
```
    private layoutHeightNormal(): boolean {

        var totalHeight = _.offsetHeight(this.eGui);
        var northHeight = _.offsetHeight(this.eNorthWrapper);
        var southHeight = _.offsetHeight(this.eSouthWrapper);

        var centerHeight = totalHeight - northHeight - southHeight;
        if (centerHeight < 0) {
            centerHeight = 0;
        }

        if (this.centerHeightLastTime !== centerHeight) {
            console.log(`height last = ${this.centerHeightLastTime}, height this = ${centerHeight}, totalHeight = ${totalHeight}, northHeight = ${northHeight}, southHeight = ${southHeight}`);
            this.eCenterRow.style.height = centerHeight + 'px';
            this.centerHeightLastTime = centerHeight;
            return true; // return true because there was a change
        } else {
            return false;
        }
    }
```
it's in borderLayout.ts

i then go to the main demo page and zoom down to 75%

in my tests, the statusBar (the south panel) is 22 pixels high. that's what the CSS sets it to. that's also what is reported by the dev tools when i inspect the element. however for some reason Chrome is alternating between reporting 21 and 23 pixels for clientHeight.

if anyone has a solution, am happy to apply. but given it's chrome reporting the wrong numbers, not sure what i can do.

i tried it in Canary btw, and that does not have the issue.

**Comment by ceolter** [comment]
no update, so closing
