### ISSUE TITLE
Row CSS Classes

### ISSUE THREAD

**Issue by randdusing** [ceolter/ag-grid#1057]
If using tree data, the row css classes are ag-row-group, ag-row-level-0, etc. Wouldn't it make more sense to have ag-row-tree, ag-row-treeLevel-0, etc? Currently I have to set a flag whether the grid is in tree mode or group mode and use that to adjust styles.

**Comment by ceolter** [comment]
i'd rather not use ag-row-tree, ag-row-treeLevel-0, as the only piece that is different between tree and non-tree is, well, whether you provide the data grouped or not. how the grid renders is the same after that.

as you say you can apply a flag yourself if you want the grid with different css. so this isn't an issue??
