### ISSUE TITLE
It appears two scroll bar in grid

### ISSUE THREAD

**Issue by openseah** [ceolter/ag-grid#1059]
Repro Steps: 
   1. click on filter option
   2. resize the browser

See the following screenshot

![qq 20160804153241](https://cloud.githubusercontent.com/assets/10209354/17393913/01fefd66-5a59-11e6-9de6-13d75d9ec5e7.png)

@ceolter Do you know how to solve this ?

  Thanks.

**Comment by ceolter** [comment]
no solution to it. however this is very edge case - why would someone decide to resize your browser if they are just about to change a filter? doesn't sound like normal user flow to me.
