### ISSUE TITLE
AutoSize All Columns

### ISSUE THREAD

**Issue by randdusing** [ceolter/ag-grid#1060]
I see that ```autoSizeAllColumns()``` is a part of ```columnController``` when examining the default main menu items. Anyway that can be exposed to the columnApi? Right now I'm doing something like this:

```
var keys = _.map($scope.gridOptions.columnApi.getAllColumns(), 'colId');
$scope.gridOptions.columnApi.autoSizeColumns(keys);
```

**Comment by ceolter** [comment]
done. will be in next release.

**Comment by randdusing** [comment]
A couple years late, but I noticed the documentation doesn't cover this
