### ISSUE TITLE
AngularJS scope - value not in $scope

### ISSUE THREAD

**Issue by jarek-jpa** [ceolter/ag-grid#1063]
Hi,
Looking at the example at: https://ag-grid.com/angular-grid-cell-rendering/index.php (section complex html, with Angular JS) - there is a mysterious "{{value}}" binding which suggests "value" would be in $scope. This is however not the case, all I can see is the "data" object. Is it a bug?

The "data" object is generally fine, as long as we know precisely what we are looking for. But for general renderers it reduces reusability.

**Comment by randdusing** [comment]
I think the documentation is incorrect. There's only a single scope per row, so a generic value property wouldn't make sense.

You could do something like this:

```
column.cellRenderer = function (params) {
  return '{{data[\'' + params.colDef.field + '\']}}';
};
```

**Comment by jarek-jpa** [comment]
Thanks with the tip, it should work.

But with the scope it isn't true - there is separate scope for cells - look e.g. here: https://ag-grid.com/javascript-grid-cell-template/index.php - all the cells have the standard .ngScope

**Comment by randdusing** [comment]
The angular plugin for Chrome Tools isn't working for me on the example page, but I do see the ng-scope class on each cell. But each cell is using the same $scope since the $id property is the same. If there was a separate scope for each cell, I think the grid would be much slower.

**Comment by jarek-jpa** [comment]
Hmm, it seems you are right.
Tracked down here: https://github.com/ceolter/ag-grid/blob/d6b340ceb2cda946a4beb930b7c2a90b90889f54/src/ts/rendering/renderedRow.ts#L534

So clearly a documentation bug :)

**Comment by ceolter** [comment]
i don't know how you got the link above, it's old data, the correct cellRendering docs are:
https://ag-grid.com/javascript-grid-cell-rendering/index.php

as per discussion above, there is one scope per row. there was never a scope per cell.

if you want to reuse your cellRenderer, bind it with the data, eg:

```
function myRenderer(field, params) {
  return '{{data.'+field+'}}';
}

colDef = {
  cellRenderer: myRenderer.bind(this, 'firstName');
}
```
