### ISSUE TITLE
ag-Grid 5.0.7 Enhancement: now colId's can be numbers, not just strings

### ISSUE THREAD

**Issue by stephanjust** [ceolter/ag-grid#1064]
Versions used:
    "ag-grid": "5.0.7",
    "ag-grid-ng2": "5.0.0",

```Columns``` use strings for their ids even if the original ```ColDef``` provided an id as a number. As inspected in the chrome developer console:
```
column
    colDef
        colId: 84185401002
    colId: "84185401002"
```
This means that certain checks inside of ag-grid will fail when providing the ids of the original ```ColDef```, such as in getColumn:
```
ColumnController.prototype.getColumn = function (key, columnList) { // key is a number, columnList contains columns with strings as ids
    // ag-grid code
    
    function colMatches(column) {
        var columnMatches = column === key;
        var colDefMatches = column.getColDef() === key;
        var idMatches = column.getColId() === key;
        return columnMatches || colDefMatches || idMatches;
    }
    return null;
}
```
```colMatches``` always returns ```null```, as ```getColId() === key``` fails for numbers and strings. Using ```==```would obviously be a fix, but I believe that if we supply a number as an id the columns should use numbers as well.

**Comment by ceolter** [comment]
done. will be in next release.
