### ISSUE TITLE
suppressCellSelection on Individual Columns

### ISSUE THREAD

**Issue by randdusing** [ceolter/ag-grid#1065]
It would be nice if cell selection could be suppressed at the column level.

**Comment by ceolter** [comment]
this seems odd to me. excel doesn't suppress cell selection.

if you have an action on the cell selection, why not just suppress the action?

i'm considering if this should be a grid feature, or your application feature.

**Comment by randdusing** [comment]
I think my use case for this is no longer needed in my application, but this is easy to do from the application side anyways via getContextMenuItems and looking for a flag on the colDef.

**Comment by ceolter** [comment]
cool. thanks.
