### ISSUE TITLE
Checkbox Styles

### ISSUE THREAD

**Issue by randdusing** [ceolter/ag-grid#1067]
Currently the checkbox uses images with data URIs to handle the styling of checkboxes. If I want to add a header checkbox, I have to duplicate those data URIs. Or if I just want to change the existing checkbox styles, I have to modify ag-grid code. It would be really convenient if this was done through CSS styles like .ag-selection-checkbox-checked, .ag-selection-checkbox-unchecked, .ag-selection-checkbox-indeterminate.

Seems like a fairly easy change, so I'm open to submitting a PR if you approve the idea. I'll have to reduce the event handlers from three to one and then modify the remaining event handler to use the current class to determine what action to take.

**Comment by domchik** [comment]
I have the same problem

**Comment by ceolter** [comment]
these are changed via the icon configuration
https://www.ag-grid.com/javascript-grid-icons/index.php

**Comment by randdusing** [comment]
Thanks, I missed that part of the documentation.

**Comment by ceolter** [comment]
np!

**Comment by don-bluelinegrid** [comment]
@ceolter 
Niall -

I read through this issue, and understand about how to replace the image icons for checkboxes.

However, my question is a bit different.  It's about why these must be images.  If my application is using a specific styling throughout the application, including for checkboxes, how can I apply that same styling to the row checkboxes?  As a specific example, I am using Bootstrap's styled checkboxes, which are actually complex DOM elements that associate a hidden checkbox input element with a styled label element.  I imagine that many developers use the Bootstrap checkboxes.

However, with the current icon-based approach, it doesn't look like there's a straightforward way to do this.  Of course, I could take a screenshot of the Bootstrap-styled checkboxes in the various states, and then use those images to replace the default icons; but that defeats the purpose of Bootstrap and CSS - if I later decide to modify the Bootstrap styles, I must then create new icons.

Can you provide any straightforward way of applying the Bootstrap checkboxes and behaviors to the row checkboxes in agGrid?

Thanks,
Don

**Comment by ceolter** [comment]
@don-bluelinegrid 
hi Don, the reason for choosing images is that gives greater flexibility on what you can put in there. actually it's not just images, you can stick any html you want in. if you want to use the same look and feel, then the best is to take an image of what you want and use that.

in a perfect world, i'd have both, so you can decide to use images or checkboxes, however that's effort for us and we need to prioritise, and this would be low priority.

btw - it was originally checkboxes - and people requested to make them images!!

**Comment by don-bluelinegrid** [comment]
Niall -

I understand to some extent about the flexibility of images for checkboxes; however, there are a number of downsides that you probably already considered: impossibility of styling with CSS; requirement to have images representing three states (checked, unchecked, disabled); requirement to load the images per row.

Regarding the last one - I've also noticed that when the grid loads row data, I see many many loading requests for the checkbox image, with a URL like this:
```
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAOCAYAAAAfSC3RAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAA2ZpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMy1jMDExIDY2LjE0NTY2MSwgMjAxMi8wMi8wNi0xNDo1NjoyNyAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0UmVmPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDpFQ0VGQkU3ODM4MTFFNjExQjlCQzhERUVDNkNGMzFDMyIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDpBRkJCRDU1MTEyM0ExMUU2ODE4MUUyOTNBNTRGQkIxNyIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLmlpZDpBRkJCRDU1MDEyM0ExMUU2ODE4MUUyOTNBNTRGQkIxNyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ1M2IChXaW5kb3dzKSI+IDx4bXBNTTpEZXJpdmVkRnJvbSBzdFJlZjppbnN0YW5jZUlEPSJ4bXAuaWlkOjIzMkM4M0M1M0MxMUU2MTFCOUJDOERFRUM2Q0YzMUMzIiBzdFJlZjpkb2N1bWVudElEPSJ4bXAuZGlkOkVDRUZCRTc4MzgxMUU2MTFCOUJDOERFRUM2Q0YzMUMzIi8+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8+riMaEQAAAL5JREFUeNqUks0JhDAQhSd7tgtLMDUIyTXF2IdNWIE3c0ruYg9LtgcPzvpEF8SfHR8MGR75hpcwRERmrjQXCyutDKUQAkuFu2AUpsyiJ1JK0UtycRgGMsbsPBFYVRVZaw/+7Zu895znOY/j+PPWT7oGp2lirTU3TbPz/4IAAGLALeic47Ztlx7RELHrusPAAwgoy7LlrOuay7I8TXIadYOLouC+7+XgBiP2lTbw0crFGAF9ANq1kS75G8xXgAEAiqu9OeWZ/voAAAAASUVORK5CYII=
 ```

See attachment, for the full example.  I realize that these images would most likely load from the browser cache, but I have to believe that it would be more efficient to have a DOM-based checkbox element compared to this.

Is the only option to achieve the currently, to create some sort of custom row cell renderer which would put the HTML checkbox into the column cell?

Thanks,
Don
![screen shot 2016-10-11 at 1 39 03 pm](https://cloud.githubusercontent.com/assets/19780097/19281400/1f499cd4-8fb8-11e6-9326-d5c702b71047.png)

**Comment by ceolter** [comment]
the images are not loaded. the images are embedded in the javascritp base64 encoded. i don't know why the browser is reporting to be loading them.

re checkbox - i'm considering having an option 'use standard checkbox instead of images' - might solve both worlds. i appreciate people want to style checkboxes.

**Comment by randdusing** [comment]
Check the Hide data URLs button, and you'll at least not see them :)

**Comment by ceolter** [comment]
@randdusing thanks, good answer for others who ask about this, it has come up before.
