### ISSUE TITLE
TypeError: cellRendererFunc is not a function

### ISSUE THREAD

**Issue by rakeshadak137** [ceolter/ag-grid#1068]
I changed my ag-grid version from 2.3.7 to 5.0.7.
I am using cellRenderer to group my data.
I am getting 'TypeError: cellRendererFunc is not a function' error.
I am using Angular 1.2.8.

Below is my code for gridOptions  :   
`{headerName: "KAM", field: "kam",width: 300, cellRenderer: {
            renderer: 'group'
        }
        },
        {headerName: "Job", field: "job", width: 300},
        {headerName: "Associate", field:"associate",width: 150},
        {headerName: "Sourced", field: "sourced", width: 120},
        {headerName: "InternalSubmit", field: "internalSubmitted", width: 120},
        {headerName: "CvSubmitted", field: "cvSubmitted", width: 120,cellStyle:function(params){
            if(params.value <= 0){
                return {color: 'red'};
            }
            else{
                return null;
            }
        }}`

Its working fine with the older version.
Is there any change for CellRenderer ??

**Comment by ceolter** [comment]
yes there are changes. please check with the examples and docs for the latest version on how to configure the group cell renderer.
