### ISSUE TITLE
How to show context menu when right click on header cell?

### ISSUE THREAD

**Issue by hank7444** [ceolter/ag-grid#1069]
Context menu show only cells are right clicked, has any way can show it when right click on header cell?

or has any function can cell & show context menu manually? thx!

**Comment by ceolter** [comment]
for showing the column menu, use:

```
    public showColumnMenuAfterButtonClick(colKey, buttonElement)
    public showColumnMenuAfterMouseClick(colKey, mouseEvent)
```

the methods differ by where the menu appears.

this is for column menus, hence you pass in the column details so correct options are displayed.

**Comment by hank7444** [comment]
sorry, could you provide a small example to show how to use this two methods? thx :)

**Comment by ceolter** [comment]
sorry, what? think you have a typo in your english?????

**Comment by kuldeepmodi7** [comment]
I am opening this issue , as this is the required business functionality in some cases , Please guide us , how can we open the context menu not column menu on right click of header cell
