### ISSUE TITLE
Allow row templates

### ISSUE THREAD

**Issue by ceolter** [ceolter/ag-grid#107]
Allow row templates, as described here: http://www.angulargrid.com/forum/showthread.php?tid=77

**Comment by nelreina** [comment]
+1

**Comment by AkosLukacs** [comment]
Link broken, maybe this: http://www.angulargrid.com/forum/showthread.php?tid=77

**Comment by ceolter** [comment]
yup, i'll updated the original post.

**Comment by randdusing** [comment]
https://github.com/ceolter/ag-grid/commit/d3567e2255ec33d52c8f3571bfbe152a2af1b5c3 removed row compilation, so now the class directive hack doesn't work anymore. Row templates would be very useful now.

**Comment by ceolter** [comment]
i now compile the columns individually, if we also compiled the row, then the columns get compiled twice.

i could rework how it's done, however that would be aligning the grid with angular 1 - which i don't want to do.

suggestion - use ```processRowPostCreate``` callback to add whatever it is you need to the dom.

then use ```virtualRowRemoved``` event for any cleanup for when row is removed.

**Comment by ceolter** [comment]
you can use callback processRowPostCreate to add functionality to rows.
