### ISSUE TITLE
header cells not aligned when column right pinned + scrollbar in Chrome

### ISSUE THREAD

**Issue by intergalactic-overlords** [ceolter/ag-grid#1070]
When you have a column pinned to the right and a scrollbar in the table, the right header cells aren't aligned to the right body cells.
This bug occurs in Chrome 53. Firefox 47 and Safari 9.1.2 are ok. 

See: https://www.ag-grid.com/javascript-grid-pinning/index.php

**Comment by ceolter** [comment]
don't know what you mean, that example is working fine for me.

**Comment by BamaBoy** [comment]
I have same issue!

**Comment by ceolter** [comment]
ah right, yes i see, top right, the column is slightly out. i'm aware of this. will add it to my list. medium priority.

**Comment by ceolter** [comment]
this was fixed end of last year
