### ISSUE TITLE
Feature: allow to stop "stopEditing" in newValueHandler

### ISSUE THREAD

**Issue by stephanjust** [ceolter/ag-grid#1071]
When using the ```newValueHandler``` you're free to not accept input values and discard them. However, the ```CellEditor``` is still closed even when not accepting the value. This is not always optimal.

Proposal: add a function to stop the propagation of ```stopEditing``` after ending ```newValueHandler```, similar to ```preventDefault``` for HTML elements.

**Comment by ceolter** [comment]
this wont work - as the grid only edits one cell at a time. what do you do if use double clicks on another cell? the editing will be forced to stop.

suggestion - why not put his logic you need into your cellEditor? so cellEditor doesn't stop the editing until after you have the value ready?

**Comment by GurjitDrish** [comment]
using cellEditor can't use navigation keys to change focus location.
Any suggestion pls?

**Comment by GurjitDrish** [comment]
I've fixed this requirement by doing following changes in ag grid js file

    RenderedCell.prototype.onNavigationKeyPressed = function (event, key) {
	        if (!this.editingCell) {
	            //this.stopRowOrCellEdit();      
	            this.rowRenderer.navigateToNextCell(key, this.rowIndex, this.column, this.node.floating);
	            event.preventDefault();
	        } 
	    };


And I would like to suggest AG team to change this event like this. Cause mostly user like to move focus using navigation keys while using edit mode

**Comment by stephanjust** [comment]
> And I would like to suggest AG team to change this event like this. Cause mostly user like to move focus using navigation keys while using edit mode

I highly doubt that (and in fact I know that my users are tabbing through tables constantly) and it also wasn't my original idea. Cosndiering @ceolter 's comment I expected that the new focus is simply not applied, meaning a double click/tab would have no impact (potentially with a visual hint and/or toaster, but that's up to me). I expected this to be in newValueHandler as this is the position where new values are handled, but doing so in the CellEditor itself is just fine (we work around it at the moment by resetting focus on the original field, it's a niche use case for us anyway).
