### ISSUE TITLE
valueGetter and select cellEditor conflict

### ISSUE THREAD

**Issue by lilling** [ceolter/ag-grid#1075]
when I implement to a column field and cellEditor all is good. but when Its cellEditor and valueGetter 'all hell breaks loose! the 'cellValueChanged' event wont fire. 

Im writing in angular 2 if this an important matter regarding this issue.

**Comment by ceolter** [comment]
you need either field or newValueHandler set on colDef for editing to work

maybe you should be using newValueHandler instead of listening on the event
