### ISSUE TITLE
Not applying CSS definitions

### ISSUE THREAD

**Issue by jaden210** [ceolter/ag-grid#1076]
The datatable is not recognizing any CSS. I have tried putting it inline, on an external ref sheet, and the reference in the index.html. All the row data is floating to the left of the screen. This is on angular2 RC.4 using the cli. ag-grid v5.0.7 and reference tags as defined on https://ag-grid.com/javascript-grid-styling/index.php

**Comment by ceolter** [comment]
this is not a grid issue - the grid is standard DOM. the classes are applied to the grid (there is no way to  have the grid without the classes) so your browser is not apply the CSS. the only thing that can result in this is you are not loading the css. or maybe your application is overriding the css somehow.

**Comment by nidhibaheti1991** [comment]
I had the same issue and the css was not appearing properly. Fixed it by adding the following in .angular-cli.json. (Reference - https://www.ag-grid.com/ag-grid-angular-angularcli/#gsc.tab=0) 

// .angular-cli.json
"styles": [
    "../node_modules/ag-grid/dist/styles/ag-grid.css",
    "../node_modules/ag-grid/dist/styles/theme-fresh.css"
],
