### ISSUE TITLE
[Bug] Move Column header => Image of drag header of column does not in coordinates of mouse

### ISSUE THREAD

**Issue by namminh2005** [ceolter/ag-grid#1080]
When i have grid is in below of Screen Browser
I move column and image of drag header cannot in coordinates of mouse
Please see image attachment
![untitled2](https://cloud.githubusercontent.com/assets/9007173/17691984/caff5d02-63c1-11e6-9552-d5da9c0a8b40.png)
![untitled](https://cloud.githubusercontent.com/assets/9007173/17691987/d23e1c7a-63c1-11e6-9a3d-feba51ff936b.png)

Do you have any Plan to fix it?
Thank you

**Comment by ceolter** [comment]
cannot reproduce.

i moved the image in my demo down, and tried both with scrolling browser and not scrolling browser, either way the dragging icon appeared in the correct location.

your app must be interfering with the css ????

if you can reproduce in a plunker or similar, i can look. however not reproduce, not fix :(

![image](https://cloud.githubusercontent.com/assets/6539563/17703375/5b0df3ca-63c9-11e6-92b8-85082d417ae7.png)

**Comment by namminh2005** [comment]
Thank you for reply it soon.

I see your picture and i think you should increase height of your Area have border is Green. It need have height > height of screen of browser.

I use https://github.com/ceolter/ag-grid-ng2-example and create div have height > height of screen of browser.

Scroll browser to see grid.
Move Header column and bug appear :(

Best regards.
Thank you for ag-grid

**Comment by namminh2005** [comment]
I does not know how to create plunker with angular2 + ag-grid.
So i zip source code and send you.
This source is simply. It is source on [https://github.com/ceolter/ag-grid-ng2-example](url) and i add new dive have height > max height of my browser.

Can you download and check it?
[https://drive.google.com/file/d/0B8XOJHcROefZUi1GSXd2dEFrUEU/view?usp=sharing](url)

![capture1](https://cloud.githubusercontent.com/assets/9007173/17705832/0070c39e-6404-11e6-834a-938bad9677b4.PNG)

**Comment by ceolter** [comment]
no need, i have it reproduced now. give me 15min.

**Comment by namminh2005** [comment]
Thank you very much :)

**Comment by ceolter** [comment]
ok fixed now. will be in next release.

https://github.com/ceolter/ag-grid/commit/c3dcfb7bf6cd6fe8629aa7ddc25de202efd2ef08

**Comment by namminh2005** [comment]
ok, thank you very much
