### ISSUE TITLE
Column.visible always true even when column grouping is used and the column has columnGroupShow: 'open'

### ISSUE THREAD

**Issue by m4urer** [ceolter/ag-grid#1082]
I'm not sure if this is a bug or a design decision, but when column grouping is used, the columnApi.getColumn is not showing any attributes indicating this, and the visible attribute is always true, even if the column is not showing.
I'd like to have visible:false when it's hidden (group is closed and the column is columnGroupShow: 'open'), or maybe some group related attributes, like groupHeaderName, columnGroupShow, and columnVisible (to know if it's currently visible or not).

Thanks!

**Comment by ceolter** [comment]
to see if column is grouped, aggregated or pivoted, see if column is in any of these lists:
columnApi.getValueColumns()
columnApi.getRowGroupColumns()
columnApi.getPivotColumns()

or use the following column methods:
column.isRowGroupActive()
column.isPivotActive()
column.isValueActive()

**Comment by m4urer** [comment]
The first 3 methods are returning an empty array in every case, and the las 3 ones always false.. should they?
Please take a look : [codepen](http://codepen.io/m4urer/pen/OXqkRq)

**Comment by ceolter** [comment]
yes, because  you have no grouping, pivot or aggregation active.
