### ISSUE TITLE
Filter options not "drilled down" when a filter is applied to a column

### ISSUE THREAD

**Issue by connorblack** [ceolter/ag-grid#1083]
<img width="1093" alt="screenshot 2016-08-16 15 25 16" src="https://cloud.githubusercontent.com/assets/1903789/17712916/39e8bce6-63c6-11e6-8c31-0af27ef4f69e.png">

I would expect the behavior to be that when a column has a filter applied to it and you go to apply another filter to a column, the only filter options showed are ones that are applicable (i.e. only 2002 should be shown in the above screenshot).

Is there any way to easily configure this?

**Comment by ceolter** [comment]
i've just fixed this. it should happen by default. however if leave out teh filterParams, it doens't work. so put in a blank filterParams.

see the main demo on ag-Grid.com (view source), country and language are working, but game name is not. this will be fixed in next release.
