### ISSUE TITLE
Inconsistent file name references

### ISSUE THREAD

**Issue by arkon** [ceolter/ag-grid#1085]
If you have `forceConsistentCasingInFileNames` set to `true` in tsconfig, you'll get the following error:

```
File name '[...]/node_modules/ag-grid/dist/lib/rowControllers/iDataSource.d.ts' differs from already included file name '[...]/node_modules/ag-grid/dist/lib/rowControllers/iDatasource.d.ts' only in casing
```

**Comment by ceolter** [comment]
i put that in, but doesn't warn me. maybe it only works on linux or max? (i'm using windows 10)

**Comment by arkon** [comment]
I'm on Windows 7. But I think it's because you have imports like `"../iDataSource"` and `"../iDatasource"`.

**Comment by ceolter** [comment]
yes i know, and i've just fixed that, thanks for raising.

what i mean twas, i set forceConsistentCasingInFileNames=true, and it didn't warn me.
