### ISSUE TITLE
unable to refer typings on Linux

### ISSUE THREAD

**Issue by mrudangit** [ceolter/ag-grid#1087]
get the below error. 
node_modules/ag-grid/main.d.ts(99,15): error TS2307: Cannot find module './dist/lib/rowControllers/inMemory/inMemoryNodeManager'.

It works on windows because file name, folder names are case insensitive on Windows , however on Linux they are case sensitive. 

using ag-grid and agrid-ng2 5.1.0

**Comment by ceolter** [comment]
releasing in next hour, will be fixed. thanks for raising.
