### ISSUE TITLE
Customise the loading panel

### ISSUE THREAD

**Issue by ceolter** [ceolter/ag-grid#109]
The loading panel content should be customisable, either the text, or user provides a template.

**Comment by jettagozoom** [comment]
I would like to add my own spinner icon. Would be nice to add, as part of the customizable icon, a loading icon.

**Comment by oh-wo** [comment]
Hi Ceolter,
Thanks for such a fantastic library. I have a similar wish to @jettagozoom, so if you do implement this feature, `user provides a template` would be very helpful. 

Thanks again!

**Comment by ceolter** [comment]
today's release has customisable loading panel.
