### ISSUE TITLE
Expandable Rows - with Parent Row

### ISSUE THREAD

**Issue by cah-chaitanyamunagala** [ceolter/ag-grid#1095]
I have a requirement to Display a parent row (data in all columns) with a column dedicated to Group Expand/Collapse Icon. There are no aggregations on any of the columns that's displayed as parent row.

When expanded it should show other items belonging to that group with same list of columns. 

Can this be achieved with 5.0.7 version of ag-grid-enterprise? 

I looked at #43, it's kind of related but I don't need custom columns for the group items.

Thanks.

**Comment by ceolter** [comment]
i don't fully understand the questions. however new feature of fullWidth rows was introduced:
https://www.ag-grid.com/javascript-grid-master-detail/index.php

if this doesn't do what you want, maybe you can frame the question by describing the limitation you have with the fullWidth feature?

**Comment by priyanka813** [comment]
@ceolter 
Hello, 
I am trying to implement something like https://ag-grid.com/javascript-grid-tree/index.php.
But, I am not able to expand rows and also issue with groupExpanded and groupContracted icons.

Please help me to out these.

**Comment by ceolter** [comment]
if you provide a plunker, someone can help. otherwise, with the info above, i have no idea. maybe try comparing to the provided examples for guidance???

**Comment by priyanka813** [comment]
I am trying to do  expand and contracted rows.
I have shared with you screenshot.

![rowgrouping](https://cloud.githubusercontent.com/assets/19928173/18194864/30992a0c-7106-11e6-9ca5-aba6802e1751.png)

But problem is, I am not getting plus and minus icons. And here group c is expanded by default but how can i expand group A and Group B ?

My code as per below.  

```

var gridOptions = {
        columnDefs: columnDefs,
        rowData: rowData,
        debug: true,
        getNodeChildDetails: getNodeChildDetails,
        icons: {
              groupExpanded: '<i class="fa fa-minus-square-o"/>',
              groupContracted: '<i class="fa fa-plus-square-o"/>'
    };
 getNodeChildDetails(rowItem) {
        if (rowItem.group) {
            return {
                group: true,
                expanded: rowItem.group === 'Group C',         
                children: rowItem.participants,
            };
        } else {
            return null;
        }
    }

```

**Comment by ceolter** [comment]
```I am not getting plus and minus icons``` => you probably don't have groupCellRenderer for one of your columns.

as for expanding, the code you need to modify is this:
```expanded: rowItem.group === 'Group C'```

**Comment by priyanka813** [comment]
thanks for answer.
