### ISSUE TITLE
How to set the header's style?

### ISSUE THREAD

**Issue by arrinhzh** [ceolter/ag-grid#1097]
How to set the header's style?

**Comment by ceolter** [comment]
use colDef.headerClass, or provide your own header template.

**Comment by HariBabuThubati** [comment]
@ceolter : How can I add ICON only in the header and should be clickable and arrow turn down in group by functionality.

**Comment by HariBabuThubati** [comment]
@ceolter : i added the icon to header by using headerCellRenderer , i am trying to call one method by clicking on that Icon , can you please suggest.
