### ISSUE TITLE
Saving ColumnDef to Server

### ISSUE THREAD

**Issue by alhweiti** [ceolter/ag-grid#1098]
Hi Niall/Ag-Grid Admin,

I am working on a solution to save grid definition to the server in encrypted field. So basically users can save their own views/griddef..
I looked at the API trying to find where the updated columnDef is, but can't find it.

I basically need to save how the grid has been changed on runtime to server. (If user changed width, grouping, sorting, filtering, column orders, etc). I wanted to avoid to listen to all events/interactions from user...
I tried the following:
gridOptions.columnApi.getAllGridColumns() ==> doesn't have grouping
and 
gridOptions.api.gridOptionsWrapper.getColumnDefs(); ==> same as initial columndef

Can you please let me know what is the best way to access the runtime  updated columndef so I can save it to server, and if it's not being updated, what would be the best way to do this?

Thanks,

Ahlam

**Comment by killyosaur** [comment]
Are you talking about the columns' state? If so there are functions on the column api for getting, setting, and resetting the column state, you just need to save off the state and reapply on grid ready. Check the documentation: https://www.ag-grid.com/javascript-grid-column-api/index.php

There are also functions for saving the sort order models and filter models, they are in the main grid api: https://www.ag-grid.com/javascript-grid-api/index.php

There is also a function for setting column defs if you really want to be altering the definitions themselves (though you really shouldn't need this unless the defs are changing and not just their state)

**Comment by alhweiti** [comment]
Thanks Killy but I don't think that would allow me to save the way users rearranged their columns (column display order). Also, I was looking to save width and anything basically the user can change from UI to the database. So, I guess the issue is, the grid allows to setcolumndef but it doesn't allow to generate it back, after user interactions, to give users ability to save their customized grid, so it can be saved in server side for later retrieval, so users don't have to make same changes again, when they open the grid in future.

**Comment by killyosaur** [comment]
The set and get column state in the column api will do exactly what you are asking. I should know, I do it in my app :)

**Comment by alhweiti** [comment]
Perfect. It's working out for me.
Thank you.

Ahlam

**Comment by ceolter** [comment]
@killyosaur thanks for answering :)

**Comment by germanger** [comment]
@alhweiti  mind telling me how? maybe pasting the relevant parts of the code?

**Comment by alhweiti** [comment]
Use this:
save this to server...
JSON.stringify(gridOptions.columnApi.getColumnState())


Get it from server then apply using this:
var viewDef= CALL SERVER TO GET VALUE
 gridOptions.api.setRowData(mydata);
 gridOptions.columnApi.setColumnState(JSON.parse(viewDef));

for filter:
JSON.stringify(gridOptions.api.getFilterModel())
sort model..
JSON.stringify(gridOptions.api.getSortModel())

and saame apply:
var sortDef= CALL SERVER TO GET VALUE
var filterDef =CALL SERVER TO GET VALUE
   if (sortDef != null) gridOptions.api.setSortModel(JSON.parse(sortDef));
 if (filterDef != '') gridOptions.columnApi.setFilterModel(JSON.parse(filterDef));

all the set methods should be done **After**you call the 
 gridOptions.api.setRowData(mydata);

Hope it helps..

Ahlam

**Comment by germanger** [comment]
Thank you very much.

In summary:

         gridOptions.columnApi.getColumnState();
         gridOptions.columnApi.setColumnState(json);

        gridOptions.api.getSortModel();
        gridOptions.api.setSortModel(json);

        gridOptions.api.getFilterModel();
        gridOptions.api.setFilterModel(json);

I also used this:

       columnDefs: [...],
       onGridReady: function() {
            $scope.gridOptions.api.addGlobalListener(function(type, event) {
                if (type.indexOf('column') >= 0) {
                    // Save columns state ...
                }
            });
       }

to save the columns state each time they change

**Comment by pupeno** [comment]
Hello, 

The information in this issue doesn't seem to be working for me. I set the state in on grid ready but it has no effect. Setting the state in exactly the same way in another callback has the expected behavior, but not grid ready. 

I'm using the ReactJS version. Does that change anything?

**Comment by VaishaliJain09** [comment]
I am also using React. Can anyone please tell me if there is any event fired after data changes in ag-grid?
I am able to get the state but unable to set it as I don't know where I can do so.

Thanks

**Comment by siddharthdawar** [comment]
@VaishaliJain09 Please refer to this: [ag-grid events](https://www.ag-grid.com/javascript-grid-events/?framework=javascript#gsc.tab=0)

**Comment by Pradeepg21** [comment]
Hi,
getColumnState() is only returning the children columns state and I want function which will return the columns including the groups for ag-grid
**example**: I have scenario
**_saved state is    Array(14)
					0:
						children:Array(13)
						0:{headerName: "Unit1", field: "Unit1", enableRowGroup: true, enablePivot: true, hide: false}
						1:{headerName: "Unit2", field: "Sub Business Unit2", enableRowGroup: true, enablePivot: true, hide: false}
						...
						...
						2
						__proto__:Array(0)
						headerName:"Main Header"
						__proto__:Object
					1:{headerName: "Header2", children: Array(4)}
					2:{headerName: "Product1", children: Array(24)}
					3:{headerName: "Product2", children: Array(41)}
					...
					..._**
so if I change the unit1 with unit2, I should get the whole output as above with grouping and only change in uint1 and unit2.
I tried below methods also, but no help:
getColumnGroupState()
getAllDisplayedColumns() etc

Please help me with the proper method as per my requirement.

Thanks,

**Comment by Prithivraj200** [comment]
Hi,

   Any update on retaining the groups for ag-grid as mentioned by @Pradeepg21
