### ISSUE TITLE
Floating Rows with aggregation sum

### ISSUE THREAD

**Issue by kamisialke** [ceolter/ag-grid#1100]
I need sum of rows in floating Rows, how can i use built in aggregation sum function  so that  if filter are apply on that row it will update that sum .

If it is not support and i have created my on sum function, but the problem in this case is that how can i trigger my sum function when filter are apply on table?

**Comment by ceolter** [comment]
use the events to know when the filters have changed. then you can use forEachNodeAfterFilter to access the nodes for your aggregation.
