### ISSUE TITLE
Disable right pinning

### ISSUE THREAD

**Issue by vsanat** [ceolter/ag-grid#1102]
hi guys,
Is it possible to only disable right pinning feature?

thanks

**Comment by ceolter** [comment]
no. but good point. i'll add to my list.

**Comment by vsanat** [comment]
ok, thank you.

**Comment by aodinok** [comment]
Hi guys, why this was closed?

**Comment by RajeevKashyap** [comment]
I have the same issue. Could anyone help on this. How to disable right pinning in aggrid?

**Comment by tylerstephens814** [comment]
Still having this issue. Is there a solution?

**Comment by whtitefall** [comment]
Hi, 

i'm trying to find the same solution to this problem, 

the following threads don't provide an anwer, do we have a proper solution to this issue ? 

https://github.com/ag-grid/ag-grid/issues/3558
https://github.com/ag-grid/ag-grid/issues/3557

**Comment by madmandrew** [comment]
Any news on this still doesn't seem possible?
