### ISSUE TITLE
All data read from the ag-grid

### ISSUE THREAD

**Issue by mcarkv** [ceolter/ag-grid#1104]
Hi,
I am trying to read the all cell values from the ag-gid, but only able to read arround 20 records. Its seems like that only visible data able to read.

Please let me know, how to read the all data available on Grid.

**Comment by ceolter** [comment]
ag-Grid only renders what you see on the screen. if you want to render everything, set rowBuffer = <a big number>, eg gridOptions.rowBuffer=99999999

that way, all rows will get rendered, however it will be a slower grid, especially if you have many rows. if thousands of rows, expect your browser to run out of memory.
