### ISSUE TITLE
throw exception after set forPrint as true

### ISSUE THREAD

**Issue by ricklxm** [ceolter/ag-grid#1107]
I'm using it in angular2. And the version is: ```` "ag-grid": "^5.2.0",
     "ag-grid-ng2":` "^5.2.0"````.
The gridOptions is: 

        this.gridOptions = <GridOptions>{
        	forPrint: true,
        	columnDefs: this.columnDefs,
        	rowData: this.rowData,
        	rowSelection: 'multiple',
        	enableColResize: true,
        	enableSorting: true,
        	rowHeight: 20,
        	// ...
        }

With this option, ag-grid throw exception:

    platform-browser.umd.js:937 EXCEPTION: TypeError: Cannot read property 'addEventListener' of undefinedBrowserDomAdapter.logError @ platform-browser.umd.js:937BrowserDomAdapter.logGroup @ platform-browser.umd.js:947ExceptionHandler.call @ core.umd.js:4389next @ core.umd.js:9971schedulerFn @ core.umd.js:9168SafeSubscriber.__tryOrUnsub @ Subscriber.ts:240SafeSubscriber.next @ Subscriber.ts:192Subscriber._next @ Subscriber.ts:133Subscriber.next @ Subscriber.ts:93Subject._finalNext @ Subject.ts:154Subject._next @ Subject.ts:144Subject.next @ Subject.ts:90EventEmitter.emit @ core.umd.js:9156onError @ core.umd.js:9394onHandleError @ core.umd.js:9266ZoneDelegate.handleError @ zone.js:327Zone.runTask @ zone.js:259drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426
    platform-browser.umd.js:937 STACKTRACE:BrowserDomAdapter.logError @ platform-browser.umd.js:937ExceptionHandler.call @ core.umd.js:4391next @ core.umd.js:9971schedulerFn @ core.umd.js:9168SafeSubscriber.__tryOrUnsub @ Subscriber.ts:240SafeSubscriber.next @ Subscriber.ts:192Subscriber._next @ Subscriber.ts:133Subscriber.next @ Subscriber.ts:93Subject._finalNext @ Subject.ts:154Subject._next @ Subject.ts:144Subject.next @ Subject.ts:90EventEmitter.emit @ core.umd.js:9156onError @ core.umd.js:9394onHandleError @ core.umd.js:9266ZoneDelegate.handleError @ zone.js:327Zone.runTask @ zone.js:259drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426
    platform-browser.umd.js:937 TypeError: Cannot read property 'addEventListener' of undefined
        at GridPanel.addBodyViewportListener (http://localhost:3000/node_modules/ag-grid/dist/lib/gridPanel/gridPanel.js:243:27)
        at GridPanel.init (http://localhost:3000/node_modules/ag-grid/dist/lib/gridPanel/gridPanel.js:155:14)
        at eval (http://localhost:3000/node_modules/ag-grid/dist/lib/context/context.js:194:115)
        at Array.forEach (native)
        at eval (http://localhost:3000/node_modules/ag-grid/dist/lib/context/context.js:194:60)
        at Array.forEach (native)
        at Context.postConstruct (http://localhost:3000/node_modules/ag-grid/dist/lib/context/context.js:191:15)
        at Context.wireBeans (http://localhost:3000/node_modules/ag-grid/dist/lib/context/context.js:70:14)
        at new Context (http://localhost:3000/node_modules/ag-grid/dist/lib/context/context.js:23:14)
        at new Grid (http://localhost:3000/node_modules/ag-grid/dist/lib/grid.js:69:24)BrowserDomAdapter.logError @ platform-browser.umd.js:937ExceptionHandler.call @ core.umd.js:4392next @ core.umd.js:9971schedulerFn @ core.umd.js:9168SafeSubscriber.__tryOrUnsub @ Subscriber.ts:240SafeSubscriber.next @ Subscriber.ts:192Subscriber._next @ Subscriber.ts:133Subscriber.next @ Subscriber.ts:93Subject._finalNext @ Subject.ts:154Subject._next @ Subject.ts:144Subject.next @ Subject.ts:90EventEmitter.emit @ core.umd.js:9156onError @ core.umd.js:9394onHandleError @ core.umd.js:9266ZoneDelegate.handleError @ zone.js:327Zone.runTask @ zone.js:259drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426
    zone.js:463 TypeError: Cannot read property 'addEventListener' of undefined(…)consoleError @ zone.js:463drainMicroTaskQueue @ zone.js:477ZoneTask.invoke @ zone.js:426
    zone.js:101 XHR finished loading: GET "http://localhost:3000/api/pats/report/summary/4ed79ed1-bfd5-48f2-8ce3-e526704860db".scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:336Zone.scheduleMacroTask @ zone.js:273(anonymous function) @ zone.js:122send @ VM1318:3(anonymous function) @ http.umd.js:1419Observable.subscribe @ Observable.ts:93(anonymous function) @ toPromise.ts:24ZoneAwarePromise @ zone.js:584toPromise @ toPromise.ts:22PatsReportSummaryService.getSummary @ pats-report-summary.service.ts:16(anonymous function) @ pats-report-summary.component.ts:42SafeSubscriber.__tryOrSetError @ Subscriber.ts:249SafeSubscriber.next @ Subscriber.ts:193Subscriber._next @ Subscriber.ts:133Subscriber.next @ Subscriber.ts:93BehaviorSubject._subscribe @ BehaviorSubject.ts:33Observable.subscribe @ Observable.ts:93PatsReportSummaryComponent.ngOnInit @ pats-report-summary.component.ts:39_View_PatsReportComponent0.detectChangesInternal @ PatsReportComponent.ngfactory.js:48AppView.detectChanges @ core.umd.js:12586AppView.detectViewChildrenChanges @ core.umd.js:12612AppView.detectChangesInternal @ core.umd.js:12597AppView.detectChanges @ core.umd.js:12586ViewRef_.detectChanges @ core.umd.js:10804RouterOutlet.activate @ router.umd.js:3058ActivateRoutes.placeComponentIntoOutlet @ router.umd.js:2633ActivateRoutes.activateRoutes @ router.umd.js:2610(anonymous function) @ router.umd.js:2572ActivateRoutes.activateChildRoutes @ router.umd.js:2571ActivateRoutes.activate @ router.umd.js:2566(anonymous function) @ router.umd.js:2322(anonymous function) @ Observable.ts:133SafeSubscriber.__tryOrUnsub @ Subscriber.ts:240SafeSubscriber.next @ Subscriber.ts:192Subscriber._next @ Subscriber.ts:133Subscriber.next @ Subscriber.ts:93MergeMapSubscriber.notifyNext @ mergeMap.ts:144InnerSubscriber._next @ InnerSubscriber.ts:17Subscriber.next @ Subscriber.ts:93MapSubscriber._next @ map.ts:84Subscriber.next @ Subscriber.ts:93ReduceSubscriber._complete @ reduce.ts:82Subscriber.complete @ Subscriber.ts:120MergeMapSubscriber._complete @ mergeMap.ts:134Subscriber.complete @ Subscriber.ts:120ArrayObservable._subscribe @ ArrayObservable.ts:126Observable.subscribe @ Observable.ts:93Observable._subscribe @ Observable.ts:152MergeMapOperator.call @ mergeMap.ts:82Observable.subscribe @ Observable.ts:93Observable._subscribe @ Observable.ts:152ReduceOperator.call @ reduce.ts:37Observable.subscribe @ Observable.ts:93Observable._subscribe @ Observable.ts:152MapOperator.call @ map.ts:54Observable.subscribe @ Observable.ts:93subscribeToResult @ subscribeToResult.ts:32MergeMapSubscriber._innerSub @ mergeMap.ts:128MergeMapSubscriber._tryNext @ mergeMap.ts:124MergeMapSubscriber._next @ mergeMap.ts:108Subscriber.next @ Subscriber.ts:93MergeMapSubscriber.notifyNext @ mergeMap.ts:144InnerSubscriber._next @ InnerSubscriber.ts:17Subscriber.next @ Subscriber.ts:93EverySubscriber.notifyComplete @ every.ts:52EverySubscriber._complete @ every.ts:71Subscriber.complete @ Subscriber.ts:120MergeAllSubscriber._complete @ mergeAll.ts:95Subscriber.complete @ Subscriber.ts:120Subscriber._complete @ Subscriber.ts:142Subscriber.complete @ Subscriber.ts:120ArrayObservable._subscribe @ ArrayObservable.ts:126Observable.subscribe @ Observable.ts:93Observable._subscribe @ Observable.ts:152MapOperator.call @ map.ts:54Observable.subscribe @ Observable.ts:93Observable._subscribe @ Observable.ts:152MergeAllOperator.call @ mergeAll.ts:65Observable.subscribe @ Observable.ts:93Observable._subscribe @ Observable.ts:152EveryOperator.call @ every.ts:31Observable.subscribe @ Observable.ts:93subscribeToResult @ subscribeToResult.ts:32MergeMapSubscriber._innerSub @ mergeMap.ts:128MergeMapSubscriber._tryNext @ mergeMap.ts:124MergeMapSubscriber._next @ mergeMap.ts:108Subscriber.next @ Subscriber.ts:93MapSubscriber._next @ map.ts:84Subscriber.next @ Subscriber.ts:93MapSubscriber._next @ map.ts:84Subscriber.next @ Subscriber.ts:93MergeMapSubscriber.notifyNext @ mergeMap.ts:144InnerSubscriber._next @ InnerSubscriber.ts:17Subscriber.next @ Subscriber.ts:93MapSubscriber._next @ map.ts:84Subscriber.next @ Subscriber.ts:93MapSubscriber._next @ map.ts:84Subscriber.next @ Subscriber.ts:93ForkJoinSubscriber.notifyComplete @ ForkJoinObservable.ts:118InnerSubscriber._complete @ InnerSubscriber.ts:26Subscriber.complete @ Subscriber.ts:120(anonymous function) @ subscribeToResult.ts:48ZoneDelegate.invoke @ zone.js:323onInvoke @ core.umd.js:9245ZoneDelegate.invoke @ zone.js:322Zone.run @ zone.js:216(anonymous function) @ zone.js:571ZoneDelegate.invokeTask @ zone.js:356onInvokeTask @ core.umd.js:9236ZoneDelegate.invokeTask @ zone.js:355Zone.runTask @ zone.js:256drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426

If I set ````forPrint: false,```` then ag-grid works well without exception.

**Comment by ceolter** [comment]
fixed in 5.3.x, released yesterday.
