### ISSUE TITLE
textAlign is not working in headerCellRenderer

### ISSUE THREAD

**Issue by AbuSufyan** [ceolter/ag-grid#1108]
Hi,
We've some requirement first grid header column text is left align rest of all columns text are right align. For this purpose I've used **headerCellRenderer**  in column definitions but this is not working. Other properties are working like fontWeight, background. Jsfiddle is attached.
http://jsfiddle.net/AbuSufyan/vd0yj3xf/2/

**Comment by ceolter** [comment]
putting ```text-align: right``` to the parent ag-header-cell-label worked for me.

**Comment by AbuSufyan** [comment]
Thanks for updates, by doing this all columns header text are right aligned. But we need first column text left align rest of all columns are right align. text-align is not worked. I've used float:left, its worked for me.

**Comment by ceolter** [comment]
use colId to help narrow down your css selector

eg in the main online example, i can see the first column has colId of 'name'

```
<div class="ag-header-cell ag-header-cell-sortable ag-header-cell-sorted-none" colid="name" style="width: 200px; left: 0px;"> 
```

**Comment by linuradu** [comment]
using: `headerClass: 'a-given-class'`
the property: `text-align: center;`

is not working.

Any idea how can I center the header for only one cell?

**Comment by teuf22** [comment]
There is an open issue for this: https://github.com/ag-grid/ag-grid/issues/1953
