### ISSUE TITLE
filtered rows count

### ISSUE THREAD

**Issue by vsanat** [ceolter/ag-grid#1112]
Hi I am using below code to get filtered rows, but I am getting error saying "rowModel is private and can be used only withing GridApi". Please let me know if any better way is there?

 onAfterFilterChanged: () => {              
                console.log(this.gridOptions.api.rowModel.rowsToDisplay.length)
            },

note => even though I get error but it gives the correct value.

**Comment by vsanat** [comment]
found the solution 

onModelUpdated: () => { this.filteredRowsCount = this.gridOptions.api.getModel().getRowCount(); },

**Comment by randdusing** [comment]
I think getRowCount() internally uses rowsToDisplay.length. This value doesn't count rows within collapsed groups. I used this code below to get an unfiltered row count.

```javascript
var count= 0;
api.forEachNodeAfterFilter(function () {
    count++;
});
return count;
```

**Comment by ceolter** [comment]
using api.forEachNodeAfterFilter() and a counter is what i suggest for the reason given above, otherwise yo may be missing rows inside groups.
