### ISSUE TITLE
ag-grid with angular 2 - .getVirtualRowCount() is not available

### ISSUE THREAD

**Issue by vsanat** [ceolter/ag-grid#1113]
hi, 
I am using ag-grid with angular 2, I am trying to get total count to of filtered rows, for that I am trying to use 
var modal = api.getModel()
var count = modal.getVirtualRowCount() 
but I am getting error that  "Property 'getVirtualRowCount() ' does not exist on type IRowModel"

Please tell me what I am missing

**Comment by vsanat** [comment]
found the solution 

onModelUpdated: () => { this.filteredRowsCount = this.gridOptions.api.getModel().getRowCount(); },

**Comment by ceolter** [comment]
yup, getVirtualRowCount is for virtual pagiantion, sounds like you are not using virtual pagination.

**Comment by vsanat** [comment]
yes I was not using Virtual pagination. Thanks for the reply :)
