### ISSUE TITLE
Sluggish movement with scroll bar

### ISSUE THREAD

**Issue by AbuSufyan** [ceolter/ag-grid#1114]
We are using ag-grid v5.2.0, we face some issues with scroll bars. With vertical scroll bar Pinned column (First column) movement very sluggish, with horizontal scroll bar header columns movements very sluggish and not synced properly. You can see this behaviour in video. How we fix that issue? One Drive video link
[https://1drv.ms/v/s!AnrJsIrWjGXuxGipyG69BXCsu5Bv]

**Comment by ceolter** [comment]
This has already been raised (so closing this issue). the pinned and header move slowly, especially noticable on iPads and Android Pads.

**Comment by AbuSufyan** [comment]
Its happend on Windows 10 
Internet Explorer  Version: **11.545.10586.0**
