### ISSUE TITLE
Rename Column

### ISSUE THREAD

**Issue by randdusing** [ceolter/ag-grid#1116]
Is it possible to allow setColumnState() to modify the header name? Currently to rename a column name, I need to call setColumnDefs(), which is pretty expensive.

**Comment by ceolter** [comment]
column name can be dynamic, see colDef.headerValueGetter

so as long as the headerValueGetter is configured to return back the correct new name, then call api.refreshHeader() to refresh the header

**Comment by randdusing** [comment]
Thanks, missed this in the docs.
