### ISSUE TITLE
same id, how can I do

### ISSUE THREAD

**Issue by alex3stones** [ceolter/ag-grid#1117]
my data have id field, it's conflict with node id which makes the node id number incorrect, how can I do? 

thanks.

**Comment by ceolter** [comment]
i don't understand that question

**Comment by alex3stones** [comment]
sorry for my business so I didn't check this post.

eg: in ag-grid, we have Node Attributes: id, but my data field also has this , so when I tried to use them both, the serial number changed, not like (1,2,3...) but (1.10,20..) plz take a look at the below pic:
![image](https://cloud.githubusercontent.com/assets/15151490/18699412/dffc8410-8003-11e6-9aa9-fa4a0fbfa331.png)

`var columnDefs = [
                      // this row just shows the row index, doesn't use any data from the row
                      {headerName: "#", width: 50,
                          cellRenderer: function(params) {
                              return **params.node.id** + 1;
                          },
                          // we don't want to sort by the row index, this doesn't make sense as the point
                          // of the row index is to know the row index in what came back from the server
                          //,suppressSizeToFit: true
                          suppressSorting: true,
                          checkboxSelection: true,
                          suppressMenu: true },
                      {**headerName: "id"**, field: "antiMalwareEventID",width:10,hide: true},`

**Comment by alex3stones** [comment]
code is here

`{headerName: "#", width: 50,
                          cellRenderer: function(params) {
                              return params.node.id + 1;
                          },
                          suppressSorting: true,
                          checkboxSelection: true,
                          suppressMenu: true },
                      {headerName: "id", field: "antiMalwareEventID",width:10,hide: true}`

**Comment by ceolter** [comment]
your data id is nothing to do with the node id.

```
function cellRenderer(params) {
  // this is the node id
  console.log(params.node.id);
  // then this would be your id, if you have one on your data
  console.log(params.data.id);
}
```
