### ISSUE TITLE
onFilter/SortChange events don't include column

### ISSUE THREAD

**Issue by randdusing** [ceolter/ag-grid#1118]
In #1045, I said I'd use the onFilterChange or onSortChange events to resize the column... but onFilterChange and onSortChanged params just seem to be a blank object. Should this include the column that was affected by the filter or sort?

**Comment by ceolter** [comment]
no, that wasn't my intent. if i did put this in, then it gets confusing if multiple columns were changed (eg sorting or filtering by multiple columns) or no columns were changed (filter could be by quick filter or external filter). so keeping it simple to help with grid maintenance.
