### ISSUE TITLE
Feature Request: style floating rows

### ISSUE THREAD

**Issue by raptoria** [ceolter/ag-grid#1120]
Is there a way to style the floating rows, something like floatCellStyle ? I see that there is a floatingCellRenderer but nothing specifically for the styles.

Also, is it possible to add a template for ag-floating-bottom?
I'd like to add a header (div) just above the ag-floating-bottom (floating rows) so that I can clearly indicate to the end user that this data is different than the data in the above portion of the grid. Is this possible?

**Comment by ceolter** [comment]
use css - easiest way is to inspect the dom and see what you want to style.

eg you can use the css class ag-floating-bottom-container
