### ISSUE TITLE
rowDoubleClicked event works only when clicking an an are with Text

### ISSUE THREAD

**Issue by iamstormnet** [ceolter/ag-grid#1121]
Hi, i am issuing the following problem:

i want to use the rowDoubleClicked event to open up record in new popup. In general it works but the doubleclick event only works when i click on a value within a cell, not an are which is empty but the same column. For example:

`
```
| ColumnName         |
-----------------------
| My Text            |
```
`

This works:
```
| ColumnName         |
-----------------------
| My x Text          |
```

This not:

```
| ColumnName         |
-----------------------
| My Text    x       |
```

when i click on the pointed **x** then it works otherwise not. Is this a bug?

**Comment by ceolter** [comment]
could not reproduce this. i used the main demo, i took 'editable' off of the 'game name' column, and put a print statement into the onDoubleClicked()  callback. i got the event fired every time in double clicked, regardless of which part of the cell i clicked in.

so my guess is you are using your own cellRenderer that is consuming the events?

or if  something else, well i need an example to troubleshoot. so please show how to reproduce on one of the examples, or provide a plunker with it demonstrated.
