### ISSUE TITLE
Apply styling on selected cell or group of selected cells (not rows) in ag-grid and ag-grid-react

### ISSUE THREAD

**Issue by fakiolinho** [ceolter/ag-grid#1123]
First of all, congrats for the great effort you 've put in `ag-grid`. I am trying to evaluate it for my company and so far it looks really promising. One thing i haven't figured out yet is the following functionality:

- Select 1 cell or group of cells (not whole rows)
- Apply some styling rules like color: red, text-align: right etc
- This should also work the other way, i mean i want to provide by default specific styling for some cells (color: red, text-align: right etc) when the grid loads for the first time. I think there is no way to tackle this apart from using `columnDefs`.

Is this functionality offered or not?

**Comment by ceolter** [comment]
thank you for the positive feedback.

```Select 1 cell or group of cells (not whole rows)```
=>using ag-grid-enterprise you can use range selection for this.

```Apply some styling rules like color: red, text-align: right etc```
> please see docs or how to style cells
https://www.ag-grid.com/javascript-grid-cell-styling/index.php

in particular, check out ```cellClassRules```, if you want to apply rules based on values in your data.

so for initial styling, use colDef.cellStyle or colDef.cellClass, then cellClassRules for styles based on data values.

**Comment by nick250386** [comment]
Is it possible to apply a css class dynamically based on an option selected from context menu ?

**Comment by niralishah1599** [comment]
yes @nick250386  i faced same issue .. please help me
