### ISSUE TITLE
Callback function for Columns drag start and Stop

### ISSUE THREAD

**Issue by shivekundefined** [ceolter/ag-grid#1125]
While debugging the core ag-grid file I found that onDragStart and OnDropStopped events are registered in itself. Great!!.. But when trying to access those grid API or even registering those with gridOptions are not working. Please tell how to use it. A small working example or code would be helpful.

My approach was simple..

     var gridOptions = {
           onDragStop:some_function,
           columnMoved:some_other_function,
           dragStopped:some_other_function,
           onMouseUp:some_other_function,
    }

But none of above worked for me. 
I am using ag-grid v5.1.2 and chrome latest update.

**Comment by ceolter** [comment]
use:

```
var gridOptions = {
  onDragStarted: function() {},
  onColumnMoved: function() {},
  onDragStopped: function() {},
}
```

there is no onMouseUp event.

see here for events:
https://www.ag-grid.com/javascript-grid-events/index.php
