### ISSUE TITLE
Cannot read property 'focusCell' of undefined

### ISSUE THREAD

**Issue by maxired** [ceolter/ag-grid#1127]
Hi,

when using the grid in group mode,  in edit mode,
and navigating with tabs,  I sometime trigger the following error : 

![focuscellofundefined](https://cloud.githubusercontent.com/assets/1194083/18380867/bd57fe28-7679-11e6-9bb9-029b153c7855.png)

Looks like this is when the next row is the group row.

Looks like the error is coming from : 
https://github.com/ceolter/ag-grid/blob/97682aa220c214e647733f7f5dbc31b0e8aabfe0/src/ts/rendering/rowRenderer.ts#L648

**Comment by ceolter** [comment]
ok - i can fix it so this error  is not thrown (ie check for undefined) however i'd like to fix. can you advise how i can reproduce this in an example?

**Comment by ceolter** [comment]
no feedback, so closing.
