### ISSUE TITLE
angularCompileRows not working for all cells with d3.js as angular directive

### ISSUE THREAD

**Issue by schiz** [ceolter/ag-grid#1129]
I am using d3.js to create charts, that I want to show inside ag-grid.

Angular.js 1.5.x
D3.js v4

<img width="532" alt="2016-09-12 19 35 21" src="https://cloud.githubusercontent.com/assets/10157876/18444000/772fe9cc-7928-11e6-96a3-40dbb842c8a6.png">

I include ag-grid in html (jade) as follows:
<img width="416" alt="2016-09-12 19 36 22" src="https://cloud.githubusercontent.com/assets/10157876/18444050/aa93c2c0-7928-11e6-8cfd-ffce09ef856f.png">

I use angular directive to create a chart:
<img width="837" alt="2016-09-12 19 46 36" src="https://cloud.githubusercontent.com/assets/10157876/18444401/1c1233b8-792a-11e6-975a-33cf6b153587.png">

And pass this directive to cellRendererFunc:
<img width="466" alt="2016-09-12 19 48 15" src="https://cloud.githubusercontent.com/assets/10157876/18444453/4cf4402a-792a-11e6-8a74-6a37631a71ae.png">

In order to get the passed html string compiled by Angular I specify in gridOptions `angularCompileRows: true`, and finally, compiled are directives only in first cell of the column and in bottom floating row:
<img width="253" alt="2016-09-12 19 50 40" src="https://cloud.githubusercontent.com/assets/10157876/18444527/a0eaa994-792a-11e6-9923-6fcbb9117efb.png">

And If I scroll down, the chart from the first cell disappears. What can be the cause of this, and how can I get directives compiled and recompiled in all rows (including on scrolling) ?

**Comment by schiz** [comment]
Found the solution. The issue was that in `selectAll` instead of `select` in d3 selector.

**Comment by ceolter** [comment]
thanks for feeding back the solution.
