### ISSUE TITLE
tooltipField Display Value "null"

### ISSUE THREAD

**Issue by mperrenoud** [ceolter/ag-grid#1130]
I think the `tooltipField` works great, but it displays the value `null` when the value of the field is `null`; I'm thinking if we look at that from a user experience standpoint we probably just don't want to display anything if the value is `null`.

Thoughts?

**Comment by ceolter** [comment]
fixed. will be in todays release.

**Comment by mperrenoud** [comment]
Awesome, thanks a lot!

Sent from my iPhone

On Sep 15, 2016, at 05:08, Niall Crosby <notifications@github.com> wrote:

fixed. will be in todays release.

**Comment by harshitgupta** [comment]
It works great. 

Is there any way to make it fast. as of now, upon hover overing it, you have to wait for 2-3 seconds until it appears. Thats a lot of time waste. Is there any way i can avoid it?

Thanks a lot.

**Comment by ceolter** [comment]
the browser is displaying the tooltip, so check if the browser setting can be changed.
