### ISSUE TITLE
Master Detail Grids with angularCompileRows = true

### ISSUE THREAD

**Issue by daric81** [ceolter/ag-grid#1133]
Hi,
I have a scenario where i need grids within grids with the depth dependant on the data itself.  I also use angular in my grids. When I switch on angularCompileRows i get an error:

`Uncaught TypeError: Cannot read property '$new' of null`

from RenderedRow.prototype.createChildScopeOrNull;

I've tried tweeking the master detail grids example setting angularCompileRows :true with the same result.

**Comment by ceolter** [comment]
you need to be using the ag-Grid Angular 1 directive for it to work. sounds like you are not using the angular directive.

**Comment by SebastianPelaez** [comment]
Hi, im getting the same issue, do you fixed it? i tried many ways to solved it, but i dont know what more i can do. I really appreciate if you can help me
