### ISSUE TITLE
grid does not show the updated rows (in IE only)

### ISSUE THREAD

**Issue by neawasthi** [ceolter/ag-grid#1134]
Strange issue where when i come back to the grid post making a data update, it does not update itself to get the latest data. There is code which should fetch the updates from server but it will never fire.  The same works perfectly on Chrome.

Stranger is the fact that when I leave the console open IE, it starts to work. I can see that server calls are made as intended post this. Any clue what is going on or is this again some IE only magic error !!

**Comment by neawasthi** [comment]
Never mind, got the issue. 
Turned out to be a caching issue (insane IE caching) with get calls. Fixed it !

**Comment by ceolter** [comment]
thanks for feeding back the solution.
