### ISSUE TITLE
onRowSelected and node.setSelected() infinite loop, is there a way to prevent event?

### ISSUE THREAD

**Issue by Matheo13** [ceolter/ag-grid#1135]
Hi,

I have a problem for which I didn't found a real solution.

Is there a way to prevent the callback/event wich fires onRowSelected() when I use `node.setSelected(!node.selected)`?

I have 2 linked components, a map and an ag-grid.
When I check a point on the map it calls `node.setSelected(!node.selected)`
which triggers `onRowSelected`. 
Here is my problem: infitine loop, cause when it trigger a `onRowSelected` it checks a point on the map and ...

So is there a way to prevent the callback/event onRowSelected when I use `node.setSelected(!node.selected)`?

I took a look on the code, tried different stuff, but I didn't figure it out.
I tried to use `setSelectedInitialValue` but it didn't worked as I expected or some dirty stuff.

Thank you.

**Comment by Matheo13** [comment]
Actually the thing which is also a bit confusing is that, 
When I fire the check on the grid (gui checkbox), the `node.selected` is at `false`.
When I fire `node.setSelected()` in code without gui click, `node.selected` is at `true`

**Comment by Matheo13** [comment]
Sorry, I was tired, it seems working with `setSelectedInitialValue` (not in the documentation) if I check from where the interaction comes first: 
```
              if(from === this){
//from gird checkbox interaction
                node.setSelectedInitialValue(!node.selected);
              } else {
//from manual code
                node.setSelectedInitialValue(node.selected);
              }
```

**Comment by ceolter** [comment]
```setSelectedInitialValue``` is not documented as i don't intend for you to call. this does not tie in with the grid events - the grid uses it when rows that are already selected are read in while using virtual pagination. however if it works for you, happy for you to use it, just don't look for support or complain if the method changes int he future!! :)

regards the issue, i see the grid behave just link a DOM item. so if you want to not listen on an event, either remove your listener, or have a flag so your listener knows it's the result of something you set. all the events in ag-Grid are synchronous, so if you call api.XXX(), then all events will have fired by the time the method returns.

**Comment by Matheo13** [comment]
Yes I went against my intuition that `setSelectedInitialValue` shouldn't be used.
(for exemple it dosen't fire events to the selectionController, so when you call, `getSelectedRows` it will be empty)

I used a flag, seems to work thank you.

**Comment by domhaas** [comment]
I got the same issue and it looks like the events are not synchronous any more.
Are there any new advices how to prevent triggering "onSelectionChanged" on doing stuff like "api.deselectAll()" or "node.setSelected(true)"?

Thank you in advance.

**Comment by dicbrus** [comment]
I faced the same issue, 
it is not possible to set "flag" as @ceolter advised, since events are not synchronous (as @domhaas mentioned).

Re-opening the bug

**Comment by domhaas** [comment]
> I faced the same issue,
> it is not possible to set "flag" as @ceolter advised, since events are not synchronous (as @domhaas mentioned).
> 
> I think bug should be reopened.

I've found out that the third param of the setSelected-method can control to skip event pushing:
node.setSelected(true, false, skipEvents);

It is currently not official documented, but it work's fine now for me.

**Comment by dicbrus** [comment]
Yes, I saw this param, it is name `suppressFinishActions`

it skips the event for onSelectionChanged listener, but not for `onRowSelected`, 
unfortunately `onRowSelected` still fired.

**Comment by domhaas** [comment]
> Yes, I saw this param, its name is `suppressFinishActions`
> 
> it skips the event for `onSelectionChanged` listener, but not for `onRowSelected`,
> unfortunately `onRowSelected` still fired.

I see. I don't use the onRowSelection-Event, just the onSelectionChanged and den getting the selected rows by:
`grid.api.getSelectedRows()`

So maybe you could avoid it by this.

**Comment by dicbrus** [comment]
No, unfortunately that is not my case. 
I need explicitly know not only select event but un-select as well.

Currently I'm just looking at manual adding/removing listener on the row.

**Comment by AngeiMachi** [comment]
I had the same problem when i was trying to select all the node children when using ag-grid as **treeData**  . this is the bypass i wrote to avoid the bug :

`onRowSelected: (event) => {
                let selectedNode = event.node;
                if (this.isManualSelectionEvent(selectedNode)) {
                    this.selectAllNodeChildren(selectedNode);
                    this.emitOnNodeSelectedEvent(selectedNode);
                }
 },
`

` selectAllNodeChildren(selectedNode) {
        for (let child of selectedNode.allLeafChildren) {
            child.setSelected(selectedNode.selected);
        }
    }
`
`this.manualSelectionFlag = 0;`

`isManualSelectionEvent(selectedNode) {
        if (this.manualSelectionFlag === 0) {
            this.manualSelectionFlag = selectedNode.allLeafChildren.length - 1;
            return true;
        }
        else if (this.manualSelectionFlag > 0) {
            this.manualSelectionFlag--;
            return false;
        }
    }
`

Hope it helps :)

**Comment by luker2** [comment]
@dicbrus ever find a solution? I want to trigger logic every time a row is selected/deselected, and know whether it was explicitly selected by a user or programmatically using `node.setSelected()`.

Otherwise it's almost like I'd need to keep a history of selected nodes or something -_-

**Comment by MisterMunchkin** [comment]
Are there any updates to this? I'm currently facing the same issue where I use setSelected to programmatically set the selected nodes based on a selected boolean value in my grid model. 

I don't want the onRowSelected to fire when I'm setting the selected nodes. Only during user interaction. onSelectionChange doesn't have the row data in its params so it's not ideal. 

currently just using a mix of both onRowSelected and onSelectionChanged to handle different logic. Feels hacky but does the job for now.
