### ISSUE TITLE
How I can let row's  bottom  border fill the screen from left to right?

### ISSUE THREAD

**Issue by arrinhzh** [ceolter/ag-grid#1142]
If I have only  one or two columns,how can I  let row's  bottom  border fill the screen from left to right?
Now I can see ,my bottom border is as long as  the data (only one column).
Thank you

**Comment by ceolter** [comment]
you can't. if you don't want the blank space, the you should have the columns fit the width of the grid. having the rows the width of the grid in any other way doesn't work, as it would then mess with the horizontal scrolling.
