### ISSUE TITLE
Virtual Paging / Infinite Scrolling issue

### ISSUE THREAD

**Issue by daric81** [ceolter/ag-grid#1143]
Hi,
Since the re-write of Virtual Pagination I've noticed some unexpected changes in behaviour.  First off is when the rowCount is know and set, the scroll bar (thumb) used to be calculated upfront and never changed in size. This no longer seems to be the case.

Secondly when there is no data being returned and  params.failCallback() is called, rows are still placed into the grid, and scrolling is permitted.   This used to work differently.  Rows were not inserted if the fail callback was called.

**Comment by ceolter** [comment]
"First off is when the rowCount is know and set, the scroll bar (thumb) used to be calculated upfront and never changed in size. This no longer seems to be the case."
=> the rowCount only changes if you bring back more data in your datasource. to have it not change, make sure you set it via setVirtualRowCount(count, true) (the true means maxRowFound) and then never bring back more rows in your datasource.

"Secondly when there is no data being returned and params.failCallback() is called" => this is for application errors - so how the grid behaves is not something i'm terribly concerned about. you should be popping up a message saying "this app is having problems and cannot continue, please contact admin etc etc etc". if its a normal use case that no rows exist after the call, you should be calling success callback with lastRow=0

**Comment by daric81** [comment]
Hi,
Thanks for the reply.
However, I'm not really following regarding the virtual paging on the first point and believe there's still an issue or at least a change in behaviour that doesn't match the documentation.

Before populating my grid i get a count of the expected result set, say 1000.  I then set rowCount on my grid options to this value and then set up the datasource.  I've also tried api.setVirtualRowCount(1000) after setting up the datasource as you suggest. Say my page size is 200. 

According to the documentation and how agGrid used to work too,

"If the grid knows how many pages in total at the start, the scroll will be sized to match the entire data set despite the data set not loaded from the server."

So i don't know if the change in behaviour with the scroll was intended but whats mentioned in the docs doesn't happen. 

On the second point, I've changed my code to call success rather than fail on an empty result set, however i still believe that adding rows to the grid when an error occurs is not ideal at all and is an undesirable change in behaviour.

**Comment by ceolter** [comment]
1. ```I then set rowCount on my grid options``` don't set it on your grid options, set it on your datasource. See the last example on this page: https://www.ag-grid.com/javascript-grid-pagination/index.php - it is a standard pagination example (not virtual pagination) however setting the row count on the datasource is done the same way.

2. you don't need to set rows into the grid. you can call success with an empty list, and also set rowCount to zero ie ```successCallback([], 0)```
