### ISSUE TITLE
pasting into CellEditor shows old value

### ISSUE THREAD

**Issue by tobciu** [ceolter/ag-grid#1144]
hey,
i found strange ...
if i paste into a CellEditor (editable: true) and leave the cell, the old value will be shown.

**Steps to reproduce**
1.  Go to [https://www.ag-grid.com/javascript-grid-cell-editing/exampleCellEditing.html](https://www.ag-grid.com/javascript-grid-cell-editing/exampleCellEditing.html)
2. copy a cell or have something in clipboard
3. doubleclick on a cell to activate the CellEditor
4. paste from clipboard (STRG/CMD+V)
5. leave the cell

**Comment by nareshbhatia** [comment]
We are running into the same issue. Can this be fixed please?

**Comment by ceolter** [comment]
thanks. fixed. will be in next release (planning one today or tomorrow).

when editing, the grid was working on ctrl+v, ctrl+c, ctrl+x, ctrl+d, which messed up the edit. Now the grid ignores these if you are editing the cell.

**Comment by nareshbhatia** [comment]
Thanks, @ceolter. Quick question, will this fix be available only in 6.x or also on 5.x? We are still on 5.x.

Of course, this would be a good motivation for switching to 6.x :-). However we will have to do lot of regression testing to make sure we haven't broken anything.

**Comment by ceolter** [comment]
we work going forwards only, sorry, it till be the next 6.x release

**Comment by ceolter** [comment]
we just don't have the capacity to be putting patches against all historic releases

**Comment by nareshbhatia** [comment]
No worries. We will switch to version 6.
