### ISSUE TITLE
suppressScrollLag / isScrollLag doesn't work for chrome

### ISSUE THREAD

**Issue by schiz** [ceolter/ag-grid#1145]
My goal is to achieve a fast, performant scroll.

I pass an angular directive:
<img width="827" alt="2016-09-19 18 33 06" src="https://cloud.githubusercontent.com/assets/10157876/18638126/03935a4e-7ea0-11e6-90c2-9f4e5aa3afeb.png">

to a cellRenderer component:
<img width="495" alt="2016-09-19 18 35 23" src="https://cloud.githubusercontent.com/assets/10157876/18638191/49133422-7ea0-11e6-8bf6-422f1928bf5b.png">

and as a result get this:
![2016-09-19 18 36 45](https://cloud.githubusercontent.com/assets/10157876/18638254/74182fce-7ea0-11e6-992d-8a18e61c41d0.png)

In the gridOptions I try both `suppressScrollLag: true` and `isScrollLag: function() { return false; }`
<img width="347" alt="2016-09-19 18 38 52" src="https://cloud.githubusercontent.com/assets/10157876/18638343/d09ad832-7ea0-11e6-9588-941a24f9f498.png">

Finally, we have two things, that slow down rendering when scrolling:

- Angular directive, that being passed to cellRenderer slows it down
- Expensive DOM manipulations, that are used to compose the chart (complex set of html elements) 
 
Despite of these two, that slow the rendering down while scrolling, the resulting performance with `suppressScrollLag: true` or `isScrollLag: function() { return false; }` is good, but only in Safari. This is because of how @ceolter said  [here](https://github.com/ceolter/ag-grid/issues/231) : 

> the biggest performance gain for IE and Safari (not the others) comes with the 'scrollLag' feature. when you are scrolling, the grid listens to the scroll events to update the dom. in IE and Safari, this gave a very 'jumpy' scrollbar (on my machine). with this enabled, then it will wait for 50ms and do nothing if another scroll event comes in. that means, if you are scrolling, the grid will not redraw until the scroll has stayed still for 50ms. this allows you to use the scrollbar without jumps until you come to a steady position.

Now I want to achieve the same performant rendering as in Safari (precisely - the same mechanics of redraw after scroll has finished) for Chrome / Firefox / etc. How can I achieve that? 

In [official doc's property section](https://www.ag-grid.com/javascript-grid-properties/index.php) it is said:

> By default, scrolling lag is enabled for Safari and Internet Explorer (to solve scrolling performance issues in these browsers). To override when to use scroll lag either a) set suppressScrollLag to true to turn off scroll lag feature or b) return true of false from the function isScrollLag. This is a function, as it's expected your code will check the environment to decide whether to use scroll lag or not.

- Does it mean that with `suppressScrollLag: true` and `isScrollLag: function() { return false; }` scrollLag is enabled only for IE & Safari, and in that case, can we expect for this implementation of delayed redraw to be made for other browsers?
- If it meant that with `suppressScrollLag: true` and `isScrollLag: function() { return false; }` the scrollLag is enabled also for all other browsers besides IE & Safari, in that case, for what reason mechanics of delayed redraw is not applied ?
- Is there any way to implement the delayed redraw manually (there are no scroll events in docs) ?

If it is possible to somehow apply this mechanics of delayed redraw after scrolling - it would be the easiest way to solve this issue. If not, there are next alternatives:

- Make the angular directive return a chart as an HTML-string, instead of performing expensive DOM-manipulations & building the complex element.
- Avoid angularjs in the grid, and pass a cellRenderer an HTML-string instead of angular-directive.

If there is no way to apply the delayed redraw after scrolling by simply setting `suppressScrollLag: true` and `isScrollLag: function() { return false; }`, then how the last two ways can be implemented, if it is possible at all?

Thanks for any comments in advance.

**Comment by ceolter** [comment]
to get scroll lag working in Chrome, have:
```
  isScrollLag: function() { return true; },
  suppressScrollLag: false,
```

however what i would do is put the delayed rendering into your cellRenderer. i mean - have each cellRenderer with a timeout - so that chart is only rendered say if the row is on screen for more than 2 seconds - or you could have it so the charts are only rendered if the grid stops scrolling (you can listen for the viewportChanged event and time when you havn't heard this event for x milliseconds)
