### ISSUE TITLE
[feature] Grid API update - getRowData() method

### ISSUE THREAD

**Issue by GAndriyS** [ceolter/ag-grid#1146]
We have method setRowData(data) to set data into grid. 
I think that it would be great to have API to get current state of grid data (after filter, sorting etc.) eg. filter data in grid and send it to server. 
Now I am forced to use iteration through rowsToDisplay from gridOptions.api.getModel() to collect current data state. 
Is there any comprehensive way to grab current data from grid or does it make sense to add API like getRowData() ?

**Comment by ceolter** [comment]
please see here, section 'Getting Data Out'
https://www.ag-grid.com/javascript-grid-insert-remove/index.php

**Comment by igpeev** [comment]
The link above is not leading to -insert-remove. No adequate answer to much needed getAllData() or similar.

**Comment by JabbyPanda** [comment]
I think the closest page that had replaced `javascript-grid-insert-remove/index.php` page is nowdays this one https://www.ag-grid.com/javascript-grid-accessing-data/#for-each-node

One can iterate through the rows to obtain the data from RowNode collection

**Comment by vanboom** [comment]
Suggestion:  implement a getRowDataAsJson() method that pulls the data into a JSON object using the field names.  The CSV getter uses the header names.  With all of the powerful features in ag-grid, why are simple methods of extracting the data lacking?  

```javascript
  function getJson()
  {
    data = new Array;
    mygrid.forEachNode(function(row){
      data.push(row.data);
    });
    return data;
  }
```
