### ISSUE TITLE
[bug] Can't scroll grid if groupUseEntireRow: true

### ISSUE THREAD

**Issue by GAndriyS** [ceolter/ag-grid#1147]
If grid property groupUseEntireRow is true, then scroll doesn't work if mouse above group row.
Example: https://www.ag-grid.com/javascript-grid-grouping/example1.html
And if groupUseEntireRow is false, then everything is OK
Example:  https://www.ag-grid.com/javascript-grid-grouping/exampleGroupingKeys.html

**Comment by maxired** [comment]
@GAndriyS , glad you experiences also this.
There is a related issue on the enterprise repo, https://github.com/ceolter/ag-grid-enterprise/issues/69

**Comment by GAndriyS** [comment]
@maxired thanks for link to related issue, hope this bug will be fixed asap.
