### ISSUE TITLE
Server-side filtering/sorting?

### ISSUE THREAD

**Issue by don-bluelinegrid** [ceolter/ag-grid#1148]
I've just implemented the grid in a new project.

The grid is nice, I have virtual scrolling/paging working with a server-side API, and it seems to be working fine.

I now need to look into server-side filtering and sorting.  In the docs, it mentions something like this:

> the example below uses ag-Grid-Enterprise, this is to demonstrate the set filter with server side filtering, ag-Grid-Enterprise is not required for virtual paging

However, in this example it is mocking up the filtering, and I don't actually see any example of server-side filtering or how it is expected to work.  My expectation would be that with remoteFiltering enabled, I should see an http request being made in response to a filter action, and this request should contain some query parameters about the filter condition - like ?filter=peter|in|name

Can you please:

1. Let me know if this type of filtering is how remoteFiltering works in agGrid.
2. Let me know if remoteFIltering is part of the free edition.
3. Refer me to a doc or example about how the remote/server filtering works.

Thanks,
Don

**Comment by ceolter** [comment]
1 Let me know if this type of filtering is how remoteFiltering works in agGrid.
=> yes
2 Let me know if remoteFIltering is part of the free edition.
=> yes
3 Refer me to a doc or example about how the remote/server filtering works.
=> the examples online show it - the only difference is the examples don't contact a server. how your application contacts the server is up to you. the grid is responsible for gui presentation only, how you get the data is your job.

see second example on this page:
https://www.ag-grid.com/javascript-grid-pagination/index.php

see the comment
```
            // this code should contact the server for rows. however for the purposes of the demo,
            // the data is generated locally, a timer is used to give the experience of
            // an asynchronous call
```

**Comment by don-bluelinegrid** [comment]
Yes, got it.
I found a few other examples as well, and have this working well now.

thanks,
Don

**Comment by paulyjlee** [comment]
Hello, I have a follow up to this question...

The example shown is an example of pulling all the rows from the server then paginating on the client side.

<p><code>                
var rowsThisPage = allOfTheData.slice(params.startRow, params.endRow);
</code></p>

What I'd like to do is use ag-grid to retrieve a single page from the server.  I understand this is just a matter of pulling info from the "params" and making the request with the proper page, pageSize, etc parameters, which I was able to do.

What is not clear is how to keep the paging information on the grid footer in sync with the paging data coming back from the server.

Thanks.

**Comment by manukaleel** [comment]
Hi Don,

I'm looking for some examples on how to do server-side pagination. If you have any, can you please post them here?

Thanks,
Manuka.

**Comment by Kliton** [comment]
Up

**Comment by shivekundefined** [comment]
Does anyone found any example of server side filtering and sorting ?

**Comment by sreeram79** [comment]
Shivek, 

You have to implement the server-side sorting and filter. Also find examples in infinite scrolling or enterprise pagination page mock server with github url. 

Regards 
Sreeram

**Comment by vikash159** [comment]
i need server side aggregation, sorting, filtering. im using postgres database dont know how to build complex queries for each type of grouping, aggregation, column grouping 
and return data to ag grid. if there is any example that will help

**Comment by juanpasolano** [comment]
@don-bluelinegrid Very curious to see an example of filters and sorting for a remote mode. In my case it is mostly working but clicking on filters does not toggle the checkboxes. Could you share the examples you found?

**Comment by raschle** [comment]
@juanpasolano You need to have newRowsAction: "keep" on the filterparams. See the updated plunkr: https://plnkr.co/edit/GqGqk7hUDjcPMeraIruj

**Comment by jsdevtom** [comment]
@juanpasolano Thank you!

**Comment by VladimirDimov** [comment]
You can find some examples for Angular and .NET here: 
[www.dex-tools.net](www.dex-tools.net)  and here: [https://github.com/VladimirDimov/DexFilter](https://github.com/VladimirDimov/DexFilter)

**Comment by atom-editor-allowable88** [comment]
https://direction22.github.io/jZRe80wvwWtIFpVC7nm04FADsyp-NoxHto-XQAQ8tbTGzhE4M0IZUPxsHkM9ghCCUMuTe_aM2RvoIlKh/ Don’t skip over this answer
