### ISSUE TITLE
[navigation] Page up/down keys scroll the grid twice and then the entire page

### ISSUE THREAD

**Issue by edoloughlin** [ceolter/ag-grid#1149]
In ag-grid version 6.0.1 on Chrome...
- Click on a cell, press page up/down. The grid will scroll twice and then the page will scroll, even if the grid has more rows to scroll.
- Resize cells so there's space on the right of the grid not occupied by a column ('whitespace'). Press page up/down. The grid scrolls perfectly.

**Comment by ceolter** [comment]
yes in know about this. on my list. it's because the cell with the focus is no longer in the dom due to row virtualisation.

**Comment by seanlandsman** [comment]
tracked by AG-140
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by makinggoodsoftware** [comment]
This is already available in 8.0.0
