### ISSUE TITLE
[navigation] stop errors when moveFocusToNextCell on Full Width Rows

### ISSUE THREAD

**Issue by rfps** [ceolter/ag-grid#1150]
Hi,

i'm working with ag-grid to angular 1 version 6.0.1 and i found a error. 
I'm using the feature Full Width Rows and i've edit cells on other rows, the problem its that if we use tab  key through edit fields when its expected change the row to the next editable cell its returned the error "Uncaught TypeError: Cannot read property 'isCellEditable' of undefined". I think the problem is on method moveFocusToNextCell that is not check yet the option Full with row.
Can you help?

**Comment by ceolter** [comment]
thanks for the report. tab navigation around fullWidth is not supported, from the documentation "does not participate in the navigation, rangeSelection (ag-Grid Enterprise) or contextMenu (ag-Grid Enterprise) of the main grid."
https://www.ag-grid.com/javascript-grid-master-detail/index.php

to get this to work is a big chunk of work for us - so as a matter of priority, this is far down the list.

**Comment by ceolter** [comment]
this should be fixed so it doesn't cause an error, although we don't plan to handle navigation on fullWidth, the grid shouldn't be printing errors to the console, need more graceful handling.

**Comment by seanlandsman** [comment]
tracked by AG-141
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by unformatt** [comment]
Any ideas for a work around?

**Comment by seanlandsman** [comment]
@unformatt no, I'm afraid not at this time

**Comment by rfps** [comment]
I don't know if can help, but to hide this error, i create a custom monkey patch where i've changed the method "RowRenderer.prototype.moveFocusToNextCell".

> 	            
	            // or row that is not currently in view, hence the renderedCell would not exist
	            var nextRenderedCell = this.getComponentForCell(nextCell);
	            // CUSTOM CHANGE - if nextRenderedCell not exist, skip
	            if (!nextRenderedCell) {
	                continue;
	            }
                    //END CUSTOM CHANGE
	            // if editing, but cell not editable, skip cell
	            if (startEditing && !nextRenderedCell.isCellEditable()) {
	                continue;
	            }

**Comment by ceolter** [comment]
i believe this is fixed in the most recent version.
