### ISSUE TITLE
autoSizeColumns method affects performance

### ISSUE THREAD

**Issue by fakiolinho** [ceolter/ag-grid#1152]
I 've implemented `this.columnApi.autoSizeColumns()` to resize columns after `gridReady` event is emitted and now i can see some blinks while scrolling up or down. I am doing this also when `columnEverythingChanged` event is fired in order to resize columns once again after grid gets re-rendered.

Whenever i disable this then the grid scrolls really smoothly and the experience is awesome. I am about to drop it and use some default widths per column to prevent this but this is not an ideal approach here.

I am using the ReactJS version and ag-grid 6.0.

**Comment by ceolter** [comment]
you say you call ```this.columnApi.autoSizeColumns()``` once, and then afterwards the grid is slow???

or are you calling ```this.columnApi.autoSizeColumns()``` lots of times?

**Comment by fakiolinho** [comment]
Yes, i was calling this once after `gridReady` event and then i also applied it on `columnEverythingChanged` because resize didn't work everytime sth was updated. In the end i 've removed `autoSizeColumns()` and i have to admit that fixed widths make things faster.

**Comment by ceolter** [comment]
the event ```columnEverythingChanged``` gets fired when you set new column definitions or you set the column state. so i don't know why it was slowing things down (unless you were changing the column definitions logs, or setting the state lots, both of which i presume you were not doing).

if you can provide a plunker with the issue, i can take a look? however with the above info, nothing else comes to mind.

ps cos you are working around it, sounds like you don't need an answer now, so closing.
