### ISSUE TITLE
[FEAT/BUG?]: Expand/Collapse of grouped rows

### ISSUE THREAD

**Issue by Navdeep-Nurpuri** [ceolter/ag-grid#1153]
We have a grid that uses tree-data (File Browser style) to display some data. Is there an API exposed which could toggle the Expand and collpase for the grouped rows on click of an external button.

Currently I tried something as follows to achieve this (but it didnt work)
       ` getNodeChildDetails: function (obj) {
           if (obj.children && obj.children.length > 0) {
               return {
                             group: true,
                             children: obj.children,
                              expanded: $scope.expandAllRows
                          };
                       } else {
                         return null;
                      }
              }`

And to the `expandAllRows` would be set to `true` or `false` depending on the button click as follows

` $scope.test = function () {
     $scope.expandAllRows = !$scope.expandAllRows;
     $scope.gridOptions.masterList.api.refreshView()
}`

But it seems that `api.refreshView()` doesnt expand/collpass the rows. Please let me know if this would be a new feature or a bug or is there a work around for this.

Thanks.

**Comment by ceolter** [comment]
set node.expanded = true / false

then call api.onGroupExpandedOrCollapsed(refreshFromIndex?)

refreshFromIndex? is optional - if you provide a row id, it will only refresh from that row - so if you expand a group, you only need to redraw from the rows below it.
