### ISSUE TITLE
Full Width Rows missing from exported data.

### ISSUE THREAD

**Issue by eikishi01** [ceolter/ag-grid#1155]
Hi, 

First, love the project, thank you. Now the issue.

I'm using the [full width](https://www.ag-grid.com/javascript-grid-master-detail/index.php) row feature and when exporting the data in it's place there is an empty row.

![image](https://cloud.githubusercontent.com/assets/22381638/18768349/c2fe80dc-80e1-11e6-9975-ee6bb1acb17a.png)

That empty row should have a simple string from the full width row.

Thanks.

**Comment by ceolter** [comment]
use processCellCallback to change the value for the cell for the fullWidth rows.
https://www.ag-grid.com/javascript-grid-export/index.php
