### ISSUE TITLE
Possible to have field of Column API be a function as opposed to a String?

### ISSUE THREAD

**Issue by dkwin** [ceolter/ag-grid#1156]
Hi guys

    With some tables, there are rows where there are arrays and nested objects.  For example
```

rows = [
     {
         rowId: "foo",
         cells[
              {
                   Attribute1: "someAttribute",
                   value: "someValue"
               },
               {
                   Attribute1: "someAttribute2",
                   value: "someValue2"
               }
          ],
      }
];
```

Just as example of data where rows aren't really defined as proper objects.  

I'm aware that I could just make a function to convert the rows to objects but I was wondering if the Columns API allowed fields to be defined as function in the case of very funky looking Row objects.

**Comment by ceolter** [comment]
yes, use valueGetter, that can be a function.
