### ISSUE TITLE
[pagination] rowCount not reset after moving to the next page

### ISSUE THREAD

**Issue by stappwe** [ceolter/ag-grid#1159]
When moving from page to page and a different number of rows was returned from the server, the rowCount is not reset. Number of rows could have been changed due to inserts of new records on the database level.

getRows: (params: any) => {
      console.log('Asking for ' + params.startRow + ' to ' + params.endRow);
      this._tmsService.getSuppliers().subscribe(
        (data) => {
          params.successCallback(data.rows, data.length); 
        },
        err => { this.rowData_error = true }
      );
    }

In the page controller, the foundMaxRow prevent the lastRowIndex from being updated:
PaginationController.prototype.pageLoaded = function (rows, lastRowIndex) {
        var firstId = this.currentPage \* this.pageSize;
        this.inMemoryRowModel.setRowData(rows, true, firstId);
        // see if we hit the last row
        if (**!this.foundMaxRow &&** typeof lastRowIndex === 'number' && lastRowIndex >= 0) {
            this.foundMaxRow = true;
            this.rowCount = lastRowIndex;
            this.calculateTotalPages();

**Comment by ceolter** [comment]
we plan on refactoring the pagination - to give it a face lift. in two months approx from now. will look at this then.

**Comment by ceolter** [comment]
tracked by AG-143
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by ceolter** [comment]
since moving to client side pagination, this is no longer applicable.
