### ISSUE TITLE
[Feature] Editing at cell level instead of column level.

### ISSUE THREAD

**Issue by Navdeep-Nurpuri** [ceolter/ag-grid#1162]
At the moment the only way to edit a cell is through setting the colDef.editable property to true.

Is there a way where we could enable or disable editing on a "Per cell" basis. Where my code would have a logic for my cell to be editable or not.

This is one of the major reasons why we had to use cellRenderer in order to show input boxes.

**Comment by benoc008** [comment]
Hi,
actually colDef.editable can be a function where you can implement your logic. Check column.js
https://github.com/ceolter/ag-grid/blob/d60dec55225eb3da16a64dd829f8fb4c06ab46c8/dist/lib/entities/column.js#L115

**Comment by Navdeep-Nurpuri** [comment]
Hey, 

Yes, just saw the code and then checked the documentation. I guess I missed that one line.

> Set to true if this col is editable, otherwise false. Can also be a function to have different rows editable.

Well I guess this should work. 

Thanks.

**Comment by ceolter** [comment]
changing it to a function was a new feature, release in the last month. so it's possibly you didn't see it creep in!!

**Comment by RoshanRoyal** [comment]
Hey ceolter,

this function will be evaluated at time of ui rendering can we have something to make cell editable at runtime i.e. if a cell value is changed make another cell as editable
