### ISSUE TITLE
Empty grid during virtual page loads

### ISSUE THREAD

**Issue by aurhe** [ceolter/ag-grid#1163]
When using Virtual Paging / Infinite Scrolling, after we change the sorted column or apply a filter the grid becomes empty while the new page is being fetched from the server. This causes a flicker as the grid becomes momentarily blank.

Is there any way to configure the grid to not remove the previous rows until the new virtual page arrives?

**Comment by don-bluelinegrid** [comment]
@aurhe @ceolter 

This sounds similar to the issue I reported recently?
https://github.com/ceolter/ag-grid/issues/1151

Don

**Comment by ceolter** [comment]
@don-bluelinegrid different issue

@aurhe no, there is no way. if we kept the old rows, then the grid would be out of sync, ie the data would not match the sort / filter you have applied. hence we remove the rows straight away.
