### ISSUE TITLE
Viewport grouping doesn't work in 6.0.1

### ISSUE THREAD

**Issue by Hafureluspatha** [ceolter/ag-grid#1164]
Hello. I've made a post on the ag-grid forum: https://ag-grid.com/forum/showthread.php?tid=4186

The main question is: Is the viewport grouping possible? If yes then how? There's only one paragraph about this on the Viewport page and grouping is not so easy compared to viewport sorting and filtering.

**Comment by Hafureluspatha** [comment]
Sorry, my bad. 
Instead of providing a class to `cellRenderer' field, I was providing an instance of this class.

**Comment by Hafureluspatha** [comment]
However, in 6.0.1 the grid stays completely silent even with default ` group ` renderer. So, now the question is: "Is viewport grouping possible in 6.0.1? If yes then how?"

**Comment by ceolter** [comment]
grouping is not possible in viewport. this is because the data is on the server, it is not available to the grid to do the grouping.

you can still use the group cell renderer, however the data won't have any groups in it, so it won't make much sense.
