### ISSUE TITLE
Full Width Rows and Master Details on Row Click

### ISSUE THREAD

**Issue by keithckramer** [ceolter/ag-grid#1165]
We are current using aggrid and implementing the Full Width Rows and Master details. And it works great but one issue I need to solve for our software is the instead of click the + or - icon to get the childnode, I want to click the entire row.  One is this possible? 

I try to implement onRowClicked with the cellRenderer - group but doesn't seem to work well together. Any insight into this would be very helpful.  Thank you.

**Comment by ceolter** [comment]
when you want to expand the row via api, set node.expanded = true, then call api.
onGroupExpandedOrCollapsed(refreshFromIndex), where refreshFromIndex (it's optional) can be the index to refresh rows from - in your case you want to refresh everything under the parent row (or just leave it out if you are unsure, get it working first!)
