### ISSUE TITLE
Paste data to a partially editable column

### ISSUE THREAD

**Issue by benoc008** [ceolter/ag-grid#1166]
Hi, 

I have a grid with a column where the editable propery is a custom function.  So, for example the first 10 rows are disabled and the rest is enabled.

If I try to paste data using Ctrl+V when the focused row is enabled, it works just fine. 
But, whenever the focus is on a disabled row and I try to paste, the animation blinks up, but the data seems to be the same. Actually if I debug it, the new data is there, it's just a missing refresh on the view or something like that, but it's really annoying that you don't know what are the real values in the grid.

**Comment by ceolter** [comment]
fixed. will be in next release.
