### ISSUE TITLE
Scroll are not working in IE10.

### ISSUE THREAD

**Issue by vamsikrishnamannem** [ceolter/ag-grid#1167]
Hello @ceolter ,
 I appreciate you for creating this data grid.

In IE10(exact version 10.0.9200.17609) vertical and horizontal scrollbars are not working for these events 
Mouse dragon scroll and Mouse wheel.

**Comment by ceolter** [comment]
so many issues with IE :(

thanks, will be putting some time towards  IE at some point, i've it added to my list.

**Comment by BrandonNoad** [comment]
Scrolling is not working properly in IE9 either (in v6.0.1). It only seems to work if the mouse is hovering over some text in a cell and you use the mouse wheel or trackpad.

**Comment by dpsnomak** [comment]
Hi, @ceolter, I would be appreciated if you can fix this issue in the closest release at least for IE 10. Or maybe you can provide with proper workaround. 
Thank you in advance

**Comment by nmarsden** [comment]
A workaround which worked for me was to use ag-grid v5.2.0

With ag-grid v6.4.2 I found that scrolling did not work in IE9 or IE10. The scroll bars appeared but did not respond to selection.

I found that changing the 'ag-full-width-viewport' class to display:none instead of display:inline made the scroll bars selectable again.  The git log shows that the 'ag-full-width-viewport' class was introduced in v5.3.0 on 31/08/16.

**Comment by dpsnomak** [comment]
> I found that changing the 'ag-full-width-viewport' class to display:none instead of display:inline made the scroll bars selectable again.
It's work perfect, thanks a lot for your help!

**Comment by ceolter** [comment]
i see now that fullWidth causes issues in IE10. basically the fullWidth container covers everything but should be allowing mouse events to pass through. this pass through doesn't work in IE10. so i'm going to code it, so that fullWidht container is not present if you are not actually using it.

**Comment by ceolter** [comment]
```I see now that fullWidth causes issues in IE10. ``` -> just this bit (with regards fullWidht) is fixed - now the fullWidth containers are hidden if the containers are empty. thus if fullWidth is causing issues, don't put in any fulWidth rows, then the container is now shown so doesn't consume mouse events.

**Comment by ceolter** [comment]
reading back through this, i believe the issue is resolved. basically IE had issues with the overlay for fullWidth rows. so either don't use fullWidth rows, or set ```embedFullWidthRows=true``` (which then doens't use the overlay, and the fullWidth rows are sitting with the rest of the cells)

**Comment by ravidevkhile** [comment]
Hi @ceolter,

We are also facing same issue in IE11, in our case we are using Ag-Grid with Material (Angular 5).
We tried setting "embedFullWidthRows=true" but still it's not showing scrollbar
