### ISSUE TITLE
includeHeaders is always false

### ISSUE THREAD

**Issue by ckiss** [ceolter/ag-grid#1170]
Hi. In the app I'm working now, I would like that copy to always include headers. Is there a way to set includeHeaders to always be true instead of false?

and if it is, can I also remove "Copy with Headers" from contextual menu and leave just Copy?

Thanks!

**Comment by ceolter** [comment]
the design is to allow you to put whatever you want into the menu. see the docs on how to customise the context menu. then use the api to copy including the headers.
