### ISSUE TITLE
Is there some event or flag, that cell editing has started

### ISSUE THREAD

**Issue by jbalaty** [ceolter/ag-grid#1172]
Hello
I need to know when some cell is being edited eg. by double click.

Thx for any advice
Jiri

**Comment by ceolter** [comment]
no.

but the cell editors are created when editing starts. you could create your own editor. OR you could extend one of the built in editors and just add a little to the init() method (the init method gets called when it starts).

eg:
```
import {TextCellEditor} from 'ag-grid';

class MyEditor extends TextCellEditor {
  public init(params) {
    super.init(params);
    console.log('editing started');
  }
}
``` 
example is in TypeScript, if using JavaScript, the do similar with prototypes (i don't use JavaScript, so you will have to figure that one out yourself!!)
