### ISSUE TITLE
React ag-grid in tab shrinks to zero height

### ISSUE THREAD

**Issue by joequant** [ceolter/ag-grid#1173]
I have a problem with the applications joequant/sptrader.  It consists of a react ag-grid embedded in a bootstrap tab.  Version 5.2.x works fine but starting at 5.3.x, the grid will slowly shrink on the vertical axis until nothing appears.  This happens on all web browsers.  It seems that some geometry management thing changed.

**Comment by dev-oups** [comment]
Same issue within an Angular2 application with ag-grid & ag-grid-ng2 V6.1.0.

The _.ag-body_ element get its height down to 4px as well as the _.ag-floating-bottom_ element top value.

**Comment by briebug** [comment]
I'm seeing the same thing with Angular2 with ag-grid & ag-grid-ng2 V6.0.1.  A quick temporary workaround is to override the ag-root classes height like so:

.ag-root {
    min-height: 250px !important;
}

**Comment by dev-oups** [comment]
My temporary solution:

```
.ag-bl-full-height,
.ag-bl-full-height-center { height: 100%; }
```

**Comment by sstorie** [comment]
@dev-oups This kinda works but it ends up hiding any column headers in the process. I also needed to add this:

```
.ag-header {
    position: relative;
}
```

...but I haven't tested this everywhere yet.

**Comment by ceolter** [comment]
i'm 99% sure the problem is with the height that you are setting on the div that contains ag-Grid.

either you are not giving the div height, or you are using % height and not specifying height for the parent it is in (this is needed for % height to work).

the grid fills the width and height of the div you give it. so inspect your dom and work out why the div the grid is in isn't getting it's proper height.

**Comment by dev-oups** [comment]
What about flex layout ?

Setting a fixed height for one of the grid parent elements is not an acceptable solution.

**Comment by joequant** [comment]
This is going to be a particular problem for react (and angular).  The
ag-grid react element should work within the JSX framework with sensible
defaults, and if some magic is needed to get the component to work, it
should be put into the component itself.

**Comment by joequant** [comment]
Also can someone write up exactly what changed between 5.2 and 5.3.  The
5.2 behavior was quite good.

**Comment by ceolter** [comment]
change log is here: https://www.ag-grid.com/change-log/changeLogIndex.php

**Comment by fijimunkii** [comment]
Thanks @ceolter. I'm unsure why this is failing for me when inspector shows the parent div clearly has a fixed height. Not using react, but after 5.3.0 I have to control the grid height with .ag-root and window resize

**Comment by BesatZardosht** [comment]
This issue is still exist so why is it closed?
Anyone has a permanent solution?

**Comment by BesatZardosht** [comment]
I figured out what was the problem. I had updated the ag-grid but still was pointing to the old css.
Updated the css and everything works great again! 
Thanks

**Comment by sstorie** [comment]
OMG I'm seriously embarassed! Thanks for posting your solution @BesatZardosht...that was exactly what I was doing wrong.

@ceolter your library rocks btw!

**Comment by briebug** [comment]
@ceolter 
This still doesn't work for us.  I'm disappointed you have so quickly dismissed this issue and closed it.  It clearly does not work.

I'm pointing at the css located at:

```
        "../node_modules/ag-grid/dist/styles/ag-grid.css",
        "../node_modules/ag-grid/dist/styles/theme-bootstrap.css",
```

I have also added the css from @dev-oups and @sstorie.  Neither work reliably.

@ceolter - This component is something we are considering purchasing.  I have implemented your suggestions about making the outer div a specific height and it does not work.  I created a brand new project, installed the latest ag-grid (6.4.2)/ag-grid-ng2(6.4.1), mocked the data, and here is my html:

```
<ag-grid-ng2 #agGrid
             class="ag-bootstrap"
             [gridOptions]="gridOptions"
             [rowData]="rowData"
             [columnDefs]="columnDefs"
             rowHeight="22"
             rowSelection="single"
             enableColResize
             enableSorting
             suppressCellSelection="true"
             (cellClicked)="onCellClicked($event)"
             (beforeSortChanged)="onBeforeSortChanged()">
</ag-grid-ng2>
```

The grid does not display at all.  I can surround the grid with a div with a specific height, and it still doesn't display at all.  The only way I can do to make it work is to set a height on ag-grid-ng2, e.g., 

`<ag-grid-ng2 style="height: 200px">`

This is not an acceptable solution.  I hope you will reconsider your position on this issue.  If we are not able to get to a solution soon, we will need to go another direction.

**Comment by ceolter** [comment]
@briebug you have to set height on the grid, so what you are doing is correct. this is mentioned in the docs, the grid div must be given height.

ng2 example here:
https://www.ag-grid.com/best-angular-2-data-grid/
example has:
<ag-grid-ng2 #agGrid style="width: 100%; height: 350px;" class="ag-fresh"

the grid is designed to fill the height of the div you give it (or the ag-grid-ng2 tag in the ng2 instance)

**Comment by briebug** [comment]
It used to work without having to do that.  Now we end up with a double set of scrollbars for the grid and for the page.  Was there a reason for changing it to require a height?  IMO it shouldn't require a height and it should be allowed to fill up whatever container it is in.  It gives the developer the ability to restrict it to a height or allow it to expand as necessary.

**Comment by ceolter** [comment]
```Was there a reason for changing it to require a height? ```
-> we didn't change it. the design was to always require % height. for some people it wasn't needed and I don't know why, but people (such as yourself) reported it worked, which was by accident.

```IMO it shouldn't require a height and it should be allowed to fill up whatever container it is in. It gives the developer the ability to restrict it to a height or allow it to expand as necessary.```
-> direct support for that is on our radar. but not at the top of our list right now.

```Now we end up with a double set of scrollbars for the grid and for the page.```
-> if you don't want scrolls in the grid, you can change the height dynamically yourself by changing the height when the row data changes and doing some maths.

**Comment by dylanbutler** [comment]
For those interested, we found a solution that seems to work for now:

`
    .[your-grid-container] {
        height: 100%;
        .ag-body {
            position: inherit;
            height: 100% !important;
        }
        .ag-cell {
            border: none;
        }
        .ag-body-container{
            min-height: 82px;
        }
    }
`
We haven't tested this thoroughly so use it at your own risk, and it likely won't work in all scenarios because it relies on height:100%. 

Years of responsive and fluid design experience has taught us that fixed heights in general is an anti-pattern. And we shouldn't have to burn days fixing an issue that wasn't mentioned in the changelog. 

Intentional or unintentional, in my mind (and the minds of many other paying customers apparently), the code used to "work," and now it doesn't. Philosophical debate aside, for reasons of pure backwards compatibility, please put this "feature" at the top of your priority list.

**Comment by dylanbutler** [comment]
So my fix above has some issues, as expected. One of the rows is obscured, so it's not a great fix. 

@ceolter , would it be possible to pay you to bump this up in your priority list?

**Comment by crarau** [comment]
@dylanbutler solution decreased the performance of the ag-grid as all rows were being rendered.

I ended up using the solution from here https://stackoverflow.com/questions/30948667/bootstrap-fill-remaining-vertical-space

    .grid-wrapper {
        height: -webkit-calc(100vh - 72px);
        height: -moz-calc(100vh - 72px);
        height: calc(100vh - 72px);
        background-color: rgba(90,90,190,0.8);
    }
The code is calculating the available space below a given number of pixels.
The style on the grid is `style="width: 100%; height: 100%;"`

**Comment by VanyaYani-sizmek** [comment]
Why is this closed?

**Comment by thargenediad** [comment]
Yes.  Why is this closed?

**Comment by adamerose** [comment]
@ceolter I'm on 23.2.1 and it still seems like ag-grid tables will collapse to zero height unless we either

-  Define an fixed pixel height on the `ag-theme-alpine` wrapper, or...
-  Define a height of every parent component all the way up the DOM

Can this be reopened? I think this should be high priority, it makes it hard to make use of ag-grid inside projects using flex layouts

**Comment by sometimescasey** [comment]
Bumping issue in March 2023, please re-open. Setting a fixed height on a parent component is not always an acceptable solution. Why can't the table expand to the height of its contents?

**Comment by StephenCooper** [comment]
> Bumping issue in March 2023, please re-open. Setting a fixed height on a parent component is not always an acceptable solution. Why can't the table expand to the height of its contents?

A fixed height should not be required on the parent. The grid will fill its parent container when applied the style `{height: 100%}` as long as its parent is correctly sized within your application. 

We cover this in our docs https://ag-grid.com/javascript-data-grid/grid-size/
