### ISSUE TITLE
Auto-Size Columns not working properly on Internet Explorer11

### ISSUE THREAD

**Issue by depasosc** [ceolter/ag-grid#1174]
The columns are resizing according with the length of the value but on IE11 some columns names are not fully displayed. Also could you please change your example to have a long header?  This will allow to test more easily across browsers.
![aggrid-_ie_example](https://cloud.githubusercontent.com/assets/13731306/19059320/3ead59e8-899c-11e6-817e-cadb10598abe.png)

**Comment by nareshbhatia** [comment]
@ceolter, this is a show stopper for us because IE11 is the standard platform for our client. Could you please look into this? Is there a workaround that we can implement in the meanwhile? Thanks for your consideration.

**Comment by ceolter** [comment]
change property autoSizePadding, it says how many pixels to add to the autosize. default is 4 (i think) to allow for some border and padding. if you change to 6 or 8, should sole all issues for you.

this property is also dependent on what styling people are adding to the headers - so there is no 'correct' answer.

**Comment by ivansiacho** [comment]
@ceolter I've the same issue in Firefox, but this not working if we change autoSizePadding to 8, like IE. We've to change to 23 to solve all issues. So there is a big difference. The styles are the same for all browsers, so i try to figure out why only Firefox needs this value. Do you've any clue about this?

autoSizePadding = 8px
![screen shot 2016-10-14 at 7 38 51 am](https://cloud.githubusercontent.com/assets/5598171/19388059/5450bf02-91e3-11e6-9ddc-535bf5c0bd0d.png)

autoSizePadding = 23px
![screen shot 2016-10-14 at 7 39 31 am](https://cloud.githubusercontent.com/assets/5598171/19388094/7fadef4e-91e3-11e6-8e1b-1705d493ed93.png)

**Comment by ceolter** [comment]
no clue about it. i'm happy to take suggestion if anyone finds what it should be - but it's also tied to your theme (i presume, given the theme adds padding, border etc) so i am slow to have (for example) a lookup table to decide how many pixels to add based on browser, it could be different for everyone depending on platform and theme.

**Comment by madhurich** [comment]
I was facing the same issue on IE11 that autoSizeColumns wasn't working but was fine in chrome. After a lot of research I've found that in IE 11 autoSizeColumns executes before actually the grid is ready and it seems like there's not effect, for me it worked if I put a timeout or on a button click
 `function onGridReady(col){
$timeout(function(){
col.columnApi.autoSizeColumns(columnIds);
}, 800)
}`
