### ISSUE TITLE
How to access external scope within aggrid onCellClicked

### ISSUE THREAD

**Issue by madhurshome** [ceolter/ag-grid#1175]
I have a grid, on the first column cell click, I'm writing a function this.finduser.
params value gets passed in finduser paramater. I'm trying to access "this" variable of controller inside the finduser function. but its throwing error: "userService is undefined". I'm not able to access anything referenced with "this" in finduser function. Can you please suggest how to call external scope from within grid function
`export default class UserController {
    constructor(userService) {
	this.userService = userService;
	this.ColumnDefs = [{headerName: 'Username',field: 'name', onCellClicked: this.finduser}];
        finduser(params){
	let userParams = params.value;
        this.userService.find(params).then(
	response=>{},
	error=>{}
	);  } } UserController.$inject = ['userService'];`

**Comment by ceolter** [comment]
this is a javascript question. if you want access to the scope, you need to structure your code so that the listener you attach has access to it. you should not depend on this.

**Comment by anishswiss** [comment]
Try this :   onCellClicked: (deleteClickEvent) => { this.finduser(deleteClickEvent); }

**Comment by bvallambhotla** [comment]
What about gridOptions, we can pass the function  along with the gridOptions and access it using 
`rowNode.gridOptionsWrapper.gridOptions.methodtoCall()`

**Comment by Bhawna14** [comment]
@madhurshome did you got anyway to access external scopes?

**Comment by SWGeekPD** [comment]
Hi ceolter,  I want to call cellDoubleClicked event when I double click on any cell, not the cellClicked event.
I want to use both on single click cellClicked event and on double click cellDoubleClicked event. But it is always calling to cellClicked event only.
Please help
