### ISSUE TITLE
proposal: add externalised source maps to distribution

### ISSUE THREAD

**Issue by szabyg** [ceolter/ag-grid#1176]
Based on #253 it seems there used to be inline source maps generated in dist but were removed without generating externalised ones.

It makes a lot of sense to see sources in the browser for debugging purposes.

**Comment by ceolter** [comment]
not really - source maps would be for ag-Grid developers - when we're developing ag-Grid. to include them in the distribution would be adding unnecessary additional size to the distribution.

however - what you could / should do (just my opinion) is use the source files directly, if you want to see the original source files. the js files are in /dist/lib, and the TypeScript files are in /src

then you can build / compile yourself and add your own source files.
