### ISSUE TITLE
Range selection fails in some cases when using virtual rowModel

### ISSUE THREAD

**Issue by egidijusj** [ceolter/ag-grid#1177]
These are the conditions for the error:
1. You must use virtual rowModel
2. There must be empty space between last rendered row and the bottom of grid viewport.

When doing range selection and mouseleave'ing the last row, grid throws error `Cannot read property 'getGridCell' of null`. 

Here's two demos to show the difference:
- without virtual rowModel https://jsfiddle.net/y2fLf50e/1/ 
- with virtual rowModel https://jsfiddle.net/y2fLf50e/2/

**Comment by ceolter** [comment]
cool, thanks. have fixed. will be in next release. 6.2.1+
