### ISSUE TITLE
headerCellTemplate apparently cannot contain newlines

### ISSUE THREAD

**Issue by kbdguy** [ceolter/ag-grid#1178]
I'm using ag-grid-ng2, in case that matters, but this is a non-angular columnDef setup situation.

I tried using backticks (`) for my headerCellTemplate setup, and kept getting console error:

TypeError: this.eHeaderCell.setAttribute is not a function
    at RenderedHeaderCell.addAttributes

untiI l changed my code back to old-style single-line string concatenation.

For example 
              `"<span id="agText"></span>"`

works fine for a headerCellTemplate, while

      `
      <span id="agText"></span>`

(javascript preserves newline between backticks) throws the error.

This is either a bug or should be documented!

**Comment by kbdguy** [comment]
Maybe it's not actually the newline... trying some more today, it seems any "white space" at the start of the template will cause the error.

**Comment by ceolter** [comment]
the template must all fit inside one tag. you cannot start or end with whitespace or newline. this is because of how ag-Grid loads the template, it converts the template to a DOM object, eg a div or span. so your template should star/end with the same div or span (or whatever element is the root element).

**Comment by kbdguy** [comment]
Yes, I learned that the hard way.  Your product would be improved if you included this information in the documentation, as I said in the original issue.

**Comment by ceolter** [comment]
i've updated the docs (will be in next release).
