### ISSUE TITLE
Disable dragging of column indicator on RowGroupPanel

### ISSUE THREAD

**Issue by mntripathi** [ceolter/ag-grid#1179]
Hi,
I am converting my current grid implemented in swing to ag-grid based grid.
The problem I am facing:
1. I have row level grouping enabled on some columns
2. I have set rowGroupPanelShow: 'onlyWhenGrouping', to show the panel only when any grouping is applied.
3. I don't want user to drag the columns to change the column ordering. so i disabled the dragging of columns by suppressMovableColumns: true
4. But User can still drag and reorder the column if any grouping is applied, the group panel enables the column dragging. 

The span with class "ag-column-drop-cell" has mousedown event. 
what I want:
1. is there any way so that I can disable the dragging of column from group panel, or 
2. any callback function one any grouping/ungrouping happens so that I can remove the event ?
![ag-grid](https://cloud.githubusercontent.com/assets/3408377/19128343/f0eb6378-8b10-11e6-8b52-45cec166fd62.png)

**Comment by ceolter** [comment]
1. yes, please see docs for toolpanel section 'read only functions'.
https://www.ag-grid.com/javascript-grid-tool-panel/index.php

2. yes, see events
https://www.ag-grid.com/javascript-grid-events/index.php
columnRowGroupChanged

3. please read the docs!!!
