### ISSUE TITLE
To see storage for 100+k records in memory consumption

### ISSUE THREAD

**Issue by oceanofinfinity** [ceolter/ag-grid#1180]
Hi,
Was analyzing source code for ag-grid.js.
Just wanted to check how inMemoryrowmodel is storing 100+k records.
For testing i have made a loop in Javascript and loaded random 100+K records in AGGrid.
It loaded at blink of eye but on debugging in Chrome unable to figure out how browser storage is working.
Also wanted to check amount of inmemory consumed for 100+k records.
Any help regarding client(browser side) data storage  will be appreciated.

**Comment by oceanofinfinity** [comment]
Opening in forum

**Comment by oceanofinfinity** [comment]
Need documentation fro how storage is handled in Ag Grid client side(browser level).

**Comment by ceolter** [comment]
there is no storage used. if you set 100,000 rows into the grid, these 100,000 rows are just kept in the browser memory.
