### ISSUE TITLE
aggAvg function error if null/missing values

### ISSUE THREAD

**Issue by ataft** [ceolter/ag-grid#1183]
If the data for a column that's using 'avg' aggregation has any missing values, an error is thrown on line 22883 of ag-grid-enterprise:

else if (typeof currentItem.value === 'number' && typeof currentItem.count === 'number') {

this is because currentItem is undefined.

https://jsfiddle.net/andytaft/n168v3hy/2/

**Comment by ceolter** [comment]
your plunker threw ```ag-grid-enterprise.js?ignore=notused22:23173 Uncaught TypeError: Cannot read property 'value' of null```

anyway, found it. fixed. will be in next release.
