### ISSUE TITLE
Disable Move Column

### ISSUE THREAD

**Issue by avi613** [ceolter/ag-grid#1184]
Hi ag-grid people,

Is there a way to disable "move" functionality on certain columns? 

If yes, please let me know. If not, then the following is a wish list:

It could be something like: 

`{
  colId: 'blabla', headerName: 'blabla', field: 'blabla', disableMoveColumn: true
}`

with disableMoveColumn property defaultly set to false to enable column move by default, except when explicitly declared in columns definition.

Cheers,
Avi

**Comment by ceolter** [comment]
not possible. it is already requested so will close this issue. it's not so simple though, as if you have 50% columns moving, then what happens if you move another column around it?? anyway, the answer is frozen columns, columns that stay stuck on the left hand side. it's on our plan for not ETA yet, it's not scheduled into one of our releases yet.

**Comment by billytianlan** [comment]
I know this issue is closed but I have the same requirement and was wondering if this is on the roadmap now?

**Comment by wtfdaemon** [comment]
Let me second this - especially when you're doing things with custom column headers, the ability to temporarily disable drag-and-drop column behavior would be a lifesaver.

**Comment by wtfdaemon** [comment]
@ceolter

**Comment by ArekSliwa** [comment]
I understand problem. But what about not movable columns at the end? for example I would like to have standard action column, but not pinned. just I would like have it not movable and always at the end. If you can create something like that for beginning column, why not created something similar at the end?

**Comment by MikhailTatsky** [comment]
@ceolter 
 We also need the way to disable column drag.
Is there any update on it?
