### ISSUE TITLE
Row borders disappear in MS Edge (material theme)

### ISSUE THREAD

**Issue by jprince** [ceolter/ag-grid#1186]
This issue can be seen in the .gif below or on the demo (https://www.ag-grid.com/example.php) with the material theme applied.

As the user hovers over rows, from bottom to top, the border separating the rows disappears. As they hover from top to bottom the border reappears.

![edge](https://cloud.githubusercontent.com/assets/3384090/19201627/a045b6a2-8c9c-11e6-8b9f-3ddea6c1f2a4.gif)

**Comment by ceolter** [comment]
cannot reproduce. i tried locally on edge and it's working fine.

i'm wondering though - is it to do with your scaling? ie are you zooming your browser in our out, and maybe IE is then skipping a line of pixels?

to be honest, i'm not very worried, this seems like a minor issue if only on some instances of edge.

**Comment by jprince** [comment]
You're correct - I'm on a Mac and running Edge in a Windows VM and it looks like my Edge version is out of date. I had a co-worker test it on the latest Edge, on Windows, and the issue is resolved; looks like Edge must have patched something on their side. Closing this issue.

**Comment by GeorgeKnap** [comment]
Hi
I can confirm this on Endge version 14 and 15 (latest now). See the recorded gif:
[http://imgur.com/a/RmJDa](http://imgur.com/a/RmJDa)

It is like this on ag-grid website and in my Angular app :)
oh and the zoom is at normal 100%
George
