### ISSUE TITLE
Provide API method: autoSizeAllColumns(boolean: expandToFitGridWidth)

### ISSUE THREAD

**Issue by nkoterba** [ceolter/ag-grid#1188]
First 👍 for the awesome Javascript Grid implementation.  

We have a use case in our product where we need to display a variable size width table with only a *single* column.

Unfortunately, we noticed that when the table is wider than the content in the rows in the single column, we get a gap between the table and the column rows.  See picture:
![image](https://cloud.githubusercontent.com/assets/2508944/19202205/2b09f06c-8c9f-11e6-89a3-e83caf1b4dcc.png)

We can eliminate this gap by calling `gridOptions.api.sizeColumnsToFit()`.  

However, if our row content is *larger* than the table width, then we do not get a horizontal scroll bar and the content is clipped and users need to see or scroll to see the content.  See picture:
![image](https://cloud.githubusercontent.com/assets/2508944/19202249/668dcabe-8c9f-11e6-9c53-2876b63efc37.png)

To solve this situation, we can call `gridOptions.columnApi.autoSizeAllColumns()`.

But there's no `ag-grid` method or way to correctly resize a column to fill the table if its content < table width *OR* resize a column to fit its content if its content > table width.

We implemented a working solution that we `debounce` on both `gridSizedChanged` and `gridDataChanged` and everything works great...except we had to rely on **internal** ag-grid APIs which we know can and may change.

Here is our implementation: 
```javascript
_updateColumnWidth() {
	if (!this._debouncedUpdateRowWidth) {
		this._debouncedUpdateRowWidth = _.debounce(() => {
			let onlyColumn = _.first(this.gridOptions.columnApi.getAllColumns());

			if (onlyColumn) {
				let colWidth = onlyColumn.gridOptionsWrapper.columnController.autoWidthCalculator.getPreferredWidthForColumn(onlyColumn);
				let gridWidthForColumns = this.gridOptions.api.gridPanel.getWidthForSizeColsToFit();

				if (colWidth < gridWidthForColumns) {
					this.gridOptions.api.sizeColumnsToFit();
				} else {
					this.gridOptions.columnApi.autoSizeAllColumns();
				}
			}
		}, 1000);
	}

	this._debouncedUpdateRowWidth();
}
```

I recognize our situation is somewhat unique since we only have a table with *1* column but I believe this logic could be updated to support multiple columns with a behavior where: columns would never be smaller in width then their largest content width and if all the columns didn't fill up the width of the grid, the last column width would be adjusted (or perhaps each column width is increased by `(extra gap width/total number of columns)` to equally space out columns.

Suggested api call would be: `autoSizeAllColumns(boolean: expandToFitGridWidth)`

If `expandToFitGridWidth = false`, then existing `autoSizeAllColumns` behavior is applied.  If `expandToFitGridWidth = true`, then the last column is re-sized to fill any "gap" remaining in the grid OR each column is increased in width by (gap width/total number of columns).

**Comment by ceolter** [comment]
thanks for the compliments.

i'm sure you can do this with the current api.

```
gridApi.sizeColsToFit();
var widthAfterSizeColsToFit = columnApi.getColumn('myCol').getActualWidth();
gridApi.autoSizeAllColumns();
var widthAfterAutoSize = columnApi.getColumn('myCol').getActualWidth();
if (widthAfterSizeColsToFit > widthAfterAutoSize) {
  gridApi.sizeColsToFit();
}
```

the only item not in the documented API is column.getActualWidth(), but that's not going to change, it's core to how the columns work and i'm happy with it (no plan to change it).

**Comment by nkoterba** [comment]
@ceolter thanks for the response to the feature request.

I was concerned that calling the `sizeColsToFit` and `autoSizeAllColumns` might cause unnecessary processing and/or DOM thrashing (haven't looked into source code for those methods to see what they actually do).

We were attempting to try to call the "least" expensive methods.  If the above public API calls are indeed "low-cost", then I will update our "fix" to use your suggested code snippet.

As for the enterprise license, I will put in a good word with our company's president :)

**Comment by ceolter** [comment]
```sizeColsToFit and autoSizeAllColumns might cause unnecessary processing and/or DOM thrashing``` - not really, it's only resizing things, not creating / removing much in the dom, and if you call them in the same VM turn then you only have one DOM re-flow after both are finished.
