### ISSUE TITLE
Feature Clarification/Request-- Prevent columns from being added to group

### ISSUE THREAD

**Issue by aniedACN** [ceolter/ag-grid#1189]
Greetings--
I am writing to attempt to see if I am misunderstanding the API in regards to groups and movable columns.  As I understand it, movable columns can be moved between groups _unless_ the `marryChildren` flag is set to `true`.  For example, if I have a group called **GroupA** and I set `marryChildren: true`, the child columns in **GroupA** will be prevented from moving out of the group.  However, it does nothing to prevent movable columns from _other_ groups to be moved _in_-- so while I cannot move child columns out of **GroupA**, I can move other columns that are ungrouped, or in **groupB** or **groupC** _into_ **GroupA**.

Is this by design?  If so, is there a flag that can be set to prevent new child columns from being added to a group?  Perhaps a `preventAdoption` or something of the like?  And if not, is it a planned feature?  Please let me know when you are able.

Thanks!

**Comment by ceolter** [comment]
what you say is almost right. you cannot split the group if marrychildren=true. eg see the example on marry children on this page:
https://www.ag-grid.com/javascript-grid-grouping-headers/index.php

it is impossible to break up the first group. it is also impossible to move on of the other columns into the group, ie dragging 'sport' column to the left, you cannot insert it between 'athlete' and 'country'.
