### ISSUE TITLE
请求的json数据太大导致表格显示过于缓慢的问题

### ISSUE THREAD

**Issue by LPink777** [ceolter/ag-grid#1190]
如果我发送一个请求返回的json数据太大，这样一次都请求过来的话会花费很长时间，所以我要怎么结合ag-grid做页面优化

**Comment by LPink777** [comment]
@ceolter

**Comment by ceolter** [comment]
i don't speak whatever language that is!! sorry!

can you put it into english?

**Comment by LiJing890** [comment]
@ceolter LPink777 mean：
If I send a request to return the JSON data is too large, such a request will take a long time, it will take a long time, so I want to how to combine the ag-grid do page optimization

**Comment by LPink777** [comment]
@LiJing890  thank you  help me to  translate

**Comment by ceolter** [comment]
thanks for the translation!! it helps a lot :)

you have 2 options for pagination, see them explained here:
https://www.ag-grid.com/javascript-grid-pagination/index.php
https://www.ag-grid.com/javascript-grid-virtual-paging/index.php

for each of these, you will need to implement something on your server, to read in the json file, and then to provide it to your client as it's needed via the datasource.
