### ISSUE TITLE
Ag-grid-react-demo

### ISSUE THREAD

**Issue by danielpetrov** [ceolter/ag-grid#1193]
Hi! I am currently working with ag-grid and react and redux. I can say that your demo is awfull and almost made me give up ag-grid. But I found a ways to properly use Ag-grid with react and redux in the redux way. So I can contribute and make a new demo for you to show on your site. This will be no problem, just write me back if you want, I will do it for free. I also want to report what is some kind of a bug or unexpected behavior. It happens when you edit your data inside your cell and call an action on onCellValueChanged event. It actually goes and changes your store data. It is dynamic and I like it because I work with dynamic data, but I think this bug/feature should be described as a one big WARN, becaouse it is unexpected behavior. You should only change your store data through actions and reducers should handle those changes. This shouldn't normally happen in some external application like the ag-table.

**Comment by ceolter** [comment]
@danielpetrov thanks for the ping. we appreciate any help we can get. we are a small team and try our best, but never do we claim to know more than that general world of users. there is defiantly things we can be helped on.

if you want to provide a demo, we will pay you something for it - as we want to be fair - or at least give you a nice present like an iPad or something.

anyway - for a demo to be useful, it must have proper documentation, both in our docs, and also great comments in the code.

currently the demo has two grids - the standard and large. do you want to create a third? or would it be better to dispose the other two entirely? what you can do is create a third option and then propose a pull request. the documentation project you can also contribute to ag-grid-docs, maybe create a new page, and then we can copy / paste it into the main react page when it's all done (to minimise any merge conflicts).

let me know what you think.

ps - i don't check github regularly (we get hit to much) and am about to take two weeks holidays. however you can ping me on accounts@ag-grid.com (i'll reply, then you have my personal email, i dont want to post my email here)

having answered your question, i'm closing the issue :)

**Comment by danielpetrov** [comment]
I don't like both of your demos. React is nice to use when you can abstract
the state to a store e.g. use a flux pattern. The best implementation of
flux pattern is Redux. So most of the people that are using React are
actually using React&Redux. Your demos dosn't suggest how a developer
should do that. Also they are breaking some basic principles of using
React. I will provide you with more high-qulaity demo, that is easyer to
read. Also the demo will include not only React but Redux. We managed to
work more with the Ag-Grid ( we are using the paid version right now ). We
are mirroring the whole state of the table in external storage - the Redux
store. I don't have much time right now, as we are chasing some deadlines.
As soon as I get a bit free I will contribute.
P.S. I love new techs, just don't send me anything that can explode :)

2016-10-12 13:41 GMT+03:00 Niall Crosby <notifications@github.com>:

**Comment by ceolter** [comment]
sorry for late reply, i was busy getting married and doing conferences. happy to have you contribute. when you have more time, we can talk more :)

**Comment by ceolter** [comment]
ps - as mentioned, for this, use email, i don't check github very often, i try to get my head down coding instead.

**Comment by danielpetrov** [comment]
Hi! Happy new year! I am ready to start working on updating the demos for
ag-grid with react and redux. I have experiance with both.
I will try to cover what I think is nececary in the demo and I will leave a
lot of describesive comments. Then you can review to check if I missed
something. Or if this workflow doesn't suit you can point out exactly what
needs to be included.
I really like those:
https://www.amazon.com/gp/product/B01KHZ4ZYY/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=jims03-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B01KHZ4ZYY&linkId=3560c337ba18d04f1162b43f5b3de1c7
So maybe this can be the reward for my efforts.
Are you still intrested? I can be ready in worst case scenario at the end
of the month.

2016-10-28 19:00 GMT+03:00 Niall Crosby <notifications@github.com>:

**Comment by danielpetrov** [comment]
Hi Daniel,

Happy new year to you also, I hope you enjoyed the festive season.

All sounds good with regards your help, and your choice of gift sounds very
reasonable!

I've put Sean onto the email - he is currently working on all the
frameworks side of things including getting up to speed on React and Redux
so it would be great if you could sync with him.

Thanks,
Niall.




Niall Crosby
Founder & CTO
<https://www.linkedin.com/in/niallcrosby>  <https://twitter.com/ceolter>
<https://github.com/ceolter/ag-grid>

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.
