### ISSUE TITLE
special characters in the table

### ISSUE THREAD

**Issue by paradicey** [ceolter/ag-grid#1196]
@ceolter Hi, I am working with some financial data, mostly the price will have special character such as:
19-27&amp;#8542;
it is showing as regular table would show in ag-grid. 
Would you please shed some light?
Thanks.

**Comment by paradicey** [comment]
Figured a way using cellRenderer: priceRenderer
function priceRenderer(params) {
    var eDiv = document.createElement('div');
    eDiv.innerHTML = '<span>'+ params.value + '</span>';
    return eDiv;
}

**Comment by ceolter** [comment]
thanks for posting solution. in our example we show the pound sign - so you could do similar?

**Comment by paradicey** [comment]
yes. that's the gist of it.
