### ISSUE TITLE
mouse hover functionality like google inbox

### ISSUE THREAD

**Issue by nishantgirbar** [ceolter/ag-grid#1197]
Hi,

I wanted to know is there mouse hover functionality available into ag-grid for angular 2 so that I can build same functionality as there is available on google inbox ?
![googleinbox](https://cloud.githubusercontent.com/assets/18031306/19314067/60cacf58-90b6-11e6-877c-86334e534775.png)

Thanks,
Nishant Kumar

**Comment by ceolter** [comment]
no there is not. you are looking for mouse hover over row right?

what you can do is add your own over functionality using the callback processRowPostCreate(), here you could add event listeners for mouse in and mouse out to achieve the effect you want.

**Comment by nkoterba** [comment]
@ceolter In lieu of adding 1,000s of Row listeners, I know that best practice is often to listen to the parent container's mouseenter/mouseleave/mousemove events and then try to determine the hovered item by using its position offset in parent.  Identifying the offset of course is no trivial matter.  I don't suppose there's an ag-grid API call or private API method that would return the specific row under the current mouse position?

**Comment by AngeiMachi** [comment]
+1

**Comment by AngeiMachi** [comment]
+1 is there something like this today @ceolter ?

**Comment by AngeiMachi** [comment]
+ @ceolter  How to implement this today in Angular 5?

**Comment by darge98** [comment]
Hi, i want to know how to implement this now (Angular 5). Thanks

**Comment by JabbyPanda** [comment]
@darge98 @AngeiMachi you can use existing `onCellMouseOut` and `onCellMouseOver` events as of today and set 'hovered` property on Row Node object

```
<Datatable          
          onCellMouseOver={d => this.onCellMouseOver(d)}
          onCellMouseOut={d => this.onCellMouseOut(d)}

...
onCellMouseOver(d) {
    // eslint-disable-next-line no-param-reassign
    d.node.hovered = true
    this.gridApi.refreshCells({ force: true })
  }

  onCellMouseOut(d) {
    // eslint-disable-next-line no-param-reassign
    d.node.hovered = false
    this.gridApi.refreshCells({ force: true })
  }

```
Later in your cell renderer you can read Row Node 'hovered` value

**Comment by smile2014** [comment]
@JabbyPanda  When the mouse enters the button, multiple lines of data will have buttons, how to disable the focus of the button

**Comment by lingaiah-danda** [comment]
is there any way to show buttons like gmail using oncellMouse over, can we achieve this without using cell Renderer?
