### ISSUE TITLE
ag grid tree view selected node

### ISSUE THREAD

**Issue by safeerk** [ceolter/ag-grid#1198]
Hi unable to track the selected node in the Tree view structure..

 gridOptions.api.forEachNode(function (node) { 
                    if (node.data.AccountName === 'XYZ') {
                        node.setSelected(true); 
                    } 
                });

Though this stuff didnt allow me to work.?

**Comment by ceolter** [comment]
works for me. in the example here: 
https://www.ag-grid.com/javascript-grid-tree/
i changed the onGridReady to the following, and it successfully selected the row:
```
    onGridReady: function(params) {
        params.api.sizeColumnsToFit();
        params.api.forEachNode(function (node) {
            if (node.data.athlete === 'Janica Kostelic') {
                node.setSelected(true);
            }
        });
    }
```
