### ISSUE TITLE
license key encryption

### ISSUE THREAD

**Issue by paradicey** [ceolter/ag-grid#1200]
@ceolter Is there a way to avoid clear text license key described in here:
[https://www.ag-grid.com/javascript-grid-set-license/index.php](url)

Thanks.

**Comment by ceolter** [comment]
no - your license key will be available to the public. the best you can do is minify your code.

however we are not worried - if someone wants to pirate ag-grid, it's easy download the project and disable the license check - because we are javascript, there is not much we can do here.

**Comment by SWGeekPD** [comment]
@ceolter , I am having a valid enterprise License , while testing ag-grid component using Jasmine test cases, I am getting "License not valid" error in karma console. Do we need to inject license in beforeEach section of jasmine also to avoid this. 

import {LicenseManager} from "ag-grid-enterprise/main";
 beforeEach(() => {
LicenseManager.setLicenseKey("your license key");
});
Like this.
This solves the problem but I am thinking if this is the correct way of doing so. Please suggest.
