### ISSUE TITLE
Context Menu in Angular2 project

### ISSUE THREAD

**Issue by nunna-suma** [ceolter/ag-grid#1204]
I'm trying to implement the context-menu in my angular2 project. so , that whenever right-click on rowitem it has to show the menu with copy,alert like these options. I tried to place the syntax and functionality in coding but no use it is not working and there is no errors also.

can anyone please help me to slove these issue 
Thanks in advance.

**Comment by seanlandsman** [comment]
Please create an issue in the ag-grid-ng2 project for this - this is for the core ag-grid project

**Comment by ceolter** [comment]
....however, if you are trying to create a context menu, this is nothing to do with Angular 2

if you are trying to use the grid's context menu, this is only available in ag-grid enterprise.

if you are trying to use context menu event - well what you do with the event is up to you - now sure what the question is to be honest.
