### ISSUE TITLE
Can't disable filters that are enabled by default (touch device)

### ISSUE THREAD

**Issue by Ruud-cb** [ceolter/ag-grid#1205]
On touch devices (also with chrome dev tools), when press and hold an table column header, a box popup shows to filter on the data. 

Any temporary workaround? I have some other right-click behavior on the table column headers.

According to this documentation I should set all 3 variables to true to suppress the menu.

https://www.ag-grid.com/javascript-grid-column-menu/index.php

This does not work. I see it is an enterprise feature but it would be a bit weird to not be able to hide something I don't need.

Setting `suppressToolPanel`, `suppressMenu` and `suppressFilter` on each individual column doesn't  help as well.

**Comment by ceolter** [comment]
i'm going to review the touch and menu options - in hind sight, i now think the column menu should appear when you context menu click, which you should be able to turn off as an option.

then the touch support should do nothing, ie the 'long hold' should result in a context menu click, which should do the above.

in the mean time, just for you, i've stuck in a property 'suppressTouch', to turn off the touch i put in. will be in tomorrows release.
