### ISSUE TITLE
when sorting is enabled, moving a column will also sort it.

### ISSUE THREAD

**Issue by Ruud-cb** [ceolter/ag-grid#1206]
The new feature for moving columns on touch devices works well. However, when sorting is enabled, a column will also be sorted when moving, on both touch and desktop.

FYI: There are also some console debug messages printed when moving a column.

**Comment by ceolter** [comment]
re console logs, thanks, i have taken these out.

re sort getting called, i cannot reproduce, i've tried on iPad Pro and my Android phone. can you advise what you are on?

when i touch and drag, the column moves, but no sorting happens.
