### ISSUE TITLE
Validate cell before 'cellValueChanged'

### ISSUE THREAD

**Issue by somiclds** [ceolter/ag-grid#1210]
I want to allow numeric input only.

I am able to validate input in my custom cellEditor, but how to handle input when it is pasted from clipboard, before cell value is changed? 
Currently, I can catch 'clipboardPaste' event, but there is any properties so I could get pasted value.

**Comment by ceolter** [comment]
Just added this: processCellFromClipboard(), to allow you to change data as it's been copied from the clipboard. Will be in next release.

**Comment by swalters** [comment]
@ceolter I can't find this anywhere in docs

**Comment by ceolter** [comment]
@swalters 

mentioned here:
https://www.ag-grid.com/javascript-grid-callbacks/

also in example here:
https://www.ag-grid.com/javascript-grid-range-selection/

**Comment by MaximBalaganskiy** [comment]
I think this event is useless as it does not provide any information on cells being pasted to
