### ISSUE TITLE
Is it possible to place a button on a column selectively

### ISSUE THREAD

**Issue by suncds** [ceolter/ag-grid#1211]
I have a column in the grid in which the button should only populated for certain cells,  in a column
The column contains a string value, so I'd like to only style certain cells within this column with a button

**Comment by suncds** [comment]
I am working with angular2, BTW

**Comment by ceolter** [comment]
yes, provide your own cellRenderer. the init() method gets the params, where you can get details about the row. then decide in your renderer what you want to do.
