### ISSUE TITLE
Click to button row expand also trigger onRowClicked event

### ISSUE THREAD

**Issue by ildarnm** [ceolter/ag-grid#1212]

**Comment by ceolter** [comment]
is this a question or a statement? please provide a description as to what you mean!!

**Comment by ildarnm** [comment]
It is statement and I think it is bug. I think click on row expand button shouldn't trigger onRowClicked event.

**Comment by ceolter** [comment]
could argue this either way. so i'd like to leave it as it is, so it doesn't break anyone who depends on it the other way around.

the event that is fired contains the original mouse event, so you can see the path the event took. so your listener can check if it came from the expand icon or not (by checking the attributes or class on the target element).
