### ISSUE TITLE
Column's filter does not work when filterChangedCallback is present on settings

### ISSUE THREAD

**Issue by carloshpds** [ceolter/ag-grid#1213]
```
{
  headerName: 'company'
  field: 'name',
  pinned: 'left',
  filter: 'text'
}
```
These settings perfectly work, but when i try to add filterChangedCallback, my callback is called but the column's filter does not work anymore.
```
{
  headerName: 'company'
  field: 'name',
  pinned: 'left',
  filter: 'text',
  filterParams: {
    filterChangedCallback: function(){
      console.log('filterChangedCallback', ctrl.gridOptions.api.getFilterModel());
    }
  }
}
```

**Comment by ceolter** [comment]
wow!!!!! don't do that!!!!!

filterChangedCallback() is provided by the grid to your filter, you call it when your customer filter changes.

if you provide your own filterChangedCallback(), then this overrides the grid's one, and the grid never knows when the grid changes.

see the documentation on creating customer filters on how filterChangedCallback() should be called.

i don't know what you are trying to do, but it's is not achieved by providing your own filterChangedCallback!!!!!

**Comment by carloshpds** [comment]
Oooh @ceolter, got it! That's my bad.
The `onAfterFilterChanged` callback works fine to me. 

But is there any way to know if an specific filter changed? Something like to know if an specific column's filter has changed.

**Comment by ceolter** [comment]
@carloshpds no way to track one particular filter. if you implemented your own filter, you could put it in there, but no with the filters that are provided.
