### ISSUE TITLE
groupRowInnerRenderer does not seem to fire lifecycle methods

### ISSUE THREAD

**Issue by quassnoi** [ceolter/ag-grid#1214]
https://jsfiddle.net/q9nxjywb/

When I expand and collapse the groups, the grouping rows below the one I'm triggering seem to be re-initialized (e. g. when you expand or collapse United States, Russia and Australia get re-rendered).

However, `destroy` does not seem to be ever called for the old rows.

I'm using some custom components to render the grouping rows in my project so I expected each `init` to be accompanied by `destroy` at some point so that I can destroy my component gracefully.

**Comment by ceolter** [comment]
moved to forum
https://www.ag-grid.com/forum/showthread.php?tid=4297
