### ISSUE TITLE
Feature Request: Floating row constraint

### ISSUE THREAD

**Issue by Siern** [ceolter/ag-grid#1216]
My case: 
I have a grid with floating rows. While there are normally no more than 4 of these, there is the edge case that more that 4 entries could appear.  This is due to the rows being related to the current set but not being a part of the actual datagrid data set.

Desired Feature:
What is desired is an ability to constrain the floating rows to X rows, while not throwing out data.  Hence, after X elements scroll the floating row viewport.  I do realize that this means a second scroll in the data grid is required for the compromise.

Or perhaps there exists a constraint for these views (and I just managed not to see it).

I have looked into controlling this with styles, but it appears your calculating heights and absolute positioning the header, top, bottom and body.

**Comment by ceolter** [comment]
this is to specific to include in the grid, we keep the grid as standard as possible, if we were to include items that 0.5% of people would use, then the grid would become far to complex for 95% of users.

the whole idea of floating rows is similar to pinned columns, you should not have scrolls in them.

what you could do is look at master / slave, this might give you what you are after:
https://www.ag-grid.com/javascript-grid-master-slave/index.php
