### ISSUE TITLE
[Feature request] Hook into column virtualization process to apply automatic resizing

### ISSUE THREAD

**Issue by simoneb** [ceolter/ag-grid#1217]
From the docs:

> To get around this, you can turn off column virtualisation by setting grid property suppressColumnVirtualisation=true. So choice is yours - what do you want - column virtualisation working OR auto-size working on off screen columns.

Would it be possible to provide a hook so that when a column is rendered on the screen it is possible to operate on it, i.e., automatically resize it?

**Comment by ceolter** [comment]
there is an event virtualColumnsChanged, this tells you when virtual columns have changed - however the grid rendering also listens to this, so you may need to put what you want to do into a timeout, so you can then tell the grid to do something after the new columns are rendered.

there is also a columnApi.getAllDisplayedVirtualColumns() method - that returns the virtually rendered columns. so you can work out what 'new' columns are rendered.

**Comment by simoneb** [comment]
@ceolter thanks, that works
