### ISSUE TITLE
[model new] FEATURE: TreeData (or Flower Nodes) with Virtual Scrolling Data Model

### ISSUE THREAD

**Issue by nkoterba** [ceolter/ag-grid#1219]
It sounds like `ag-grid` provides powerful support for master/detail as well as flower and even "nested" rows: https://www.ag-grid.com/javascript-grid-master-detail/index.php

However, everything I can find indicates that:
- grouping
- tree data
- flower nodes
- child panels
- master/detail grids

all require  the `In Memory` data model.  This appears to limit the extensibility and functionality of `ag-grid`, in particular the ability to load remote/virtual data yet have it expand or display additional related information (which ideally could be fetched on demand as the row is expanded to reduce data/DOM bloat in the browser until the user actually needs to use it).

We recognize that one of the _primary_ limitations of expanding rows in a `virtual` paging model is calculating the _height_ of the "virtual" scrollbar.

However, if the "expanded" entities had a pre-defined (e.g. `gridOptions.expandedContentHeight`) fixed or known height, I don't see how this is any technically different than how virtual paging currently works where the overall height is "estimated" and manipulated as more information is obtained on the actual true # of data records.

A callback similar to `getRowHeight` could be provided for expanded content to even potentially provide dynamic expanded content row height.

Are there other technical concerns preventing this useful expansion in `ag-grid` functionality?

We have successfully implemented this functionality in `ui-grid` and it works quite well:
![image](https://cloud.githubusercontent.com/assets/2508944/19666658/ddc11b9a-9a19-11e6-9cc8-87672d5aa506.png)

![image](https://cloud.githubusercontent.com/assets/2508944/19666663/eb992b90-9a19-11e6-8fae-83349d2d0fa8.png)

Unfortunately, `ui-grid` is badly performant due to the sheer # of watches it creates (it creates over 2500 in our UI on just a simple table) and we'd like to switch to `ag-grid` but without virtual paging support for any of the items above, we will have to remain using `ui-grid`.

**Comment by ceolter** [comment]
having server side grouping and pivoting is something we indent working on in Q1 2017. thanks for raising, it's on our radar.

**Comment by psumstr** [comment]
@nkoterba I ran into the same issue and worked around it the following way:
```        
onGridReady: function(params) {
            this.api = params.api;
            this.columnApi = params.columnApi;
            var gridBody = document.getElementsByClassName('ag-body-viewport')[0];
            gridBody.addEventListener('scroll', function() {
                if (gridBody.scrollHeight - $(gridBody).height() - gridBody.scrollTop < 200 && moreData) {
                    //request data and setRows
                }
            });
        }.bind(this)
```
In my scroll callback, I check if I'm close to the bottom of the scroll area and if I have additional data to request. When I request the new data, I append it to the previous set of rowData array. Then when I set the concatenated data, it looks similar to virtual scrolling. The downside to this workaround is that your rowData keeps growing as you append more data to it and you need to manage the number of "pages" if it becomes to big.

**Comment by nkoterba** [comment]
@psumstr So you are using the In-Memory Row Model and just manually adding data to the `rowData` array when scroll gets close to bottom?

And this works with "expandable" flowers or nodes?

**Comment by psumstr** [comment]
@nkoterba Yeah, it seems to be working fine. I opened an unrelated tree data bug today which happens independently of this approach.

**Comment by psumstr** [comment]
@nkoterba BTW, the bug I just mentioned above seems to have been fixed in the freshly released 6.3.0

**Comment by ceolter** [comment]
tracked by AG0150
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by ceolter** [comment]
the new Enterprise Row Model covers this - please take a look. it allows grouped data that is loaded in infinite scrolling fashion.

**Comment by rgansevles** [comment]
> having server side grouping and pivoting is something we indent working on in Q1 2017. thanks for raising, it's on our radar.

Does the new Enterprise Row Model cover both server side grouping and pivoting?
