### ISSUE TITLE
valueGetter specific to quick filtering

### ISSUE THREAD

**Issue by bkmorimoto** [ceolter/ag-grid#1221]
We are running into an issue with using the quick filter for custom cell renderers.

We built a custom dropdown cell editor where the values stored in the grid are IDs, but the values displayed are strings. We want to use the quick filter to filter based on the displayed strings rather than the stored IDs.

Looking at the aggregateRowForQuickFilter function in the FilterManager, it uses getValue of the valueService to return which value to concatenate, where we can take advantage of the valueGetter of the column definition to modify what we want to filter on. In this case, we would create a valueGetter to retrieve the proper string.

The issue is that we **ONLY** want the valueGetter to be used when creating this string to quick filter on. We do not want the valueGetter to execute at any other point (especially when populating the grid/retrieving data from the grid). Is there something we can do to achieve this?

**Comment by eberhara** [comment]
+1... 
I am having the same problem rendering complex objects / components.

**Comment by ceolter** [comment]
"I am having the same problem rendering complex objects / components."
-> put a toString into your object, this will then get used.

with regards the first point, i intend having the quick filter string customisable - ie have a callback so you can change it.

how about if we have a callback like this:

```
function quickFilterTest(params) {
  return convertValueToSomething(params);
}
```

where params would have a) the value b) the string the grid wants to use (so you can return this by default) c) the rowNode d) the column

that would work right???

**Comment by bkmorimoto** [comment]
This sounds like it would work. Would the callback live on the column definition?
When can we expect this to be implemented?

Thanks for the quick reply.

**Comment by eberhara** [comment]
+1 for the callback to live on the columnDefs

**Comment by ceolter** [comment]
i'll stick it to my (long) list, expect sometime in the next 4 weeks

**Comment by ceolter** [comment]
this is done, will be in a release we are doing later today.

```
colDef = {
    headerName: "D", field: "d",
    getQuickFilterText: function(params) {
        return params.value.name;
    }
}
```

new release comes with an example, docs will be updated
