### ISSUE TITLE
exportDataAsCsv exports [object Object] on complex data

### ISSUE THREAD

**Issue by eberhara** [ceolter/ag-grid#1222]
Hi, 
I am currently having problems with ag-grid when working with complex object data and react components.
I raised this [ag-grid-react issue #44](https://github.com/ceolter/ag-grid-react/issues/44), but got no response.

Basically this is the code I am running:

```
import MyComponent from '../components';
const columnDefs = {
    ...
    cellRendererFramework: MyComponent,
    keyCreator: ({ value }) => (
        value.firstName
    ),
};

<AgGridReact
    ...
    columnDefs={columnsDef}
    quickFilterText={this.state.quickFilterText}
/>
```

My cell value (value passed to the react component) looks like this: `const value = {firstName: 'First', lastName: 'Last', picture: 'picture.png'};`.

The grid is considering the value of the cell like `[object Object]`. I could find this out due to 2 facts:
- grid returns all rows when I type `[object object]` into quickFilterText.
- when I `this.api.exportDataAsCsv()`, it returns me a CSV with `[object Object]` in all cells containing a react component.

Does anyone know if I should use any param (other than `keyCreator`) to fix those 2 scenarios? I

**Comment by ceolter** [comment]
this was answered in the react link above

**Comment by shasankjabade** [comment]
@eberhara @ceolter I couldn't find the link and solution for this. Can u please help me? I'm also facing the same issue.

**Comment by yash5862** [comment]
Above link is not found. Any updates on this??

**Comment by hoangdinhcong** [comment]
@shasankjabade  @yash5862 @eberhara 
I'm facing the same issue.. 
I found this nice article and it works well.

https://medium.com/netcompany/using-hidden-columns-to-customize-export-files-in-ag-grid-a040d0a97dd

   ```
 exportExcel(): void {
        this.gridOptions.api.exportDataAsExcel({
            processCellCallback: (params: ProcessCellForExportParams) => {
                const { value, column } = params
                .......
                return params.value?.name
            }
        });
    }
```
