### ISSUE TITLE
styling the pagination component

### ISSUE THREAD

**Issue by deepakjan** [ceolter/ag-grid#1223]
Hi is there any option for including the custom pagination look and feel for the ag-grid such as 

![image](https://cloud.githubusercontent.com/assets/8823937/19741628/4cc09310-9b76-11e6-8167-41ae90706ac4.png)

Please let me know thanks?

**Comment by ceolter** [comment]
no - but we plan to rework the pagination panel later this year, which will also mean customisable templates for it.

**Comment by ssjtux** [comment]
I think you can style it your self with, for instance, the one I use is this:<br />
![screenshot from 2017-11-10 11-32-46](https://user-images.githubusercontent.com/3635549/32645030-2df64720-c60b-11e7-94ae-fe4c4bf3793e.png)

**CSS:**
    .ag-header-row {
      border-bottom: 1px solid #ccc;
      border-top: 1px solid #ccc;
    }
    .ag-header-cell-resize {
      width: 1px;
      height: 70%;
      background-color: #ccc;
    }

    .ag-paging-panel {
      float: right;
    }

    .ag-paging-button {
      border: none;
      background: #fff;
    }

    .ag-paging-row-summary-panel {
      text-align: right;
    }

    .ag-cell-label-container,
    .ag-header-cell-label {
      height: 100%;
    }

**JS:**(font-awesome)
    $("button[ref=btPrevious]").html('<i class="fa fa-step-backward" />');
    $("button[ref=btFirst]").html('<i class="fa fa-fast-backward" />');
    $("button[ref=btNext]").html('<i class="fa fa-step-forward" />');
    $("button[ref=btLast]").html('<i class="fa fa-fast-forward" />');

**Comment by stherrienaspnet** [comment]
How can I change the height properly of the pagination panel? 
Using this css rule work until user go in browser fullscreen (F11) wich produce a new scrollbar
.ag-theme-material .ag-paging-panel{
  height: 32px;
}

**Comment by shishiru16** [comment]
how to move the pagination to top of the grid
