### ISSUE TITLE
sizeColumnsToFit issue

### ISSUE THREAD

**Issue by rajgopalk** [ceolter/ag-grid#1224]
Iam applying sizeColumnsToFit to grid.it works fine but it will show a horizontal scrollbar.scrollbar covers upto the width of vertical scrollbar.
my code:
    $scope.gridOptions = {
            columnDefs: columnDefs,
            debug: true,
            rowData: null,
            angularCompileRows: true,
            rowGroupPanelShow: 'always',
            enableFilter: true,
            enableSorting: true,
            rowSelection: 'multiple',
            enableColResize: true,
            rowModelType: 'pagination',
            paginationPageSize: 100,  
            onGridReady: function (event) {
                event.api.sizeColumnsToFit();
            }

Screenshot:
![1](https://cloud.githubusercontent.com/assets/22521609/19761833/78b3e82a-9c05-11e6-8b5b-44312b3318d5.PNG)

**Comment by ceolter** [comment]
the grid is autosizing before the scrolls are visible.

change to this:
```
onGridReady: function (event) {
   setTimeout( function() {
     event.api.sizeColumnsToFit();
   }, 0);
}
```
