### ISSUE TITLE
forPrint option breaks ag-grid

### ISSUE THREAD

**Issue by dlvx** [ceolter/ag-grid#1225]
I´m doing this with React. Giving the forPrint option set to true. I´m having two different errors:

This one when having supressHorizontalScroll="true"
- gridPanel.js:144 Uncaught TypeError: Cannot read property 'style' of undefined

Specifically in this block of code:

`if (this.gridOptionsWrapper.isSuppressHorizontalScroll()) {
            this.eBodyViewport.style.overflowX = 'hidden';
        }`

The other one (if I set supressHorizontalScroll to false) is this one:
- gridPanel.js:243 Uncaught (in promise) TypeError: Cannot read property 'addEventListener' of undefined

Specifically in this line of code:

`this.eBodyViewport.addEventListener('contextmenu', listener);`

Both end up in the grid not displaying at all.

Is there other property I may be missing or is this something not supported for the ag grid React component?

BTW: I have very few rows at this moment

Thanks

**Comment by ianbeks** [comment]
Upgrading to latest version fixes this issue.

**Comment by ceolter** [comment]
```Upgrading to latest version fixes this issue.``` -> if this is true, then closing issue???
