### ISSUE TITLE
Ag-Grid doesn't work inside an editor of another Ag-Grid.

### ISSUE THREAD

**Issue by Anruin** [ceolter/ag-grid#1226]
Greetings.
We are trying to use AgGrid in template of the editor of root AgGrid. We are using dynamic building of the editor component to be able to show different renderers/editors for different AgGrid rows. But it doesn't compile and Angular says that it can't bind to AgGridNG2 properties, errors are like the following one:

```
core.umd.js:3462 EXCEPTION: Template parse errors:
Can't bind to 'gridOptions' since it isn't a known property of 'ag-grid-ng2'.
1. If 'ag-grid-ng2' is an Angular component and it has 'gridOptions' input, then verify that it is part of this module.
2. If 'ag-grid-ng2' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
 ("
                         id="products_grid"
                         class="ag-architect"
                         [ERROR ->][gridOptions]="grid_options"
                         [columnDefs]="column_defs"
                         [rowData]="row_data"
"): BindParameterProductEditorComponent@19:7
```

Is there any workaround for this problem? AgGrid is very cool and flexible, so it could be great to use it even inside its own editor. :)

Thanks.

**Comment by ceolter** [comment]
no idea what's wrong here. you might be better posting this on the ag-grid-ng2 project, as more ng2 people looking at that - i'm not working with ng2 (i'm focused on the core)

@seanlandsman - anything come to mind?

gridOptions is listed as a property of the ag-grid-ng2 component, i can see it here:
https://github.com/ceolter/ag-grid-ng2/blob/master/src/agGridNg2.ts#L116

ps closing, as this should be in the ng2 project

**Comment by seanlandsman** [comment]
Hi @Anruin - please raise a new issue under ag-grid-ng2 and we can pick it up there

Your use case - a grid within a grid (if I understood correctly) - isnt something thats been raised before. Interesting!

**Comment by Anruin** [comment]
Greetings @seanlandsman @ceolter I created new issue [here](https://github.com/ceolter/ag-grid-ng2/issues/75), sorry that I've missed repository last time 😄
