### ISSUE TITLE
gridOptions typescript missing onRowValueChanged event handler

### ISSUE THREAD

**Issue by adamweeg** [ceolter/ag-grid#1227]
The gridOptions typescript object is missing onRowValueChanged. This event handler has an [example](https://www.ag-grid.com/javascript-grid-cell-editing/) in the documentation. Adding the following to gridOptions.d.ts resolves the issue:

`onRowValueChanged?(event?: any): void;`

Thanks,
Adam

**Comment by ceolter** [comment]
fixed. will be in next release. thanks.
