### ISSUE TITLE
gridOptions.api.removeItems is not a function

### ISSUE THREAD

**Issue by krucezhang** [ceolter/ag-grid#1230]
I use angularjs framework. The data has been load, but call remove row function, it is print error message: "gridOptions.api.removeItems is not a function"

The code is:

var selectedNodes = $scope.gridOptions.api.getSelectedNodes();
$scope.gridOptions.api.removeItems(selectedNodes);

The variable "selectedNodes"  has been found row data. 

who help me resolve it. thanks

**Comment by ceolter** [comment]
i see nothing wrong. are you on latest ag-Grid version? if not, maybe you are on a version where ```removeItems``` does not exist.

if you provide a plunker, we can look, however with the above info, not much else we can do.
