### ISSUE TITLE
disable ag-grid

### ISSUE THREAD

**Issue by joma167** [ceolter/ag-grid#1231]
Is there a way to disable (no scrolling, filtering, sorting, selecting) an instance of ag-grid, the same way as a button or an input element can be disabled?

**Comment by ceolter** [comment]
no.

nothing in the grid for that.

what you can do yourself is put an overlay over the table yourselv - this means, in your javascript, put a div over the grid's div, with same height etc, but make the background transparent (or blank with 80% transparancy to put a grey tint onto it). that will block all mouse events getting to the grid.

**Comment by joma167** [comment]
Thanks a lot for the answer :-) was not sure if I missed it in the docu. The overlay will work for me, didn't think about that before.

**Comment by lakepacific** [comment]
ceolter - is it possible to provide an example?  when i overlay my ag-grid the overlay appears to be push-down by two rows.  not, sure how to match up the overlay to the top/left corner of the grid.
