### ISSUE TITLE
Debounce for filter input

### ISSUE THREAD

**Issue by don-bluelinegrid** [ceolter/ag-grid#1232]
@ceolter 

Niall,

I noted in this issue about a year and a half ago, someone was requesting the ability to add a delay in the key events in the filter input - basically asking for a debouncing function:
https://github.com/ceolter/ag-grid/issues/272

Was anything more done, aside from the option of the explicit "Apply" submit button?

I am going to need to use debouncing, so could use your guidance on how to do this.  Where is the appropriate point to intercept the key event, before it notifies the grid to call getRows()?  Is the ```filterChangedCallback``` useful for this?  Or should it be done in the key event listener?

This will be for use with remote server data/filtering.

Any guidance appreciated.

Regards,
Don

**Comment by ceolter** [comment]
i haven't worked on debounce for the filter, and it's currently not on my stack.

with guidance - the filters are not designed with this in mind - so no point of extensions. what you would need to do is copy the filter, and then hack it in your self. the built in filters can be found here:
https://github.com/ceolter/ag-grid/blob/master/src/ts/filter/textFilter.ts
https://github.com/ceolter/ag-grid/blob/master/src/ts/filter/numberFilter.ts
https://github.com/ceolter/ag-grid-enterprise/tree/master/src/setFilter

**Comment by don-bluelinegrid** [comment]
@ceolter 

Thanks, Niall.  I had ended up using the example filter in the documentation as a starting point, and have created a custom filter, and have integrated the npm debounce module into the filter input change.

Thanks,
Don
