### ISSUE TITLE
Filter popup is unaligned and remains visible on horizontal scroll

### ISSUE THREAD

**Issue by urrri** [ceolter/ag-grid#1235]
Filter popup should be aligned to column (scrolled together with grid and become invisible when column is completely out of viewport) or just disappear when scrolling horizontally

**Comment by ceolter** [comment]
when you scroll, the filter should disappear, i'll check this ....

**Comment by ceolter** [comment]
ok just checked in, for next release, the menu will now hide when yous scroll the body.
