### ISSUE TITLE
Scroll to row programatically with virtual paging/infinite scrolling.

### ISSUE THREAD

**Issue by LuisPalacios** [ceolter/ag-grid#1237]
Hi, I've tried api.selectNode(node, true) mentioned in #381 and ensureIndexVisible(index) in #907, however I'm using [virtual paging / infinite scrolling](https://www.ag-grid.com/javascript-grid-virtual-paging/) with i.e. paginationPageSize: 100.

So, when I get the data modified and issue a setDatasource(mydatasource) so my table gets refreshed it inmediately positions into its first page (0-99) and trying i.e. ensureIndexVisible(1000) returns an error. 

Is there a way to, programatically, jump to a specific page (offset) or scroll to any row (I guess triggering a new request for an specific page) ?

Thanks a lot for your help in advance, 
Luis

**Comment by ceolter** [comment]
go to here:
https://www.ag-grid.com/javascript-grid-virtual-paging/
look at last example, the button 'jump to 500' shows jumping to row 500

**Comment by laps1967** [comment]
how can you show the row as selected after you jump to the row

**Comment by jml3on** [comment]
I'm having trouble selecting the row after ensuring it's visible.

use case: large virtual table, double click jumps to the details page for that row. When user navigates back, to the list I want to table to show where they were.

ensureIndexVisible properly restores the table with the row showing, but now, I want that row to be selected.

GridApi.selectIndex prints a warning telling me to use node.setSelected:
ag-Grid: do not use api for selection, call node.setSelected(value) instead

but right after calling ensureIndexVisible, I don't have that node.

So I've hooked up into the onModelUpdated events and do a foreachNode until I find my node and can select it. while this works,  ag-grid prints a warning that :
ag-grid-enterprise.js:10806 ag-Grid: cannot select node until id for node is known

But this seems fragile and overly complicated.

any suggestion?

Tx.

**Comment by Chris55** [comment]
hi @jml3on 

4 years later I'm trying to do the same thing... wondering where you able to find a more robust solution?

**Comment by jml3on** [comment]
nope. but it looks like closed issues never get looked at, so you should probably open a new one.

**Comment by Chris55** [comment]
my workaround , starting point was the same 'jump to 500' official example.
[https://stackoverflow.com/questions/66920395/how-to-select-a-row-on-ag-grid-in-infinite-row-mode](url) 

I'm using the community version with Infinite model, I guess will never have an answer here from ag-grid. but I guess quite similar to the server-end model.
