### ISSUE TITLE
double Click is not working on cell of ag-grid.

### ISSUE THREAD

**Issue by jprathore** [ceolter/ag-grid#1238]
Hi , I am using ag-grid and ondoubleClicked of cell , I want to redirect to other page , but    **rowDoubleClicked** is not working.
$scope.gridOptions = {
        columnDefs: columnDefs,
        rowData: rowData,
        rowSelection: 'multiple',
        angularCompileRows: true,
        rowDoubleClicked: onSelectionChanged
    };

Thank You

**Comment by ceolter** [comment]
please check the docs, if putting callbacks on the gridOptions, you put 'on' in the method name

**Comment by jprathore** [comment]
function onSelectionChanged(){
        var selectedRows = $scope.gridOptions.api.getSelectedRows();
        var selectedRowsString = '';
        selectedRows.forEach( function(selectedRow, index) {
            if (index!=0) {
                selectedRowsString += ', ';
            }
            selectedRowsString += selectedRow.Id;

        });
        $scope.Id =selectedRowsString;

        $scope.selectid = selectedRowsString;


        if(selectedRowsString){

            $state.go('EditProject);

        }
    }

$scope.gridOptions = {
columnDefs: columnDefs,
rowData: rowData,
rowSelection: 'multiple',
angularCompileRows: true,
onrowDoubleClicked: onSelectionChanged
};

Hello ceolter , I put 'on' in the method name as above code but it is still do not working. can you suggest     

 what I am doing wrong in above code .

I am able to execute event onSelectionChanged but my requirement is double click.

Thank You

**Comment by pete-hotchkiss** [comment]
@jprathore - assuming your using Angular? have you tried adding the $scope to the prefix on the event call back function? 
```
$scope.gridOptions = [
  ...
  onRowDoubleClicked: $scope.onRowDoubleClicked,
  ...
];
```

**Comment by jprathore** [comment]
@pete-hotchkiss  I tried onRowDoubleClicked: $scope.onRowDoubleClicked, but it still does not trigger any event on double click of ag-grid cell.

**Comment by ceolter** [comment]
needs to be camel case, ie capital R

```
$scope.gridOptions = {
columnDefs: columnDefs,
rowData: rowData,
rowSelection: 'multiple',
angularCompileRows: true,
   onRowDoubleClicked: onSelectionChanged
};
```
