### ISSUE TITLE
"cellClass" function keeps old classes around after change.

### ISSUE THREAD

**Issue by stuartwilliamchaulk** [ceolter/ag-grid#1239]
I have a cellClass function assigned in my column definition.

When the cell edit event occurs, I return ['data-edited']. This works.  On a subsequent change (which reverts the value), I return an empty array.  However, the 'data-edited' class never goes way.  it seems to only be additive.

Any thoughts on this?  Using AG6.
Thanks,
sc

**Comment by ceolter** [comment]
use cellClassRules, see them explained in the docs

**Comment by mcrowder65** [comment]
For quick lookup... see https://www.ag-grid.com/javascript-grid-cell-styling/#gsc.tab=0 and lookup `cellClassRules`

Thanks!
