### ISSUE TITLE
Size Columns to fit -> Size to Fit Header, SizeToFitHeaderOrContent

### ISSUE THREAD

**Issue by jogibear9988** [ceolter/ag-grid#1240]
Is it possible that I autosize all columns, so the full header is readable, and also that the full header & full content is readable?

**Comment by ceolter** [comment]
sizeColumnsToFit takes into consideration the header, so i don't understand the question :(

**Comment by jogibear9988** [comment]
maybe i need to update.
on my system the columns are only as big as the value

**Comment by chetan-rathod** [comment]
@ceolter 
when i was trying sizeColumnsToFit , it is considering the header
