### ISSUE TITLE
Unable to create exampleColumnGroupComplex by using ag-grid with angularjs

### ISSUE THREAD

**Issue by santosh-k1** [ceolter/ag-grid#1241]
We try to create exampleColumnGroupComplex by using angularjs.. but  in your doc example has provide by using javascript .. 2nd question it free or paid ?

[(https://www.ag-grid.com/javascript-grid-grouping-headers/exampleColumnGroupComplex.html)]

so question is how we can use exampleColumnGroupComplex by using angularjs ?

![image](https://cloud.githubusercontent.com/assets/4470369/19996847/7ecd3322-a288-11e6-8b8e-9c15ced2c643.png)

**Comment by ceolter** [comment]
grouping columns is free.

there is no difference with angular vs normal js versions, so use the online examples. all the examples are in standard javascript, but all features work in angular, angualr2, react etc.
