### ISSUE TITLE
[edit languages] Typing non-latin letters on focused cell does not open cell editor

### ISSUE THREAD

**Issue by egidijusj** [ceolter/ag-grid#1242]
Are you planning to support other alphabets, like cyrillic?

I assume that the problem is due to hardcoded set of characters here: https://github.com/ceolter/ag-grid/blob/master/src/ts/rendering/renderedCell.ts#L56

I think that matching character code against a limited set of non-printable characters would be more flexible and faster.

**Comment by ceolter** [comment]
```I think that matching character code against a limited set of non-printable characters would be more flexible and faster.``` => can you provide an example please?

**Comment by ceolter** [comment]
sorry, i'm a native english speaker, not much experience with other alphabets.

**Comment by egidijusj** [comment]
Actually, it's an easy fix. 

As it is stated on [MDN](https://developer.mozilla.org/en/docs/Web/Events/keypress):
```
The keypress event is fired when a key is pressed down and that key normally produces a character value.
```

Assuming the above, it is redudant to perform additional check for printable characters [here](https://github.com/ceolter/ag-grid/blob/master/src/ts/rendering/renderedCell.ts#L469):
```
public onKeyPress(event: KeyboardEvent): void {
        // check this, in case focus is on a (for example) a text field inside the cell,
        // in which cse we should not be listening for these key pressed
        var eventTarget = _.getTarget(event);
        var eventOnChildComponent = eventTarget!==this.getGui();
        if (eventOnChildComponent) { return; }

        if (!this.editingCell) {
            var pressedChar = String.fromCharCode(event.charCode);
            if (pressedChar === ' ') {
                this.onSpaceKeyPressed(event);
            } else {
                if (RenderedCell.PRINTABLE_CHARACTERS.indexOf(pressedChar)>=0) {
                    this.startRowOrCellEdit(null, pressedChar);
                    // if we don't prevent default, then the keypress also gets applied to the text field
                    // (at least when doing the default editor), but we need to allow the editor to decide
                    // what it wants to do. we only do this IF editing was started - otherwise it messes
                    // up when the use is not doing editing, but using rendering with text fields in cellRenderer
                    // (as it would block the the user from typing into text fields).
                    event.preventDefault();
                }
            }
        }
    }
```

If `RenderedCell.PRINTABLE_CHARACTERS.indexOf(pressedChar)` check was removed, you'd get rid of redudancy and agGrid would support keyboards of any non-english layout as well.

**Comment by ceolter** [comment]
not true, i tested it, took out the check, then editing out not stop. eg enter new text, hit Enter, the cell doesn't exit edit mode (or maybe it is, but then doing into edit mode again directly after, i'm not sure). just giving quick feedback, didn't investigate to long, just trying to sweep github issues quickly.

**Comment by ceolter** [comment]
tracked by AG-154
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by ceolter** [comment]
this is now done. i use this trick:

```
    static isEventFromPrintableCharacter(event: KeyboardEvent): boolean {
        let pressedChar = String.fromCharCode(event.charCode);
        let printableCharacter: boolean;
        if (_.exists(event.key)) {
            // modern browser will implement key, so we return if key is length 1, eg if it is 'a' for the
            // a key, or '2' for the '2' key. non-printable characters have names, eg 'Enter' or 'Backspace'.
            return event.key.length===1;
        } else {
            // otherwise, for older browsers, we test against a list of characters, which doesn't include
            // accents for non-English, but don't care much, as most users are on modern browsers
            return Utils.PRINTABLE_CHARACTERS.indexOf(pressedChar)>=0
        }
    }
```

**Comment by makinggoodsoftware** [comment]
Hi,

Just to let you know that as of 11.0.0 this has been implemented, see the changelog for more details..

https://www.ag-grid.com/change-log/changeLogIndex.php#gsc.tab=0
