### ISSUE TITLE
Add row without redrawing existing

### ISSUE THREAD

**Issue by cc1000** [ceolter/ag-grid#1244]
Is there any way to add a new row to a grid without redrawing the existing rows? 

I have a text box in a cell (added via custom renderer) and when it's value changes a new row needs to be added to the grid. This is done on the keyup event as opposed to when tabbing off, and I'm using api.addItems() to add a new row. When the user types the existing rows seem to redraw, meaning the state of the text box is lost (value, focus, etc.). 

Is there any way to avoid this so it just adds a new row without redrawing the existing? I've tried updating the underlying model by adding a new item to the data array and re-setting rowData, and then calling refreshView() (the documentation says this will only redraw volatile rows) but that doesn't then add the new row. 

I've noted [this SO post](http://stackoverflow.com/questions/35031661/adding-new-rows-to-the-grid) which seems related. The answer seems to suggest what I want is not possible, but this is using ng2 which I'm not so I'm not sure how relevant the answer is. 

Thanks in advance for any help :)

**Comment by ceolter** [comment]
it's not possible. when you insert rows, the whole grid gets refreshed.

**Comment by cc1000** [comment]
Thanks for the quick reply. 

Is there any workaround you can think of, aside from tracking the state of the controls and adding it back again? Ultimately the controls will be fairly advanced and composite in nature (ie a lot of state so not trivial to reinstate) so this approach would be laborious.

**Comment by ceolter** [comment]
put in blank rows? then you just update the blank rows.

to change the grid would require a lot of work, i don't have it coded to take care of all the different things that can change, basically it's a shotgun approach, when something like row count changes, it redraws everything.
