### ISSUE TITLE
Reload complete table [Server-Side]

### ISSUE THREAD

**Issue by krunalshah68** [ceolter/ag-grid#1245]
How to reload the complete table in rowModelType("pagination") ?
I have a date picker component, based on changes in date the table needs to reload with data with respect to selected data.

Awesome plugin! 
We want to purchase enterprise license but first we are trying to implement our requirements.

**Comment by ceolter** [comment]
thanks for positive feedback!

to reset the pagination, set the datasource again. you don't need to change the datasource, just set the same one in again.

api.setDatasource(newDatasource);

**Comment by krunalshah68** [comment]
I have done that but it doesn't  go to "getRows" of datasource because of that it won't initiate a new server request.

**Comment by ceolter** [comment]
```I have done that but it doesn't go to "getRows" of datasource because of that it won't initiate a new server request.```
yes it does, you must be doing something wrong!!!

see the first example here:
https://www.ag-grid.com/javascript-grid-pagination/
when you change the page size, it creates a new datasouce and sets it, which then results in getRows(), so deffo works.

**Comment by krunalshah68** [comment]
Yes, it's going into "getRows" and I'm passing the latest data to "successCallback" too! but somehow data in table is not refreshed, values are not changed.

**Comment by ceolter** [comment]
i don't know what's wrong, you appear to be doing it right. either a) debug through the grid code, see if you can work it out or b) create a plunker, then someone else can debug and figure it out.

**Comment by krunalshah68** [comment]
okay will try to create a plunker.
Thank you. :)
