### ISSUE TITLE
how to set grid height dynamically based on row count?

### ISSUE THREAD

**Issue by rajgopalk** [ceolter/ag-grid#1246]
how to set dynamic Grid height based on row count, if row count is 10, height will set to 10 records, if it's 25 , then 25, if 1000,grid will occupy bottom height of display and scrollbar will shown. is it possible?

**Comment by ceolter** [comment]
not possible. only way is for you to set the height yourself based on your own maths after you set the data in.

**Comment by rajgopalk** [comment]
ok, doing math is not a problem.one case it is ok,i.e if we have single line rows, we calculate height based on (row count*actual row height)+(remaining header and pagination footer height).
suppose some rows have multi line text, then it will become more complex i think.again we need to do more coding.can we get height of body without header and footer? if you we have api for getting items(all rows) height, task will become easy.based on that we will assign height to grid dynamically.

**Comment by alexjpujol** [comment]
+1 here
