### ISSUE TITLE
export to excel

### ISSUE THREAD

**Issue by rajgopalk** [ceolter/ag-grid#1247]
hi ceolter, can you implement export to excel feature in future? and  we need some features from the grid(checkbox for select all, unselect all rows and page size dropdown at pagination section and auto grid height).if we purchase the enterprise version can you provide those?

**Comment by ceolter** [comment]
excel => on our radar, ETA next 2 months
checkbox for select all, unselect all rows => not high priority given you have the API,
page size dropdown at pagination section => you can do that yourself? as per the example online for pagination?
and auto grid height => on our radar, but no ETA, yet to be scheduled

if we purchase the enterprise version can you provide those => depends how big a customer, get in touch with our sales team to show interest and talk licenses! we can then discuss.

**Comment by rajgopalk** [comment]
page size dropdown at pagination section =>we need to place that control beside the" last " button in pagination.Actually i put that control after the "last" button in pagination.Problem is if grid have 25000 rows, page count is also more(ex: page 1 of 8456) if i select page size 15.due to more text in (page 1 of ....).last button and my page size dropdown will overlap eachother.thats y iam asking you, if you provide builtin control for page size in pagination section.it will automatically adjust like responsive.from my side, if we place the page size dropdown at pagination level.that looks good.


Thank you

**Comment by shmarlya** [comment]
@rajgopalk for export to excel
simply use this [alasql js library](https://github.com/agershun/alasql)

for example for export all data:
`alasql('SELECT * INTO XLSX("export.xlsx",{headers:true}) FROM ?',[gridOptions.rowData]);`

for export only visible data in grid
```
var visibleColumns = scope.gridOptions.columnApi._columnController.allDisplayedColumns;
var dataToExcel = [];
gridOptions.rowData.forEach(function(item,i){
var newData = {};
     for(var j=0;j<visibleColumns.length;j++){
           if(item[visibleColumns[j].colId] === null ){
             newData[visibleColumns[j].colDef.headerName] = '-';
          }else if(item[visibleColumns[j].colId]){
             newData[visibleColumns[j].colDef.headerName] = item[visibleColumns[j].colId];
          }
      }
      dataToExcel.push(newData);
   });
alasql('SELECT * INTO XLSX("export.xlsx",{headers:true}) FROM ?',[dataToExcel]);

```
