### ISSUE TITLE
Allow sorting of groups

### ISSUE THREAD

**Issue by ceolter** [ceolter/ag-grid#125]
http://www.angulargrid.com/forum/thread-96.html

**Comment by axelnormand** [comment]
I'm also looking to custom sort my each group.
Any suggestions about how I might go about this at the moment? 

Happy to fork or anything.
Thanks

**Comment by ceolter** [comment]
suppose it should be tied into the group column, so the first column if your using the default group presentation. then add in another step, something like:

```
if (colToSort===firstCol && grouping===true) {
  // sort the rows sort 
  // then separatly sort the groups
} else {
 // just sort the row
}
```

(code made up without referring to the code base, variables names etc wrong)

**Comment by axelnormand** [comment]
Thanks for prompt reply. Understood the pseudo code.
Where does this code appear? In a custom comparator in the columnDefs for the grouped columns?

**Comment by ceolter** [comment]
was thinking around InMemoryRowController.prototype.doSort, either in that method, or after that method is called. just thinking off the top of my head, haven't gotten deep into it.

**Comment by jcomet** [comment]
I also have a need for group sorting.   I need to sort on numeric columns and need them to be in order.

**Comment by cah-chaitanyamunagala** [comment]
@ceolter 

I am having issues with sorting while Suppressing the group row. Sorting seems all weird. Even the example provided here https://www.ag-grid.com/javascript-grid-grouping has similar problems. Is there a way to configure the grid to sort on the Column first before sorting on the group?

Thanks

**Comment by ceolter** [comment]
sorting in groups is now supported, i should of closed this issue.

see bottom of page:
https://www.ag-grid.com/javascript-grid-sorting/index.php

if you want to sort in any other way, then provide your own colDef.comparator

**Comment by Ruud-cb** [comment]
@ceolter I'm having a bit of trouble with the combination of grouping and sorting.
I have separate events that eventually call `gridOptions.columnApi.addRowGroupColumn(column);` or the remove function. When this happens, no sorting is applied or executed. But later in the code, when I'm kind of syncing settings with the grid, it might call `gridOptions.api.setSortModel(null);`. When this happens, the groups get sorted (alphabetically?).
Shouldn't the grid sort this automatically? Or don't sort at all when the sort model method is called?

**Comment by namnn** [comment]
Hi @ceolter ,

First of all, thanks for the awesome grid.

I have a dynamic full row grouping, when sorting column it does sort the records inside each group, but not the groups themselves.

Do you have any example code for sorting groups? The doc above doesn't contain any.

Thanks in advance.

**Comment by kannan-stk** [comment]
Hi @ceolter

I've got the enterprise license of Ag-Grid and using the row grouping feature. As @namnn pointed out, I'm looking for sorting the rows within the row grouping instead of loosing out the group column sorting when we click on non-grouped column. Shift+click on another column when the sorting applied on grouped column does also making no impact.
![aggrid sort issue](https://user-images.githubusercontent.com/20913058/76991299-b92f2a00-691f-11ea-88e7-3afb81509092.png)

**Comment by mrosminin** [comment]
UP.
The same problem. Grouping by column with refData. Groups are sorting by value, not via comparator func.
