### ISSUE TITLE
Filter reset using setFilterModel(null) not working with remote data/virtual paging

### ISSUE THREAD

**Issue by don-bluelinegrid** [ceolter/ag-grid#1250]
@ceolter 

Niall,

I have a working grid instance that is using virtual paging, remote filtering, and remote sorting.  I would now like to have a "Clear Filters" button, similar to what's shown on a couple of the examples.

However, in both of the examples that show something like this, there is not real remote data or virtual paging or remote filtering.  The examples show these two lines for clearing filters:
```
gridOptions.api.setFilterModel(null);
gridOptions.api.onFilterChange();
```
When I attached those two lines to a button and call them, I do visually see the filter button state change, I see ```getRows()``` being called, and I see the correct un-filtered set of data being returned from the remote call.  But, visually I do not see rows being added to the grid - and in fact, the grid is completely empty of rows.

I did also try adding a ```refreshView()``` call, but that made no difference.

Can you provide any suggestions on what may be happening, or if there's an alternate approach for clearing/resetting filters needed when using remote data/virtual paging?

Thanks,
Don

**Comment by don-bluelinegrid** [comment]
@ceolter 

Follow-up:

I've also tried adding a call to reset the datasource, like this -
```
gridOptions.api.setFilterModel(null);
gridOptions.api.setDatasource(gridOptions.datasource);
gridOptions.api.onFilterChange();
```
This initially seemed to working, but actually is not working.  It does seem to reset the filters so that all of the data is returned to the grid; but then subsequently trying to filter the grid does not work - typing into the filter doesn't seem to trigger the grid filtering, after the datasource has been replaced.

Don

**Comment by ceolter** [comment]
works for me, i took this example:
https://www.ag-grid.com/javascript-grid-virtual-paging/virtualPagingServerSide.html

i added in this code:
```
setInterval( function() {
    gridOptions.api.setFilterModel(null);
    gridOptions.api.onFilterChanged();
}, 10000);
```
and it cleared the filter and worked 10 seconds after loading.

ps it's onFilterChanged, not onFilterChange

if you provide a plunker with it broken, i can look
