### ISSUE TITLE
how to catch column drag start and end event?

### ISSUE THREAD

**Issue by rajgopalk** [ceolter/ag-grid#1251]
...
   onDragStopped: function (event) {
                event.api.sizeColumnsToFit();
            },
            onDragStarted: function (event) {
                event.api.sizeColumnsToFit();
            },
        };
iam applying this in grid options, but event is not fired. is it a right way. i also try without "on" like dragStopped:function... and dragStarted:func...
what is the correct way of achieving it.

**Comment by ceolter** [comment]
don't use drag events, use the column moved events

**Comment by rajgopalk** [comment]
tq ceolter, but i got this below error when i call api from that event.
0x800a138f - JavaScript runtime error: Unable to get property 'sizeColumnsToFit' of undefined or null reference.
my code is:
onColumnMoved: function (event) {
                event.api.sizeColumnsToFit();
            }

**Comment by ceolter** [comment]
the column event doesn't have the api, use the api on gridoptions instead
