### ISSUE TITLE
sizeColumnsToFit not working if we call that api from column moved event

### ISSUE THREAD

**Issue by rajgopalk** [ceolter/ag-grid#1252]
i call the api from onColumnMoved event, but nothing will happen.(still i got horizontal scrollbar)
iam calling api like this, in grid options
onColumnMoved: function (event) {
                event.api.sizeColumnsToFit();
            }

is it right or wrong?

**Comment by rajgopalk** [comment]
i hv tried $scope.gridOptions.api.sizeColumnsToFit(); this also not working in that place of event call

**Comment by HerokunTan** [comment]
sizeColumnsToFit does not work when forPrint=true

**Comment by rajgopalk** [comment]
i didnt enabled it.so, default it is set to false i think.

**Comment by ceolter** [comment]
```sizeColumnsToFit does not work when forPrint=true``` -> it is not supported. forPrint doesn't use scrollbars so it doesn't make sense.

```$scope.gridOptions.api.sizeColumnsToFit();``` should work

please provide a plunker.

ps closing - this is not a problem with ag-grid, issues are for items that need fixing in ag-grid
