### ISSUE TITLE
Set Cursor at the end of text.

### ISSUE THREAD

**Issue by GurjitDrish** [ceolter/ag-grid#1253]
Hi team ! 
I am using enterprises version of AG grid. I had two issues at the start of cell editing process
a) Moving cursor in edit box with navigation key.
b) Setting cursor position at the end of text on edit cell.

I've resolved a by doing following 
RenderedCell.prototype.onNavigationKeyPressed = function (event, key) {
        if (!this.editingCell) {
            //this.stopRowOrCellEdit();      
            this.rowRenderer.navigateToNextCell(key, this.rowIndex, this.column, this.node.floating);
            event.preventDefault();
        } 
    };

but issue (b) is still not resolved. Kindly help me out.

**Comment by ceolter** [comment]
this is not something broken in ag-grid, issues are for tracking work items needed in ag-grid, so closing.

this is a general javascript question, please google for answers!!
http://stackoverflow.com/questions/511088/use-javascript-to-place-cursor-at-end-of-text-in-text-input-element

do this in afterGuiAttached() method

**Comment by GurjitDrish** [comment]
afterGuiAttached() worked , that what event I was looking for.

Thanks @ceolter
