### ISSUE TITLE
prevent doubleclick editing of cells

### ISSUE THREAD

**Issue by pete-hotchkiss** [ceolter/ag-grid#1254]
I'd like if I can to be able to intercept the doubleclick triggering a cell edit.

Whilst my columDef object has some columnset to editable: true; I only want to trigger the editing of row contents via a keyboard-short cut or button press.

anychance I can detect that fact the edit was triggered by a doubleclick in the params object that cell editors get in their init() method ?

**Comment by ceolter** [comment]
no.

but the editable can be a function. so what you could do is:
1. make all cells not editable. (function returns false, can store false in a flag).
2. when you want to start editing, configure function to return true.
3. call api.startEditingCell(params) (see the docs)
4. in a timeout, set flag for editable back to false.

**Comment by venki-si-ai** [comment]
does not make sense! if i enable single click editing, double-click must be leffout to something else! such as, i want to enable click editing on single click and double click to open a details dialog on a row!

**Comment by eddy14u** [comment]
you can pass `gridOptions.singleClickEdit=true` to the table.

you could also do `suppressClickEdit=true` to disable all clicking to edit, then make your functionality to start editing on your cell renderer.

https://www.ag-grid.com/javascript-grid-cell-editing/#singleClickEditing
