### ISSUE TITLE
Any way to prevent cells in a column from being destroyed when calling setRowData()?

### ISSUE THREAD

**Issue by franktroia** [ceolter/ag-grid#1256]
Hi,

I have a custom column implemented using the cellRenderer component. This column provides a menu dropdown that can be used to operate on each row in the grid. The grid is also constantly updated with live data, so I call setRowData whenever new data is fetched from the server (every 5 seconds, lets say). The use case is to provide near real time data to the user.

The problem is that calling setRowData forces the cell's content to be destroyed, thus obliterating the menu dropdown every 5 seconds. This makes it difficult to select an option from the menu before the next call to setRowData.

I'm wondering if there is way to prevent a specific column (or set of cells) from being destroyed on setRowData? Or perhaps there is a more appropriate way to update the grid with new data from the server?

Thanks!

**Comment by ceolter** [comment]
if you want live data from the server, you can use viewport (enterprise only).

you can also use these methods, they won't destroy the columns:
https://www.ag-grid.com/javascript-grid-insert-remove/
