### ISSUE TITLE
grid renders scroll on wrong position 

### ISSUE THREAD

**Issue by magmel48** [ceolter/ag-grid#1259]
After changing gridOptions and resize window scroll is rendered on wrong position, columns don't change their size and there is big empty space gap between last column and scroll

**Comment by ceolter** [comment]
'''After changing gridOptions'''
=> really depends on what you mean here. there is no such thing as 'changing grid options'. if you want  a new grid, you need to destroy the old one and create a new one again from scratch. it isn't designed to just change to a new grid options object.
