### ISSUE TITLE
Is there inagGrid any validation for user input?

### ISSUE THREAD

**Issue by ua9msn** [ceolter/ag-grid#1260]
agGrid provides API for custom editor but do not provide any option to cancel stopping the edit. 
So if user enter incorrect value - the only way is to revert value to previous. 
That is very confusing, especially for complex data and validation rules. For example for invalid credit card number, invalid phone number, or whatever where user may make an error. 
Any suggestions?

**Comment by stephanjust** [comment]
https://www.ag-grid.com/javascript-grid-column-definitions/ -> newValueHandler(params)

is what you're looking for. If you don't do anything in this function nothing happens, meaning the value is only accepted if you change it yourself. Example:
```
column.newValueHandler = (params: { node: RowNode, data: any, oldValue: any, newValue: any, rowIndex: any, colDef: any, context: any, api: GridApi }) => {
    const validation = doYourValidationHere(.....);
    if (validationIsSuccesFull) {
        // save value in your row
       params.data[column.field] = params.newValue;
    } else {
        // not succesfull, doing nothing will automatically discard the input (do nothing)
    }
};
```

**Comment by ua9msn** [comment]
2@stephanjust This will not work. 
That is exactly what i told about: editor will be destroyed and previous value will be restored. 
There is no way to not close editor and give a user a chance to correct his input. 
What i need is "do not close editor if validation fails"

**Comment by stephanjust** [comment]
Ah sorry, that was a missunderstanding. I thought your issue was to recalculate the _previous_ value, not the _new_ one.

I asked about exaclty this before too as it's not possible at the moment:
https://github.com/ceolter/ag-grid/issues/1071

**Comment by ceolter** [comment]
what you can do is cancel the edit (return true from isCancelAfterEnd()) and then I guess display a popup to the user, telling them it was not valid?

then call the api.startEditing(value) and abuse (not supported!!) the charPress parameter to provide the text the user had entered (which will then be what the editor starts with). this is assuming your using the text editor, if a custom editor, then better, as you are in full control of charPress.

**Comment by gkp9498** [comment]
I have started using ag-grid in my Angular 4 project, and was unable to find any API's for performing in-line cell validations i.e. whenever user edits a particular cell, the requirement is to perform a required field and pattern validation. In case of any validation errors, the corresponding editable field should get highlighted and an error message needs to be displayed.

I have used the following cell events to fulfill the above purpose, but none of them provided me the desired result.

cellEditingStarted
cellEditingStopped

**Comment by mflmartin** [comment]
Related to this, and character limit validation, with the default CellEditor, I havent found a simple way to set the maxLength of the underlying simple input.

Is there any way to limit the number of characters that can be written by the user? Not validate them afterwards. 

Or... how can I access to the input, per row (different rules apply in my case per row) to set different maxLength values? I know I could validate them afterwards, but I would prefer the user not to be able to write more than it should and pre-validate or pre-cap that action.

**Comment by sushant47** [comment]
I know it's bit late 
but how about this one?
https://medium.com/ag-grid/using-angular-forms-with-ag-grid-1efe00265535
