### ISSUE TITLE
Error agGridWebComponent.ts(34,20): error TS2339: Build :Property '__agGridSetProperty' does not exist on type 'HTMLElement'.

### ISSUE THREAD

**Issue by Aws2015** [ceolter/ag-grid#1261]
I have this error when I installed the last ag-grid 6.4.2 and ag-grid 6.4.0 with angular js 2.1.2  and Typescript 2.0.9.  any solution please?

agGridWebComponent.ts(34,20): error TS2339: Build :Property '__agGridSetProperty' does not exist on type 'HTMLElement'.
\agGridWebComponent.ts(45,20): error TS2339: Build :Property 'onChange' does not exist on type 'HTMLElement'.
agGridWebComponent.ts(58,20): error TS2339: Build :Property 'setGridOptions' does not exist on type 'HTMLElement'.
.....

**Comment by ceolter** [comment]
no idea what's happening here.

the __agGridSetProperty is used inside the method initialiseAgGridWithWebComponents() which i am guessing you are not using. so there is something about your setup that is causing it. if you can reproduce in a plunker, someone can possibly take a look.

ps this isn't an issue with ag-Grid, github is for tracking issues we need to work on, so closing.
