### ISSUE TITLE
grunt  wiredep inject the main.js that using require

### ISSUE THREAD

**Issue by ofirrifo** [ceolter/ag-grid#1262]
Hi,

I'm using grunt with wiredep to inject the bower components to my index.html file.

Currently I'm getting the main.js file registered to my index.html

main.js expects require to be available, but in my case it doesn't. (I'm not using bundling)

I'd like the wiredep to inject ag-grid-enterprise.js directly.

How can this be implemented?

**Comment by ofirrifo** [comment]
I found how to solve this:

in the bower.json I add this:

"overrides": {
		"ag-grid-enterprise": {
			"main": "dist/ag-grid-enterprise.js"
		}
	},

[Bower Overrides](https://github.com/taptapship/wiredep#bower-overrides)

**Comment by ceolter** [comment]
spoke ag angular up - closing
