### ISSUE TITLE
same license key - multiple developers

### ISSUE THREAD

**Issue by vsanat** [ceolter/ag-grid#1269]
hi guys,

I have another question regarding licensing, can multiple developer use the same license key, we have procured the license for 10 developers, but we got only one key. So I suppose all the developers should use same key, but while doing this we are getting "invalid license key error" in the browser console.

Please reply. thanks in advance. 

@ceolter please respond

anybody willing to reply...

**Comment by seanlandsman** [comment]
hi @vsanat - are you're an enterprise customer you should post queries on the members forum (https://ag-grid.com/forum) - you'll get a much faster answer there

In answer to your question yes, if you have a license for 10 developers then the same license is to be used by all 10 developers. 

If you're getting an "invalid" license key message then thats almost certainly down to the license key not being set correctly. Can you please post (either here or on the members forum) what you're using to set the key and I can try help?

Please **do not** post your license key here!

**Comment by ceolter** [comment]
PPS we don't check Github daily - if you are an enterprise customer, you should use the members forum and we will get back to you promptly! :)

**Comment by vsanat** [comment]
Thanks Guys,,, 
I got this working now, problem was not with the key, I have to upgrade my Angular from 2.0.0 to 2.2.4

One suggestion -> In this case ag-grid should not say License Key invalid, this might be misguiding as what happened to me. My license key was perfect only thing is I had to upgrade Ng. Please correct the error message if possible. :)
Cheers

**Comment by ceolter** [comment]
this wasn't something on our end - our license key has nothing to do with angular versions.
