### ISSUE TITLE
AG-Grid sorting is not working with TreeData

### ISSUE THREAD

**Issue by shafaqkazmi** [ceolter/ag-grid#1270]
I have an ag-grid with **Tree Data**. (https://www.ag-grid.com/javascript-grid-tree/).

I am facing an issue that column is being sorted in lexicographical order instead of Asc/Desc. For number columns, it should be sorted by max/min value. Here is the JsFiddle link: https://jsfiddle.net/pbjqdw6w and see the behavior of **Currency** column.

Need help urgently!

**Comment by ceolter** [comment]
for custom sorting, use colDef.comparator
explained here:
https://www.ag-grid.com/javascript-grid-sorting/

**Comment by shafaqkazmi** [comment]
@ceolter Thanks for the fix. It's working after using colDef.comparator

```
comparator: function (valueA, valueB, nodeA, nodeB, isInverted) {
  return valueA - valueB;
}
```
