### ISSUE TITLE
Callbacks missing from ComponentUtil.FUNCTION_PROPERTIES?

### ISSUE THREAD

**Issue by darsee** [ceolter/ag-grid#1271]
[`ComponentUtil.FUNCTION_PROPERTIES`](https://github.com/ceolter/ag-grid/blob/master/src/ts/components/componentUtil.ts#L57-L62) includes all the callbacks listed in the documentation at https://www.ag-grid.com/javascript-grid-callbacks/index.php except for `getBusinessKeyForNode` and `checkboxSelection`. Is there a reason for this? As far as I can see it means those two cannot be passed as props to the `AgGridReact` component, and can only be used as part of a `gridOptions` prop? 

Looks like this might be similar to https://github.com/ceolter/ag-grid/issues/1182.

**Comment by ceolter** [comment]
that was an error. they are now in. will be in next release.
