### ISSUE TITLE
Angular 2 - Custom filters in production build

### ISSUE THREAD

**Issue by LePeruvien** [ceolter/ag-grid#1272]
Hi all,

I'm using ag-grid version 6.4.2 and ag-grid-ng2 version 6.4.2 in my angular 2 project. 
I created custom filters (boolean, list etc.) but I have problems in production build.
In fact, when I launch the 'ng serve' command  in development mode (ng -serve), my custom filters work fine. But when I launch the production command ('ng serve -prod') my custom filters do not work. All my custom filters are updated in textual filters.

Please do you know how to fix this issue ?

Thanks,

Adrien

**Comment by seanlandsman** [comment]
hi - I'm afraid I'll need some more information about the error you're seeing. Do you have an errors in the console? If not we'll probably need a plunker or similar before we can help you investigate this.

Going forward can you please raise ng2 related issues under the ceolter/ag-grid-ng2 project instead

thanks

**Comment by seanlandsman** [comment]
Closing as no further info provided
