### ISSUE TITLE
[react] AG Grid React/Redux issue control the grid via redux state

### ISSUE THREAD

**Issue by markhaynes456** [ceolter/ag-grid#1273]
Hello,

I am having an issue using redux state to power the Ag-grid. The issue I am seeing is as follows:
1. A filter changes
2. onFilterChange filters are sent to the server (redux action)
3. The server tells the client what filters to apply (redux)
4. The client then tells Ag-grid to render the filters using setFilterModel
5. Ag-grid renders the filters

The issue that I am seeing is that if the filter menu is open for a number/text/set filter then it becomes unresponsive once the model has been changed.

Is their any workaround that could be used for this issue?

Any advice would be appreciated

**Comment by alecperkey** [comment]
If you have some basic demo of this, would be happy to spend some time finding a solution.

**Comment by ceolter** [comment]
tracked by AG-156
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by ceolter** [comment]
this is now done. we will release later this week v10.1 which will support Redux stores.
