### ISSUE TITLE
AG Grid React Internationalisation

### ISSUE THREAD

**Issue by BaconZhang** [ceolter/ag-grid#1275]
It seems like that ag-grid react does not support internationalization. I use localText in the props of component but it does not work. If ag-grid react does support internationalization, could you please give me an example. Your timely reply will be much appreciated.

**Comment by ceolter** [comment]
everything is supported, ag-grid-react is a wrapper around ag-grid, so no features are left out. afraid we don't have time to give examples of all the features in all the frameworks, however if you provide a plunker we can take a look. it should be as simple as providing localText as you say you do.
