### ISSUE TITLE
Copy to clipboard not working when rowModelType is viewport

### ISSUE THREAD

**Issue by gsawasthi25** [ceolter/ag-grid#1276]
Use-case: Select a single row in the grid, do Ctrl+C and that item should be copied to clipboard

Error: When rowModelType is viewport then this feature doesn't work and logs out a message in console.
"ag-Grid: getDataAsCsv is only available for standard row model".

For verification:
1. Open https://www.ag-grid.com/javascript-grid-viewport/exampleViewport.html
2. Select a row and do Ctrl+C
3. Check console.

**Comment by seanlandsman** [comment]
Just to add to this, happens with mac & chrome, and windows & chrome, but also works with windows & chrome!

**Comment by ceolter** [comment]
fixed. will be in next release (we are doing it today)

**Comment by gsawasthi25** [comment]
Thanks @seanlandsman and @ceolter 
you guys are doing great job
