### ISSUE TITLE
Default selected rows

### ISSUE THREAD

**Issue by IceOnFire** [ceolter/ag-grid#1277]
Hi,

First of all congratulations for this piece of software, it's really impressive.

I'm trying to render a React/Redux grid with a default selected row, but apparently I cannot find the right way to do it. The only workaround I found, based on the docs about [selection](https://www.ag-grid.com/javascript-grid-selection/) and [React](https://www.ag-grid.com/best-react-data-grid/), is something like:

```js
let gridApi = null

const MyGrid = ({data, columns, currentRow, focusRow}) => (
  <AgGridReact
    onGridReady={({api}) => gridApi = api} // just keep a reference to api obj
    onModelUpdated={({fromIndex}) => {
      // too many events, the one I'm interested in does not have fromIndex :S
      if (gridApi != null && fromIndex == null) {
        gridApi.forEachNode((node, index) => {
          if (index === currentRow) {
            node.setSelected(true)
          }
        })
      }
    }}
    onRowSelected={({node}) => {
      if (node.selected && node.childIndex !== currentRow) {
        focusRow(node.childIndex) // Redux action
      }
    }}
    columnDefs={columns}
    rowData={data}
    rowSelection='single' />
)
```

However this is not working on initial render (at least in my application) and I find it a very bad solution overall. Is there something else I can do?

Antony

**Comment by ceolter** [comment]
thanks for positive feedback.

don't use 'fromIndex', i actually took that out in v7, it was for a performance gain in the grid that doesn't get used anymore.

actually don't use onModelUpdated, that gets fired whenever the displayed rows change, this could be after sort, filter, group open / close.

the problem is the binding you are doing with React - the grid works like a state machine, so after you call api.setRowData(newData), then you know the grid is ready with that data, and you can then call forEachNode() and be sure the data you set in is there.

however you are using React, so the binding of the property is done afterwards without your control.

if the data is given to the grid at the start, then you can do forEachNode in onGridReady, it will be available then. otherwise, after you set the data (if not at the start), then do your forEachNode check in a timeout, that way it will give React the chance to update the property first.

**Comment by caglarsarikaya** [comment]
aggrid on ready function is not proper for this transact. agon ready just drawing table if you want manipulate data you have to approach before ag ready. but there is no option for this.if you add this code on your methods. 
```
getProducts: async function() {
      let data = await repository.getAll("Product").then(r => r.list);
      for (let i = 0; i < this.value.length; i++) {
        for (let j = 0; j < data.length; j++) {
          if (this.value[i].productId == data[j].productId) {
            let x = data.splice(j, 1)[0];
            data.unshift(x);
            break;
          }
        }
      }
      this.productDataForAggrid = data;
      this.gridApi.setRowData(this.productDataForAggrid);
      window.watcher = setInterval(this.setSelectedItems, 50, this.gridApi);
    }
```
this function is normal get method except last part. İf you selected some rows on ag and if you close ag all selection will deleted on the table but you stıll have which data selected on your data property when you openin ag again. You will fallow this way.this part of code for real ready function i mean before preparation of data. 

```
setSelectedItems(api) {
      if (this.productDataForAggrid.length == api.getDisplayedRowCount()) {
        for (let i = 0; i < this.value.length; i++) {
          let node = api.getRowNode(this.value[i].productId.toString());
          if (node) {
            node.setSelected(true);
          }
        }
        this.gridApi.sizeColumnsToFit();
        clearInterval(window.watcher);
        window.watcher = 0;
        //console.log("ready!");
      }
    }
```

firstly we will add all selected data on value prop for adding to billing list. But if customer wants to reopen product select aggrid again customer cant see the selected products. This getproducts func work for everytime on ag open. and getting all products. compare this data with our value property. and sending to setSelectedItems funciton for check selected.
```

 saveSelectedProducts() {
      this.value.splice(0, this.value.length);
      for (var i = 0; i < this.gridOptions.api.getSelectedRows().length; i++) {
        if (this.gridOptions.api.getSelectedRows()[i].sellPrice === undefined)
          this.gridOptions.api.getSelectedRows()[
            i
          ].sellPrice = this.gridOptions.api.getSelectedRows()[i].odooId;

        if (this.gridOptions.api.getSelectedRows()[i].piece === undefined)
          this.gridOptions.api.getSelectedRows()[i].piece = 1;

        this.value.push(this.gridOptions.api.getSelectedRows()[i]);
      }
      //this.$emit("selectedProductsList", this.value);
      this.openProductPopup = false;
    },
```

**Comment by Nancy-Wang0721** [comment]
> then do your forEachNode check in a timeout, that way it will give React the chance to update the property first

Hi, I tried set a timeout but still no luck, gridApi is still undefined when i do `forEachNode`
	```
const onGridReady = (params) => {
		setGridApi(params.api);
		setGridColumnApi(params.columnApi);

		setTimeout(() => {
			gridApi?.forEachNode(function (node) {
				node.setSelected(node.data.id === 'AE008');
			});
		}, 90000);
	};
```
