### ISSUE TITLE
[clipboard] Copy cell value and paste it in multiple cells

### ISSUE THREAD

**Issue by prabhakerb** [ceolter/ag-grid#1278]
- The use case is to copy the one cell value(only one cell) and paste it in select range(many cells). Right now, it is only pasting in first cell of range selection. Is there anyway to make it work for selection range?

**Comment by ceolter** [comment]
no. but you can highlight a range, then press ctrl+d to copy it down. so copy to first cell (or row), then ctrl+d to fill a range.

**Comment by mbacon-edocs** [comment]
I've just written in a fix for this, as it's quite a core paste feature for us - before creating a pull request is this something you'd be happy to be active immediately or would you have this option configurable and disabled by default to keep functionality the same for existing implementations upgrading

**Comment by ceolter** [comment]
to be honest, i didn't fully understand what it is you have implemented, so can't answer if it should be default or not. can you explain a bit more what it is you did? (a movie would be great, but if you are not set up to capture and share movies easily, don't worry, just text)

**Comment by mbacon-edocs** [comment]
In Excel, if you focus a single cell, hit Ctrl + C then select a range of cells (>= 1 columns and >= 1 rows) and hit Ctrl + V, that single cell value will be duplicated across all selected cells. The current implementation only pastes the value into the one focused cell that started the range selection.

**Comment by ceolter** [comment]
ah right, gotcha. i'll put this on my list.

**Comment by mbacon-edocs** [comment]
If you want my code I achieved it by adapting some of the code from `ClipboardService.prototype.copyRangeDown`

```
ClipboardService.prototype.finishPasteFromClipboard = function (data) {
	var _this = this;
	if (main_1.Utils.missingOrEmpty(data)) {
		return;
	}
	var focusedCell = this.focusedCellController.getFocusedCell();
	if (!focusedCell) {
		return;
	}
	var parsedData = this.dataToArray(data);
	if (!parsedData) {
		return;
	}
	// remove last row if empty, excel puts empty last row in
	var lastLine = parsedData[parsedData.length - 1];
	if (lastLine.length === 1 && lastLine[0] === '') {
		main_1.Utils.removeFromArray(parsedData, lastLine);
	}
	var currentRow = new main_1.GridRow(focusedCell.rowIndex, focusedCell.floating);
	var cellsToFlash = {};
	var updatedRowNodes = [];
	var updatedColumnIds = [];
	//If there's only one value, paste to whole selection
	if(parsedData.length === 1 && parsedData[0].length === 1 && this.gridOptionsWrapper.isEnablePasteOneToMany())
	{
		this.iterateFirstActiveRange(function (currentRow, rowNode, columns) {
			updatedRowNodes.push(rowNode);
			columns.forEach(function (column, index) {
				if (!column.isCellEditable(rowNode)) {
					return;
				}
				_this.valueService.setValue(rowNode, column, parsedData[0][0]);
				var cellId = new main_1.GridCell(currentRow.rowIndex, currentRow.floating, column).createId();
				cellsToFlash[cellId] = true;
				var colId = column.getId();
				if(updatedColumnIds.indexOf(colId) === -1) updatedColumnIds.push(colId);
			});
		});
	}
	else
	{
		parsedData.forEach(function (values, index) {
			// if we have come to end of rows in grid, then skip
			if (!currentRow) {
				return;
			}
			var rowNode = _this.getRowNode(currentRow);
			updatedRowNodes.push(rowNode);
			var column = focusedCell.column;
			values.forEach(function (value) {
				if (main_1.Utils.missing(column)) {
					return;
				}
				if (!column.isCellEditable(rowNode)) {
					return;
				}
				var processedValue = _this.processRangeCell(rowNode, column, value, _this.gridOptionsWrapper.getProcessCellFromClipboardFunc());
				_this.valueService.setValue(rowNode, column, processedValue);
				var cellId = new main_1.GridCell(currentRow.rowIndex, currentRow.floating, column).createId();
				cellsToFlash[cellId] = true;
				if (updatedColumnIds.indexOf(column.getId()) < 0) {
					updatedColumnIds.push(column.getId());
				}
				column = _this.columnController.getDisplayedColAfter(column);
			});
			// move to next row down for next set of values
			currentRow = _this.cellNavigationService.getRowBelow(currentRow);
		});
	}
	// this is very heavy, should possibly just refresh the specific cells?
	this.rowRenderer.refreshCells(updatedRowNodes, updatedColumnIds);
	this.eventService.dispatchEvent(main_1.Events.EVENT_FLASH_CELLS, { cells: cellsToFlash });
	this.focusedCellController.setFocusedCell(focusedCell.rowIndex, focusedCell.column, focusedCell.floating, true);
};
```

And the required config-based code:

`GridOptionsWrapper.prototype.isEnablePasteOneToMany = function () { return isTrue(this.gridOptions.enablePasteOneToMany); };`
and
`'pivotPanelShow', 'suppressTouch', 'enablePasteOneToMany',`

**Comment by ceolter** [comment]
cool, thanks. will take a look when i get to it in my list :)

**Comment by prabhakerb** [comment]
@ceolter Any plan to add this fix in next release?

**Comment by ceolter** [comment]
tracked by AG-157
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by ceolter** [comment]
done, will be in next release.
