### ISSUE TITLE
[Question] Filter on Tablet

### ISSUE THREAD

**Issue by namminh2005** [ceolter/ag-grid#1279]
Config:
var gridOptions = {
    enableFilter: false
};

In Desktop, Menu Filter do not show.
But Menu Filter will show on Table when touch long.
Can i disable Menu Filter show on Tablet?

**Comment by namminh2005** [comment]
Can i disable Menu Filter show on Table?

**Comment by ceolter** [comment]
no, this is an issue we need to fix.
