### ISSUE TITLE
How to disabled pagination in ag-grid ?

### ISSUE THREAD

**Issue by santosh-k1** [ceolter/ag-grid#1282]
HI, 

I have checked that no of rows display in the grid  are not same as we have in the database  it menace so some rows are move to the another page. so want to  disabled pagination  or remove scrollbar so that all records will display on the same page.. i try to use 

> Print:true

but format of the grid not proper as we need. so can you tell me the name of property which we can use to fix the issue.

Thanks in advance

**Comment by ceolter** [comment]
then don't use pagination??? the default operation of the grid is to not us paging.
