### ISSUE TITLE
Get $scope in cellEditor params (angularCompileRows)

### ISSUE THREAD

**Issue by etiennecrb** [ceolter/ag-grid#1283]
Hello,
If `angularCompileRows` option is set to `true`, row scope is not passed in parameters of cellEditor `init()` method as it is for cellRenderer component. It is an issue since the only workaround is to remove `angularCompileRows` option and compile cellEditor element (which would mean a lot of work for my current grid).

Indeed, if I compile the cellEditor element in its `init()` method with a scope created with `$rootScope.$new()`, it will be compiled again by ag-grid with row scope.

I think that's why your answer to [this StackOverflow question](http://stackoverflow.com/questions/38860549/how-do-i-render-angular-directive-inside-an-ag-grid-celleditor-component) didn't work.

I believe it makes sense to add scope to cellEditor params as cellRenderer. What do you think?

**Comment by ceolter** [comment]
done. will be in next release. Added $scope to cellEditor params
