### ISSUE TITLE
[react] cellEditorFramework wraps editor component in <div>

### ISSUE THREAD

**Issue by simoneb** [ceolter/ag-grid#1284]
While trying to switch from a standard `cellEditor` to a react `cellEditorFramework` I noticed that the rendered component is wrapped in a `<div>` element, which doesn't happen when using the non-framework variant.

This has the negative side-effect that it's difficult to style the editor without having control of the wrapping `<div>`.

This wrapper should be removed in my opinion, or is there a reason for it to exist?

**Comment by ceolter** [comment]
yes it's needed to host the little mini React engine for the cell - that's how react works - it needs a parent div for us to inject the cell into.

if interested, here is the code:
https://github.com/ceolter/ag-grid-react/blob/master/src/agReactComponent.ts#L23

for styling, this element is passed to the react cellRenderer as parameter reactContainer, maybe this can help you?
