### ISSUE TITLE
Want to change background of cell onCellClicked.

### ISSUE THREAD

**Issue by Pushp1403** [ceolter/ag-grid#1290]
Hi ,

is there any way i can change background or apply a specific class to the cell i am clicking on. i  tried using onCellClicked but and then coldef.class thing but it changes the css for entire colomn. please help.

**Comment by ceolter** [comment]
use cellClassRules to apply classes to cells.
https://www.ag-grid.com/javascript-grid-cell-styling/

then you will need to refresh the cell.
https://www.ag-grid.com/javascript-grid-refresh/

**Comment by Quethzel** [comment]
> use cellClassRules to apply classes to cells.
> https://www.ag-grid.com/javascript-grid-cell-styling/
> 
> then you will need to refresh the cell.
> https://www.ag-grid.com/javascript-grid-refresh/

The first link is down
