### ISSUE TITLE
Edit cell in aggregated/group row

### ISSUE THREAD

**Issue by paradicey** [ceolter/ag-grid#1292]
Is there a way to edit the cell that is part of the aggregated/group row?
I am trying to provide the user a way to set value for all the rows for certain field under the same group.
since the row number is huge. it would be natural to let user directly edit on the group cell.
Please advise.

**Comment by ceolter** [comment]
no, but it's on our list of things to fix.

**Comment by sandeepsangole** [comment]
@ceolter , is edit feature on aggregated row added ?

**Comment by Ohjay44** [comment]
@ceolter, has this been added. I am needing to do this for a current project I have

**Comment by daonsh** [comment]
Hi, any news on this?
I am evaluating ag-Grid for a new project and also need this.
Thanks

**Comment by scrapex** [comment]
Does anyone know if this feature is available ? Thanks
