### ISSUE TITLE
how to pass another field id in click event

### ISSUE THREAD

**Issue by rajgopalk** [ceolter/ag-grid#1294]
hi, suppose one column header have claim Number(i.e : link button),if i click that button , i need to pass claim id to angular controller.if i passed the claim ID to the method. data not displayed in ag-grid.
EX; below code is for columnsDefs.
{
                headerName: "Claim No.", field: "claimNumber", width: 100, enableValue: true, suppressMenu: true, suppressFilter: true, suppressSorting: true,enableRowGroup: true,
                cellRenderer: function (params) {
                    return '<span  title=\"Claim No\" class=\"dummylink \"  ng-click=\"ClaimIdClickEvent(' + claimID + ')\">' + params.value + '</span>';
                }
            }, 

if i passed like that , actual data is not displayed on the grid.is ther any way to transfer other fields , which comes from datasource?

**Comment by ceolter** [comment]
if using angular 1, then the data is on the $scope for the row, so you can:

``` '<span title="Claim No" class="dummylink " ng-click="ClaimIdClickEvent(data.xxx)">' + params.value + '';```

this is not an issue with ag-Grid we need to fix, so closing issue, Github project is for tracking issues with ag-Grid!
