### ISSUE TITLE
how to pass "this"  to click event in ag grid. 

### ISSUE THREAD

**Issue by rajgopalk** [ceolter/ag-grid#1295]
{
                headerName: "Patient Name", field: "patientName", width: 250, enableValue: true, suppressMenu: true, suppressFilter: true, suppressSorting: true, enableRowGroup: true,
                cellRenderer: function (params) {
                    return '<span title=\"Patient Name \" class=\"dummylink \"  ng-click=\"ClaimSumPatientNameEvent(this)\">' + params.value + '</span>';
                }

i tried below also but not working,
{
                headerName: "Patient Name", field: "patientName", width: 250, enableValue: true, suppressMenu: true, suppressFilter: true, suppressSorting: true, enableRowGroup: true,
                cellRenderer: function (params) {
                    return '<span title=\"Patient Name \" class=\"dummylink \"  ng-click=\"ClaimSumPatientNameEvent('+this+')\">' + params.value + '</span>';
                }

**Comment by ceolter** [comment]
this is a JavaScript question, not an issue with ag-grid, so closing

if using angular 1, then 'this' needs to be on your scope, i dont understand what you are trying to do, but if you did want 'this' then it would be:

{
headerName: "Patient Name", field: "patientName", width: 250, enableValue: true, suppressMenu: true, suppressFilter: true, suppressSorting: true, enableRowGroup: true,
cellRenderer: function (params) {
params.$scope.this = this;
return '<span title="Patient Name " class="dummylink " ng-click="ClaimSumPatientNameEvent(this)">' + params.value + '';
}
