### ISSUE TITLE
DOM IDs should be unique.

### ISSUE THREAD

**Issue by remosewa** [ceolter/ag-grid#1296]
According to the w3 coding standards, element ids should be unique for the entire page. It looks like the convention ag-grid is using for header templates breaks this.

i.e. every header will have this:

```
        <span id="agSortAsc" class="ag-header-icon ag-sort-ascending-icon"></span>
        <span id="agSortDesc" class="ag-header-icon ag-sort-descending-icon"></span>
        <span id="agNoSort" class="ag-header-icon ag-sort-none-icon"></span>
        <span id="agFilter" class="ag-header-icon ag-filter-icon"></span>
        <span id="agText" class="ag-header-cell-text"></span>
```

**Comment by ceolter** [comment]
this was raised before. all the browsers allow duplicate dom ids, yes it goes against the spec, but it doesn't break anything.

we plan to change this in the future but not high priority. as there is another issue open for this, am closing.
