### ISSUE TITLE
field values become undefined, when applying grouping by drag n drop column

### ISSUE THREAD

**Issue by rajgopalk** [ceolter/ag-grid#1297]
hi, in cell render at column level,initially it is working fine. but when iam doing grouping it gives error like "Unable to get property 'claimNumber' of undefined or null reference" .Before doing grouping is fine. i dont know why it is coming, can you tell me, whats wrong with my code.

 {
               headerName: "", field: "check_row", width: 40, 
               cellRenderer: function (params) {
                   if (params.data.claimNumber != undefined) {
                       return '<input type=\"checkbox\" name=\"select\" ng-click="GetCheckBoxValues()" />';
                   }
                   else {
                       return "";
                   }
               }
           },

**Comment by ceolter** [comment]
best way to understand this is to debug through your cellRenderer, look inside the params.data item.

for the grouped items (ie the parent rows, the ones you expand), the data will be missing if you are not doing any aggregation. so i'm guessing you are not doing any aggregations.

so 
```
cellRenderer: function (params) {
  if (params.data && params.data.claimNumber != undefined) {
    return '<input type="checkbox" name="select" ng-click="GetCheckBoxValues()" />';
  } else {
    return "";
  }
}
```
