### ISSUE TITLE
Scrollbar position does not reset to top if rowData changes

### ISSUE THREAD

**Issue by jasmeetssalech** [ceolter/ag-grid#1298]
While doing an ajax call and showing the results in the ag-grid, once you scroll to the bottom in grid (assuming you have set the hieght of the grid with say 300px), and you again make an ajax call and rowData changes, then the scrollbar does not come to the top.

**Comment by ceolter** [comment]
after you set the data, call api.ensureNodeVisible(0)

**Comment by pidov** [comment]
Did this behavior change? 

I'm new to AgGrid and I experience the oposite behavior - I want to retain the scroll position when rowData changes but the grid always resets the scrollbar to its initial position. 

NB: I'm using the react implementation. Perhaps my question is better suited in the other repo.
