### ISSUE TITLE
undefined or null reference error

### ISSUE THREAD

**Issue by rajgopalk** [ceolter/ag-grid#1299]
ng-click is working fine.i need to pass another field value in one column.my code is
 {
               headerName: "Claim No.", field: "claimNumber", width: 100,enableRowGroup: true,filter: 'number',
               cellRenderer: function (params) {
                   if (params.value != undefined) {
                       return '<span  title=\"Claim No\" class=\"dummylink \"  ng-click=\"ClaimIdClickEvent(' + params.data.ClaimID. + ')\">' + params.value + '</span>';
                   }
                   else {
                       return "";
                   }
               }
           },

initially it is working fine. suppose if iam doing grouping, it shows error like ClaimID is undefined or null reference. i dont know why it is coming.

**Comment by ceolter** [comment]
this is a duplicate
