### ISSUE TITLE
how to set vertical alignment to middle to rows

### ISSUE THREAD

**Issue by rajgopalk** [ceolter/ag-grid#1303]

**Comment by rajgopalk** [comment]
this is my code.

 {
               headerName: "Date of Service", field: "dateofService", enableRowGroup: true, width: 140, cellStyle: { color: 'red',verticalAlign: 'center' },
           },

i tried below one also
 {
               headerName: "Date of Service", field: "dateofService", enableRowGroup: true, width: 140, cellStyle: { color: 'red','vertical-align': 'center' },
           },

**Comment by ceolter** [comment]
it's the job of the grid to allow you to specify styles. so inspect the cell dom, see if the style is getting added to the cell. if it is, then the job of the grid is done.

if the css however is not achieving the effect you want, then this is a javascript / css question (ie not an issue with ag-Grid, so closing this issue)
