### ISSUE TITLE
getRowStyle

### ISSUE THREAD

**Issue by hunguyen75** [ceolter/ag-grid#1305]
I was able to apply background-color to grid rows by using the getRowStyle callback. Is there a way to get the background color applied to all the rows from the grid (before or without using deferred scrolling)? Let's say I have 100 records within the grid but the grid initially shows 50 records before scrolling. What I want is to get those applied background colors from those 50 records at the bottom before I start scrolling.

**Comment by ceolter** [comment]
gird has no way of doing this. you could use standard JavaScript and DOM manipulation to see what CSS was applied to the DOM. nothing that the grid has to specifically help you.
