### ISSUE TITLE
Multiple detail panesl (sub grid) in different column ?

### ISSUE THREAD

**Issue by crapthings** [ceolter/ag-grid#1309]
project object

```
{
  name: 'project 1',
  desc: 'project 1 desc',
  members: [user1, usr2]
  tasks: [task1, task2],
}
```

i want to show memebrs and tasks count on that column, and u can expend sub grid with them.

can we do something like this with ag-grid ?

this example only show 1 detail

https://www.ag-grid.com/javascript-grid-master-detail/exampleMasterDetail.html

**Comment by crapthings** [comment]
it seems doesDataFlower work with this situation.

```
doesDataFlower(data) {
    return data
}
```

but i can't get parent colDef info with

```
fullWidthCellRenderer: DetailPanelCellRenderer
```

**Comment by ceolter** [comment]
not sure what you mean by 'parent colDef info from parent colDef', as the rows all use the same column definitions.

unless you are using fullWidthCellRenderer, in which case there is no colDefs (as there are no columns), so again doesn't make sense.

if you want anything passed down to the child row, you should put it into your data (which you can access from the params).

ps closing, we want github for tracking issues with ag-Grid, not client applications.
