### ISSUE TITLE
Filter dropdown unexpectedly closes when I start typing after scrolling down in the grid

### ISSUE THREAD

**Issue by theodorejb** [ceolter/ag-grid#1314]
I'm using v7.0.2.

When I start typing in the filter text field (e.g. using the Contains option), as soon as one or more rows are filtered out, the filter dialog closes which prevents me from finishing entering the filter value.

It seems to work fine when the scrollbar is at the top of the grid, but I see the problem when I try to filter after scrolling down.

**Comment by ceolter** [comment]
fixed, will be in next release. the column menu will now only disappear on horizontal scroll, not verical (it disappears for vertical, as when grid moves, popup is no longer over the right column)
