### ISSUE TITLE
Is there any way to set the currency format(like 223,200) in Ag-grid using Angular2.

### ISSUE THREAD

**Issue by nunna-suma** [ceolter/ag-grid#1317]
Hi 

I'm new to ag-grid. Can anyone help to resolve the currency format issue in ag-grid using angular 2. I'm printing the Rent amount in a column of ag-grid i want to print the amount in US r any currency format so that it is esasy to understand is there anyway (or) any keyword to print the amount like 223,405 like these.

`{
         cellRendererFramework: { template: '{{params.SchoolRent | currency}}'},
         headerName: 'School Rent', field: 'SchoolRent', width: 130, 
       },`

http://stackoverflow.com/questions/40172852/currency-format-in-ag-grid-using-angular-2-latest-version

Please help me to resolve these issue.

Thanks in advance.

**Comment by ceolter** [comment]
we are using github is for tracking issues with ag-Grid project, not for tracking client issues, so closing.

ps with regards above, i don't know the answer.
