### ISSUE TITLE
isAnyFilterPresent still returns true after setRowData clears filter settings

### ISSUE THREAD

**Issue by rellis-of-rhindleton** [ceolter/ag-grid#1320]
(This can be worked around; it's not a showstopper.)

Assuming this isn’t supposed to happen, here’s how I reproduce:

 - Leave `filterParams` at default (do _not_ set `newRowsAction` to ‘keep’).
 - Call `setRowData` to populate the grid.
 - Set one of the column filters, e.g. contains ‘filtertext’.
 - Call `setRowData` again with new data.

Consistent with the documentation, the filter settings are automatically cleared.  Then this is what I get from various gridOptions.api methods:

 - `getFilterModel` returns an empty object `{}`.
 - `isQuickFilterPresent` returns false.
 - `isAdvancedFilterPresent` returns false.
 - `isAnyFilterPresent` returns **true**.

That last one supposed to happen?  I can avoid this problem by using `setFilterModel(null)`, but wasn’t expecting to have to.

**Comment by ceolter** [comment]
fixed. will be in next release. thanks.
