### ISSUE TITLE
set focus for a node found through api

### ISSUE THREAD

**Issue by paradicey** [ceolter/ag-grid#1325]
Hi, 
Is there a way to setfocus on a cell when I only know the node id?
basically I am trying to comb through the data and find the field I am looking for, then expand the grid(which I already know how to), then focus on it. I couldn't find any clue how to do the last step.

Any suggestion will be appreciated.

Thanks.

**Comment by ceolter** [comment]
to focus a cell, use ```api.setFocusedCell(rowIndex, colKey, floating)```
