### ISSUE TITLE
Remembering user's column order upon reload of the page?

### ISSUE THREAD

**Issue by Owizardo** [ceolter/ag-grid#1327]
Hi there, 

I am new with this tool and really loving it! Im trying to find a way so that the app can remember the order of columns even after you reload the page. I've been scanning trough the API but cant seem to find the way to remember the users column order or simply the grids state. Is this something that AG-GRID is capable of?

**Comment by Rogerio-Soares** [comment]
Hi!

```
// get / set state
gridOptions.columnApi.getColumnState();
gridOptions.columnApi.setColumnState(json);

// get / set sort
gridOptions.api.getSortModel();
gridOptions.api.setSortModel(json);

// get / set filter
gridOptions.api.getFilterModel();
gridOptions.api.setFilterModel(json);
```

https://www.ag-grid.com/javascript-grid-column-api/

Happy coding!

**Comment by Owizardo** [comment]
Thanks for the quick reply. I saw that we example on the website located here https://www.ag-grid.com/javascript-grid-column-api/columnStateExample.html. When I re-arrange the columns and hit save col state. All my changes get reset to default when i refresh the page. Doing restore col state after a refresh just give a blank table. 

Maybe I am missunderstand the use of these functions but does anyone know if this is a bug or if there an alternative way of doing this?

**Comment by Rogerio-Soares** [comment]
The example don't use browser storage to persist the state. Something like above should do the trick.
```
var savedState = gridOptions.columnApi.getColumnState();
sessionStorage.setItem('savedState', savedState);
...
var savedState = sessionStorage.getItem('savedState');
gridOptions.columnApi.setColumnState(savedState);
```

**Comment by ceolter** [comment]
thanks @Rogerio-Soares 
closing issue as answered

**Comment by ssilve1989** [comment]
@Rogerio-Soares What about when you are in pivot mode? It doesn't seem to work the same way when pivot mode is enabled.

**Comment by mateuscg-cit** [comment]
@invisor @ssilve1989 did you manage to find a solution for that?

**Comment by ssilve1989** [comment]
@mateuscg-cit Currently I am doing something like 
```typescript
const columnOrder = columnApi.getAllDisplayedColumns().map(column => column.getColId())
``` 
and persisting that. Restoring via 
```typescript
columnApi.moveColumns(columnOrder, 0)
```
