### ISSUE TITLE
Angular - How to get the visibility state of a column?

### ISSUE THREAD

**Issue by Owizardo** [ceolter/ag-grid#1328]
Hi there,

Curios, is there an easy way to get the visibility state of a specific column? For example when I use $scope.gridOptions.columnApi.getColumnState("Column_ID_example") it returns an array of objects with all the properties of each columns. My guess it's the getColumnState is not meant for this type of task.

Is there an easy way to have it return the hide value of the column in a boolean format (true or false)? Since im using Angular there must be an easy way of doing this via it's scope, right?

**Comment by ceolter** [comment]
```
var column = columnApi.getColumn('name'); // where field = name
console.log('column visible = ' + column.isVisible() );
```
