### ISSUE TITLE
[BUG] Filtering a non-existent column value in a overflowed div

### ISSUE THREAD

**Issue by edunad** [ceolter/ag-grid#1330]
Hello, first, i would like to apologize if this bug is already raised (couldn't find it).

I've encountered an issue with filtering, where if you have columns beyond the table width (creating a Horizontal Scroller) and you filter a column with an invalid value, the scroll and data disappear, not allowing you to remove that filter.

It's a bit hard to explain, so I've attached a GIF and instructions showing the issue (from https://www.ag-grid.com/javascript-grid-filtering/)

http://i.imgur.com/MbcVV3z.gifv

Browser : Chrome (54.0.2840.99 m)

How to replicate : 
- Open https://www.ag-grid.com/javascript-grid-filtering/
- On the second table (Apply Function), scroll to the Total column
- Filter it using a random value (11 for example)
- BAM, you can't change that filter and the data is gone

Thanks :)

**Comment by ceolter** [comment]
fixed. will be in next release.
