### ISSUE TITLE
size columns to fit causes scrollbar flipping

### ISSUE THREAD

**Issue by Ruud-cb** [ceolter/ag-grid#1333]
Hi,

I'm having trouble with the `sizeColumnsToFit()` method. I'm executing this with a timeout after a column is resized, like so:
```
this.columnResizedEvent = function (col) {
            clearTimeout(self.timeoutResize1);
            self.timeoutResize1 = setTimeout(function () {
                self.gridTableOptions.gridOptions.api.sizeColumnsToFit();
                clearTimeout(self.timeoutResize1);
            }, 1000);
    };
```

where `self` just refers to an object so we have a global variable.
The idea is to resize the columns after a change in width has happened, but only execute it after a minute, so it is not happening instantly.

Best to illustrate the problem is by providing some pictures.
First, this is the state of the grid, everything is correct. (The height is static).

![image](https://cloud.githubusercontent.com/assets/10037514/21137888/e4a56022-c12b-11e6-98d8-7211a7b4da54.png)

Then, I drag the middle column and start resizing larger, when I do this the scroll bars appear, that's obvious because it doesn't fit anymore.

![image](https://cloud.githubusercontent.com/assets/10037514/21137934/182dd7b2-c12c-11e6-967f-4158fed8c9a1.png)

Now when I stop resizing, the event kicks in and the timeout executes which resizes all columns.
The result is some what surprising:

![image](https://cloud.githubusercontent.com/assets/10037514/21138120/fc3fd7e8-c12c-11e6-822d-02b1f12f3b5a.png)

As you see, there is enough space below it so there is no scroll bar needed, yet it still keeps showing up.
Now at that time, the column resize event gets triggered again, eventually after a second causing another call to `sizeColumnsToFit()`. Then, this happens:

![image](https://cloud.githubusercontent.com/assets/10037514/21138195/3c3d0320-c12d-11e6-8637-8d3594a3afe2.png)

The horizontal scrollbar shows up again, while I can't scroll with it.

It is very hard to re-produce, it requires a specific height with a specific amount of items. Worst-case scenario is happening when the column resized event gets triggered again, causing an infinite loop in flipping scroll bars.
I think there is a little bit going wrong in the calculation when columns get resized.

Could you please advise me on a work around or fix this bug?

**Comment by AnaSofiaGrilo96** [comment]
+1

**Comment by Piccirello** [comment]
I'm experiencing this issue as well.

One temporary fix is to call sizeColumnsToFit() in both onGridSizeChanged() and onViewportChanged(). This only works because it results in sizeColumnsToFit() being called multiple times, which is far from being the most elegant solution.

**Comment by Ruud-cb** [comment]
@Piccirello Hi, that seems to be working for the initial loading, thanks.

On resizing the columns (larger then view) the bug still happens. The `onGridSizeChanged` and `onViewportChanged` do not get triggered of course.

**Comment by Piccirello** [comment]
Have you tried calling `sizeColumnsToFit` in `onColumnResized`? I haven't personally used that event but it looks promising.

**Comment by Ruud-cb** [comment]
@Piccirello Yes I have and that is what I do in the first post. I added an timer to prevent an infinite loop, because the swapping causes a resize for almost each column.

**Comment by ceolter** [comment]
fixed in latest. there was a bug in the grid check if horizontal scroll was present or not (instead of vertical scroll) when working out the available width.

**Comment by jkjha** [comment]
May I know which version has this fix?

**Comment by Vahanhakobyan85** [comment]
I'm using AgGrid and there were some free space for columns on the right side. I wanted to make the grid to use the whole area allocated for that and called 'sizeColumnsToFit()' after that I noticed that horizontal scroll is not appearing on adding new columns.
This future is fixed ? or this is another issue?
If yes started from which version this issue is fixed? 
Thanks in advance.

**Comment by miaozilong** [comment]
which version has fix the probleam   it 's  2019 now    and i met the issue   !!!

**Comment by Lyubomir-Stavrev-Dev** [comment]
Has someone found a solution to that ?
