### ISSUE TITLE
date value changed between editor and grid 

### ISSUE THREAD

**Issue by squarewave24** [ceolter/ag-grid#1336]
I've added a simple date editor. 

When I enter the date, I can see correct date emitted in getValue()

but grids newValueHandler gets called with another update where the new date is decremented by 1 day. 

I am writing out events to the console: 

> DateEditorComponent getValue() called 2001-01-01
> newValueHandler  Object {node: RowNode, data: Object, oldValue: "2001-01-01T00:00:00", newValue: "2001-01-01", colDef: Object…}
> generalvalueChangedHandler  undefined Object {node: RowNode, data: Object, oldValue: "2001-01-01T00:00:00", newValue: Sun Dec 31 2000 19:00:00 GMT-0500 (Eastern Standard Time), colDef: Object…}
> 

notice that newValueHandler gets called with correct value. somewhere after that, it gets changed to a day earlier. 
 
I have no idea what's changing the value from 1/1/2001 to 12/31/2000. 

```
@Component({
    selector: 'date-cell',
    template: `
        <input #input type="date" (keydown)="onKeyDown($event)" [(ngModel)]="value" />`
})
export class DateEditorComponent implements AgEditorComponent, AfterViewInit {
    private params:any;
    private value:Date;
    private cancelBeforeStart:boolean = false;

    @ViewChild('input', {read: ViewContainerRef}) private input;

    agInit(params:any):void {
        this.params = params;
        this.value = this.params.value;
        this.cancelBeforeStart = params.charPress && ('1234567890/'.indexOf(params.charPress) < 0);
    }
    getValue():any {
        console.debug('DateEditorComponent getValue() called', this.value);
        return this.value;
    }
    isCancelBeforeStart():boolean {
        return this.cancelBeforeStart;
    }
    isCancelAfterEnd(): boolean {
        return this.value > new Date(9999, 1, 1);
    };
    onKeyDown(event):void {
        if (!this.isKeyPressedNumeric(event)) {
            if (event.preventDefault) event.preventDefault();
        }
    }
    ngAfterViewInit() {
        this.input.element.nativeElement.focus();
    }
    private getCharCodeFromEvent(event):any {
        event = event || window.event;
        return (typeof event.which == "undefined") ? event.keyCode : event.which;
    }
    private isCharNumeric(charStr):boolean {
        return !!/\d/.test(charStr);
    }
    private isKeyPressedNumeric(event):boolean {
        var charCode = this.getCharCodeFromEvent(event);
        var charStr = String.fromCharCode(charCode);
        return this.isCharNumeric(charStr);
    }
}

```

**Comment by ceolter** [comment]
closing as not an issue with ag-Grid - Github issues are for tracking items we need to to fix in ag-Grid :)

with the above, i see nothing wrong, however my next step would be to debug through it, start at getValue() and follow what the grid is doing. my guess is grid is doing nothing, but it's seomthing to do with your browser and timezones.

**Comment by squarewave24** [comment]
this is a local call right now so there is no timezone offset. getValue() returns correct value, grids newValueHandler gets the wrong value. not sure where to troubleshoot what happens in between these 2 events

**Comment by ceolter** [comment]
ah you say newValueHandler is getting called with correct result (i misread first time).

as to why your data is magically changing, i have no idea. if you have newValueHandler set up, the grid should be never changing your data.
