### ISSUE TITLE
Row selection event when group row footer is clicked

### ISSUE THREAD

**Issue by bnrdo** [ceolter/ag-grid#1337]
Hi,

Very nice grid!

I've been reading the documentation instensely but I cannot find a way to make the group row footer selectable. Is there a way to make the group row footer to behave as if it is a normal row? E.g. onSelectionChanged and onRowSelected will be notified of the selection.

Thanks,
Bernardo

**Comment by ceolter** [comment]
thanks for positive feedback :)

no way to select footer - the footer doesn't exist in the row model, it's just something that's attached to the group (header), so if you select the group header, the footer also gets selected.

when you are using click to select (not checkbox), then clicking the footer selects the group.

when using checkbox, we don't put a checkbox on the footer for this reason.
