### ISSUE TITLE
api for "row group expanded or not" give undefined?

### ISSUE THREAD

**Issue by rajgopalk** [ceolter/ag-grid#1341]
hi, 

i want to maintain state of row group. that is opened or not.
iam trying like this.

onRowGroupOpened: function () {
                $scope.ExpandOrNot=$scope.gridOptions.api.onGroupExpandedOrCollapsed();
            }

it gives undefined.

**Comment by ceolter** [comment]
that api is to tell the grid you have expanded or collapsed an group node, which then results in the grid getting refreshed. it is not for returning any info. it is meant to return undefined.
