### ISSUE TITLE
'groupHeaders' does not exist in type 'GridOptions'

### ISSUE THREAD

**Issue by vlio20** [ceolter/ag-grid#1344]
My app is written in TS and I am using the `GridOptions` interface (I use the original .d.ts file - not the dt declaration). I have just upgraded to version 7.* from 5.*.
I am using the 'groupHeaders' property in my grid configuration. Here is the full error that I am getting:  
```
error TS2322: Type '{ columnDefs: null; rowData: null; angularCompileRows: false; groupHeaders: boolean; enableSortin...' is not assignable to type 'GridOptions'.
  Object literal may only specify known properties, and 'groupHeaders' does not exist in type 'GridOptions'.
```

This is how I am importing the `GridOptions` interface:  
`import {GridOptions} from 'ag-grid';`  

If it has been removed from the GridOptions then the documentation should be also updated because currently it is still uses the `groupHeaders` option: https://www.ag-grid.com/javascript-grid-grouping-headers/

**Comment by ceolter** [comment]
this was removed in Version 3.0.0

i didn't see it mentioned in the docs page you referenced (maybe we took it out in last release) however i did see it in some examples, so have taken it out of all examples i could find it in.

**Comment by vlio20** [comment]
@ceolter, it is still there, under the javascript tab. adding this screenshot: http://prntscr.com/dscc8e

**Comment by ceolter** [comment]
i haven't updated the website yet, will be done in next release.

you can see latest docs source here:
https://github.com/ceolter/ag-grid-docs/tree/master/src/javascript-grid-grouping-headers

**Comment by vlio20** [comment]
cool, thanks!
