### ISSUE TITLE
@import 'nib'?

### ISSUE THREAD

**Issue by don-bluelinegrid** [ceolter/ag-grid#1346]
@ceolter 

Niall,

I am setting up a production version of the webpack build for our project, and because of the stricter error checking I'm finding some errors that I didn't see before - and one of them is in agGrid 7.0.2.

The one I've found is related to ```@import 'nib'``` in the ```ag-grid/src/styles/ag-grid.styl``` file.  What's the purpose of this? Isn't nib used by the Stylus processor, not directly by the style file?  Any ideas on what needs to be done to eliminate the webpack build error?  It seems that the import in the .styl file expects to resolve to a .styl file, but the nib file in node_modules is a .js file.
```
ERROR in ./styles/theme-blg.styl
Module build failed: Error: /Users/donpeterkofsky/Documents/gc-2-dev/node_modules/ag-grid/src/styles/theme-common.styl:9:9
    5| 
    6| */
    7| 
    8| 
    9| @import 'nib'
--------------^
   10| 
   11| .ag-{ag-style}
   12|   // copying bootstrap with line-height, sorts out alignment problems with images beside text

failed to locate @import file nib.styl
```

Thanks,
Don

**Comment by don-bluelinegrid** [comment]
Also, for reference -

I had previously included this section in our webpack build file, based on the documentation for nid:

```
  module: {
      loaders: loaders
  },
  stylus: {
    // preferPathResolver: 'webpack',
    use: [require('nib')()],
    import: ['~nib/lib/nib/index.styl']
  }
```

**Comment by ceolter** [comment]
i don't know what it's for, i didn't do this part. everything seems to work without the import, so i've taken it out, i'll be going through all the online examples before our next release (part of the regression), will see if anything breaks.
