### ISSUE TITLE
Multi sorting not always working

### ISSUE THREAD

**Issue by ha-decodeit** [ceolter/ag-grid#1350]
We are facing a strange issue that multi-column sorting is not working for all column combinations.

You can reproduce this issue on the ag-grid own demo ([ag-grid.com/example.php](https://www.ag-grid.com/example.php)) by sorting "Bank Balance" first and then "Rating". Doing it the other way around is working as expected. 
We could not identify a specific pattern for this behavior. Any help would be appreciated. 

Cheers

**Comment by ceolter** [comment]
working as expected.

as bank balance only has unique values, then it doesn't make sense to sort it again. sorting again only makes sense when the first column you sort by has groups of items that are equal.

**Comment by nmz787** [comment]
I have a custom sorting `comparator` and I am facing this issue as well. How can I force sorting to occur, any time sorting is called on by the user? My columns seem clearly unsorted by the second column (i.e. a design flaw).

**Comment by jorge-fuentes-n3uron** [comment]
> I have a custom sorting `comparator` and I am facing this issue as well. How can I force sorting to occur, any time sorting is called on by the user? My columns seem clearly unsorted by the second column (i.e. a design flaw). Data that I am first sorting on DOES have duplicates in that column, second column values are unique.

Hey @nmz787 have you fixed this?

EDIT: Done. The problem is the first comparator not returning 0 when the elements are equal.
