### ISSUE TITLE
clear button on each Column of ag-grid 

### ISSUE THREAD

**Issue by jprathore** [ceolter/ag-grid#1358]
Hi, 
I am using ag-grid for one of my project and wanted to implement clear filter button on each column of agid (currently , i have 16-column on my grid).It will be not good design to place 16 clear button on page to clear each column. 
I wanted each column have one clear button below of  **Quick Filter**.

Please suggest hint to  implement this functionality.

Thank you.

**Comment by ceolter** [comment]
as this is a question about your app and not ag-grid, i'm closing the issue. ag-grid issues are for things we need to fix in ag-grid.

this doesn't mean that someone can make helpful comments below.

**Comment by re5ive** [comment]
any idea about this ?? me also need the same with react comp :)
