### ISSUE TITLE
Update columns

### ISSUE THREAD

**Issue by Neir0** [ceolter/ag-grid#1359]
Hi,

After changing columns in gridOptions, are there any way to update it in the grid?

For example:
this.gridOptions.columnDefs = this.newColumns;
this.grid.api.refreshHeader(); // doesn't work

**Comment by Neir0** [comment]
Alright, probably grid.api.setColumnDefs is way to go

**Comment by ceolter** [comment]
grid.api.setColumnDefs is correct
