### ISSUE TITLE
Get first row that's actually displayed

### ISSUE THREAD

**Issue by Tokyros** [ceolter/ag-grid#1360]
I'm trying to get the index of the first row shown.

I need to that so I can restore the scroll position of the grid, but if I use api.getFirstRenderedRow(), I get an index from outside the actually shown grid...

Is there a way to get the first row that is below the header?

thanks!

**Comment by ceolter** [comment]
closest thing is event viewportChanged, the event has the index of the first and last rows rendered.

the default rowBuffer is 10, so 10 rows are rendered above and below the grid. you can set the rowBuffer to zero to get the viewport to be in sync with what you see.

**Comment by Fang520** [comment]
It's pity, the basic function was not provided.

**Comment by barper** [comment]
Just posting in case this helps someone I just grabbed the x-y of the header and grabbed the first row using that.

This solution doesn't take into account floating headers and just assumes you only have ag-header as the topmost element (I also have a large row height so picked appropriate rem size.

    const headerRect = (this.querySelector('.ag-header').getBoundingClientRect());

    const remSize = parseInt(getComputedStyle(document.body).fontSize);

    const firstVisible = document.elementFromPoint(headerRect.x+remSize, (headerRect.y + headerRect.height + remSize))

    console.log('firstVisible', firstVisible)

    const rowIndex = firstVisible.closest('.ag-row').getAttribute('row-index');

    console.log('rowIndex', rowIndex)

**Comment by AStaroverov** [comment]
I found! `agGridApi.getModel().getRowIndexAtPixel(0)`

**Comment by gl00m** [comment]
little bit verbose :)
```
onBodyScrollEnd(e: BodyScrollEndEvent) {
            console.log('e.api.getModel().getRowIndexAtPixel(e.top))
        }
```

**Comment by MurphyHou123** [comment]
e.api.getModel() is deprecated. Any other way???? getFirstDisplayedRowIndex does not work as expected.

**Comment by mikeburgh** [comment]
For anyone else who finds this: 

```javascript
const rows = this.api.getRenderedNodes();
const top = this.api.getVerticalPixelRange().top;
const firstRow = rows.find((row) => (row.rowTop || 0) > top);
```

**Comment by astraveritas** [comment]
> For anyone else who finds this:
> 
> const rows = this.api.getRenderedNodes();
> const top = this.api.getVerticalPixelRange().top;
> const firstRow = rows.find((row) => (row.rowTop || 0) > top);

Thank you!

**Comment by gdfeltti** [comment]
> For anyone else who finds this:
> 
> const rows = this.api.getRenderedNodes();
> const top = this.api.getVerticalPixelRange().top;
> const firstRow = rows.find((row) => (row.rowTop || 0) > top);

This didn't work any better than just using `this.api.getFirstDisplayedRowIndex()` is there anything newer?

**Comment by gdfeltti** [comment]
new for anyone who needs it. (uisng the VerticalPixelRange to find which row index falls within the top of the range)
```
const realRowTop = this.api.getRenderedNodes().find((i) => {
            const currentPage = this.api.paginationGetCurrentPage();
            const previousPagesPixels = currentPage * this.api.paginationGetPageSize() * i.rowHeight;

            let topOfRow = i.rowHeight * (i.rowIndex + 1);
            let bottomOfRow = i.rowHeight * i.rowIndex;

            topOfRow -= previousPagesPixels;
            bottomOfRow -= previousPagesPixels;

            return bottomOfRow < top && top <= topOfRow;
        });
```
