### ISSUE TITLE
Changing Row Selection From Single To None dynamically

### ISSUE THREAD

**Issue by abhibly** [ceolter/ag-grid#1361]
Hello...I want to disable the row selection dynamically.I have a situation where i show a list of Manufacturers in the grid and user can select a row.But outside the grid there is a checkbox,when the user sets it to true i need to disable the row selection in grid , i.e i want the row selection to be none and user cannot select any rows further.Again when the user unselects the checkbox i want the grid to have single row selection.What is the easiest way to have this.Is there any api call to achieve this?

**Comment by ceolter** [comment]
to toggle selection, change the rowSelection property.

alternatively, keep selection off, then use the grid api for selection (add your own click listener).

**Comment by mafixmafix** [comment]
use this` [suppressRowClickSelection]="true" ` for suppress row selection

**Comment by Mohammadhamza43** [comment]
HI, I am trying to do something similar like instead of disabling the row selection, I want to change the grid selection from 'Single' to 'Multiple'.
Here is What I am doing, I have two grids adjacent to each other and if any of the grid selection count is greater than 1, the other grid selection type will change to 'Single'. how to achieve that? So far i have done something like this, but it is not working some times


### TS code
onFirstGridRowClicked($event: any) {
    console.log($event.data);
    this.rowSelectionSecondGrid = this.firstGridApi.getSelectedRows().length > 1 ? 'single' : 'multiple'
    this.cdRef.detectChanges();
  }

  onSecondGridRowClicked($event: any) {
    console.log($event.data);
    this.rowSelectionFirstGrid = this.secondGridApi.getSelectedRows().length > 1 ? 'single' : 'multiple'
    this.cdRef.detectChanges();
  }
  
  ### **HTML CODE**
  
  **FIrst Grid**
  <ag-grid-angular
        class="ag-theme-alpine grid_measurement"
        [rowData]="rowData | async"
        [columnDefs]="columnDef"
        [overlayLoadingTemplate]="overlayLoadingTemplate"
        [pagination]="true"
        [rowSelection]="rowSelectionFirstGrid"
        [rowMultiSelectWithClick]="true"
        (gridReady)="onGridReady($event)"
        (rowClicked)="onFirstGridRowClicked($event)"
        (firstDataRendered)="onFirstDataRendered($event)">
        </ag-grid-angular>
        
        **Second Grid**
        <ag-grid-angular
        class="ag-theme-alpine grid_measurement"
        [rowData]="rowDataSecondGrid | async"
        [columnDefs]="columnDefSecondGrid"
        [pagination]="true"
        [rowSelection]="rowSelectionSecondGrid"
        (rowSelected)="onSecondGridRowClicked($event)"
        [overlayLoadingTemplate]="overlayLoadingTemplate"
        (firstDataRendered)="onFirstDataRendered($event)"
        (gridReady)="onGridReady($event)"
        [rowMultiSelectWithClick]="true"
        [isRowSelectable]="isRowSelectable">
        </ag-grid-angular>
