### ISSUE TITLE
Expandable ag-grid without grouping

### ISSUE THREAD

**Issue by vikash159** [ceolter/ag-grid#1362]
![expandable](https://cloud.githubusercontent.com/assets/13450977/21494189/b82315d4-cc35-11e6-81ac-b28c45dc69c9.png)

does ag-grid support expandable grid like i have attached image without grouping
as i need expandable grid, where on click on plus icon there will be a http call to display the sub-grid
is this possible in ag-grid?

Thank.

**Comment by ceolter** [comment]
see examples here
https://www.ag-grid.com/javascript-grid-master-detail/
