### ISSUE TITLE
Misalignment between header cell border and body cell border

### ISSUE THREAD

**Issue by iboffa** [ceolter/ag-grid#1363]
![capture](https://cloud.githubusercontent.com/assets/24269444/21496996/b426d596-cc22-11e6-88c9-1195510a00d0.PNG)

The red bar is the Bid Size cell left border.

"Bid Size" is the leftmost right-pinned column of my grid. As you can see its border falls in non-pinned columns space. If I scroll non-pinned columns to the extreme left I can see an empty space (i think about 12px), as if it was reserved for a scrollbar.

How to fix it without hacking css?
Is it a bug?

Regards

**Comment by ceolter** [comment]
i believe this was fixed in 7.1.0 (a lot of the pinned stuff was refactored with the introduction or RTL).

if not, please report back.
