### ISSUE TITLE
using cellEditorFramework and ValueGetter 

### ISSUE THREAD

**Issue by TheILPlace** [ceolter/ag-grid#1364]
hi, here is my situation.
one of my data columns, is a class. that has 2 properties (fromTime, toTime).
in order to show it correctly on the grid, i use a ValueGetter that concatenates the two properties with a hyphen.
this column has an angular2 editor component with 2 time pickers.
in order to get the original object, i can access the data via the params - which is kind of ok.

to return the selection, i am implementing getValue() . which returns the object with the time range properties into the data source.
this is ok.

in the grid component, i wanted to watch the cell change event, in order to see the old value and the new one.  and send it to the server.
what i see is not the original object, but the string returned from the getter (both old and new value)
how can i retrieve the old value (the object)  and not the manipulated string ?

hope my question was clear.

**Comment by TheILPlace** [comment]
i'll rephrase :

Using angular2, with Cell Editor Component,
the field data is an object with 2 properties.
Field also using a ValueGetter to display the values (concatenated)

registering newValueHandler  with the field.

according to the documentation:

**Comment by ceolter** [comment]
to clarify, this is to do with cellEditor and ValueGetter, it's nothing specific to Angular 2.

the behaviour is how the grid is expected to work.

the valueGetter should be returning the value to he cellRenderer, not a formatted version of it.

what you need to do is restructure what your valueGetter does, so it passes to the editor what you want to pass to your server.

**Comment by TheILPlace** [comment]
thanks for your answer.
maybe i misused the valueGetter..
i understand now, that i should use a cellRenderer to manipulate the format of the data shown on the grid, and not the valueGetter
