### ISSUE TITLE
Direct way to retrieve datasrouce

### ISSUE THREAD

**Issue by elaijuh** [ceolter/ag-grid#1366]
I am doing server side pagination and I set the datasource by API
`gridOptions.api.setDatasource(ds)`
I noticed that the ds is stored in paginationController and there is not an explicit way to get it back when I want to get the data from server side again.
`gridOptions.api.setDatasource()` just returns without any action

But if I manually store the datasource in gridOptions, I can get it back by
`gridOptions.api.gridOptionsWrapper.getDatasource()`

This works but definitely not a clear way to do it, shall we have an API to do that?

**Comment by ceolter** [comment]
the gridOptionsWrapper is internal to the grid. i've no problem with you using it (up to you if you want to), however it's internal and not documented, so we can change the implementation and it's not considered a break change.

the datasource is provided by you, so you should already have a reference to it?

given you have the datasource, i don't see why the grid should allow you to get it, and we dont' like writing code that is not needed, as that creates unneeded complexity on our side.
