### ISSUE TITLE
Server side filtering not saving with filterParams: {newRowsAction: 'keep'}

### ISSUE THREAD

**Issue by arminconscia** [ceolter/ag-grid#1369]
Hey,

Was doing server side filtering on a virtual scrolling grid, and was using "filterParams: {newRowsAction: 'keep'}" to try and persist the sorts/filters through my renders, but each time I hit a sort or add a filter, only the filter or sort I have just instantiated is in the filter model or sort model. Does this have anything to do with react re-rendering the grid?

**Comment by ceolter** [comment]
```Does this have anything to do with react re-rendering the grid```
=> no

from the description above, i can't say what's wrong. if you provide a plunker demonstrating the issue, then i could debug and see what's happening.

ps closing as want to keep github issues for tracking issues with ag-grid, not for general questions.

**Comment by arminconscia** [comment]
Actually it was. Stupid mistake, was to allow for resetting of column defs in the render function. So when they re-rendered based on the app state, when new data arrived, the widget state was lost.
