### ISSUE TITLE
[vue] Will support for vuejs!

### ISSUE THREAD

**Issue by ohohco** [ceolter/ag-grid#1371]

**Comment by ceolter** [comment]
lol, yes vuejs, it's on our radar!!! we are yet to plan what we will work on in Q1 2017, vuejs is a definite contender.

**Comment by seanlandsman** [comment]
@ohohco We're actively working on vuejs support at the moment - we're hoping to have something out in the next couple of weeks

**Comment by ceolter** [comment]
we are working on vue. as we are currently working on the support, i'm closing this, having it open doesn't change anything!
