### ISSUE TITLE
How to get custom values for each richSelect in ag-grid

### ISSUE THREAD

**Issue by YPBS** [ceolter/ag-grid#1372]
I have ag-grid reach based application where richSelect dropdowns are being used for certain columns. For some of richSelect columns, values in the dropdown should be based on an id.

My JSON data would look like this:

```
data : [{
        collegeId : "MIT",
        users : [{
                name : "Alex",
                country : "USA"
            }, {
                name : "Barbara",
                country : "Canada"
            }
        ]
    }, {
        collegeId : "Berkeley",
        users : [{
                name : "Samantha",
                country : "Australia"
            }, {
                name : "Amanda",
                country : "Germany"
            }
        ]
    }
]
```
Here is how my colDefs looks like:

```
{ headerName : "Users", field: "users", filter: "text", 
    cellEditor : "richSelect",
    cellEditorParams : {
        values : this.getValues()
    }
}
```
Issue is, in the row for MIT I want User list to have only Alex and Barbara. Similarly for Berkeley I need User's richSelect to only have Samantha and Amanda.

Here User list depends on collegeId. In getValues() I can fetch all the Users but don't know how to do so based on matching collegeId.

**Comment by ceolter** [comment]
the params for richSelect can also take a cellRenderer, so use this to render the value you want, something like this:
```
{ 
    headerName : "Users", field: "users", filter: "text", 
    cellEditor : "richSelect",
    cellEditorParams : {
        values : this.getValues(),
        cellRenderer: function(params) {
            return params.value.name;
        }
    }
}
```

**Comment by SatyabratKumarSingh** [comment]
hi, but how does it solve the problem?

**Comment by kvanlaan** [comment]
I also ran into this issue. I would like the select values to be different for each row, based on data in the row. Ideally there will be a general list that is filtered.

**Comment by yogeshpaul** [comment]
If you are okay with creating custom cell editor, then create a custom cell editor with a dropdown. Pass a boolean parameter, let's say _isVariableList_ to cell editor to tell it whether the list will vary for each row or will remain same.

1. If isVariableList is true, then pass a function, let's say _listCallBack_ as cellEditorParams and call it from within your cell editor's constructor. For function callback, you can pass cell editor's props to parent so that it can distinguish for which row/parameter it needs to do the filtering.
2. If isVariableList is false, then simply pass pass the list and use it.

**Comment by RoshanRoyal** [comment]
multiple select option for richselect

**Comment by kamilkabir9** [comment]
https://www.ag-grid.com/javascript-grid-cell-editing/#example-dynamic-parameters

**Comment by FIRSTNIGHTINTHEWOODS** [comment]
```
        cellEditorParams: {
            values: [{name: 'Name', key: '123'}],
            cellRenderer: function(params) {
             return params.value.name;
            }
        },
        cellRenderer: function(params) {
            return params.value.name;
        }

```
in value change handler u will get object as value
```
onCellValueChanged(params) {
    console.log(params.value); // {name: 'Name', key: '123'}
}
```

**Comment by cruni505** [comment]
> https://www.ag-grid.com/javascript-grid-cell-editing/#example-dynamic-parameters

this works fine, but what if we need to make a http request?

**Comment by robertou** [comment]
> this works fine, but what if we need to make a http request?

Same issue!

**Comment by jurruh** [comment]
> > https://www.ag-grid.com/javascript-grid-cell-editing/#example-dynamic-parameters
> 
> this works fine, but what if we need to make a http request?

+1

**Comment by The-MAZZTer** [comment]
I just found the cellEditorSelector property for a column which is probably a better way to do this as it allows you to define the cell editor to use with a callback function, including defining the params (which include the select values).

**Comment by steveschmitt** [comment]
> https://www.ag-grid.com/javascript-grid-cell-editing/#example-dynamic-parameters

New link is
https://www.ag-grid.com/javascript-data-grid/cell-editors/#example-rich-cell-editor--dynamic-parameters
