### ISSUE TITLE
Grid Header Templates have existing classes stripped out

### ISSUE THREAD

**Issue by pete-hotchkiss** [ceolter/ag-grid#1373]
I'm using a function to return a DOM element to my colDef.headerCellTemplate property. Pseudo code below

```
function foo() {
    let eCell = document.createElement("div");
    eCell.innerHTML =
    "<div style='text-align: left;'>" +
    "  <div id='agResizeBar' style='width: 4px; height: 100%; float: right; cursor: col-resize;'></div>" +
    "  <div style='padding: 4px; overflow: hidden; text-overflow: ellipsis;'>" +
    "    <div id='agHeaderCellLabel' class='custom__header__cell'>" +
    "      <div id='agText' class='custom__header__cell__label'></div>" +
    "      <div id='agSortAsc' class='has-icon icon--arrow-circle-up icon--white'></div>" +
    "      <div id='agSortDesc' class='has-icon icon--arrow-circle-down icon--white'></div>" +
    "      <div id='agNoSort'></div>" +
    "    </div>" +
    "  </div>" +
    "</div>";
  return eCell;
}
```

my problem is, when rendered to the browser the div item with the id of _agText_ has it's existing class ( in this case _custom\_\_header\_\_cell_ stripped away and replaced with _.ag-header-cell-text_. Whilst I'm OK with this class being added - surely this should be in addition to any class already assigned within the template?

noteably the _agSortAsc_ and _agSortDesc_ elements which also have class declarations applied to them, *dont* have existing props stripped out.

Is there a way for me to suppress this operating so aggressively - and have it apply both my template assigned class and the internal ag class?

**Comment by ceolter** [comment]
fixed. classes are not added, not replaced.
