### ISSUE TITLE
RTL not working 

### ISSUE THREAD

**Issue by EidMorsy** [ceolter/ag-grid#1374]
I set enableRtl=true in grid options but still the grid in "ltr" mode 
also when use inspect  i found that the grid still use the class "ag-ltr"

I'm using angular 1.x 

Edit : setting the enableRtl=true on the component initialization worked,
but now I can not change the layout dynamically when changing language from (rtl to ltr).

**Comment by ceolter** [comment]
you cannot turn TRL on/off after the grid is initialised.
