### ISSUE TITLE
Iam getting  unable to get property setDatasource...

### ISSUE THREAD

**Issue by rajgopalk** [ceolter/ag-grid#1376]
hi , 

iam getting this error, can you tell me how to solve this.
"Unable to get property 'setDatasource' of undefined or null reference at $scope.createNewDatasource ".
..................................................................................
 var columnDefs = [              
               {
               headerName: "col01", field: "col01", enableRowGroup: true, width: 140, cellStyle: { 'text-align': 'left' },
               },               
               {
                   headerName: "col02", field: "col02", width: 130, enableRowGroup: true, filter: 'number', cellStyle: { 'text-align': 'center' },
               },
               {
                   headerName: "col03", field: "col03", width: 130, enableRowGroup: true, filter: 'text', cellStyle: { 'text-align': 'left' },
               },
               {
                   headerName: "col04", field: "col04", width: 130, enableRowGroup: true, filter: 'text', cellStyle: { 'text-align': 'left' },
               },
                {
                    headerName: "col05", field: "col05", width: 180, enableRowGroup: true, filter: 'text', cellStyle: { 'text-align': 'left' },
                },
                {
                    headerName: "col06", field: "col06", width: 150, enableRowGroup: true, filter: 'text', cellStyle: { 'text-align': 'left' },
                },
                 {
                     headerName: "col07", field: "col07", width: 170, enableRowGroup: true, filter: 'text', cellStyle: { 'text-align': 'left' },
                 },
                   {
                       headerName: "col08", field: "col08", width: 100, enableRowGroup: true, filter: 'number', cellStyle: { 'text-align': 'center' },
                   },
                   {
                       headerName: "col09", field: "col09", width: 120, enableRowGroup: true, filter: 'number', cellStyle: { 'text-align': 'center' },
                   },
                    {
                        headerName: "col10", field: "col10", width: 270, enableRowGroup: true, filter: 'text', cellStyle: { 'text-align': 'left' },
                    },
                    {
                        headerName: "col11", field: "col11", width: 290, enableRowGroup: true, filter: 'text', cellStyle: { 'text-align': 'left' },
                    },
        ];

$scope.gridOptions = {
            columnDefs: columnDefs,
            debug: true,
            rowData: null,
            angularCompileRows: true,
            angularCompileHeaders: true,
            rowGroupPanelShow: 'always',
            enableFilter: true,
            enableSorting: true,
            rowSelection: 'multiple',
            enableColResize: true,
            rowModelType: 'pagination',
            paginationPageSize: 15,
            rowHeight: 27,
            groupUseEntireRow: true,
            suppressDragLeaveHidesColumns: true,
            suppressRowClickSelection: true,
            suppressMenuHide: true,
            groupColumnDef: {
                cellRenderer: 'group',
                headerName: 'Group Column'
            },
            overlayLoadingTemplate: '<span></span>',
            groupSelectsChildren: true,
            onSelectionChanged: function () {
                $scope.SelectedRowsCountDet($scope.gridOptions.api.getSelectedRows());
            },
            onModelUpdated: function () {   
                kendo.ui.progress($("#loading"), false);
            },
            onGridReady: function () {
                kendo.ui.progress($("#loading"), true);
            },
            defaultColDef: {
                columnGroupShow: true,
                enableValue: true
            }
        };

        $scope.createNewDatasource = function () {
            try {
                if (!$scope.allOfTheData) {
                    return;
                }
                var dataSource = {
                    getRows: function (params) {
                        setTimeout(function () {
                            $scope.rowsThisPage = $scope.allOfTheData.slice(params.startRow, params.endRow);
                            $scope.lastRow = -1;
                            if ($scope.allOfTheData.length <= params.endRow) {
                                $scope.lastRow = $scope.allOfTheData.length;
                            }
                            params.successCallback($scope.rowsThisPage, $scope.allOfTheData.length);
                        }, 500);
                    }
                };
                $scope.gridOptions.api.setDatasource(dataSource);

            }
            catch (ex) {
                $scope.errorDialogBox(ex.message, ex.stack);
            }
        }

        $scope.setRowData = function (rowData) {
            $scope.allOfTheData = rowData;
            $scope.createNewDatasource();
        }
..........................................................

iam passing data to grid, like
$scope.setRowData($scope.tmpList);
tmplist having data, i think no issues from data.

**Comment by ceolter** [comment]
if you provide a plunker, someone could troubleshoot. dont see anything wrong with the code.

ps closing issue, it's not an issue with ag-Grid, github is for tracking ag-Grid issues.
