### ISSUE TITLE
[column hover] have ag-column-hover similar to ag-row-hover

### ISSUE THREAD

**Issue by magmel48** [ceolter/ag-grid#1379]
Hi, is it possible to add some class to cells in one vertical column, which contains cell, hovered by user? We already have .ag-row-hover, what about .ag-col-hover or something else?

**Comment by jlarso11** [comment]
+1

**Comment by ceolter** [comment]
tracked by AG-168
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by ceolter** [comment]
fixed. will be in next release.

**Comment by gportela85** [comment]
@rosostolato Since v26 you need enable flags for this to work: https://www.ag-grid.com/javascript-data-grid/row-styles/#highlighting-rows-and-columns
