### ISSUE TITLE
Allow to suppress selection change

### ISSUE THREAD

**Issue by POberhofer** [ceolter/ag-grid#138]
I'd like to save data back to server when changing the selected row. If save fails, the selected row should't change. Could you add a selectionChanging callback that receives the currently selected rows and the rows to be selected as input and returns a bool or a promise.

**Comment by ceolter** [comment]
not going to implement, as this is changing the state machine nature of the grid. instead you should implement your own selection mechanism. first turn off click selection (suppressRowClickSelection=true) and the implement your own click handler for the row (rowClicked event), then use the grid selection api for the selection.
