### ISSUE TITLE
There should be an option to report number of rows w/o pagination enabled

### ISSUE THREAD

**Issue by rosensama** [ceolter/ag-grid#1385]
Thanks for the great package.  

When I don't use pagination, I'd still like the data below the grid for row count if the full size is known "Y total rows available".  And when a filter is applied it could say something like "X out of Y rows matched".  

This is somewhat related to #465 in the sense that the grid could provide more data to the user when the entire dataset is already memory resident and there's no pagination.  So it seems like sub-set of client side pagination to me.

**Comment by ceolter** [comment]
api.getModel.getRowCound()
