### ISSUE TITLE
Wrong changelog on ag-grid.com

### ISSUE THREAD

**Issue by Hafureluspatha** [ceolter/ag-grid#1387]
This outdated changelog (https://www.ag-grid.com/changeLog.php) appears in Google, while true changelog is here (https://www.ag-grid.com/change-log/changeLogIndex.php).
I regard this as an error. Is that an error?

**Comment by seanlandsman** [comment]
Thank you for reporting this - I've set a 301 against the old one

It time the old one shouldnt appear in searches anymore
