### ISSUE TITLE
[BUG] Website example weird behavior

### ISSUE THREAD

**Issue by AmitMY** [ceolter/ag-grid#1391]
In the front page of www.ag-grid.com, at the bottom, there is a file "explorer"
Right click on any cell, will open a menu, with no background, like so:
Looks odd, 
![image](https://cloud.githubusercontent.com/assets/5757359/21810794/e46819b6-d755-11e6-9055-a7a501d6aed5.png)

**Comment by ceolter** [comment]
fixed. will be in next release.
