### ISSUE TITLE
Is it possible to styles borders between group column ?

### ISSUE THREAD

**Issue by goums** [ceolter/ag-grid#1394]
From this example:
![image](https://cloud.githubusercontent.com/assets/5577626/21813973/2a4646f4-d758-11e6-8ad8-27b72a737707.png)
https://www.ag-grid.com/javascript-grid-grouping-headers/

I would like to style differently the border separating the two column groups, like that:
![image](https://cloud.githubusercontent.com/assets/5577626/21814306/2696bea2-d759-11e6-893c-e3a15f0a0dcb.png)

This would be really appreciated for tables with many columns and groups, has it would improve the global visualization of the data.
However, I did not find any css classes or options to match this requirement.
Did I miss something?

**Comment by ceolter** [comment]
no

**Comment by kapso** [comment]
Yea we would like to give the table an excel like look, by adding vertical columns lines. Is that not possible?

**Comment by anpaopao** [comment]
I was able to get something working by:

1. Return a boolean for first and last column in column group
```
const isFirstColumnInGroup = (parameters: CellClassParams): boolean => {
    const displayedColumns = parameters.api.getAllDisplayedColumns();
    const firstColumnInGroup = displayedColumns.find((col) => col.getParent() === parameters.column.getParent());
    return firstColumnInGroup?.getColId() === parameters.column.getColId();
};

const isLastColumnInGroup = (parameters: CellClassParams): boolean => {
    const displayedColumns = parameters.api.getAllDisplayedColumns();
    const columnsInGroup = displayedColumns.filter((col) => col.getParent() === parameters.column.getParent());
    const lastColumnInGroup = columnsInGroup[columnsInGroup.length - 1];
    return lastColumnInGroup?.getColId() === parameters.column.getColId();
};
```

2. add classes if first or last column in group
```
.left-border {
  border-left: 1px solid rgb(189, 195, 199); 
}
.right-border {
  border-right: 1px solid rgb(189, 195, 199); 
}
```

```
const columnDefs: (ColDef | ColGroupDef)[] = [
    { headerName: "Athlete Details", 
      children: [
        { headerName: "Athlete", cellClassRules: { "left-border": isFirstColumnInGroup, "right-border": isLastColumnInGroup }, },
        { headerName: "Age", cellClassRules: { "left-border": isFirstColumnInGroup, "right-border": isLastColumnInGroup }, },
        { headerName: "Country", cellClassRules: { "left-border": isFirstColumnInGroup, "right-border": isLastColumnInGroup }, },
      ],
    }
```

3. Optional if using movable columns refresh - refresh grid when a column is moved to reapply classes to correct columns
```
onColumnMoved = {( event: ColumnMovedEvent ) => {
  event.api.refreshCells();
}}
```

**Comment by jtbiron** [comment]
+1 on this. It's a much better user experience when the user can see that the columns are clearly grouped.
