### ISSUE TITLE
Cell Navigation on Floating Rows

### ISSUE THREAD

**Issue by randdusing** [ceolter/ag-grid#1395]
Documentation says: Selection and cell navigation are turned off for floating rows. This was done by choice. Maybe in the future, if the requirement is there, this will be provided as an option. However the most common use case for floating rows is for header / footer information, which normally do not partake in the row selection process.

But I'm able to tab into floating rows. Should I be able to? I'd prefer to disable it!

**Comment by ceolter** [comment]
you can disable using callbacks navigateToNextCell and tabToNextCell

**Comment by ceolter** [comment]
i've taken this paragraph out of the docs. next time we refresh website it will be gone.
