### ISSUE TITLE
[focus] focus pinned cell prints 'ensureIndexVisible....' warning

### ISSUE THREAD

**Issue by randdusing** [ceolter/ag-grid#1396]
If I focus a cell that's in a pinned column, GridPanel.ensureColumnVisible logsa warning about not making sense on pinned columns. Anyway to disable this? I'm wondering if RowRenderer.findNextCellToFocusOn should check the column for its pinned state.

![image](https://cloud.githubusercontent.com/assets/6188656/21823752/16d1d2f2-d742-11e6-8234-e58ad977caf8.png)

**Comment by ceolter** [comment]
tracked by AG-172
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by ceolter** [comment]
done. will be in next release.
