### ISSUE TITLE
[BUG]Conditional checkboxSelection not working properly

### ISSUE THREAD

**Issue by naveenballa** [ceolter/ag-grid#1398]
In ag-grid-ng2 example RichGridComponent [(rich-grid.component.ts)](https://github.com/ceolter/ag-grid-ng2-example/blob/master/angular-cli/src/app/rich-grid.component.ts)
I modified the column definition as below for the first column.
`{
      headerName: '#', width: 30, /*checkboxSelection: true,*/ suppressSorting: true,
      suppressMenu: true, pinned: true,
      cellRenderer: (params) => {
          params.colDef.checkboxSelection = (params.data.proficiency < 50);
          return "";
      }
},`
I am trying to show the checkbox only when proficiency > 50.

I observe that the checkbox for first row is not displayed where proficiency > 50, the checkbox will be displayed only after I scroll down and then scroll to top.

**Comment by ceolter** [comment]
for help using ag-Grid please use stackoverflow or members forum (for customers). if this is a bug with ag-Grid, need to have example provided (on fiddle or similar) demonstrating the bug.
