### ISSUE TITLE
Column width set to a string value causes render issues

### ISSUE THREAD

**Issue by daric81** [ceolter/ag-grid#140]
Hi,

Great Work! Love the grid.
I just hit this and it took a little while to figure out the cause. I'm in the process of trialling angular grid , moving from ng-grid v 2.x and ng-grid handle string values for column widths.  It might be worth throwing an error or converting to a number behind the scenes as the grid is unusable with string values.

**Comment by ceolter** [comment]
understood. thanks for raising.

**Comment by ceolter** [comment]
should not use a string as then people would think %width is acceptable.

the grid now prints a warning if a string is used.
