### ISSUE TITLE
angularCompileHeaders not working with Angular 2

### ISSUE THREAD

**Issue by wOOx92** [ceolter/ag-grid#1400]
The _angularCompileHeaders_ option in _gridOptions_ is only working with Angular 1.x.

Currently, there is no possibility to use Angular 2 Components as _headerCellRenderer_ / _headerCellTemplate_ or even any Anuglar 2 click functionality.

Please make angularCompileHeaders work with Angular 2.

Relating threads:
https://ag-grid.com/forum/showthread.php?tid=4132
https://ag-grid.com/forum/showthread.php?tid=4130

**Comment by seanlandsman** [comment]
As per the forum - compile headers is only applicable for ng1. For ng2 we'll shortly be providing the ability to use components in the header.

For ng2 issues/requests please raise them in the ag-grid-ng2 repo
