### ISSUE TITLE
[pagination] change sort column at Nth page without jumping to first page

### ISSUE THREAD

**Issue by john-hu** [ceolter/ag-grid#1402]
## Use Case ##
As a user, we would like to keep at Nth page while we use server-side sorting and change the sort column. 

---
The line of code:
https://github.com/ceolter/ag-grid/blob/5deba16090655b2ef4f966753cbc7c5799ea4334/src/ts/rowControllers/paginationController.ts#L92

**Comment by ceolter** [comment]
tracked by AG-173
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by ceolter** [comment]
this is no longer the case with client side pagination, which is the preferred pagination going forward.
