### ISSUE TITLE
isAnyFilterPresent not returning expected result

### ISSUE THREAD

**Issue by don-bluelinegrid** [ceolter/ag-grid#1406]
@ceolter 

Niall,

I am running the latest 7.1.X version of ag-grid, and am finding unexpected behavior with the api.isAnyFilterPresent() method.

Right now I am looking at a grid that has a filter applied - 1 row out of a possible 3 are being displayed due to filtering - but in the debugger my call to `api.isAnyFilterPresent()` is always returning false.  

Is this related to: https://github.com/ceolter/ag-grid/issues/1320?  Or, do you have any ideas on what could cause this?  In this particular grid, I am using the inMemoryRowModel, and when I examine the FilterManager object it shows no active filters of any type.

Please advise, as we are releasing a product in one day and have just encountered this as a defect.

Cheers,
Don

**Comment by ceolter** [comment]
yes it could be related. please try with latest release.

**Comment by don-bluelinegrid** [comment]
@ceolter 

Niall,

I've tried with latest release 7.2.2, and I don't see any difference in behavior.  I have a Grid instantiated inside an Aurelia dialog.  When I filter the grid, and catch the onAfterFilterChanged event, it shows very unusual behavior (same in 7.1.X); the original reference to the `gridOptions.api.filterManager` shows no filters applied, but the `this` gridOptions object inside the event handler does show a filter applied.

You can see this in the attached screen shots: one shows the actual grid in the filtered state with the original reference showing no filters; the other shows the `this' object in the event handler that does show filters applied.

Do you have any further thoughts on this?

Thanks,
Don
![screen shot 2017-01-24 at 4 34 18 pm](https://cloud.githubusercontent.com/assets/19780097/22267846/4769a1c6-e253-11e6-8dd6-9c2653cfde9d.png)
![screen shot 2017-01-24 at 4 28 59 pm](https://cloud.githubusercontent.com/assets/19780097/22267847/47699988-e253-11e6-81a2-382b523ad97c.png)
