### ISSUE TITLE
Locked First Column Can be moved via other columns

### ISSUE THREAD

**Issue by jlarso11** [ceolter/ag-grid#1408]
I have a grid where I would like the first column to always be first.  So I added the 'suppressMovable: true' to my colDefs.  So now I can't move it - Great.  But I can still move another column to be in front of it by dragging.  So even tho I can't move the column.  It does not ensure that column 1 is always column 1.

**Comment by ocrlopez** [comment]
+1 

Would like to see this implemented as well.

**Comment by ceolter** [comment]
having fixed columns is already tracked in another issue.

**Comment by ceolter** [comment]
https://github.com/ceolter/ag-grid/issues/853
