### ISSUE TITLE
master-details - missing documentation

### ISSUE THREAD

**Issue by TheILPlace** [ceolter/ag-grid#1415]
hi,
i've tried to use the master-detail functionality, described at
https://www.ag-grid.com/javascript-grid-master-detail/

i've done all is needed, to configuree the grid but didnt get the small "+" sign at the left, in order to expand the rows.

after much digging, i found that in order to achieve this, you need to create a cellrenderer on the first column like this:

cellRenderer: 'group'

this is taken from the examples. 

i think it should be in the documentation that explains the master-details feature. it could have saved me a lot of time..

**Comment by ceolter** [comment]
docs updated
