### ISSUE TITLE
row hover - doesnt exist in all themes

### ISSUE THREAD

**Issue by TheILPlace** [ceolter/ag-grid#1416]
hi,
the css class **ag-row-hover** is included in the material theme, but not in the other themes. could that be included to ? (i know i can add it myself, but think that consistency is important)

**Comment by ceolter** [comment]
just add the css in yourself. not everyone wants hover.

eg:

```
.ag-row-hover {
  background: red;
}
```

**Comment by Jmenache** [comment]
Hi,
Thank you for your answer. I still didn’t manage to make it work yet.
Could you develop a bit more? Is there a specific place where I should add this class?
I would guess the way to do it changed with the new themes.
