### ISSUE TITLE
Ag Grid : Change filter template in Angular 2

### ISSUE THREAD

**Issue by ALFRED-Guillaume** [ceolter/ag-grid#1417]
I'm trying to add a close button to filter template of Ag Grid using Angular 2.

I haven't find a template option for filter. Do I have to create a custom filter that is very close to the built-in filters (except for the template part) ?

Thanks in advance.

**Comment by seanlandsman** [comment]
Hi

If the provided filter doesn't suit your purposes then yes you'll need to create your own filter component - you can find details on how to do this here: https://www.ag-grid.com/javascript-grid-filtering/

**Comment by ALFRED-Guillaume** [comment]
Hi,

Thank you very much !
