### ISSUE TITLE
Breaking changes in 7.2?

### ISSUE THREAD

**Issue by don-bluelinegrid** [ceolter/ag-grid#1418]
@ceolter 

I just npm updated to version 7.2, and I'm seeing some errors like this:

`
Type '{ columnDefs: any[]; rowSelection: string; rowHeight: number; headerHeight: number; suppressMenuH...' is not assignable to type 'GridOptions'.
  Property 'dateComponent' is missing in type '{ columnDefs: any[]; rowSelection: string; rowHeight: number; headerHeight: number; suppressMenuH...'.
`

This code compiled and ran without problem using v7.1.

Are there release notes/changelog available for v7.2?  I don't see the changelog updated on the main AgGrid web site.

Thanks,
Don

**Comment by sousarka** [comment]
@seanlandsman @ceolter 
this is happening in 7.2.1 as well

**Comment by seanlandsman** [comment]
@don-bluelinegrid @sousarka we'll take a look at this today

**Comment by ceolter** [comment]
ahhhhh! dateComponent should be optional.

as a quick fix, set it to null.

will make it optional.

thanks for raising.
