### ISSUE TITLE
unnecessary console.log in latest update

### ISSUE THREAD

**Issue by R11** [ceolter/ag-grid#1419]
I just updated to the latest ag-grid (7.2.0) and now I am getting console.log messages on all of my pages. It says "visible = false" and it appears to be coming from a rowContainerComponent.js file. Line 59.

**Comment by seanlandsman** [comment]
We've just release 7.2.1 to fix this - thanks for reporting

**Comment by GustavSt** [comment]
I get this in enterprise still.

**Comment by seanlandsman** [comment]
@GustavSt 7.2.2 has been released now too - that should fix this for you
