### ISSUE TITLE
Typo in changelog for 7.2.x?

### ISSUE THREAD

**Issue by GustavSt** [ceolter/ag-grid#1420]
In the change log it states there is a new property called `fullWidthRows` and then it links to [here](https://www.ag-grid.com/javascript-grid-grouping/#fullWidthRows)

However there the docs explain the property `embededFullWitdhRows`. Is this the real property and the changelog is wrong?

**Comment by ceolter** [comment]
docs update, will be on website next time we refresh the website. thanks.
