### ISSUE TITLE
I'm using version 5.0.0,the mobile column without animation effects, how should solve?

### ISSUE THREAD

**Issue by crazyaguai** [ceolter/ag-grid#1421]
Whether the version problem?

**Comment by seanlandsman** [comment]
Animation was only added 7.x - if you want this feature you'll need to upgrade I'm afraid

thanks

**Comment by crazyaguai** [comment]
When I drag and drop the head cross tip also not have, is a version of the reason?As follow the mouse as example.

**Comment by seanlandsman** [comment]
I would say so yes - 5.x is relatively old now, a great deal has been added since then
