### ISSUE TITLE
[editing] editing cells / rows become non-editing when scrolled outside of viewport

### ISSUE THREAD

**Issue by majoshi1** [ceolter/ag-grid#1424]
The row becomes non-editable on scrolling, with few hundreds of rows.
Steps:
-Update the following sample to have say 500 rows.
https://www.ag-grid.com/javascript-grid-cell-editing/exampleFullRowEditing.html
-Hit Edit row button.
-Scroll down such that the editing row is no longer visible.
-Scroll back up.
-The row is no longer in edit mode.
-This does not happen for smaller data set.

**Comment by majoshi1** [comment]
Workaround is to set row buffer to number of rows.
gridOptions.rowBuffer: <row count or 9999999>
e.g.
gridOptions.rowBuffer: 10000

Ref: http://stackoverflow.com/questions/36138943/is-there-a-way-to-disable-angular-grid-virtualization-i-e-angular-creating-div

**Comment by majoshi1** [comment]
The row buffer slows the grid for larger values. 
So, need to be used with pagination.
e.g.
            	    rowModelType: 'pagination',
            	    rowBuffer: 50,
            	    paginationPageSize: 50,

Ideally, the original issue should be fixed.

**Comment by ceolter** [comment]
this is not just rows, it's just simple cell editing also. if you scroll the editing item (row or cell) outside of the rendered cells, the cells are remove. when they get rendered back again (you scroll back) they are in read only.

fix would be for row virtualisation to NOT remove the rows if there are been edited.

**Comment by majoshi1** [comment]
Thanks so much for the reply.
Till the issue is fixed, found another (better) workaround.
Idea is to keep the edited row on top using floating header.
No need of pagination, so better performance.

var row = ... ; // Row data for new or existing row.
// Set the row as a floating row.
gridOptions.api.setFloatingTopRowData([newRow]);

To programmatically start editing the row.
            gridOptions.api.setFocusedCell(0, colKey, true, true);
            var gridCell = gridOptions.api.getFocusedCell();
            gridCell.floating = "top"; // Without this, it edits first non-header row.
            gridOptions.api.rowRenderer.startEditingCell(gridCell, null, null);

Ref: https://github.com/ceolter/ag-grid/issues/1326

**Comment by ceolter** [comment]
tracked by AG-175
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by ceolter** [comment]
fixed. will be in next release.

**Comment by sskmail14** [comment]
Thanks @ceolter  when can we expect the next release?
