### ISSUE TITLE
clicking on checkbox doesnt start editing of a cell in a different column

### ISSUE THREAD

**Issue by gerlstar** [ceolter/ag-grid#1425]
I have a checkbox in the first column of my grid and I'm using cellRenderer in in the last column. When I click on the checkbox, I'd like the last cell to be focused so that users can enter in a value. Right now this isnt working. This is the renderer:

```
function nameRenderer  (params) {
            var hasAttr;
            var sp = document.createElement('span');
            var t = document.createTextNode(' ' + params.value);     // Create a text node
            var chkBox = document.createElement('input');
            chkBox.setAttribute('type', 'checkbox');
            chkBox.setAttribute('value', params.data.name);        
            chkBox.addEventListener('click', function(e){

                hasAttr = chkBox.getAttribute('checked');
                // console.log(hasAttr);
                if (hasAttr === null || hasAttr === ''){
                    chkBox.setAttribute('checked', true);
                    vm.gridOptions.api.setFocusedCell(params.rowIndex, 'allocation');
                    vm.gridOptions.api.startEditingCell({
                        rowIndex: params.rowIndex,
                       colKey: 'allocation'
                    });


                }else{
                    chkBox.removeAttribute('checked');
                    vm.gridOptions.api.stopEditing();
                }

            });
            sp.appendChild(chkBox);
            sp.appendChild(t);
                     return sp;

        }
```

![focus](https://cloud.githubusercontent.com/assets/3219706/22077536/89efbce0-dd82-11e6-916c-c1957b088a7c.png)

**Comment by ceolter** [comment]
you should use the api to start editing a cell.

```api.startEditingCell(params)```

**Comment by haifahrul** [comment]
You can use boolean (true or false)

I try this and it's work :

    var columnDefs = [
      {
        headerName: 'Refunded', 
        field: 'refunded',
        editable: true,
        cellEditor: 'booleanEditor',
        cellRenderer: booleanCellRenderer
      },
    ];


**Function checkbox editor**

    function getBooleanEditor() {
        // function to act as a class
        function BooleanEditor() {}
        
        // gets called once before the renderer is used
        BooleanEditor.prototype.init = function(params) {
            // create the cell
            var value = params.value;

            this.eInput = document.createElement('input');
            this.eInput.type = 'checkbox'; 
            this.eInput.checked = value;
            this.eInput.value = value;
        };

        // gets called once when grid ready to insert the element
        BooleanEditor.prototype.getGui = function() {
            return this.eInput;
        };

        // focus and select can be done after the gui is attached
        BooleanEditor.prototype.afterGuiAttached = function() {
            this.eInput.focus();
            this.eInput.select();
        };

        // returns the new value after editing
        BooleanEditor.prototype.getValue = function() {
            return this.eInput.checked;
        };

        // any cleanup we need to be done here
        BooleanEditor.prototype.destroy = function() {
            // but this example is simple, no cleanup, we could
            // even leave this method out as it's optional
        };

        // if true, then this editor will appear in a popup
        BooleanEditor.prototype.isPopup = function() {
            // and we could leave this method out also, false is the default
            return false;
        };
        
        return BooleanEditor;
    }

**And then booleanCellRenderer function**

    function booleanCellRenderer(params) {
        var value = params.value ? 'checked' : 'unchecked';
        
        return '<input disabled type="checkbox" '+ value +'/>';
    }


**Let the grid know which columns and what data to use**

    var gridOptions = {
        columnDefs: columnDefs,
        pagination: true,
        defaultColDef: {
            filter: true,
            resizable: true,
        },
        onGridReady: function(params) {
            params.api.sizeColumnsToFit();
        },
        onCellValueChanged: function(event) {
            if (event.newValue != event.oldValue) { 
                // do stuff
                // such hit your API update
                event.data.refunded = event.newValue; // Update value of field refunded
            }
        },
        components:{
            booleanCellRenderer: booleanCellRenderer,
            booleanEditor: getBooleanEditor()
        }
    };

**Setup the grid after the page has finished loading**    

    document.addEventListener('DOMContentLoaded', function() {
        var gridDiv = document.querySelector('#myGrid');
        // create the grid passing in the div to use together with the columns & data we want to use
        new agGrid.Grid(gridDiv, gridOptions);
        
        fetch('$urlGetData').then(function(response) {
            return response.json();
        }).then(function(data) {
            gridOptions.api.setRowData(data);
        })
    });
