### ISSUE TITLE
about the license

### ISSUE THREAD

**Issue by yuntaoguo** [ceolter/ag-grid#1429]
HI,

I want to know if i cannot use the ag-grid without an enterprise license key.
Thanks.

**Comment by yuntaoguo** [comment]
There is a declare of the license and price. But how to download the version for free?

**Comment by AmitMY** [comment]
Ag-grid is free and is licensed under the MIT license. You can use it by cloning, downloading, or preferably `npm install ag-grid`

If you mean is it possible to use the ag-grid-enterprise without a license, the answer would be yes, you can use it without a license for 2 months, only if you press the big green button on the website [here](https://www.ag-grid.com/documentation-main/documentation.php) saying "try ag-grid enterprise for free"

This should send an email to the ag-grid team asking for a 2 months free trial.

To download ag-grid-enterprise you would do the exact same as above, but the name of the repository is ag-grid-enterprise and not ag-grid. (you would need both)

**Comment by ceolter** [comment]
@AmitMY thanks amit.

Amit - any chance you want to move to London and work for us?

**Comment by AmitMY** [comment]
@ceolter I'd love to. However, I have to enlist to mandatory army service this year for 3-5 years. (I am 18), so... do you have any remote openings? :)

**Comment by ceolter** [comment]
3 to 5 years? wow, that's heavy. i'll be retired by then. ideally we want to grow the team here, i'm a believer in having people working sitting beside each other. email accounts@ag-grid.com, give me your email.

**Comment by AmitMY** [comment]
Retired? You don't look that old. I would agree on that. Working on location is much more effective than remote. Better communication
