### ISSUE TITLE
[Bug] website "Try ag-grid enterprise" button is not working

### ISSUE THREAD

**Issue by AmitMY** [ceolter/ag-grid#1430]
For users (like me) who does not use a desktop client for mailing (like outlook), the big green button does nothing.
I was baffled for a few seconds, and then when looking at the page source noticed that it does:

> mailto:accounts@ag-grid.com?body=%0ADear%20ag-Grid%20Team%2C%0A%0AI%20am%20interested%20in%20taking%20a%20trial%20of%20ag-Grid%20Enterprise.%0A%0AMy%20name%20is%3A%20%3CEnter%20Name%3E%0AMy%20company%20name%20is%3A%20%3CEnter%20Company%20Name%3E%0A%0APlease%20email%20me%20back%20with%20a%20license%20key%20that%20I%20can%20use%20for%20my%20trial.%0A%0AThank%20you.%0A%0APS%20You%20guys%20at%20ag-Grid%20are%20awesome!!&Subject=ag-Grid%20Free 2 Month Trial

I have no clue how you could change it, I just think you should, because most users when searching for a grid will give up after something breaks because they are not yet attached.

**Comment by ceolter** [comment]
crap. for me, it opens my gmail.

**Comment by ceolter** [comment]
noted. i've passed onto the team.

**Comment by AmitMY** [comment]
Thanks! I was not aware this is possible you just saved me around 20 seconds a day trying to convert mailto links to addresses.
Here is a way to do it client side:
https://developers.google.com/web/updates/2012/02/Getting-Gmail-to-handle-all-mailto-links-with-registerProtocolHandler

**Comment by ceolter** [comment]
this is now a from.
