### ISSUE TITLE
Cell selection doesn't work properly in Material theme

### ISSUE THREAD

**Issue by pdavin** [ceolter/ag-grid#1433]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Load ag-grid with ag-material theme. 
Repro here: https://www.ag-grid.com/javascript-grid-themes/material-theme.php
Left click and drag across text to select it
Result: No visible change to indicate the highlighted selection - I wouldn't know what is selected or that I can copy it. 

**Expected behavior**
Expected behavior to be more like this: https://www.ag-grid.com/example.php
(intended behavior is described by ceolter here: https://github.com/ceolter/ag-grid/issues/87 )

**Minimal reproduction of the problem with instructions**
Repro here: https://www.ag-grid.com/javascript-grid-themes/material-theme.php
Left click and drag across text to select it
Result: No visible change to indicate the highlighted selection - I wouldn't know what is selected or that I can copy it. 

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
N/A

* **ag-Grid version:** X.X.X
7.1.x.

* **Browser:**
Chrome 55.0.2883.87

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by ceolter** [comment]
you need to have rangeSelection=true set to enable range selection.

see the demo here, choose material theme, and it is working.
https://www.ag-grid.com/example.php

**Comment by pdavin** [comment]
Oh ok, I didn't realize rangeSelection was a requirement for copy/paste to work. Thanks. 
It looks like I also have to have suppressCellSelection off (false), otherwise it doesn't work. I would consider that a bug, but already mentioned it under https://github.com/ceolter/ag-grid/issues/87 and it's not Material specific, so it's probably better covered there.
