### ISSUE TITLE
IAfterFilterGuiAttachedParams not found after 7.1.0, it change to IAfterGuiAttachedParams without notification .

### ISSUE THREAD

**Issue by denghuiquan** [ceolter/ag-grid#1434]
`IAfterFilterGuiAttachedParams` not found after 7.1.0, it change to `IAfterGuiAttachedParams` without notification .

**Comment by seanlandsman** [comment]
Hi 

Sorry for the inconvenience here - this change is documented as a breaking change on the changelog (https://www.ag-grid.com/change-log/changeLogIndex.php) but I appreciate that this is still annoying

Next time we'll ensure that breaking changes are kept for major releases
