### ISSUE TITLE
Be able to recieve keyboard event on navigateToNextCell

### ISSUE THREAD

**Issue by edogr1** [ceolter/ag-grid#1437]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The NavigateToNextCellParams includes only the key code that was pressed.

**Expected behavior**
Recieve the keyboard event so I could check if ctrl, shift or alt was pressed.

**What is the motivation / use case for changing the behavior?**
I used navigateToNextCell to select the row when pressing the up/down arrows keys (finding the node using nextCellDef.rowIndex and selecting it).
I wanted to implement that when pressing shift with the up/down arrows keys it'll multi select the lines, but I can't check if shift was pressed since I don't have the keyboard event but only the key code.

**Comment by seanlandsman** [comment]
Thanks for the feedback - item added to our backlog (https://www.ag-grid.com/ag-grid-pipeline/) as AG-190

**Comment by ceolter** [comment]
done. will be in next release.
