### ISSUE TITLE
Column group header animation is inconsistent

### ISSUE THREAD

**Issue by AmitMY** [ceolter/ag-grid#1439]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently, if having a table with a header of grouped columns, and one tries to hide/show a column, the columns slide to the new position, while the group header snaps to the new position.
Also, the right most column (for me, June) header slides, while the content just appears, no ease

**Expected behavior**
Group headers should too slide into position (animation: size of header group change)

**Minimal reproduction of the problem with instructions**
- Go to: https://www.ag-grid.com/example.php
- In the tool panel, hide the "name" column (preferably, several times, just to see the animation / snapping)

**What is the motivation / use case for changing the behavior?**
- Aesthetic. 
- It looks weird and it takes a second to figure out what happened

**Please tell us about your environment:**
Using the ag-grid website example

* **ag-Grid version:** 7.2.2 assumed

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by seanlandsman** [comment]
Thanks for the feedback - item added to our backlog (https://www.ag-grid.com/ag-grid-pipeline/) as AG-191

**Comment by ceolter** [comment]
fixed, header groups now slide. will be in next release.
