### ISSUE TITLE
inserting row after expanding groups not possible, index exceeded

### ISSUE THREAD

**Issue by jestersimpps** [ceolter/ag-grid#1441]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

when inserting a row after group expanded, the maxrow index variable is not updated, hence causing a warning rowindex > maxrow index.
**Expected behavior**

the maxrow index gets updated after every row manipulation. the row gets inserted at rowindex.
**Minimal reproduction of the problem with instructions**

copy a nested row to application memory
expand group rows
try insert row from memory in last group row
an error will be given, similar to: ag-Grid: invalid index 27, max index is 15

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

    "ag-grid": "^7",
    "ag-grid-enterprise": "^7",
    "ag-grid-ng2": "^7",

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ts
![screenshot 2017-01-25 10 44 34](https://cloud.githubusercontent.com/assets/6909198/22285583/8c3067c4-e2ec-11e6-97f3-ec6e27f999a8.png)

**Comment by seanlandsman** [comment]
Thanks for the feedback - item added to our backlog (https://www.ag-grid.com/ag-grid-pipeline/) as AG-193

**Comment by ceolter** [comment]
we are about to release today v10.1 which has a new mechanism for updating data. please try this when release, it should fix the issue.
