### ISSUE TITLE
Refresh Cells for Child rowNode

### ISSUE THREAD

**Issue by mail2gopinath** [ceolter/ag-grid#1442]
Hi 
  I am using the angular 1.x version of ag-grid with the master detail relationship and would like to refresh the cells of only detail row using the refreshCells(rowNodes, colIds). This works well with the parent nodes but how to retrieve only the Child rowNodes to be refreshed and as the fullWidthRow is considering the whole child grid as just one Row Node.

**Comment by seanlandsman** [comment]
As per the issue template, please raise support questions either via the ag-grid forum, or stackoverflow/gitter
