### ISSUE TITLE
rowDataChanged is not firing

### ISSUE THREAD

**Issue by squarewave24** [ceolter/ag-grid#1443]
according to [documentation](https://www.ag-grid.com/javascript-grid-events/#gsc.tab=0): _rowDataChanged	The client has set new data into the grid_

below are my common grid settings i use for all the grids in my app. the other events fire, but i can't get rowDataChanged to do anything. All the grids work and show rows of data. 

version:

>  "ag-grid": "6.4.x",
>  "ag-grid-enterprise": "6.4.x",
>  "ag-grid-ng2": "6.4.x", 

options definition: 

```

  getCommonOptions(rowdata, columndefs, type: EntityType): any {
        return {
            rowData: rowdata,
            columnDefs: columndefs,
            getRows: (params: any) => {
                console.log('getRows ', params);
            },
            rowHeight: null,
            enableSorting: false,
            enableColResize: true,
            groupHeaders: false,
            isExternalFilterPresent: () => true,
            onCellValueChanged: (e) => this.generalvalueChangedHandler(e, type),
            rowDataChanged: (rows)  => console.debug('rowDataChanged ', rows), // <-- not firing 
            onGridReady: e => {
                this.setApi(type, e.api, e.columnApi);
                console.log('the grid is now ready', e)
            },
            onModelUpdated: e => {
                // this.autoSizeAll(EntityType.Class);
                console.log('model updated ', e)
            },
```

grid tag: 

```
<ag-grid-ng2 [hidden]="Classes.length < 1" #agGrid style="width: 100%;" [style.height]="GridHeight()" class="ag-etp"

    [gridOptions]="gridOptions"
    [columnDefs]="columnDefs"
    [showToolPanel]="showToolPanel" 
    [rowData]="Classes"

    enableColResize
    enableSorting
    enableFilter

    rowHeight="20"
    rowSelection="multiple"
    >
</ag-grid-ng2>
```

**Comment by squarewave24** [comment]
oops sorry i figured it out. 

in this case I should use _**onRowDataChanged**_ i confuse those sometime :) 

looks like it is passing in an empty object, should it be passing rows?

**Comment by seanlandsman** [comment]
hi - no, its always an empty object. I'll discuss with the team and see if we can simply remove this parameter from being passed in the first place.

Closing this issue as you seem to have resolved your initial problem 

thanks
