### ISSUE TITLE
[row selection]: triggering selection change when selecting a column of the same line

### ISSUE THREAD

**Issue by jlame** [ceolter/ag-grid#1444]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
After upgrading our ag-grid version we saw that when clicking on a different column of the same row, the selectionChange callback was not called anymore. 
I guess this comes from some modifications on rowNode.ts : selectThisNode =>
         if (this.selected === newValue) { return false; }
For the moment we've commented the line above in a fork.

**Expected behavior**
We expect the callback to be triggered when clicking on a different column of the same row. it would be great to have something to enable this behaviour.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** 7.0.2

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
Hi

I think the docs need to be updated here - this event is specifically for row selection, not any selection. I'll update the docs to be clearer, but as a solution you could use the cellClicked event to trigger what you're after

**Comment by jlame** [comment]
Hi @seanlandsman, thank you for the quick reply.
Actually, what we're looking for is an event which will gives us the selected line and col.
As for today we're managing this selection change using gridOptions.onSelectionChanged, so what you mean is that this onSelectionChange event should only be triggered by a row change ?

If that's the case, i guess we'll have to stick with the onCellClicked as you mentionned.

**Comment by seanlandsman** [comment]
@jlame - yes, onSelectionChange should really be call on**Row**SelectionChange

The onCellClicked event should contain both the row & column information you're after here
