### ISSUE TITLE
API stopEditing 

### ISSUE THREAD

**Issue by razvanip** [ceolter/ag-grid#1445]
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

Hello,
It would be nice if ```stopEditing``` method of the api, would support a second param

```
stopEditing(cancel=false, cancelAfterEnd = false)
```

so that  u can cancel and prevent data added to the cell in some situations directly from the api.

As an use case:
Let's say u have an external validator for all inputs but you want to keep the text default ```cellEditor``` without having to create multiple cellEditors of type input that would implement multiple custom ```isCancelAfterEnd``` methods

What do u think ?

**Comment by ceolter** [comment]
what is the difference between cancel=false and cancelAfterEnd=false, to me it sounds like the second one is redundant

**Comment by razvanip** [comment]
Hey,
Thank your for the fast response

What i mean when u call ```stopEditing``` on a cell in the end to call the ```isCancelAfterEnd``` witch is a method on a ```cellEditor``` function, this requires me to have this method implemented on the cellEditor and pass information from outside of the grid to prevent data being edited.

It gets harder to do if u need to implement ```isCancelAfterEnd``` on multiple cellEditors.

If we could have a second param added to the ```stopEditing``` method on the api and modify this
```var userWantsToCancel = cancelAfterEnd  || this.cellEditor.isCancelAfterEnd && this.cellEditor.isCancelAfterEnd();``` where cancelAfterEnd would be the second param to the ```stopEditing``` function i could stop a cell editing and also prevent the changes to propagate in the cell field directly from the grid's api.

https://github.com/ceolter/ag-grid/blob/master/src/ts/rendering/renderedCell.ts#L712

**Comment by seanlandsman** [comment]
The current `cancel` parameter does this - if you set it to true it will cancel the editing (ie won't accept changes).

**Comment by razvanip** [comment]
Yup that is what i am after! When i called the method it canceled the editing mode but the cell accepted the modifications i did on the input!

Might have been my fault!

**Comment by seanlandsman** [comment]
Great, glad it worked out - closing this as it looks like this has been resolved

thanks
