### ISSUE TITLE
Why grid applies default sorting based on ASCII characters

### ISSUE THREAD

**Issue by vsanat** [ceolter/ag-grid#1446]
hi, 

Please clarify my doubt.. why the grid is doing default sorting based on ASCII characters, and how can I disable this feature. The data-source has sorted data base on A-Z sorting, but after binding it to the grid the final result looks something like this 

AA
Ab
aa
bb

means capital first then small letters.

**Comment by seanlandsman** [comment]
Going forward please dont post support questions here. Pay attention to the issue template you're prompted with before posting.

Take a look at https://www.ag-grid.com/javascript-grid-sorting - you can supply your own comparator
