### ISSUE TITLE
MarryChildren not working when a column is hidden

### ISSUE THREAD

**Issue by ha-decodeit** [ceolter/ag-grid#1447]
**I'm submitting a bug report**

**Current behavior**
When adding hide: true to a column, the marryChildren property of column groups seems to be ignored. 

**Expected behavior**
Hiding columns should not interfere with column group properties.

**Minimal reproduction of the problem with instructions**
Please see the jsfiddle example here:
https://jsfiddle.net/9c9L29bq/4/
Altough both column groups have _marryChildren_ set to true, items of the "Results" group can be dragged out and moved out of the group.
When the _hide: true_ property is removed from the age column, items of the "Results" group cannot be dragged out.

* **ag-Grid version:** X.X.X
7.2

* **Browser:**
Chrome 56

* **Language:**
Typescript 2.1.4

**Comment by seanlandsman** [comment]
thanks for reporting this - I've raised an issue our side (AG-207) for this

You can track its progress on our pipeline page (https://www.ag-grid.com/ag-grid-pipeline/) but we'll update this issue when its been resolved too

**Comment by ceolter** [comment]
fixed. will be in next release.

**Comment by makinggoodsoftware** [comment]
Hi,

Just to let you know that as of 11.0.0 this has been implemented, see the changelog for more details..

https://www.ag-grid.com/change-log/changeLogIndex.php#gsc.tab=0
