### ISSUE TITLE
Update filter values

### ISSUE THREAD

**Issue by mmameko** [ceolter/ag-grid#1450]
Is there any possibility to change filter values (on-fly)? 
I want to make a request to server, when user click on filter icon and then shows filter panel accordinly to values we have got. 
Can I do this without custom filter? I don't need custom filter becasue I just need to update list of values every time when I click on filter icon in the column header...
How I can realize this? What kind of realization can you advise me?

Thanks.

**Comment by seanlandsman** [comment]
Please raise support requests on either stackoverflow or the free forum: https://ag-grid.com/forum/forumdisplay.php?fid=4

Github is for issues only please.

**Comment by mmameko** [comment]
ok, sorry, I replaced post to [forum](https://ag-grid.com/forum/showthread.php?tid=4774)
Could you answer on it, please?
