### ISSUE TITLE
getSelectedRowsAfterFilterAndSort()

### ISSUE THREAD

**Issue by jathri** [ceolter/ag-grid#1451]
I'm submitting a feature request.

**Current behavior**
When I use gridOptions.api.getSelectedRows() on sorted dataset, array is created based upon original (and not sorted) order of items. And callbacks from forEachNodeAfterFilterAndSort() seems to be asynchronous. So they cannot all reach the same array for me to make my own list. Only thing that works for me is to save data to hidden html element and collect them afterwards. Which is a solution I do not like.

**Expected behavior**
To have getSelectedRowsAfterFilterAndSort() (or something like this) to be able to continue in synchronous processing. (In the case there is a need to work with a list of such items).

**Comment by seanlandsman** [comment]
"So they cannot all reach the same array for me to make my own list"

I'm not sure I understand this - it's true that forEachNodeAfterFilterAndSort will callback in turn, but this shouldnt stop you building up your own array

Something like this

array = [];
gridOptions.api.forEachNodeAfterFilterAndSort(function(node) {
    array.push(node);
})

**Comment by jathri** [comment]
This works. Thank you.
