### ISSUE TITLE
[header component] Add headerCellRendererFramework 

### ISSUE THREAD

**Issue by billyvg** [ceolter/ag-grid#1452]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
N/A
**Expected behavior**
Add a `headerCellRendererFramework` property so we can use other js frameworks for header cell

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
To be able to use React components for headercell

* **ag-Grid version:** X.X.X
7.2

**Comment by jameswyse** [comment]
I've been waiting for this too and I'm pretty sure it's in the next version (to be released this week last I heard)

**Comment by seanlandsman** [comment]
Hi - this will be available in the next release, to be released this week, or early next week at the latest
