### ISSUE TITLE
Provide non-offset pagination ability via augmentation of the "IGetRowsParams" interface

### ISSUE THREAD

**Issue by begincalendar** [ceolter/ag-grid#1453]
**I'm submitting a ...**
```
[ ] bug report
[x] feature request
[ ] support request
```

**Current behavior**
The `IGetRowsParams` interface only provides `startRow` and `endRow` which are offsets/indices into the row data.

**Expected behavior**
The `IGetRowsParams` interface should provide additional properties such that row data can be fetched via one or more properties of the cached row data, instead of by offset.

**Minimal reproduction of the problem with instructions**
N/A

**What is the motivation / use case for changing the behavior?**
The current behaviour relies on fetching row data via offsets.

If the data source is a remote relational database and the total row count is non-trivial, querying by offset is bad for performance.

A more performant solution is to query not by offset, but by a `WHERE` clause on one or more columns.

This isn't possible without access to the rows already cached in the ag-grid instance.

Yes I could go and implement my own custom state management to keep track of cached rows, but then everybody else who wants performant pagination has to re-invent the wheel over and over. It would be handy if ag-grid provided the means for everyone to be able to do it.

**Please tell us about your environment:**
N/A

* **ag-Grid version:** 7.1.0

* **Browser:** N/A

* **Language:** ES6 and React.js

**Comment by begincalendar** [comment]
After skimming some of the relevant code, it appears as though the `IGetRowsParams` interface is being used for both pagination and virtual pagination.

This "pagination-by-where" technique only works when you know the **previous adjacent** page, so it wouldn't work for virtual pagination, because there is potential for non-adjacent page skipping.

So I'm thinking if this were to be implemented, that `IGetRowsParams` interface will need to be split into two (e.g. via inheritance, to avoid duplication).

**Comment by ceolter** [comment]
```The IGetRowsParams interface should provide additional properties such that row data can be fetched via one or more properties of the cached row data, instead of by offset.```

i don't follow this, can you explain more? what would the extra params look like?

**Comment by begincalendar** [comment]
Sorry about the lack of clarity.

So for an existing use-case example, consider Reddit and viewing posts in a sub-reddit.
You get a "prev" and/or a "next" button and the pagination is done via WHERE clause, for performance reasons. 
I.e. the pagination is done via a query string like so: `?count=25&after=t3_5sules` (for getting the next page) and `?count=25&before=t3_5sules` (for getting the previous page).
No offset, just a value (based on the prior page's data) to put in the WHERE clause and a LIMIT.

So it would be handy to be able to implement that kind of pagination/fetching of rows, without everyone having to manually keep track of previously fetched rows.

I.e. If Ag-grid could (in addition to `startRow`, `endRow`, etc.), provide either:

- All the rows fetched from the prior page.
- The first and last rows from the prior page.
- Etc.

...in addition to some kind of indication as to whether this new page to be fetched is before or after the prior page, so also providing either:

- Prior page number and new page number
- Boolean variable which is true for forward and false for backwards.
- Etc.

I would usually be more specific with something like a pull request, but I'm not sure on the design approach you'd want to take if you are interested in providing this behaviour.

If it's still unclear, please let me know and I'll create a small pull request just to show you exactly what I mean, regardless of whether that particular implementation is used.

**Comment by begincalendar** [comment]
I realise this would not be suitable for a pull request, but [this](https://github.com/ceolter/ag-grid/compare/master...begincalendar:allowForWHEREClausePagination) should illustrate the concept.

**Comment by ceolter** [comment]
i'm understanding better, however i'm not convinced this belongs in the grid, as it ties the grid to a particular implementation of the server side.

why can't you put this logic into your datasource?

what happens if user jumps to a page? (we will be providing an API soon)

what happens if user is using virtual pagination (other other item we use datasource for), then the pages are not necessarily loaded in sequence.

what happens if user hits 'next' a few times to jump a few pages before previous page comes back? (then you don't have id's for the previous page, assuming i understand)

as a whole, i do think this is to specific to be part of the core grid, instead should be in the datasource.
