### ISSUE TITLE
data is not cleared

### ISSUE THREAD

**Issue by rajgopalk** [ceolter/ag-grid#1454]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
data is not cleared.

**Expected behavior**
data will be cleared

**Minimal reproduction of the problem with instructions**
when the page loads , i have display some data in agGrid based on some default location. if user selects another location, at that time no data is available. then we need to clear previous records and will display no records layout. 

no records layout is shown, but grid maintains previous records.

how can i , reset or clear previous records.
i've tried 
1. passing empty datasource - not working.
2. refreshview api call - not working.

**Comment by seanlandsman** [comment]
This isn't a bug, this is usage problem - please refer to https://www.ag-grid.com/javascript-grid-api/ for help on how to use the API.

To clear data in the grid try gridOption.setRowData([]) - you might need to do the same for the column definition if they're changing too

**Comment by bharatvaggu** [comment]
I am using gridOption.setRowData([]) for client side row model. Facing below issue

`TypeError: Cannot read property '0' of undefined
GridApi.setRowData
node_modules/ag-grid-community/dist/lib/gridApi.js:197
  194 | if (this.gridOptionsWrapper.isRowModelDefault()) {
  195 |   if (this.gridOptionsWrapper.isDeltaRowDataMode()) {
  196 |     var _a = this.immutableService.createTransactionForRowData(rowData),
> 197 |         transaction = _a[0],
      | ^  198 |         orderIdMap = _a[1];
  199 | 
  200 |     this.clientSideRowModel.updateRowData(transaction, orderIdMap); // need to force updating of full width rows - note this wouldn't be necessary the full width cell comp listened`

**Comment by seanlandsman** [comment]
@bharatvaggu can you provide a repro of this problem?

**Comment by bharatvaggu** [comment]
Below is the sample code

`public gridReady = (params: GridReadyEvent) => {
    if (params.api) {
        params.api.setRowData([]);
    }
};

<AgGridReact
    deltaRowDataMode={true}
    suppressMenuHide={true}
    suppressRowHoverHighlight={true}
    suppressMovableColumns={true}
    columnDefs={columnDefs}
    defaultColDef={{
    sortable: true,
    filter: true,
    resizable: true,
    autoHeight: true
    }}
    rowHeight={50}
    suppressRowTransform={true}
    onGridReady={this.gridReady}
    suppressRowClickSelection={true}
    suppressCellSelection={true}
    rowSelection={'multiple'}
    domLayout="autoHeight"
/>`

**Comment by bharatvaggu** [comment]
I have resolved by removing deltaRowDataMode={true}
