### ISSUE TITLE
Type annotations are incorrect for refreshCells

### ISSUE THREAD

**Issue by stephanjust** [ceolter/ag-grid#1457]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

This is really only a minor annoyance as it can be circumvented by an ```<any>``` cast, but that's not really the point of using Typescript, is it? :) 

**Current behavior**
```GridApi.refreshCells(rowNodes: RowNode[], colIds: string[], animate?: boolean): void``` takes a ```string[]``` as a parameter (colIds), although in the end the function to evaluate them is ```ColumnController.getGridColumn(key: string|ColDef|Column)``` (and 'obviously' it works with ```ColDefs``` and ```Columns``` just fine).

It appears that this chain is in general "wierdly" typed, with ```RowRenderer.refreshCells(rowNodes: RowNode[], colIds: string[], animate = false): void```and ```RenderedRows.refreshCells(colIds: string[], animate: boolean): void``` all taking a ```string[]```, whereas ```ColumnController.getGridColumns(keys: any[]): Column[]``` takes  an ```any[]``` to call ```ColumnController.getGridColumn(key: string|ColDef|Column)```.

**Expected behavior**
Methods that accept ```string|ColDef|Column``` as a paremeter should also have that included in their type annotations to avoid constant casting to ```<any>``` (or facing compiler errors otherwise).

* **ag-Grid version:** 7.1.0
and still the case in the github repo.

* **Language:** [TypeScript 2.1.1]

**Comment by seanlandsman** [comment]
tracked by AG-235

**Comment by makinggoodsoftware** [comment]
The types have been ammended to reflect the correct types. This will be available in the next release.
