### ISSUE TITLE
Is this intended behaviour?

### ISSUE THREAD

**Issue by AmitMY** [ceolter/ag-grid#1462]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When pinning right a checkbox header, the checkbox is to the right. Looks odd

**Expected behavior**
I would think it should go on the left.

**Minimal reproduction of the problem with instructions**
- Go to https://www.ag-grid.com/example.php
- pin `Name` column right

**What is the motivation / use case for changing the behavior?**
Consistency? not really sure, looks odd.

**Comment by willhalling** [comment]
Hello @AmitMY, I agree. I've raised this as a potential bug with core devs. For reference, this is the CSS in case you want to override it now, before a possible fix is added:

`.ag-ltr .ag-pinned-right-header .ag-header-select-all {
    float: left; // changed from right to left
}`

**Comment by AmitMY** [comment]
@willhalling Thanks. I am not using the grid ATM, so I won't need that patch :) Just noticed on the example page

**Comment by seanlandsman** [comment]
tracked by AG-233

**Comment by ceolter** [comment]
fixed. will be in next release.
