### ISSUE TITLE
AgGrid.Grid.setFrameworkBeans error

### ISSUE THREAD

**Issue by Ajaybhardwaj7** [ceolter/ag-grid#1464]
I am using a trial enterprise version of ag-Grid v 8.0.0 in react.
I have installed ag-grid-react v8.0.0 and have set the license. If I try to create an Ag grid react using 

> <AgGridReact
>           rowData= {this.props.events}
>           enableSorting="true"
>           enableFilter="true"
>           rowHeight="22"
>           columnDefs = {{headerName : "Report Status" , field:"Report Status"}}
>         />

it gives me the error 

> uncaught TypeError: AgGrid.Grid.setFrameworkBeans is not a function

I am not able to debug the actual cause

**Comment by ceolter** [comment]
you need v8.0.x for EVERYTHING, not just ag-grid-react, the first two digits must match when combining the ag-grid projects.

it sounds like you don't have right version set for ag-grid or ag-grid-enterprise.

if still an issue, please raise in the forum (get access if you are on a trial)
