### ISSUE TITLE
Cannot find module reactDateComponentFactory

### ISSUE THREAD

**Issue by Haemoglobin** [ceolter/ag-grid#1465]

**Comment by Haemoglobin** [comment]
I'm getting a typescript error:
ERROR in [at-loader] node_modules\ag-grid-react\main.d.ts:5:15
TS2307: Cannot find module './lib/reactDateComponentFactory'.


This file is referenced but it does not exist 

Thanks

**Comment by seanlandsman** [comment]
hi - already raised here: https://github.com/ceolter/ag-grid-react/issues/56

thanks for reporting this
