### ISSUE TITLE
Header group components cannot be dragged

### ISSUE THREAD

**Issue by ha-decodeit** [ceolter/ag-grid#1467]
**I'm submitting a bug report**

**Current behavior**
Header group components cannot be dragged. 

**Expected behavior**
According to the header component documentation, moving a column is a responsibility of ag grid, so I expect all header group columns to be movable if unless the _suppressMovableColumns_ property is set to true.

**Minimal reproduction of the problem with instructions**
The bug can be seen in the official demo for [header group components](https://www.ag-grid.com/javascript-grid-header-rendering/exampleHeaderGroupComponent.html)
Dragging a header group column does not work.

**Please tell us about your environment:**
Browser: **Chrome 56**
Language: **Typescript 2.1.4**
ag-Grid version: **Ag Grid (enterprise) 8.0.0** / **Ag Grid React 8.0.0**

(By the way, the link to **moving** is broken in the [header rendering documentation](https://www.ag-grid.com/javascript-grid-header-rendering))

**Comment by seanlandsman** [comment]
thanks - we'll take a look and get back to you

**Comment by seanlandsman** [comment]
re link, thanks - this has been reported and will be fixed today
