### ISSUE TITLE
rowSelected/selectionChanged events not triggered on deselecting a row

### ISSUE THREAD

**Issue by neha-nsharma** [ceolter/ag-grid#1470]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I upgraded to version 8.0.0 of ag-grid from version 3.x and started seeing this issue. 
The event handler for rowSelected and selectionChanged are not invoked when a selected row is clicked again to deselect

**Expected behavior**

The event handler for rowSelected and selectionChanged should be invoked when user clicks on the selected row again to unselect it.

**Minimal reproduction of the problem with instructions**
Created a simple ag-grid and set the options as 
    `onSelectionChanged = ->
        selectedRows = $scope.options.api.getSelectedRows();
        if selectedRows.length > 0
            console.log 'selected one row'
        else
            console.log 'Unselected the row'

    $scope.options =
        rowData:    data
        rowSelection: 'single'
        onSelectionChanged: onSelectionChanged`

In the grid, when a row is clicked first time the onSelectionChanged() in invoked. Click the same row again, the onSelectionChanged() is not invoked.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

MAC OS, IntelliJ, bower, jetty 

* **ag-Grid version:** X.X.X

Version 8.0.0.

* **Browser:**

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.37 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
CoffeeScript

**Comment by neha-nsharma** [comment]
I see the issue in  onRowClick function in renderedRow.ts 

`if (this.rowNode.isSelected()) {
            if (multiSelectKeyPressed) {
                if (gridOptionsWrapper.isRowDeselection()) {
                    this.rowNode.setSelectedParams({newValue: false});
                }
            } else {
                // selected with no multi key, must make sure anything else is unselected
                this.rowNode.setSelectedParams({newValue: true, clearSelection: true});
            }
        }
`

In the above else clause `this.rowNode.setSelectedParams({newValue: true, clearSelection: true});`, the newValue should  be set to false instead of true.

**Comment by willhalling** [comment]
Hi @neha-nsharma, the behaviour is slightly different in later versions of ag-Grid. You now deselect using cmd & left click (or ctrl & left click on windows). But first you need to set rowDeselection to true in gridOptions:
 
`rowDeselection: true,`

If you want the old behaviour you will need to create your own listener & logic for this.

**Comment by neha-nsharma** [comment]
Thank you for clarifying the behavior. It would be nice if the documentation is updated for the Selection API. It currently says `rowSelected: Gets called when a row is selected or deselected.`

**Comment by remborg** [comment]
I know it's a bit old but I just had a similar issue with angular2.
My solution was to add `suppressRowClickSelection: true` into the gridOptions and then listen to the `rowClicked` event :
```
  rowClicked(params) {
    params.node.setSelected(!params.node.isSelected());
  }
```
I find the new deselection behaviour (holding the ctrl or cmd key + click) not really user friendly but I guess there is a reason behind this decision :)
