### ISSUE TITLE
Bad circular dependency: context/context.ts and logger.ts

### ISSUE THREAD

**Issue by TheWind3** [ceolter/ag-grid#1476]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report 
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
`logger.ts` import decorators `@Bean` and `@Qualifier` from `context/context.ts`.
`context/context.ts` imports class `Logger` from `logger.ts`. `Logger` class is used by class `Context` in `context/context.ts`.
When CommonJS is used as module system, this circular dependency is ok. However, with ADM modules 
this dependency can not be resolved, and @Bean decorator is `undefined` in Logger class.

**Expected behavior**
It would be great to get rid of this circular dependency. It can be achieved by placing decorator definitions (`@Bean`, `@Qualifier`, etc) from `context/context.ts` to some separate file (say, `context/decorators.ts`.)

**Minimal reproduction of the problem with instructions**
Change module system to "amd", build and try execute any application. Exception will be raised when attempting to apply decorator to class Logger

**What is the motivation / use case for changing the behavior?**
For some reasons, a do not use webpack-ed ag-grid. Instead, i build ag-grid using AMD module system, then bundling compilation result in single js-bundle. At runtime this bundle is loaded with RequireJS loader.
Getting rid of the above circular dependency will allow using AMD loaders and "custom" builders/packers.

**Please tell us about your environment:**

* **ag-Grid version:** 8.0.1

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

* **Language:** 
all

**Comment by makinggoodsoftware** [comment]
The circular dependency has been fixed, it would be available in the next release.

**Comment by TheWind3** [comment]
Thank you :)
