### ISSUE TITLE
forEachNode cell update not taking as HTML 

### ISSUE THREAD

**Issue by safeerk** [ceolter/ag-grid#1477]
Dears,
            Am working with this ForeachNode updation please find the code below:

var updatedNodes = [];
   gridOptions1.api.forEachNode(function (node) { 
                                                var data = node.data;
                                                for (c = 0; c < result.length; c++)
                                                    if (data.JVM_RefNo.toString() == result[c][0]) {
                                                                **data.Status = "<@bold>" + result[c][1] + "</@bold>";**
                                                        updatedNodes.push(node); 
                                                    } 
                                            });  
                                            gridOptions1.api.refreshCells(updatedNodes, ['Status']);

PN: "<@bold>" is b

Even though am updating the the column to BOLD its not rendering as HTML 

![image](https://cloud.githubusercontent.com/assets/22815639/22977515/fdf9fdf2-f39f-11e6-8558-298960a5b8e4.png)

Is there any way to do so????
Thanks

**Comment by willhalling** [comment]
Hi @safeerk, check out cell rendering: https://www.ag-grid.com/javascript-grid-cell-rendering/

**Comment by safeerk** [comment]
Thanks dear, That work like charm... ;)
