### ISSUE TITLE
Supporting dynamic endRow in datasource

### ISSUE THREAD

**Issue by Liooo** [ceolter/ag-grid#1479]
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

I'm using datasource and fetching the data from server. I'm adding an arbitrary number of rows based on the fetched data, so the number rows added by `successCallback` differs every time. 

**Current behavior**
Because the number of the rows added goes beyond the `endRow`, these exceeded rows are overwritten by the ones that are added by the next `successCallback`. It'd be nice if I could change the `endRow` value.

**What is the motivation / use case for changing the behavior? / Expected behavior**

Here's what I'm trying to do in my app.

I have a list of data sorted by type column in advance, and want to insert fullwidthcells in table where the type changes, to make it easier to see the group of rows. Like the following

```
    id | type
    --------
          <---- fullwidthcell having "A" as the content
    1  |  A
    2  |  A
    3  |  A
          <---- fullwidthcell having "B" as the content
    4  |  B
    5  |  B
    6  |  B
    7  |  B
    8  |  B
    9  |  B
          <---- fullwidthcell having "C" as the content
    10 |  C
```

Here's what the current datasource is looking like, and it'd be nice if I could do something like `setEndRow()` below.

```
  var lastType = null;
  let dataSource = {
    rowCount: null,
    getRows: (params)=> {
      let pageSize = params.endRow - params.startRow,
          pageNum = 1 + (params.startRow / pageSize),
      
      // fetching `pageSize` records at the `pageNum` page
      MyApi.fetchData(pageNum, pageSize).then((data) => {
        let lastRow = (params.endRow >= data.totalCount) ? data.totalCount : -1,
             rowsToAdd = [],
             fullWidthRowAdded = 0;

        data.rows.forEach((r)=>{
          if(lastType != r.type){
            rowsToAdd.push({isFullWidthCell: true, domContent: r.type});
            fullWidthRowAdded++;
          }
          rowsToAdd.push(r);
          lastType = r.type;
        })

        // => wanna do something like the below, so that next time `getRows()` is called, 
        // params.startRow would be (params.endRow + fullWidthRowAdded + 1)
        setEndRow(params.endRow + fullWidthRowAdded); 

        params.successCallback(rowsToAdd, lastRow);
      })
    })
  };
```

* **ag-Grid version:** 
8.0.1

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

* **Language:**
all

**Comment by willhalling** [comment]
Thanks for info. I've raised this with the core dev team who will decide whether or not we can include this feature request - in a future release. We'll update this thread once we have confirmation either way.

**Comment by Liooo** [comment]
@willhalling okay thank you!

**Comment by ceolter** [comment]
this is an api method setVirtualRowCount()

doesn't this do what you want?

**Comment by Liooo** [comment]
@ceolter 
Thanks for the response!

setVirtualRowCount() updates the count of the total row, and what I want is to update the count of the rows in each page.

Say the page size is 10. In the first getRow() call, startRow is 0 and endRow is 10, if I add 15 rows here, the 11th to 15th rows will be overwritten by the next getRows() call. Because the library assumes the last row is the 10th one and starts rendering new ones from 11th row. 

I assume I need to call setVirtualRowCount() as well when doing this.

**Comment by Liooo** [comment]
@ceolter oh sorry maybe my mistake, setVirtualRowCount() does the exact thing I wanna do right?

**Comment by ceolter** [comment]
```setVirtualRowCount() does the exact thing I wanna do right?```

yes i think it does - but not 100% sure.

the grid should show exactly what is on your server side, so if you are showing rows 0 to 9, then that should be rows 0 to 9. i am afraid you are introducing groups on the UI, which do not exist on the server, which are impacting the row indexes. if this is the case, and you are changing the indexes, then it will not work like that. the infinite scrolling row model mandates that it's a linear list without introducing groups into the indexes.

on the other hand, if you are not introducing groups, then the rowCount should do as you want. when the grid reads more rows from the server, the indexes should align.

**Comment by AbinashMaharana** [comment]
ag-grid pagination is not working. Can anyone  help me please?
