### ISSUE TITLE
can't modify angular2 state from grid events ? 

### ISSUE THREAD

**Issue by squarewave24** [ceolter/ag-grid#1480]
I am using ag-grid for Angular2 and tried to do the following: 

        onCellClick: e => {
          console.debug('cell clicked ', e);
          this.MyObject.foo = 'bar 22222';
        }

basically modifying some variable in my class and then showing it in my view.html.

    MyObject: {{MyObject.foo}} 

I can see the original value, **but the modified value does not trigger UI update**. 

does ag-grid have any events that wire into Angular2 state?

**Comment by squarewave24** [comment]
ok so it looks like global grid events work in this fashion, it's just the cell click handler of the column does not.. 

i think i could get around this using global events.

**Comment by seanlandsman** [comment]
You have two options available to you here - use the context object:

Parent: https://github.com/ceolter/ag-grid-angular-example/blob/master/angular-cli/src/app/from-component.component.ts
Child: https://github.com/ceolter/ag-grid-angular-example/blob/master/angular-cli/src/app/child-message.component.ts

Or the angular suggested way to do this, which is to use services.

**Comment by squarewave24** [comment]
hey thanks! 

not sure how services apply here though? it just seems that the column click handler is not executed within angular context, so it wouldn't have any effect on services just like it doesn't on class variables. 

also not sure how the parent/child ways can be leveraged from column click component. 

i am now working on doing this via the global grid click handler which seems to be executed within angular2 context. 

these are just my findings/assumptions, i may be wrong!
