### ISSUE TITLE
Filter list not rendering full list (.ag-virtual-list-container)

### ISSUE THREAD

**Issue by vargarobert** [ceolter/ag-grid#1482]
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
There is something wrong with the ".ag-virtual-list-container" class as in the version of ag-grid-enterprise I am using there is an issue with the filter pop-up. The last item of the list is cut in half. Extending the height of .ag-virtual-list-container by a few more pixels in chrome debug console solves the issue. 
<img width="229" alt="screen shot 2017-02-20 at 19 34 37" src="https://cloud.githubusercontent.com/assets/1752085/23139452/55d8ff02-f7a4-11e6-8034-4471a176fd2a.png">

**Expected behavior**
The filter pop-up should have a height to cover the full list of items.

**Minimal reproduction of the problem with instructions**
Just use the latest version of ag-grid-enterprise and enable filtering.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** 8.1.0

* **Browser:** all (i.e. chrome v. 56)

* **Language:** all

**Comment by seanlandsman** [comment]
Hi 

We are unable to reproduce this using 8.1.0 (chrome 56) on a mac. 

![image](https://cloud.githubusercontent.com/assets/1329081/23205772/f11971b0-f8e2-11e6-875f-60dcdf48b3ca.png)

Can you please provide a bit more detail - are you on windows perhaps (not sure that would make a difference in this case) ?

**Comment by vargarobert** [comment]
I'm sorry. It was something on my side
