### ISSUE TITLE
scroll down to row programmatically after edit form

### ISSUE THREAD

**Issue by harsh5400** [ceolter/ag-grid#1483]
Hi

After edit form how I can scroll down to last selected row ? Please help

Using Angular 2

**Comment by harsh5400** [comment]
Hi

After edit form how I can scroll down to last selected row ? Please help

**Comment by seanlandsman** [comment]
As per the issue template, please dont use github for support

Take a look at the api - try either ensureIndexVisible or ensureNodeVisible
