### ISSUE TITLE
Column Grouping breaks in 8.1.0 with pinned columns

### ISSUE THREAD

**Issue by supersabillon** [ceolter/ag-grid#1488]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When opening and closing group columns, the layout breaks.

**Expected behavior**
When opening and closing group columns with pinned columns the layout should not break.

**Minimal reproduction of the problem with instructions**
Here is the same data in 6.4.2 working correctly:
http://jsbin.com/yucitohono/edit?js,output

here is 8.1.0 where layout breaks:
http://jsbin.com/bawonodoyu/edit?js,output

To reproduce, open the group column, close it, and scroll to the right and you will notice some of the layout is not correct.

**Please tell us about your environment:**
 Mac, Chrome,

* **ag-Grid version:** X.X.X
worked fine in 6.4.2, recently updated to 8.1.0 and it breaks.

* **Browser:**
Chrome

* **Language:** 
javascript

**Comment by willhalling** [comment]
Hi @supersabillon, thanks for raising this and providing examples. I've raised with core dev team and should be fixed in a future release. You can track progress on our pipeline page (AG-274):

https://www.ag-grid.com/ag-grid-pipeline/

**Comment by ceolter** [comment]
i have tested this locally on the latest and it is working. i believe i fixed it a few weeks ago - i came across it myself when looking at something else. will be fixed in next release.
