### ISSUE TITLE
Cannot evaluate Aurelia string interpolation and binding expressions in cellRenderer

### ISSUE THREAD

**Issue by don-bluelinegrid** [ceolter/ag-grid#1489]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In a cellRenderer like the following, the Aurelia string interpolation and binding expressions are not evaluated:
```
            cellRenderer: function(params) {
              var eDiv = document.createElement('div');
              eDiv.innerHTML = '<i if.bind="requestType==\'INVITED\'" onclick="editConnectionRequest([connection], \'ACCEPT\')" click.delegate="editConnectionRequest([connection], \'ACCEPT\')" class="ico-bin float-right"></i> <i click.delegate="editConnectionRequest([connection], \'ACCEPT\')" class="ico-circle-right6 float-right"></i>';
              var eButton = eDiv.querySelectorAll('.btn-simple')[0];

              return eDiv;
            }
```

**Expected behavior**
We need to be able to use these expressions in a cellRenderer.  Without this, we can't bind click actions to methods in Aurelia ViewModels.

**Minimal reproduction of the problem with instructions**
See above example.

**What is the motivation / use case for changing the behavior?**
See above expected behavior.

**Please tell us about your environment:**
N/A

* **ag-Grid version:** X.X.X
7.2.2

* **Browser:**
All.

* **Language:** TypeScript

**Comment by seanlandsman** [comment]
We dont support dynamic binding etc in cell renderer (or editor/filter) functions - functions are for "pure" js only.

For aurelia, you need to make use of templates (or components) - I suggest you take a look at the aurelia example project for examples of what we support here: https://github.com/ceolter/ag-grid-aurelia-example

Going forward, can you please raise issues under the https://github.com/ceolter/ag-grid-aurelia repo for aurelia related issues - thanks

**Comment by don-bluelinegrid** [comment]
@seanlandsman 

Sean,

OK, I converted this piece of implementation over to use the declarative style with the Aurelia plugin, and it works fairly well.  I have run into one issue though.

Again, my goal was to use a custom renderer template in a cell.  The template looks like this:
```
        <ag-grid-column header-name="" >
            <ag-cell-template>
                <i if.bind="requestType=='INVITED'" click.delegate="$this.editConnectionRequest([data], 'DECLINE')" class="ico-bin float-right"></i> <i click.delegate="editConnectionRequest([connection], 'ACCEPT', 'CONNECTION_ACCEPTED')" class="ico-circle-right6 float-right"></i>
            </ag-cell-template>
        </ag-grid-column>

```

What's interesting, and the issue, is that the ```if.bind`` is being correctly evaluated and exectued; but the ```click.delegate``` is not working correctly.  The function ```editConnectionRequest()``` exists in the ViewModel (controller) but when I click the element I see this error in the console:

```
Uncaught Error: editConnectionRequest is not a function
    at getFunction (aurelia-binding.js:1924)
    at CallScope.evaluate (aurelia-binding.js:1527)
    at Listener.callSource (aurelia-binding.js:5064)
    at aurelia-binding.js:5088
    at HTMLDocument.handleDelegatedEvent (aurelia-binding.js:3232)
```

Do you have any explanation or advice for this?

This is my key use case - provide a custom cell template with clickable icons, whose click event is delegated to an Aurelia ViewModel function.

Thanks,
Don
