### ISSUE TITLE
Unable to get context menu in Pop up editors

### ISSUE THREAD

**Issue by JonathanDX** [ceolter/ag-grid#1491]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Unable to Right-Click / Open context menu on Pop Up Editor components. Editor is closed on Right Click.

Currently have to remove the event listener being added for context menu within Pop Up Service - addAsModalPopup.

**Expected behavior**
Context menu shows on right click within editor component. Editor does not close.

**What is the motivation / use case for changing the behavior?**
Show Context Menu, allowing for Chrome Features like spell checking of words in text editing components.

**Please tell us about your environment:**

* **ag-Grid version:** 8.1.0

* **Browser:**
Chrome

* **Language:** all

**Comment by willhalling** [comment]
Thanks for feedback @JonathanDX 

However, we believe 'right click' is outside the responsibility of the core grid. And is within the scope of the Pop Up Editor. So controlling the listeners (and event propagation) with your own logic is the best solution.
