### ISSUE TITLE
The grid is missing basic functionality

### ISSUE THREAD

**Issue by WhitneyLand** [ceolter/ag-grid#1492]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
For all common and simple activities you must write code to handle them wasting a large amount of time.  How does it make sense to require users to provide custom methods for the simplest date sorting, currency rendering, etc?

**Expected behavior**
This has nothing to do with customization.  It's great that you can customize!  But there is just no reason to not support such common scenarios.  Lots of people are asking these questions over and over.

**Minimal reproduction of the problem with instructions**

Just look at the docs, no options for common sorting and rendering scenarios.

**What is the motivation / use case for changing the behavior?**
Why on Earth should devs waste time writing this code just to sort dates?  Here is an example of what is expected from the docs:

function dateComparator(date1, date2) {
    var date1Number = monthToComparableNumber(date1);
    var date2Number = monthToComparableNumber(date2);

    if (date1Number===null && date2Number===null) {
        return 0;
    }
    if (date1Number===null) {
        return -1;
    }
    if (date2Number===null) {
        return 1;
    }
    return date1Number - date2Number;
}

**Please tell us about your environment:**
ReactJS

* **ag-Grid version:** 8.1.0

* **Browser:**
Chrome

* **Language:** [ES6/7 | ES5]

**Comment by ceolter** [comment]
this is a very strange issue.

we are a team of 6 now, 3 of us are full time dev, from those 3, 1 of us is doing frameworks full time (mostly angular 2, as that's causing the most noise these days) and the other two of us are doing core development constantly adding new features.

we have a big backlog of items to get through.

this issue sounds like "work harder guys, you not getting all the features in the world expects"

if you want to raise specific issues or feature requests, please do.

**Comment by WhitneyLand** [comment]
With the benefit of a full nights sleep, I realize my report was imprecise, lacking constructive suggestions, and not as respectful as I would have liked.

I do have sepecific ideas on how to make things better, and I think without actually burdening the team more.  How would that be possible?  Hopefully soon I'll have some time to write something up explaining the big picture.

In any case, until then I wish you the best.
