### ISSUE TITLE
Resize on pinned-right column bug

### ISSUE THREAD

**Issue by iboffa** [ceolter/ag-grid#1493]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When resizing a pinned-right column, the border moving is the one on the left of the one I'm moving

**Expected behavior**

I expect to resize the column on the side I'm moving

**Minimal reproduction of the problem with instructions**

-Pin two columns on the right
-Move the middle border

**What is the motivation / use case for changing the behavior?**

A table with pinned-right columns

**Please tell us about your environment:**

Windows 7, Eclipse Neon, Apache 8

* **ag-Grid version:** 8.1.0

* **Browser:**

Google Chrome 56.0.2924.87 , Mozilla Firefox 48.0, Internet Explorer 11
* **Language:** [all | TypeScript X.X | ES6/7 | ES5] Javascript ES6

**Comment by willhalling** [comment]
Hello @iboffa, unfortunately, two of us cannot replicate this issue. Please can you try using the main demo at https://www.ag-grid.com/example.php

And if the problem persists include an example/screenshot?

**Comment by iboffa** [comment]
I tried to replicate it on Plunker, but actually I cannot (same table configuration, same css). I think you can close by now
