### ISSUE TITLE
Feature request: Server side search, no way to set startRow and endRow on results for pagination

### ISSUE THREAD

**Issue by gregbown** [ceolter/ag-grid#1495]
I could not locate any method to update the page, startRow or endRow after server side search.

Motivation / use case for changing the behavior:
With server side search, page size of 25 rows, if a the result is on page 2 of 150, lets say row 27 of 3,750 rows there is no way to set the startRow and endRow on getting the results.
see https://gist.github.com/gregbown/1750a13fdfd71392ce15cbc2e04bcc12

Expected behavior:
I should be able to show the user that the result is on page 2 of 3,750 and they should be able to paginate forward and backwards in that filtered or search set. In my response data I get total pages and current page so my data provides everything needed.  If the data is loaded without the search i can find the item I am looking for in row 27 or page 2. My query accepts a page size so I am getting back a result that the searched item is on the second page, I get rows 26-50 with the search result in row 27.

Is there an obscure method I can call through the api or rownode to set the page or row? Is this a request that is already in the pipeline?  I see plans to avail external pagination so, perhaps this functionallity will be added by default with that.

Current behavior
The only way to affect the startRow and endRow seems to be via the built in pagination controls. Pagination works great via the controls but there appears to be no way to present a search result as it would rank by page or row.

My environment:
Using Angular 2.4.8, AG-Grid 8.1.1 AG-Grid-Angular 8.1.0, TypeScript 2.2.1 compiling to ES5 with Webpack 2, Windows 10 Pro, Chrome Version 55.0.2883.87

Thank you
Greg

**Comment by ceolter** [comment]
sorry, i am just not following the question.

we are working on an API, which will have something like:
api.nextPage()
api.previousPage()
api.whatIsTheCurrentPage()

will that work?

**Comment by gregbown** [comment]
No, I need to be able to set the page prior to the pagination being rendered.  I have a leader board that shows player rank.  My server side search returns a user who ranks 27th so they are on page 2 with the grid set to 25 rows per page. When I get the search data, the data reflects that it is page 2 of the total pages and returns row 26 thru 50. There is no way to set the row or page in the grid that will trigger the pagination indicating page 2 of ... Currently it will always show a server side search result as page 1 therefor I cannot correctly paginate through a server side search result. clicking 'Next' will request startRow 26 and endRow 50 which will result in the exact same page I already had and 'Previous' is not available when it should be.
What I need is a method to set startRow, endRow or current page.
Something like api.setRows(start:number, end:number) or api.setCurrentPage(page:number)

Thank you, any assistance is appreciated.
Greg

**Comment by ceolter** [comment]
setting page number will be part of the new api. i'm closing this issue as it's already covered by the work i'm currently doing! it will be in the next release. thanks.

**Comment by gregbown** [comment]
Awesome! Thank you for great data grid framework and the amazing integration with Angular 2.

**Comment by gregbown** [comment]
My current work around for keeping the pagination in sync is to do one of the following, however; it is not ideal since it triggers requesting the exact data that was just received in the prior search.
```
          /** The search result page we received is not page 0 that ag-grid thinks */
          // Could do this.
          this.gridOptions.api.paginationGoToPage(this._pageNumber - 1);
          // or this
          // this.gridOptions.paginationStartPage = (this._pageNumber - 1);
          // this.gridOptions.api.onSortChanged();
          return;
```

**Comment by pankyka** [comment]
Hi guys, Is there any way to set the initial page before having call `getRows()` method? Sort and filter models are able to serialize/deserialize in url, for pagination I didn't find any workaround.

**Comment by jskod** [comment]
Is there any solution setting start page using server-side model? I am saving `currentPage=Number` in  URLs and whenever somebody visits that URL with currentPage=Number, I want to initialize grid and load the request page instead of loading first page and then setting `paginationGoToPage(Number)`. If you have any good work-around, please help me.

**Comment by foysalit** [comment]
Any update on this? Has this been released already but not documented?

**Comment by naveenkumar1012** [comment]
Any update?
