### ISSUE TITLE
Keyboard Navigation Bug

### ISSUE THREAD

**Issue by jathri** [ceolter/ag-grid#1497]
**I'm submitting a bug report**

**Current behavior**
When I press alt + up in the grid, alt modifier is ignored and up navigation event is triggered.

**Expected behavior**
Cursor (focus) should not move one row up. Like in notepad++ or excel.

**Minimal reproduction of the problem with instructions**
press alt + up

**What is the motivation / use case for changing the behavior?**
i want to use alt + up, down... as shortcuts for custom actions

**Please tell us about your environment:**
W7, Firefox 51.0.1., ag-grid v8.1.0

**Comment by willhalling** [comment]
Hello @jathri, you can create your own custom keyboard navigation. Check out the docs: https://www.ag-grid.com/javascript-grid-keyboard-navigation/

And you can create your own event listener to stop propagation for alt + up.

**Comment by jathri** [comment]
Thank you. Solution:
1) column definition:
`cellRenderer: function (params) {
	params.eGridCell.addEventListener('keydown', listenIt)
    return params.value;
    }`
2) listenIt function:
`function listenIt(e) {
if (e.altKey && e.keyCode == 38) {
		  e.stopPropagation();
    e.preventDefault();
		// custom action
	}
}`
But I still think there is a bug in your navigation system. Alt + up just is not up.
Regardless of it I would like to ask if you can look into:
http://stackoverflow.com/questions/42414625/getting-value-from-getwidthforsizecolstofit
What am I please missing?
