### ISSUE TITLE
Column group moving may break apart column group

### ISSUE THREAD

**Issue by mikethone** [ceolter/ag-grid#1500]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

manually moving column groups around sometimes results in the column group being broken apart. 

**Expected behavior**

I expect to be able to move column groups around, and have the sub-columns remain within the group. 

**Minimal reproduction of the problem with instructions**

On the ag-grid demo site (https://ag-grid.com/example.php): 
1. Expand Performance column group, notice that there are three columns grouped under the Performance header.
2. Move Performance column group to the left of the Game of Choice column group.
3. Move Rating column to the left of Game of Choice column
4. Expand Performance column group again, notice that Performance Group sub-columns have been broken apart, and now have the Rating column in between.

See video example here: https://youtu.be/0kAKPjjT6wI

**What is the motivation / use case for changing the behavior?**

Our implementation relies heavily on column grouping, and moving column groups around. Having the column groups break apart without intending it creates a confusing experience.

**Please tell us about your environment:**

Chrome 56.0.2924.87 (64-bit) / Mac OSX 10.11.6

* **ag-Grid version:** X.X.X

ag-grid-enterprise v7.1.0 

* **Browser:**

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES5

**Comment by seanlandsman** [comment]
This issue has been raised as AG-308. You can track its progress in our pipeline (https://www.ag-grid.com/ag-grid-pipeline/) but we’ll also update this thread when actioned.

thanks

**Comment by ceolter** [comment]
use the attribute marryChildren on the group, this will stop the children from breaking apart.
