### ISSUE TITLE
removeEventListener not removing the listener

### ISSUE THREAD

**Issue by param-randhawa** [ceolter/ag-grid#1502]
Great work on the Ag-Grid. It is very powerful and I am loving it so far.
I think I discovered a bug. I am not able to remove an event listener.
As per the documentation, I should be able to remove the event listener using “removeEventListener(eventType, listener)”.

**Following is my code to add event listeners and remove them:**
```
[x] bug report => 

// Add event listeneers:

onGridReadyElementTypes(): void {
        this.gridOptionsElementTypes.api.sizeColumnsToFit();
        this.gridOptionsElementTypes.api.addEventListener('selectionChanged', this.onSelectionChangedElementTypes.bind(this));
        this.gridOptionsElementTypes.api.addEventListener('modelUpdated', this.onModelUpdatedElementTypes.bind(this));
        this.gridOptionsElementTypes.api.addEventListener('rowClicked', this.onRowClickedElementTypes.bind(this));
    }

// Remove event listeners:

onSomeButtonClick(): void {
        this.gridOptionsElementTypes.api.sizeColumnsToFit();
        this.gridOptionsElementTypes.api.removeEventListener('selectionChanged', this.onSelectionChangedElementTypes.bind(this));
       this.gridOptionsElementTypes.api.removeEventListener ('rowClicked', this.onRowClickedElementTypes.bind(this));
    }


```

**Current behavior**
Event listeners are not removed, as specified in example above.

**Expected behavior**
Event Listeners should remove when removeEventListener is used

**Minimal reproduction of the problem with instructions**
refer to code above.

**What is the motivation / use case for changing the behavior?**
refer to code above.

**Please tell us about your environment:**
Windows 7, Chrome (latest), Ag-Grid 8.1.1

* **ag-Grid version:** 8.1.1
Ag-Grid 8.1.1

* **Browser:**

* **Language:** [TypeScript 2.X | ES5 ]

**Comment by seanlandsman** [comment]
The probable cause here is that the event listener you're adding isnt the one you're trying to remove later.

Try something like this: 

let listener = this.onSelectionChangedElementTypes.bind(this);
this.gridOptionsElementTypes.api.addEventListener('selectionChanged', listener);

this.gridOptionsElementTypes.api.removeEventListener('selectionChanged', listener);

**Comment by seanlandsman** [comment]
Hi

I assume that the above helped you resolve the issue. If this is still a problem please raise a new issue.

thanks

**Comment by joeylgutierrez** [comment]
this is not fixed, if you look in the eventService of release 10.1.0, you can see that async is always false.  There's no option to update that variable and it will always be undefined.  I went back to 9.1.0 and it's done differently and works find.
`    EventService.prototype.removeEventListener = function (eventType, listener, async) {
        if (async === void 0) { async = false; }
        var listenerList = this.getListenerList(eventType, async);
        utils_1.Utils.removeFromArray(listenerList, listener);
    };`

**Comment by anatolyzolotar** [comment]
@joeylgutierrez, agree. I've encountered the same problem. I use 11.0.0 and found that when I call 
`gridOptions.api.addEventListener('someEventName', handlerFn)`
under the hood EventService adds this handlerFn into
`gridOptions.api.eventService.allAsyncListeners.someEventName` array. But when I remove the handler with
`gridOptions.api.removeEventListener('someEventName', handlerFn)`
EventService tries to find this handler **in sync listeners array**. And, as a result, handler is still added. And looks like I can not change value of async parameter for work with proper handlers array.

**Comment by seanlandsman** [comment]
@joeylgutierrez @anatolyzolotar 

The original issue was resolved - it sounds like you've uncovered a new issue specifically introduced in 10.1

Can you please raise a new issue for this
