### ISSUE TITLE
How set row style dynamically?

### ISSUE THREAD

**Issue by MehdiSaeedifar** [ceolter/ag-grid#1505]
Is there any way to set row style dynamically on run time? for example in **onRowValueChanged** event if  an error occurred we want to set border of the row to red color.

**Comment by seanlandsman** [comment]
Please dont use github for support queries - use stackoverflow or our free forum: https://ag-grid.com/forum/forumdisplay.php?fid=4

Take a look at the docs on styling: https://www.ag-grid.com/javascript-grid-cell-styling/#gsc.tab=0

**Comment by self-reference799** [comment]
https://dynatree.github.io/7ajd3G6v6M1ogDn6KxsAi0Xl8PZymtx-cK9QyEBH7z9T8VhbXw/



Consider this perspective
