### ISSUE TITLE
Read only floating row in editable cell

### ISSUE THREAD

**Issue by MehdiSaeedifar** [ceolter/ag-grid#1506]
Is there any way to set floating row read only in editable cell?

**Current behavior**

Floating row cells become editable as their column definition.

**Expected behavior**
 
There is an parameter like **floatingCellEditable** to control floating row cell editing.

**Minimal reproduction of the problem with instructions**
Define editable columns with floating row.

* **ag-Grid version:** X.X.X

8.1.1

**Comment by seanlandsman** [comment]
Use stackoverflow or our free forum for support queries: https://ag-grid.com/forum/forumdisplay.php?fid=4
