### ISSUE TITLE
suppressKeyEdit

### ISSUE THREAD

**Issue by jathri** [ceolter/ag-grid#1508]
**I'm submitting a feature request**

**Current behavior**
When you press any key from this list (https://www.ag-grid.com/javascript-grid-cell-editing/#start-editing), cell editing (in editable column) will start even if you do not want to.

**Expected behavior**
Ability to have complete control over how cell editing is started. When both suppressKeyEdit and suppressClickEdit are true, only mean how to start editing would be api.startEditingCell().

**What is the motivation / use case for changing the behavior?**
I can of course stop propagating all keys to grid except for whitelisted but that cut off users from using other firefox shortcuts like ctrl + 9 which focuses last tab. This is also related to unfixed bug from https://github.com/ceolter/ag-grid/issues/1497. When I press ctrl + 9, grid ignores ctrl modifier and start editing cell with value 9. 
I also need suppressKeyEdit to make something like this (http://stackoverflow.com/questions/42175788/search-focus-as-you-type) work. I do not want to start editing and I only want to listen to keys pressed and act upon it.

**Please tell us about your environment:**
W7, Firefox 51.0.1., ag-grid v8.1.0

**Comment by seanlandsman** [comment]
If you want full control on key interactions you can use Cell Editor Components https://www.ag-grid.com/javascript-grid-cell-editor

You can use the isCancelBeforeStart method to determine if editing should start or not

**Comment by jathri** [comment]
I have:
```
var stopEdit = (params.keyPress || params.charPress);
this.cancelBeforeStart = stopEdit;
```
in prototype.init.
It really prevents cell from being edited by pressing any of this keys (https://www.ag-grid.com/javascript-grid-cell-editing/#start-editing).
But the ctrl + 9 shortcut is consumed with it. It does not get through to firefox browser. It is consumed  because grid ignores modifier and read this shortcut only as a 9 and try to start editing cell. The result is the same as stopping propagation of all keys without whitelisted ones. User cannot use firefox shortcuts. Please, can you comment on this...

**Comment by jathri** [comment]
Any news here, please?
