### ISSUE TITLE
Per column filter row just after the column header row

### ISSUE THREAD

**Issue by jindalit** [ceolter/ag-grid#1510]
I am trying to implement the Per column filter row just after the column header row

http://stackoverflow.com/questions/39785484/per-column-filter-on-ag-grid

![cqllk](https://cloud.githubusercontent.com/assets/892808/23654757/2861f988-0358-11e7-9725-5003e1c3757b.png)

**Comment by jindalit** [comment]
Please help me to integrated the same

**Comment by seanlandsman** [comment]
With the next release there will be floating row filters - we're doing a release today

**Comment by jindalit** [comment]
Thanks for incorporate this feature in this release.

Can you guys please explain me the steps to integrate this newly added feature.

Regards,
Mayank Jindal

**Comment by st-andrew** [comment]
https://www.ag-grid.com/javascript-grid-filtering/#floatingFilter
