### ISSUE TITLE
In react version filter is reset when data changes

### ISSUE THREAD

**Issue by macrozone** [ceolter/ag-grid#1512]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When I set a filter and the rowData changes, the filter is reset. 

**Expected behavior**

The filter should maintain its state if rowData changes

**Minimal reproduction of the problem with instructions**

- create AgGridReact component with filtering:

```
  <AgGridReact
        columnDefs={agCoumnDefs}
        enableFilter
        rowData={rowData}
      />
```

- set a filter
- update rowData

**What is the motivation / use case for changing the behavior?**

AgGridReact with filtering is unusable with live-data

**Please tell us about your environment:**

React 15.4.2

* **ag-Grid version:** 8.2.0

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
Please take a look at the filter docs here: https://www.ag-grid.com/javascript-grid-filtering

You dig in further on each time of filter below that

You want newRowsAction - this property determines what to do when new data arrives. Set this to "keep" and it should do what you need
