### ISSUE TITLE
Set filter model with "greaterThan" and "0" not working

### ISSUE THREAD

**Issue by wOOx92** [ceolter/ag-grid#1513]
**I'm submitting a ...** 
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
I've got a simple column named 'myColumn' with numeric values. I want to set a filter on it with values > 0.

I'm using the following code snipped for that

**Expected behavior**
All rows with column 'myColumn' < 1 will not be shown (filtered).

**Minimal reproduction of the problem with instructions**
1. `let filterInstance: any = this.gridOptions.api.getFilterInstance('myColumn');
        filterInstance.setModel({ type: 'greaterThan', filter: 0 });`
2. `this.gridOptionsSend.api.onFilterChanged();`

The funny thing is, it's working with 'filter:1' and any other values, except zero (0).

**Please tell us about your environment:**
Angular 2.4.9 + Webpack 

* **ag-Grid version:** 8.2.0
and ag-grid-angular 8.2.0

* **Reason**
I think the reason for this bug is the method "doesFilterPass(...)" in the class "ScalarBaseFilter", where the variable 'from' is checked for 'null' in the following line:
https://github.com/ceolter/ag-grid/blob/cd20dfe349f8320b4e6d09300568a2e293c90edd/src/ts/filter/baseFilter.ts#L282

Because my 'filter' IS the value 0, it will always return at this point. :(

**Comment by seanlandsman** [comment]
Set filters do not support numeric comparisons - for that sort of filter you'd need to use a number filter or a custom one

Set filters only a list of values (or none)

thanks

**Comment by wOOx92** [comment]
Hello,

thx for the response. I am already using a number filter, or am I doing it wrong?
In the previous version, this feature was perfectly working?

**Comment by seanlandsman** [comment]
Ok, I see, I incorrectly assumed you were using set filter, but see what you meant now

This looks like a bug - we'll raise an issue our side and it'll be fixed in the next release

thanks

**Comment by wOOx92** [comment]
Ok, thank you very much! :+1:

**Comment by ajarratt** [comment]
I have also found this bug with the number filter evaluating every row to "true" when 0 is inputted into filter.

Is there any fix outside the Ag-Grid source that we can make in the meantime before it is fixed in Ag-Grid? Preferably outside of creating a custom Number filter. Thanks for the help!

**Comment by hyyan** [comment]
@seanlandsman Is this issue solved yet, it seems not for me so far ?!

**Comment by seanlandsman** [comment]
@hyyan yes, this has been fixed. You can verify this by trying the gold col (for example) here: https://www.ag-grid.com/javascript-grid-filtering/example1.html

Both via the filter ui or via the api the greaterThan 0 works as expected

thanks

**Comment by us-concrete-sdiwan** [comment]
Still, i am facing this same in **ag-grid-angular@26.2.0**
