### ISSUE TITLE
Restriction of row grouping attributes.

### ISSUE THREAD

**Issue by upendrareddyvca** [ceolter/ag-grid#1515]
This is not a bug.

I want to restrict grouping attributes to only one. In row group panel we can drag and drop as many columns as we want to see the grouped rows. I want to restrict it to one.

Until unless user removes the existing grouped attribute it should not allow to add another grouping attribute or it has to replace the existing grouping attribute with new grouping attribute. 

Is it possible to implement with current ag-grid if so, please guide me....

**Comment by seanlandsman** [comment]
Please raise enterprise requests in the members forum: https://ag-grid.com/forum/forumdisplay.php?fid=5
