### ISSUE TITLE
Not able to change the place of row group panel

### ISSUE THREAD

**Issue by upendrareddyvca** [ceolter/ag-grid#1516]
Not able to change the position of row group panel. I want to style it as the following image
![image](https://cloud.githubusercontent.com/assets/26376973/23847444/5656c5fe-07f8-11e7-970a-cad143b46853.png)
is it possible to style like the above image? if so please advice me...

**Comment by seanlandsman** [comment]
Please raise enterprise feature requests on our Members Forum: https://ag-grid.com/forum/forumdisplay.php?fid=5
