### ISSUE TITLE
 floating filter framework

### ISSUE THREAD

**Issue by sklyarov-ivan** [ceolter/ag-grid#1518]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Expected behavior**
Add floating filter framework to be able to customize template and behavior.

* **ag-Grid version:** 8.2.0

* **Language:** [ ES6/7]

**Comment by mikevanilla** [comment]
Is this something that is already targeted for a future release? Most of my data cannot utilize the standard floating filters.

**Comment by seanlandsman** [comment]
Hi - I've raised request AG-323 for this.

It is not something targeted for a release yet I'm afraid

**Comment by makinggoodsoftware** [comment]
Hi,

Just to le you know that as of 10.1.0 this is available.

Please check the changelog

Thanks
