### ISSUE TITLE
TypeScript - set filter parameters

### ISSUE THREAD

**Issue by sbublava** [ceolter/ag-grid#1521]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

"ag-grid" defines SetFilterParameters (ag-grid/dist/lib/filter/setFilterParameters.d.ts), which seems to be out of date / does not match the documentation.

"ag-grid-enterprise" defines ISetFilterParams (ag-grid-enterprise/dist/lib/setFilter/setFilter.d.ts), which matches the documentation, but optional properties (e.g. cellHeight) are marked as mandatory.

This code should compile:

import { ColDef } from 'ag-grid';
import { ISetFilterParams } from 'ag-grid-enterprise/main';

export class ClientDataListComponent {
    protected createColumnDefinitions(): Array<ColDef> {
        return [
            {
                filter: 'set',
                filterParams: <ISetFilterParams>{
                    values: [true, false]
                }
            }
        ]
    }
}

but triggers this error:

ERROR in xxx.ts  (9,31): Type '{ values: boolean[]; }' cannot be converted to type 'ISet
FilterParams'.
  Property 'cellHeight' is missing in type '{ values: boolean[]; }'.)

This seems to be related to Angular CLI / Webpack - tsc doesn't compain for some strange reason. 

**Expected behavior**

Please remove the outdated interface and mark optional properites as such.

**Please tell us about your environment:**

WIndows

* **ag-Grid version:** 8.2.0

* **Browser:** IE 11, Firefox 51

* **Language:** TypeScript 2.1.5

**Comment by seanlandsman** [comment]
Hi - thaks for reporting

AG-328 raised our side for this - we'll update this thread too once done

**Comment by jindalrohit** [comment]
I was having the same issue but after some hit and try, it's working fine now for me. 
"ag-grid": "^11.0.0",
"ag-grid-angular": "^11.0.0",
