### ISSUE TITLE
Grouping with Full width Row (Expandable)

### ISSUE THREAD

**Issue by ananddc1989** [ceolter/ag-grid#1523]
@ceolter: I try  to implement the grouping or tree data with full width row (Expandable).  because both having the same set of cellrenderer, expandable not working when grouping available

> cellRenderer: 'group', 

if its possible, can we have example here please
https://www.ag-grid.com/javascript-grid-full-width-rows/?framework=angular#gsc.tab=0

Thanks you
Anand

**Comment by seanlandsman** [comment]
Hi

Please raise support requests either in stackoverflow, or our free forum: https://ag-grid.com/forum/forumdisplay.php?fid=4

**Comment by spiko-md** [comment]
Has this issue been raised in either SO or official forums so I can check the answer?
