### ISSUE TITLE
ag-grid iPad Sort and Filter issue

### ISSUE THREAD

**Issue by sonuait135** [ceolter/ag-grid#1524]
Hi Team,

I have successfull impemented Ag-grid and its working fine in desktop browser, but when we open our application in iPad, we get below two issues :-

Issue # 1:  When you click once on a column header to sort, the system responds as if you've clicked twice.
**For example:** with no filtering or sorting applied, I clicked once on a column name "Deal ID". It quickly showed the upward pointing triangle and then changed to the downward pointing triangle. If I click it a second time then it quickly shows no triangle and then changes to the upward pointing triangle.

Issue # 2:- When i click on filter icon, filter menu opens, but it sorts the column also.

Any help in these issues will be highly appreciated.

Thanks
Sonu

**Comment by seanlandsman** [comment]
Hi

I cannot reproduce issue 1 - can you reproduce it here? ag-grid.com/example.php

I think there might have been an issue in a previous release around this, since fixed

For issue 2, the filter icon should not appear when on mobile devices - I've raised issue for this AG-330

On mobile devices you invoke the menu by pressing and holding down on the header

**Comment by sonuait135** [comment]
Hi ,
 Thanks for your response. I am not able to reproduce this issue in that link. But I figured out that this thing is happening because the onsortchanged method implemented at grid options is getting called twice. This same thing happens   when we implement onbeforesortchange or onaftersortchanged. If I remove this method , it works fine.  
This issue is happening only in iPad not on desktop. 

Kindly look into this issue

Thanks
Sonu

**Comment by seanlandsman** [comment]
I'm afraid we'll need something from you that reproduces this problem before we can investigate it - we are unable to do so with any of our examples

thanks

**Comment by sonuait135** [comment]
HI , I was able to fix this issue by setting"SuppressTouch" as false. Hence closing this issue
