### ISSUE TITLE
Ag-grid free version

### ISSUE THREAD

**Issue by jindalit** [ceolter/ag-grid#1526]
hi Team,

Can i use Ag-grid free version for one of my commercial application without any enterprise feature. i only required the free features of ag-grid.

Guys please revert me with best suitable answers.

I appropriate ag-grid team for such a wonderful product in Angular 2

regards,
Mayank Jindal

**Comment by seanlandsman** [comment]
Hi,

Yes, you can use the free version commercially provided you dont use any of the enterprise features :-)

thanks

**Comment by KrishnaPG** [comment]
How does one know which are enterprise features and which are not? For example, can we safely assume that everything from this present repository is free, and anything else not in the present repository is enterprise?

**Comment by niranjanpawar7** [comment]
can i use ag-grid for free in my angular commercial project ?

**Comment by seanlandsman** [comment]
@KrishnaPG @niranjanpawar7 

You can use ag-grid-community and any of the framework projects (ag-grid-angular, ag-grid-vue etc) in commercial applications.

You may not use ag-grid-enterprise without purchasing a license.

thanks

**Comment by KrishnaPG** [comment]
Thanks @seanlandsman . That clarifies clearly.
