### ISSUE TITLE
floatingFilterComponentFramework not wiring up correctly due to missing mandatoryMethodList entry

### ISSUE THREAD

**Issue by mjttoogood** [ceolter/ag-grid#1528]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When setting the floatingFilterComponentFramework property of a ColumnDefinition you get a runtime error: '"this.floatingFilterComp.onParentModelChanged is not a function"

StackTrace: 

"TypeError: this.floatingFilterComp.onParentModelChanged is not a function
    at FloatingFilterWrapperComp.onParentModelChanged (http://localhost:3000/scripts/vendor.js:29974:33)
    at HeaderRowComp.createFloatingFilterWrapper (http://localhost:3000/scripts/vendor.js:20709:31)
    at HeaderRowComp.createHeaderElement (http://localhost:3000/scripts/vendor.js:20694:31)
    at http://localhost:3000/scripts/vendor.js:20652:47
    at Array.forEach (native)
    at HeaderRowComp.onVirtualColumnsChanged (http://localhost:3000/scripts/vendor.js:20638:22)
    at HeaderRowComp.init (http://localhost:3000/scripts/vendor.js:20606:14)

**Expected behavior**
The custom floating filter component should render

**Minimal reproduction of the problem with instructions**
There is a solution to this which I have debugged.

The issue is that when wrapping the React component you use ReactFrameworkComponentWrapper from ag-grid-react.  This uses the "mandatoryMethodList" property from ComponentProvider in ag-grid to decide which methods to wireup from wrapper to the custom React component.

Looking at the setup (in componentProvider.js) currently it is:

            textFloatingFilterComponent: {
                mandatoryMethodList: [],
                optionalMethodList: [],
                defaultComponent: floatingFilter_1.TextFloatingFilterComp
            },

The solution is to add 'onParentModelUpdated' to the mandatory method list for every floating filter component.  I have done this in the Chrome debugger at runtime, and this solves the problem.

**What is the motivation / use case for changing the behavior?**
Make the floatingFilterComponentFramework property behave as expected.

**Please tell us about your environment:**

Windows 10, Webstorm, Webpack, Node.js

* **ag-Grid version:** X.X.X
8.2.0

* **Browser:**
Chrome 56.0.2924.87

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.1.4

**Comment by seanlandsman** [comment]
Thanks for reporting - I've raised AG-335 to track this issue our side, but we will update this thread too with updated

**Comment by mjttoogood** [comment]
Thanks a lot Sean.

**Comment by amit-coditas** [comment]
any update on this bug? where can i track the update on AG-355

**Comment by seanlandsman** [comment]
Hi

This has been released as part of 9.0.0 - apologies, you should have received an update here

thanks

**Comment by amit-coditas** [comment]
@seanlandsman , i still see this issue on 9.0 too. 
On the pipeline page, i see this is still in backlog. Can you please help confirm if the fix is in 9.0.

**Comment by seanlandsman** [comment]
I've taken a look again and see whats happened here - I raised AG-335, but in your earlier comment today you mentioned AG-355, which is what I used to look it up.

AG-335 (the correct reference) is still open - I'm afraid I dont have an update for you on this

**Comment by amit-coditas** [comment]
ah thanks, my bad. Hoping for a fix for this soon.

**Comment by saurabhraja** [comment]
I'm facing the same issue. Please update if there is a fix for the same.

**Development environment**

Windows 7, Visual Studio Code, Webpack, Node.js

ag-Grid version: X.X.X
9.0.3

Browser:
Chrome 57.0.2987.133

Language: [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.1.4

**Comment by makinggoodsoftware** [comment]
Hi,

Just to let you know that v10.0.0 has just been released and includes the fix that we discussed in this thread.

Thanks

**Comment by paulkahle** [comment]
I'm getting this issue in 10.0.
this.floatingFilterComp.onParentModelChanged is not a function
at FloatingFilterWrapperComp.onParentModelChanged. 

As described above, when I add  'onParentModelChanged' to the mandatoryMethodList in componentProvider.js it works.

**Comment by yuanjinyong** [comment]
node_modules\ag-grid\dist\lib\componentProvider.js    9.1.0 or 10.0.0

var ComponentProvider = (function () {
    function ComponentProvider() {
    }
    ComponentProvider.prototype.postContruct = function () {
        this.allComponentConfig = {
            dateComponent: {
                mandatoryMethodList: ['getDate', 'setDate'],
                optionalMethodList: [],
                defaultComponent: dateFilter_1.DefaultDateComponent
            },
            headerComponent: {
                mandatoryMethodList: [],
                optionalMethodList: [],
                defaultComponent: headerComp_1.HeaderComp
            },
            headerGroupComponent: {
                mandatoryMethodList: [],
                optionalMethodList: [],
                defaultComponent: headerGroupComp_1.HeaderGroupComp
            },
            setFloatingFilterComponent: {
                **mandatoryMethodList: ['onParentModelChanged'],**
                optionalMethodList: [],
                defaultComponent: floatingFilter_1.SetFloatingFilterComp
            },
            textFloatingFilterComponent: {
                **mandatoryMethodList: ['onParentModelChanged'],**
                optionalMethodList: [],
                defaultComponent: floatingFilter_1.TextFloatingFilterComp
            },
            numberFloatingFilterComponent: {
                **mandatoryMethodList: ['onParentModelChanged'],**
                optionalMethodList: [],
                defaultComponent: floatingFilter_1.NumberFloatingFilterComp
            },
            dateFloatingFilterComponent: {
                **mandatoryMethodList: ['onParentModelChanged'],**
                optionalMethodList: [],
                defaultComponent: floatingFilter_1.DateFloatingFilterComp
            },
            readModelAsStringFloatingFilterComponent: {
                **mandatoryMethodList: ['onParentModelChanged'],**
                optionalMethodList: [],
                defaultComponent: floatingFilter_1.ReadModelAsStringFloatingFilterComp
            },
            floatingFilterWrapperComponent: {
                **mandatoryMethodList: ['onParentModelChanged'],**
                optionalMethodList: [],
                defaultComponent: floatingFilterWrapper_1.FloatingFilterWrapperComp
            },
            emptyFloatingFilterWrapperComponent: {
                **mandatoryMethodList: ['onParentModelChanged'],**
                optionalMethodList: [],
                defaultComponent: floatingFilterWrapper_1.EmptyFloatingFilterWrapperComp
            },
            floatingFilterComponent: {
                **mandatoryMethodList: ['onParentModelChanged'],**
                optionalMethodList: [],
                defaultComponent: null
            },
            filterComponent: {
                mandatoryMethodList: [],
                optionalMethodList: [],
                defaultComponent: null
            }
        };
    };

**Comment by jeffskelton3** [comment]
@yuanjinyong the above _does_ seem to stop the error message from happening but the parent model does not appear to be getting updated when I fire onFloatingFilterChanged(). Not sure why but I was able to get a functional filter action happening via a combination of your suggestion and just updating the filter via the grid api. Gist: https://gist.github.com/jeffskelton3/7ced212868abb59a783eda7726724e21

Hopefully that will help anyone who, like me, has been stuck for a bit. Thanks!!
