### ISSUE TITLE
No provision in first column to prevent drag and pinned 

### ISSUE THREAD

**Issue by jindalit** [ceolter/ag-grid#1531]
No provision in first column to prevent (restrict) drag and pinned 

Thanks,
Mayank Jindal

**Comment by seanlandsman** [comment]
hi

Are you asking for a feature request that prevents dragging and pinning of a column?

**Comment by jindalit** [comment]
Yes

**Comment by seanlandsman** [comment]
You can use the suppressMovable property to prevent dragging of columns

With regards to suppressing pinning, there is no property for this, and isnt something we're likely to add soon I'm afraid
