### ISSUE TITLE
TreeData - Filter is not working for parent/group node.

### ISSUE THREAD

**Issue by shafaqkazmi** [ceolter/ag-grid#1532]
**I'm submitting a ...**  
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Column filter does not work for group nodes

**Expected behavior**
Filter should also consider group nodes. 

**Minimal reproduction of the problem with instructions**
To reproduce this issue, please follow the below steps:
1: Open https://jsfiddle.net/bz01sarw/1
2: Filter in "Group" column
3: Lets suppose you typed "child" in first column, it bring the result
4: You types "group" but no result came.

**What is the motivation / use case for changing the behavior?**
Parent/Group nodes should be part of filtering. 

* **ag-Grid version:** X.X.X
v8.2.0

* **Browser:**
Chrome

**Comment by seanlandsman** [comment]
Filters only work on child rows, not grouped/parent rows I'm afraid

We do have an item open to enhance this, but at this time the behaviour you're seeing is by design

**Comment by shafaqkazmi** [comment]
Since I required this feature so I am changing below code in ag-grid

**Method:** FilterStage.prototype.recursivelyFilter
**Change Set:** Add OR condition __this.filterManager.doesRowPassFilter(childNode)_ at line #: 24665

```
rowNode.childrenAfterGroup.forEach(function(childNode) {
    if (childNode.group) {
        // a group is included in the result if it has any children of it's own.
        // by this stage, the child groups are already filtered
        if (childNode.childrenAfterFilter.length > 0 || **_this.filterManager.doesRowPassFilter(childNode)**) {
            filterResult.push(childNode);
        }
    } else {
        // a leaf level node is included if it passes the filter
        if (_this.filterManager.doesRowPassFilter(childNode)) {
            filterResult.push(childNode);
        }
    }
});
```
