### ISSUE TITLE
Column pinned resize allows to make the unpinned columns unreachable

### ISSUE THREAD

**Issue by manfredArtavia** [ceolter/ag-grid#1533]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When all the visible columns are pinned, the other columns disappear and is impossible to look at them.

**Expected behavior**
Allow the user scroll to the right.
Doesn't allow the user resize more than the visible part of the other columns unpinned.

**Minimal reproduction of the problem with instructions**
Use a grid with a lot of columns.
Pin up all the columns that are currently visible.
See how the other unpinned columns are unreachables.

**What is the motivation / use case for changing the behavior?**
The user experience it's affected because the columns are disappeared and impossible to reach them.

**Please tell us about your environment:**
Windows 7, Atom, Npm, Node.

* **ag-Grid version:** 
6.4.2

* **Browser:**
Chrome 56.0.2924.87 (64-bit) 

* **Language:**  [all | TypeScript X.X | ES6/7 | ES5]
ES6/7

 Styling with Markdown is supported
Submit new issue

**Comment by seanlandsman** [comment]
Hi - we've raised issue AG-340 for this our side. We'll update with any progress as soon as we have any

**Comment by ceolter** [comment]
this has been raised before - but there is nothing we can do. if you pin lots of columns, then yes, you will not be able to scroll horizontally.

can you suggest what it is you expect to happen when you pin to many columns?

(note, i'm going to update the docs to say this is user error)
