### ISSUE TITLE
Menu Filter Icon

### ISSUE THREAD

**Issue by gauravjhs** [ceolter/ag-grid#1534]
I am submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Menu filter icon is only visible when we hover on column header.

**Expected behavior**
Make a flag with which we can set if that Filter icon should be visible at all times to the user. 

**Minimal reproduction of the problem with instructions**
1. [https://www.ag-grid.com/example.php](url)
2. Hover on column header
3. Filter icon is shown

**What is the motivation / use case for changing the behavior?**
We give filter only on specific columns of a table. User should be aware if filters are available and on which columns.

**Please tell us about your environment:**
N/A

    ag-Grid version: 8.0.1
    Browser: ALL
    Language: all

**Comment by seanlandsman** [comment]
Hi - I've raised issue AG-342 for this. We'll update this thread with updates as soon as we have any

**Comment by kevinbull** [comment]
Isn't this available via the suppressMenuHide property?  I use it on my grid and it keeps the menu visible no need to hover to see it.

**Comment by seanlandsman** [comment]
@kevinbull you're quite right - thats exactly what that property's for 

thanks for pointing it out

**Comment by mytee306** [comment]
Example usage

```html
<ag-grid-angular
  [suppressMenuHide]="true"
></ag-grid-angular>
```
