### ISSUE TITLE
Date Filter documentation

### ISSUE THREAD

**Issue by pete-hotchkiss** [ceolter/ag-grid#1535]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Documentation related to applying Date filter models has some errors. Specifically the examples related to the `onFilterChanged` method.

Currently the example listed shows
```
// OR set filter model and update
dobFilterComponent.setModel({
    type:'equals',
    dateFrom:'2008-08-24'
});
dobFilterComponent.onFilterChanged()

```

should this not be

```
// OR set filter model and update
dobFilterComponent.setModel({
    type:'equals',
    dateFrom:'2008-08-24'
});
this.grid.gridOptions.api.onFilterChanged()
```
**Expected behavior**

Documentation to not cause devs to bang heads against wall :-)

**Comment by seanlandsman** [comment]
Hi

Thanks for the feedback - i've  updated this and it'll be reflected in our next release (later this week)

Sorry for the confusion!
