### ISSUE TITLE
Range Copy & Paste parsing bugs

### ISSUE THREAD

**Issue by bonfire-dev** [ceolter/ag-grid#1537]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I've found two issues with copying ranges from and pasting ranges to a grid:

1) When you copy a range from ag-grid to the clipboard, cells containing tabs in the value are not double-quote delimitted, like when doing the same from Excel. If you then paste the copied range, the parser parses the single tab-containing value as multiple values, which changes how many cells are affected by the paste and what values are sent to each cell.

2) If a copied range begins an empty top-left cell and there is only 1 column in the pasted range, then it ignore the first row of the paste entirely and the rest of the rows paste normally. If there are multiple columns in the pasted range, then each value in the first row is shift left by one.

**Expected behavior**
1) I'd expect copying a range to the clipboard would delimit values in double quotes, the same way Excel does.

2) I'd expect the first empty value to be interpreted as an empty value, rather than be ignored.

**Minimal reproduction of the problem with instructions**
1) In ag-grid, make one cell contain a value including a tab. Copy the cell, and paste into the grid. See that the paste interprets it as a range of values.

2) In Excel, copy a range of values such that the top-left cell is empty. Paste into an ag-grid. See that the values land in the wrong cells.

**What is the motivation / use case for changing the behavior?**
In both cases, pasting into the grid can have result in values landing in the wrong cells.

**Please tell us about your environment:**
Mac OSX, Sublime Text 2, NPM

* **ag-Grid version:** X.X.X
7.3 -- I couldn't find references to these bugs in the change logs.

* **Browser:**
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by seanlandsman** [comment]
Hi

I understand your issue here, but most of our users want the "raw" data when copying cells, without us adding information to it. 

If you want to quote items before its made available to the clipboard, you can use the processCellForClipboard callback, where you can then quote/escape etc based on your requirements

thanks
