### ISSUE TITLE
I am trying to use onDragStopped but not successfull in getting the column information

### ISSUE THREAD

**Issue by nithinbv** [ceolter/ag-grid#1547]
I am trying to use onDragStopped but not successfull in getting the column information

 onDragStopped:function(param){
         console.log('Got column event..: ' + param);
       }

**Comment by seanlandsman** [comment]
Please raise support queries either on stackoverflow or our forum: https://ag-grid.com/forum/

The drag events do not contain any information I'm afraid - they're meant to allow users to wait for a drag operation to complete before doing some other action
