### ISSUE TITLE
Get current Column width?

### ISSUE THREAD

**Issue by jogibear9988** [ceolter/ag-grid#1550]
Is there a way to read out the current width of the columns?

**Comment by seanlandsman** [comment]
You can use column.getActualWidth for this

**Comment by jogibear9988** [comment]
thx

**Comment by jogibear9988** [comment]
The API Function seems not to be described in https://www.ag-grid.com/javascript-grid-column-api/#gsc.tab=0

**Comment by gjenner** [comment]
when i change the browser size, which shrinks the column size, the gridSizeChanged event returns the original column width, not the new column width using this.gridOptions.columnApi.getColumn(0).getActualWidth()

**Comment by behnam7171** [comment]
In ag-grid angular, actualWidth is private property. is there another way?

**Comment by gs-amaddi** [comment]
https://www.ag-grid.com/angular-data-grid/column-object/

**Comment by Toscan0** [comment]
> The API Function seems not to be described in https://www.ag-grid.com/javascript-grid-column-api/#gsc.tab=0

use grid APi now: https://www.ag-grid.com/javascript-data-grid//grid-api/#reference-state-getColumnState
columnApi was deprecated
