### ISSUE TITLE
In ragne filtering not working as expected

### ISSUE THREAD

**Issue by chungwong** [ceolter/ag-grid#1551]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
use any demo on this page https://www.ag-grid.com/javascript-grid-filtering/?framework=react#gsc.tab=0
for example, filter `Age` from 23 to 24 it returned nothing
**Expected behavior**

It should return rows matching `Age` from 23 to 24(inclusive)
**Minimal reproduction of the problem with instructions**

* **ag-Grid version:** 8.2.0

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

I believe the cause for this is https://github.com/ceolter/ag-grid/blob/8.2.0/src/ts/filter/baseFilter.ts#L313

With replacing the original line `return compareResult > 0 && compareDateToResult < 0` to `return compareResult >= 0 && compareDateToResult <= 0` it works as expected.

Is this behaviour regarded as `a feature` or a bug?

**Comment by seanlandsman** [comment]
Hi

This has been changed and will be available in the next release

thanks
