### ISSUE TITLE
Multiple Sort Numbers disappear after scrolling 

### ISSUE THREAD

**Issue by hhinch212** [ceolter/ag-grid#1557]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Pin a few columns on the left.  Have enough columns in the grid that you get a horizontal scroll.  Use the multiple sorting feature on unpinned columns, you will see them number.  Now scroll to the right so those columns are no longer visible, then scroll back to the left and you will notice the numbers are gone.

**Expected behavior**
I would expect the numbers to remain.

**Minimal reproduction of the problem with instructions**
Using the demo from the ag-grid site you can duplicate the issues. In your demo I pinned Name, Language, and Country columns, used the multiple sort (shift click) in this order Game name, Bought, Bank Balance.  they were numbered 1, 2, 3, respectively.  Then scroll to the right so they are not visible, and then back left.  The sorting icons are there but the 1, 2, 3 is gone. 

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** 8.2.0

* **Browser:**
Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.3; .NET4.0C; .NET4.0E; rv:11.0) like Gecko"

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"

"Mozilla/5.0 (Windows NT 6.1; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
Hi

I've verified this and raised issue AG-366 for this our side. We'll update this thread with any updates as soon as we can.

thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Just to let you know that this ticket has been released as part of v12. https://www.ag-grid.com/change-log/changeLogIndex.php

Thanks
