### ISSUE TITLE
Type Definitions

### ISSUE THREAD

**Issue by ianmh** [ceolter/ag-grid#1558]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Not sure where to file this, but getNodeChildDetails is missing from gridOptions in definitely typed definition.

**Comment by seanlandsman** [comment]
Thanks for reporting - I've raised issue AG-365 our side to track this, but we'll update this thread too with updates

thanks

**Comment by ianmh** [comment]
I've found another one missing from gridOptions. onGridReady

**Comment by seanlandsman** [comment]
Hi

This has now been corrected - thanks
