### ISSUE TITLE
Set Filter with search terms and unselecting (Select All) doesn't clear all selections

### ISSUE THREAD

**Issue by tystol** [ceolter/ag-grid#1559]
Bug Report

**Current behavior**
On https://www.ag-grid.com/example.php  

1. open the Set Filter on the Country column
2. type 'Ge' into the search field
3. Uncheck Select All
4. Only Argentina and Germany are unselected (the currently visible ones). All other items are still selected.

**Expected behavior**
I expect all items to be unselected. 

**What is the motivation / use case for changing the behavior?**
This allows the user to quickly select what they had narrowed their search down to (eg. in the case above, they can select only Germany after typing in 'ge'). 

* **ag-Grid version:** 
v9.0.0 on https://www.ag-grid.com/example.php

**Comment by makinggoodsoftware** [comment]
Hi,

This is working as intended, that column has the flag selectAllOnMiniFilter set to true, which means that your select all/unselect all works only on the items visible on the set. If this flag was set to false (the default) then it would behave as you expect.

You can see the docs for the set filter here: https://www.ag-grid.com/javascript-grid-filter-set/

Thanks

**Comment by tystol** [comment]
Ah, did not realize that was an option, sorry for the issue noise. And thanks for an amazing product!

**Comment by anatolyzolotar** [comment]
Is there any possibility to rename"Select all" option? It can be confusing if we use selectAllOnMiniFilter : true

**Comment by MikeBombardi** [comment]
That option is no longer available in the docs. Has the name changed?
