### ISSUE TITLE
autoSizeAllColumns not work well on Firefox

### ISSUE THREAD

**Issue by rfps** [ceolter/ag-grid#1561]
On firefox the width of column is calculated on different way. 
The offsetWidth that is used to see the width of the column returns a different value on Firefox. On Chrome, vivaldi...works well.

**Comment by seanlandsman** [comment]
Hi

Thanks for reporting - I've raised issue AG-374 for this our side. We'll update this thread once we have an update for you.

thanks

**Comment by ceolter** [comment]
cannot reproduce.

see image, i went to our demo using firefox, hit 'auto size' button, and it worked.

![image](https://user-images.githubusercontent.com/6539563/26984534-9ffa864e-4d37-11e7-8008-f38cfb672240.png)
