### ISSUE TITLE
Reset columns button lost multi-column sort number

### ISSUE THREAD

**Issue by stevey1** [ceolter/ag-grid#1562]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

This is on multi-column sorting, ag-grid will display column sorting order at column header. But if Reset Columns is clicked, ag-grid refreshes and column sorting order disappears.

**Expected behavior**

Reset Columns is click, ag-grid refreshes and ag-grid should continue display column sorting order 

**Minimal reproduction of the problem with instructions**

1. set order on multiple order, and you will see column sorting number on column header
2. click reset-columns menu item from column main menu, sort number disappears

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

IIS
* **ag-Grid version:** X.X.X

test it on 8.2.0 and 9.0.0

* **Browser:**

Chrome and IE
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES5

**Comment by seanlandsman** [comment]
Hi

Thanks for reporting - I've raise issue AG-375 for this and will update this thread with updates as soon as I can.

thanks

**Comment by ceolter** [comment]
fixed. will be in next release.
