### ISSUE TITLE
gridOptions.paginationAutoPageSize type should be boolean

### ISSUE THREAD

**Issue by elaijuh** [ceolter/ag-grid#1563]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

paginationAutoPageSize type is number, which violates TS compiler
https://github.com/ceolter/ag-grid/blob/master/src/ts/entities/gridOptions.ts#L104
**Expected behavior**

should be boolean
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** 9.0.0

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
Hi

I've raised issue AG-376 for this our side. I'll update this thread with updates as soon as I have any

thanks

**Comment by ceolter** [comment]
this is now fixed.
