### ISSUE TITLE
"format" values when copying

### ISSUE THREAD

**Issue by RodolpheGohard** [ceolter/ag-grid#1570]
**I'm submitting a ...**
```
[x] feature request
```

**Current behavior**
My data contains Date values (javascript Dates).
When copying aggrid cells, then copying to Excel, I got a "raw" toString() serialization like: "Tue Jan 31 2017 01:00:00 GMT+0100 (Romance Standard Time)".

**Expected behavior**
I would like to have a hook/callback to have control over what get copied to Excel, a pasteFormatter or something. I want a convenient output date like 31/01/2017 or 01/31/2017

**What is the motivation / use case for changing the behavior?**
I would like to paste "clean" string dates into Excel and keep actual dates in my data

**Please tell us about your environment:**
Win7 Chrome 50

* **ag-Grid version:** 7.2.0

**Comment by seanlandsman** [comment]
Hi - you can use processCellCallback for this. See https://www.ag-grid.com/javascript-grid-excel/ for more information

thanks

**Comment by RodolpheGohard** [comment]
Hi, thanks for you answer. I'm using Ctrl+C and Ctrl+V to copy paste to Excel, so I'm not mannually calling exportDataAsExcel. Is there a way to wire this callback to Ctrl+C action ?

**Comment by RodolpheGohard** [comment]
Ok, I've found it by debbuging into aggrid source. I used processCellForClipboard callback in gridOptions:

```javascript
    const gridOptions = {
      rowSelection: 'range',
      enableColResize: true,
      groupHeaders: true,
      headerHeight: 40,
      rowHeight: 35,
      paginationPageSize: 25,
      rowModelType: 'virtual',
      enableRangeSelection: true,
      // This doesn't work:
      processCellCallback: params => {
        console.log('processCeelCallback called (gridoptions)', params);
      },
      // This is called any type we hit CTRL C
      processCellForClipboard: params => {
        /* params should look like:
         {
         column: column,
         node: rowNode,
         value: value,
         api: this.gridOptionsWrapper.getApi(),
         columnApi: this.gridOptionsWrapper.getColumnApi(),
         context: this.gridOptionsWrapper.getContext()
         }
         */
        console.log('processCellForClipboard called (gridoptions)', params);
        return moment(params.value).format('DD/MM/YY');
      }
    };
```

**Comment by seanlandsman** [comment]
Hi @RodolpheGohard - great, glad you worked it out

**Comment by rananaresh86** [comment]
Hi @RodolpheGohard ,

Any chance we have this 'processCellCallback' working?

Thanks

**Comment by rananaresh86** [comment]
Hi,

If anyone still has issues with export, please try this:

defaultExportParams: {
    processCellCallback: sanitise,
  },

function sanitise(params){
// return the processed value
}

Thanks
