### ISSUE TITLE
headerCheckboxSelection selectall works Very slow

### ISSUE THREAD

**Issue by safeerk** [ceolter/ag-grid#1573]
Dear, 
        Thanks to the team..
Regarding the header checkbox selection , the select all renders very slow .
If we have a row size of 100-200 columns the select all will take like 10-12 sec to select the full data.
Kindly help me on it.

Thanks Safeer

**Comment by seanlandsman** [comment]
Hi - please provide a plunker or similar so that we can investigate this, as per the issue template

**Comment by safeerk** [comment]
Dear ,
            Mt Coding will be like this:
```
  var columnDef1 = [
                               { headerName: "Service Description", width: 220, field: 'SERVICE_CODE',headerCheckboxSelection: isFirstColumn,checkboxSelection: isFirstColumn},
                               { headerName: "Date", width: 120, field: 'JVM_Date' },
                               { headerName: "Charge", width: 160, field: 'Amount', cellStyle: { 'text-align': 'right' } },
                               { headerName: "Status", width: 140, field: 'STATUS' }
            ]; 
```

So when the header checkbox is checked its taking like 10-12 sec for selection all the checkbox on that table. 

Also in headercheckbox selection you can see isFirstColumn function just to include the name and checkbox in the first column. Please find the function detail below

```
   function isFirstColumn(params) {
                    var displayedColumns = params.columnApi.getAllDisplayedColumns();
                    var thisIsFirstColumn = displayedColumns[0] === params.column;
                    return thisIsFirstColumn;
                }
```

This grid is having setFloatingBottomRowData & paginationPageSize=100

**Comment by huzan123** [comment]
Hi, was there any update to this? I'm tried with Ag-grid Enterprise v21 and 23, have around 300 rows displayed and there is a noticable 10seconds lag when select all is checked.
