### ISSUE TITLE
Grouped row aggregations not updated when filter is changed

### ISSUE THREAD

**Issue by oliyh** [ceolter/ag-grid#1577]
Bug report
 
Steps to reproduce

1. View grid at the bottom of https://www.ag-grid.com/javascript-grid-aggregation/?framework=all#gsc.tab=0
2. Filter the first column “Athlete” to select Michael Phelps
3. Expand all
4. The table shows United States (3) with aggregation 18, 2, 2 and rows for 2008 (8, 0, 0), 2004 and 2012 (see fig 1)
5. Filter the first column again to add Allyson Felix
6. The table shows United States (6) but the aggregations for all group rows are wrong, stuck on the previous value, e.g. totals for 2008 should be (9, 0, 0) but are still (8, 0, 0) – see fig 2

Expected behaviour is that all aggregated values are recomputed each time a filter results in different rows being displayed, so that the values in the aggregation cells are consistent with the data shown in the table.

We have hacked around this by calling `recomputeAggregates` when the `onFilterChanged` event is fired, but it seems like a bug.

Let me know if you need any more explanation.
 
Cheers

Fig 1
![image](https://cloud.githubusercontent.com/assets/2052835/24721872/8919922a-1a39-11e7-9eb8-6be1f162153b.png)

Fig 2
![image](https://cloud.githubusercontent.com/assets/2052835/24721881/8e6b5d76-1a39-11e7-8078-67b8716ddd0e.png)

**Comment by seanlandsman** [comment]
Hi - thanks for reporting this. I've taken a look and can verify that this is a bug. 

I've raised issue  AG-386 our side for this and we'll update this thread with updates as soon as we can

thanks

**Comment by oliyh** [comment]
Thanks @seanlandsman

**Comment by ceolter** [comment]
this is fixed in latest. verified from latest version on our website.

![image](https://user-images.githubusercontent.com/6539563/26969214-d8e470ae-4cfc-11e7-9760-45d66bfdb6dd.png)

**Comment by oliyh** [comment]
Great, thank you very much!
