### ISSUE TITLE
Please add multiline options to row

### ISSUE THREAD

**Issue by Radzhab** [ceolter/ag-grid#1578]
var gridOptions = {
        columnDefs: columnDefs,
       ....
      multiline:true}

i have troubles with it
http://stackoverflow.com/questions/43246606/ag-greed-cell-multiline

**Comment by seanlandsman** [comment]
StackOverflow is the correct place for support queries. Github is reserved for issues or feature requests

**Comment by vikasnawal** [comment]
`.ag-theme-balham .multiline .ag-header-cell-label .ag-header-cell-text {
    text-overflow: clip;
    overflow: visible;
    white-space: normal;
    height: auto;
}
And compute the maximum scrollHeightof all header labels, on some events (onColumnResized, onGridReady):

const MIN_HEIGHT = 25;

function autosizeHeaders(event) {
    if (event.finished !== false) {
        event.api.setHeaderHeight(MIN_HEIGHT);
        const headerCells = document.querySelectorAll('#myGrid .ag-header-cell-label');
        let minHeight = MIN_HEIGHT;
        headerCells.forEach(cell => {
            minHeight = Math.max(minHeight, cell.scrollHeight);
        });
        event.api.setHeaderHeight(minHeight);
    }
}`

**Comment by vikasnawal** [comment]
`const MIN_HEIGHT = 25;

function autosizeHeaders(event) {
    if (event.finished !== false) {
        event.api.setHeaderHeight(MIN_HEIGHT);
        const headerCells = document.querySelectorAll('#myGrid .ag-header-cell-label');
        let minHeight = MIN_HEIGHT;
        headerCells.forEach(cell => {
            minHeight = Math.max(minHeight, cell.scrollHeight);
        });
        event.api.setHeaderHeight(minHeight);
    }
}

(function() {

    document.addEventListener('DOMContentLoaded', function() {

        var gridDiv = document.querySelector('#myGrid');

        var gridOptions = {
            enableColResize: true,
            enableSorting: true,
            onColumnResized: autosizeHeaders,
            onGridReady: autosizeHeaders,
            columnDefs: [
                {
                    headerName: 'Header with a very long description',
                    field: 'name',
                    headerClass: 'multiline'
                },
                {
                    headerName: 'Another long header title',
                    field: 'role',
                    headerClass: 'multiline'
                }
            ],
            rowData: [
                {name: 'Niall', role: 'Developer'},
                {name: 'Eamon', role: 'Manager'},
                {name: 'Brian', role: 'Musician'},
                {name: 'Kevin', role: 'Manager'}
            ]
        };

        new agGrid.Grid(gridDiv, gridOptions);
    });

})();`
