### ISSUE TITLE
Cards View support?

### ISSUE THREAD

**Issue by jogibear9988** [ceolter/ag-grid#1579]
Is it planed to support somthing like a Cards view? 
like https://documentation.devexpress.com/#WindowsForms/CustomDocument3466 or https://documentation.devexpress.com/#WindowsForms/CustomDocument3466

**Comment by seanlandsman** [comment]
Hi

You can achieve something similar if you use cell renderer components in the grid, but we've no plans to introduce something like this in the near future I'm afraid

thanks

**Comment by shshnkjin** [comment]
Any plans to support the kanban view?

**Comment by thimmappa-splashbi** [comment]
Hi @seanlandsman 
Is there any solution for the above problem.

If there is no solution in AG - Grid, Do we have any other solution with example.

**Comment by jogibear9988** [comment]
I use in a Project AGGrid for my Table Views, but I also have a Card view. For this I use https://www.webcomponents.org/element/@polymer/iron-list
So I switch between aggrid or iron-list.

**Comment by jogibear9988** [comment]
We then use https://node-projects.github.io/web-component-designer-demo/index.html as a Designer for the Card Templates, so the customers could modify the layout of the Cards.

**Comment by thimmappa-splashbi** [comment]
@jogibear9988  Need like this https://codepen.io/coldsoul/pen/qNLWBB

**Comment by jogibear9988** [comment]
yes, thats possible with this solution

**Comment by jogibear9988** [comment]
Ours looks like this:
![image](https://user-images.githubusercontent.com/364896/224704380-131ea435-3a41-407e-bb86-099ac03ee20a.png)

we load dynamicly when we scroll down.

and our template in designer looks like this:

![image](https://user-images.githubusercontent.com/364896/224704654-1a40d136-20c8-4b64-ae1c-a8794fc4eccb.png)

**Comment by thimmappa-splashbi** [comment]
Are you using AG-Grid in this?

**Comment by jogibear9988** [comment]
As I said, no not for the cards view. Only for the grid view.

**Comment by alex-bgamestudios** [comment]
Has someone found a solution for this?? 
I'm looking to add a "grid vs row" mode like: 
![image](https://github.com/ag-grid/ag-grid/assets/89936914/abcc3fc0-4e89-493e-b098-1cab869a5a4d)
where it alternates between: 
![image](https://github.com/ag-grid/ag-grid/assets/89936914/8428ca22-e998-4629-a87f-cd26e903c0c9)

**Comment by Dimitri-Habruk** [comment]
> Has someone found a solution for this?? I'm looking to add a "grid vs row" mode like: ![image](https://private-user-images.githubusercontent.com/89936914/287067960-abcc3fc0-4e89-493e-b098-1cab869a5a4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NjA1MDMsIm5iZiI6MTczNTY2MDIwMywicGF0aCI6Ii84OTkzNjkxNC8yODcwNjc5NjAtYWJjYzNmYzAtNGU4OS00OTNlLWIwOTgtMWNhYjg2OWE1YTRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMxVDE1NTAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMGYzODdjYjY0NmQwZGFiY2RhMTQ5OTZmNzY0Y2U5OGQ4YTkyM2NmYzQxMDNmZWI5MDMyMDQ2OTQ5ODFlMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XNMzY5hL7JjIF-CEh8kgwNxpiHCK7JL2K7shcuER1BI) where it alternates between: ![image](https://private-user-images.githubusercontent.com/89936914/287068019-8428ca22-e998-4629-a87f-cd26e903c0c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NjA1MDMsIm5iZiI6MTczNTY2MDIwMywicGF0aCI6Ii84OTkzNjkxNC8yODcwNjgwMTktODQyOGNhMjItZTk5OC00NjI5LWE4N2YtY2QyNmU5MDNjMGM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMxVDE1NTAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNWUwNGYxZWM2Zjc3MjM1Y2MwNTgyYmM2NmRlNTNhYTE0NDFlMmUzNjViYjg5MTNjMjY2MTYzNDhjMTRlNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FKUuucQ5_rRKwCSBlb12G0fgnGTaqYl-zZgDOc-ttQ8)

Did you found any solution?

**Comment by rmadrazo97** [comment]
I found a hacky and dirty solution. 
I can share later 
But in summary, used js to manipulate the DOM and replace with a component.

**Comment by lisinaner** [comment]
> 我找到了一个肮脏的解决方案。 我稍后可以分享 但总而言之，使用 js 来操作 DOM 并替换为组件。

wait

**Comment by cadeParade** [comment]
@rmadrazo97 Any update on this?

**Comment by Dimitri-Habruk** [comment]
finally it's a bad idea, it's better to create a new component and not use aggrid for the card view

> [@rmadrazo97](https://github.com/rmadrazo97) Any update on this?
