### ISSUE TITLE
autoSizeColumns only works with ColDef.field, not with ColDef

### ISSUE THREAD

**Issue by httpdigest** [ceolter/ag-grid#1580]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Calling `gridOptions.columnApi.autoSizeColumns(allColumns);` only works when `allColumns` is an array of `ColDef.field` values, meaning strings which are the `field` values of their respective column definitions.
However, at least the TypeScript typedefinition tells that one can also use an array of ColDef's. However, this does not seem to work as the columns are not being resized anymore. There is also no JavaScript runtime error being thrown.

**Expected behavior**
Column resizing should also work with an array of ColDef being input as the argument to the `gridOptions.columnApi.autoSizeColumns()` method.

**Minimal reproduction of the problem with instructions**
I used the following code (as illustrated by the ag-Grid examples) to resize the columns:
```JavaScript
      onGridReady: () => {
        const allColumnIds = [];
        this.gridOptions.columnDefs.forEach((columnDef) => {
            allColumnIds.push(<ColDef>columnDef);
        });
        this.gridOptions.columnApi.autoSizeColumns(allColumnIds);
      },
```
This will not resize the columns.

**What is the motivation / use case for changing the behavior?**
Being able to automatically resize the columns even when they do not have a `field` attribute value, such as with computed properties via the `valueGetter` property.

**Please tell us about your environment:**
Windows 7 x64, Node 7.8.0, npm 4.5.0, Angular 4.0.1

* **ag-Grid version:** 9.0.0

* **Browser:**
Chrome 57.0.2987.133 (64-bit)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.2.2

**Comment by seanlandsman** [comment]
Hi

Thanks for reporting this - I've raised issue AG-395 our side to track this. We'll update this thread with updates as soon as we can.

thanks

**Comment by ceolter** [comment]
the method should take an array of col id's. these are strings.

see the docs on id's
https://www.ag-grid.com/javascript-grid-column-definitions/

do not pass in col defs.

**Comment by httpdigest** [comment]
> the method should take an array of col id's. these are strings.

I know that. Please carefully read the initial post:

> However, at least the TypeScript typedefinition tells that one can also use an array of ColDef's. However, this does not seem to work as the columns are not being resized anymore.

**Comment by ceolter** [comment]
yes, the colDef is in there. that's historic. we will be removing that soon because of this issue. however the solution for your application is to use the id's.

the codDef's used to work, as the column contained a reference to the original colDef, however since we implemented defaultColDef (it's a grid option), the colDef is now merge of both the default and the actual, thus it's a new colDef that the column contains. so comparing by colDef reference doesnt' work anymore.

sorry for the confusion.

**Comment by ceolter** [comment]
internally we have renamed our jira
AG-395 drop colDef from the colKey

**Comment by httpdigest** [comment]
Thank you!
