### ISSUE TITLE
How to distinguish onCellClick and onDragStopped

### ISSUE THREAD

**Issue by ydpai3** [ceolter/ag-grid#1581]
onDragStopped ($event){
        this.savePreference( 'fieldsOrder' );
        this.setSameState();
    }
When I want to click But trigger onDrag 
How should i do？

**Comment by seanlandsman** [comment]
Hi - please post support queries either on stackoverflow or on our free forum: https://ag-grid.com/forum/forumdisplay.php?fid=4

Github is reserved for issues or feature requests only
