### ISSUE TITLE
Full width row does not scroll in touch device

### ISSUE THREAD

**Issue by ThaiGT** [ceolter/ag-grid#1585]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The full width row example [https://www.ag-grid.com/javascript-grid-full-width-rows/exampleFullWidthComponent.html](url) works perfectly in computer. 
When I try it on the touch device, it doesn't scroll, if I touch and hold my finger on the full width row and try to scroll. 
The grid scroll normally if I hold my finger on the normal row.

**Expected behavior**

The example in ag grid website [https://www.ag-grid.com/javascript-grid-full-width-rows/exampleFullWidthComponent.html](url)

**What is the motivation / use case for changing the behavior?**

We use the full width row to display more detail for each device in out web page. The user may access the page with computer or mobile device

**Please tell us about your environment:**

Linux, 

* **ag-Grid version:** X.X.X

* **Browser:**

Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by seanlandsman** [comment]
Hi

I've raised issue AG-425 for this our side - we'll update this thread with updates as soon as we have any.

thanks

**Comment by ceolter** [comment]
if you set embedFullWidthRows=true, this will fix the problem. see docs for what embedFullWidthRows does.

**Comment by ThaiGT** [comment]
It works. Thanks
