### ISSUE TITLE
Introduce locked columns

### ISSUE THREAD

**Issue by ha-decodeit** [ceolter/ag-grid#1591]
**I'm submitting a
```
[X] feature request
```

**Current behavior**
Currently it is not possible to have a pinned column at the very left / right and prevent other columns from being dragged before / after them.

**Expected behavior**
It should be possible to have a _lockedIndex_ column configuration property which prevents other columns from being moved before / after them. The _lockedIndex_ property should be available for columns having the _pinned_ property set to either left or right. It should expect an integer defining the position (from left to right) among other locked columns.

I.e. A column having  _pinned_ set to _left_ and _lockedIndex_ set to _1_ should be at the very left edge of the grid. It should not be possible to drag any other column to the left of the _pinned_ column.
Additionaly, _lockedIndex_ columns should not be move-able by the user (like setting the _suppressMovable_ property to _true_).

**What is the motivation / use case for changing the behavior?**
In our application, we have a pinned menu column that should be at the very left side, and users should not be able to drag this column or any other columns before it.

**Comment by randdusing** [comment]
You can always do something like this. Anytime a column is moved, I ensure these two columns are pinned to the far left.

```javascript
onDragStopped = function () {
  columnApi.moveColumn('treeData', 0);
  columnApi.moveColumn('selection', 1);
};
```

**Comment by ceolter** [comment]
this is a duplicate.
https://github.com/ceolter/ag-grid/issues/853

also tracked by AG-121
https://www.ag-grid.com/ag-grid-pipeline/
