### ISSUE TITLE
setDataValue does not update aggrageted value

### ISSUE THREAD

**Issue by Vizer** [ceolter/ag-grid#1592]
**I'm submitting a**
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
After applying grouping and default  sum aggregation  updating cell value using `rowNode.setDataValue(colId, newValue)` aggregated value remains old.

**Expected behavior**
Aggregated value should be updated 

**Minimal reproduction of the problem with instructions**
[Here ](https://plnkr.co/edit/wm7td2gYBgeGXffUKnwk?p=preview) is quickly updated plunker(timeout in `group-row-renderer.component.ts`)

* **ag-Grid version:** 9.0
* **Language:** TypeScript 2.1.4

**Comment by seanlandsman** [comment]
hi

If you call this.gridOptions.api.recomputeAggregates(); after your update the value it should do what you want it to do

thanks
