### ISSUE TITLE
Release Date/version of Enterprise rowModalType

### ISSUE THREAD

**Issue by upendrata** [ceolter/ag-grid#1594]
Hi Team,

Had a look into enterprise rowModalType and this feature is dam good, would like to know the ETA on enterprise rowModalType full release as it currently in Development state

Thanks in Advance

**Comment by seanlandsman** [comment]
hi

Thanks for the feedback - the ETA for this is in the next few weeks, keep an eye out on ag-grid.com, but as I say it should be released within the next 2-4 weeks

thanks
