### ISSUE TITLE
empty "Date" quick-filter causes exceptions

### ISSUE THREAD

**Issue by sbublava** [ceolter/ag-grid#1600]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

- open http://plnkr.co/edit/faZcqRAIh1xp1ZdtlnE8
- click the quick filter input field

There is an exception in BaseFilter.onFloatingFilterChanged(). The call to BaseFilter.setModel() fails, because "casted" is null. 

BaseFilter.prototype.onFloatingFilterChanged = function (change) {
	        //It has to be of the type FloatingFilterWithApplyChange if it gets here
	        var casted = change;
	        this.setModel(casted.model);
	        this.doOnFilterChanged(casted.apply);
	    };

This might be a duplicate of / the same underlying bug as https://github.com/ceolter/ag-grid/issues/1549.

**Expected behavior**

no exceptions

* **ag-Grid version:** 9.0.0

* **Browser:** IE 11

* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi, thanks for raising this, there is a ticket AG-382, this will be available in the next release
