### ISSUE TITLE
which event tells me that grid has finished loading? 

### ISSUE THREAD

**Issue by sahilgandhi15** [ceolter/ag-grid#1602]
which event tells me that grid has finished loading.?
i tried onGridready() but it fires during loading. i need an event which fires after everything is loaded.

**Comment by seanlandsman** [comment]
Hi

gridReady should fire when the data has been set if using gridOptions.rowData. If you're using api.setRowData you'll need to use rowDataChanged instead

Please dont use github for support queries - use either our free forum or stackoverflow. Github is reserved for issues only

**Comment by SergioPrats1** [comment]
rowDataChanged no longer exists https://www.ag-grid.com/react-data-grid/grid-events/.
