### ISSUE TITLE
 Cannot read property 'api' of null 

### ISSUE THREAD

**Issue by pdvbalaji** [ceolter/ag-grid#1604]
Hi,
 I am using ag-grid ,when I want to cancel the grid when loading I used  this.gridOptions.api.destroy();
it was giving error  Cannot read property 'api' of null .
Can u help me about this issue 

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
Please dont ask for support in github - please use stackoverflow or our members forum for support
