### ISSUE TITLE
In ag-grid can we add link in overlayLoadingTemplate options

### ISSUE THREAD

**Issue by pdvbalaji** [ceolter/ag-grid#1605]
HI ,

 I am using ag-grid , I want to added link in overlayLoadingTemplate to cancel the loading of the grid 
example : 
this.gridOptions.overlayLoadingTemplate =' <a href="#" target="_blank" (click)="stopLoadingGrid()" >Cancel...</a > ';

But Unable to Click cancel 
please help me how can i do

**Comment by seanlandsman** [comment]
Please dont ask for support in github - please use stackoverflow or our members forum for support
