### ISSUE TITLE
Shift+click to select multiple results selects additional text in IE

### ISSUE THREAD

**Issue by basvandenberg** [ceolter/ag-grid#1613]
**I'm submitting a bug report**

**Current behavior**
If you open the [multi-select example](https://www.ag-grid.com/javascript-grid-selection/?framework=all#multiRowSelectionExample) in Internet Explorer (I used 11) and select multiple rows using Shift+click, the table rows are selected as expected, but also all header texts and the text row above the table is selected. 

The behavior can be very different. There are cases where all texts in the table are selected, but it also happens that all text content on the page is selected up until the ag-grid, .

**Expected behavior**
No text content should be selected at all, only the ag-grid rows.

**Please tell us about your environment:**
Observed with Windows 7, IE 11.

* **ag-Grid version:** 8.1.1

* **Browser:** IE

* **Language:** TypeScript 2.0.10

**Comment by seanlandsman** [comment]
Hi

That's the browser doing text selection, what happens on any webpage when you hold down ctrl and click twice

You'll need to disable this with CSS - see here: http://stackoverflow.com/questions/826782/how-to-disable-text-selection-highlighting-using-css for more information

thanks

**Comment by basvandenberg** [comment]
Hi,

Thanks for the quick response. 

I also found this on stackoverflow, but this doesn't work when applying this CSS property to the ag-grid element. This only works if you set the CSS property for [the entire body](http://stackoverflow.com/questions/38220880/shift-row-selection-in-ag-grid-in-internet-explorer-selects-additional-text), which means that you cannot select any text in the entire web application. Globally disabling text selection is no option in our case, and I guess in many cases.

It would be very nice if ag-grid could somehow prevent this text selection in Internet Explorer. I noticed that many other data table libraries show the same behavior, but for example [handsontable](https://handsontable.com/examples.html?headers) seems to somehow prevent the text selection in IE.

**Comment by SmoooZ** [comment]
+1

**Comment by karanbabariya** [comment]
Hi @basvandenberg ,

I am also facing the same issue. Did you find any workarounds for the same?
It turns out to be very annoying at times. I also tried the css fix, but it gave no help.

Thanks

**Comment by arunkotagiri** [comment]
@basvandenberg @seanlandsman @ceolter 
Do we have any fix for this ?

**Comment by nasaleanhorea** [comment]
hey , just add window.getSelection().removeAllRanges(); on the OnRowSelected event
