### ISSUE TITLE
Incorrect column width when using React Material Drawer

### ISSUE THREAD

**Issue by nikitaulshin** [ceolter/ag-grid#1618]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Hello.
I'm using ag-grid-react with [react-material-ui](https://github.com/callemall/material-ui).
I'm using Drawer component and 100% width ag-grid.
When I toggle the Drawer, grid' columns get resized without any events/callbacks/etc (they become narrower ).

**Expected behavior**

Columns should not be resized when I toggle th Drawer.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Ubuntu 16.04, WebStorm, NPM, Webpack

* **ag-Grid version:** X.X.X

9.1.0

* **Browser:**

google Chrome Version 57.0.2987.133 (64-bit)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by seanlandsman** [comment]
As per the issue template please provide a plunker or similar for us to investigate.

We do not have experience with react-material-ui and I'm afraid we dont have the time trying to create a working example with this
