### ISSUE TITLE
Quick Filter Not Working

### ISSUE THREAD

**Issue by mindnervestech** [ceolter/ag-grid#1619]
api.setQuickFilter(quickFilter) not working when my gridOtions have rowModelType: 'infinite'
it gives error ag-grid: cannot do quick filtering when doing virtual paging

**Comment by seanlandsman** [comment]
Quick filter is not supported with this model type, as per the docs here: https://www.ag-grid.com/javascript-grid-filter-quick/

> Server Side Data
> Quick Filters only make sense with client side data (i.e. when using the In Memory row model). For > the other row models (pagination, infinite scrolling etc) you would need to implement your own server side sorting to replicate Quick Filter functionality.

thanks

**Comment by v-lukoyanov** [comment]
Hello. 
Is any workaround to run quick filter with server side model?
It was not described in Docs...
