### ISSUE TITLE
Grouping combined with FullWidthRenderer

### ISSUE THREAD

**Issue by asdkalluri** [ceolter/ag-grid#1631]
I'm testing out the Enterprise version which has the cool "Grouping" feature using the `rowGroupIndex`.
However when I try to add a `fullWidthRenderer `to one of the columns (like I used to with the Free Version),  providing all these props,

>  isFullWidthCell={this.isFullWidthCell}
>  fullWidthCellRendererFramework={MyComponent}
>  getNodeChildDetails={this.getNodeChildDetails}
>  getRowHeight={this.onGetRowHeight.bind(this)}

only the `FullWidthRenderer `takes precedence and the Grouping is never seen.
Is this expected behaviour?
I'd like certain Grouped Rows and then I'd like to apply the FullWidthRenderer

**Comment by seanlandsman** [comment]
Hi,

For enterprise support please contact accounts@ag-grid.com who will be able to give you access to the Members Forum ( https://ag-grid.com/forum/forumdisplay.php?fid=5 ) even if you're only trialling ag-Grid Enterprise.

The Members Forum is staffed by a team who will be able to assist you further with your enqury.

thanks
