### ISSUE TITLE
Custom checkbox column definition is firing a sort event when suppressSorting is true (only on mobile device)

### ISSUE THREAD

**Issue by TimmyGChi** [ceolter/ag-grid#1639]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
clicking on checkbox header is firing the sort event

**Expected behavior**
check all the rows in the grid

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X
ag-grid 8.2.0
ag-grid-angular 8.2.0

* **Browser:**
iPad pro

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
Hi

I've raised issue AG-478 for this our side - we'll update this thread with any updates when we have any

thanks

**Comment by ceolter** [comment]
i have just checked the latest release v10.1 on iPad pro and cannot reproduce.

i went to www.ag-grid.com/example.php on an iPad pro and was able to click the checkbox in the header to select all rows. it worked fine. tapping outside of the checkbox didn't select the checkbox.
