### ISSUE TITLE
How to target richSelect values for specific row?

### ISSUE THREAD

**Issue by kvanlaan** [ceolter/ag-grid#1641]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I cannot figure out how to target the richSelect values for a specific row. As far as I now the richSelect values are set in the cellEditorParams.values for the specific columnDef. However i would like each row to have a different filtered set from a common value list.

**Expected behavior**

A way to set the values for a richSelect field on different rows.
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Mac, VS Code
* **ag-Grid version:** X.X.X

Latest
* **Browser:**

Chrome
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by seanlandsman** [comment]
For enterprise support, please raise them on our Members Forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5

thanks
