### ISSUE TITLE
Update value directly in the main component whenever user changes a value from an input field inside the cellRendererFramework component.

### ISSUE THREAD

**Issue by saurabhraja** [ceolter/ag-grid#1645]
In my grid, one of the columns is rendered by a component using cellRendererFramework. This component has an input field whose value is editable. The text field will have an initial value which is received through params inside the component. My requirement is to update the original array residing in the main component whenever user changes the value from the cellRendererFramework component.

**Current behavior**
Here, I'm able to access the parent component value inside my cellRendererFramework component using the params.

```
agInit(params: any): void {
    this.params = params;
}
```
**Expected behavior**
The cellRenderer component has an input text field which will initially have a value from params. This value can be changed by the user and that change should reflect in the original params object in parent component. One solution which I can think of is using an observable for checking changes but I think it would cost me on performance as I'll be pushing value on every key press. Please let me know if there's any built in functions in ag-grid api to achieve this.

```
<div>
  <input type="text" [(ngModel)]="value">
</div>
```

**Environment:**
Operating system : Windows 7
Code editor : Microsoft visual studio code
Package manager : npm

* **ag-Grid version:** 
v9.0.3

* **Browser:**
Google chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
Please raise support queries either on our members forum (https://ag-grid.com/forum/forumdisplay.php?fid=5) or on stackoverflow.

Github is reserved for issues or feature requests
