### ISSUE TITLE
 Saving State of ag-grid

### ISSUE THREAD

**Issue by PrasadNaidu** [ceolter/ag-grid#1648]
Here is the below code i am using to set state of the ag-grid
 Saving State of ag-grid:      
initializeGrid() {
        this.gridOptions = <GridOptions> {
            enableServerSideSorting: true,
            enableServerSideFilter: true,
            rowModelType: 'pagination',
            paginationPageSize: this.pageSize,
            onGridReady: () => {
                this.createDataSource(this.providersListService);
                this.staticDataService.gridState=JSON.stringify(this.gridOptions.columnApi.getColumnState());
                this.staticDataService.gridFiler=JSON.stringify(this.gridOptions.api.getFilterModel());
                this.staticDataService.gridSorting=JSON.stringify(this.gridOptions.api.getSortModel());

            }

        };

Reading a State of  ag-grid:
var sortDef=this.staticDataService.getGridState();
        var filterDef=this.staticDataService.getGridFilter();
        var stateDef=this.staticDataService.getGridState();
        if (sortDef != null)
        this.gridOptions.columnApi.setColumnState(this.staticDataService.getGridState());
        if (filterDef != null)
        this.gridOptions.api.setFilterModel(this.staticDataService.getGridFilter());
        if (stateDef != null)
        this.gridOptions.api.setSortModel(this.staticDataService.getGridSorting());

I am getting below error on reloading or refreshing grid for new filter or sorting scenario,

TypeError: columnState.forEach is not a function
    at ColumnController.setColumnState (columnController.js:922)
    at ColumnApi.setColumnState (columnController.js:47)

Can one please help me to fix this issue

**Comment by PrasadNaidu** [comment]
having an issue while setting columnState as below
this.gridOptions.columnApi.setColumnState

**Comment by seanlandsman** [comment]
Please don't post support requests here - use either the members forum (https://ag-grid.com/forum/forumdisplay.php?fid=5) or stackoverflow for this

**Comment by rtvalluri** [comment]
Parsing the restored column state solved the issue.
this.gridOptions.columnApi.setColumnState(JSON.parse(this.staticDataService.getGridState()));
