### ISSUE TITLE
Broken image on example page

### ISSUE THREAD

**Issue by AmitMY** [ceolter/ag-grid#1650]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
> GET https://www.ag-grid.com/excel_error.png/ 404 (Not Found)
On https://www.ag-grid.com/javascript-grid-excel/#exportToXlsx&gsc.tab=0

**Expected behavior**
Not a broken image

**Comment by seanlandsman** [comment]
Thanks for reporting - I've fixed this now
