### ISSUE TITLE
AG Grid Floating filter clear button

### ISSUE THREAD

**Issue by re5ive** [ceolter/ag-grid#1653]
Hi,

can we have the clear button outside the drop meun? 

something like just input and a button to clear for react?

and also i cannot find a document for react to custamize the floating filter.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

The docs for React are not there yet, you are right, this is still supported though, al you need to do is to register your component as usual in the framework property, and add the methods specified in the docs.

If you want to customise the button outside of the drop menu, you will have to create a custom filter, and possible a custom header (if you want to put the button in the header)

**Comment by re5ive** [comment]
Hi,

thank you for your reply, what i did below..

i add this button inside the render func 
<i onClick={this.clearFilters.bind(this)} className="clear--all--filter sapUiIcon si-decline"></i>


and the clear func

clearFilters() {
        this.grid.api.setFilterModel(null);
        this.grid.api.onFilterChanged();
    }

now its working fine. :)

**Comment by stephan-fischer** [comment]
@re5ive  can you please provide the full code?
