### ISSUE TITLE
Infinite scrolling: can't change cache block size

### ISSUE THREAD

**Issue by sbublava** [ceolter/ag-grid#1655]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have a table that uses pagination with infinite scrolling. According to https://www.ag-grid.com/javascript-grid-infinite-scrolling/#pagination infinite block size must not be smaller than pagination page size.

Therefore I adjust gridOptions.cacheBlockSize before calling gridOptions.api.paginationSetPageSize() to ensure that both values are identical.

This has no effect. My datasource is still called with parameters that match the old block size.

**Expected behavior**

After changing cacheBlockSize, additional calls to the installed data source need to use the new value when calculating startRow and endRow.

It must be possible to change cache block size in order to compensate changes to pagination page size.

Maybe changing pagination page size should change cache block size as well, if it is smaller than the new page size.

**Minimal reproduction of the problem with instructions**

Open https://plnkr.co/edit/IeFmBsyL3pqcqdBjdsKK and change the page size from 5 to 10. You'll see a number of alerts that prove that data is still requested 5 rows at a time.

**Please tell us about your environment:**

* **ag-Grid version:** 10.0.0
* **Browser:** IE 11
* **Language:** TypeScript

**Comment by makinggoodsoftware** [comment]
The correct name of the property if infiniteBlockSize, Ill recommend you to use the members forum for this questions though.

Thanks

**Comment by sbublava** [comment]
You are mistaken. The property was renamed for version 10.0. See https://www.ag-grid.com/change-log/changeLogIndex.php.

**Comment by cliffsun91** [comment]
There is a definitely a bug (when using AgGrid React at least) - gridOptionsWrapper.ts provides a getter getCacheBlockSize() which returns this.gridOptions.cacheBlockSize, however copyAttributesToGridOptions() in ComponentUtils.ts (used by AgGridReact) copies only 'known' grid options but in the NUMBER_PROPERTIES array it's still known as 'infiniteBlockSize'.

As a result you can't change the block size at all in the infinite row model. If you pass the prop 'cacheBlockSize' Ag Grid throws it away as it doesn't recognise it as a valid grid option, but if you pass in the prop 'infiniteBlockSize' then it gets passed in as a grid option but infiniteRowModel.ts is now referencing 'cacheBlockSize' which it thinks is undefined.

This needs to be fixed as it's preventing us from migrating from AgGrid version 9 to 11 whilst maintaining the server side pagination/sorting functionality we need.

**Comment by Shadrongowes** [comment]
I am also using AgGrid React and the Enterprise model, we set the this.gridOptions.cacheBlockSize property and then bind the AgGrid component to onGridReady. In the onGridReady function we call console.info and output the grid object to console. There is no visible cacheBlockSize property, agGrid is just throwing the property away.

**Comment by cliffsun91** [comment]
I've created a pull request here which should fix the issue: https://github.com/ceolter/ag-grid/pull/1734
