### ISSUE TITLE
Drag and drop ghost element stuck when touch dragging into pinned area

### ISSUE THREAD

**Issue by ha-decodeit** [ceolter/ag-grid#1656]
**I'm submitting a ...** 
```
[X] bug report
```

**Current behavior**
If a custom react header renderer is provided via _headerComponentFramework_, the drag and drop ghost element gets stuck when trying to move a column into the pinned area or vise versa. This bug only happens on touch devices or when enabling touch emulation in the chrome dev tools. If no custom header renderer is used, everything works as expected.

**Expected behavior**
When using a custom header renderer, moving columns via touch should work the same way as with mouse input.

**Minimal reproduction of the problem with instructions**
As I could not find a bundled version of ag-grid-react to show an online example, I put together a small gist that demonstrates the bug. In this example, dragging a column into the left pinned area causes the drag and drop ghost to be stuck and the move event to be canceled on touch devices / touch emulation. 
[Link to the gist](https://gist.github.com/ha-decodeit/b5a06b325cf197797265500e2f73e282)

![spectacle m20008](https://cloud.githubusercontent.com/assets/4749930/26391599/b63e48ae-4063-11e7-91c5-27776c27c85d.png)

**What is the motivation / use case for changing the behavior?**
Our application needs to support mobile devices as well as a custom header renderer.

* **ag-Grid version:** 
10.0.0 (Also tested with version 8.2.0 and 9.x.x)

* **Browser:**
Chrome 58 (With device emulation enabled)
Latest mobile Safari

* **Language:** 
Typescript 2.3.2

**Comment by makinggoodsoftware** [comment]
There is a ticket to track this:

AG-489

Will update this thread as soon as the fix is available

**Comment by kiril-matev** [comment]
Hi @ha-decodeit!

I just wanted to follow up on this issue.

The issue you've described doesn't appear when using AG Grid v27.3.

Please follow the steps below **on a touch device**:
1. Open
https://plnkr.co/edit/kF74O6pd9Iw0PBhY?open=index.jsx
**Actual**: COUNTRY column pinned
2. Tap and hold, then drag the YEAR column header to the pinned area
**Actual & Expected**: YEAR, COUNTRY column pinned
3. Tap and hold, then drag the YEAR column header back into the unpinned area
**Actual & Expected**: COUNTRY column pinned, YEAR column unpinned

Please upgrade to this new version of AG Grid if needed to resolve this issue.
