### ISSUE TITLE
The filter text removed if we setColumnDefs

### ISSUE THREAD

**Issue by ahmed-saber** [ceolter/ag-grid#1661]
**I'm having an issue with ag-grid the text for my column filter get's cleared if I set the columns using this method setColumnDefs, my columns have this below option :

```
filterParams = {
    newRowsAction: 'keep'
};
```

**Current behavior**

The filter text removed

**Expected behavior**

To keep the filter text

**Minimal reproduction of the problem with instructions**

Apply the grid option using html template and get whatever data from remote server and bind the columns and rows to the grid using the API methods.

**What is the motivation / use case for changing the behavior?**

None

**Please tell us about your environment:**

Windows 8, Visual studio code, Webpack, Aurelia

* **ag-Grid version:** X.X.X

ag-grid:**8.1.1**
ag-grid-aurelia:**8.1.0**

* **Browser:**

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by makinggoodsoftware** [comment]
Hi I have tried this in our examples right now and seems to be working, can you please see if you can reproduce it there or send us a plunkr.

https://www.ag-grid.com/javascript-grid-filter-set/

Thanks
