### ISSUE TITLE
onBeforeSortChanged isnt called anymore, regrission on 10.0

### ISSUE THREAD

**Issue by MrFrankel** [ceolter/ag-grid#1662]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
onBeforeSortChanged Is not being called when sorting

**Expected behavior**
onBeforeSortChanged should be called on sorting

* **Browser:** chrome

* **Language:** TypeScript

**Comment by makinggoodsoftware** [comment]
Hi,

Since 10.0.0 onBeforeSortChanged is not used anymore, you can listen to onFilterChanged and it should keep the same logic as it was using before.

**Comment by MrFrankel** [comment]
@makinggoodsoftware subscribing to onBeforeFilterChanged or to onFilterChanged doesn't trigger when grid column is sorted...
