### ISSUE TITLE
Align arguments of Cell-Renderers

### ISSUE THREAD

**Issue by kleinerroemer** [ceolter/ag-grid#1663]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently, if a column has a _valueGetter_ and _filterParams: {cellRenderer: params => ...}_, the _cellRenderer_ gets passed a _params_ object consisting of only one property named _value_ that is set to the value returned by the value getter.

**Expected behavior**
As described [here](https://www.ag-grid.com/javascript-grid-filter-set/?framework=all#gsc.tab=0), expected behavior would be to get passed the same object as a cell renderer gets passed.

**Minimal reproduction of the problem with instructions**
Create a column config with one column containing a _valueGetter_ and a _filterParams: {cellRenderer: ....}_

**What is the motivation / use case for changing the behavior?**
If grouping has to be based on a certain value (returned by the value getter e.g. the _id_ of an object), but filtering has to be done on the rendered value (e.g. the _name_ of an object), this is currently not possible

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X
10.0.0

* **Browser:**
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.3

**Comment by makinggoodsoftware** [comment]
Hi,

I am confused, I think there a few things mixed up here you mention valueGetters, filterParams and cellRenderers but they are independent from each other, you are linking our setFilter docs.

Can you be more specific or provide a reproducible plunkr

Thanks.

**Comment by kleinerroemer** [comment]
Please have a look at [this example](https://jsfiddle.net/mgpk6t18/2/).
As you can see:

- the _cellRenderer_ gets called with a complex object containing the whole data structure (not possible to log this to the console due to circular json structure)
- the _filterParams.cellRenderer_ gets called with an object containing only a value property, nothing more.

Therefor, it is not possible to filter for the rendered values.

**Comment by makinggoodsoftware** [comment]
Hi,

I can see now what you are talking about, you are right this is a bug we have created the ticket AG-497 to track this so you will receive as a parameter both the value after valueGetter if specified and the original value from your rowData.

This will be available from the next release, we will let you know once that is available

**Comment by makinggoodsoftware** [comment]
Hi upon revisiting this issue I should refine my previous answer.

I don't think there is anything we can do about this, we have changed the docs so that this is clear:

The new docs for the setFilter will be changed to:

cellRenderer: Similar to the cell renderer for the grid (you can use the same one in both locations).
            Setting it separately here allows for the value to be rendered differently in the filter. Note that
            the cellRenderer for the setFilter only receives the value as a parameter, as opposite to the cellRenderer
            in the colDef that receives more information.

We use value getters to build the list of the set filters, and then we create a unique list, and then we delegate in the setFilterParams cellRenderer

I am afraid we don't support this..

I think we could help you if you would share what you are trying to achieve here..

Thanks

Unfortunately I am going to close 497
