### ISSUE TITLE
Master Detail does not work with infinite row model

### ISSUE THREAD

**Issue by gregbown** [ceolter/ag-grid#1667]
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Taking a working master detail example and switching the row model to infinite causes the controls for expanding rows to be hidden. In addition, the node method setExpanded(boolean) is absent so no programmatic control of expanding the row is possible.

**Expected behavior**
As per the documentation "It is possible to use fullWidth with any of the row models"
[https://ag-grid.com/javascript-grid-master-detail/?framework=all#using-fullwidth-with-pagination](url)

**Minimal reproduction of the problem with instructions**

**With infinite row model (does not work)**
[https://plnkr.co/edit/dXAUDm?p=preview](url)

**With pagination row model (works)**
[https://plnkr.co/edit/MI29es?p=preview](url)

**What is the motivation / use case for changing the behavior?**
The expanding row feature was one of the primary reasons for selecting ag-grid
The documentation suggests that if doing server side pagination, switching to the infinite row model is best, however; this breaks functionality?
[https://ag-grid.com/javascript-grid-pagination/index.php#gsc.tab=0](url)

**Please tell us about your environment:**
Windows 10, Chrome Version 56.0.2924.87, Angular 4.2.0-rc.0, Typescript 2.3.3, Webpack 2.6.0, Node 6.9.1, npm 4.0.2, ag-Grid 10.0.1, ag-Grid Angular 10.0.0

In addition:
Will switching to the Viewport Row Model Enterprise solve the isssue?
There is no clear direction on if the pagination row model is deprecated?  It appears to be extended by the other row models?

**Comment by seanlandsman** [comment]
You cannot use master/detail with infinite row model due to the nature of the infinite row model.

You can however use the Enterprise Row Model for lazy loading of child nodes, but this is an Enterprise feature and requires a license

See https://www.ag-grid.com/javascript-grid-enterprise-model/ if this might be of interest

thanks

**Comment by gregbown** [comment]
Thank you Sean,

I switched to the enterprise row model, however; there is little consistency in instantiating the full width detail rows across models.  The method setExpanded is present however the getFullWidthCellRenderer and getNodeChildDetails are never called and the detail is never rendered.  In fact the ag-full-width-viewport and its container remain an empty dom element. Adding cellRenderer: 'group' to the column configuration does nothing. There is no documentation explaining what is required to achieve a full width detail row with the enterprise row model.

Somewhat related; I tried to use my enterprise key in a plnkr in order to share the issue but it seems to never validate the key.

**Comment by seanlandsman** [comment]
Apologies I missed your follow up Greg - will respond to your forum issue now

**Comment by ashishupadhyay** [comment]
hey guys,
I have the trial version of ag-grid-enterprise. I was trying to implement the master/detail for server side but got to know it is not supported. I checked the enterprise row model grouping and tree data as well but I'm not sure how to implement something where i can show a table in the child row just like in master/detail?

**Comment by juminoz** [comment]
I'm also looking into implementing master/detail for server side row model and the expand row doesn't seem to be working and the custom cell renderer never gets called. @ashishupadhyay Where did you see that this is not supported?

**Comment by seanlandsman** [comment]
@juminoz master/detail in server side row model isn't currently supported - but! - it will be in the next release, scheduled for this month

**Comment by ashishupadhyay** [comment]
@juminoz - Go to this link [.](https://www.ag-grid.com/javascript-grid-master-detail/) The last topic is Supported Modes, you'll find it there.

@seanlandsman - Thanks for the update. That's great news. Can you provide a date?

**Comment by KonradLinkowski** [comment]
> @juminoz master/detail in server side row model isn't currently supported - but! - it will be in the next release, scheduled for this month

Is master/detail for server side row model supported yet?

**Comment by pavan-shipmnts** [comment]
master does work with server side model now

**Comment by yoni-noma** [comment]
Does master/details can now work with infinite?

**Comment by sabahang** [comment]
@yoni-noma  if you have an enterprise licence (which you would need to for master detail), you should be using SSRM instead of infinite ([as per the docs](https://www.ag-grid.com/javascript-data-grid/infinite-scrolling/))
