### ISSUE TITLE
CellRenderer component gets destroyed on horizontal scroll

### ISSUE THREAD

**Issue by saurabhraja** [ceolter/ag-grid#1670]
**I'm submitting a ...**
```
[X] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
On horizontal scroll of the grid as the cell rendered by a cellRenderer component goes out of view, the component gets destroyed along with all its states. In more detail, I have an input field inside the cellRenderer and as I click on a button from another component I'm listening to that event using a subscription which will make my input field editable by setting a property to true which by default is false. Now with the input field editable if I scroll out of view the component is destroyed and as I scroll back in it is set to the default state and is subscribing to my edit click event. But the edit event was already triggered previously, and now as the component is re-initialised the same should be triggered once again.

**Expected behavior**
This issue is however not happening on vertical scroll and the cell goes out of view. Expected behavior is the cellRenderer component should not be destroyed as it goes out of view as all subscriptions are resubscribed and the same should be fired once again. 

**Environment:**
Operating System: Windows 7
Package Manager: npm

* **ag-Grid version:** 9.1.0

* **Browser:**
Google chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by saurabhraja** [comment]
This issue was fixed by setting the **suppressColumnVirtualisation: true** in gridOptions.

**Comment by makinggoodsoftware** [comment]
Hi I am afraid this is how is intended to work and you have implemented our recommended workaraoud.

**Comment by Vyshakhcs1** [comment]
> This issue was fixed by setting the **suppressColumnVirtualisation: true** in gridOptions.

I was finding a solution for this. This solution saved me. Thanks
