### ISSUE TITLE
Floating filters not displaying content when filter is set to Equals and the value is the number 0

### ISSUE THREAD

**Issue by Grimoire42** [ceolter/ag-grid#1676]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When setting a floating filter to be Equal to 0, the floating filter text box remains empty.

**Expected behavior**

When setting a floating filter to be Equal to 0, the floating filter text box should show the value 0.  When any other value is entered, such as 0.01, the value is shown in the floating filter text box

**Minimal reproduction of the problem with instructions**

1. Go to https://www.ag-grid.com/example.php
2. Click the [...] button on the Total Winnings column
3. In the Filter... text box, enter 0
4. Click outside the filter dropdown
5. Note that 0 is not displayed in the floating filter textbox

**What is the motivation / use case for changing the behavior?**

Being able to visually see what values you are filtering on is quite important, and 0 is particularly important.

**Please tell us about your environment:**

Windows Server 2012
Webpack
nginx

* **ag-Grid version:** 9.1.0 & 10.0.0

* **Browser:**

"Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
"Mozilla/5.0 (Windows NT 6.2; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0"
"Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; WOW64; Trident/6.0; .NET4.0E; .NET4.0C; InfoPath.3; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 1.1.4322)" 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All

**Comment by makinggoodsoftware** [comment]
Hi,

There is a ticket created to improve the way the input validation for floating filters works:

AG-392

Once that this is available we will let you know.

**Comment by makinggoodsoftware** [comment]
Hi,

Just to le you know that as of 10.1.0 this is available.

Please check the changelog

Thanks
