### ISSUE TITLE
Page freezes as result of scroll if any row has 0 height

### ISSUE THREAD

**Issue by dmitrievanthony** [ceolter/ag-grid#1678]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If any row has 0 height and user tries to scroll table then the whole page freezes (thread stuck in infinite loop in `inMemoryRowModel.js` in `getRowIndexAtPixel(pixelToMatch)` function).

**Expected behavior**

Table shouldn't freeze page and crash it.

**Minimal reproduction of the problem with instructions**

1. Make a row height 0.
2. Load table with scroll and set cursor near the row with 0 height.
3. Scroll table.

**What is the motivation / use case for changing the behavior?**

It's not a correct behavior to crash whole page.

**Please tell us about your environment:**

Apache, npm, Angular4

* **ag-Grid version:** X.X.X

9.1.x

* **Browser:**

Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.3.2

**Comment by makinggoodsoftware** [comment]
Hi,

We don't support 0 height rows, you can however filter rows out by applying a bespoke filter and making them disappear completely.

https://www.ag-grid.com/javascript-grid-filter-external

**Comment by dmitrievanthony** [comment]
I need to hide group header in some cases, but filters don't applied on group header rows.

**Comment by febret** [comment]
(I'm an ag-grid enterprise user) - Even if zero height rows are not supported, having the grid freeze the entire page because of that does not seem like a good behavior. At minimum, there should be an error message generated when a zero-height row is detected.
