### ISSUE TITLE
There isn't an event triggered when all rows are selectedq

### ISSUE THREAD

**Issue by pupeno** [ceolter/ag-grid#1679]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When you have a row with headerCheckboxSelection, no event is triggered when the checkbox in the header is clicked. 

**Expected behavior**
An event should be triggered, such as onAllRowsSelected. 

**What is the motivation / use case for changing the behavior?**
We are using master/slave grids and we need to catch that event to transfer it to the other grid so all rows are selected on both. 

**Please tell us about your environment:**
We are using Windows, ClojureScript, React, agGrid 9.1.0 with the cljsjs wrapper we developed to make agGrid easy to use on Clojure projects. 

* **ag-Grid version:** 9.1.0

* **Browser:**
"Mozilla/5.0 (Windows Nº 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safary/537e36" 

* **Language:**
ClojureScript but I don't think it really matters for this issue

**Comment by makinggoodsoftware** [comment]
Hi,

While we don't have an event for the select all. You can listen on rowSelected and act on it for each row selected/deselected from the header.

**Comment by pupeno** [comment]
But if I'm using onSelectionChanged, how do I distinguished between it being triggered by the user, from the UI and it being triggered by the other grid. Because without it, when I try to synchronize both ways, it generates an infinite loop.
