### ISSUE TITLE
Can't set isCancelBeforeStart for default TextCellEditor

### ISSUE THREAD

**Issue by lianyzhou** [ceolter/ag-grid#1688]
**I'm submitting a support request 

**Current behavior**
I can use default text Editor, and it works fine
```
_assign(column, {
            editable: true,
            cellEditor: 'text'
          })
```

**Expected behavior**
I want to set isCancelBeforeStart function for default text editor, depends on column defination by a property called updatable
```
{
     dctId :  'email',
     updatable : false,
     ... some other column defination ....
}

```
I can't find a way to do it , so if i need to write a text editor for my own ? 

**Please tell us about your environment:**

Win10, Sublime Text 3,  webpack, koa

* **ag-Grid version:** 10.0.0

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"

* **Language:** ES6/7

**Comment by seanlandsman** [comment]
As per the issue template please don't use GitHub for support queries. Either use our Members Forum (https://ag-grid.com/forum/forumdisplay.php?fid=5) or use StackOverflow

GitHub is reserved for issues and feature requests
