### ISSUE TITLE
Filter on blur?

### ISSUE THREAD

**Issue by Kliton** [ceolter/ag-grid#1693]
Hi,
is possible to run event "filterChanged" only on filter blur ?

Thanks

**Comment by seanlandsman** [comment]
As per the issue template please don't use GitHub for support queries. Either use our Members Forum (https://ag-grid.com/forum/forumdisplay.php?fid=5) or use StackOverflow

GitHub is reserved for issues and feature requests

In answer to your question I'm afraid this isn't possible
