### ISSUE TITLE
Update gridOptions

### ISSUE THREAD

**Issue by CindySLiu** [ceolter/ag-grid#1695]
I have a question. After ag-grid created, can I still update gridOptions? For example, at beginning pagenation is not enabled. After rows increase, then it is enabled. Can we do this and how?

Thanks in advance!!!

**Comment by seanlandsman** [comment]
As per the issue template please don't use GitHub for support queries. Either use our Members Forum (https://ag-grid.com/forum/forumdisplay.php?fid=5) or use StackOverflow

GitHub is reserved for issues and feature requests

In answer to your question however, generally properties on gridOptions are read once and not again. Post load changes should be done via the grid & column APIs

**Comment by Ruud-cb** [comment]
@CindySLiu did you find a solution :) Still comes up some what higher in the search results so yeah.
