### ISSUE TITLE
Up-gradation from 3.0 to 10.0 version Ag-Grid Not not working

### ISSUE THREAD

**Issue by santosh-k1** [ceolter/ag-grid#1696]
Hi, i have developed the application in 3.0 by using ag-grid and angularJS1 ... and now some new features we found in 10.0 version when we up-grade the framework application is not working.. so can you provide the resolution for above issue..

Thanks

**Comment by seanlandsman** [comment]
As per the issue template please don't use GitHub for support queries. Either use our Members Forum (https://ag-grid.com/forum/forumdisplay.php?fid=5) or use StackOverflow

GitHub is reserved for issues and feature requests
