### ISSUE TITLE
ag-grid-react, React 15.5.0 compatibility

### ISSUE THREAD

**Issue by uvtzxpm** [ceolter/ag-grid#1697]
Can someone take a look at this on the ag-grid-react repo?

https://github.com/ceolter/ag-grid-react/issues/65

It's been a couple of months since that issue was opened.

I also notice there's been [some activity on ag-grid-react today](https://github.com/ceolter/ag-grid-react/commit/709b7cdab736f450b490a489afa46a1cf7d600ef).

PR https://github.com/ceolter/ag-grid-react/pull/67 makes a lot of small improvements but may need some testing (due to the move to ES6).

PR https://github.com/ceolter/ag-grid-react/pull/70 solves the problem in the absolute simplest way and should be safe to just merge in.

**Comment by seanlandsman** [comment]
Hi

I'm actively working on the react side of things at the moment - the above should be incorporated soon, amongst a whole host of other changes

Keep an eye on the react repo over the next week or two

thanks

**Comment by uvtzxpm** [comment]
@seanlandsman Thanks, that's good to know 👍
