### ISSUE TITLE
Group renderer errors on Enter keypress if node is not editable

### ISSUE THREAD

**Issue by iblocks-Xander** [ceolter/ag-grid#1700]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If the row node is not editable, pressing enter to expand or contract the group will error in the console with error message:
```
Uncaught TypeError: this.params.node.isCellEditable is not a function
    at GroupCellRenderer.onKeyDown
``` 
It looks like the commit to check whether expansion should happen if the row is editable does not make sure the property exists ( line of code is [here](https://github.com/ceolter/ag-grid/blob/9c700640c1cf111105a6a00d321fe3c9f97681c8/src/ts/rendering/cellRenderers/groupCellRenderer.ts#L397) ) 
I would probably just put a check for the property existing at all before checking the result of the function 
**Expected behavior**
Enter to expand or contract rows should work without the row being editable.

**Minimal reproduction of the problem with instructions**
In the master detail example given on the site, this error occurs.
https://www.ag-grid.com/javascript-grid-master-detail/exampleMasterDetail.html

**Please tell us about your environment:**

* **ag-Grid version:** 10.1.0

* **Browser:**
Chrome

* **Language:** All

**Comment by seanlandsman** [comment]
Hi,

Thanks for reporting - I've raised issue AG-525 for this our side. We'll update this thread with updates as soon as we have any.

It has been marked as a high priority issue

thanks

**Comment by ceolter** [comment]
this is fixed in latest v11
