### ISSUE TITLE
deselectAll method doesn't work

### ISSUE THREAD

**Issue by dloprodu** [ceolter/ag-grid#1702]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have a grid set up as infinite scroll with pagination (filter and sorting in server side). The strange behaviour in version 10.1.0 is as follow:

1. I select a row.
2. I apply a filter where the selected row doesn't match and it'll disapear.
3. The grid is updated with new rows that match with the filter.
4. I clear all selection (api.deselectAll) but the previous selected row still stay.

**Expected behavior**
clear all selection.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** 10.1.0

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
Hi,

Thanks for reporting - I've raised issue AG-527 for this our side. We'll update this thread with updates as soon as we have any.

It has been marked as a high priority issue

thanks

**Comment by ceolter** [comment]
fixed. will be in next release.

**Comment by chanakyachatterjee** [comment]
it's still not working ..
