### ISSUE TITLE
How to fit a Tree data structure in ag-grid?

### ISSUE THREAD

**Issue by DamanjitKaur** [ceolter/ag-grid#1704]
Is there any way to create a tree in ag-grid with tree data structure ? I have seen the below link : 
[https://www.ag-grid.com/javascript-grid-tree/#gsc.tab=0] but it seems like a grouping of flat data on the basis of a specific data field values. I have a parent child relationship in data and want to create similar structure in ag-grid.

I need something like this available in ui-grid :
[http://ui-grid.info/docs/#/tutorial/215_treeView](url)

I want to create a tree structure like below:
1 Step 1
-> 1-1 level 1 Parent step 1
  ->1-1-1 leaf step 1
  ->1-1-2 leaf step 2
->1-2 level 1 Parent Step 2
 ->1-2-1 leaf step 1
  ->1-2-1 level 2 Parent Step 2
    ->1-2-1-1 leaf step 2

**Comment by seanlandsman** [comment]
As per the issue template please don't use GitHub for support queries. Either use our Members Forum (https://ag-grid.com/forum/forumdisplay.php?fid=5) or use StackOverflow

GitHub is reserved for issues and feature requests

To answer your question however, the tree data support doesn't require the data to be grouped - it is entirely down to the developer to massage the data into a tree like (parent/child) format.
