### ISSUE TITLE
headerComponentFramework components do not render in Internet Explorer.

### ISSUE THREAD

**Issue by schreyerpeter** [ceolter/ag-grid#1707]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I am using React to build an app and in Chrome my headerComponentFramework components render and behave perfectly for sorting columns and displaying my custom content, yet in IE, they do not render, but I can find them through inspecting the DOM.

**Expected behavior**

I would expect IE behavior to be the same as Chrome's.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10, Visual Studio Code, NPM

* **ag-Grid version:** X.X.X

10.0.0

* **Browser:**

Internet Explorer

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by makinggoodsoftware** [comment]
Hi,

I have just tested of our out of the box header examples, and they all seem to be working fine in IE

https://www.ag-grid.com/javascript-grid-header-rendering

Can you give them a go and see if they are also working for you?

My guess is that in your custom header component you have some custom HTML/CSS that is not compatible with IE.

This doesn't look like an ag-grid issue to me

**Comment by schreyerpeter** [comment]
You are absolutely right, I was applying a small margin-top to my ag-react-container, causing the contents to completely disappear. Thank you for your time.
