### ISSUE TITLE
Incompatible change in ag-grid 10.1.0: rows are inserted in reverse order

### ISSUE THREAD

**Issue by catahoc** [ceolter/ag-grid#1709]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

ag-grid 10.1.0: gridApi.insertItemsAtIndex(0, [a, b]) inserts item in the following order: b, a <- breaking change
gridApi.updateRowData({addIndex: 0, add: [a, b]}) gives the same incompatible result: b, a

**Expected behavior**

ag-grid before 10.1.0: gridApi.insertItemsAtIndex(0, [a, b]) inserts item in the following order: a, b

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10, Intellij IDEA 17.1.3, npm 5.0.0, webpack 2.3

* **ag-Grid version:** 10.1.0

This is most recent ag-Grid version

* **Browser:**

Chrome 58.*

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript 2.3

**Comment by catahoc** [comment]
Workaround:
```
        items.reverse().forEach(x => gridApi.updateRowData({
            addIndex: index,
            add: [x]
        }));
```

**Comment by catahoc** [comment]
Also found: https://www.ag-grid.com/javascript-grid-data-update/#gsc.tab=0

> The index to add is put in for historical purposes and should not be used. If you want the grid to display in a certain order, you should apply a grid sort and have the row data sorted.

This is not friendly change, you force developers to use grid sort, but it is not useful sometimes. In our case, server computes position for each row and sends to client update with computed index. Client-side js just insert rows at this index

**Comment by catahoc** [comment]
Exact error is in inMemoryNodeManager.ts:101
```
            add.forEach( item => {
                let newRowNode: RowNode = this.addRowNode(item, addIndex);
                rowNodeTransaction.add.push(newRowNode);
            });
```

It's better to add items in reverse order, or increment index at each iteration

**Comment by dbVaspo** [comment]
+1

**Comment by seanlandsman** [comment]
Hi

Thanks for reporting this - I have raised a high priority issue for this our side ( AG-543 ).

We'll update this thread with updates as soon as we have any

thanks

**Comment by ceolter** [comment]
fixed. will be in next release.

**Comment by makinggoodsoftware** [comment]
Hi,

Just to let you know that as of 11.0.0 this has been implemented, see the changelog for more details..

https://www.ag-grid.com/change-log/changeLogIndex.php#gsc.tab=0

**Comment by catahoc** [comment]
Thanks!
