### ISSUE TITLE
Take out 'no selection'

### ISSUE THREAD

**Issue by ceolter** [ceolter/ag-grid#171]
http://www.angulargrid.com/forum/showthread.php?tid=2233

**Comment by ceolter** [comment]
have changed my mind on this - as the selection will change in the future to work like 'excel', in that you will be able to select a group of cells by dragging the mouse. if text selection is turned on, it will make this look very odd.

**Comment by bdoum** [comment]
If you can put an option to switch this, for instance excelLikeSelection true or false and false enable the usual select, would be great!
I'm doing the css revert for now.

ben

**Comment by ceolter** [comment]
range selection implemented, this is no longer valid request.
