### ISSUE TITLE
How to do unit test CellRenderer and CellEditor?

### ISSUE THREAD

**Issue by dmngu9** [ceolter/ag-grid#1717]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

How can I do unit test for CellRenderer and CellEditor for angularjs project? Please let me know.
**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

For project test coverage

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
As per the issue template, please don't raise support requests here. Either use stackoverflow or our Member Forum ( https://ag-grid.com/forum/forumdisplay.php?fid=5 )
