### ISSUE TITLE
Get DOM element by item

### ISSUE THREAD

**Issue by PranKe01** [ceolter/ag-grid#1718]
**I'm submitting a ...**
```
[X] feature request
```

**Current behavior**
It is not possible to get the rows DOM element, by the underlying item.

**Expected behavior**
I need to get the DOM element for a specific item for unit testing.

**Minimal reproduction of the problem with instructions**
Create a grid with some items (and child items), sort and filter them and try to get the DOM for a row of these items.

**What is the motivation / use case for changing the behavior?**
We need it for unit testing. For example click-tests, based on a specific item.

**Comment by PranKe01** [comment]
Looks like there is already a callback function available: getBusinessKeyForNode(node)

**Comment by nmz787** [comment]
this is working for me, with some filtering based on row index OR data attributes, and the column name
```
function modify_DOM_for_row_by_data(data_id){
    let rows = gridOptions.api.rowRenderer.rowCtrlsByRowIndex;
    // for each row
    for (let row_index = 0; row_index < rows.length; ++row_index) {
        // filter based on the row-ID
        if (row_index != row_id) {}
            continue;
        }
        // OR filter based on the row's data
        // if (rows[row_index].rowNode.data.id != data_id){ continue; }

        let cols = rows[row_index].centerCellCtrls.list;
        // for each column
        for (let col_index = 0; col_index < cols.length; ++col_index) {
            let col = cols[col_index];
            let col_id = col.column.colId;
            // check the Column ID/name (value of "field" in the gridOptions columnDefs dict)
            if (col_id == 'id') {
                col.eGui.innerHTML = 'something new';
                return;
            }
        }
    }
}
```
