### ISSUE TITLE
Cannot invoke parent component method from inside cellRendererFramework 

### ISSUE THREAD

**Issue by harikrishnan-u01** [ceolter/ag-grid#1721]
I need to invoke the parent component method from inside the cellRendererFramework. For this I referred the example mentioned in the agGrid documentation. PFB the plunker for the same:
https://plnkr.co/edit/J04rdB?p=info

I referred the component ChildMessageComponent.

The below code is not working because this.params.context is undefined. 
I am using agGrid version 8.2.0 (to support server side pagination) and Angular version 4.1.3.

`    public invokeParentMethod() {
        this.params.context.componentParent.methodFromParent(`Row: ${this.params.node.rowIndex}, Col: ${this.params.colDef.headerName}`)
    }
`

**Comment by seanlandsman** [comment]
I think the context was only made available for this use in a later version of ag-grid.

I suggest you upgrade and see if this resolves your problem

**Comment by harikrishnan-u01** [comment]
Hi @seanlandsman ,

I am stuck with agGrid version 8.2.0 because I need server side pagination meaning I need to call the server to get the records for a page on page number click.

The latest version of agGrid doesn't support server side pagination. It only works if I pull all the records first up which is not recommended in our application.

Is there any workaround for this issue?

Thanks,
Hari

**Comment by seanlandsman** [comment]
Hi

Please see the note at the top of https://www.ag-grid.com/javascript-grid-pagination/

If you were doing server side pagination, we recommend moving to pagination with infinite scrolling as a way of migration to the new mechanism. 

The link for this is here: https://www.ag-grid.com/javascript-grid-infinite-scrolling#pagination

**Comment by amol-mpandit** [comment]
This might be helpful.
[(https://www.ag-grid.com/best-vuejs-data-grid/#parent_child)]
