### ISSUE TITLE
Date floating filter does not allow input on IE11

### ISSUE THREAD

**Issue by R4DIC4L** [ceolter/ag-grid#1728]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using a floating filter of type 'date' (filter: 'date') on a column, the input of the floating filter doesn't allow user input for the date in IE11 browser.

**Expected behavior**
The 'date' column floating filter should allow user input for the date.

**Minimal reproduction of the problem with instructions**
This behavior can also be seen in the ag-grid example in the documentation page for floating filters at section _Complex example with JQuery_, on the _Date_ field [here](https://www.ag-grid.com/javascript-grid-floating-filter-component).

**Please tell us about your environment:**
* **OS:** Windows 10
* **ag-Grid version:** 11.0.0
* **Browser:** IE/11.413.15063
* **Language:** Javascript ES6, React

**Comment by makinggoodsoftware** [comment]
I fixed this a couple of days ago. It is tracked by AG-541. It will be available in the next release of ag-grid. I'll update this thread as soon as this release is available.
