### ISSUE TITLE
Mistake in BaseColDefParams interface definition

### ISSUE THREAD

**Issue by anatolyzolotar** [ceolter/ag-grid#1729]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Hi. I believe there is a mistake in **BaseColDefParams** interface here https://github.com/ceolter/ag-grid/blob/11.0.0/src/ts/entities/colDef.ts#L307
```
export interface BaseColDefParams {
    node: any,
    data: RowNode,
    ...
}
```

**Expected behavior**
```
export interface BaseColDefParams {
    data: any,
    node: RowNode,
    ...
}
```

**Minimal reproduction of the problem with instructions**
see link above

* **ag-Grid version:** 11.0.0

* **Browser:**

* **Language:**  TypeScript 2.3

**Comment by seanlandsman** [comment]
Hi

This has since been fixed and will be available in the next release

thanks
