### ISSUE TITLE
Issue with Observable/Ag-Grid, it's good a few of day ago

### ISSUE THREAD

**Issue by leduong** [ceolter/ag-grid#1731]
Hi.

My project build failed recently although no code changes. I have tried version 10.x and 11.x still have errors. This project Angular 4 & SystemJS-builder

https://travis-ci.org/stuartshay/CoreDataStore/jobs/248300098#L1742
![screenshot from 2017-06-30 00-37-12](https://user-images.githubusercontent.com/1042749/27701813-4a494550-5d2c-11e7-9600-b9b22ce0c30b.png)

* **ag-Grid version:** 10.X.X or 11.X.X
* **Language:** [all | TypeScript 2.3 | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
This is due to a change in typescript 2.4. Change your cell renderer(s) to implement the optional refresh method

TS 2.4 now insists on classes implementing interfaces with optional methods having all methods implemented. I think this is bonkers, but it is a TS 2.4 issue
