### ISSUE TITLE
ag-grid --paginationEvents and custom pagination is not available

### ISSUE THREAD

**Issue by Bhawna14** [ceolter/ag-grid#1732]
Hi  ,

As per my requirement, i need pagination where total page no, next,last, previous buttons would listen to my service call and show data based on that.
Only event mentioned on tutorial 'paginationChanged' throws error when i declare it as this.gridOptions.paginationChanged= userPagination;

Is there any way by which i can define that on clicking 'NEXT' on the pannel , i can make server call to get more data??

**Comment by seanlandsman** [comment]
Please dont cross post issues. Closing this
