### ISSUE TITLE
Typescript 2.4 error

### ISSUE THREAD

**Issue by Haemoglobin** [ceolter/ag-grid#1739]
Error when running on typescript 2.4 in ./node_modules/ag-grid/dist/lib/rendering/cellRenderers/groupCellRenderer.d.ts:17:22
TS2559: Type GroupCellRenderer has no properties in common with type ICellRenderer

**Comment by talynone** [comment]
Being discussed here:
https://github.com/ceolter/ag-grid/issues/1708

**Comment by seanlandsman** [comment]
For now rolling back to 2.3.x is your only option - we'll see what we can do our side to help TS 2.4 users going forward, but this will only be in the next release

**Comment by matbrighi** [comment]
@seanlandsman

This commit added support to TS 2.4: ceolter/ag-grid@cfaf82df618a3f79b88ae55da878f22557086ab2

This commit revert the previous commit:  ceolter/ag-grid@75058c0bb02b723590f19dc6204b9f331bfc6048

Any chances to see the support for TS2.4 reintroduced? 

Many Thanks

**Comment by seanlandsman** [comment]
hi - the next release will support ts 2.4. The above change is part of a wider change for 2.4 compatibility

We'll be doing a release either tomorrow or early next week - wait for that release and TS 2.4 should work fine

**Comment by matbrighi** [comment]
ok, thanks very much!
