### ISSUE TITLE
`suppressColumnVirtualisation` removed?

### ISSUE THREAD

**Issue by grovesNL** [ceolter/ag-grid#1743]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
`suppressColumnVirtualisation` was removed from `BOOLEAN_PROPERTIES` in a recent commit https://github.com/ceolter/ag-grid/commit/e8f12ad2a1e96d4b21cff5f1901345152ee94522#diff-2043214abe30ce0230cf46c0c337eb1c and it appears the flag is no longer passed to `gridOptions` because it's skipped during [`copyAttributesToGridOptions`](https://github.com/ceolter/ag-grid/blob/28197aea856f0b738015ba47f8edd95cbf78708a/src/ts/components/componentUtil.ts#L108).

**Expected behavior**
Column virtualization would be suppressed correctly when the flag was provided to ag-grid, i.e. in React `<AgGridReact suppressColumnVirtualisation {...otherProps} />`.

**Comment by seanlandsman** [comment]
Hi

Thanks - it was overwritten by mistake. This has been fixed and will be available in the next release
