### ISSUE TITLE
How to debounce on loading overlay template?

### ISSUE THREAD

**Issue by csreddy** [ceolter/ag-grid#1744]
Posted question on stackoverflow, but haven't got any response, hence posting here. Sorry!
https://stackoverflow.com/questions/44935279/how-to-debounce-on-showing-loading-overlay-template

I'm using ag-grid and ag-grid-angular v9.0.0. 
I need to show loading overlay template after 2 seconds if the rows are empty otherwise hide it. Currently it shows instantly and goes away after rows are rendered. Any clues or suggestions on how to accomplish is appreciated.

**Comment by seanlandsman** [comment]
Hi

You'll need to manage the overlay yourself in this case - please see the overlay documentation here https://www.ag-grid.com/javascript-grid-overlays/ for options
