### ISSUE TITLE
TS 2.4.1 Error: Type 'GroupCellRenderer' has no properties in common with type 'ICellRenderer'.

### ISSUE THREAD

**Issue by smhc** [ceolter/ag-grid#1745]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Compilation with typescript 2.4.1 fails with;

node_modules/ag-grid/dist/lib/rendering/cellRenderers/groupCellRenderer.d.ts(17,22): error TS2559: Type 'GroupCellRenderer' has no properties in common with type 'ICellRenderer'.

**Expected behavior**

Compilation is successful.
See 'weak type detection': https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes

**Minimal reproduction of the problem with instructions**

Compile an ag-grd project using typescript 2.4.1.

**What is the motivation / use case for changing the behavior?**

Can compile projects using the latest version of typescript.

**Please tell us about your environment:**

Linux, Visual Studio Code

* **ag-Grid version:** 11.0.0

* **Browser:** Any

* **Language:**  TypeScript 2.4.1

**Comment by iblocks-Xander** [comment]
https://github.com/ceolter/ag-grid/issues/1708

Already being discussed here.

**Comment by smhc** [comment]
Already being discussed. Closing.
