### ISSUE TITLE
Slow rendering of detail grid

### ISSUE THREAD

**Issue by elineopsommer** [ceolter/ag-grid#1754]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Slow rendering of the detail rows

**Expected behavior**
Should be the same speed as the master grid

**Minimal reproduction of the problem with instructions**
Plunker: https://plnkr.co/B0fXvdiaAXCdskmxwZdo

**What is the motivation / use case for changing the behavior?**
The grid is not usable anymore as it is slow in use

**Please tell us about your environment:**
Does not apply as it is shown in the plunker

* **ag-Grid version:** 11.0.0

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

* **Language:** [TypeScript 2.1.1]

**Comment by seanlandsman** [comment]
Hi

Thanks for reporting this - Ive raised AG-613 our side to track this. We'll update this thread with updates as soon as we have any

thanks

**Comment by seanlandsman** [comment]
Hi

Having taken a further look we can see that this is because the detail grid is massive - try setting the detail grid to be smaller (it'll then have a scrollbar) and it should render fine

**Comment by elineopsommer** [comment]
Hi,
This is really a problem as it is not very user friendly to have a scrollbar inside a grid with also a scrollbar. Can this be solved as this is a major blocker?

**Comment by elineopsommer** [comment]
@seanlandsman is there any solution for this?
