### ISSUE TITLE
onRowDoubleClicked event handler doesn't have any injected services available

### ISSUE THREAD

**Issue by CindySLiu** [ceolter/ag-grid#1756]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Create a simple grid in a component like the following. The problem is onRowDoubleClicked event handler (onView in my case) doesn't have any injected services available, like http service is undefined. But they are available for other methods in the component.

`@Component({
    moduleId: module.id,
    templateUrl: './mycomponent.html',
})
export class MyComponent {
      gridOptions: GridOptions;

    constructor(
        private changeRef: ChangeDetectorRef,
        private http: Http) {
 
        this.gridOptions = {};
        this.gridOptions.columnDefs = this.GetGridDef();
        this.gridOptions.rowData = [];
        this.gridOptions.enableColResize = true;
        this.gridOptions.enableFilter = true;
        this.gridOptions.enableSorting = true;
        this.gridOptions.enableRangeSelection = true;
        this.gridOptions.rowSelection = "multiple";
        this.gridOptions.suppressRowClickSelection = true;
        this.gridOptions.pagination = true;
        this.gridOptions.paginationPageSize = 20;
        this.gridOptions.onRowDoubleClicked = this.onView;
    }

onView(event) {
  // this.http == undefined
}

otherMethod() {
  // this.http is populated.
}
`

**Expected behavior**
Injected services, like this.http, should be available - populated with data - inside onRowDoubleClicked event handler. 

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 64 bit
npm v4.2.0
node v7.8.0

* **ag-Grid version:** X.X.X

ag-grid v10.0.1
ag-grid-angular v10.0.0

* **Browser:**

Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
This is almost certainly a scoping issue

Try     this.gridOptions.onRowDoubleClicked = this.onView.bind(this)

**Comment by CindySLiu** [comment]
You are right. Your work around works! Thanks!
