### ISSUE TITLE
Grid only works with fixed dimensions

### ISSUE THREAD

**Issue by SkylarLK9998** [ceolter/ag-grid#1757]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When the grid size is xpx by ypx, the grid works fine. When grid size is x% by y% it just displays a black line

**Expected behavior**
When grid size is x% by y% it would display an actual grid, not a black line

**Minimal reproduction of the problem with instructions**

![screen shot 2017-07-13 at 11 05 38 am](https://user-images.githubusercontent.com/22405235/28181296-fb4ade82-67bc-11e7-9c68-f442fa128886.png)
![screen shot 2017-07-13 at 11 06 27 am](https://user-images.githubusercontent.com/22405235/28181297-fb69806c-67bc-11e7-824c-966b92069e77.png)

http://plnkr.co/edit/TJnlsvylnXleLlNZ4p0D?p=preview

**What is the motivation / use case for changing the behavior?**

Dynamic web design requires features to be able to be resized based of window sizes and monitor sizes. This requires %s

**Please tell us about your environment:**
Mac
WebStorm

* **ag-Grid version:** 
11.0.0

* **Browser:**
I only have Safari and Chrome on my laptop right now, but I'm guessing this problem would occur on all Browsers.

* **Language:**
Angular 1

**Comment by seanlandsman** [comment]
I have updated your plunker http://plnkr.co/edit/Dr1Dh1vzpdbVJosrVpwU?p=info

The problem is down to using doctype html - this is stricter and disables quirks type modes. You need to specify a html & body height for this to work

This isnt a grid issue as such - it would happen with any div 

thanks
