### ISSUE TITLE
Doubt regarding cell click and row click how can i differentiate whether when cell is clicked how to prevent the rowclick

### ISSUE THREAD

**Issue by balajiptg** [ceolter/ag-grid#1758]
So I have a column where I placed a delete icon on click of it it is calling row click in angular 2 how to differentiate or can prevent that row click

**Comment by seanlandsman** [comment]
As per the issue template please dont use github for support. 

Either use our members forum ( https://ag-grid.com/forum/forumdisplay.php?fid=5 ) or stackoverflow for support
