### ISSUE TITLE
Incorrect name of renamed property in warning message

### ISSUE THREAD

**Issue by YPBS** [ceolter/ag-grid#1759]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Incorrect property name in the warning message.

**Expected behavior**
Renamed property name in warning message should match new property name.

**Minimal reproduction of the problem with instructions**
Source code issue

**What is the motivation / use case for changing the behavior?**
console.warn("ag-grid: since version 11.0.x, groupColumnDef has been renamed, this property is now called autoColumnGroupDef. Please change your configuration accordingly");

Minor issue: groupColumnDef has actually been renamed to autoGroupColumnDef, we used 'autoColumnGroupDef' based on warning message and lost time trying to figure out the correct name. 

**Please tell us about your environment:**
Windows 7
Eclipse
Webpack/Node.js

* **ag-Grid version:** 11.0.0

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by seanlandsman** [comment]
Hi

Thanks for reporting this - this has already been fixed and will be reflected in the next release.

Apologies for the hassle and lost time it cost you

thanks
