### ISSUE TITLE
AgRendererComponent params (that is injected into "agInit" or "refresh") has invalid rowIndex when grid is sorted

### ISSUE THREAD

**Issue by AVykhrystyuk** [ceolter/ag-grid#1760]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have a grid with `gridOptions.suppressClickEdit = true;`
I have the following cell renderer component for angular 2:

```
export class MyRendererComponent implements AgRendererComponent {
    private _params: any;

    agInit(params: any): void {
        this._params = params;
    }

    refresh(params: any): void {
        this._params = params;
    }

    startEdit() {
        this._params.api.startEditingCell({
            rowIndex: this._params.rowIndex,
            colKey: this._params.column
        });
    }
}
```

Invoking `api.startEditingCell()` when grid is sorted `this._params.rowIndex` is pointing to the previous rowIndex (that was before the sorting). This results in opening an editor for the wrong cell

**Expected behavior**
Either `this._params.rowIndex` field of the params instance should be updated when we do sorting.
Or there should be API on how to get updated rowIndex after sorting

**Minimal reproduction of the problem with instructions**
create a custom RendererComponent, store params instance from agInit | refresh to a component field, sort the grid so order of the your component cells changed, invoke startEdit method for example from the button

**What is the motivation / use case for changing the behavior?**
I want to start the editing in another way using a button in my cellRenderer

**Please tell us about your environment:**
* Windows 10

* **ag-Grid version:** 11.0.0

* **Language:** [typescript]

**Comment by seanlandsman** [comment]
Hi

Thanks for reporting this - Ive created issue AG-623 our side for this.

We'll update this thread with any updates as soon as we have any

thanks

**Comment by ceolter** [comment]
the params is a throw-away object - once the grid passes it to you, it throws it away, it doesn't keep it for keeping things up to date

if you want the index, use rowNode.rowIndex, the rowNode is passes as a param (params.node)

you can also listen for indexes changes to the node:

```rowNode.addEventListener('rowIndexChanged', myListener);```
... if you do this, remember to remove the listener
```rowNode.removeEventListener('rowIndexChanged', myListener);```
