### ISSUE TITLE
Show Row Index for ag-grid

### ISSUE THREAD

**Issue by dotnetynb** [ceolter/ag-grid#1761]
Is there any method we can call to show the row index of the row as a column for ag-grid ?

**Comment by yogeshpaul** [comment]
I assume you want to show row indices in a column. You can create a cellRenderer function which will get params object as argument, params object will have a property rowIndex which you can render in the cellRenderer.

**Comment by dotnetynb** [comment]
Thank you for the quick reply. I am new to ag-grid. Can you provide any link so that I can refer ?
Thanks again

**Comment by yogeshpaul** [comment]
Here is a rough sketch on how to do it, In the columnDef for your new column, type property
cellRenderer : function(params){
    return params.rowIndex;
}

**Comment by dotnetynb** [comment]
Just did it by myself, thank you verymuch
