### ISSUE TITLE
On Enter keypress event for grid

### ISSUE THREAD

**Issue by jenb34** [ceolter/ag-grid#1764]
I've written a custom editor for the grid which opens in another div on screen. I would like the users to be able to press enter on the keyboard to open a row for editing in this div - for accessibility purposes. Is there a way to override a keypress event to the grid to capture the enter key being pressed?

**Comment by seanlandsman** [comment]
Hi,

If you want the entire row to be editable, you can use the full row editing feature - this should provide what you need out of the box: https://www.ag-grid.com/javascript-grid-cell-editing/#fullRowEdit

thanks

**Comment by reiui9** [comment]
[look at this](https://www.ag-grid.com/react-data-grid/column-properties/#reference-columns-suppressKeyboardEvent)

```js
suppressKeyboardEvent: (props) => {if(props.event.key == 'Enter') props.event.stopPropagation()},
```

on columnDefs
