### ISSUE TITLE
Grouping Rows change breaks old code

### ISSUE THREAD

**Issue by dereklin** [ceolter/ag-grid#1766]
I migrated from 10.1.0 to 11.0.0

When grouping rows, In 10.1.0, I am able to use blank for Group column by using a blank string.  In 11.0.0, If I use
```
      autoGroupColumnDef: {
        headerName: '', width: 200, field:'field1'
      }

```
The word Group shows up as the column header.  How can I use blank instead?

**Comment by seanlandsman** [comment]
HI,

Try replacing headerName with ' ' (a single space)

thanks
