### ISSUE TITLE
Group Header Column Hinderance with Custom Filter

### ISSUE THREAD

**Issue by Ajaybhardwaj7** [ceolter/ag-grid#1770]
I am not sure if this is a bug or I am missing something.
**I have an enterprise licence.**

The problem is related to custom filter over column headers group.

**Current Behaviour**:
I have implemented my own custom header with custom filter with ag-grid-react. I am grouping my column headers too. eg. my colDefs contains
```
{ 
              headerName:"COMMON",
              headerClass :"header-group-cls common",
              groupId:"Common",
              children:[
                 { headerName : "ID" , field : "status.ID"},
                 { headerName : "ReportStatus" , field : "status.ReportStatus"},
                 { headerName : "TransactionReferenceNumber" , field : "status.TransactionReferenceNumber"}
                 
              ]
              }
```
My Custom Filter on Change event:
 ```
onChange(event, value) {
        var colId = this.props.colId;
        var filterInstance = this.props.api.getFilterInstance(colId);
        if (filterInstance) {
            filterInstance.setModel({ filter: value, type: 'contains'});
            this.props.api.onFilterChanged();
        } 
    }
```
**Bug**: If I enter any value to filter it wipes all table row data and only headers are shown. The filter does not work. No error.

**Expected behavior:**
It should filter. If I remove the column group COMMON and provide all children headers in columnDefs this works fine.

**Environment**:
Windows 7
Chrome v59
"ag-grid": "^11.0.0",
 "ag-grid-enterprise": "^11.0.0",
 "ag-grid-react": "^10.0.0"

**Comment by Ajaybhardwaj7** [comment]
Found the actual cause. ColDefs were not updated properly with filter props. Apologies for that.

**Comment by seanlandsman** [comment]
Hi,

Thanks for following up!
