### ISSUE TITLE
Bug: Not Contains does not return blank or null values

### ISSUE THREAD

**Issue by killyosaur** [ceolter/ag-grid#1773]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When I have a column with blank or filled values, if I type a value and select not contains, blank values do not return despite the fact that they do not contain the typed in value.

**Expected behavior**
When I filter by not contains, I should see all values that do not contain the value including the blank values.

**Minimal reproduction of the problem with instructions**
This can be seen on the documentation for the text filter: https://www.ag-grid.com/javascript-grid-filter-text/?framework=all#gsc.tab=0 
in order to get it to happen, 
1. sort the athletes (there are 3 with no names)
2. change sort to "not contains"
3. type a value (i.e. "aaron")
the values with nothing in them will also fail to show despite not containing "aaron"

**What is the motivation / use case for changing the behavior?**
I am using the grid to display data for a variety of document sources and some of the fields have the possibility of not being populated

**Please tell us about your environment:**
Windows 7/10, IE11 (though I can replicate it in Chrome).

* **ag-Grid version:** 10.0.0 & 12.0.0

* **Browser:**
IE11, Chrome 58

* **Language:** ES5

**Comment by makinggoodsoftware** [comment]
This has been fixed and it will be available in the next release
