### ISSUE TITLE
No way to explicitly set row model to inMemory

### ISSUE THREAD

**Issue by gregbown** [ceolter/ag-grid#1780]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In version 11 use of rowModelType: "normal" was the documented way to specify the in memory row model.
In version 12 using rowModelType: "normal" will cause error: "cannot call setRowData unless using normal row model"
And the grid then fails to call setRowData
Using rowModelType: "inMemory" as the [documentation now seems to elude to](https://www.ag-grid.com/javascript-grid-row-models/?framework=all#gsc.tab=0) will cause a different error: "ag-Grid: count not find matching row model for rowModelType inMemory" however; the grid will default to the correct row model.
Omitting the setting rowModelType will cause the grid to default to the desired in memory row model however the documentation clearly states 
> Set it to one of {inMemory, infinite, viewport, enterprise}

**Expected behavior**
Either the support of the prior setting, directions to omit the setting, a new way to achieve setting the row model to in memory or listing it as a breaking change.

**Minimal reproduction of the problem with instructions**
Both described settings are commented out, but you can un-comment to verify.
[Plnkr](https://plnkr.co/edit/S94PxG?p=preview)

**What is the motivation / use case for changing the behavior?**
There used to be a clear direction of what setting to use so most likely this will only be a documentation update.

**Please tell us about your environment:**
Windows 10, Chrome Version 56.0.2924.87, Angular 4.3.1, Typescript 2.4.1, Webpack 3.3.0, Node 6.10.2, npm 4.0.2, ag-Grid 12.0.0, ag-Grid Angular 12.0.0

**Comment by seanlandsman** [comment]
Hi

I've taken a look and can see what you mean. I've raised AG-636 our side to track this - we'll update this thread with updates as soon as we have any

thanks

**Comment by ceolter** [comment]
workaround - set it explicitly to 'undefined'

**Comment by makinggoodsoftware** [comment]
Hi Just to let you know that we have just released a patch release for this.
