### ISSUE TITLE
Column Menu button always Visible

### ISSUE THREAD

**Issue by jogibear9988** [ceolter/ag-grid#1782]
Is there a way, to make the Column Menu Button (the 3 Lines) always visible? Not only on mouseover?

**Comment by uvtzxpm** [comment]
`suppressMenuHide`

> Set to true to always show the column menu button, rather than only showing when the mouse is over the column header.

https://www.ag-grid.com/javascript-grid-properties/#gsc.tab=0

**Comment by jogibear9988** [comment]
thanks
