### ISSUE TITLE
Slower release cycle with fewer breaking changes

### ISSUE THREAD

**Issue by mischkl** [ceolter/ag-grid#1788]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Every month a new major release happens which often breaks a lot of stuff.

**Expected behavior**
Major releases happen at most every half year and incur minimal upgrade costs.

**What is the motivation / use case for changing the behavior?**
Enterprise customers need stability. AG Grid is at the moment anything but stable if you want to stay remotely close to the newest version.

**Please tell us about your environment:**
Angular 4

* **ag-Grid version:** 9.x, attempting to upgrade to newest

* **Browser:**
N/A

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by seanlandsman** [comment]
Hi,

We've taken this on board - I appreciate 12.x especially had a lot of breaking changes and I know that this can be frustrating.

I've raised it with the team and we will endeavour to reduce this kind of noise going forward

**Comment by uvtzxpm** [comment]
I've usually found it quite easy if you upgrade to the new versions as they come. I can imagine trying to go from v9 to v12 could be difficult though.
