### ISSUE TITLE
Change request - AngularJS & Angular

### ISSUE THREAD

**Issue by AmitMY** [ceolter/ag-grid#1794]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In some docs you use Angular 2, in some AngularJS, AngularJS 1.
In code, the initialization method is `initialiseAgGridWithAngular1`

**Expected behavior**
Use the names `Angular` and `AngularJS`
Not a pressing matter, just a nice change to see

**What is the motivation / use case for changing the behavior?**
Angular 2 is long gone, Angular 4 is currently out, and 5 is in beta. This is just the preferred naming by the angular team

**Comment by seanlandsman** [comment]
Hi @AmitMY - this is something we'd like to do and are aware of the naming change, but a lot of our users aren't I'm afraid.

We found that there was some confusion - at least initially - when we replaced Angular 2 with just Angular.

I think this will remain as is for at least another few months after which we will switch to the new names.

Thanks for the suggestion though :-)
