### ISSUE TITLE
Default sorting by string values has changed from case-insensitive to case-sensitive

### ISSUE THREAD

**Issue by basvandenberg** [ceolter/ag-grid#1795]
**I'm submitting a ...**
```
[x ] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Currently (after updating from v8 to version v12) sorting rows by string values is by default case-sensitive, so a column with values: "a", "B",  and "c", will be sorted as:
- B
- a
- c 

**Expected behavior**
I'm not sure what the specified behavior is, but in version 8 the default string sort was case insensitive, resulting in the following order:
- a
- B
- c

**What is the motivation / use case for changing the behavior?**
The default sorting behavior seems to have changed. Since I could not find anything about this in the release notes\* I thought this might have happened unintentionally. 

The change seems to be introduced in this [commit](https://github.com/ceolter/ag-grid/commit/e5f9327a61545251997439a4c44bc24e41bb031e), where the default `localeCompare` is replaced with a `doQuickCompare` function.

Or should the 'accentedSort' be used for case insensitive sort? In which case it would be nice to have this mentioned in the documentation.

\* I updated from 8 to 12, so I had to go through quit some release notes and might have missed this.

**Please tell us about your environment:**

* **ag-Grid version:** 12.0.1

* **Browser:**
All

**Comment by ceolter** [comment]
this was done on purpose, to allow for quicker comparing when you don't get impacted by case.

to have it work as previous, attach your own 'default' comparator to the default col def, ie:
```
gridOptions = {
  defaultColDef = {
      comparator: function(a,b) {
          if (typeof a === 'string') {
               return a.localCompare(b);
          } else {
               return (a > b ? 1 : (a < b ? -1 : 0));
          }
      }
  }
  ...
}
```

**Comment by petyosi** [comment]
The snippet from @ceolter above contains a typo ( `localCompare -> localeCompare`).

```js
gridOptions = {
  defaultColDef = {
      comparator: function(a,b) {
          if (typeof a === 'string') {
               return a.localeCompare(b);
          } else {
               return (a > b ? 1 : (a < b ? -1 : 0));
          }
      }
  }
  ...
}
```

**Comment by vikasnawal** [comment]
var dateformat = /^(0?[1-9]|[12][0-9]|3[01])[\/\-.](0?[1-9]|1[012])[\/\-.](?:[0-9]{2})?[0-9]{2}$/;
  

  // Match the date format through regular expression
  if(inputText.match(dateformat))
  {

**Comment by vikasnawal** [comment]
function validatedate(inputText)
  {
 var dateformat = /^(0?[1-9]|[12][0-9]|3[01])[\/\-.](0?[1-9]|1[012])[\/\-.](?:[0-9]{2})?[0-9]{2}$/;

**Comment by vikasnawal** [comment]
function validatedate(inputText)
  {
 var dateformat =' /^(0?[1-9]|[12][0-9]|3[01])[\/\-.](0?[1-9]|1[012])[\/\-.](?:[0-9]{2})?[0-9]{2}$/';

**Comment by vikasnawal** [comment]
`function validatedate(inputText)
  {
 var dateformat = /^(0?[1-9]|[12][0-9]|3[01])[\/\-.](0?[1-9]|1[012])[\/\-.](?:[0-9]{2})?[0-9]{2}$/;`

**Comment by ISkomorokh** [comment]
`GridOptions` now has a property `accentedSort` for this.
