### ISSUE TITLE
Empty space at the bottom of grid

### ISSUE THREAD

**Issue by katasup** [ceolter/ag-grid#1797]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Currently you can see extra empty space after last row. Reproduced when floating bottom row enabled.
<img width="972" alt="2017-08-01 23 41 11" src="https://user-images.githubusercontent.com/3366664/28846254-65123cce-7713-11e7-968c-16a1a3cf00f3.png">

**Expected behavior**

I guess this shouldn't be here.

**Minimal reproduction of the problem with instructions**

https://www.ag-grid.com/react-examples/examples/?fromDocs&example=floating-row
https://plnkr.co/edit/Of88H3?p=preview

* **ag-Grid version:** 12.0.2

* **Browser:** Chrome, Safari

* **Language:** All

**Comment by seanlandsman** [comment]
Hi,

This is expected behaviour - if you have a grid of a certain height where the rows + header heights dont exactly fit there will be an amount of space left over. You can try this by setting the grid height to 700px for example

**Comment by katasup** [comment]
<img width="954" alt="2017-08-02 13 16 10" src="https://user-images.githubusercontent.com/3366664/28869261-cc9e4998-7784-11e7-957f-20e6254cb5d3.png">

Empty space always there, even grid height equals rows height.

**Comment by katasup** [comment]
Any news?

**Comment by rrhvella** [comment]
I have also encountered this issue. Is it possible to get it fixed?

**Comment by petyosi** [comment]
That's the fix for it: https://github.com/ag-grid/ag-grid/commit/f037ba13ee728e2e0fc84208cb16ffd1029dcd7e#diff-374544943f4ef689f74fd75c395193d0R576

**Comment by katasup** [comment]
@petyosi yup, but this breaks pinned columns. Also, check RTL mode.
