### ISSUE TITLE
HTMLElement is not defined

### ISSUE THREAD

**Issue by CindySLiu** [ceolter/ag-grid#1798]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I'm using .Net Core Angular VS2017 template to create VS2017 project (following the url https://long2know.com/2017/04/net-core-angular-vs2017-templates/). The sample project works well with Angular version 4.0 up and webpack 2.5 up. Then I added 
		"ag-grid": "^10.0.0",
		"ag-grid-angular": "^10.0.0",
in my package.json and modified app.module.shared.ts as following:

```
import { NgModule } from '@angular/core';
import { RouterModule } from '@angular/router';

import { AppComponent } from './components/app/app.component'
import { NavMenuComponent } from './components/navmenu/navmenu.component';
import { HomeComponent } from './components/home/home.component';
import { FetchDataComponent } from './components/fetchdata/fetchdata.component';
import { CounterComponent } from './components/counter/counter.component';

import { AgGridModule } from "ag-grid-angular/main";

export const sharedConfig: NgModule = {
    bootstrap: [ AppComponent ],
    declarations: [
		AppComponent,

        NavMenuComponent,
        CounterComponent,
        FetchDataComponent,
        HomeComponent
    ],
    imports: [
		AgGridModule,
       RouterModule.forRoot([
            { path: '', redirectTo: 'home', pathMatch: 'full' },
            { path: 'home', component: HomeComponent },
            { path: 'counter', component: CounterComponent },
            { path: 'fetch-data', component: FetchDataComponent },
            { path: '**', redirectTo: 'home' }
        ])
    ]
};

```
When I ran my code, I got the following error:

An unhandled exception occurred while processing the request.

Exception: Call to Node module failed with error: Prerendering failed because of error: ReferenceError: HTMLElement is not defined
at Object.setPrototypeOf.__proto__ (C:\MyProjects\VS2017\WebPageProider\ClientApp\dist\main-server.js:17514:31)
at __webpack_require__ (C:\MyProjects\VS2017\WebPageProider\ClientApp\dist\main-server.js:20:30)
at Object.defineProperty.value (C:\MyProjects\VS2017\WebPageProider\ClientApp\dist\main-server.js:31692:20)
at __webpack_require__ (C:\MyProjects\VS2017\WebPageProider\ClientApp\dist\main-server.js:20:30)
at Object.c (C:\MyProjects\VS2017\WebPageProider\ClientApp\dist\main-server.js:6859:20)
at __webpack_require__ (C:\MyProjects\VS2017\WebPageProider\ClientApp\dist\main-server.js:20:30)
at Object.c (C:\MyProjects\VS2017\WebPageProider\ClientApp\dist\main-server.js:11994:23)
at __webpack_require__ (C:\MyProjects\VS2017\WebPageProider\ClientApp\dist\main-server.js:20:30)
at Object.c (C:\MyProjects\VS2017\WebPageProider\ClientApp\dist\main-server.js:21106:18)
at __webpack_require__ (C:\MyProjects\VS2017\WebPageProider\ClientApp\dist\main-server.js:20:30)
Current directory is: C:\MyProjects\VS2017\WebPageProider
Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance+<InvokeExportAsync>d__7.MoveNext()

**Expected behavior**
No error when importing ag-grid.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
VS2017,
@angular/cli: 1.2.1
node: 7.8.0
os: win32 x64
angular/animations: 4.1.2
angular/common: 4.1.2
angular/compiler: 4.1.2
angular/core: 4.1.2
angular/forms: 4.1.2
angular/http: 4.1.2
angular/platform-browser: 4.1.2
angular/platform-browser-dynamic: 4.1.2
angular/platform-server: 4.1.2
angular/router: 4.1.2

* **ag-Grid version:** X.X.X
+-- ag-grid@10.1.0
`-- ag-grid-angular@10.1.0

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.2 up

**Comment by seanlandsman** [comment]
Hi,

First, you need to import AgGridModule differently now - please see https://www.ag-grid.com/angular-more-details/  for more information

Secondly, this error is probably because you're doing some sort of server side compilation - is this the case?

**Comment by CindySLiu** [comment]
Yes, you are right. I have to disable server side compilation. I first moved ag-grid import to app.module.client.ts so the server module doesn't have ag-grid. It didn't work. So I disabled server side compilation and it works. Can you tell me why server side compilation affects ag-grid?

Thanks in advance!!!

**Comment by seanlandsman** [comment]
As the grid is designed for use in the browser, server side compilation wasn't really considered at design time

There is a ticket for adding support for this our side - AG-258. You can track it's progress on our pipeline page here: https://www.ag-grid.com/ag-grid-pipeline/
