### ISSUE TITLE
Change detection of keypress event target 

### ISSUE THREAD

**Issue by dkopitsa** [ceolter/ag-grid#181]
I have angular rendered cell with always visible input element. When I press 'space' in focused input, the line is selected. 
In than moment event.currentTarget is eGridCell and event.target is my input element. 

Please change 

```
        if (event.currentTarget !== eGridCell) {
            return;
        }
```

to 

```
        if (event.target !== eGridCell) {
            return;
        }
```

**Comment by ceolter** [comment]
working though old issue,s i searched code for "event.currentTarget" and couldn't find. so think this issue is no longer valid given the code has moved on. if still an issue, please reopen.
