### ISSUE TITLE
Add class to whole row to indicate hover (required when columns are pinned to highlight whole row)

### ISSUE THREAD

**Issue by jonsamwell** [ceolter/ag-grid#223]
Hi,

If you have a pinned column and you want to say change the background colour when any of the row is hovered over it currently will not work due to the pinned column(s) and non-pinned column(s) not being under the same parent.  If you could add a class to the pinned and non-pinned row/columns to indicate the mouse is over them this would solve the problem.

Here is a Plunker which highlights the issue.

http://plnkr.co/edit/vXJNaoDgsRRGJbwVR9Lx?p=preview

Thanks,

Jon

**Comment by ceolter** [comment]
noted. thanks.

**Comment by MikaAK** [comment]
+1 Is this still non-existant? We cannot use this at work without hover functionality in place.

**Comment by Sergeykp** [comment]
+1

**Comment by chiptus** [comment]
can't you just use .ag-row:hover? that's how we do it

**Comment by Sergeykp** [comment]
.ag-row:hover will not work correctly, when you have pinned columns

**Comment by mpetkov** [comment]
+1

**Comment by antru** [comment]
+1

**Comment by ceolter** [comment]
already done. class is ag-row-hover

**Comment by jlarso11** [comment]
Is there a way to remove the default color for this?  I want to control the color myself in CSS

**Comment by ceolter** [comment]
@jlarso11 it's css - so if you lay your css out correctly, your style will get used.

**Comment by LinnykS** [comment]
ag-row-hover class working properly only when you hover pinned column but what about highlighting the pinned rows when the main rows hover?
