### ISSUE TITLE
Support for show/hide columns

### ISSUE THREAD

**Issue by nileshmali** [ceolter/ag-grid#23]
It would be great if you provide support for show/hide columns.
E.g. 
https://datatables.net/extensions/colvis/

**Comment by lukelalo** [comment]
Have you tried changing the columnDefs attribute and calling the onNewCols() api method?

**Comment by tannerlinsley** [comment]
maybe an active property on the colDef?

**Comment by ceolter** [comment]
mixed feeling about this - typically i would just set the list of columns
again as mentioned above.

does this imply a gui for selecting columns to show also?


On 19 April 2015 at 05:40, Tanner Linsley <notifications@github.com> wrote:

> maybe an active property on the colDef?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/angular-grid/issues/23#issuecomment-94234916>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by nileshmali** [comment]
@ceolter Yes. This will have gui to show/hide columns.

**Comment by jongravois** [comment]
I like ng-grid's show/hide gui where each colDef has a visible value that defaults to true but when false hides the column. Makes it very easy in columnDefs to programmatically trigger the show/hide.

**Comment by nileshmali** [comment]
Any plans to implement this?

**Comment by ceolter** [comment]
Yes. I plan to do this. About 6 weeks out.

**Comment by nitech** [comment]
+1

**Comment by nileshmali** [comment]
Sorry to reiterate, but is this still on your radar?

**Comment by ceolter** [comment]
show / hide columns is done. see the column api.

**Comment by saurabhraja** [comment]
Hi,

Is there an option to show/hide column group? I checked the api documentation and couldn't find any method for the same. We already have an option to show/hide a column or a set of columns using setColumnsVisible() also we have an option to set group column opened or closed using setColumnGroupOpened() but no such option for setColumnGroupShow(). 

Thank you.

**Comment by jfstephe** [comment]
I too have wasted time looking for this. Can we get something in the docs to say 'hide all columns = hide the group' (assuming that's what we have to do).

**Comment by PedramMarandi** [comment]
Me either, it would be great to hide group cols.

**Comment by marslan2037** [comment]
this.columnApi.setColumnsVisible(colId, false)
this is not working for me, i tried it with different ways, like 
this.columnApi.setColumnsVisible(headerName, false)
this.columnApi.setColumnsVisible(object, false)

its not working, no error and nothing is happening.
i have columnApi from onGridReady function
