### ISSUE TITLE
Custom Themes with the new update 18

### ISSUE THREAD

**Issue by PierBJX** [ceolter/ag-grid#2452]
**Current behavior**
I am following this [page](https://www.ag-grid.com/javascript-grid-styling/#customizing-sass-variables) to customise my table but it does not work on the version 18.

**Expected behavior**
I downloaded the example version available on  [GitHub](https://github.com/ag-grid/ag-grid-customise-theme) and it works. However this version is 17.

**What is the motivation / use case for changing the behavior?**
We are trying to mimic the Merge Cells feature in Excel, and we have an nested ag-grid component that expands and contracts as the user adds and removes rows from this nested component. This is the only way that we can dynamically add rows to specific columns only, and grouping the other row cells around these rows.

**Please tell us about your environment:**
OS: Linux
IDE: Visual Code
Package Manager: NPM
HTTP Server: Node/Express

    **ag-Grid version:**
    18.0.1

    **Browser:**
    Firefox

    **Language:**
    TypeScript

**Comment by makinggoodsoftware** [comment]
Hi

Just to let you know that ag-grid staff is now going to monitor this thread to help find an answer to this issue (hence the ag-grid engaged label)

Thanks for all the feedback

**Comment by makinggoodsoftware** [comment]
Just checking, are you saying that our example in github if you upgrade it to v18 it does not work?

Have you tried with v19?

Thanks
