### ISSUE TITLE
[selection] have up / down keys change selection

### ISSUE THREAD

**Issue by ceolter** [ceolter/ag-grid#246]
http://www.angulargrid.com/forum/showthread.php?tid=2248

**Comment by elgerm** [comment]
+1

**Comment by tiwarisnehal** [comment]
+1

**Comment by sandves** [comment]
+1

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-53

**Comment by ceolter** [comment]
the documents were updated, it's possible to do this without changes in the grid.
https://www.ag-grid.com/javascript-grid-selection/#gsc.tab=0
