### ISSUE TITLE
Read-only custom floating filter not working

### ISSUE THREAD

**Issue by pshurygin** [ceolter/ag-grid#2492]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When implementing a read-only floating filter using getModelAsString method as described in documentation, the filter does not work correctly. Whenever you change parent filter value and afterwards clear it you get
`Uncaught TypeError: Cannot read property 'operator' of null
 at currentParentModel `
error in console. The error is also present in the official example in the documentation page.

**Expected behavior**
You can successfully change and clear filter values when custom read only floating filter is present.

**Minimal reproduction of the problem with instructions**
Look at this example: https://www.ag-grid.com/javascript-grid-floating-filter-component/#custom-filter-and-read-only-floating-filter-example
Try to enter any filter value, then remove this value to clear the filter => you get console error.

**Please tell us about your environment:**
Latest Chrome on Windows

* **ag-Grid version:** 18.1.0

**Comment by amramamohanreddy** [comment]
My read-only custom floating filter was working very well before I migrate to version 18.1.1.
Currently, I'm facing the same issue. When I tried to navigate to some other page. it's not allowing me with a bunch of stupid errors on the console. I have to refresh my whole page to move ahead.
I had a quick workaround for this.
If you set up the getModel returns blank filter, it would allow to clear the filter and ignores this errors. However, it's it's considered the filter applied to this field but the filter, type and filterType are null/blank.

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks
