### ISSUE TITLE
Provide access to default renderer for headers and cells

### ISSUE THREAD

**Issue by greglockwood** [ceolter/ag-grid#258]
It would be very helpful to have access to the default renderer for data cells and header cells via the params object.

This would enable you to invoke the original renderer and then extend/modify the result. Or, alternatively, it allows you to have one column that renders differently, whereas the rest use the default renderer.

Without this feature, you either get the default renderer, which is really nice, or you have to completely replicate it in order to have a special column.

My specific use case was that I wanted to render a button in the top left cell, which had a blank `headerName` specified, but then use the default renderer, which shows the nice filter and sort icons, for the rest of the columns. I ended up having to use the `ready` callback to use jQuery to insert my button after the grid had rendered for the first time. This isn't ideal, as you can definitely see the grid render, then the button get added a short time later.

**Comment by ceolter** [comment]
the current header template allows this.
