### ISSUE TITLE
Hide/show column from button in column.

### ISSUE THREAD

**Issue by Fangmingdu** [ceolter/ag-grid#264]
Hello,

I tried the new function for reordering and show/hide column from the tool panel. It's good.
But it takes extra space and extra button to get there. 
Can you take a look at the UI below? When the user mouse over the column header, there are two buttons show, one for filtering and one for show/hide column. This is more intuitive.
And for the reordering, it would be great if the user can do it by drag/drop on column header.

![grid_show_hide](https://cloud.githubusercontent.com/assets/5725594/8309391/047a0e9c-1990-11e5-9de4-3a105c96f559.png)

//Link
http://zippyui.com/react-datagrid/#/examples/filtering
http://zippyui.com/react-datagrid/#/examples/reorder-columns

**Comment by ceolter** [comment]
it's on my list of items to do, to vamp up the menu. i plan on allowing the column reordering here like you say, in addition to the toolbar. all in the big play :)

**Comment by thisisbinod** [comment]
That would be a nice feature. Also for consistency, it would be great if funnel icon instead of hamburger icon be used for mouse hovering over filter.

**Comment by cp2587** [comment]
+1, solution found by react-datagrid is awesome. Having it in your project would be a big plus (although your library is really great as is, especially on the performance side) !

**Comment by santosh-k1** [comment]
Can you provide any example by using angular with ag-grid.. @Fangmingdu you have used below url with react http://zippyui.com/react-datagrid/#/examples/filtering.. so can you provide demo angular with ag-grid !
