### ISSUE TITLE
Filters do not reset in IE 9

### ISSUE THREAD

**Issue by kenobi883** [ceolter/ag-grid#271]
I am having trouble with some of the filtering functionality. In IE 9, using any of the built in filters (set, number, text), if you type a value in, the filter applies successfully, but if you delete the value in the input field, the filter does not remove itself. For instance, in the linked JSBin:
1. Click the button for the set filter on Role.
2. Type "dev" into the filter box.
3. Only "Developer" shows in the list.
4. Delete or backspace over "dev".
5. "Developer" is still the only value in the list.

In other browsers, removing the text resets the filter. Any ideas?

http://jsbin.com/lutahe/edit?html,js,output

**Comment by ceolter** [comment]
this is working for me, but I'm using IE 11. can anyone advise on this, why IE 9 different?

these are the events i listen on:
    element.addEventListener("changed", listener);
    element.addEventListener("paste", listener);
    element.addEventListener("input", listener);

so looks like IE9 is calling NONE of the above when you hit delete???

**Comment by thomas3577** [comment]
You can test by yourself. Open IE11, press F12, click on the tab "Emulation" and change Dokumentmodus to "9"

**Comment by ceolter** [comment]
When i do that, it doesn't work at all, I get "angular is undefined".

![image](https://cloud.githubusercontent.com/assets/6539563/8388057/0904ae72-1c56-11e5-84a0-aa3f0b042149.png)

**Comment by thomas3577** [comment]
It seems you have a little problem with IE9. I was testing the examples on your website. I don't get this error, but i can't see the grid.

**Comment by ceolter** [comment]
Will check.....

**Comment by rmuchall** [comment]
I recommend the following for testing in different browsers:
http://spoon.net/browsers
It costs a small amount but well worth it for the time saved :)

**Comment by ceolter** [comment]
@rmuchall spoon is interesting. how much does it cost? i can't seem to find pricing on their site.

**Comment by rmuchall** [comment]
It costs 24 USD per month for the "build plan". This gives you access to the complete browser repository. I think you need to create an account and then subscribe. Spoon don't seem to advertise much, I think they mostly cater to the enterprise market.

**Comment by ceolter** [comment]
is this still broken?
