### ISSUE TITLE
Support for nested properties in field column definition

### ISSUE THREAD

**Issue by juanrapoport** [ceolter/ag-grid#28]
Hi @ceolter, I found this grid very interesting!

Could you please add support to map columns to nested data properties? 

```javascript
var data = [{
	name: 'juan',
	address: {
        street: '9 de Julio 544',
        city: 'Montevideo'
    }
}]

var coldef = [{
    displayName: 'name',
    field: 'name'
},{
    displayName: 'City',
    field: 'address["city"]'
}]

```

**Comment by ceolter** [comment]
Yes I'll put that in in time.

However you can still achieve this, by providing your own cell renderer. You don't have to return back HTML from the renderer, you can simple pass back a string that's a value. In your example:
'''
var coldef = [
displayName: 'name',
cellRenderer: function(params) { return params.data.address.city}
];
'''

**Comment by juanrapoport** [comment]
That's very useful,
Thank you very much.

**Comment by ceolter** [comment]
Welcome!

**Comment by tannerlinsley** [comment]
This would be useful.  :+1:

**Comment by vivektodi** [comment]
I found that once we use cellRenderer to render fields from nested data, we cannot use filters on that column. 

@ceolter should I open this as an issue?

**Comment by ceolter** [comment]
the new 'value getter' should be user to populate the filter values. it's on my list.

**Comment by sbowler** [comment]
I'm really surprised this hasn't been implemented yet. Maybe we can get a bump up on this in the priority.

**Comment by ceolter** [comment]
because it can be done with value getter, i didn't see the rush. is there a reason for not using valuegetter?

**Comment by ceolter** [comment]
nested properties is done. will be in the next release.

**Comment by juanrapoport** [comment]
Great news! Thank you very much.

**Comment by syllant** [comment]
Note that nested properties are now supported for display, but not for edition (code [here](https://github.com/ceolter/ag-grid/blob/bc76142e92bfdf9e230b030a3797bb1603ffb4b6/src/ts/rendering/renderedCell.ts#L301) updates the property supposing it corresponds to a top level field name).

This can be easily solved by customizing the cell edition (e.g. with [newValueHandler](https://ag-grid.com/angular-grid-editing/index.php)), but this might be added in the todo list to make this nested property support more consistent (not sure if I should open a separate issue).

**Comment by ceolter** [comment]
fixed. now you can edit with embedded fields. with be in next release.

**Comment by caminic** [comment]
Hi Nail, had a quick question on this

I tried the following and it works, but then it seems like the filtering doesn't work well: 
`cellRenderer: function (params) { return params.data.DomainType.DomainTypeDesc }`

Referring to your latest comment does that mean that I can now using something like:
`"headerName": "Domain Type", "field": "data.DomainType.DomainTypeDesc", "width": 200`

Also, that would be in v4 right?

Thanks

**Comment by ceolter** [comment]
i just tested, seems to be working fine:
![image](https://cloud.githubusercontent.com/assets/6539563/13700893/b5d46412-e77b-11e5-8a91-ae3b9ec772e8.png)

i updated my example to put game into a new structure:
```
game = {
 name: xxx,
 bought: yyy
}
```
and it worked fine

**Comment by santhoshsoundar** [comment]
Hi @ceolter , have a quick question regarding attaching multiple keys to a column for search, for example: For 1 row 
`data = { Column_Name:Metrics, 
                Values: {{key: 'metricA', value: '0.3'}, 
                             {key: 'metricB', value: '0.7'}, 
                             {key: 'metricC', value: '0.9'}}} }`

I would like to know if I can run a search on metricA and metricB separately., I am looking to build the search fields outside the ag-grid as a separate panel., I am trying to get in touch with ag-grid support team if there is any examples & I have not got a response yet., 
<img width="1331" alt="screen shot 2019-02-04 at 2 16 39 pm" src="https://user-images.githubusercontent.com/14152628/52241151-cd34db00-2887-11e9-8523-9ae05ef9a24d.png">

**Comment by santosh626** [comment]
I have nested data. wanted to achieve sorting based on one of nested properties. I have used filterValueGetter to filter but did not came across any such function w.r.to sorting.

**Comment by junaidahmed501** [comment]
I have been trying to feed the remote data that is very much nested & not just one level but it contains 3 level nesting.
Please have a look at the attached video which is my actual data coming from the backend. There is an image attached as well which shows what I want to achieve.

I had reached out to the support team as well but their suggestion of using **Master-Detail config** doesn't work for me as having subgrids is not something I want. 

Just sharing my data model in case it helps. 

```
interface RootObject {
--> tourStops: TourStop[];
physicalStatus: string;
tenantId: string;
id: string;
tourName: string;
planningStatus: string;
processingStatus: string;
deliveryDate: string;
plannedDistance: number;
weight: number;
packageCount: number;
vehicles: string;
drivers: string;
plannedArrival?: any;
}

& the subsequent interfaces/models that the RootObject need are:

interface TourStop {
processingStatus: string;
physicalStatus: string;
tenantId: string;
id: string;
locationId: string;
tourId: string;
plannedDistance: number;
stopLocation: StopLocation;
--> orders: Order[];
weight: number;
packageCount: number;
plannedArrival?: any;
timeWindow: string;
}

export interface Order {
--> packages: Package[];
physicalStatus: string;
id: string;
orderNumber: string;
targetDeliveryDateTime: Date;
unitCount: number;
weight: number;
volume?: any;
isDummyOrder: boolean;
returnedEmptiesCount: number;
sourceLocationId: string;
sourceAddressId?: any;
destinationLocationId: string;
destinationAddressId?: any;
packageCount: number;
}

export interface Package {
removedAt?: any;
id: string;
weight: number;
tourId: string;
orderId: string;
shippingUnitIdentifier: string;
dangerousGoods: boolean;
physicalStatus: string;
processingStatus: string;
stackability: Stackability;
size: Size;
actionType: string;
}
```


https://user-images.githubusercontent.com/12663872/135808323-a81aa4f3-70d2-4276-924a-bcbadd607a6d.mp4


https://user-images.githubusercontent.com/12663872/135808792-9a159a40-6abd-44b8-adf6-f189ee93e323.mp4



![Screenshot from 2021-09-30 22-39-37](https://user-images.githubusercontent.com/12663872/135808316-5fd2a1ed-b734-46ae-975b-5918bcdb50e5.png)
