### ISSUE TITLE
[filter] Add range filter for Number

### ISSUE THREAD

**Issue by Fangmingdu** [ceolter/ag-grid#284]
The number filter only has greater than, equals, or less than.

It is better to have a range filter like, greater than 3 and less than 5. This is pretty common.

Thanks!

**Comment by ceolter** [comment]
in the mean time, you can implement your own custom filter :)

**Comment by Fangmingdu** [comment]
Thanks for letting me know! That's a good idea.

**Comment by ceolter** [comment]
to be honest, most people will end up creating their own filters, if you use generic filters your app will look very, well, generic. so my plan was just give a few to show how it's done, but really you should be building your own for your own apps needs.

**Comment by priyanka813** [comment]
The number filter has equals, not equals, greater than and  less than.
I want to add   =, != , > ,  <  instead of that.
Then how can I edit these labels in number filter.

![number_filter](https://cloud.githubusercontent.com/assets/19928173/18409619/1a124cc8-7769-11e6-813f-4d0c83d13b0c.png)

**Comment by ceolter** [comment]
@priyanka813 
change it as described here:
https://www.ag-grid.com/javascript-grid-internationalisation/index.php

**Comment by alexmallet** [comment]
@Fangmingdu @priyanka813 

I think you will find what you're looking for here: https://www.ag-grid.com/javascript-grid-filtering/

**Comment by ceolter** [comment]
tracked  by https://ag-grid.atlassian.net/browse/AG-55

**Comment by makinggoodsoftware** [comment]
This has been added, it will be available in the next release
