### ISSUE TITLE
Select all checkbox not un-check when any checkbox marked as un-select

### ISSUE THREAD

**Issue by sachingvit** [ceolter/ag-grid#2860]
**I'm submitting a bug report**

**Providing a Reproducible Scenario**

When I am create a grid with checkbox in row and having select all, 

Step 1: check one by one all the row checkbox and at last select all will also get selected, 
Step 2: Now remove any checkbox, in this case **select all** should also need to get un-selected but its not working  
Plnkr: https://plnkr.co/edit/uzFPY0vPGGioU4026xC6?p=preview 

* **ag-Grid version:** 19.1.2
* **ag-Grid community version:** 19.1.4
* **ag-Grid community version:** 19.1.4

* **Browser:** Chrome

* **Language:** [TypeScript 3.1.6]

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license. (issues reported via GitHub)
ag-Grid Enterprise - our commercial version which funds the development of both versions. (issues reported via zendesk)

If you are a customer, you should be using ag-Grid Enterprise in which case you should have access to our customer support system (via zendesk), and that is the only channel where we accept feature requests.

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
