### ISSUE TITLE
Quick filter doesn't take new columns into account

### ISSUE THREAD

**Issue by topeju** [ceolter/ag-grid#288]
If I have a grid with some set of columns, then add a new one and call `$scope.gridOptions.api.onNewCols()` to show it, the quick filter does not take the values in the new column into account (i.e. the filtering is still done based on the original columns only).

**Comment by ceolter** [comment]
can you add all the columns from the start, just make the ones you don't mind with hide=true ???

**Comment by topeju** [comment]
Hmm, that wasn't an option for me earlier when I was using a somewhat older version of the grid, but I now updated to the latest version so `hide=true` would be possible. I'll give it a try.

**Comment by ceolter** [comment]
hide=true is pretty recent, about two weeks old feature.

**Comment by topeju** [comment]
It seems the quick filter also uses hidden columns for filtering? I think users would not expect that, as the result would have rows which don't seem to match the filter.

**Comment by ceolter** [comment]
Yea I think your right.

**Comment by ceolter** [comment]
can use api.resetQuickFilter()

**Comment by D-Shri** [comment]
I am using subgrid - grid inside a grid. And my quick filter for parent grid is not working. while it works for inner grid. have anyone tried this ..
