### ISSUE TITLE
expose doLayout and allow setInterval

### ISSUE THREAD

**Issue by ceolter** [ceolter/ag-grid#297]

**Comment by thomas3577** [comment]
Any news here? I really need that.

**Comment by ceolter** [comment]
doLayout is exposed in the API in last release. setting the interval is yet to be done.

**Comment by thomas3577** [comment]
Okay, now I use doLayout(). This works find for me.

**Comment by EndarValuk** [comment]
setInterval still not implemented. And perhaps, need to allow choice: work "on timer" or "specific event"

**Comment by ceolter** [comment]
added new property layoutInterval
