### ISSUE TITLE
Column Pinning left and right

### ISSUE THREAD

**Issue by danseid** [ceolter/ag-grid#31]
It would be great to pin the columns also on the right side of the table.

[An example](http://embed.plnkr.co/5Ag6gN8xaSyDnKNlowpK/).

**Comment by ceolter** [comment]
Thanks @danseid. There is a fair amount of work to a pinned 'section' and it's a rare requirement in my experience to require on on both the left and the right. So have put this on the 'nice to have' list. Would be interested in others opinions, is pinning on the left hand side a common requirement?

**Comment by vamsikrishnamannem** [comment]
Hi @danseid thank you for creating awesome grid. Your right this is use rarely but it is common requirement for present grids Please accept the PR.

**Comment by ceolter** [comment]
> Hi @danseid thank you for creating awesome grid

You can start by getting my name right!!!! :)

It's on my list, but very far down, lots of other changes to get in first.

**Comment by ceolter** [comment]
column pinning left and right is now in

**Comment by RajeevKashyap** [comment]
How to enable/disable left or right pinning in Aggrid? Any help will be appreciated.

**Comment by Shariqmo-kore** [comment]
Right column pinning feature become nightmare for me. Please let me know how can I disable this feature I am using ag-grid react.
