### ISSUE TITLE
Allow grid to open with a specific virtual page

### ISSUE THREAD

**Issue by erwin-beckers** [ceolter/ag-grid#320]
At the moment the grid always opens virtual page # 0 when using virtual paging.
It would be great if there was an option (in gridoptions) where we could override this behaviour and 
for example open the grid with virtual page #6

**Comment by lucasvall** [comment]
There is method in the API, `ensureIndexVisible(index)`. It may help you to do what you are trying to do.
Documentation [here](http://www.angulargrid.com/angular-grid-api/index.php)

**Comment by russell-miller** [comment]
`ensureIndexVisible` fails (as does `ensureNodeVisible`) for rows that are not loaded.

+1, I would also like a way to programmatically load a specific virtual page.

**Comment by ceolter** [comment]
api.ensureIndexVisible() now works. see example at end of this page:
https://www.ag-grid.com/javascript-grid-virtual-paging/

**Comment by TesterArvind** [comment]
nice
