### ISSUE TITLE
Feature request: include filter comparisonType in filterModel.

### ISSUE THREAD

**Issue by zman13** [ceolter/ag-grid#326]
The issue addresses the fact that in filterModel the field type =1 currently means equals if its a numeric field and contains if it's a string filter etc.... 
So if the property value contains a 3rd attribute that could give us the context for the type it would be easier to dynamically build filters.Thanks!

**Comment by ceolter** [comment]
sorry, i don't know what you mean, can you explain a little??

**Comment by zman13** [comment]
I was thinking if we had a propert called field type I could write a generic version of this type of thing which right now isn't too simple to reuse. Instead of testing for known fields I would test to see what type of filter it was

        function makeFilterString(value, property, i) {
            var retval = i == 0 ? "" : " and ";
            if (["Name", "Address", "Phone"].indexOf(property) > -1)
                if (value.type == 1)
                    retval = retval + "substringof('" + value.filter + "', " + property + ") eq true";
                else if (value.type == 2)
                    retval = retval + property + " eq '" + value.filter + "'";
                else if (value.type == 3)
                    retval = retval + "startswith('" + value.filter + "', " + property + ") eq true";
                else
                    retval = retval + "endswith('" + value.filter + "', " + property + ") eq true";
            else if (["numberOfBoxes","numberOfPeople"].indexOf(property) > -1) {
                if (value.type == 1)
                    retval = retval + property + " eq " + value.filter;
                else if (value.type == 2)
                    retval = retval + property + " lt " + value.filter;
                else if (value.type == 3)
                    retval = retval + property + " gt " + value.filter;
            }
            return retval;
        }
Thanks!

**Comment by ceolter** [comment]
ah ok, i understand. thanks for clarification.

**Comment by ceolter** [comment]
also mentioned again here. note to self: must get this fixed soon.

**Comment by dtslvr** [comment]
Any news on this? I have exactly the same difficulty to distinguish the type in the filterModel (text or numeric). Type 2 means 'exact match' but also 'less than'.

**Comment by dorogoy** [comment]
@dtslvr I just check if value.filter is a string or a number. For example with lodash you can use _.isNumber(value.filter) and _.isString(value.filter). It's not optimal, I agree, but it works for me.

**Comment by ceolter** [comment]
comparison types are now strings.
