### ISSUE TITLE
Bootstrap integration

### ISSUE THREAD

**Issue by stgunholy** [ceolter/ag-grid#34]
How is it possible to use bootstrap for grid styling? Then this grid will fit perfectly into rest of application.

**Comment by ceolter** [comment]
The "test-drive" example page is using bootstrap, it shows the grid working
alongside bootstrap. Is this enough or were you looking for something else?

On 3 April 2015 at 09:29, stgunholy <notifications@github.com> wrote:

> How is it possible to use bootstrap for grid styling? Then this grid will
> fit perfectly into rest of application.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/angular-grid/issues/34>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by stgunholy** [comment]
Yes, this I noticed, but thing is that grid looks really feature-intense but has not really modern look. the theme that would look/fit more into current trends of UI design will be welcomed! :) This is IMHO of course.

**Comment by ceolter** [comment]
can you send me an example of a bootstrap-themed grid?

On 3 April 2015 at 09:47, stgunholy <notifications@github.com> wrote:

> Yes, this I noticed, but thing is that grid looks really feature-intense
> but has not really modern look. the theme that would look/fit more into
> current trends of UI design will be welcomed! :) This is IMHO of course.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/angular-grid/issues/34#issuecomment-89225454>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by ceolter** [comment]
all honest opinions welcome!! (and taken with a pinch of salt)

On 3 April 2015 at 10:04, Niall Crosby <niall.crosby@gmail.com> wrote:

> can you send me an example of a bootstrap-themed grid?
>
> On 3 April 2015 at 09:47, stgunholy <notifications@github.com> wrote:
>
>> Yes, this I noticed, but thing is that grid looks really feature-intense
>> but has not really modern look. the theme that would look/fit more into
>> current trends of UI design will be welcomed! :) This is IMHO of course.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ceolter/angular-grid/issues/34#issuecomment-89225454>
>> .
>>
>
>
>
> --
> --
>
> The information transmitted is intended only for the person or entity to
> which it is addressed and may contain confidential and/or privileged
> material. Statements and opinions expressed in this e-mail may not
> represent those of the sender. Any review, retransmission, dissemination or
> other use of, or taking of any action in reliance upon, this information by
> persons or entities other than the intended recipient is prohibited. If you
> received this in error, please contact the sender immediately and delete
> the material from any computer.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by lukelalo** [comment]
This is a sample of a themed bootstrap table design
http://infinite-woodland-5276.herokuapp.com/tables.html

Is the theme we are using. Basically it seems to need the 'table' and other classes in the container layer, depending on the 'table' style you want to apply. Anyway, I don't think it is really possible to make the bootstrap themes work in your grid, basically because you don't have table, tbody, tr, th and td's. Only div's (and for me it's perfect the way you've done it)

There is anyway other approach that developers can use to apply bootstrap styles to your grid, like LESS. Creating a theme from one of yours and applying bootstrap themes to your classes seems the best way to fit a modern style to the grid.

Best regards
Pablo García

**Comment by ceolter** [comment]
Yes all the above makes sense. Maybe I can create a 'bootstrap' theme of my
own, matching colors, spacing etc, but not actually reusing the bootstrap
classes.

**Comment by ceolter** [comment]
Custom icons are now possible in the headers. Can put bootstrap icons into the headers now??

**Comment by impulz** [comment]
I took the fresh theme and modified it a bit to look like Bootstrap 3. It's a quick and dirty solution and I didn't make sure everything is perfect, but it might be a starting point: http://pastebin.com/iz3kVNc8  
Usage: Add to your CSS and set the class of the directive element to ag-bootstrap (class="ag-bootstrap")

**Comment by pauljoey** [comment]
I'm a big fan of the CSS implementation in angular-grid. The classes are clean, well-structured and named consistently. The separate themes/styling mean that styles are fully-decoupled. Adding a bootstrap-like theme with the existing class structure is very straightforward and I would recommend this over trying to introduce/introduce bootstrap classes into the angular-grid code base.

**Comment by ceolter** [comment]
Thanks for your comment Paul.

**Comment by nelreina** [comment]
+1 for pauljoey comments

**Comment by ceolter** [comment]
+1 from me also (I should of said that above). i particularly like the separation of style vs layout.

**Comment by tannerlinsley** [comment]
With the latest build in master, styles are now separated to avoid conflicting interests.
So it will be as simple as referencing `core.css`, and then building your own theme overrides based on one of the given themes.  I personally have a "flat" ui design that I'm using right now that simply overrides a few of the ag-fresh classes.  You will no longer have to use `!important` too ;)

**Comment by cplehew** [comment]
I have to imagine a great many Angular devs use Bootstrap (myself included). Being able to quickly integrate a grid without having to spend the afternoon styling would make ag-grid far more attractive.

Any chance you could incorporate a "theme-strap", essentially a Bootstrap-looking style as discussed above, into the core distribution?  

Side note: Given modern UI design could probably just ship with "theme-classic" (currently called "theme-fresh", though its not really :P ), "theme-dark", and "theme-strap".

Anyway, thanks for a great grid!

**Comment by ceolter** [comment]
Noted. Given time, will get it done.

**Comment by cplehew** [comment]
Great! Thanks again!

**Comment by musicthebee** [comment]
Can someone post any example they have with ag-grid and bootstrap? Greatly appreciate it.

**Comment by localhero** [comment]
Hi,
Is the Bootstrap theme available ?
Would love to use ag-grid but all my other UI components use Bootstrap.
Thanks.

**Comment by ceolter** [comment]
i haven't built one yet.

**Comment by localhero** [comment]
Hi,

Ok, no problem.
Do you have an idea of a roadmap for that feature ?

Thanks

David PERBAL
BNP Paribas Personal Finance
PFT / France Canaux Prescripteur (Nantes)
Tél: 02 28 03 70 21

De : Niall Crosby [mailto:notifications@github.com]
Envoyé : mardi 19 janvier 2016 14:49
À : ceolter/ag-grid
Cc : PERBAL David
Objet : Re: [ag-grid] Bootstrap integration (#34)


i haven't built one yet.

—
Reply to this email directly or view it on GitHub<https://github.com/ceolter/ag-grid/issues/34#issuecomment-172859088>.
 

Ce message et toutes les pièces jointes (ci-après le "message") sont 
établis à l'intention exclusive de ses destinataires et sont 
confidentiels. Si vous recevez ce message par erreur, merci de le 
détruire et d'en avertir immédiatement l'expéditeur. Toute utilisation 
de ce message non conforme a sa destination, toute diffusion ou toute 
publication, totale ou partielle, est interdite, sauf autorisation 
expresse. L'internet ne permettant pas d'assurer l'intégrité de ce 
message, BNP PARIBAS PERSONAL FINANCE (et ses filiales) décline(nt) 
toute responsabilité au titre de ce message, dans l'hypothèse ou il 
aurait été modifié. N'imprimez ce message que si nécessaire, pensez à 
l'environnement. 

--------------------------------------------- 

This message and any attachments (the "message") is intended solely for 
the addressees and is confidential. If you receive this message in 
error, please delete it and immediately notify the sender. Any use not 
in accord with its purpose, any dissemination or disclosure, either 
whole or partial, is prohibited except formal approval. The internet can 
not guarantee the integrity of this message. BNP PARIBAS PERSONAL 
FINANCE (and its subsidiaries) shall (will) not therefore be liable for 
the message if modified. Do not print this message unless it is 
necessary, consider the environment. 

---------------------------------------------

**Comment by ceolter** [comment]
it's currently not on my roadmap :(

**Comment by dileep8014** [comment]
Amazing tool , so many features would love to see bootstrap integrated to this tool :-)

**Comment by xfight0** [comment]
:+1:

**Comment by Amdingo** [comment]
Here's a *really* quick css for bootstrap-striped.  Haven't messed with the submenu stuff yet but I'm going to get to it.

https://gist.github.com/Amdingo/34a5f1b5155bf186e14d

**Comment by xfight0** [comment]
@Amdingo  Thank you, great work!

**Comment by supersabillon** [comment]
+1 on a bootstrap theme. Great work with the grid! Using it on an emberjs app.

**Comment by ceolter** [comment]
someone has given me some css for angular material. is there a bit difference between the style for angular material and bootstratp?

**Comment by bradparks** [comment]
without knowing much about it, if this would integrate with semantic-ui's themeing, then it might be able to easily take on 6 different theme types from there as well (Github, Amazon, Material, Bootstrap, Twitter, Semantic UI)

http://semantic-ui.com/ - Search on this page for "Unbeleivable themeing" for a demo

how it works, here:
http://semantic-ui.com/usage/theming.html

**Comment by supersabillon** [comment]
@ceolter  angular material and bootstrap are not quite the same

**Comment by ceolter** [comment]
thanks, will treat them separately in my head so.

**Comment by mikeerickson** [comment]
+1 I would love to see a pure bootstrap version

**Comment by mikeerickson** [comment]
@Amdingo would you mind telling me how you integrated this into your app?  It looks very clean and I would like to use it.  Thanks in advance

**Comment by mikeerickson** [comment]
@ceolter Is there any further work on a bootstrap theme?

**Comment by ceolter** [comment]
we are working on it now. should be ready in a week.

**Comment by mikeerickson** [comment]
@ceolter awesome, thanks for update!!

**Comment by Alex219267** [comment]
+1

**Comment by Joemurai** [comment]
also looking forward to bootstrap theme :)

+1

**Comment by pantonis** [comment]
+1 Its pity that such a great control is not using the most widely uses bootstrap

**Comment by cumanacr** [comment]
Bootstrap styling it's working with this dependencies:
```
  "dependencies": {
    "ag-grid": "^4.2.5",
    "ag-grid-react": "^4.2.0",
```

**Comment by ceolter** [comment]
any comments on the latest bootstrap theme from last fridays release? it can be seen on the main demo page.

**Comment by AmitMY** [comment]
Looks good.
However, when I think of bootstrap tables, I usually think on the striped (that you have), and row border, like [here](http://www.w3schools.com/bootstrap/bootstrap_tables.asp):].
(.table .table-striped)

Also, the group dropzone blends with the header. It should have a border at the bottom, or a lighter background color

**Comment by jdelafon** [comment]
Is [this](https://www.ag-grid.com/javascript-grid-themes/bootstrap-theme.php) what it refers to? I don't find it very pretty or close to a default Bootstrap table (lines are too narrow, text is not vertically centered, and what happens when you click on a row is pretty ugly).

**Comment by ceolter** [comment]
@jdelafon yes that's the one, and yes it's not very pretty.

**Comment by ceolter** [comment]
bootstrap theme provided, so closing.

**Comment by emonney** [comment]
bootstrap theme provided, so closing... lol. That theme is ugly. Wonderful grid though 👍

**Comment by jadhavajay** [comment]
Anyone has any idea about Integrating any Semantic UI theme with ag-grid-aurelia?

**Comment by mbrookson** [comment]
I have to say, the material theme looks great but the bootstrap theme doesn't look at all like bootstrap
