### ISSUE TITLE
Editing using a control other than textbox

### ISSUE THREAD

**Issue by abhijeetpathak** [ceolter/ag-grid#342]
Is it possible to edit contents of a cell using our choice of preferred control (like select list) instead of the default textbox?

**Comment by ceolter** [comment]
For now, you need to implement this yourself using cell renderer.

**Comment by abhijeetpathak** [comment]
Yep. I referred to the example.
The difficulty with that approach is that it doesn't work as good as normal 'textbox' editing.
For example, with textbox editing, we can have text rendered differently on the fly than what is stored in actual internal data structure.

**Comment by ceolter** [comment]
> The difficulty with that approach is that it doesn't work as good as normal 'textbox' editing.
> For example, with textbox editing, we can have text rendered differently on the fly than what is stored in actual internal data structure.

sorry, i don't understand this

**Comment by abhijeetpathak** [comment]
Sorry If my statements aren't clear.

If we use a cell renderer, the text displayed in cell can be modified on the fly. And at the time of editing that cell, the textbox shows the value present in the grid's internal data structure.

Now, if I use custom editor (like a select control) in cell renderer, I can't have diff text for normal cell display and diff text for editing.

**Comment by ceolter** [comment]
Update the data outside the grid, then get the grid to refresh the rows
that changed??

**Comment by abhijeetpathak** [comment]
I needed editing with select instead of texbox without using cell renderer.
If editing using 'select' list is supported natively, then I'll be free to use cellRenderer for formatting the data in other way.

I've kinda implemented it. Please see the commit d7325d77414050aa2781e60859328db4ba159ee2

**Comment by ceolter** [comment]
i've done a large amount of refactoring since you made the change, makes it difficult to compare :(

**Comment by abhijeetpathak** [comment]
I've merged with your latest code changes.

i've submitted compiled angular-grid.js and .min.js also. Please ignore them.

**Comment by ceolter** [comment]
editing was implemented in 2016.

**Comment by abhijeetpathak** [comment]
Thanks!
