### ISSUE TITLE
Add class to row to indicate focus when a row's cell is selected via keyboard navigation

### ISSUE THREAD

**Issue by jonsamwell** [ceolter/ag-grid#373]
It would be nice to have a class on the row of a selected cell to indicate the currently focused row on the grid when the user is navigating via the keyboard.

**Comment by ceolter** [comment]
sounds fair

**Comment by scotthovestadt** [comment]
+1

Using the below code to accomplish this, but would be nice to have an option built in.
````
// Apply "focus" class to row in addition to cell
self.cellFocused = function(params) {
  $('.ag-row-focus', self.api.grid.gridPanel.eBodyContainer).removeClass('ag-row-focus');
  $('.ag-row[row="' + params.node.id + '"]', self.api.grid.gridPanel.eBodyContainer).addClass('ag-row-focus');
};
````

**Comment by scotthovestadt** [comment]
@ceolter I'll submit a pull request for this after my other pull request is merged in.

**Comment by ceolter** [comment]
this is done.
