### ISSUE TITLE
We need multiple selection.

### ISSUE THREAD

**Issue by oknoorap** [ceolter/ag-grid#383]
When I'm using slickgrid and w2ui grid, it's supports multiple selection like excel, no need hold control and can selects multiple cells (drag and drop mouse events) but when I'm looking this feature in AG it doesn't supports, after reading on the forum it was by design, why?

I think multiple selection is standard feature, if developer is busy, at least give people chances to create their own plugin/extension/module/whatever.

Thanks.

**Comment by ceolter** [comment]
i plan on changing the selection, but it's not near the top of my list at the moment.

making it pluggable is a nice idea, however that would take time for me to get in also!

**Comment by oknoorap** [comment]
:-D :+1:  hanks it will looks great..

**Comment by rsmything** [comment]
.coffee
```
gridDiv = document.getElementById 'tracker-table'
data = JSON.parse gridDiv.getAttribute('data-tracker')

$(gridDiv).delegate '.ag-row', 'click', ->
  $(@).toggleClass 'ag-row-selected'
  select = $(@).hasClass 'ag-row-selected'
  gridOptions.api.rowModel.rowRenderer.renderedRows[@.getAttribute('row')].rowNode.setSelected select`


gridOptions =
  rowSelection: 'multiple'
  suppressRowClickSelection: true
  suppressCellSelection: true
  suppressMenuHide: true
```

**Comment by ceolter** [comment]
range select is now in.
