### ISSUE TITLE
gridApi.setAutoGroupColumnDef is not a function

### ISSUE THREAD

**Issue by Filprots** [ceolter/ag-grid#3887]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

THROWS ERROR TypeError: params.api.setAutoGroupColumnDef is not a function

**Expected behavior**

setAutoGroupColumnDef(colDef) | Call to set new auto group column definition. The grid will recreate any auto-group columns if present.

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

23.1.0

* **Browser:**

Chrome/83.0.4103.61

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

TypeScript 3.8

**Comment by jdwilkin** [comment]
I am seeing this exact problem... was it fixed? or?

**Comment by jdwilkin** [comment]
for anyone else finding this, upgrading from 23.1.0 to 24.0.0 fixed this problem... (though I couldn't find any reference to this in any of the release notes)
