### ISSUE TITLE
Issue on custom column filter with virtual paging enabled

### ISSUE THREAD

**Issue by andre-morassut** [ceolter/ag-grid#423]
Hi,

When defining a custom filter with virtual paging activated, angular-grid raises an error when you try to display the filter popup using the column menu.

The error : "TypeError: this.rowModel.getTopLevelNodes is not a function (line 3139)", raised when angular-grid try to execute this function on the rowModel. Its seems that, instead of being aware that it is a "VirtualPageRowController", it considers it as a "InMemoryRowController"

I combined the "Custom Filter example [link](http://www.angulargrid.com/angular-grid-filtering/example2.html)" code and the "A Wee Bit More Complex Example - Sorting & Filtering [link](http://www.angulargrid.com/angular-grid-virtual-paging/virtualPagingServerSide.html)" code in the following plunkr to demonstrate the issue : 

 [Plunkr - Server side custom angular grid filter](http://plnkr.co/edit/zsYXxQJFzs7mh3jv1K1D?p=preview)

When you click on the "Athlete" column menu to display the filter, you'll get the error in the console and the popup won't show. A second click, and the popup shows.

Anyway, thanks for this wonderful grid!

**Comment by ceolter** [comment]
thanks for raising. will fix.

**Comment by andre-morassut** [comment]
Awesome, thanks.

**Comment by ceolter** [comment]
this is now fixed. will be in the next release (later today??)

**Comment by andre-morassut** [comment]
Updated to 2.3.0 today, I confirm do not have the issue anymore. Thanks a lot!

**Comment by ceolter** [comment]
cool!!!
