### ISSUE TITLE
[FEAT] Expandable rows

### ISSUE THREAD

**Issue by YonatanKra** [ceolter/ag-grid#43]
One of my favorite features in ng-grid (and kendoUI grid) is the expandable grid.
Can this be achieved with the current API?

**Comment by ceolter** [comment]
Not right now am afraid . . . but why not use grouping feature to achieve
the same? Or just have a second grid that gets loaded based on first grid
selection?

I could put this n a later date, but need to get other features in first.

**Comment by yccteam** [comment]
A few things:
1) Thanks for the ultra fast reply
2) Kudos for a GREAT plugin/module
3) Grouping nesting is an amazing feature!
Now regarding my issue:
I need to grids to open much like a tree menu. Grouping behavior is good (especially the nested one), only I need custom columns for the group, and different columns for the individuals inside the group. Unlimited grouping is awesome!
For isntance - I have a list of football players with teams, age and scores as properties.
Now I want to group according to teams, and for each team have 4 columns:
1) List of players
2) AVG age
3) AVG score
4) A button that leads to the team's website
(it can get more complicated - like get data about each player from a different dataset).
For each player I'd need his details, in addition to a few more pieces of data coming from a different data set (for instance, AVG number of passes that comes from a passes data set).
Can this be done in the method you mentioned?

**Comment by ceolter** [comment]
If I were doing that, I would go master / detail tables. Ie one table for
teams, then a second for players. But I am thinking with my business
application hat on. Think your users are more typical human so maybe not
the best.

It is possible to work out aggregates in the group, there is an example in
the docs working out age span for the Olympic winners. With that, the col
would show avg age, for example, for groups, and age for players. But then
you would be left with empty and redundant cols where group doesn't have
corresponding aggregate.

The grid doesn't currently support lazy loading of groups - yet - not sure
if you implied that as a requirement.

You could use 'group uses entire row' to give customised header to the
groups.

Hope the above helps. Not sure I answered correctly, but hope you
understand your options better.

**Comment by davakos** [comment]
+1 for this feature!

I also read your response to a similar feature request here:
http://www.angulargrid.com/forum/showthread.php?tid=103&highlight=nested

I'm using another data grid solution that I'd like to move away from (requires heavy customization and outside dependencies) and have really been impressed with the design and feature set offered in Angular Grid; unfortunately, I just can't do without this particular feature.  The basic functionality is that if a user clicks an expand icon in a row, I'd like to be able to fire-off an AJAX request to get more data on that item and then present that data using a "drop-down" (animated show/hide) drawer with a full column span that I can provide a rowTemplate for. As you noted in your last response, I tried using the grouping functionality to create a single item grouping and then aggregate the item details to the top grouping "container" row, using a combination of suppressCount, groupAggFunction, groupUseEntireRow & groupSuppressAutoColumn.  I was then hoping I might be able to "hide" the actual row in the group so all you have visible is the grouping "container" row and provide a template for the footer to use as the "drawer", but neither of these appear to be possible.  An example of this attempt can be found here:

http://plnkr.co/edit/sBCiSLVykuD69LKXvfrt?p=preview

I also tried using a gridOptions.rowClicked callback and loading another data item to be placed after the clicked item, but realized this implementation might break down when combined with sorting and filtering and also didn't provide the desired ability to style the extra row with a new height and full column span.

Unfortunately, using a second data table or a popup dialog for this additional data are also not feasible in my application for various reasons (design requirements, screen real estate usage, etc.)

Thanks for your work on a great grid, hope to be able to use it soon!

**Comment by nelreina** [comment]
+1 ng-grid (and kendoUI grid) is the expandable grid.

**Comment by ammar91** [comment]
Is there any plan to be added this feature soon?

**Comment by ceolter** [comment]
yea, there is a plan. it's about two months away. not sure if you consider that 'soon'.

**Comment by Naveg** [comment]
Really looking forward to this one. Thanks for all the hard work on ag-grid @ceolter

**Comment by amphy777** [comment]
Would be great to have expandable rows where another grid could be added.  Just looked at trying ag-grid in my application but unfortunately couldn't use it without it :( Such a shame as it looks like such a great tool!

**Comment by alhweiti** [comment]
+1, we're also looking forward to this feature. Thank you @ceolter 

A. Alhweiti

**Comment by ceolter** [comment]
```yea, there is a plan. it's about two months away. not sure if you consider that 'soon'.```
it's still about two months away - pivoting has taken much longer than expected. :(

**Comment by a497988** [comment]
+1, Do you think this will be available by Q3?

**Comment by cc1000** [comment]
+1. If you could keep us up to date with any change in ETA that would be great :)

**Comment by cc1000** [comment]
@ceolter, will the implementation you're working on work with virtual scrolling, or will it be disabled (as with aggregation and grouping)?

**Comment by ceolter** [comment]
i plan starting to work on this in two weeks from now - it's second on my list.

it won't work with virtual scrolling, as it will be tied in with grouping. so when you expand a group, the child row will be another grid. so it will only become supported in virtual scrolling when that supports grouping.

**Comment by squarewave24** [comment]
yes this would be a killer add-on to an already great grid!

**Comment by ceolter** [comment]
i've started to implement this. 2 or 3 weeks dev work in it.

**Comment by Verron** [comment]
ceolter Good to hear. You're amazing!

**Comment by faris-git** [comment]
I'm looking forward for this feature. Expandable rows + Virtual paging. I'm doing a analysis to use grid which can handle millions of rows with expandable rows and columns feature. Now I'm just stucked with expandable rows feature using virtual paging.

Would be good if it's available soon.

**Comment by ceolter** [comment]
@faris-git 
the expandable rows feature i am working on will not support virtual paging, as the expandable bit is with regards the grouping, and you can't do grouping in virtual paging.

**Comment by faris-git** [comment]
@ceolter
Thank you for your answer. Is this feature available in enterprise or may be in future?

**Comment by ceolter** [comment]
what i am working on now, expandabale rows in normal row model (not virtual pagination) will be available in standard free version.

**Comment by julia-bougaev** [comment]
Good to know that you've considered working on this feature. Could you give us please an approximate timeline regarding when this feature would be available. We are considering to buy this product and the main requirement for our application is to have rows that expand to a panel with custom template and dynamic height.

**Comment by mpetkov** [comment]
Out of curiosity, will this feauture behave like the data tables child rows?
https://datatables.net/examples/api/row_details.html

**Comment by ceolter** [comment]
this is now released
https://www.ag-grid.com/javascript-grid-master-detail/index.php

**Comment by squarewave24** [comment]
thanks !! 

in the detail section, is it possible to bind to Angular2 component values? or is it same thing as before where angular binding is no longer available after initial render?

**Comment by squarewave24** [comment]
is it possible to create a github examples in Angular2 for these: https://www.ag-grid.com/javascript-grid-master-detail/index.php ?

there is one full width row example in your ng2 examples repo: https://github.com/ceolter/ag-grid-ng2-example but that has a different implementation so not sure how to add a more complex renderer

**Comment by ceolter** [comment]
@squarewave24 the fullWidth feature is the same across normal and Angular 2 versions of the grid. we only present items in the Angular 2 examples that are different in Angular 2, otherwise we would be giving each example in each of the frameworks that we support, and our team team is not big enough to be able to do that.

**Comment by chennoam7** [comment]
Hi Guys,

I'm really interested in your ag-Grid, however I would like to use it with Angular 2. There are no Angular 2 demos for ag-Grid. Most of examples are just regular java script. This is why we like Kendo UI, all their examples are Angular 2.
One of the feature that we need is expandable rows, we would like to create input text boxes and buttons within each row when expanding it.
Can you please tell me how to achieve that functionality using ag-Grid. We really like it.
We don't care buying it, if there is a good support that will give us help & answers.

Thanks,
Chen

**Comment by ceolter** [comment]
@chennoam7 loads of examples of angular 2 here:
https://www.ag-grid.com/best-angular-2-data-grid/
