### ISSUE TITLE
Double click on mobile

### ISSUE THREAD

**Issue by equilerex** [ceolter/ag-grid#436]
Forum - http://angulargrid.com/forum/showthread.php?tid=2813

Any chance of modifying cellDoubleClicked event to work on mobile devices? 

does not seem to be working out of the box: http://tinyurl.com/qfsmrcf
full plnkr: http://plnkr.co/edit/r0hj1QDmbLODzuNdgNXj?p=preview

i need to be able to highlight the row to enable certain actions upon it and on double click, it should open a modal for additional detail... works fine on desktop but no dice on ios and android

**Comment by ceolter** [comment]
what's the fix for mobile?

**Comment by ceolter** [comment]
no movement in over a year, closing.
