### ISSUE TITLE
Provide documentation for event structure passed to rowSelected and other callbacks.

### ISSUE THREAD

**Issue by thallgren** [ceolter/ag-grid#439]
The rowSelected function that can be assigned to the gridOptions takes an argument but there's no explanation provided with details about that argument. Judging from source code, it's an event structure with a `node` which in turn contains a `data` which is the actual object that represents the row.

Please add documentation for all callback arguments.

**Comment by ceolter** [comment]
in time. there is a lot of documentation missing. how the node structure works is one of them. but yes, that node contains a row.

basically the row data is what you provide, and the grid never updates anything on that object. to keep grid state, each row data item is wrapped by a node object, and the grid stores whatever state it needs on the node.

**Comment by thallgren** [comment]
:+1: no rush. I just thought I'd add an issue so it gets tracked.

**Comment by ceolter** [comment]
http://www.ag-grid.com/angular-grid-model/index.php
