### ISSUE TITLE
Callback x events - sizeColumnsToFit

### ISSUE THREAD

**Issue by naando-araujo** [ceolter/ag-grid#445]
Hi, taking a look in the src code, I believe that I didn't find a away to get a response when the sizeColumnsToFit() really did finish.

It's interesting provide some callbacks or events to bind and be executed after that kind of stuff; in my case I need to print a grid just after be resized, currently I'm using a $timeout workaround.

Thanks!

**Comment by ceolter** [comment]
when you call sizeColumnsToFit(), it's not asynchronous, so when the call returns, it's already complete!!

**Comment by naando-araujo** [comment]
Strange, when I resize the parent DOM e call sizeColumnsToFit(), it takes up to 10 seconds to fit in the new size, but the function already returned and is done (calling window print before fiting).
