### ISSUE TITLE
[Question] gulp-angular-filesort

### ISSUE THREAD

**Issue by shinrox** [ceolter/ag-grid#446]
Hi,

I'm not sure if this is the right repo to place this issue, but when I use the [gulp-angular-filesort](https://github.com/klei/gulp-angular-filesort) package the ag-grid is not being injected correctly after angular.js, it only works if I install like `bower install angular-grid=ag-grid`

I'm not sure, but I think it's because the folder sctructure, and due to the optional usage of angular in this project

I've opened an [issue](https://github.com/klei/gulp-angular-filesort/issues/35) in their repo as well

**Comment by S-YOU** [comment]
It's most likely because of ag-grid does not depends on angular - https://github.com/ceolter/ag-grid/pull/429

**Comment by shinrox** [comment]
Oh, yeah probably that. Thanks for pointing that out =)
