### ISSUE TITLE
Publish as ag-grid on npm?

### ISSUE THREAD

**Issue by aciccarello** [ceolter/ag-grid#447]
I'm not sure if you are aiming for ag-grid or angular-grid, but I noticed that ag-grid is open on [npm](https://www.npmjs.com/package/ag-grid). Would you want to publish it there for consistency with bower (See #49), the github repo, and [new website](http://www.ag-grid.com/)?

**Comment by ceolter** [comment]
the first ag-grid release will be happening today (i am in the middle of a name change). it will be pushed then. sorry for the confusion, once i get this release out of the way, all confusion should be gone as it's ag-grid everywhere and bye bye angular-grid.

btw, website is also changing, will be ag-grid in the next few hours!

**Comment by ceolter** [comment]
2.0.0 is now released and published to npm.

can you please verify?

**Comment by S-YOU** [comment]
may be http://www.angulargrid.com/forum/ link to http://www.ag-grid.com/forum/ in website too?

**Comment by ceolter** [comment]
yes i noticed something odd here, so i've the forum on www.angulargrid.com only now (or at least, all the links point to here, even if coming from ag-grid.com)

**Comment by S-YOU** [comment]
@ceolter, not sure i should raise new issue, but I can't get rowClass (with function params) work with 2.0 version with angular 1.x. its warn to use getRowClass, but getRowClass don't have params and tried getRowClassFunc, but can't get it work somehow. still reading into source.
