### ISSUE TITLE
Documentation Versions

### ISSUE THREAD

**Issue by sbowler** [ceolter/ag-grid#449]
Hello,

First, thank you for saving us from other poor performing grids and ones terrible to work with angular. Could you please provide a way on your website to reference older versions of documentation? A drop down menu might be nice to select which version. 

Unfortunately, there are probably many people that do not have the luxury of being able to update their libraries weekly or even monthly and so it can be difficult to reference the right version of documentation they are working with. Thanks.

**Comment by ceolter** [comment]
Thank you for your feedback. I agree, it would be ideal to have multiple versions. Unfortunately I am not using a content management system, and such would have to be done manually. I will have a think about it, maybe there is an easy way I am not thinking of.

**Comment by ceolter** [comment]
this is deffo in the category "if only i had more time" . . . . . if i could somehow get sponsored to do this work i could give up my job . . . . . . or pay someone to manage the website . . . . . :(

**Comment by S-YOU** [comment]
Here is my approach

https://raw.githack.com/S-YOU/ag-docs/master/index.html

**Comment by ceolter** [comment]
that simple! i thought that having the docs off the web root might cause some issues. i'll see about posting these onto the website.

**Comment by S-YOU** [comment]
there is actually some issues for some images (mostly loaded from javascript) not showing up, I can't find the way without touching sources yet.

**Comment by ceolter** [comment]
i am not to worried about the images.

**Comment by S-YOU** [comment]
:smile:

**Comment by ceolter** [comment]
ok, i've started doing this. from now on, i'll stick the documentation here:
http://www.ag-grid.com/archive/
so far, i only have todays release. i can't easily put the other releases up there as i had to make the urls configurable.
@sbowler if you can use s-you's link to get what you need?
going forward, my new approach will see to it.

**Comment by vz28bh** [comment]
Archive link returns 404

**Comment by lucky0027** [comment]
After selecting the version at:
https://www.ag-grid.com/archive/
I see the JS documentation. But I can't navigate to the Angular ones, it returns an error indicating that the page doesn't exist. 

**How can you see the documentation specific to a version of angular?**

**Comment by StephenCooper** [comment]
Which version are you trying to view. 

I see this working for 26 for example. https://www.ag-grid.com/archive/26.0.0/angular-data-grid/getting-started/

**Comment by lucky0027** [comment]
I´m trying with the **version 24.1.0.**

I have tried to test this URL
https://www.ag-grid.com/archive/24.1.0/angular-data-grid/getting-started/
but the page doesn´t exist

**Comment by seanlandsman** [comment]
Looks like there was an issue in that version that didn't play nice in archives - you can navigate there directly via: https://www.ag-grid.com/archive/24.1.0/javascript-grid/

**Comment by lucky0027** [comment]
Thanks... 
but that documentation is only for javascript, right? I would be interested in the **angular** documentation

**Comment by seanlandsman** [comment]
Yes - it's not ideal but you can substitute the framework you're interested in to find the documentation: https://www.ag-grid.com/archive/24.1.0/angular-grid/

**Comment by lucky0027** [comment]
> Yes - it's not ideal but you can substitute the framework you're interested in to find the documentation: https://www.ag-grid.com/archive/24.1.0/angular-grid/

Yes, I Just found out...
thank you very much!

**Comment by lucky0027** [comment]
unfortunately not all pages are uploaded:

it´s works for **JS**
https://www.ag-grid.com/archive/24.1.0/javascript-grid-master-detail-detail-grids/
_but_
https://www.ag-grid.com/archive/24.1.0/angular-grid-master-detail-detail-grids/
It doesn´t work for **Angular**..

Thanks anyway
