### ISSUE TITLE
Please make "Total" in foot aggregation configurable

### ISSUE THREAD

**Issue by ralphite** [ceolter/ag-grid#451]
Seems like it's hardcoded [here](https://github.com/ceolter/ag-grid/blob/4776c4d4ea900ad0b5fe8a318eae3bff12e29d38/src/ts/cellRenderers/groupCellRendererFactory.ts#L129).

**Comment by ralphite** [comment]
https://github.com/ceolter/ag-grid/blob/4776c4d4ea900ad0b5fe8a318eae3bff12e29d38/src/ts/cellRenderers/groupCellRendererFactory.ts#L129

**Comment by ceolter** [comment]
done!
