### ISSUE TITLE
Uncaught NotSupportedError: Failed to execute 'registerElement' on 'Document': Registration failed for type 'ag-grid'. A type with that name is already registered.

### ISSUE THREAD

**Issue by manuknkra** [ceolter/ag-grid#461]
I am including the ag-grid.js file using gulp. The package is installed via bower. I am getting above error. Is there anything I am doing wrong?

Following is the simple gulp task I have added.
gulp.task('vendorScripts', function() {
    return gulp.src([
            'bower_components/**/angular.js',
            'bower_components/**/angular-resource.js',
            'bower_components/**/dist/jquery.js',
            'bower_components/**/assets/javascripts/bootstrap.js',
            'bower_components/**/release/angular-ui-router.min.js',
            'bower_components/**/ui-bootstrap-tpls.js',
            'bower_components/**/dist/ag-grid.min.js'
        ])
        .pipe(plumber())
        .pipe(concat('vendor.js'))
        .pipe(gulp.dest('dist/js'));
})

**Comment by scotthovestadt** [comment]
I think you're including ag-grid twice. You're using a wildcard in bower_components, if ag-grid.min.js exists in two places it'll be included twice. The error also heavily implies it's being included twice.

**Comment by manuknkra** [comment]
I changed the bower component path to 'bower_components/**/ag-grid/dist/ag-grid.js'
