### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by piernik** [ceolter/ag-grid#462]
I see major upgrade - where can I find changelog?

**Comment by ceolter** [comment]
there is no change log. when i do a release, i mention what is new on the main documentation page:
http://www.ag-grid.com/documentation.php

when a release is done, i notify via the email dist list  and twitter.

going forward, i'll start creating change logs.

the project is morphing from a pet project to a proper industry strength project with lots of users. you are the first person to ask for a change log would you believe! but your right, a change log will be held going forward.

**Comment by piernik** [comment]
Thanks - Your product is great!
