### ISSUE TITLE
26.0.0: Unable to use customize themes

### ISSUE THREAD

**Issue by darrenfurr** [ceolter/ag-grid#4642]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.
- I am a customer. Submitting here and Zendesk

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
- `git clone https://github.com/ag-grid/ag-grid-customise-theme.git`
- `cd /src/react`
- `npm i`
-  `npm start`

**Current behavior**
```
./src/App.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./src/App.scss)
SassError: Invalid CSS after "    @return math": expected expression (e.g. 1px, bold), was ".div($lhs, $rhs);"
        on line 315 of node_modules/ag-grid-community/src/styles/mixins/_ag-theme-params.scss
        from line 1 of node_modules/ag-grid-community/src/styles/ag-theme-base/sass/_ag-theme-base-default-params.scss
        from line 1 of node_modules/ag-grid-community/src/styles/ag-theme-base/sass/_ag-theme-base-mixin.scss
        from line 1 of node_modules/ag-grid-community/src/styles/ag-theme-base/sass/_ag-theme-base.scss
        from line 1 of node_modules/ag-grid-community/src/styles/ag-theme-alpine/sass/_ag-theme-alpine-mixin.scss
        from line 3 of /Users/darrenfurr/github/ag-grid-customise-theme/src/react/src/App.scss
>>     @return math.div($lhs, $rhs);
```

**Expected behavior**

**Please tell us about your environment:**
```
Google Chrome | 92.0.4515.159 (Official Build) (x86_64)
-- | --
OS | macOS Version 11.5.2 (Build 20G95)
```

* **AG Grid version:** 26.0.0

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]: all

**Comment by jogilvyt** [comment]
I also had this issue - changing from `node-sass` to Dart Sass solved it for me. Weback has an example [here](https://webpack.js.org/loaders/sass-loader/#implementation) on how to use Dart Sass.

**Comment by nikhilknoldus** [comment]
I am still facing this issue, I am using scss, but after upgrading, it is not being compatible with scss. I have to change the imports for `ag-grid` to `ag-grid.css`.
Along with that, while using `node-sass-chokidar`, I was using, `--include-path` and `--recursive` flags in my package.json, what are the alternatives for `sass`.

**Comment by NehalDamania** [comment]
Any update on this how to resolve?

**Comment by darrenfurr** [comment]
@NehalDamania  - I replaced my node-sass npm package with [dart-sass](https://github.com/sass/dart-sass) & that resolved this.

**Comment by NehalDamania** [comment]
Thanks @darrenfurr replacing node-sass worked for me too
