### ISSUE TITLE
`startRow` and `endRow` parameters being `undefined` after updating from v24.1.0 to v25.3.0 even 26.0.0

### ISSUE THREAD

**Issue by carrey-k** [ceolter/ag-grid#4644]
I can confirm that the issue is not fixed on v25.1.0. I mentioned this in a [ticket on the ZenDesk](https://ag-grid.zendesk.com/hc/en-us/requests/17585) as my company is a paying customer, together with another regression with the `startRow` and `endRow` parameters being `undefined` after updating from v24.1.0 to v25.1.0

_Originally posted by @lwouis in https://github.com/ag-grid/ag-grid/issues/4295#issuecomment-826480587_

**Comment by ms14981** [comment]
For future readers, you need to add `serverSideStoreType={ServerSideStoreType.Partial}` to the `AgGrid` component: https://github.com/ag-grid/ag-grid/issues/4295#issuecomment-827359534

**Comment by KartikB34** [comment]
@ms14981 Thank you so much
