### ISSUE TITLE
Toggle header after initialization

### ISSUE THREAD

**Issue by benoror** [ceolter/ag-grid#467]
Hi @ceolter!

I just met this project thanks to angular air's podcast ([Episode 32](https://www.youtube.com/watch?v=jQ_nyTiKbZg)). I'm looking for an alternative to ui-grid, and this looks rock-solid :smile: congrats! (I introduced myself [today in the gitter chat](https://gitter.im/ceolter/ag-grid?at=560b0513dfb315130285677b), but unfortunately I noticed you can't access it).

Anyway, back to business, I would like to **toggle (hide/show) the header** after initialization, I couldn't find any method besides `gridOptions.headerHeight`, which I can effectively use to hide it if I **set it to `0`** during initialization.

Nevertheles I would like to hide it **after getting some configuration from the server (async)**, I tried the following callback function **with different ways to refresh the header**, but none worked:

```
  function onRefreshOptions(options) {
    vm.gridOptions.headerHeight = options.headerHeight;
    // ...
    // Refresh View
    vm.gridOptions.api.sizeColumnsToFit(); // \
    vm.gridOptions.api.refreshHeader();    //   - None of these will refresh header Height
    vm.gridOptions.api.refreshView();      // /
  }
```

Is it something not yet covered and should it be considered a new feature? 

Cheers!

**Comment by ceolter** [comment]
hi @benoror ,

yea i don't use the chat channel any more. it was just far to distracting for me, every hour getting a help request pushed to my phone!! with the forum and github, i can spend sold time on helping when i have the time, it fits much easier into my daily planning.

to set the header height, use the api:
api.setHeaderHeight(newHeight)

mentioned here btw:
http://localhost:8082/angular-grid-api/index.php

and yes, setting the height to 0 is what i recommend for hiding the header.

have fun!!

**Comment by S-YOU** [comment]
s/localhost:8082/ag-grid.com/

**Comment by ceolter** [comment]
@S-YOU  ta!

**Comment by benoror** [comment]
Thanks!

On Thu, Oct 1, 2015, 05:07 Niall Crosby <notifications@github.com> wrote:

> @S-YOU <https://github.com/S-YOU> ta!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/ag-grid/issues/467#issuecomment-144685766>.
>
-- 

Sent from my phone (sorry for possible typos)
Benjamin Orozco - benoror.com
