### ISSUE TITLE
Add the ability to put extra custom items in the column menu dropdown

### ISSUE THREAD

**Issue by mikeokner** [ceolter/ag-grid#47]
I'm interested in seeing a feature that accomplishes something similar to this ui-grid feature: http://ui-grid.info/docs/#/tutorial/303_customizing_column_menu

**Comment by ceolter** [comment]
I agree. This will come at some point. I will take a look at ui-grid, but my implementation will be different (better??)

**Comment by mikeokner** [comment]
FWIW I was able to use existing APIs meant for custom column filters to stick the menu elements I need in the dropdowns in `getGui`. It might be nice to have a wrapper with options that go in colDefs for clickable menu items, but my current implementation using the existing API works just fine and isn't too messy.

**Comment by ceolter** [comment]
Yes I did think of that solution, but didn't share it, as it's not very
clean, and you can't use the built in filters then. My goal, as you
suggest, is have another method alongside getGui that returns back either
menu options, or HTML to display (similar to how the cell renderers return
values).

On 15 April 2015 at 21:59, Mike <notifications@github.com> wrote:

> FWIW I was able to use existing APIs meant for custom column filters to
> stick the menu elements I need in the dropdowns in getGui. It might be
> nice to have a wrapper with options that go in colDefs for clickable menu
> items, but my current implementation using the existing API works just fine
> and isn't too messy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/angular-grid/issues/47#issuecomment-93567917>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by randdusing** [comment]
@ceolter Can you share your solution?

**Comment by ceolter** [comment]
customising the column menu is not possible. the above thread is over 1 year old!

it's an enterprise feature only though:
http://localhost/javascript-grid-column-menu/index.php

**Comment by randdusing** [comment]
Not sure how I missed the the documentation. Thanks!
