### ISSUE TITLE
Requesting angular2/angular2.js but I'm running  Angular 1.x

### ISSUE THREAD

**Issue by Bodom78** [ceolter/ag-grid#470]
My project is using JSMP and ES6 style modules on Angular 1.x

I've added the ag-grid and can create the examples from the documentation without issues however when my app loads it's making a request to "angular2/angular2.js" which is obviously not found since I'm not using it.

Is there a way to force this module to not guess what library I'm using?

**Comment by ceolter** [comment]
interesting. that is right, i'm trying to load Angular2 if i sense JSPM is available. it will result in a failed call, but the application should work anyway. i would rather not have different versions of the app if i can avoid it, so let me think if there is another way first.

**Comment by Bodom78** [comment]
I understand not wanting different versions of the app.

I've only glanced at the unminified source but perhaps only execute the Angular2 setup method if Angular1 is not found on the window object?

**Comment by ceolter** [comment]
yes that will solve it for you, but not for the person who is not using angular at all !!

**Comment by ceolter** [comment]
or using just web components

**Comment by Bodom78** [comment]
Ah yes, I see. Cannot assume they are using angular. It's a tricky one.

One idea is if you wish to use Angular2 you would need to include a "ag-angular2.js" file that would have the init code in it.

**Comment by ceolter** [comment]
> One idea is if you wish to use Angular2 you would need to include a "ag-angular2.js" file that would have the init code in it.

yea, that's one way of doing it. but then why not have one separate file for ng2, one for ng1, one for web-components etc (ie duplicate the whole grid in each file). that way at least your only bringing in one file :(

**Comment by Bodom78** [comment]
Would the build process be able to create separate releases, ie ag-standalone.js, ag-angular.js, ag-angular2.js and ag-webcomponents.js ?

**Comment by ceolter** [comment]
yes it would. but that's what i'd like to avoid at any cost if i can.

there are currently 4 flavours, each with minified and non-minified, that would create 8 releases

**Comment by ceolter** [comment]
actually it's worse than that, it would have to be each framework and each module loading combination,

eg:
ng1 & jspm
ng1 & requirejs
ng1 & normal
ng2 & jspm
etc etc etc

**Comment by Bodom78** [comment]
Yea, looking at it now that option gets out of control quite quickly.

The solution will most likely be more complex conditional checking.

Another consideration would be adding the [System.has] (https://github.com/systemjs/systemjs/blob/master/docs/system-api.md#systemhasmodulename---boolean) api call to see if "angular" package is present. If so you would not need to require Angular2

**Comment by ceolter** [comment]
> Another consideration would be adding the System.has api call to see if "angular" package is present. If so you would not need to require Angular2

I'll look into that. I'm new with JSPM.

I could also have routines that you call, eg instead of ag-Grid trying to fine Angular (1 or 2), you call a method on the grid telling it to initialise and you pass it a reference to Angular. This would work, but another step required by the developer.

**Comment by Bodom78** [comment]
New to JSPM myself, might be worth adding ag-grid to the [registry](https://github.com/jspm/registry) as well.

**Comment by ceolter** [comment]
blind leading the blind!! i have no idea!! i will look into it.

i think i need to read up on jspm in general. all i have done is copy the example from angular 2 and nothing else.

**Comment by Bretto** [comment]
Good to see I am not the only one experiencing this issue. 
@ceolter Great work by the way !

**Comment by ceolter** [comment]
cheers @Bretto 

i've not come up with another solution yet. i'm still pondering over it.

i think maybe i don't initialise my Angular 2 component by default, rather put this into another script which you don't include if not using jspm and ng2.

**Comment by Bretto** [comment]
I was thinking something along what you said:
> you call a method on the grid telling it to initialise

Was not a too heavy price tag, considering the number of permutations...

**Comment by Bodom78** [comment]
> Was not a too heavy price tag, considering the number of permutations...

Agreed, most developers using this heavily will be across the docs so as long as it's documented it shouldn't pose a problem.

**Comment by ceolter** [comment]
i've just done a release. this is now fixed.

to use Angular2 with JSPM, you have to call this:

ag.grid.initialiseAgGridWithAngular2(ng2)

basically you pass in a reference to the ng2 library to ag-Grid, and it uses that, rather than trying to load the library itself.

i think that's enough for now . . . . . think i'll let the dust settle with the new technologies a bit, or at least wait until i'm more familiar with them.
