### ISSUE TITLE
Accessibility Requirement - ag grid header default context menu button need role, name and state setting (Related to #4197)

### ISSUE THREAD

**Issue by DandelionWenjing** [ceolter/ag-grid#4710]
**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
https://www.ag-grid.com/angular-data-grid/context-menu/#example-context-menu
1. Open this example in Plunker.
2. Open Dev Tools by F12 and hover on the header context menu.
3. No name, role and state display.
4. ag-grid-angular version 26.1.0 for plunker.

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
1. Display ag grid by using default header.
2. Use Dev Tools to select an element in the page to inspect it and hover header context menu button.
3. ag grid header default context menu button have no name, role and state ('aria-expanded' setting).
image
![image](https://user-images.githubusercontent.com/33156672/136739874-36612340-93d8-4b05-942a-8b4b2aa1f045.png)

**Expected behavior**
ag grid header default context menu button have name, role and aria-expanded state. Or have a way to set them.

**Please tell us about your environment:**
Windows 10, VS code, npm

* **AG Grid version:** X.X.X
ag-grid-angular 23.2.0.

* **Browser:**
Chrome/Edge
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

This bug is related to the bug #4197, comments suggest to upgrade to 24.1.0, have tried to upgrade to 24.1.0 and also not work

**Comment by DandelionWenjing** [comment]
@kiril-matev Thanks and for the answer details.

**Comment by yazha-MS** [comment]
@makinggoodsoftware  It looks that this issue still not released, do we have a timeline for this?

**Comment by kiril-matev** [comment]
@yazha-MS Please see my response above.
