### ISSUE TITLE
单元格编辑状态下，点击cellEditor时，不想触发 rowClicked 事件，应该怎么判断处理？

### ISSUE THREAD

**Issue by chenkai88** [ceolter/ag-grid#4717]

**Comment by chenkai88** [comment]
![image](https://user-images.githubusercontent.com/24888514/137085973-6f35938f-717a-4d00-acf6-eddf78f863e3.png)

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
