### ISSUE TITLE
Does a commercial company need to buy AG Grid Enterprise?

### ISSUE THREAD

**Issue by pasapsi** [ceolter/ag-grid#4721]
I'm submitting a ...

[ ] bug report => see 'Providing a Reproducible Scenario'
[ ] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'

Requesting Community Support

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

Providing a Reproducible Scenario
No need

Current behavior
No need

Expected behavior
Good afternoon, I did not quite understand the license indicated on the site. Can you please tell me, is it possible to use the free version for a commercial company? Or do you need to buy the corporate version for these purposes?
Thank you!

Please tell us about your environment:
No need

**Comment by makinggoodsoftware** [comment]
Hi,

Anyone can use the free version, the only limitation is the set of features that you need, if you need an enterprise feature, then you need to buy a license.

In short, you can use the free version if you want.

Does this make sense?
