### ISSUE TITLE
React grid editing changes state incorrectly when it shouldn't, or evaluates onCellValueChanged function incorrectly with stale information

### ISSUE THREAD

**Issue by AmrineA** [ceolter/ag-grid#4723]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
https://stackblitz.com/edit/ag-grid-react-hello-world-scmn1f?file=index.js

**Current behavior**
**With reactUi** It appears that it's not properly evaluating this function when it should and the onCellValueChanged function is essentially locked down based on what the state is when the grid is initially rendered.

**Without reactUi** It appears that the state object is being updated directly without me having called the state setter function.

**Expected behavior**
I would expect the `data` value to reflect the current state of what is in `data` and not the initialized value or the changed value. The grid should never update the data value directly, but only when I specifically tell state to be updated through the state setter functions.

**Please tell us about your environment:**
I'm running Windows, but you can see it happen in StackBlitz.

* **AG Grid version:** 26.1.0 and 26.0.0

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36

* **Language:** React/JavaScript

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks
