### ISSUE TITLE
`onSortChanged` should have an indicator on what column has changed

### ISSUE THREAD

**Issue by guido-visser** [ceolter/ag-grid#4732]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
When using the `onSortChanged`, the parameter given to the function looks like: 
```
{type: 'sortChanged', api: GridApi, columnApi: ColumnApi}
```
This way, you have no idea what column has been sorted. Here's a Plunkr with a `console.log` on a `onSortChanged`: https://plnkr.co/edit/3lD8lA8RLr0LrTLB

**Expected behavior**
It would be nicer to see a similar approach like the `onColumnMoved` and `onColumnResized` where an event is passed with a `column` property, so that you know which column has been sorted. It might be that passing a column is not desirable, since it's not a column specific event, then pass a columnId or at least something to know what the sort has changed, so it can be used to grab the new value and pass it along to the server without having to pass the entire column state.

**Please tell us about your environment:**
Windows 10 64-Bit

* **AG Grid version:** 26.1.0
Used a Plunkr from the sorting demo, I'm assuming that is using the latest version.

* **Browser:**
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36'

* **Language:** all

**Comment by guido-visser** [comment]
I was looking at the pipeline and saw the item, thanks! However, I was filtering on `sort` and saw this one come by: `AG-1817`. I can't see the content of that issue, but does this reference the same thing? Also, if it's the same thing, I can basically assume that this will never be implemented, since it doesn't have a priority at all?

**Comment by kiril-matev** [comment]
Hi @guido-visser,

Thanks for pointing out AG-1817. 

I took a closer look at it and found it's opened for the same requirement as AG-5928. This is why I've consolidated this requirement under AG-5928 and have deleted AG-1817.

**Please look up AG-5928 going forward in our pipeline to get an update on our progress on implementing this.**

Thank you for your time to bring this up!

**Comment by fhqvst** [comment]
@kiril-matev Hi! While you're at it - is there any chance you can add the source of the event too, just like there's a source for `columnVisible`, `columnMoved`, etc?

The use case here is being able to distinguish between a user clicking a header vs. programmatically applying column state.

**Comment by kiril-matev** [comment]
Hi @fhqvst,

Thanks for reaching out.

The requirement to add a source property to the sortChanged event is tracked by this feature request:
**AG-2013 [Events] Add source to all events in ag-grid (sortChanged, filterChanged, rowGroupOpened, cellValueChanged, etc)**

You can get an update on the status of this item in the pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

Thanks for using AG Grid!

**Comment by fhqvst** [comment]
Perfect, thanks!

**Comment by Valar103769** [comment]
talkless
