### ISSUE TITLE
Toggling visibility of header row

### ISSUE THREAD

**Issue by MikaAK** [ceolter/ag-grid#474]
When item's get selected I want to be able to turn off the header so something can replace it. How can I turn off the header row?

**Comment by ceolter** [comment]
Set the header height to zero. There is an api method for setting header height.

**Comment by sulemanuzair** [comment]
headerHeight is the key name for this option, in grid options

**Comment by lloy0076** [comment]
There is a semantic difference between a grid with `0 header height` and a grid with `no headers`, though...
