### ISSUE TITLE
Sorting is case sensitive?

### ISSUE THREAD

**Issue by piernik** [ceolter/ag-grid#475]
I see that default sorting is case sensitive - I have "Z" before "a" - how to change it? I want it to be case insensitive

**Comment by ceolter** [comment]
You have to provide your own comparator to change it. See the docs for colDef options.

**Comment by piernik** [comment]
Can You provide comparator example?

**Comment by ceolter** [comment]
http://www.ag-grid.com/forum/showthread.php?tid=2552&highlight=comparator

colDef.comparator = function(valueA, valueB, nodeA, nodeB, isInverted) {
  // do the compare here, then return either negative, positive, or zero (for equals)
}

**Comment by amreshpandey** [comment]
How to use comparator in angularjs where function is written with $scope.
Pls help me, my code is below

var courseColumnDefs = [{
                        headerName: "ID",
                        valueGetter: 'data.CourseId',
                        width: 5,
                        sort: 'desc',
                        sortingOrder: ['asc', 'desc'],
                        hide: true
                    },
                    {
                        headerName: "Course Name",
                        valueGetter: 'data.CourseName',
                        width: 200
                    },
                    {
                        headerName: "Linked Course",
                        valueGetter: 'data.LinkedCourseName',
                        width: 200
                    },
                    {
                        headerName: "Class Size",
                        valueGetter: 'data.ClassSize',
                        width: 100
                    },
                    {
                        headerName: "Duration (Days)",
                        valueGetter: 'data.CourseDuration',
                        width: 150
                    },
                    {
                        headerName: "Actions",
                        field: "",
                        width: 200,
                        suppressMenu: 'true',
                        suppressSorting: true,
                        suppressSizeToFit: 'true',
                        cellRenderer: function(params) {
                            return '<a ng-show="isSchedule == 0" href="" title="View" ng-click="viewCourseDetails(\'' + params.data.CourseId + '\')"> <u>View</u> &nbsp; &nbsp;</a>' +
                                '<a ng-show="isSchedule == 1 || isSchedule == 0" href="" title="Schedule" ng-click="courseSchedule(\'' + params.data.CourseId + '\')"> <u>Schedule</u> &nbsp; &nbsp;</a>' +
                                '<a ng-show="isSchedule == 2" href="" title="Select" ng-click="showScheduleInCalendar(\'' + params.data.CourseId + '\')"> <u>Select</u></a>' +
                                '<a ng-show="isSchedule == 3 || isSchedule == 0" href="" title="Quiz" ng-click="courseQuiz(\'' + params.data.CourseId + '\')"> <u>Quiz</u></a>';
                        }
                    }
                ];

                // TODO:: Set grid options, e.g. header height, row height, and default message if no record found.
                $scope.courseGridOptions = {
                    columnDefs: courseColumnDefs,
                    rowData: null,
                    headerHeight: 65,
                    rowHeight: 55,
                    angularCompileRows: true, // This is needed to use angular syntax on grid, e.g. ng-click to view course.
                    //overlayNoRowsTemplate: "No data found."
                    enableSorting: true
                };

**Comment by vikkivikrant** [comment]
Here is the code that we used with angular 4 implimentation : 

    private stringComparator(valueA: any, valueB: any, nodeA: any, nodeB: any, isInverted: any) {
        if ((valueA === null && valueB === null) || (valueA === undefined && valueB === undefined)) {
            return 0;
        }

        if (valueA === null || valueA === undefined) {
            return -1;
        }
        if (valueB === null || valueB === undefined) {
            return 1;
        }

        var upperValueA = valueA.toUpperCase();
        var upperValueB = valueB.toUpperCase();
        return upperValueA === upperValueB ? 0 : (upperValueA > upperValueB) ? 1 : -1;
    }
	
	
	
private numberComparator(valueA, valueB, nodeA, nodeB, isInverted) {
        var desc = isInverted;
         if ((valueA === null && valueB === null) || (valueA === undefined && valueB === undefined)) {
            return 0;
        }

        if (valueA === null) {
            return -1;
        }
        if (valueB === null) {
            return 1;
        }

        return valueA - valueB;
    }

**Comment by SWGeekPD** [comment]
@vikkivikrant  Can you please let me know, how you called above functions.

**Comment by haseeb1009** [comment]
Grid now has a property `accentedSort` to make your sort locale specific you can configure this by setting the property `gridOptions.accentedSort = true`
