### ISSUE TITLE
[edit] newValueHandler tabbing without changing data fires onCellValueChanged (newValue = oldValue)

### ISSUE THREAD

**Issue by RamiMustaklem** [ceolter/ag-grid#479]
If you press "Tab" key after starting to edit a cell with "newValueHandler" it fires the "onCellValueChanged" although it has not been changed and printing the params of the "onCellValueChanged" it shows the "newValue" same as the "oldValue", I think the "onCellValueChanged" should not be fired and if it has to be fired there shouldn't be a "newValue" when you press Tab without changing.

There is also a problem when the value of the field in empty (null) and you press the Tab, it makes a real Tabbed space and oldValue = null and newValue = ""

Is it also possible to have "Keyboard Navigation" properties added for custom editing like a cellRenderer for editing just like the example in the documentation? and if you press Tab it goes to the next cell that is per se cell Rendered or editable?

**Comment by ceolter** [comment]
> Is it also possible to have "Keyboard Navigation" properties added for custom editing like a cellRenderer for editing just like the example in the documentation? and if you press Tab it goes to the next cell that is per se cell Rendered or editable?

that's something i want to put it, but to do it right, i want to rework how the cellRenderers work, rather than just a function that returns something, they will need to expose an API somehow, similar to how the filters work (they return back a class with multiple methods, not just a function).

regards your first issue, thanks for sharing. when i get time i'll look into it.

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-73

**Comment by ceolter** [comment]
this is now done, will be in next release.

when you finish editing (including tabbing), the grid will check the values when the value is string, number or boolean, and if value is the same, then no refresh of cell or events are fired.

if using a newValueHandler, then you now can return true / false. return true if update was success. return false if not (ie the values are the same). if false, then no refresh or events are fired.

**Comment by makinggoodsoftware** [comment]
Hi,

Just to let you know that as of 11.0.0 this has been implemented, see the changelog for more details..

https://www.ag-grid.com/change-log/changeLogIndex.php#gsc.tab=0
