### ISSUE TITLE
Set rowsAlreadyGrouped after initialization

### ISSUE THREAD

**Issue by benoror** [ceolter/ag-grid#483]
How can I set `rowsAlreadyGrouped ` to `true` asynchronously after initialization (eg. after an ajax call)?

I couldn't find it in the [Grid API](http://www.ag-grid.com/angular-grid-api/index.php) :cry: 

P.S. Would you be interested in migrating the documentation to a more intuitive service like [ReadMe.io](http://readme.io/)? (The same way @kentcdodds did with [docs.angular-formly.com](http://docs.angular-formly.com/) :smile: )

 I could set it up & help a bit :wink:

**Comment by ceolter** [comment]
> How can I set rowsAlreadyGrouped to true asynchronously after initialization (eg. after an ajax call)?

just change it in your grid options. then call 'setRowData(rows)' with the new rows, the property will  be used when setting up the new rows. 

> P.S. Would you be interested in migrating the documentation to a more intuitive service like ReadMe.io? (The same way @kentcdodds did with docs.angular-formly.com  )

two reasons for me keeping the docs the way they are:
1) i use all the examples as regression tests for the grid. while developing, i use the docs for implementing and testing new features. i also do full regression testing by going through all my examples before releasing.
2) for SEO, i've tight control over the docs!

if i move to another system, then i presume i loose my first point.

**Comment by benoror** [comment]
Well, maybe this is a good opportunity to separate examples from documentation, while keeping them under your control (again, my suggestion is based in direct parallelism with @kentcdodds' [angular-formly examples](http://angular-formly.com/#/example/intro/introduction))

Also, having your examples (self-hosted, jsbins or whatever) pointing to a branch exclusively for distribution purposes [is also a good practice](https://medium.com/@kentcdodds/why-i-don-t-commit-generated-files-to-master-a4d76382564).

You might find Kent's advices quite helpful, as he's gone through all that before, as a OSS library maintainer:

- [How to Write a JavaScript Library](https://medium.com/@kentcdodds/how-to-write-a-javascript-library-3bac85f88153)
  - [Egghead series](https://egghead.io/series/how-to-write-an-open-source-javascript-library)
- [Why I don’t commit generated files to master (for libraries…)](https://medium.com/@kentcdodds/why-i-don-t-commit-generated-files-to-master-a4d76382564)

Hope it helps, cheers! :smile:

**Comment by kentcdodds** [comment]
Thanks for the high praise @benoror! My methods might not work for everyone, but it's been awesome for me. @ceolter, let me know if you're interested and I'd be happy to do a hangout to answer your questions :-)

**Comment by benoror** [comment]
Although projects are different in many ways, I think @ceolter can effectively skip some headaches you've been through as a maintainer, and automate some tasks in the way :smiley_cat:

**Comment by ceolter** [comment]
thanks for the feedback @kentcdodds  & @benoror. i've a lot on at the moment, but will rethink all of this in the new year. i'm giving up my job, and taking a holiday for november and december, so will be back with lots of energy in the new year to take the grid to another level.

**Comment by kentcdodds** [comment]
Good luck on your new adventures!!

**Comment by ceolter** [comment]
thanks @kentcdodds

ps pity we didn't get to meet on angular air, but your coming to london in two weeks so will deffo get you then :)

**Comment by benoror** [comment]
Good luck @ceolter!
