### ISSUE TITLE
Remove module from d.ts

### ISSUE THREAD

**Issue by aciccarello** [ceolter/ag-grid#486]
Is there a reason why the `module` variables need to be declared in `ag-grid.d.ts`? In my project we are using the node definitions defined by the [DefinitelyTyped](http://definitelytyped.org/) project and ag-grid is conflicting because it tries to redefine that variable.

I saw that [main.ts](https://github.com/ceolter/ag-grid/blob/master/src/ts/main.ts#L5) declares `module`.  If that declaration is moved inside of the closure, is the variable added to the `d.ts` file?

**Comment by ceolter** [comment]
if i move the declarations to inside the closure, it doesn't compile with message "error TS1184: Modifiers cannot appear here."

do you know how i can get TypeScript to reference an unknown variable like it's doing? basically it's looking to see if module and exports are provided by the wrapping commonjs (browsersify??) code. because i don't use these myself, i can't test this.

**Comment by S-YOU** [comment]
actually, I had same issue since a while, I normally comment it out from .d.ts file manually.
but actually you can just declare as normal variable not with `declare` inside clojure, and PR submitted.
https://github.com/ceolter/ag-grid/pull/488

of course there will `var module;` in source code but it does not harm anything in javascript.

**Comment by aciccarello** [comment]
@ceolter The project I'm working on is using browserify. Can you include a reference to [node.d.ts](https://github.com/aciccarello/DefinitelyTyped/blob/master/node/node.d.ts) in your source code? That'll define export and module for you. 

Alternatively, I know you can declare a variable in a namespace. Could you refactor that file to move that `declare var module: any;` inside of a namespace? See [TS Playground](http://www.typescriptlang.org/Playground#src=%2F%2F%2F%20%3Creference%20path%3D%22grid.ts%22%20%2F%3E%0A%2F%2F%2F%20%3Creference%20path%3D%22components%2FagGridNg2.ts%22%20%2F%3E%0A%2F%2F%2F%20%3Creference%20path%3D%22components%2FagGridWebComponent.ts%22%20%2F%3E%0A%0Adeclare%20var%20exports%3A%20any%3B%0A%0Anamespace%20ag%20%7B%0A%09declare%20var%20module%3A%20any%3B%0A%09%0A%20%20%20%20%2F%2F%20Establish%20the%20root%20object%2C%20%60window%60%20or%20%60exports%60%0A%20%20%20%20var%20root%20%3D%20%3Cany%3E%20window%3B%0A%0A%20%20%20%20%2F%2F%20provide%20a%20reference%20to%20angular%0A%20%20%20%20var%20angular%20%3D%20(%3Cany%3E%20window).angular%3B%0A%0A%20%20%20%20%2F%2F%20if%20angular%20is%20present%2C%20register%20the%20directive%20-%20checking%20for%20'module'%20and%20'directive'%20also%20to%20make%0A%20%20%20%20%2F%2F%20sure%20it's%20Angular%201%20and%20not%20Angular%202%0A%20%20%20%20if%20(typeof%20angular%20!%3D%3D%20'undefined'%20%26%26%20typeof%20angular.module%20!%3D%3D%20'undefined'%20%26%26%20angular.directive%20!%3D%3D%20'undefined')%20%7B%0A%20%20%20%20%20%20%20%20var%20angularModule%20%3D%20angular.module(%22agGrid%22%2C%20%5B%5D)%3B%0A%20%20%20%20%20%20%20%20angularModule.directive(%22agGrid%22%2C%20function()%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20restrict%3A%20%22A%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20controller%3A%20%5B'%24element'%2C%20'%24scope'%2C%20'%24compile'%2C%20'%24attrs'%2C%20AngularDirectiveController%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20scope%3A%20true%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%3B%0A%20%20%20%20%20%20%20%20%7D)%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20if%20(typeof%20exports%20!%3D%3D%20'undefined')%20%7B%0A%20%20%20%20%20%20%20%20if%20(typeof%20module%20!%3D%3D%20'undefined'%20%26%26%20module.exports)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20exports%20%3D%20module.exports%20%3D%20angularGridGlobalFunction%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20exports.angularGrid%20%3D%20angularGridGlobalFunction%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20root.agGridGlobalFunc%20%3D%20angularGridGlobalFunction%3B%0A%0A%20%20%20%20function%20AngularDirectiveController(%24element%3A%20any%2C%20%24scope%3A%20any%2C%20%24compile%3A%20any%2C%20%24attrs%3A%20any)%20%7B%0A%20%20%20%20%20%20%20%20var%20gridOptions%3A%20any%3B%0A%20%20%20%20%20%20%20%20var%20quickFilterOnScope%3A%20any%3B%0A%0A%20%20%20%20%20%20%20%20var%20keyOfGridInScope%20%3D%20%24attrs.agGrid%3B%0A%20%20%20%20%20%20%20%20quickFilterOnScope%20%3D%20keyOfGridInScope%20%2B%20'.quickFilterText'%3B%0A%20%20%20%20%20%20%20%20gridOptions%20%3D%20%24scope.%24eval(keyOfGridInScope)%3B%0A%20%20%20%20%20%20%20%20if%20(!gridOptions)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20console.warn(%22WARNING%20-%20grid%20options%20for%20ag-Grid%20not%20found.%20Please%20ensure%20the%20attribute%20ag-grid%20points%20to%20a%20valid%20object%20on%20the%20scope%22)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20return%3B%0A%20%20%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%20%20%20var%20eGridDiv%20%3D%20%24element%5B0%5D%3B%0A%20%20%20%20%20%20%20%20var%20grid%20%3D%20new%20ag.grid.Grid(eGridDiv%2C%20gridOptions%2C%20null%2C%20%24scope%2C%20%24compile%2C%20quickFilterOnScope)%3B%0A%0A%20%20%20%20%20%20%20%20%24scope.%24on(%22%24destroy%22%2C%20function()%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20grid.destroy()%3B%0A%20%20%20%20%20%20%20%20%7D)%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20%2F%2F%20Global%20Function%20-%20this%20function%20is%20used%20for%20creating%20a%20grid%2C%20outside%20of%20any%20AngularJS%0A%20%20%20%20function%20angularGridGlobalFunction(element%3A%20any%2C%20gridOptions%3A%20any)%20%7B%0A%20%20%20%20%20%20%20%20%2F%2F%20see%20if%20element%20is%20a%20query%20selector%2C%20or%20a%20real%20element%0A%20%20%20%20%20%20%20%20var%20eGridDiv%3A%20any%3B%0A%20%20%20%20%20%20%20%20if%20(typeof%20element%20%3D%3D%3D%20'string')%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20eGridDiv%20%3D%20document.querySelector(element)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20(!eGridDiv)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20console.warn('WARNING%20-%20was%20not%20able%20to%20find%20element%20'%20%2B%20element%20%2B%20'%20in%20the%20DOM%2C%20Angular%20Grid%20initialisation%20aborted.')%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20eGridDiv%20%3D%20element%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20new%20ag.grid.Grid(eGridDiv%2C%20gridOptions)%3B%0A%20%20%20%20%7D%0A%0A%7D)

**Comment by ceolter** [comment]
done. i've moved to node.d.ts

**Comment by aciccarello** [comment]
Thanks! Looking forward to this getting into DefinitelyTyped and to your AngularConnect talk.

**Comment by ceolter** [comment]
> Looking forward to this getting into DefinitelyTyped and to your AngularConnect talk

you going?

**Comment by aciccarello** [comment]
> you going to Angular Connect?

No but I'm planning on watching the livestream. I'll be going to ng-Conf though.

**Comment by ceolter** [comment]
lets see if they invite me back to ng-Conf after my talk at Angular Connect!!!

**Comment by aciccarello** [comment]
:+1:

**Comment by RefactorMan** [comment]
I still have this issue. I installed ag grid d.ts from DT,  using typings command. 
"declare var module"  is still in the file.  What should I do with this conflict?

**Comment by aciccarello** [comment]
@RefactorMan Look for a d.ts file included with the npm package. That one is likely more up to date.
