### ISSUE TITLE
groupRowRenderer not being called when passed a function

### ISSUE THREAD

**Issue by GeorgeNYCDA** [ceolter/ag-grid#490]
Hey Niall, I'm having issues with the groupRowRenderer not being called when I'm passing it a function.  When I pass it an object it works as expected but it's not reacting to a function.  I'm definitely setting the groupUseEntireRow=true configuration.  Can you try this out on your end and let me know if it works for you?  Thanks.

**Comment by ceolter** [comment]
What version you on?

**Comment by GeorgeNYCDA** [comment]
I initially tried it on 1.14 then I upgraded to 2.3.0.  It didn't seem to work for either.

**Comment by ceolter** [comment]
fixed. will be included in next release. thanks for raising. this hasn't worked in a while, you must be the only person using it!!
