### ISSUE TITLE
Double click group header to expand

### ISSUE THREAD

**Issue by Shadlington** [ceolter/ag-grid#493]
Hi there, I was wondering if there was a way to set the group headers to expand upon double clicking (anywhere in the group header, not just after clicking the expand icon).

Incidentally, love the grid, it's really awesome - thanks for all the work you do on it :)

**Comment by Shadlington** [comment]
Oh and the inverse too - collapsing upon double click of an already-expanded group header.

**Comment by ceolter** [comment]
lol, i'll have to think about this one!!!

what i'm planning to do is refactor the headers, to allow much better customisation of them, so you can add this type of behaviour easily yourself if you want.

i'll leave this open, but i i'll put it aside for the moment, wait for my column header refactoring to be done.

thanks for the positive feedback :)

**Comment by HarperHampton** [comment]
We need the group header to be keyboard accessible.  This means that it needs to be able to receive focus AND to listen/act on a keyboard select event.   This was discussed in the forum:   http://ag-grid.com/forum/showthread.php?tid=3076&pid=6529#pid6529

We need this same functionality on row-expanders as well.

**Comment by ceolter** [comment]
now that you can provide your own header templates, you can put this login in yourself.
