### ISSUE TITLE
Pivot mode forces me to perform execute grouping/value columns in specific order.

### ISSUE THREAD

**Issue by Krzysztof1985** [ceolter/ag-grid#4939]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Hello I am using AG-grid and I have to use server **side row data model**. Based on AG-Grid-Oracle example I adjusted a little bit the queries and behaviour for postgres db, after some filter adjustments on backend in Java (my customization in implementation) works nicely!

I have issues with pivot mode. Pivot requires me to execute (drag & drop) or click by the columns which I would like to use in specific order. I always must use "value" column (numeric type) as a last one step, otherwise I got finished with empty grid.

**Providing a Reproducible Scenario**
I am starting with AG-Grid server side row data model,
- switch to pivot mode using slider
- group by column A, column B etc... (any column which is not "number" type of column)
- value column (amount in my case)
- label column

Result:
Grid is displaying proper layout but without the values.

**Working sequence example**
- switch to pivot mode using slider
- group by column A, column B etc... (any column which is not "number" type of column)
- label column
- value column (amount in my case) must be provided as a last one (drag & drop) or click

**Expected behavior**
Pivot should be generated no matter if I select value column first, then group and then label column.

**Current behavior**
Ag grid lost the "sequence" of the request and is not refreshing the data properly

**Please tell us about your environment:**
Mac OS 10, IntelliJ, Java 11 + Spring boot 2.5, PostgreSQL

* **AG Grid version:** 26.2.0

* **Browser:**
Chrome  98.0.4758.109 (x86_64)

* **Language:** [ReactJS]

This is my code snippet
```javascript
....
required imports
...

const Worksheet = () => {
  const gridRef = useRef();
  const [enableRangeSelection] = useState(true);
  const [sideBar] = useState(true);
  const [groupIncludeFooter] = useState(true);
  const [showEnableRowGroupPanel] = useState("always");
  const [animateRows] = useState(true);
  const [rowModelType] = useState("serverSide");
  const [serverSideStoreType] = useState("partial");
  const [gridApi, setGridApi] = useState(null);
  const [gridColumnApi, setGridColumnApi] = useState(null);

  const handleOnGridReady = params => {
    setGridApi(params.api);
    setGridColumnApi(params.columnApi);
    params.api.setServerSideDatasource(datasource);
  };

  const datasource = {
    getRows(params) {
     backendService.getRows(params.request)
        .then(response => {
          params.successCallback(response.data, response.lastRow);
          params.success({ rowData: response.data });
          addPivotColDefs(response, params.columnApi);
        })
        .catch(error => {
          console.log(error);
          params.failCallback();
        });
    },
  };

  const addPivotColDefs = (response, columnApi) => {
    const existingPivotColDefs = columnApi.getSecondaryColumns();
    if (existingPivotColDefs && existingPivotColDefs.length > 0) {
      return;
    }
    const pivotColDefs = response.secondaryColumnFields.map(function(field) {
      const headerName = field.split("_")[0];
      return { headerName, field };
    });
    columnApi.setSecondaryColumns(pivotColDefs);
  };

  return (
    <AgGridReact
      ref={gridRef}
      maxConcurrentDatasourceRequests={1}
      columnDefs={columnsDefinition}
      autoGroupColumnDef={autoGroupColumnDef}
      rowModelType={rowModelType}
      defaultColDef={defaultColumnDefinition}
      onGridReady={handleOnGridReady}
      serverSideStoreType={serverSideStoreType}
      sideBar={sideBar}
      enableRangeSelection={enableRangeSelection}
      cacheBlockSize={100}
      groupIncludeFooter={groupIncludeFooter}
      rowGroupPanelShow={showEnableRowGroupPanel}
      animateRows={animateRows}
      rowGroupOpened={handleRowGroupOpened}
    />
  );
};
```
This sequence works
![Pivot-sequence](https://user-images.githubusercontent.com/2550886/155554294-1b7b8091-33d7-46c9-8a89-fe62c0b24868.png)

This sequence is not working

![pivot-incorrect-sequence](https://user-images.githubusercontent.com/2550886/155555161-06e1e16d-1fe9-40e7-bb5c-4253ba03a4a5.png)

I have only custom value formatter for numbers (3 decimal places) + custom cellRendererParams for autogroup columns.
But this is not an issue, when I am using default ones this also is not working.
For sure there is not an issue with backend, I messed up something with frontend, but I don't know what is wrong.

Can you help me in this case, please?

**Comment by icedjello** [comment]
Hi, 

Thank you for raising this, a member of our team will have a look and get back to you when we have an answer.

Thanks again,

**Comment by icedjello** [comment]
Hi, 
 
I've tried to replicate your example in the following plunker: 
 
https://plnkr.co/edit/eSoYo8JQxB0J01Wy 
 
As you can see, you can add the groups values and labels in any order and the grid works. 

To investigate further, I will need to see a working example of this issue.

**Comment by makinggoodsoftware** [comment]
Hi Chris,

Thanks for this, we will close this then and continue the investigation on Zendesk

**Comment by Krzysztof1985** [comment]
Hello,

This is the repo, which requires a very small setup.
Please do not put this code into public places.

Soon I will provide a pull request with AG-Grid for PostgreSQL.
I spent a lot of time adjusting the filter mechanisms on the backend.

https://drive.google.com/file/d/1nzQmHEFNDsBrK2TJsP8Hp8dmJ0ymi5wV/view?usp=sharing

Alternatively I can push this code to the bitbucket. I don't want to
publish this code (for now) in a public github repo.
Please give me some time and I will also give something from me to the
community ;) (for example filters, sorting, complex filters on backend
side).

Thank you in advance!

Krzysztof



pt., 11 mar 2022 o 16:11 Bamdad Fard ***@***.***> napisał(a):
