### ISSUE TITLE
Set open/close state of group headers

### ISSUE THREAD

**Issue by Shadlington** [ceolter/ag-grid#494]
Is there a way to set the open/close state of the group headers programmatically? And also to get the current open/close state? And watch for changes to this state?

My use case is saving/restoring the group header open states.

**Comment by ceolter** [comment]
see here:
http://www.ag-grid.com/angular-grid-column-api/index.php

to set use columnGroupOpened

to inspect use getHeaderGroups

**Comment by Shadlington** [comment]
Oops, sorry. Knew about getHeaderGroups but missed columnGroupOpened in the docs. Thanks :)

**Comment by ceolter** [comment]
no worries

i can't remember doing it so it was a nice surprise to me when i went to the api and found it was all available!!!
