### ISSUE TITLE
virtual scrolling in ie 11

### ISSUE THREAD

**Issue by sadamia** [ceolter/ag-grid#496]
Hello @ceolter,

ag-grid virtual scrolling doesn't work in ie11, do you have any thoughts about that ? It works like an infinite scroll, the scroll tracker doesn't compute the scroll height.

**Comment by sadamia** [comment]
I found similar issue #226, seems it is a problem.

**Comment by ceolter** [comment]
is this the same issue or a similar issue? if same, then i'll close this as a duplicate.

i don't know yet how to solve this. nothing has been presented to me by the community and i haven't invested much time into it myself.

**Comment by ceolter** [comment]
no feedback, over 1 year old, closing.
