### ISSUE TITLE
CSV Export Limit Failing Silently (Chrome)

### ISSUE THREAD

**Issue by aciccarello** [ceolter/ag-grid#501]
I'm running into a limit in the amount of data that can be exported via CSV. The export of data fails silently when the amount of data gets too big. Is this a known issue? I've been able to reproduce the issue in Chrome 46.

As a reference, I was able to export a larger amount of data using ng-csv but it didn't respect the columns shown, order, etc. so I would like to use the native feature if possible. 

## Example
See this [plunker](http://plnkr.co/edit/opk1pza6gbvpSk9iluvD?p=preview) for a demonstration of the limit. Clicking the download link doesn't work untill you cut the number of rows in half (by commenting out a line in `exportExample.js`.

```JavaScript

    $http.get("olympicWinners.json")
        .then(function(res){
            var olympicWinners = res.data
            // double the size several times (plunker complained till I trimmed down olympicWinners.json)
            olympicWinners = olympicWinners.concat(olympicWinners);
            olympicWinners = olympicWinners.concat(olympicWinners); // comment this line to get the export working
            // olympicWinners = olympicWinners.concat(olympicWinners);
            $scope.gridOptions.api.setRowData(olympicWinners);
        });
```

**Comment by aciccarello** [comment]
Here's an example using ng-csv and many more rows.
http://plnkr.co/edit/a48Vl3?p=preview

**Comment by ceolter** [comment]
ah crap! i wasn't aware of that. don't suppose your know why it silently fails???

**Comment by aciccarello** [comment]
If I recall correctly from when I stepped through the debugger. It creates an `<a>` element with the href but the call to click on it doesn't do anything. I'm not sure what's going on beyond that.

**Comment by ceolter** [comment]
ok thanks. i'll see what i can do. but i'm busy the next few days :(

**Comment by aciccarello** [comment]
That's fine. I'll let you know if I find out anything else.

**Comment by ceolter** [comment]
this is fixed, so closing.

**Comment by aciccarello** [comment]
Great! thank you! And great talk at AngularConnect. It was cool to see how ag-grid is put together.
