### ISSUE TITLE
Virtual paging - grid height

### ISSUE THREAD

**Issue by joshikeerti** [ceolter/ag-grid#502]
I am using the  virtual paging feature, however I need to make server calls to get data for each page,

Below is the code where I am handling the virtual paging.
and the html where grid height is specified. However, when the data is loaded in the grid, there is some extra empty space at the bottom, so the grid height is not being calculated correctly.

Is there anything I am missing that can fix the height calculation?

html -
```  <div ag-grid="main.gridOptions" class="ag-fresh ag-fresh-custom" style="height:630px;width:100%">```

```  
messages.loadAppData = function(currAppId, sortBy, locale) {
    var pageNum = 1;
    setTimeout(function() {
      messages.keyDetails = []; //response.data.messages[0];
      var dataSource = {
        rowCount: null, // behave as infinite scroll
        pageSize: perPage,
        overflowSize: perPage - 20,
        getRows: function(params) {
          pageNum = params.endRow / perPage;
          console.log("pageNum", pageNum);
          $http.get(Configuration.baseUrl + '/applications/' + currAppId + '/messages?page=' + pageNum + '&rowsPerPage=' + perPage + '&sortBy=' + sortBy + '&locale=' + locale).then(function(response) {

            messages.keyDetails.push.apply(messages.keyDetails, response.data.messages);
            var rowsThisPage = messages.keyDetails.slice(params.startRow, params.endRow);
            // if on or after the last page, work out the last row.
            var lastRow = -1;
            if (messages.keyDetails.length <= params.endRow) {
              lastRow = response.data.pagination.totalPages * perPage;
            }
            // call the success callback
            params.successCallback(rowsThisPage, lastRow);
          }, function(error) {
            messages.alertModal("No Records Found");
          });
        }
      };
      messages.gridOptions.api.setDatasource(dataSource);
    }, 50);
};
```

**Comment by ceolter** [comment]
> there is some extra empty space at the bottom

are you expecting the grid to resize? if so , the grid doesn't resize based on the data, it stays as the height you specify.

but  i think it might be this:
```
        pageSize: perPage,
        overflowSize: perPage - 20,
```

the overflow should be a positive number. if it's a negative number, then it's going to render less rows to fill a page. try something like this:
```
        pageSize: perPage,
        overflowSize: 20,
```

ps i'm closing this, the preferred way to get help is the forum. issues are for changes required in the grid!
