### ISSUE TITLE
checkbox check event

### ISSUE THREAD

**Issue by pallavi-shailja** [ceolter/ag-grid#507]
Hi,
I need a popup on checkbox check in grid.When we check checkbox rowClicked event is getting fired and modal is getting popped up. This popup opens even if I click on other cells of the row also.
Please suggest me what to do to open popup only on checkbox check.

Thanks & Regards,
Pallavi Shailja

**Comment by ceolter** [comment]
listed for the rowSelected event, not the rowClicked event.

ps, github issues for something wrong in the grid. please use the forum for questions.
