### ISSUE TITLE
pagination - if lastRow is smaller than params.startRow keeps changing empty pages for ever

### ISSUE THREAD

**Issue by chiptus** [ceolter/ag-grid#510]
Hi,

First I'd like to say again thanks for the awesome work you've done.
Secondly, I'm encountering a bug while trying to use paging.
I have two ways to know I've reached the last page:
1. either by seeing that the received data length is smaller than the page size, in that case i'me covered. 
2. other case is that the data length is the same size as the page size and then I'll only know that I've received the last page at the next time when i get data length equals zero. 
In this case I'll have an empty page appearing in the grid, what I would like is a way to the the grid to return to the previous page. I can return a failed callback but if I do that the grid won't know that it reached the end and will issue a call to the server every time.

What do you think? I can help implement it and PR it, but I don't like to do any mess, would you prefer it to be part of the getRows function api. Maybe have the success callback check for empty rows parameter and return back in that case?

Thanks!
Chaim

**Comment by chiptus** [comment]
I tried to use failCallback, but it didn't do anything? shouldn't it at least return to the previous page?

**Comment by ceolter** [comment]
> I tried to use failCallback, but it didn't do anything? shouldn't it at least return to the previous page?

that's for a non-recoverable error, not something your system should be using as a normal flow.

eg the server is down!!

**Comment by ceolter** [comment]
re the page size, what you should be doing is asking the server if there are more pages. this is normally done by looking for (pageSize + 1) rows each time on the server, and then discarding the very last row (the only purpose of the very last row is to tell you another row exists).
