### ISSUE TITLE
Grid on an angular-ui bootstrap tab. Noticeable column header render issue.

### ISSUE THREAD

**Issue by daric81** [ceolter/ag-grid#511]
Table content rendered fine, however headers don't appear initially and when they do they move table content down. Worked in 1.14.1 but an issue in 1.15.0 onwards. (I'm using Chrome)

See forum [post](http://www.ag-grid.com/forum/showthread.php?tid=2905&pid=5745#pid5745) for repro/plunk.

**Comment by ceolter** [comment]
cleaning up old issues. if this a problem with the grid (ie not your application) then reopen and explain. grid has moved on many versions since this was raised.
