### ISSUE TITLE
sortModel / filterModel query string syntax doesn't fit ASP.NET MVC / JSON deserializer

### ISSUE THREAD

**Issue by SetTrend** [ceolter/ag-grid#514]
ag-grid creates something similar to the following query string parameter arguments when requesting a data source:

```
Request.QueryString.AllKeys:
    [0]: "startRow"
    [1]: "endRow"
    [2]: "sortModel[0][colId]"
    [3]: "sortModel[0][sort]"
    [4]: "filterModel[col01][]"
```

The ASP.NET MVC JSON deserializer is not able to deserialize the `sortModel` structure back into:

```c#
public class AgSortItem
{
    public string colId;
    public string sort;
}

public JsonResult agGet(int startRow, int endRow, AgSortItem[] sortModel, AgFilterItem[] filterModel)
{}
```

Same for `filterModel` ...

<br/>
I believe this is due to the (invalid) array syntax used for `colId` and `sort`. *(If using array syntax was done intentionally then `colId` and `sort` should be surrounded by quotes.)*

Wouldn't it be preferrable to have the sortModel/filterModel query string amended into sending a structure like this:

```
Request.QueryString.AllKeys:
    [0]: "startRow"
    [1]: "endRow"
    [2]: "sortModel[0].colId"
    [3]: "sortModel[0].sort"
    [4]: "filterModel.col01"
```
... to avoid the cumbersome necessity of being required to manually parse the sortModel/filterModel?

**Comment by S-YOU** [comment]
strange - if I `JSON.stringify(params.sortModel)` object I got like 
`[{"colId":"sport","sort":"asc"}]`

**Comment by SetTrend** [comment]
Ah, I see ... This isn't a `ag-grid` issue, it rather could be regarded a `jQuery` issue. I was expecting this to work without `JSON.stringify()`.

Thanks for enlightening me!
