### ISSUE TITLE
Loader not showing on keyboard event

### ISSUE THREAD

**Issue by LucasWerner437** [ceolter/ag-grid#5204]
**I'm submitting a ...**
```
[x] bug report
[] feature request
[] support request
```

**Current behavior**
I wanted to be able to delete data from the grid by pressing delete key on keyboard. Since my grid is tied to some data in the back end I implemented an AJAX call to persist changes.
I used the suppressKeyboardEvent() method as described in the docs.
So far the implemented logic works, meaning the call is triggered and server does its job, returning expected response leading to a remove transaction in the datagrid. 

BUT

I wanted to display the loader overlay whenever a user starts a delete operation on one or more rows. I'm actually using a similiar feature for edit operations so the user knows when the server starts et ends its process.
Thing is though, the loader shows fine inside the onValueChange() method but not at all in the suppressKeyboardEvent() method.

**Expected behavior**
Loader overlay should show whenever it's called, that's to say whenever the gridApi.showLoadingOverlay() is called.

**Code samples**
```
onCellValueChanged: async ev => {
            // This method call actually does show the loader
            ev.api.showLoadingOverlay();
            // Cell Value Edit => Triggers PUT call
            const {edit, ...resource} = ev.data;
            let response = await this.#editRow(edit, resource);
             // And this method hides it back
            ev.api.hideOverlay();
        }
```

```
suppressKeyboardEvent: params => {
            // If user not already in edition mode, delete or backSpace btns trigger DELETE call for selected rows
            if (!params.editing) {
                let isBackspaceKey = params.event.keyCode === 8;
                let isDeleteKey = params.event.keyCode === 46;

                if (isBackspaceKey || isDeleteKey) {
                    // Don't know why but loader is not showing after the next method call.
                    params.api.showLoadingOverlay();

                    // The rest of the logic works fine though
                    // AJAX call fires and after data was properly removed from DB the grid removes it also via a transaction
                    const selectedRows = params.api.getSelectedRows();

                    selectedRows.forEach(async row => {
                        const isDeleted = await this.#deleteRow(row.edit);
                        if (isDeleted) {
                            params.api.applyTransaction({ remove: [row] });
                        }
                    });

                    params.api.hideOverlay();
                    return true;
                }
            }
            return false;
        }
```

**Please tell us about your environment:**
Windows 11, PHPStorm, npm

* **AG Grid version:** 27.2

* **Browser:**
* Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36 Edg/101.0.1210.47
* (Edge Chromium latest)

* **Language:** [ES6/7]

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks
