### ISSUE TITLE
overlayNoRowsTemplate not showing on initialize (rowData)

### ISSUE THREAD

**Issue by carloshpds** [ceolter/ag-grid#524]
`overlayNoRowsTemplate` does not appear on initialize when you're using `rowData` attribute and  try to pass an empty array as table data.

it works when you use `setDatasource` instead of `rowData`.

**Comment by ceolter** [comment]
will be in next release

**Comment by carloshpds** [comment]
Nice !! :+1: 
Thanks for the quick answer :)

**Comment by carloshpds** [comment]
@ceolter It's happening again after upgrade to `v4.0.5` :/

**Comment by ceolter** [comment]
i believe this is fixed in the latest
