### ISSUE TITLE
each cell should have isolated $scope

### ISSUE THREAD

**Issue by faizanali6** [ceolter/ag-grid#535]
I want to show datepicker for datetime fields. I have this cellRenderer function

    $scope.dateEditor = function(params) {
      var html = '<span ng-show="!editing" ng-click="editing=true">{{data.'+params.colDef.field+'}}</span> '    +
          '<input ng-blur="editing=false" ng-change="editing=false" ng-show="editing" type="text" class="form-control" data-ng-model="data.'+params.colDef.field+'" bs-datepicker data-date-format="yyyy-MM-dd" data-date-type="string" >'
      return html;
    }

The issue is I have multiple date fields in a single row. When I click one other also go in edit mode because the cell don't have its own isolated scope.

**Comment by ceolter** [comment]
one scope per row is done on purpose, to keep the grid extremely fast.

if you need isolated scope per cell, you will need to introduce your own directive to be used inside the cell.
