### ISSUE TITLE
checkboxSelection - Checking one checkbox uncheck other checkboxes in other rows.

### ISSUE THREAD

**Issue by faizanali6** [ceolter/ag-grid#536]
when checkboxSelection is set to true. If I check one checkbox all others get uncheck. What is the problem?

**Comment by ceolter** [comment]
maybe you need to set selection to multiple??

ps if it's a question or an issue in your client code, please use the forum, github should be kept for issues inside the grid.

**Comment by ceolter** [comment]
rowSelection	Type of row selection, set to either 'single' or 'multiple' to enable selection.
