### ISSUE TITLE
selectAll doesn't fire selection events

### ISSUE THREAD

**Issue by ceolter** [ceolter/ag-grid#537]

**Comment by simoneb** [comment]
If you have any hints about how this can be fixed I'd be glad to submit a PR because this is hitting us. We select all rows programmatically using the API but when we use the copy to clipboard feature nothing is copied.

**Comment by ceolter** [comment]
this is working on the latest. it's an old issue form last year, the selection has undergone a lot of work since then. if you are on the latest, and still broken, please give details on how to reproduce and i can take a look. however i tested it just now on the main demo page (i called selectAll() after setting the row data, and all events are getting fired).

**Comment by ckiss** [comment]
@ceolter in this example https://www.ag-grid.com/javascript-grid-selection/example4.html from the documentation if you "select all american" and CTRL+C nothing gets copied to clipboard

**Comment by ceolter** [comment]
@ckiss because it's not using enterprise version of ag-grid, just the free version. clipboard is an enterprise feature.

**Comment by ckiss** [comment]
@ceolter sorry, that's a bad example. though this one should reproduce what I'm saying https://www.ag-grid.com/javascript-grid-clipboard/exampleClipboard.html if you select let's say 4 random rows and CTRL + C it doesn't work properly

**Comment by feugy** [comment]
To be more precise, it depends *how* you select them:
- contiguous selection using left click and `SHIFT`, then `CTRL+C`: works, all rows are copied.
- random selection using left click and `CTRL`, then `CTRL+C`: doesn't work: only the *first cell* clicked is copied.

This bug doesn't occur when using the "Copy selected rows to clipboard" button, only using keyboard shortcut.

@ceolter, can you confirm this is a bug ?

**Comment by ckiss** [comment]
That's true, and in our app we have a button that selects all rows using `gridApi.selectAll()` in which case `CTRL + C` doesn't work either.

**Comment by ceolter** [comment]
if you are using range selection, then this gets preference. even if the range is one cell.

can you turn range selection off? then try?

**Comment by ckiss** [comment]
@ceolter range selection is disabled by default, right? we haven't enabled it, so that shouldn't be the cause

**Comment by ceolter** [comment]
range selection is off by default.

the example you provided had range on, so maybe a bad example.

i updated the main demo page (just locally) and turned off range selection and i was not able to reproduce this, only selected rows get copied.

**Comment by ckiss** [comment]
Thank you @ceolter, but in our case we don't have range selection on and we don't select all rows by clicking them but by clicking a button that calls gridApi.selectAll().

The button is part of the grid(like excel, top left corner).
Everything works fine when we select multiple rows by holding down CTRL, or contiguous selection using SHIFT, you can ignore these situations. The only one that makes us problems is the one above when we select using the API. 
I also tried forEachNode to set each node as selected but after that CTRL+C still wouldn't work.

And yes, we use ag-grid enterprise.

**Comment by ceolter** [comment]
on the main demo page, i took out range selection, then put the following in:
```
setTimeout( function() {
    gridOptions.api.selectAll();
}, 2000);
```

after selection happens, i then click on a cell (so it gets focus) and hit ctrl+c, and it works.

maybe you don't have browser focus on the grid? in which case, it doesn't get the ctrl+c command.

otherwise, i can't reproduce this, please provide a plunker to take it further.
