### ISSUE TITLE
ebody returns 0 width when doing sizeColumnsToFit

### ISSUE THREAD

**Issue by chiptus** [ceolter/ag-grid#539]
for some reason my columns doesn't spread on all the grid width. when I'm putting a breakpoint in the function, I can see that this.eBody.clientWidth return 0.
But I saw that this.eBody should be document.querySelector(".ag-body"), and checking the width of .ag-body I see that it has the right size, not 0 as returns in the function (running document.querySelector(".ag-body").clientWidth return 2000px).
I'm almost sure it's something with my design, because on another app sizeColumnsToFit does work.
But what I thought was weird is that this.eBody!==document.querySelector('.ag-body'). Is it the way it's suppose to be?   

Thanks for the wonderful grid

**Comment by ceolter** [comment]
Is the grid in the dom and on the page? The width will return 0 if grid has no width (yet). Try putting you call into a timeout.

**Comment by chiptus** [comment]
it is inside a timeout, and I tried even calling it from the console (by
getting the scope with angular.element().scope()) both ways width is 0

**Comment by ceolter** [comment]
eBody IS ag-body, this is my code:
```
                this.eBody = this.queryHtmlElement('.ag-body');
```

so i don't know how your getting this.eBody!==document.querySelector('.ag-body')

**Comment by chiptus** [comment]
I ran the function and have a breakpoint on the place it calculates the
width. I then run

this.eBody === document.querySelector('.ag-body');

and get false.

I know that it should be true, that's why I opened this bug.

**Comment by chiptus** [comment]
ok, sorry, as I said, it was a bug with my app.
I used a directive for doing multi-transclude that instead of moving the nodes it just copied the innerHtml, and thus when you first load this.eBody it gets one value and then the node is removed from the dom.

I think :)

Thank you for the help

**Comment by ceolter** [comment]
Great. Thanks for updating and closing the issue.
