### ISSUE TITLE
[cell resize] groups always resize despite resize suppressed in children

### ISSUE THREAD

**Issue by ceolter** [ceolter/ag-grid#541]
http://www.ag-grid.com/forum/showthread.php?tid=3019

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-82

**Comment by bondib** [comment]
+1 on this.
This is making trouble for us as well. Please fix ASAP.

**Comment by ceolter** [comment]
fixed. will be in next release.

**Comment by makinggoodsoftware** [comment]
Hi,

Just to let you know that as of 11.0.0 this has been implemented, see the changelog for more details..

https://www.ag-grid.com/change-log/changeLogIndex.php#gsc.tab=0
