### ISSUE TITLE
Multi-Level grouped headers

### ISSUE THREAD

**Issue by axelnormand** [ceolter/ag-grid#543]
I'm looking to implement mutli-line (or rather multi level) grouped headers and was wondering if you could point me in the right direction with regards to how you might do this with a custom renderer and which css classes you might use.

I also see your re-doing the header rendering so am wondering if i should wait if your next release is imminent

To model this, I'm guessing instead headerGroup property i might want to specify an array of header groups for the "Value" column.
```
headerGroups: ["Region", "Date"]
```

Then have multiple sibling divs with a css class like ".ag-header-group-cell" and the correct widths.
Then fix the header height.

This might end up looking like this
Note that the "Value" header is first. The purpose of this feature is to easily compare values on different days across different regions for the same stock

```
-----------------------------------------------------------------------
Stock        |                          Value                         |
             ---------------------------------------------------------
             |        USA                   |                 UK      |
             ---------------------------------------------------------
             | 29th Oct |  30th Oct         |   29th Oct | 30th Oct   |
-----------------------------------------------------------------------
AAPL         |  $100    |     $200          |   $300     | $400       |
-----------------------------------------------------------------------
```
Any hints much appreciated and many thanks for a great library.

**Comment by ceolter** [comment]
the next major release will be in 2016. nothing imminent.

there is a PR for this:

**Comment by axelnormand** [comment]
Thank you for your speedy response!
I'll take a look at the PR which should point me in the right direction. Hopefully i'll be able to do all i want with a custom header renderer rather than a fork but open to either method.

Many thanks

**Comment by Chandru22714** [comment]
How to handle multi level grouped headers customization? I don't find relevant documentation to try in latest version of ag grid angular. Please help to create the layout of the table below,

![image](https://user-images.githubusercontent.com/15182262/209123160-027185e3-b5cb-4ffd-9ea2-5da9062e240f.png)
