### ISSUE TITLE
Trigger external filter immediately

### ISSUE THREAD

**Issue by ejbaker** [ceolter/ag-grid#545]
I have data that I want to "page" with tabs by, for example, month.

Setting this as an external filter works fine, except that on initial page load *all* the data is shown, even though self.selected is already defined as the current month elsewhere.

```javascript
		$scope.grid = {};
		$scope.grid.gridOptions = {
			columnDefs:columnDefs,
			rowData:rowData,
			enableSorting: true,
			isExternalFilterPresent:isExternalFilterPresent,
			doesExternalFilterPass:doesExternalFilterPass,
		};
		// always true... but just setting this to true doesn't work!
		function isExternalFilterPresent(){
			return true;
		}
		function doesExternalFilterPass(node) {
			return (node.data.tabbedBy === self.selected);
		}
		$scope.grid.externalFilterChanged = function() {
			$scope.grid.gridOptions.api.onFilterChanged();
		};
```

(I should add that setting isExternalFilterPresent to a simple boolean caused the code not to work at all. doesExternalFilterPass never fired. Might be related issue.)

Any help would be appreciated, thanks!

**Comment by ceolter** [comment]
please use the forum for asking question, not github issues. this should be kept for me tracking things i need to work on in the grid.

to get the grid to filter, call api.onFilterChanged()

so call this after you call api.setRowData(data)
