### ISSUE TITLE
Selection: minSelections / maxSelections

### ISSUE THREAD

**Issue by benoror** [ceolter/ag-grid#549]
Is there a way to limit the maximum/minimum numbers of rows to select?

http://www.ag-grid.com/angular-grid-selection/index.php

**Comment by ceolter** [comment]
no, this is not supported by the grid. do other grids do this, and if so, can you explain the general pattern?

**Comment by benoror** [comment]
Sorry, I wasn't thinking straight

In case someone want to see the implementation: http://jsbin.com/zeniye/2/edit?js,console,output
