### ISSUE TITLE
Multi-Level Grouping show 'undefind' values 

### ISSUE THREAD

**Issue by vamsikrishnamannem** [ceolter/ag-grid#555]
Multi-levl grouping shown undefined when the group key is not aviable in row.

![screen shot 2015-11-07 at 4 11 46 pm](https://cloud.githubusercontent.com/assets/7932747/11014742/57fb2876-856a-11e5-9c3e-842460a5d427.png).

**Comment by ceolter** [comment]
use a valueGetter and handle this in your client code. if it was left blank, you could have three blank groups (null, undefined, empty string) with no way of knowing why the duplicate, so solving this problem in the grid just creates another one!
