### ISSUE TITLE
Adding columndef parameter to the signature of the column comparator

### ISSUE THREAD

**Issue by xarsman** [ceolter/ag-grid#556]
##### use case / problem
When I want to sort a grid which is build dynamically, the only realistic option is to use the default sort. This is because the comparator only offer `value` and `node` of the 2 rows-to-compare. If I want to include some meta-data like the datatype, I have two options:
+ Include an extra column which produces a lot of overhead
+ Add 1 extra line to the column definition

The first option produces too much overhead especially when you're handling data with 100.000+ records. The second is ideal but the comparator doesn't have access to the column definition.

##### solution
Add the column definition to the comparator.
Instead of this:
```javascript
return column.colDef.comparator(valueA, valueB, nodeA, nodeB, isInverted);
```
use this:
```javascript
return column.colDef.comparator(valueA, valueB, nodeA, nodeB, column.colDef, isInverted);
```

##### why?
The reason why this is important is because this way you can create a comparator that handles everything based on some meta-info in the column definition. It's a must have to create good grids dynamically.

**Comment by ceolter** [comment]
what you are looking for can be achieved using javascript in a few ways, bind and closure come to mind.

eg closure:
```
function myComparator(type) {
  return function(valA, valB, nodeA, nodeB, inInverted) {
    // here you have all the items you need
    if (type=='myType') {
       // do comparison
    } else {
       // do another type of comparison
    }
  }
}

// then assign
colDef.comparator = myComparator('myType');
```

**Comment by xarsman** [comment]
TIL about javascript closure. Thank you for the fast response and teaching me a new thing
