### ISSUE TITLE
Row formatting

### ISSUE THREAD

**Issue by AbuSufyan** [ceolter/ag-grid#557]
We need to conditionally make a row text as Bold. Currently its working on only single cell but we need to apply text bold on all columns cells. After applying the formatting 'isBold' column must be hide/remove. This column is used only for formatting. How to apply text-indent: 10px; of first column where the isBold column contains true value? Any possibility to achieve this?here is plunker http://plnkr.co/edit/YVGpi2FkwzCl3R1K8fwo?p=preview

**Comment by DrCool** [comment]
Hi Abu.  What you need to use is a custom cellRenderer function. In that function, you will check the "isBold" field to see if the current cell should be bold or not.  The params sent to each cell includes the row's data so it's easy for a cell in a row to check a value in another cell of the same row.

Here's a plunker showing the code working as you described:
http://plnkr.co/edit/MfmUPwFJAgdj8goOAHcW?p=preview

**Comment by ceolter** [comment]
issues are for issues with the grid. this is a question so am closing. please use the forum for questions :)
