### ISSUE TITLE
No of rows selection

### ISSUE THREAD

**Issue by AbuSufyan** [ceolter/ag-grid#558]
We need to select maximum two no of rows. How we force that only two rows are selected and how to get selected rows data? Any help would be appreciated.

**Comment by DrCool** [comment]
You're going to want to work with the grid's events: http://www.ag-grid.com/javascript-grid-events/index.php

You'll also want to read about selections: http://www.ag-grid.com/angular-grid-selection/index.php  For example, look at api.getSelectedRows()

I think you'll need to use the onSelectionChanged event in your gridOptions object.  The grid will send a parameter containing the currently selected rows (I think... I haven't tried it).

I don't know how to limit the selection to only two rows.  If this were my project, I would look into the two pages I linked to above to get started, then maybe I would need to track how many rows are currently selected.  If the user clicks on another row to select it (I'd check the onRowClick event), then I might see how to override the user's selection of a third row by defining the selection as the first two selected rows the user made.

**Comment by ceolter** [comment]
as with @DrCool, you need to listen to the events and add your own logic to deselect rows if more than what you want is selected.

please post questions on the forum :)

**Comment by AbuSufyan** [comment]
Thanks for quick response, how we select more than one row without pressing the 'Ctrl' button, same like single click? Any help would be appreciated.

**Comment by ceolter** [comment]
please post questions on the forum :)
