### ISSUE TITLE
Export to Excel

### ISSUE THREAD

**Issue by AbuSufyan** [ceolter/ag-grid#559]
We need to export ag-grid to excel with formatting. Is there any why of export with full formatting like bold, text indent, colors etc? Please suggest any plunker.

**Comment by DrCool** [comment]
You'll need to write your own export function but that's not too difficult to do.  There are a lot of table and JSON export-to-Excel functions out there you can copy/paste.  You'll need to get exportable data using this ag-grid api call: getDataAsCsv(params).  To know what params you can use, check the export page here: http://www.ag-grid.com/angular-grid-export/index.php

Now, you'll need to create an HTML table with the data but include your styles inline for each table cell `<td>`.  For example, you may have a row that looks like this:

    <tr>
        <td style="font-weight: bold; color: #FF0000">($1,592)</td>
        <td style="background-color: #F0F0F0">Some text</td>
    </tr>

More info on CSS styles when exporting to Excel:
https://www.google.com/?gws_rd=ssl#q=preserve+css+styling+export+to+excel

See here for three specific rules to keep in mind when defining styles to export to Excel:
http://stackoverflow.com/questions/18467418/retain-html-table-styling-after-exporting-to-excel-using-javascript-jquery

**Comment by ceolter** [comment]
this is not an issue with the grid. closing!
