### ISSUE TITLE
Default text filter, on type "ends with", fails on rows with duplicate substrings

### ISSUE THREAD

**Issue by andre-morassut** [ceolter/ag-grid#560]
Using the built-in filter for 'text' with 'ends with' type fails on rows containing multiple occurrences of the filter text.
Example : 
I have a row value "test test" and I use the text filter, typing 't' as filter with 'ends with' type.
The row 'test test' is not shown in the matches.

The bug is due to the algorithm used by the built-in filter : line 2067 & 2068, it should look for _the last_ occurrence and not stop on the first found.

I've made a plunkr to demonstrate the issue : http://plnkr.co/edit/RjmcEs
Simply use the filter on the "Athlete" column, select "ends with" and input "y" : it should show 3 lines (Aleksey, Cindy, Kirsty) but the grid shows no matches.

**Comment by ceolter** [comment]
bug accepted. will get fixed when back from my holidays.

**Comment by andre-morassut** [comment]
Great news. Enjoy your holidays!

**Comment by romain-cadet** [comment]
+1

**Comment by ceolter** [comment]
i tried reproducing this on my latest, and can't. is it still a problem?

i went to ```Apply Function``` example on this page:
https://www.ag-grid.com/angular-grid-filtering/index.php

i filtered on athlete with 'y' and it worked fine.

can this be closed??

**Comment by andre-morassut** [comment]
No it can't be closed, the issue is still present.

Your scenario is perfect to demonstrate the issue. If you filter on athlete with a "y" and "ends with" filter, you'll see that the athlete "Kirsty Conventry" is not in the filtered list. That is the issue : the filter stops on the first "y" and rejects the whole row because this occurrence is not at the end of the word.

**Comment by ceolter** [comment]
cool, fixed. will be in next release. ```string``` has a ```lastIndexOf``` method, made fixing easy!
