### ISSUE TITLE
Column header text alignment with bottom border

### ISSUE THREAD

**Issue by AbuSufyan** [ceolter/ag-grid#564]
Hi,
This is a very nice grid, thank you so much for your great effort, we use this grid and have some requirements about column header text alignment with bottom border of each column, we need to left align first column of header text with all rows cells of that column and rest of all columns are right align with all rows cells, We used following text-align in ag-fresh theme
.ag-fresh .ag-cell {
  padding: 2px;
  text-align:right;
}
.ag-fresh .ag-header-cell-label {
  padding: 4px 2px 4px 2px;
  text-align:right;
  font-weight:bold;
}

but this setting is applied on all columns and rows cells.
How we achieve that same like showing header alignment and cells text with border? Any help would be appreciated.

![11-13-2015 1-04-09 pm](https://cloud.githubusercontent.com/assets/11941140/11141446/55e019ec-8a07-11e5-9c94-64d6393d5128.png)

This is our output after applying above text-align in theme
![11-13-2015 1-35-16 pm](https://cloud.githubusercontent.com/assets/11941140/11141924/6e41961a-8a0b-11e5-8ad6-0d8ed9910db4.png)

**Comment by ceolter** [comment]
Each cell and header div has additional attributes to indicate the column. So what you need to do is use CSS to style the individual column.

Additionally, you can use cellStyle and cellClass for individual cells. These are specified on the colDef.
