### ISSUE TITLE
Multiple rows selection without pressing ctrl button

### ISSUE THREAD

**Issue by AbuSufyan** [ceolter/ag-grid#565]
Hi,
We need to select maximum two no. of rows with out ctrl button pressing same like single row selection, if user select more than two rows than first one is deselect automatically and new one is selected. For example user first selected third and than fourth row, than click on second row apparently  three rows are selected but need to bound the latest two rows. In that case third row automatically deselect and must be vanish from selectedRows collection. How we achieve that goal? Any help would be appreciated.

**Comment by ceolter** [comment]
Set suppressRowClickSelection=true, then add your own functionally to row clicks. Use the api for selection.

**Comment by AbuSufyan** [comment]
Thanks for response, if we set suppressRowClickSelection=true, than row selection is disabled. Can you help me how we write own functionality? because i'm new in angualar js. Any help would be appreciated.
