### ISSUE TITLE
[row model] lazy load child rows in groups

### ISSUE THREAD

**Issue by scotthovestadt** [ceolter/ag-grid#566]
The heavy lifting would of course fall on the data source, but implementing hooks for this would make it possible to implement.

**Comment by ceolter** [comment]
I think you are looking more for a complete end-to-end reporting application rather than a gui grid???!!! Not sure this request fits in what I was aiming for. Any examples or further explanation of what you mean??

**Comment by scotthovestadt** [comment]
Essentially, I want row grouping with a remote data source. Obviously the grid can't do the grouping for me because it won't have all the data due to infinite scrolling. Here is my need:
- Enable mode so all rows passed from remote datasource are considered top-level "groups"
- When a group is expanded, make a second call to remote datasource to fetch rows in group and render them

I actually have a working implementation of this, but it's a bit hacky right now. I'd prefer to have it supported in the grid.

Would you accept a PR?

**Comment by ceolter** [comment]
ah right, i got mixed up with what pivot meant. so basically you want lazy loading of the child groups. yes i'll get that in at some point. i'll rename this issue.

re PR, i probably won't accept a PR on this, as it's core to the workings of the grid, so i'll prob have my own ideas on how this should be done with regards the rest of the grid.

**Comment by ildarnm** [comment]
+1

**Comment by pengx17** [comment]
+1 Really need it in my project.

**Comment by tiberiuzuld** [comment]
+1

**Comment by chaosfoal** [comment]
+1

**Comment by xtreemrage** [comment]
+1

**Comment by squarewave24** [comment]
+1

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-86

**Comment by ceolter** [comment]
this is now done, part of the Enterprise Row Model

**Comment by tomasreichmann** [comment]
Is it possible to turn this off and get the page with groups already expanded using `groupDefaultExpanded: -1 `? This setting doesn't seem to do anything with the server-side model.
