### ISSUE TITLE
Grid with Angular2 b45

### ISSUE THREAD

**Issue by EricSch** [ceolter/ag-grid#567]
Hi, 
I have a similar problem like here http://ag-grid.com/forum/showthread.php?tid=2863
Error: "No Directive annotation found on AgGridNg2"
We aren't using SFX, but System.import

I tried to add the ag.grid.initialiseAgGridWithAngular2(ng2), but we don't have the call to System.import("angular2/angular2"). We are using the bootstraper.

Do you have any hints?

Thanks

**Comment by ceolter** [comment]
Closing as was answered (by Eric!!) on the forum

```
import * as ng2 from 'angular2/angular2';

ag.grid.initialiseAgGridWithAngular2(ng2);
```

**Comment by vladimir-ivanov** [comment]
would perhaps be nice to include this on the documentation page?
