### ISSUE TITLE
[scroll] Page wheel scrolling not available on pinned cols when table does not have a scrollbar

### ISSUE THREAD

**Issue by ychailler** [ceolter/ag-grid#570]
A fix has been applied to enable scrolling on pinned cols to move the scroll on the body part of the table. (https://github.com/ceolter/ag-grid/issues/14)
This prevent the scrolling on pinned columns to work correctly on the page viewport when there is no table scrollbar because the added eventListener intercept the scroll event and manually compute the scrollTop value.

I suggest to change this by forwarding the event to the eBodyViewport:

```
GridPanel.prototype.mouseWheelListener = function (event) {
            var newEvent = new event.constructor(event.type, event);
            this.eBodyViewport.dispatchEvent(newEvent);
                // if we don't prevent default, then the whole browser will scroll also as well as the grid
                event.preventDefault();
                return false;
            };
```

**Comment by ceolter** [comment]
Thanks for raising. Will check when back from holidays.

**Comment by bdwellons** [comment]
@ychailler, the fix works great except for IE. IE fails when calling event.constructor (object doesn't support method). Any fix for that? I've gone through and tried with docs provided on MSDN but no luck.
Thanks

**Comment by buremba** [comment]
+1

**Comment by tsachis** [comment]
+1

**Comment by ceolter** [comment]
i'm confused, the mouse wheel is working or scrolling or me. are people saying the mouse wheel scrolling is not working for IE ?

**Comment by bdwellons** [comment]
It exists on 2.x.x versions.

**Comment by ceolter** [comment]
so it's fixed in latest?

**Comment by ceolter** [comment]
i spent a while looking into this and cant get it to work.

basically i coded up the below in gridPanel.ts (replacing the method of the same name):
```
    private addMouseWheelEventListeners(): void {
        let leftListener = (event: WheelEvent) => {
            var newEvent = new WheelEvent(event.type, event);
            this.eBodyViewport.dispatchEvent(newEvent);
            event.preventDefault();
            return false;
        };
        this.addDestroyableEventListener(this.ePinnedLeftColsViewport, 'mousewheel', leftListener);
    }
```

i expected that the mouse event would be applied to the eBodyViewport. although the event is received (if i add a mousewheel listener to eBodyViewport, it gets called) but it doesn't have any impact on the eBodyViewport, no scrolling happens.

anyone any ideas?

**Comment by ceolter** [comment]
@ychailler the suggested solution does not work. see here:
http://stackoverflow.com/questions/35526092/does-dispatchevent-trigger-default-handler

basically when you do this ```this.eBodyViewport.dispatchEvent(newEvent);``` is it not a trusted event, so the mouse scroll is not processed by the browser.

pity, it seemed like a very elegant solution, but unfortunately doesn't work. closing issues as suggestion doesn't work.
