### ISSUE TITLE
[filter] Invalid SetFilterModel behavior on external data source

### ISSUE THREAD

**Issue by gdaszuta** [ceolter/ag-grid#572]
Hello,

I've stumbled on funny bug - SetFilterModel.setModel() is not setting eGui.eSelectAll() value to indeterminate, thus when SetFilterModel.setModel() is called after data model update, it resets filter by calling SetFilterModel.selectEverything();

I prepared quick and dirty fix, but don't have time to test it properly (works in my use case), if anyone has suggestions how to do it properly, I could prepare proper pull request.

[agGrid-setFilterModel.patch.txt](https://github.com/ceolter/ag-grid/files/37590/agGrid-setFilterModel.patch.txt)

**Comment by ceolter** [comment]
thanks for raising. will fix when back from holidays.

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-89

**Comment by makinggoodsoftware** [comment]
It looks like this has been fixed already, can you please let us know if you are still experiencing the same issue?
