### ISSUE TITLE
PinnedColumnCount row selection

### ISSUE THREAD

**Issue by AbuSufyan** [ceolter/ag-grid#574]
Hi,
This is a very nice grid, thank you so much for your great effort, we used row hover style using
.ag-row:hover {
    background-color: #FFA500;
    cursor: pointer;
}
but this is only worked for other than pinned columns, its work when we have mouse directly on pinned columns but other than pinned columns row have no hove style, is it possible hover style apply on all columns row either pinned or not?
here is plunker :
http://plnkr.co/edit/QDDFND5PrROyKiahyrsu?p=preview

In Internet Explorer version 11 selected row color is break when we use mouse scroll button up down. 
Please select any row from Complex Plain Javascript Example and use mouse scroll button up down you can see the color break in columns.
http://www.ag-grid.com/best-javascript-grid/index.php

**Comment by ceolter** [comment]
thanks for raising. fixing the hover & pinned cols is something i intend fixing when i'm back from holidays.

**Comment by AbuSufyan** [comment]
Any update about this issue?

**Comment by ceolter** [comment]
my holidays only finished today. i'll be looking at everything soon.

**Comment by AbuSufyan** [comment]
Any news here? We really needed this fixed.

Cheers

**Comment by ceolter** [comment]
no update.

**Comment by AbuSufyan** [comment]
Any news here? We really needed this fixed.

Cheers

**Comment by ceolter** [comment]
no update

**Comment by AbuSufyan** [comment]
Any idea when we get this fix?

**Comment by ceolter** [comment]
no. i've lots of people asking me to fix / add things and i'm giving priority to people who are paying me money.

**Comment by AbuSufyan** [comment]
How much you would charge for this fix?

**Comment by ceolter** [comment]
can you ping me an email on accounts@ag-grid.com

thanks :)

**Comment by AbuSufyan** [comment]
Any update on this issue?

**Comment by ceolter** [comment]
this was fixed a few months ago. now ag-row-hover class is added to row when mouse is hovered over it.

**Comment by AbuSufyan** [comment]
If you see the following plnkr. Row hover style is working for both pinned and non pinned columns separately. But whole row must be highlighted either we or moving mouse on pinned columns or non pinned columns.
[http://plnkr.co/edit/QDDFND5PrROyKiahyrsu?p=preview]

**Comment by ceolter** [comment]
now ag-row-hover class is added to row when mouse is hovered over it.

this has nothing to do with the hover style!!! stop trying to use the hover style. use the ag-grow-hover class instead.

see the provided material theme, it makes use of it.
