### ISSUE TITLE
When grouping and setting the group type to row, the Text should span all columns

### ISSUE THREAD

**Issue by killyosaur** [ceolter/ag-grid#575]
Currently if you are grouping (pivoting) rows using a row as a group type, the title of the group/pivot is only as wide as the column directly below it.
![group row a](https://cloud.githubusercontent.com/assets/9081387/11273696/bd1446b6-8ea2-11e5-9df1-db8db36d0058.png)

When the column below is resized to a smaller row.
![group row b](https://cloud.githubusercontent.com/assets/9081387/11273701/c2517cfc-8ea2-11e5-96ed-10d9ed2b61bd.png)

**Comment by killyosaur** [comment]
Should add that this is only an issue with Pinned columns. It spans only the pinned columns and not every column. Not sure how this will get fixed the way pinning is being handled currently, but something to keep in mind if this is getting changed at some point.

**Comment by ceolter** [comment]
correct, this is with pinned columns. the group row has two parts, one for the pinned part, one for the non pinned part. you are also right, with the way pinning is implemented, it is not possible to fix this.

**Comment by jogibear9988** [comment]
when I set the style of ag-group-cell to width:100%, it works, when the "ag-group-cell" dose not have a width set! But I've not searched the Code where I could remove the width...

**Comment by ceolter** [comment]
with the introduction of fullWidth rows, this is now gone.
