### ISSUE TITLE
deselecNode doesn't take suppressEvents parameter

### ISSUE THREAD

**Issue by GustavSt** [ceolter/ag-grid#577]
According to the docs the api function deselectNode is supposed to take a second parameter, suppressEvents, it does not. The other select/deselect api functions have this parameter, only deselectNode that doesn't.

**Comment by GustavSt** [comment]
saw that it was already a pull request for this one, #552

**Comment by senthanal** [comment]
:+1: 
Hi, Yes, suppress events doesn't work at the moment. Fix would be great :) 
Thanks for the awesome grid :)

**Comment by ceolter** [comment]
suppressEvents is no longer supported, stop listening for the event if you no longer want it
