### ISSUE TITLE
[csv export] choose delimiter for CSV export

### ISSUE THREAD

**Issue by vaubrun13** [ceolter/ag-grid#579]
It would be cool to be able to choose the delimiter used to build the csv thanks to the parameters passed to exportDataAsCsv .

**Comment by ceolter** [comment]
noted. thanks.

**Comment by alqu** [comment]
Same here. There are 2 lines involved to implement this.

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-90

**Comment by makinggoodsoftware** [comment]
Hi guys, just going through the docs, I can see that this seems to be implemented already, if you check this page: https://www.ag-grid.com/javascript-grid-export/ you will see that there is an existing param called columnSeparator

Let us know if this satisfies your requirement

**Comment by vaubrun13** [comment]
Indeed i haven't seen it then (or it wasn't existing), anyway it looks satisfying to me

**Comment by vijaysvs80** [comment]
I would like to use TAB as separator. I tried using "/t" or ASCII code. It doesn't work. Any thoughts how this can be done ?
