### ISSUE TITLE
[filtering] Allow set-filters to update it's values after a data change.

### ISSUE THREAD

**Issue by arikanos** [ceolter/ag-grid#58]
Could you please add the behavior, so the checkboxes in set-filters updates when a cell value is edited. Thank you in advance. 

best regards, 

osman

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-41

**Comment by ceolter** [comment]
duplicate of https://github.com/ceolter/ag-grid-enterprise/issues/8
closing
