### ISSUE TITLE
'number' filter does not work

### ISSUE THREAD

**Issue by mparisi76** [ceolter/ag-grid#583]
Hi, I am trying to get the filter to work with numbers. I'm attempting to follow your example, but it does not work either.

http://www.ag-grid.com/angular-grid-filtering/example1.html

When you click on the the Age filter, nothing is shown except the input. Is this a known issue?

Thanks!

**Comment by ceolter** [comment]
No this is not a known issue.

Are you saying the example is broken? The example is working for me.

**Comment by mparisi76** [comment]
Maybe I'm not understanding expected behavior. I've attached a screenshot of what I'm seeing. I would expect that all of the possible ages would be displayed in a checklist.

![screen shot 2015-12-01 at 10 17 48 pm](https://cloud.githubusercontent.com/assets/4642133/11521354/7e8a003a-9879-11e5-8920-ca55a09b95b5.png)

**Comment by ceolter** [comment]
What you see is expected. For a selection set, change the filter type to set, not number.

**Comment by mparisi76** [comment]
The root of my issue is that with a selection set, the items are always sorted as strings. I need to be able to sort them as numbers and dates as well. This is not built in to ag-grid?

**Comment by ceolter** [comment]
Set your own comparator on the colDef. Sort whatever way you wish!!

**Comment by mparisi76** [comment]
Oh great! Any documentation on how to accomplish this?

**Comment by ceolter** [comment]
http://www.ag-grid.com/angular-grid-column-definitions/index.php

Just attach your comparator function to the colDef. You are only concerned with the first two parameters, as nodes are only relevant when sorting the data rows (the filter has values, not rows).

**Comment by mparisi76** [comment]
That will sort the items in the selection set in the filter?

**Comment by ceolter** [comment]
yes (90% sure)

**Comment by we-suman-k001** [comment]
Ag-grid number function is not working as expected for me. I'm trying to get the start and end value for in-range filter but it is only sending the start value like this ``` filter[price][value]: 12 ``` this is my coldef for that number function: 
```javascriptfilter:  ```'agNumberColumnFilter',
                    filterParams: {
                        inRangeInclusive: true,
                        buttons: ['reset'],
                        debounceMs: 1000,
                        maxNumConditions: 1
                    },
```
