### ISSUE TITLE
[web components] Webcomponent: setGridOptions should be gridOptions= because it's a property (not the api)

### ISSUE THREAD

**Issue by milesburton** [ceolter/ag-grid#588]
Working through your WebComponent implementation of Ag-Grid.

component.setGridOptions is a function whilst component.columnDefs (etc) are ES6 setters.

On a similar note, it would be advisable to note on the docs that web components use es6 setters rather than setXYZ.

**Comment by ceolter** [comment]
thanks for raising

```
component.setGridOptions is a function whilst component.columnDefs (etc) are ES6 setters
```
-> what difference does thsi make?

are you just talking about the code style, in that setGridOptions is a function, however the properties are just properties (which i just happen to implement as setters?)

**Comment by milesburton** [comment]
Fairly nuanced. if the function is named setGridOptions, it has to be called envoked as "setGridOptions(value)". If the function is marked as a property then it must be set using "gridOptions = value;"

A minor difference but one I didn't spot until I started digging. I may have mentioned it in my other issue, but I believe there's a combination of functions marked with set and standard functions.

**Comment by ceolter** [comment]
ah right, i understand. i thought setGridOptions was on the api, but it is not. so your right (i think), it should have no 'set' in it's name. (unless in was in the api, but then it's not a web component property)

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-92

**Comment by seanlandsman** [comment]
Done. Please see https://github.com/ceolter/ag-grid-webcomponent and https://github.com/ceolter/ag-grid-webcomponent-example respectively

thanks
