### ISSUE TITLE
[web components] Webcomponent: Subsequent calls to setGridOptions cause duplicate grids

### ISSUE THREAD

**Issue by milesburton** [ceolter/ag-grid#589]
See http://jsfiddle.net/r47mbz0o/2/

I would anticipate a "setGridOptions" would effectively reset the grid (not including listeners)

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-93

**Comment by seanlandsman** [comment]
Done, but repeated setGridOptions will have have no effect. If you wish to reset the grid state you'll need to destroy and re-create the grid
