### ISSUE TITLE
Excel-Style Filtering - Updating Filter Options based on other filters

### ISSUE THREAD

**Issue by bkirk1012** [ceolter/ag-grid#59]
Hello,

I think the filters would be more intuitive to Angular Grid users if they functioned similar to how filtering works in Microsoft Excel.  For instance, if I filter on one particular column in a data set, any additional filters should be limited to display only the filter options available based on the remaining data set from the first filter.

Not sure if this is already on the feature list or not!

**Comment by ceolter** [comment]
Yes this would be good indeed, make the grid more professional. However I would like to have it as an option that's off by default, and can be turned on, as it's might be confusing if your not expecting it.

**Comment by bkirk1012** [comment]
Hi Niall,

Saw that 1.7 includes the Filter API.  I'm thinking the Filter API could be leveraged to support this feature?

Also, separately - do you have an estimated time of completion for Server-Side Filtering/Sorting? That feature would be particularly useful for me! :)

**Comment by ceolter** [comment]
Hi Billy,

Re the filtering, I haven't thought about how such would be implemented.
But my initial guess is it's a bit tricky, even with the new filtering API.
I hadn't intended working on it much in the short to medium term.

Regarding server side filtering, good news, I plan to do it over the coming
week!!

**Comment by nsang92** [comment]
+1

**Comment by ceolter** [comment]
going back over old issues, this was fixed a few weeks ago.
