### ISSUE TITLE
Master Custom Detail Grid - Issue on refresh of parent grid destroys & recreates the detail grid

### ISSUE THREAD

**Issue by melon2504** [ceolter/ag-grid#5909]
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'

**Current behaviour**
I have a parent grid where I perform add/delete/edit row data on button clicks and the data updates if any change (have used client-side applyTransaction)
I also have a column which on expanding displays master detail grid which I'm using the custom detail grid by passing to detailCellRenderer prop of AgGrid
Data for detail grid is fetched via a separate API by passing an ID parameter obtained from parent grid.
Now any update that happens on parent grid as in if row is added/deleted/updated the detail grid refreshes/is recreated completely even though data for detail grid has not changed
I could find that  source of the recreation of detail Grid is when I use getRowId for the parent Grid which is a necessity to refresh the data and identify the rowId (applyTransaction)

**plunkr Link**
Have added a reproducible scenario on plunkr, have used static data provided by AgGrid in the code link since cant add API part but the issue can be replicated on click of refresh
https://plnkr.co/edit/OZuOt9n8ll5PKdM2?open=index.tsx

**Expected behavior**
The issue doesnt occur if I use the default agGrid detailCellRendererParams (https://plnkr.co/edit/sPrZF1kBEiqUvAvI?open=index.tsx) ,  the data is updated for detail grid only for the cell that updates and there's option to provide refreshStrategy='rows'

But I cannot use the above approach of the default detail grid since detailCellRendererParams returns an object and I can't use react hooks (both inbuilt and custom) for fetching the data via WebSockets inside the same

**Please tell us about your environment:**
Windows

* **AG Grid version:** X.X.X
28.2.0

* **Browser:**
Chrom

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
React + TypeScript

**Comment by StephenCooper** [comment]
Hi @melon2504,

We use github issues for bug reports and it is not clear if there is a bug here or a feature request. This looks more like a support question instead of an issue.

It looks like you have an AG Grid Enterprise license so please submit a support ticket:
https://ag-grid.zendesk.com/

If you don't yet have access, or you are having any issues, please contact us at [info@ag-grid.com](mailto:info@ag-grid.com) and we will assist you.
