### ISSUE TITLE
grid is broken in version angular 2 - 2.0.0-alpha-52

### ISSUE THREAD

**Issue by vladimir-ivanov** [ceolter/ag-grid#593]
the grid is not rendering anymore in angular2.
The reason for that is that AgGridNg2.prototype.onInit() 
AgGridNg2.prototype.onChanged() 
AgGridNg2.prototype.onDestroy() 
methods don't exist anymore

need to be replaced with 
AgGridNg2.prototype.ngOnInit()
AgGridNg2.prototype.ngOnChanged() 
AgGridNg2.prototype.ngOnDestroy() 

Please re implement or if you prefer can raise a pull request?

Also the inputs mechanism is broken (assuming the above is fixed) -
should work with  (TypeScript example):

 @Input('column-defs') columnDefs: string;
 @Input('data-rows') dataRows: string;

Thank you

**Comment by vladimir-ivanov** [comment]
ok, seems bea-0 is out:
https://github.com/angular/angular/blob/master/modules/angular2/docs/migration/kebab-case.md
https://github.com/angular/angular/blob/master/CHANGELOG.md#200-alpha52-2015-12-10

**Comment by ronzeidman** [comment]
Got it to work!
[agGridNg2.zip](https://github.com/ceolter/ag-grid/files/72205/agGridNg2.zip)
With this you can work with the beta.
Add this to your webapp and use the bower version of ag-grid:
`bower install ag-grid`
`tsd link'
and add this to the index.html after the angular import:
```html
<script src="/bower_components/ag-grid/dist/ag-grid.js"></script>
```
Then just import and use!
Enjoy

**Comment by vladimir-ivanov** [comment]
great, thank you

Would be nice to have drag and drop to reorder the columns within the table itself. 
I did that by extending AgGridRenderHeaderCell
something around this (covers single columns e.g. no grouping in columns) lines:

https://gist.github.com/vladimir-ivanov/6f8c7a06d6bd2145293a <https://gist.github.com/vladimir-ivanov/6f8c7a06d6bd2145293a>

At the moment we are using the above, but would prefer to have it incorporated within the code. Also extending the typescript file is rather nasty as it manipulates private methods and properties.

Let me know your thoughts. 
Shout if you need help.

Thank you

Kind Regards


Vladimir

**Comment by ewyuen** [comment]
Do you have a full example sources to get this to work?

**Comment by vladimir-ivanov** [comment]
I made it work by adding this after the ag grid js file include

e.g. 
<script src=“ag-grid.js <https://gist.github.com/vladimir-ivanov/6f8c7a06d6bd2145293a#file-ag-grid-render-header-cell-js>"></script>
<script src=“ag-grid-render-header-cell.js <https://gist.github.com/vladimir-ivanov/6f8c7a06d6bd2145293a#file-ag-grid-render-header-cell-js>"></script>

the difference is in https://github.com/ceolter/ag-grid/blob/0fa265e8f876c4a99683d14839f3c3ab40f90ff5/src/ts/headerRendering/renderedHeaderCell.ts <https://github.com/ceolter/ag-grid/blob/0fa265e8f876c4a99683d14839f3c3ab40f90ff5/src/ts/headerRendering/renderedHeaderCell.ts>

inside private setupComponents() method, added this code  e.g. line 160 (after this.addMenu() -> self = this))


            if (self.gridOptionsWrapper.gridOptions.enableColReorder) { //TODO - find the best place for this
                headerCellLabel.setAttribute('draggable', 'true');
                headerCellLabel.addEventListener('dragstart', ev => sourceColumn = self.column);

                headerCellLabel.addEventListener('drop', ev => {
                    ev.preventDefault();

                    let columns = self.gridOptionsWrapper.gridOptions.columnDefs;

//try to do the same with setState()?
                    self.gridOptionsWrapper.gridOptions.columnApi.getState().forEach((item, key) => columns[key].width = item.width);
                    self.gridOptionsWrapper.gridOptions.api.setColumnDefs(move(columns, sourceColumn.index, self.column.index));
                });

                headerCellLabel.addEventListener('dragover', ev => ev.preventDefault());
            }

It only deals with header cells but not with grouped cells.


Thanks


Regards


Vladimir

**Comment by kjensenportfolio** [comment]
Thanks for the help with the  beta update! I have added the onInit, onChange, onDestroy in the ag-grid.js file , but now I am wondering, where do we insert the code below into, I didn't quote catch where that needs to be inserted

@Input('column-defs') columnDefs: string;
@Input('data-rows') dataRows: string;

**Comment by ceolter** [comment]
the latest in git works with angular 2 beta 0. i just haven't done a release yet. it will be in the next release.

**Comment by ceolter** [comment]
i've just released. the latest works with angular 2 beta 0.
