### ISSUE TITLE
CellRender method not sending through parameter data

### ISSUE THREAD

**Issue by MrBrits** [ceolter/ag-grid#594]
So I have an anchor in a cell and when the click on it it should take them to another page.
I got it to fire on the ng-click, but it is not sending any data through.
angularCompileRows is set to true

```javascript
function testCellRenderer(data){
            data.$scope = $scope;//Had to add the main scope to the row's scope because it was null
            return '<a class="pointer" ng-click="editTest(data.data)">'+data.value+'</a>';
}

$scope.editTest(data){
        //'data' is coming through as undefined
}
```

So the data.value is displaying correct and the method editTest is being called, yet no data is coming through.

Am I missing something?

**Comment by MrBrits** [comment]
Ok I have found the problem, but ran into some other problems as well.

I changed this line
```javascript
return '<a class="pointer" ng-click="editTest(data.data)">'+data.value+'</a>';
```
To this:
```javascript
return '<a class="pointer" ng-click="editTest(' + data.data + ')">'+data.value+'</a>';
```
But now it was moaning about the syntax which is incorrect because data.data is an Object.
So if I send through data.data.valueOne, data.data.valueTwo, etc. it works, but only if I am sending through numbers for some reason. As soon as I send through a number and a name it breaks.

Very odd that I can't send through an object. Will try and figure out what is going on.

**Comment by ceolter** [comment]
the above code snippets look fine. it depends on what your data is as to why it's not working i think.

if you want help further, then can i suggest you recreate the problem in a plunker? without having a working example to troubleshoot, there is not much more i can do.

ps i'm closing the issue, as i want to keep issues for items wrong with the grid. for help on using the grid, the forum is the preferred location.
