### ISSUE TITLE
Strings seen as numbers in excel

### ISSUE THREAD

**Issue by mparisi76** [ceolter/ag-grid#595]
Hi, I'm running across an issue where I have a data set which I'm calling the ag-grid API to download a csv file, however, when I have strings such as "00412641447947383461", excel converts them to numbers and ends up showing 4.12644E +17. Does ag-grid have a way to specify a custom separator character?

**Comment by ceolter** [comment]
```
Does ag-grid have a way to specify a custom separator character?
```
right now, no it doesn't.

**Comment by ceolter** [comment]
latest version has export to Excel supported, so should be able to use this.
