### ISSUE TITLE
Columns not auto-sizing on page load

### ISSUE THREAD

**Issue by twcus** [ceolter/ag-grid#596]
I am working on a web app using Angular 1.4 and ag-grid 3.0.7 to get data from a backend using a REST API and display it in a grid. The data is periodically updated using Angular's [Interval](https://docs.angularjs.org/api/ng/service/$interval) service. I have defined an update() function that makes a GET request to the API to retrieve the data. I call this function when the page is first loaded, and then continue to call it using the interval service at a set interval (currently every 5 seconds).

I would like the visible columns to resize to fit the screen automatically when the grid is created. To do this, I am trying to use ag-grid's sizeColumnsToFit() function. I call this function in the update() function right after the GET request is made. However, the grid columns do not resize when the page is first loaded. They only resize once the update() function is called by the interval service 5 seconds later.

```
// Pull the data with GET request and resize columns
function update() {
	dataService.getData().$promise
	.then(function(response) {
		$scope.gridOptions.api.setRowData(response);
		$scope.gridOptions.api.sizeColumnsToFit();
	})
	.catch(function(response) {
		// TODO: handle error
	})
};

// Pull the data initially and then periodically afterwards
update();
$interval(update, dataService.POLL_INTERVAL);
```

How can I go about resizing the columns to fit the screen immediately after the data is retrieved and the grid is created?

**Comment by ceolter** [comment]
the problem is probably your grid is not displayed on the screen when you are calling sizeColunnsToFit for the first time. this is a common problem. because it's not visible, the grid does not know what width it is, so can't work out the column sizes.

to get around this, put your sizeColumnsToFit call into a timeout.

**Comment by rjborba** [comment]
I really do not think that this thread should be closed. 2020 and we're still missing sizeColsToFit automatically.
