### ISSUE TITLE
Need to somehow trigger event of a custom rendered cell

### ISSUE THREAD

**Issue by jsalles** [ceolter/ag-grid#599]
I have a custom rendered cell that implements a javascript class with a custom input.
This javascript class listens to the 'click' event to start editing.

I want to somehow trigger the 'click' event of that class when I press ENTER with the cell selected
Is this possible?

Thanks in advance

**Comment by jsalles** [comment]
I found a way to do this by subscribing to the eventService.
The problem is that this customRenderer is called several times and instantiates the same javascript input for different cells.
So inside my customRenderer, I have to subscribe to an event that is a concatenation of the rowIndex and the colDef.field fields, so only the event for this cell will be called.

var eventName = params.rowIndex.toString() + '-' + params.colDef.field;
params.api.eventService.addEventListener(eventName, function (params) { alert(eventName); });

Is there a better way of doing it? This doesn't look very pretty to me....

**Comment by ceolter** [comment]
The renderer params has eGridCell. This is the cell div that you should be adding your listeners onto.

Actually it's a virtual element (part of my home backed virtual dom) but that doesn't matter, it has an addEventListener method that you can call, that will add the listener to the div when it is rendered.
