### ISSUE TITLE
[FEAT] Reorder columns

### ISSUE THREAD

**Issue by amcdnl** [ceolter/ag-grid#6]
Column re-ordering would be a nice feature, you already have resizing.

**Comment by ceolter** [comment]
Agreed, will put in at some point. Thinking a popup with two lists for now,
with 'add' / 'remove' columns as well re-ordering. Then dragging columns
would be a nice 'show off' feature.

On 8 March 2015 at 02:23, Austin <notifications@github.com> wrote:

> Column re-ordering would be a nice feature, you already have resizing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/angular-grid/issues/6>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by cnd5041** [comment]
Just wanted to second the request for the column re-ordering / dragging re-order. 
Haven't implemented yet but looks awesome, thanks for making it!

**Comment by ceolter** [comment]
Thanks cnd5041 for your input, it's deffo on my 'to do' list . . . . just finishing 'checkbox selection' at the mo, next on my list is 'cell selection and keyboard navigation'.

**Comment by brianfeister** [comment]
+1 for this... was thinking the same

**Comment by vikasmur** [comment]
I want to use the column reordering feauture using drag drop in my app.
Could you please let us know the request's status / priority. 
Thanks in advance.

**Comment by ceolter** [comment]
status: not started. priority: medium. estimate: two or three months from now.

**Comment by sbowler** [comment]
Any updated time frame on this?

**Comment by victordelacruz** [comment]
+1 on column reordering!

**Comment by ceolter** [comment]
you can reorder using the toolpanel

**Comment by victordelacruz** [comment]
Excellent, just tried the new Test Drive! :)

**Comment by killyosaur** [comment]
+1 on draggable Reorder of columns (not having to use the toolpanel).

**Comment by ceolter** [comment]
+1 . . . on my list

**Comment by mikeerickson** [comment]
+1

**Comment by scotthovestadt** [comment]
+1

**Comment by victordelacruz** [comment]
+1

**Comment by matatron** [comment]
+1

**Comment by jasdeepsingh** [comment]
+1

**Comment by epernice** [comment]
+1

**Comment by lucaalex87** [comment]
Guys, you have custom header renderer, you can implement drag&drop there, and call gridOptions.columnApi.moveColumn(fromIndex, toIndex) on ondragover. 

I'm working on something like this just now. But it's with angularCompileHeaders: true also.

**Comment by lucaalex87** [comment]
Here you go, a simple example: (w is instead of $scope here):
I needed angular compile headers because I'm accessing angular data. (gridOptions). You may want to remove that if you're not using angular.

```javascript
    var columnDefs = [
        {headerName: "Make", field: "make"},
        {headerName: "Model", field: "model"},
        {headerName: "Price", field: "price"}
    ];

    var rowData = [
        {make: "Toyota", model: "Celica", price: 35000},
        {make: "Ford", model: "Mondeo", price: 32000},
        {make: "Porsche", model: "Boxter", price: 72000}
    ];

    w.gridOptions = {
        columnDefs: columnDefs,
        rowData: rowData,
        angularCompileHeaders: true,
        headerCellRenderer: headerCellRendererFunc
    };


    function headerCellRendererFunc(params) {

        var eHeader = document.createElement('div');
        eHeader.setAttribute('draggable', true);

        eHeader.addEventListener('dragstart', function (event) {
            var sourceIndex = w.gridOptions.columnDefs.indexOf(params.colDef);
            event.dataTransfer.setData("fromIndex", sourceIndex);
        });

        eHeader.addEventListener('dragover',function (event) {
            event.preventDefault();
            event.target.style.color = 'blue';
        });

        eHeader.addEventListener('dragleave',function (event) {
            event.preventDefault();
            event.target.style.color = '';
        });


        eHeader.addEventListener('drop', function (event) {
            var toIndex = w.gridOptions.columnDefs.indexOf(params.colDef);
            event.preventDefault();
            var fromIndex = event.dataTransfer.getData("fromIndex");
            w.gridOptions.columnApi.moveColumn(fromIndex, toIndex);
            //console.log('fromIndex: '+fromIndex);
            //console.log('toIndex: '+toIndex);
        });

        var eTitle = document.createTextNode(' ' + params.colDef.headerName + ' ');
        eHeader.appendChild(eTitle);

        return eHeader;
    }
```

**Comment by liratanak** [comment]
+1 
Thanks @lucaalex87, really nice example

**Comment by andrea-bologna** [comment]
+1 is there any estimation about that?

**Comment by ceolter** [comment]
dragging column headers will be in in the next week or two. it's the next 'big ticket' item i'll be doing.

**Comment by Wykks** [comment]
Works great with the lastest version, thanks !
Can you add an option/api to disable/enable this manually ?

**Comment by nsteenbeek** [comment]
@Wykks
Is possible on:
Grid level: suppressMovableColumns (https://www.ag-grid.com/javascript-grid-properties/index.php)
Column level: suppressMovable: true

**Comment by Wykks** [comment]
Whoa I missed that. Thanks ! :)

**Comment by ceolter** [comment]
closing this issue, complete :)

**Comment by nsteenbeek** [comment]
I found an issue.
Using ag-grid.min.noStyle.js: dragging column moves only the header and not the whole column.
Using ag-grid.min.js: dragging column moves whole column (expected)

**Comment by ceolter** [comment]
that's really strange, the only difference is 'noStyle' doesn't contain the css.

are you including the css yourself directly then?

**Comment by ceolter** [comment]
@nsteenbeek i've just tested, it works fine for me

**Comment by nsteenbeek** [comment]
@ceolter My fault! Forgot to update the ag-grid.css. That's why the version including styles worked. Thumbs up for ag-grid!

**Comment by chenokn** [comment]
> Thanks cnd5041 for your input, it's deffo on my 'to do' list . . . . just finishing 'checkbox selection' at the mo, next on my list is 'cell selection and keyboard navigation'.

For keyboard accessibility.
Column re-ordering would be a nice feature with keyboard.

**Comment by AG-Zoheil** [comment]
Thank you for your comment @chenokn.

You'll be pleased to know that we are looking to add this functionality with our next `v31` release. I have added the backlog item reference to this Github issues for your reference.
