### ISSUE TITLE
Group Rows Collapsed and scroll move to top  once data updated

### ISSUE THREAD

**Issue by arulganapathy** [ceolter/ag-grid#600]
Hi,
Im using ag-grid for live data which was reflected in every 10 sec time interva.I have grouped row based on some field.While updating the data(i have used setRowData for data update) grouped rows again collapse together. If user expand the row means he cant see the inner rows more then 10 sec it again collapsed in next data update(10 sec). 

Is Any possible way to maintain the state of group rows(expand/collapse) even after data update(setRowData)

Both SoftRefresh and RefreshView not working out for me.

**Comment by ceolter** [comment]
answered here:
http://www.ag-grid.com/forum/showthread.php?tid=3056&highlight=onGroupExpandedOrCollapsed

**Comment by davidalee** [comment]
I have the same question but the link posted in the answer is no longer valid. Can you provide an answer in this thread for posterity?

Thanks!

**Comment by davidalee** [comment]
For anyone who comes across this question, the answer can be found here: https://www.ag-grid.com/javascript-grid-grouping/#keeping-group-state

**Comment by valceaalexandra** [comment]
I have the same problem in 2020. Just added the last version and when i edit a cell the group will collapse and the grid will scroll to the top. I didnt find anything in the docs about that. 
@davidalee can you tell me what is the solution?

**Comment by davidalee** [comment]
@valceaalexandra Try taking a look at this archived version of that link I posted back in 2018, and search for "Keeping group state": http://web.archive.org/web/20181107104535/https://www.ag-grid.com/javascript-grid-grouping/

**Comment by arulganapathy** [comment]
@valceaalexandra I have used mentioned code snippet achieve same

var oldState = [];
        $scope.gridOptionsToday.api.forEachNode(function (node) {
            if (node.group && node.expanded) {//if the node is a group and is open push it to the oldstate var                    
                oldState.push(node.key);
            }
        });
        **$scope.gridOptionsToday.api.setRowData(data)**;
        $scope.gridOptionsToday.api.forEachNode(function (node) {
            if (node.group && oldState.indexOf(node.key) != -1) {
                node.expanded = true;
            }
        });
        $scope.gridOptionsToday.api.onGroupExpandedOrCollapsed(0);
        $scope.gridOptionsToday.api.refreshView();

**Comment by valceaalexandra** [comment]
> @valceaalexandra Try taking a look at this archived version of that link I posted back in 2018, and search for "Keeping group state": http://web.archive.org/web/20181107104535/https://www.ag-grid.com/javascript-grid-grouping/
> 
> Though it may or may not work depending on which version of ag-grid you're using. If you're using a more updated version of ag-grid which I imagine you are, you may have to look for a more current solution.

Thank you so much! Now the group keeps the same state, but the grid will scroll to the top. Do you have the same problem?

**Comment by arulganapathy** [comment]
I have done workaround for that. By setting previous scroll position
**var oldScrollPosition = $('.ag-body-viewport').scrollTop();**
var oldState = [];
$scope.gridOptionsToday.api.forEachNode(function (node) {
if (node.group && node.expanded) {//if the node is a group and is open push it to the oldstate var
oldState.push(node.key);
}
});
$scope.gridOptionsToday.api.setRowData(data);
$scope.gridOptionsToday.api.forEachNode(function (node) {
if (node.group && oldState.indexOf(node.key) != -1) {
node.expanded = true;
}
});
$scope.gridOptionsToday.api.onGroupExpandedOrCollapsed(0);
$scope.gridOptionsToday.api.refreshView();
**$('.ag-body-viewport').scrollTop(oldScrollPosition);**

**Comment by valceaalexandra** [comment]
Thank you so much but I found this :deltaRowDataMode="true" and it works perfect for me

**Comment by squarewave24** [comment]
it is unclear what solution is in the links people are posting, but i came across this? 

`rememberGroupStateWhenNewData=true`

which doesn't work for me.. the grid still gets collapsed after each refresh

**Comment by LalanaChami** [comment]
Setting below grid options to true helped me fix this issue. 

rememberGroupStateWhenNewData: true,
suppressScrollOnNewData: true,

**Comment by Popa-Andrei-Valentin** [comment]
> Setting below grid options to true helped me fix this issue.
> 
> rememberGroupStateWhenNewData: true, suppressScrollOnNewData: true,

this still works, thank you very much ! ( ag-grid-vue )
