### ISSUE TITLE
$scope.gridOptions.api.SelectIndex doesn't work with datasource

### ISSUE THREAD

**Issue by pacificeyes** [ceolter/ag-grid#601]
I'm using the server side pagination and filtering example.
On loading the data in grid, I would like to programmatically set the first row.
However below method does not work if the grid data has been set using data source.
$scope.gridOptions.api.SelectIndex doesn't work with datasource

**Comment by pacificeyes** [comment]
below hack did the trick. I'm not sure if it's an optimal solution or not:              
function createNewDatasource() {
        if (!allOfTheData) {
            // in case user selected 'onPageSizeChanged()' before the json was loaded
            return;
        }

        var dataSource = {
            //rowCount: ???, - not setting the row count, infinite paging will be used
            pageSize: parseInt($scope.pageSize), // changing to number, as scope keeps it as a string
            getRows: function (params) {
                // this code should contact the server for rows. however for the purposes of the demo,
                // the data is generated locally, a timer is used to give the experience of
                // an asynchronous call
                console.log('asking for ' + params.startRow + ' to ' + params.endRow);
                setTimeout(function () {
                    // take a chunk of the array, matching the start and finish times
                    //var rowsThisPage = allOfTheData.slice(params.startRow, params.endRow);
                    var dataAfterSortingAndFiltering = sortAndFilter(params.sortModel, params.filterModel);
                    var rowsThisPage = dataAfterSortingAndFiltering.slice(params.startRow, params.endRow);                    // see if we have come to the last page. if we have, set lastRow to
                    // the very last row of the last page. if you are getting data from
                    // a server, lastRow could be returned separately if the lastRow
                    // is not in the current page.
                    var lastRow = -1;
                    if (dataAfterSortingAndFiltering.length <= params.endRow) {
                        lastRow = dataAfterSortingAndFiltering.length;
                    }
                    params.successCallback(rowsThisPage, lastRow);
                    **//This is the hack**
                    **params.rowData = rowsThisPage; **
                    **$scope.gridOptions.api.selectIndex(0, false, false);**
                }, 500);
            }
        };

        $scope.gridOptions.api.setDatasource(dataSource);
    }

**Comment by ceolter** [comment]
```
$scope.gridOptions.api.SelectIndex doesn't work with datasource
```
i just test this, it does work.

i tested using this virtual pagination example online and selected the first index after the first page was loaded.

ps am closing this issue. if still an problem for you, can you reproduce in a plunker? then raise it on the forum? (the issues should be for when items are broken in the grid)
