### ISSUE TITLE
Server side sorting, I always get the same sortModel

### ISSUE THREAD

**Issue by jmdagenais** [ceolter/ag-grid#602]
I have a gridOptions with enableServerSideSorting: true.

In the parameter of the "getRows" function of my datasource the params.sortModel[0].sort has always the value 'asc'. Even if I click multiple time on the same column header.

**Comment by ceolter** [comment]
i can't reproduce this here.
http://localhost/angular-grid-pagination/pagingServerSide.html

i debugged thought the code, and when no sort is applied, the sortModel array is empty.

so i'm guessing something is wrong with your code?
