### ISSUE TITLE
add support for right-to-left langauges

### ISSUE THREAD

**Issue by bsagal** [ceolter/ag-grid#610]
I tried to use this grid in a page with `direction: rtl` and the headers do not align properly.

Lack of support for right to left causes the scrollbar to be on the opposite side to what is expected for a rtl language page

**Comment by rubinsh** [comment]
+1

**Comment by golan4ik** [comment]
+1

**Comment by ceolter** [comment]
noted.

**Comment by golan4ik** [comment]
For any project that requires rtl support it`s a real suffer. CSS not helping alot because of horizontal scrolling and header.
if no horizontal scrolling required it`s simple enough to fix.

**Comment by MehdiSaeedifar** [comment]
+1

**Comment by RefactorMan** [comment]
+1

**Comment by TheCodeCleaner** [comment]
+1

**Comment by aviram26** [comment]
+1

**Comment by RefactorMan** [comment]
Tried css tricks but nothing works.. There alot of issues.  Resize columns by drag or double click,  columns movement by drag, columns position...

**Comment by TheCodeCleaner** [comment]
@golan4ik how can you fix it if no horizontal scrolling required?

**Comment by aviram26** [comment]
I played a little and was able to solve some of the problems, but it's to hacky... 
A lot of absolute positioning with "left" - need to change them to "right", floating stuff, etc... 
And this procedure needs to be triggered all the time - too high overhead.
The correct solution is to have a property in the option + API to handle this

**Comment by MehdiSaeedifar** [comment]
any progress?

**Comment by ceolter** [comment]
we haven't started working on it in ag-Grid. it is on the list though and pretty high priority.

**Comment by adamkleingit** [comment]
Can we get an estimated ETA on this?
Thanks

**Comment by adamkleingit** [comment]
Did anyone solve this via CSS or other solution?

**Comment by TamarAmit** [comment]
+1
This is a really important requirement for RTL interfaces. 
Can you please provide any estimation for this?

**Comment by lior035** [comment]
+1 
I know about many enterprise companies that the RTL support is a mandatory requirement.
Your library is really impressive and rich with features, please let us know if and when you are planning on adding rtl support?

Thank you.

**Comment by mkeidar** [comment]
+1

**Comment by inbaldoron** [comment]
+1

**Comment by Okle** [comment]
+1

**Comment by tamiro44** [comment]
+1

**Comment by ceolter** [comment]
will be starting this next week.

**Comment by OmriPeretz** [comment]
+1

**Comment by ceolter** [comment]
working on it, no more +1's needed!!!!!!

**Comment by ceolter** [comment]
getting there, it's no way finished, just wanted to post this img so you can see i am actually working on it!!

![image](https://cloud.githubusercontent.com/assets/6539563/20897321/ceb3c334-bb19-11e6-81ed-f9712a34b271.png)

**Comment by MehdiSaeedifar** [comment]
@ceolter 

Thanks a lot for adding rtl feature in the latest version.

**Comment by ahmedelbatal** [comment]
@ceolter 
Thank you very much for this great effort, well done.
I want to ask if you can keep the vertical scroll on the right hand side. Much better UX as most people are right-handed, even with right-to-left languages.

**Comment by MehdiSaeedifar** [comment]
@ahmedelbatal 

Yes, I'm also think vertical scroll on the right hand side is more common and handy.

**Comment by Tokyros** [comment]
Anybody getting problems with columns resizing with enableRtl=true?
It looks like the location of the resize handle is not getting inverted

**Comment by ceolter** [comment]
@aelbatal i don't set the scrollbar onto the left,  it is the browser that is doing this. if i was to keep the panels LTR but the contents RTL, which would be very confusing for me to program (can of worms with all the scrolls in the system) so i'd rather keep it simple. if i was to introduce such complexity in to the grid, i'd rather put this complexity towards solving something else.

**Comment by aelbatal** [comment]
@ceolter I understand. hope you find the time to do all the enhancement things like that. but please keep it on the list. and thanks for the great useful tool.

**Comment by MhosenBiglari** [comment]
I solved it : [link](https://stackoverflow.com/questions/53921749/ag-grid-headers-move-to-the-opposite-direction-upon-horizontal-scroll/56027707#56027707)
