### ISSUE TITLE
groupUseEntireRow causing aggregations to disappear

### ISSUE THREAD

**Issue by ImranAhmed** [ceolter/ag-grid#611]
Hi,

I've got a problem with the groupUseEntireRow and row level aggregation. In the below two examples the code is the same except in the second example I have set groupUseEntireRow to True. This seems to be working fine but notice how I've lost my aggregations? Any help, appreciated. I am using ag-grid v2.3.5.

Example 1
![test_1](https://cloud.githubusercontent.com/assets/2539520/11978035/28f8c3dc-a980-11e5-9e21-c0ba4dfb51b4.png)

Example 2
![test_2](https://cloud.githubusercontent.com/assets/2539520/11978036/2c77feb0-a980-11e5-9741-3668e39b8f0d.png)

     this.categoryGrid =  {
                columnDefs: columnDefs,
                rowData: gridData,
                groupUseEntireRow: true,  // set to false in Example 1
                groupKeys: ["Group", "Currency", "Country"],
                groupAggFunction: this.groupAggFunction

            };

     private groupAggFunction(nodes:any) {

            var sums = {};

            var test = 'Test';
                sums[test]=15;
            return sums;
        }

In both examples my column definitions are as follows:

![columndefs](https://cloud.githubusercontent.com/assets/2539520/11978113/eee51712-a980-11e5-9036-0bc470565551.png)

**Comment by ceolter** [comment]
when you use 'groupUseEntireRow' then then columns don't get rendered for the group row.

if you want to show your aggregate data, do one of the following:
1) do NOT use groupUseEntireRow
2) provide your own groupRowInnerRenderer (see here http://www.ag-grid.com/angular-grid-grouping/index.php)

**Comment by ImranAhmed** [comment]
Hi Niall,

Thanks for the response. I am taking a look at the example for groupRowInnerRenderer. What if I don't want to render my own row data outside their column structure but instead just want the totals to appear in their respective columns - see attached. My grid has a fair few columns and it doesn't make sense to render the data outside the column for each summary row however we do want to drop the superfluous 'Description' column shown in example 1 above.

![18-12-2015 15-21-58](https://cloud.githubusercontent.com/assets/2539520/12111928/0fd73b70-b391-11e5-81c2-d4c46e37993a.png)

**Comment by ceolter** [comment]
then you are describing the default behaviour? which is groupUseEntireRow=false (or leave this property out)

if there is no data, then the cell will be blank (for non aggregated columns)

if you want to display data under the right columns, then why do you want to groupUseEntireRow??

**Comment by ImranAhmed** [comment]
Hi Niall,

Thanks for the prompt reply. Yes, I am looking for the default behavior however if you see the attached.

https://cloud.githubusercontent.com/assets/2539520/11978035/28f8c3dc-a980-11e5-9e21-c0ba4dfb51b4.png

The Description column here is unnecessary. I just want to remove the Description column and push its data into Column A so I have a proper tree structure. The groupUseEntireRow property achieved this easily but as you point out it removes the aggregated data for the summary rows also.

**Comment by ceolter** [comment]
```
The groupUseEntireRow property achieved this
```
--> no it doesn't, this property groupUseEntireRow doesn't remove columns

if you don't want a column to appear then:
1) you can hide it (colDef.hide=true), you can still pivot by the hidden column
2) you can groupHidePivotColumns=true, this will remove the columns you pivot by, hence removing teh duplication

**Comment by ImranAhmed** [comment]
ok, thanks for your time. Maybe I missed something:

Here is my plunkr: http://plnkr.co/6WoFdE

Requirements are:

1. Hide column: currency.

2. Data for column 'currency' ie. EUR/GBP/USD should appear in the Category column under node Test (3).

3. The column 'value' should display all the data it currently displays. 

The end result should look like this:

![group_props](https://cloud.githubusercontent.com/assets/2539520/12119916/5f09a3b0-b3c6-11e5-9c1f-b03c73aea1be.png)

**Comment by ceolter** [comment]
like this:
http://plnkr.co/edit/bujo8Z?p=preview

i changed the field of the group col here:
```
                groupColumnDef: {
                    headerName: 'Category',
                    field: 'Currency',
                    cellRenderer: {
                        renderer: 'group'
                    }
                },
```

and i also removed the value column as you didn't want it.

**Comment by ImranAhmed** [comment]
Perfect, thanks!

**Comment by SonicReal** [comment]
Hello from 2020, how can i do the same thing?
![asdsdasdsd](https://user-images.githubusercontent.com/22213630/97706165-0939b600-1ad7-11eb-844f-8bea0a2750d2.PNG)
