### ISSUE TITLE
No rows visible when using node 5.1.0.0 

### ISSUE THREAD

**Issue by geoffreywk** [ceolter/ag-grid#612]
So I'm using node and I can see the data is returning correctly to the client and I can view the HTML in the development tools and see the rows are there, but they aren't showing on the screen for some reason. I've attached my sample code, it's using a trimmed down version of the JSON file from the docs.  
[SampleagGridNode.zip](https://github.com/ceolter/ag-grid/files/70876/SampleagGridNode.zip)

I don't think this is a node issue as I changed to using node 4.2.3 and still experiencing same issue.

Am I missing something simple here?
Thanks

**Comment by ceolter** [comment]
You have set the height to 100% without setting a height for the parent div.

This is nothing to do with the grid, but how you are using css. If you are using % height, then you need to be careful to set the height in the containing div also.

Please set the height in pixels first (eg to 500px) on your grid, to see if that fixes it. Then you can play with the % on your page to get that working also.
