### ISSUE TITLE
Select and Deselecting Bug

### ISSUE THREAD

**Issue by dvrakas** [ceolter/ag-grid#613]
When selected all row (or rows based on status) everything works fine. But when deselecting the selected rows, the last row is left selected. Simple code below. DeselectAll() will also leave the last element selected 
```javascript
if (status === "All") {
                vm.gridApi.forEachNode(function (node) {
                   
                        vm.gridApi.selectNode(node, true);

                });
               
            }
            if (status === "Deselect") {
                vm.gridApi.forEachNode(function (node) {

                                   
                        vm.gridApi.selectNode(node, false);
                   
                });
                
            }
```

**Comment by ceolter** [comment]
To deselect nodes, use the deselectNode API, et:
```
            gridOptions.api.deselectNode(node);
```
The second parameter for selectNode is whether you want to support multi selection or not.

So the grid is working, you are just not using the right API.
