### ISSUE TITLE
size to fit not resizing columns on Grid Ready

### ISSUE THREAD

**Issue by killyosaur** [ceolter/ag-grid#620]
This may be a bug, this may not, I saw the earlier one where the guy was trying to resize on page load and your statement is he needed to wait for the grid. I set my call to this function in the onready event (which I presume to mean that the grid is displaying at the time of its call) even attempted to use a timeout, it doesn't seem to resize the columns at all. Now the restore state works fine in this situation, no issues with that displaying as soon as the grid is ready, but if I don't have a state to restore, I'd like my columns to resize. The big question is, does putting a width in the column definitions prohibit this function from working? is that possibly why I am not seeing a resize as I thought it worked even with the columns marked with a width?

**Comment by ceolter** [comment]
```
does putting a width in the column definitions prohibit this function from working
```
-> no, the sizeToFit works with the widths. this is nice, as you can have a 'best guess' as the provided widths, then calling the function will spread the extra space evenly, so somehow keeping the relative widths.

i can't suggest why it's not working for you. as you point out, the biggest problem with this for other people is the grid is not visible at the time of calling. what you could do is debug through the code - at one point the code gets the grids width - this comes back as zero if the grid is not visible. you can see if this is happening for you. if not, and still broken, then for me to help further i'd need to see it recreated in a plunker.
