### ISSUE TITLE
Using ngUpgrade adapter to bootstrap angular1 app breaks the grid if virtual repeat rows are present

### ISSUE THREAD

**Issue by vladimir-ivanov** [ceolter/ag-grid#621]
steps to reproduce:
in our angular1 app

import "reflect-metadata";
import {UpgradeAdapter} from "angular2/upgrade";

const adapter = new UpgradeAdapter();
adapter.bootstrap(document, ["eos"]);

to replace
    angular.element(document).ready(function() {
        angular.bootstrap(document, ['eos']);
    });

breaks without touching ag-grid itself (also tried to use the generic new ag.grid.Grid(...)) - same issue persists (investigating the source code, no immediately obvious reason)
Inclined to believe it is an issue with angular and ngUpgrade, could not find anything in ag-grid, investigating further.
May close this issue soon

**Comment by ceolter** [comment]
Thanks for closing.  :)

**Comment by vladimir-ivanov** [comment]
From the documentation: 

* When reasoning about how a hybrid application works it is useful to have a mental model which
 * describes what is happening and explains what is happening at the lowest level.
 *
 * 1. There are two independent frameworks running in a single application, each framework treats
 *    the other as a black box.
 * 2. Each DOM element on the page is owned exactly by one framework. Whichever framework
 *    instantiated the element is the owner. Each framework only updates/interacts with its own
 *    DOM elements and ignores others.
 * 3. AngularJS v1 directives always execute inside AngularJS v1 framework codebase regardless of
 *    where they are instantiated.
 * 4. Angular v2 components always execute inside Angular v2 framework codebase regardless of
 *    where they are instantiated....

Not very impressed with the adapter, running two apps slows down things and makes slow angular1 pages to perform much worse - zone.js triggers a lot more digest cycles than necessary on change :-( - dramatic performance hit.
