### ISSUE TITLE
No responsive Columns width

### ISSUE THREAD

**Issue by gabrielenosso** [ceolter/ag-grid#624]
Hi,
I have a problem with AG-Grid. It seems to be a great tool, but it's lacking in responsiveness.

The main problem is that you cannot have columns that change their widths.

There should be a way to disable the adding of the "width" property, so that you can use CSS classes on each column and define CSS properties like "min.width", "max-width", etc.

**Comment by ceolter** [comment]
afraid that's not trivial. the widths of the columns are specified in pixels so that the grid can have full control of the grid widths. this is needed to, for example, to keep the grid headers in sync with the grid cells, also to have full control on column widths which is important for column groups, etc. this gets again more complex with pinned columns, floating rows, master/slave grids, etc.

```
The main problem is that you cannot have columns that change their widths.
```
what are you trying to achieve? if you want the grid to fit the screen, you can use api.sizeColumnsToFit(). if you want to do something else, then what are you trying to do? i'd rather consider a solution that doesn't rely on css for layout.

**Comment by gabrielenosso** [comment]
the method  api.sizeColumnsToFit() works fine.
But why isn't there a property on the grid to automatically use it on the initialization and also on window resize?

Couldn't it be helpful so that the table will be always of the parent size?

**Comment by gabrielenosso** [comment]
Moreover, when I resize the window, if I expand it the grid is resized, but if I shrink the window it doesn't resize and the window horizontal scrollbar appears.

**Comment by ceolter** [comment]
those are fair points, and ones i'd like to consider without using css.

i've created an issue that's more specific:
https://github.com/ceolter/ag-grid/issues/627

```
Moreover, when I resize the window, if I expand it the grid is resized, but if I shrink the window it doesn't resize and the window horizontal scrollbar appears.
```
this doesn't sound right. the online test drive resizes fine when the browser resizes, so something must be wrong in your code. if you can reproduce in a plunker i can take a look.

**Comment by gabrielenosso** [comment]
Could it be that it happens cause I'm using flexbox to regulate the parent's div size?

Moreover... should it get also the parent div height?

**Comment by ceolter** [comment]
I don't use flexbox so I can't comment.

**Comment by gabrielenosso** [comment]
I have still problems with the width responsiveness.
This time with animations as CSS transactions.
What I do in my project it just animating the "left" and "right" properties of a container, in which there is the grid.
Now the point is that the event"gridSizeChanged" is fired only at the begin of the animation.
The strange thing, though, is that the width of the grid is updated correctly following the width of its parent (even though it generates a little bit of lag due to the fact that it tries to resize more times during the animation).

**Comment by gabrielenosso** [comment]
It's not great, but I tried to attach a video:
https://drive.google.com/file/d/0B74fwRpri-2vWlRQYUpPd2pZMGM/view
When I click on the Filter button to hide the filters column, the "gridSizeChanged" event is fired only at the begin of the animation (when I click the button), but not at the end. The strange thing is that the grid size is meanwhile updated correctly (as you can see the border of the headers fits the whole container)

**Comment by gabrielenosso** [comment]
It probably happens because the window resize listener directly invokes the doLayout() method:
https://github.com/ceolter/ag-grid/blob/52863382b095aa722ee7e9f7240a64fab3c5d7fc/src/ts/gridCore.ts#L169
Maybe the doLayout method doesn't fire the "gridSizeChanged" when needed.

**Comment by ceolter** [comment]
thanks for the vid. that is strange, that should be working.

**Comment by gabrielenosso** [comment]
I don't know if it makes any difference, but I'm using the ag-grid-react-component (but I don't think it's the problem)

**Comment by ceolter** [comment]
should make no difference.

nice use of the grid btw. is that on a public facing website or internal?

**Comment by gabrielenosso** [comment]
It's internal (sorry! :S)

**Comment by gabrielenosso** [comment]
The width of the grid is updated thanks to the periodicallyDoLayout() method
(https://github.com/ceolter/ag-grid/blob/master/src/ts/gridCore.ts#L192) which continually runs.
It invokes the doLayout() method (https://github.com/ceolter/ag-grid/blob/master/src/ts/gridCore.ts#L258)
which should check if the size is changed.
In case it is changed, it redraws the rows and dispatch the EVENT_GRID_SIZE_CHANGED.

Is it right?
If it is right, the strange thing is: why the headers of the table are updated but the vent is not fired?

**Comment by gabrielenosso** [comment]
Update: trying to debugging it, I found out that the EVENT_GRID_SIZE_CHANGED isn't fired at all when the grid is enlarging (before I said that it was fired when the animation started, but it isn't true. It was another handler...)

**Comment by gabrielenosso** [comment]
Just to try to help, this is a video with the console. I'm logging every time the gridSizeChanged event is fired.
https://drive.google.com/file/d/0B74fwRpri-2vcUVqVktvRWQzb0U/view

**Comment by gabrielenosso** [comment]
Maybe I found the problem:
the method layoutWidth() doesn't return anything (https://github.com/ceolter/ag-grid/blob/master/src/ts/layout/borderLayout.ts#L235).

It should return true or false, checking if the width is changed! (Like the method layoutHeight() )

**Comment by ceolter** [comment]
good spot. i've check in a fix to trunk. i will be releasing in the next few days if you can wait.

thanks for all the work investigating this. i'm pretty busy these days with the enterprise release!!
