### ISSUE TITLE
ag-grid not working with angular2 beta typescript version

### ISSUE THREAD

**Issue by patilms16** [ceolter/ag-grid#625]
I have latest version of ag-grid (i.e. build of v2.3.6) 

I have included following in my index.html  
```bash
    <script src="../node_modules/angular2/bundles/angular2-polyfills.js"></script>
    <script src="../node_modules/systemjs/dist/system.src.js"></script>
    <script src="../node_modules/rxjs/bundles/Rx.js"></script>
    <script src="../node_modules/angular2/bundles/angular2.dev.js"></script>
    <script src="../bower_components/ag-grid/dist/ag-grid.js"></script>
    <script>
      System.import('angular2/core').then(function(ng2) {
        ag.grid.initialiseAgGridWithAngular2(ng2);
      });
     </script>
```
I have used ag-grid directive as follows: 
```bash
<ag-grid-ng2 style="width:100%;height:800px" class="ag-fresh" [gridOptions]="gridOptions" (rowClicked)="onRowClicked()" (ready)="onGridReady()"></ag-grid-ng2>
```

Also I have included the directive in my component :
```bash
@Component({
	selector: 'patient-search',
	templateUrl: 'app/components/patientSearchForm/patientSearchForm.html',
	directives: [ag.grid.AgGridNg2],
	providers: [PatientService]
})
```
I am getting 'EXCEPTION: No Directive annotation found on AgGridNg2' 

Please let me know If I am missing something.

**Comment by ronzeidman** [comment]
it works if you bootstrap like this
bootstrap.ts:
```typescript
import 'zone.js/dist/zone.min.js';
import 'reflect-metadata';
import {Top} from './top';
import {bootstrap} from 'angular2/bootstrap';
import * as core from 'angular2/core';

ag.grid.initialiseAgGridWithAngular2({ core: core });
bootstrap(Top);
```
index.html
```html
</body>
<script src="/node_modules/ag-grid/dist/ag-grid.js"></script>
<script src="/node_modules/systemjs/dist/system.src.js"></script>
<script src="config.js"></script>
<script>
    SystemJS.import('./src/bootstrap').catch(console.log.bind(console));
</script>
</html>
```
config.js
```javascript
SystemJS.config({
    defaultJSExtensions: true,
    paths: {
        './*': './*',
        '../*': '../*',
        '*': './node_modules/*'
    },
    packageConfigPaths: ['./node_modules/*/package.json'],
    map: {
        'crypto': "@empty"
    }
});
```

What I'm missing is how to make ag-grid work with SystemJS without adding the `<script src="/node_modules/ag-grid/dist/ag-grid.js"></script>` explicitly

**Comment by kjensenportfolio** [comment]
Thank you so much ronzeidman! This helped me out a lot! Now the grid is showing up! Thanks so much!

**Comment by helix46** [comment]
Sample code here for ag-grid using angular2 beta with typescript if anyone needs it
<https://github.com/helix46/ag-grid-angular2-beta-ts>

**Comment by patilms16** [comment]
Thank you @ronzeidman and @helix46  :)

**Comment by HydTechie** [comment]
Any Clue for below error: 
zone.js:388 Unhandled Promise rejection: Template parse errors:
**Can't bind to 'gridOptions' since it isn't a known property of 'ag-grid-ng2'.**
1. If 'ag-grid-ng2' is an Angular component and it has 'gridOptions' input, then verify that it is part of this module.
2. If 'ag-grid-ng2' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
 ("    <ag-grid-ng2 #agGrid style="width: 100%; height: 350px;" class="ag-fresh"

                     [ERROR ->][gridOptions]="gridOptions"
                     [columnDefs]="columnDefs"
                     [show"): RichGridComponent@44:21

**Comment by ceolter** [comment]
v7 has had a lot of changes with ng2 in ag-grid. if still an issue in v7, please raise in the ag-grid-ng2 project
