### ISSUE TITLE
autosizing the columns

### ISSUE THREAD

**Issue by tonyeung** [ceolter/ag-grid#626]
columnApi relies on the dev to pass in the width of the column
Is there a reason why we *must* pass it in ourselves?

Wouldn't inserting the code below into [here](https://github.com/ceolter/ag-grid/blob/master/src/ts/columnController.ts#L549) accomplish the same result?

        var waitForGridRendered = $interval(() => {
          var width;
          var element = document.querySelectorAll('#borderLayout_eGridPanel > div')[0]; 
          if (element) width = element.clientWidth - 2;
          
          if (width && width > 0) {
            this.gridOptions.columnApi.sizeColumnsToFit(width);  
          }
          
          $interval.cancel(waitForGridRendered);
        }, 100)

**Comment by ceolter** [comment]
correct, the column API does.

however you don't have to call this.

instead call the method of similar name on the grid api (gridOptions.api.sizeColumnsToFit). this takes no parameter and works out the width of the grid.

**Comment by tonyeung** [comment]
wow, awesome. I must be blind. Now that you've pointed it out its one of the first functions on the api list. Thanks!
