### ISSUE TITLE
have option to autosize grid, ie call api.sizeColsToFit automatically

### ISSUE THREAD

**Issue by ceolter** [ceolter/ag-grid#627]
grid should have option to fit cols by default, and also option to do this when grid size changes.

**Comment by gabrielenosso** [comment]
If the option would be set, it should update the cols width also when the columns are resized, sown/hidden and when the columns panel is toggled.

**Comment by DESURE** [comment]
Thank you, I will consider these events

**Comment by gabrielenosso** [comment]
Is it merged in the current version?
It doesn't seem to work yet.

And also: is the "gridSizeChanged" event invoked also after the first rendering?

**Comment by ceolter** [comment]
"Is it merged in the current version?"-> no

"And also: is the "gridSizeChanged" event invoked also after the first rendering?" -> yes

**Comment by armuell** [comment]
How is this coming along? I would really like this functionality and I am having problems hacking this to get it to work. I have tried setting a timeout/using onGridReady like described in #269 or #596 . Should I try and continue to hack it or is there a fix for this in the works?

**Comment by ceolter** [comment]
@armuell you should use the 'gridReady' event, and put the call in there.

see second example on this page:
https://www.ag-grid.com/javascript-grid-refresh/index.php

**Comment by dtslvr** [comment]
Thanks for your input, @ceolter. This works as expected (distributing columns equally) in ag-grid v5.1.2:
`
onGridReady: event => {
  event.api.sizeColumnsToFit();
}
`

But this does not change anything
`
onGridReady: event => {
  event.columnApi.autoSizeColumns();
}
`

Any ideas?

**Comment by ceolter** [comment]
@dtslvr 
autoSizeColumns(keys) takes a list of columns keys to autosize. you need to provide this list.

note it will only autosize columns that are rendered, so if using column virtualisation (the default), only cols visible by the horizontal scroll will be autosized.

**Comment by dtslvr** [comment]
Using the list of columns keys works, but only if I wrap it in a timeout like this:
`
onGridReady: event => {
  $timeout(function() {
    event.columnApi.autoSizeColumns(keys);
  }, 2000);
}
`

It also works if I add a button as in the example of [Resizing](https://www.ag-grid.com/javascript-grid-resizing). For me it seems that `onGridReady` fires too early.

**Comment by ceolter** [comment]
closing as this can and should be done in onGridReady. i've considered this in my mind, however onGridReady is exactly for calling the grids api after the grid is initialised. have different properties for different permutations of what one might call on the grid after it's ready would add to many redundant property methods and add to noise.

**Comment by marclazell** [comment]
onGridReady is called too early. Would be good to have an api which fires when data is provided.

**Comment by ceolter** [comment]
"onGridReady is called too early. Would be good to have an api which fires when data is provided."
=> then call sizeColsToFit() after you set the data. if you are using a framework (React or Angular etc) then you need to call it after they have done their update cycle.

**Comment by DVLP** [comment]
How I wired this with React

```
componentDidUpdate(prevProps) {
    // after update compares old data with new(now current) data to trigger column sizing only once after initial load
    if(!prevProps.data.size && this.props.data.size) {
      this.grid.sizeColumnsToFit();
    }
  }
```

**Comment by dtslvr** [comment]
I'm using this in combination with Angular and it works fine.

```javascript
onRowDataChanged:` (event) => {
  $timeout(() => {
    this.gridOptions.api.columnApi.autoSizeColumns(keys);
  });
}
```

Thanks for your support, @ceolter and @DVLP.
