### ISSUE TITLE
split out ag-Grid ng1, ng2 etc to assist dependencies for loading

### ISSUE THREAD

**Issue by tbenbrahim** [ceolter/ag-grid#631]
As there is no depency declared between ag-grid and angular, build tools are free to load ag-grid anywhere when creating a combined file, including before angular. Unfortunately, this causes the angular module to not be defined if one is unlucky enough to have ag-grid before angular in the combined file. This can be overcome with shims in webpack (http://stackoverflow.com/questions/33410860/ag-grid-not-working-with-angular-and-webpack/33427878)

I understand that angular1, angular2, ,etc.. are optional dependencies, however the conditional module registration is broken. Here is a suggestion which will save developers angst and wasted time before even starting to use the grid. Rather than packaging everything in one file, In package `ag-grid`, only include the core javascript code. Create packages `ag-grid-ng1`, `ag-grid-ng2`, etc... that  contain only the angular/web component specific code, and _unconditionally_ load the module, and declare a proper dependency on some version of the required library (such as angular) as well as `ag-grid`. This has the added benefit of smaller download sizes for everyone, as it is, every site serving ag-grid is serving code for angular1, angular2, web components, etc.., even if they are not using it. 

Thank you for your consideration.

**Comment by vladimir-ivanov** [comment]
and use es6/typescript module imports instead :-) :+1:

**Comment by ceolter** [comment]
```
This has the added benefit of smaller download sizes for everyone
```
-> not really. the code for each of them is about 1% of the total code base, so the reduced size won't really add anything.

with regards the dependencies and order of loading, yes that makes sense. i'll keep that in mind.

**Comment by ceolter** [comment]
this was done early in 2016
