### ISSUE TITLE
[bug] in `api.paginationGoToPage(4)`

### ISSUE THREAD

**Issue by changhuixu** [ceolter/ag-grid#6343]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

**Providing a Reproducible Scenario**

https://www.ag-grid.com/angular-data-grid/row-pagination/
In the Office Document, the Example shows that the API can navigate to pagination on a specific page number, e.g., 4.
The reason is that the Grid API knows the number of rows per page, then can calculate the final state.

However, if you use the plnkr: https://plnkr.co/edit/nfWPdFgz6VE9NnEq?open=app%2Fapp.component.ts
This plnkr is slightly different. I used `[paginationAutoPageSize]="true"` instead of a static page size.
Then try to set the page number from 4 to 100, you will see the final page number stays at 87.
The failure is due to that the Grid API assumes the number of rows per page is 100.
While the API should wait a little bit to do the pagination.

**Expected behavior**
`paginationGoToPage` should also work when `[paginationAutoPageSize]="true"`
This behavior works in Ag-Grid v27. I am not sure about if it is the same in v28, but it doesn't work in v29 now.

Thank you.

**Comment by StephenCooper** [comment]
Hi @changhuixu,

I have raised this for further investigation. In the meantime you can work around this by placing the api call in a setTimeout with a small delay. Not ideal but might be enough to unblock you in the meantime.

**Comment by changhuixu** [comment]
Thank you very much

**Comment by AndrewGlazier** [comment]
Hello,

This has been raised before, and we are already tracking it in our pipeline with the following reference and description:
AG-7888 - paginationGoToLastPage() goes to wrong page when paginationAutoPageSize:true

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

I would recommend signing up for ag-Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Regards,
