### ISSUE TITLE
nice to have tslint.json for the project

### ISSUE THREAD

**Issue by vladimir-ivanov** [ceolter/ag-grid#635]

**Comment by greglockwood** [comment]
Is the aim to help enforce a consistent code style for contributors in pull requests?

**Comment by vladimir-ivanov** [comment]
one of the aspects yes :-)

**Comment by ceolter** [comment]
that's a personal choice for the developers of the project, which then boils down to a personal choice or me!!!

personally I don't like code checkers as I find I'm able to write quality code without them. such checkers are useful when you have weaker developers contributing, however I'm not accepting large contributors with the grid (just some small changes, any large change goes through very big code reviews by me and normally gets rewritten anyway). we used similar in work last year and I found them frustrating!!

**Comment by vladimir-ivanov** [comment]
Agreed that it is your project and you should manage it in the way you think is best and respect your opinion. 
Slightly disagree about the necessity of code quality tools - e.g. sometimes you find yourself refactoring code and forgetting to remove a parameter declaration which is no longer needed, etc - code checker catches all sort of different tiny not necessary important details.
And regarding the developers contribution - all of the new frameworks come with tslint by default - e.g. angular2 etc, inappropriate contributions are simply discarded.

Thank you.

**Comment by ceolter** [comment]
thanks for all the valuable feedback, i welcome it all. i need to be balanced and appreciate the world has more experience that me. i've taken your points on board.

**Comment by vladimir-ivanov** [comment]
You are doing a great work by the way, evaluated other tables too, but this one is in my opinion the most suitable to use with angular2 as of now. 
Used slick grid in the past - but the support is discontinued at the moment. Might be nice to get ideas regarding functionality from there.

thanks

**Comment by ceolter** [comment]
yea i'm trying to get tests under way. spent a few hours on it yesterday then got annoyed with trying to configure it all. i'm very versed with testing from other languages. in javascipt, everything is so much more messey to get set up. how the hell to do i test typescript but use javacscript then integrate with node and gulp and then get grid modules loaded ahhhhhhhhh!!!!!!!!!!!!! i'll get back to it again soon, but i had to move on and focus on features again as i was getting to bogged down. but yes, deffo, project is to large now, tests are needed.

**Comment by vladimir-ivanov** [comment]
There are multiple different options there - from choosing what test runner to use (e.g. karma), what framework to use for assertions (e.g. jasmine/ mocha), whether to do the testing with using transpilers for typescript (e.g. babel - typescript with system js or webpack js) or simply include the generated ag-grid.js file and do a simplified js tests (assuming your tests are not written in typescript but in plain js).
On top of that you can decide whether to write unit tests using injectors (e.g. angular1 injector, then angular2 injectors etc) or simply test the core js (i would choose perhaps) in plain js manner.

Can spend a few hours to help / give you some ideas if you like this week and next week, before switching my attention to universal js :-).

**Comment by ceolter** [comment]
i was trying plain javascript tests against ag-grid.js generated file. i was caling jasmine directly from gulp using gulp-jasmine, which i understand doesn't require a test runner. i got stuck (annoyed) and left it. when i get my column work done, i'll get back to it.
