### ISSUE TITLE
adding field sorting to setState / getState?

### ISSUE THREAD

**Issue by vladimir-ivanov** [ceolter/ag-grid#636]
Had a request today to save the multi column sorted state to localStorage - so had to extend the setState and getState methods.
Can create a  pull request for the sorting to be added to the columns state if the feature could be potentially useful?

**Comment by ceolter** [comment]
get/set sort state can already be done via it's own api. this isn't part of the main column get/set state as it isn't managed by the columnController (inside my code). i'll keep this issue open as i may refactor to get it responsible, then the main get/set state will do this also.

**Comment by vladimir-ivanov** [comment]
it is just the case of ColumnController having a property columns -> and each column inside that array already contains sort property and is easy to expose (alternatively it should not belong there?)
Feel free to close if it goes against your design principles.
Thank you

**Comment by ceolter** [comment]
no, makes sense. column controller should do it all. just the evolutionary nature of the design is why it's the way it is now.

**Comment by ceolter** [comment]
see "Saving / Restoring State, Sort and Filter" at bottom of this page:
https://www.ag-grid.com/javascript-grid-column-api/

this is the preferred way of getting and saving the sort order.

we could change the design, however given it's the way it is now, changing the design would be a breaking change for people, so am leaving sleeping dogs lie.
