### ISSUE TITLE
Grid height problem when using flexbox (ngMaterial)

### ISSUE THREAD

**Issue by ninety7** [ceolter/ag-grid#637]
Hello,
I'm having big issues using agGrid inside ngMaterial flex card. The grid should have a 100% height but somehow it misses setting the correct height and so it shows a scrollbar inside the rows (not desired). Apparently it is not adding the header height to the grid height from what I could see.
I greatly appreciate if you could fix this issue which can be reproduced on firefox and chrome with this plunker:
http://embed.plnkr.co/ivKiUxsyIlDxUxdVKYGO/
Grid height is correctly set when setting print mode on the grid's options, but obviously I don't want to use print mode.

**Comment by ceolter** [comment]
I don't see anything wrong. In the plunker, the grid is showing with 5 or so rows and a scroll.

Using dev tools, I manually change the div height from 100% to 500px, and this works fine also.

**Comment by ninety7** [comment]
Thanks for your quick reply @ceolter. I'm just seeing 3 rows and I am trying to hide the scroll. Any ideas?
<img width="357" alt="screen shot 2016-01-19 at 10 33 42 am" src="https://cloud.githubusercontent.com/assets/5440311/12428217/42341af4-be98-11e5-90b1-824cc96924c3.png">

**Comment by ceolter** [comment]
afraid not :(

**Comment by ninety7** [comment]
Do you need any help on this? I tried to look at the code but there seems to be a very specific architecture that I could not understand

**Comment by ceolter** [comment]
i'm not sure what you are expecting. you don't have any height specified for the grid, but you say you want 100% height. in the dev tools, i set "height: 500px;" for the grid div, and it resizes fine. when it put it to 100%, ie resizes past the screen, but that's normal if you don't have height set appropriately in other parts of your application.
