### ISSUE TITLE
Static AGG Data

### ISSUE THREAD

**Issue by maraisr** [ceolter/ag-grid#640]
I have about 4.5 million rows in my database, showing 500 per page, and its working fine.. I want to aggregate "totals" for a column. My data is grouped, and is working. So for that "group" footer, is there a way to tell it what my aggregate values are, rather than let ag-grid calculate them?

**Comment by ceolter** [comment]
yes, either:
a) provide the data to the grid already grouped (like the file explorer does). that way, you put whatever you like into the group fields. (ps - i've not used this with paging before, so I'm only 75% sure it will work, but good chance it will work without issues)
b) provide your own 'groupAggFunction' - although it will be provided with all the nodes to group, you just ignore that and get your results from somewhere else.
