### ISSUE TITLE
columnController.hideColumns performance is unacceptable

### ISSUE THREAD

**Issue by vladimir-ivanov** [ceolter/ag-grid#641]
columnController.hideColumns - performance when adding bulk colIds and hide = false is very slow - tested with 95 colIds - single row record takes around a minute to render. Possibly related to 
 updatedCols.forEach(function (column) { var event = new grid.ColumnChangeEvent(grid.Events.EVENT_COLUMN_VISIBLE) .withColumn(column); _this.eventService.dispatchEvent(grid.Events.EVENT_COLUMN_VISIBLE, event); });

**Comment by scotthovestadt** [comment]
+1

**Comment by ceolter** [comment]
+1

**Comment by ceolter** [comment]
in the mean time, consider using setState

**Comment by vladimir-ivanov** [comment]
pretty sure setState was calling hideColumns somewhere down the stack trace :-). Might be wrong.

**Comment by ceolter** [comment]
fixing it now in v3 anyway, so not to worry

**Comment by vladimir-ivanov** [comment]
thank you

**Comment by ceolter** [comment]
now fixed in v3 branch. will be releasing that in the coming days.
