### ISSUE TITLE
would be nice to have angular1 digest cycle triggered on resize of columns

### ISSUE THREAD

**Issue by vladimir-ivanov** [ceolter/ag-grid#650]

**Comment by ceolter** [comment]
sorry vladimir, i'm not going to do this! you can achieve this by listening for the events and implementing yourself. i'm gearing away from angular specific stuff and focusing on the agnostic. that way, i allow the hooks (in this case the column resize event) for you to get deep with angular.

**Comment by vladimir-ivanov** [comment]
was going to edit this ticket - would be nice to have a generic hook so you can listen to changes on state - e.g. need to know when the state changed. Suggested the above, as I found code that does already that. 
Great that that code will be removed :+1:
