### ISSUE TITLE
Problems with position:fixed and offsetParent

### ISSUE THREAD

**Issue by cehter** [ceolter/ag-grid#654]
For our project, we need to fix the position of the filter. The first time the filter get the new position everything works fine. But if I want to close and reopen it, I got a problem. After some time I found the source: position:fixed and offsetParent don't work together. For a fast bugfix I changed the function `Utils.isVisible()` from: 
```javascript
return (element.offsetParent !== null);
```
to
```javascript
 return (element.parentNode !== null);
```

On first sight it works fine and I don't see a problem in using parnedNode, but I don't know the grid that well. Does this fix come with a problem I don't see at the moment or would it be possible to change it to parentNode?

Thanks and greetings.

**Comment by ceolter** [comment]
can't accept this change, it breaks the toolPanel, which also uses the popup service for displaying the aggField values. the method is also used by BorderLayout, but I'm not sure of the implications of it there.
