### ISSUE TITLE
columnApi.getDisplayedColumns() method is not available anymore

### ISSUE THREAD

**Issue by smelyakov** [ceolter/ag-grid#656]
It has been wiped out here https://github.com/ceolter/ag-grid/commit/29e1ecb938fe9a6d9790cd8ac27369cc3882d49e

I suppose that hasn't been done intentionally as soon as the method is still in the docs.

**Comment by ceolter** [comment]
Replaced with getDisplayedCenterColumns(), getDisplayedLeftColumns(), getDisplayedRightColumns()

(the last one i just stuck in now, about to release)

i'll update the docs.

the old method no longer made sense in the new way i implemented pinning.
