### ISSUE TITLE
rowSelection: 'multiple' and navigation with arrow keys

### ISSUE THREAD

**Issue by NisStrom** [ceolter/ag-grid#659]
It would be nice to be able to navigate the up and down from the currently selected row by using the arrow keys.

**Comment by ceolter** [comment]
you can navigate the selected cell, and then select the row with space bar.

**Comment by NisStrom** [comment]
Thanks for the info, it works but it is not very nice since i don not see anything until i hit the spacebar. Can i somehow change the style so that the current row is highlighted somehow?

**Comment by ceolter** [comment]
what if i added a css class to the focused cell, then you could add background color to that class. that get what you want?

**Comment by NisStrom** [comment]
Yeah, probably:
currentRow and currentCell.

I only need currentRow, but others might use currentCell.

**Comment by ceolter** [comment]
current cell already done, it has the ag-cell-focus class when focused and ag-cell-no-focus when not focused

**Comment by ceolter** [comment]
i've just implemented adding ag-row-no-focus and ag-row-focus to the rows. it will be in the the next release, which will be early next week.

**Comment by NisStrom** [comment]
Perfect, thanks.

**Comment by Ruud-cb** [comment]
@ceolter I don't really see why you would want to navigate a single cell, which can't be retrieved anyway I guess, and then have to press spacebar again to select the next row.
Could you make it possible to select the next row on navigating with arrows possible? An optional gridOptions property?
Or a better question then perhaps: How do I receive the navigation events so that I can automatically select the next row? In the documentation is stated 

> The grid element that receives the focus is provided to the cell renderers via the eGridCell parameter. 

How?

**Comment by ceolter** [comment]
@Ruud-cb you could use cellFocused to know when a cell is navigated onto. however that would also fire when user clicks on a cell, maybe that is ok?

re what you quote above, the cellRenderer gets the grids div object, so you can add whatever listener you want to the cell.

**Comment by Ruud-cb** [comment]
@ceolter hmm, I see what you are getting at, and with that I would somehow set a new selected row I guess. Will have to look at this later but wouldn't it be an idea to have an optional setting that determines if navigating up and down will result in a new row being selected? Should I make an issue?

**Comment by ceolter** [comment]
@Ruud-cb such a property would work - but i have turned down a lot of similar requests around selection. basically the grid offers a simple selection that works, if you want something different, then use the api.

the reason for this is open source projects can become a mess as everyone contributes what hey want a particular item to do. so then what happens is a product that has every possibly combination of feature under the sun, difficult to understand, and then breaks with bugs. so the ag-Grid philosophy is the opposite, i do not want to implement anything than (approx) <20% of users would use, instead allow it to be extendable.

**Comment by Ruud-cb** [comment]
Thanks for the reply @ceolter. You are correct about the open-source project thing indeed, It just depends if a majority of the users would like to have this feature. Sometimes hard to track down. Anyway,  I indeed can use the `onCellFocussed` (altough it also fires when there is an data update:(, and not documented), Is there another function to set a row selected, with the given `rowIndex` from the `onCellFocused` event? Browsing somewhat trough the code there should be a node.setSelected, but ir requires a value parameter if I'm correct? What would be the easiest way in this situation.
Thanks!

**Comment by ceolter** [comment]
you should use ```rowNode.setSelected(true/false)```

if you have the index, but not the rowNode, then you can look up the rowNode via api.getModel().getRow(index)

**Comment by Ruud-cb** [comment]
@ceolter Thanks! It works! Yet still have the issue when data is being updated. The data is server-push based, changes can come in every second. With this implementation it will cause a short flicker because when a row is updated it the cellFocused event which will set the row selected.
Any trick to prevent deselection when data is being updated? 

     onCellFocused:  function (params) {
        console.log("CellFocusChanged", params);
        if (params && params.forceBrowserFocus && params.rowIndex) {
            var row = self.gridOptions.api.getModel().getRow(params.rowIndex);
            row.setSelected(true);
        }
    },

**Comment by ceolter** [comment]
i don't understand what you mean. as long as everything is one in one VM turn, then there should be no flicker, as DOM updates are all done at the end.

**Comment by Ruud-cb** [comment]
Check this plunker: https://embed.plnkr.co/w9ppmvKejR0QVr7CFAMb/
Click  one row so that it is selected. Then watch what happens when items get updated.

**Comment by ceolter** [comment]
you are selecting in a different VM turn by the looks of it.

select the row you want selected directly after calling api.setRowData(), it's a synchronous call, so once it has returned, the grid has all the data set up and ready that you provided it.

or us the new insert rows api
https://www.ag-grid.com/javascript-grid-insert-remove/index.php

**Comment by AswinkumarRA** [comment]
may you try the below code for the functionality you are trying, it's working fine
onCellFocused(e) {
        if (e.column) {
            this.api.forEachNode(node => {
                 if (node.id == e.rowIndex)
                     node.setSelected(true, true);
             })
        }
    }
