### ISSUE TITLE
Custom Renderers to accept a promise that resolves template

### ISSUE THREAD

**Issue by tannerlinsley** [ceolter/ag-grid#66]
It would be great for custom renderers to accept a promise that resolves the cell/header content.  Some things just needs to be async sometimes ;)

**Comment by ceolter** [comment]
That's actually already possible!! The infinite scrolling does exactly that
when you scroll to a page that isn't loaded yet. What you do is create an
empty object. Then when the cell is rendered (you get notified of this by
the cell renderer getting called), you then kick off you async process.
When the process comes back, get the table re refresh the required row!

On 16 April 2015 at 23:56, Tanner Linsley <notifications@github.com> wrote:

> It would be great for custom renderers to accept a promise that resolves
> the cell/header content. Some things just needs to be async sometimes ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/angular-grid/issues/66>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by tannerlinsley** [comment]
Got an example of this?

**Comment by ceolter** [comment]
Just the code behind virtualization I'm afraid. Would make a good example
for the documentation alright.

**Comment by tannerlinsley** [comment]
So your saying I can return a promise inside of the cellRenderer on a
column Def?

**Comment by ceolter** [comment]
No you can't return a promise. Return blank from the renderer (or whatever
to display when waiting). Resolve the promise yourself, and when the result
comes back, get the grid to refresh that row - second time around rendering
the data will be there.

**Comment by tannerlinsley** [comment]
I see. It feels cumbersome though.

**Comment by tannerlinsley** [comment]
Are there other reasons eg. performance, etc, that the cellRenderer function could not simply return a promise?

**Comment by ceolter** [comment]
Hi Tanner,

No performance on the grid side. Just from a client point of view it
doesn't make sense to me. For example, if only one column requires this,
then showing n rows would result in n simultaneous network calls (assuming
the promise is to get the data remotely). Would of though such would be
better handled in batch, then get the grid to refresh the whole view (which
is practically instantaneous). Is your use case different?

**Comment by tannerlinsley** [comment]
Yes. I can think of many cases where asynchronous operations may need to
build charts, meta data, calculations etc. In my case I could use all
three. The assumption that the data being displayed on the grid all comes
from the same data source be it local or remote and is ready to be
displayed immediately is too strict. Angular is also built on promises, so
naturally there are going to be use cases where rendering using angular
will at some point have a requirement for this.

**Comment by ceolter** [comment]
Fair point. OK I agree with you!!

Do you want to raise an issue?

The implementation I would go for though would not use an AngularJS
promise, or any other promise library, as I'd want to limit dependencies
here - so would provide a simplified promise pattern (similar to the
callbacks in the pagination datasource). That way the client could use a
promise, but handle the promise itself, calling the grid provided callbacks
when the result comes back. That way it sticks with the plan of "limit
expose to AngularJS", allowing easy porting to Angular 2, Web Components,
any future web frameworks.

On 17 April 2015 at 22:34, Tanner Linsley <notifications@github.com> wrote:

> Yes. I can think of many cases where asynchronous operations may need to
> build charts, meta data, calculations etc. In my case I could use all
> three. The assumption that the data being displayed on the grid all comes
> from the same data source be it local or remote and is ready to be
> displayed immediately is too strict. Angular is also built on promises, so
> naturally there are going to be use cases where rendering using angular
> will at some point have a requirement for this.
> On Fri, Apr 17, 2015 at 2:15 PM Niall Crosby <notifications@github.com>
> wrote:
>
> > Hi Tanner,
> >
> > No performance on the grid side. Just from a client point of view it
> > doesn't make sense to me. For example, if only one column requires this,
> > then showing n rows would result in n simultaneous network calls
> (assuming
> > the promise is to get the data remotely). Would of though such would be
> > better handled in batch, then get the grid to refresh the whole view
> (which
> > is practically instantaneous). Is your use case different?
> > On 17 Apr 2015 17:43, "Tanner Linsley" <notifications@github.com> wrote:
> >
> > > Are there other reasons eg. performance, etc, that the cellRenderer
> > > function could not simply return a promise?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/ceolter/angular-grid/issues/66#issuecomment-94024352
> > >.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ceolter/angular-grid/issues/66#issuecomment-94065837
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/angular-grid/issues/66#issuecomment-94079887>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by tannerlinsley** [comment]
Here, I simply check for a promise of some sort (whatever lib may be present), and apply the resolution.  If it's not a promise, go default.

```javascript
RowRenderer.prototype.putDataIntoCell = function(colDef, value, node, $childScope, eGridCell, rowIndex) {
        if (colDef.cellRenderer) {
            var rendererParams = {
                value: value,
                data: node.data,
                node: node,
                colDef: colDef,
                $scope: $childScope,
                rowIndex: rowIndex,
                gridOptions: this.gridOptionsWrapper.getGridOptions()
            };
            var resultFromRenderer = colDef.cellRenderer(rendererParams);

            if (resultFromRenderer.then) {
                resultFromRenderer.then(function(res) {
                    if (!res) {
                        return;
                    }
                    checkType(res);
                });
            } else {
                checkType(resultFromRenderer);
            }

        } else {
            // if we insert undefined, then it displays as the string 'undefined', ugly!
            if (value !== undefined && value !== null && value !== '') {
                eGridCell.innerHTML = value;
            }
        }

        function checkType(result) {
            if (utils.isNode(result) || utils.isElement(result)) {
                // a dom node or element was returned, so add child
                eGridCell.appendChild(result);
            } else {
                // otherwise assume it was html, so just insert
                eGridCell.innerHTML = result;
            }
        }
    };
```

**Comment by tannerlinsley** [comment]
This obviously doesn't pause the grid cycle, so filtering and aggregating the resulting data doesn't work.

**Comment by ceolter** [comment]
"This obviously doesn't pause the grid cycle, so filtering and aggregating
the resulting data doesn't work."  . . . . . . why not? If you filter /
aggregate - then the dom inside the grid is discarded, so setting the
result into eGridCell will have no effect, as it is no longer attached??
Every time you sort or filter, the cell renderer will be called again.

On 17 April 2015 at 22:57, Tanner Linsley <notifications@github.com> wrote:

> This obviously doesn't pause the grid cycle, so filtering and aggregating
> the resulting data doesn't work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/angular-grid/issues/66#issuecomment-94084342>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by ceolter** [comment]
With regard handling the promise, what you propose looks good.

I do plan on making a lot of changes in this area though - I'm planning on
separating the 'getting of a value' and 'rendering of a value' - which will
impact. This will be implemented as the colDef having valueGetter and
cellRenderer. The result of the valueGetter will be passed to cellRenderer.
The result of valueGetter will also be used for sorting, filtering, and
allowing combinations of valueGetter and cellRenderers to be used (eg a
currency renderer, but the value is got in different ways).

Keep me posted with regards the gulp / build / requirejs work - it's on my
todo list again this weekend (as well as with other stuff unfortunately).



On 17 April 2015 at 23:04, Niall Crosby <niall.crosby@gmail.com> wrote:

> "This obviously doesn't pause the grid cycle, so filtering and
> aggregating the resulting data doesn't work."  . . . . . . why not? If
> you filter / aggregate - then the dom inside the grid is discarded, so
> setting the result into eGridCell will have no effect, as it is no longer
> attached?? Every time you sort or filter, the cell renderer will be called
> again.
>
> On 17 April 2015 at 22:57, Tanner Linsley <notifications@github.com>
> wrote:
>
>> This obviously doesn't pause the grid cycle, so filtering and aggregating
>> the resulting data doesn't work.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ceolter/angular-grid/issues/66#issuecomment-94084342>
>> .
>>
>
>
>
> --
> --
>
> The information transmitted is intended only for the person or entity to
> which it is addressed and may contain confidential and/or privileged
> material. Statements and opinions expressed in this e-mail may not
> represent those of the sender. Any review, retransmission, dissemination or
> other use of, or taking of any action in reliance upon, this information by
> persons or entities other than the intended recipient is prohibited. If you
> received this in error, please contact the sender immediately and delete
> the material from any computer.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by tannerlinsley** [comment]
I'm almost done with the build refactor.  I'll PR it as soon as it's stable.

As for the valueGetter, I love the idea.  It could expose some variables to decorate or transform the data as its coming in or getting sorted.  Just make sure it supports promises if angular is being used.

**Comment by tannerlinsley** [comment]
As for the first question, no, it doesn't sort or filter.  In the specific scenario, I'm creating a "fake" column that uses data from other columns to make some new data.  It also uses promises.  So since there isn't really a "value" that the column is pulling from the row, and since the cell renderer is async, the value isn't really there to be sorted or aggregated on.  This is why I love the idea of a valueGetter ;)

**Comment by ceolter** [comment]
The promise pattern you suggest, the rendered cell will miss the angular
digest cycle. So either need to cater for that, or just not bother . . .
once people understand how the grid works they will prob not use angular in
cell renderers anyway.

**Comment by tannerlinsley** [comment]
True.

**Comment by ceolter** [comment]
thinking about this more, i think adding handling of a promise should not be done for these reasons:

1) updating the cell after the fact i see as responsibility of the cell renderer. the cell renderer can pass back an html dom node, which it can keep a reference to and do whatever it wants at a future point.

eg:
```
cellRenderer = function() {
    var eSpan = document.createElement('span');
    $http.get('/someUrl').
         success(function(data, status, headers, config) {
         eSpan.innerHTML = createTheHtml(data);
     });
};
```

The approach above would work regardless of using a promise, or even just HTTP timer, or any other event after the cellRenderer returns.

2) three is already an api method rowDataChanged(rows) - this is the intended way to tell the grid to re-render a row. in keeping with this design, it could be extended to take a list of nodes or indexes (currently it takes data items). it could also could take a column (so grid knows to re-render just a column) but this would be a lot of work to implement.

**Comment by tannerlinsley** [comment]
I agree. So will the value getter work with promises? Or will it user the same concept. Attacking it higher up the chain is better I think.

**Comment by ceolter** [comment]
closing this issue, as the feature can be achieved with the current cellRefresh functions.

**Comment by reda-alaoui** [comment]
Here we are in 2023 , with the same problem as @tannerlinsley . Today, promises are everywhere and supported natively by all browsers.
Could we have an easy to use api that can deal with promises please?
