### ISSUE TITLE
Have all cells editable in grid on button click

### ISSUE THREAD

**Issue by a497988** [ceolter/ag-grid#660]
Hi, I was wondering if there is a current feature that I may be missing or a way to make it so I can have a grid with 5 columns and 10 rows, and make it so when a user clicks a button, all of the cells in the grid become editable, and then when they click a save button for example, all of the cells are then put back to the read only state?

I know there is single cell edit with the double click right now in the grid, but I was hoping for the multi-cell edit.

**Comment by ceolter** [comment]
no that doesn't exist. if you wanted to implement that, you can do it by implementing your own cell renderer. then keep track of all the currently displayed cells yourself and switch them all to edit mode.

**Comment by linuradu** [comment]
Was is the meantime this feature implemented? Would be a really nice feature :)
