### ISSUE TITLE
Wrong doc on the website about hiding row groups

### ISSUE THREAD

**Issue by gabrielenosso** [ceolter/ag-grid#661]
On one page it says that the property should be called "groupHideRowGroupColumns" (http://www.ag-grid.com/javascript-grid-properties/index.php), in another it says "groupHideGroupColumns" (http://www.ag-grid.com/angular-grid-grouping/index.php).

The second one is the one which really works :)

**Comment by ceolter** [comment]
damit!!! ok thanks. i've fixed the docs. website will get updated on next release.
