### ISSUE TITLE
Layout properties not working properly

### ISSUE THREAD

**Issue by gabrielenosso** [ceolter/ag-grid#663]
There are some problems with properties and events.

1) gridOptions.onColumnGroupChanged doesn't work.
(before it was onColumnPivotChanged)

2) gridOptions.onColumnResized is continually invoked while the user is resizing the column.
I know that probably that is how it should be, but you can't invoke gridOptions.api.sizeColumnsToFit() in it, otherwise it goes mad (too many invocations).
So it would be good to have another event when the resizing of the user is finished.

**Comment by ceolter** [comment]
#1 - mistake in the docs, i've just fixed it, it should be columnRowGroupChanged
#2 - the event has a 'finished' flag, set to true when the resizing is complete.

**Comment by gabrielenosso** [comment]
About the #2, could there be a possibility to mantain the size of the resized column? (as the method resizes all the columns)

**Comment by gabrielenosso** [comment]
Also: onColumnRowGroupChanged, the event object passed in the method doesn't have any reference to the current grouping state.
Shouldn't it have it, so that the code could, for instance, sort the data by that column?

**Comment by ceolter** [comment]
```
About the #2, could there be a possibility to mantain the size of the resized column? (as the method resizes all the columns)
```
sorry? i don't understand?

the current row grouping state can be got via: columnApi.getRowGroupColumns()
