### ISSUE TITLE
gridOptions.icons.menu is not working on version 3.1.0

### ISSUE THREAD

**Issue by ainasiart** [ceolter/ag-grid#665]
On version 3.1.0, 
the `font-size:0` in the class `.ag-fresh .ag-header-cell-menu-button` (line 67 of css files) makes difficult to have gridOptions.icons.menu working well.
It works itself but when I want to customize it, it shows nothing

**Comment by ceolter** [comment]
the problem i was trying to fix was that with font-size as default, the border around the menu icon was to large and as a result the menu border was hitting the edges of the header which looked crap.

any idea if we change font-size back (ie take the css out of the class), how the border issue can be resolved?

**Comment by ainasiart** [comment]
how about  `line-height: 0` instead of `font-size:0`

**Comment by ceolter** [comment]
accepted. i've now changed it to line-height.
