### ISSUE TITLE
3.1.0 no longer shows certain data

### ISSUE THREAD

**Issue by mparisi76** [ceolter/ag-grid#666]
I just upgraded ag-grid to version 3.1.0 and my grids no longer show ip addresses such as "167.82.67.0/24". Any ideas why that might be?

Version 3.0.0 works, version 3.1.0 does not.

**Comment by ceolter** [comment]
the only thing in that area that changes was the deep references for fields, ie from my release notes:
```
Now colDef.field can had deep references, eg colDef.field = 'owner.firstName'
```
nothing else comes to mind. also, nobody else has complained. to help troubleshoot, or at least get around the problem, can you try using valueGetter? (so if the field is ipAddress, use valueGetter='data.ipAddress')

if you can put a plunker together i can take a look.

or you can debug through the code, the method of interest is getValueUsingField (if using field) and executeValueGetter (if using valueGetter)

**Comment by ceolter** [comment]
no update, closing
