### ISSUE TITLE
How can I add a class to the ag-grid floating filter?

### ISSUE THREAD

**Issue by Berni3011** [ceolter/ag-grid#6661]
I was wondering if it is possible to add a headerClass to the floating-filter or if there is any way to add a class to the floating-filter.

We are currently working on a normal view and compact view of our grid. When the 'compact' class is added the grid is made smaller. For the header I can use the 'headerClass' property in the colDef. But this 'headerClass' does not apply to the floating filter.

**Comment by zoheil-ag** [comment]
Hi @Berni3011,

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

Something like this from our documentation may be useful to your question: https://ag-grid.com/javascript-data-grid/global-style-customisation-headers/#style-header-on-filter

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
