### ISSUE TITLE
WebComponent: Setting groupColumnDef causes exception

### ISSUE THREAD

**Issue by milesburton** [ceolter/ag-grid#667]
I'm attempting to specify a group column manually, but it looks like there's a some sort of missing reference.

Looking at line the following (compiled) line
 AgileGridProto.onChange = function (changes) {
                grid.ComponentUtil.processOnChange(changes, this.gridOptions, this);
            };

Should actually be this._gridOptions. That said, with that modification the eventing gets in a change loop and crashes.

It doesn't appear possible at the moment to use groupColumnDef

**Comment by ceolter** [comment]
are you trying to set columnDefs?

there is no such property groupColumnDef. you specify the groups as columns and then set using columnDefs property.

see the online examples for how to create groups of columns:
http://localhost/angular-grid-grouping-headers/index.php

**Comment by milesburton** [comment]
No? It's mentioned in the API several times, and the code?

http://www.ag-grid.com/angular-grid-grouping/index.php

"groupColumnDef	Allows specifying the group 'auto column' if you are not happy with the default. If grouping, this column def is inc"

The property is also exposed as a simple attribute.

Has this been deprecated?

**Comment by milesburton** [comment]
I had originally used columnDefs, and groupKeys but assumed the groupColumnDef provided more functionality. In that case am I best using columnDefs and specifying a group renderer?

**Comment by ceolter** [comment]
ops, sorry, my fault, i take back all of the above!! my head is deep in code and i'm trying not to take to much time on forums etc as it distracts me. let me take a look . . . .

**Comment by milesburton** [comment]
No worries, I use your library quite heavily so if I spot something I'll generally have a dig through the code first to see if I can spot anything

**Comment by ceolter** [comment]
great your using the grid heavily. with such a small complain, sounds like it's working out quite well for you!

**Comment by ceolter** [comment]
i am guessing you are setting the property AFTER you initialise the grid? not all the properties are updatable via web components properties yet. just i haven't gotten around to it. to see the status, you can check it here:
https://github.com/ceolter/ag-grid/blob/master/src/ts/components/componentUtil.ts

basically the properties WITH_IMPACT_ are the ones that you can set after the grid is initialised. the other ones, you only get to set them once, and if you want to change them, then you have to either set them directly on the gridOptions, or use an appropriate API method (if it exists).

in time, i'll change all the properties over to 'have impact', especially given i'm starting to integrate now with React, which will have the same problem and i presume many more people using React and ag-Grid than web components.

in the mean time, set the property you need on gridOptions. the one in question, groupColumnDef, doesn't actually do anything when you set it, it just 'gets used' next time the grid is rendering. so set it, then call one of the api.refresh methods.

ps i'm closing this, as it's not specific to groupColumnDef. if you want to open up another one for 'have all options impact' then you can, but i'm aware of this, and as i said, with react coming online with ag-Grid, i'll be dealing with this anyway.
