### ISSUE TITLE
3.1.1 bower package contains 3.1.0 dist files

### ISSUE THREAD

**Issue by AkosLukacs** [ceolter/ag-grid#668]
The title tells everything, I guess.
Building the bower package actually changes the dist files to 3.1.1, and changes content of the ag-grid.js and ag.grid.d.ts file as well.

**Comment by ceolter** [comment]
shit. thanks. i'll fix it. might be easiest if i just go to 3.1.2

**Comment by ceolter** [comment]
3.1.2 released
