### ISSUE TITLE
tsd duplication error

### ISSUE THREAD

**Issue by vlio20** [ceolter/ag-grid#669]
Hi,
I am using ag-grid.tsd and it has declaration for require function declare function require(name: string): any; (line 1467). 
The conflict is with "awesome-typescript-loader" library, it's runtime.d.ts.

Here is a screenshot of the error:
http://prntscr.com/9thxro

I have also opened issue in DefinitelyTyped repo. Here is a link:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/7738

**Comment by ceolter** [comment]
did you take ag-grid.tsd from Definitely typed repo, or the one that comes with ag-Grid distribution?

also, i'm confused, is it a problem with the grid or awesome-typescript-loader? if the latter, then nothing i can do???

**Comment by AkosLukacs** [comment]
@ceolter Looks like the typings in DefinitelyTyped repo are not updated, maybe kill that file with a note that says "just use the typings in the distribution"?

**Comment by ceolter** [comment]
looks like own issue that' snow solved, closing
