### ISSUE TITLE
Drag and Drop column headers

### ISSUE THREAD

**Issue by helix46** [ceolter/ag-grid#672]
I like your drag and drop toolbox, but it would be even better if I could grab a column header and drag it up to a grouping area like this: <http://demos.devexpress.com/aspxgridviewdemos/GroupingSorting/Grouping.aspx>
I could sell ag-grid to my boss easily if this were a feature. I've been at him to change our grids from server side (devexpress) to a js grid, but he likes easy UI grouping.
Re-arranging columns could work that way too
I see you have hundreds of issues to work through, but I hope this makes it to the list

**Comment by helix46** [comment]
Sorry, I see this is already raised #630

**Comment by ceolter** [comment]
Dragging columns to reorder is high on my list, hopefully in the coming two weeks. Yes it's already raised, so closing this issue.
