### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by AmitMY** [ceolter/ag-grid#673]
Im using AG-GRID 2.7.
This is because on 3+, I cannot find the option for floating columns, and all of my columns are set in the 100% of my div. So my first question is, what is the setting that im missing?
My second question is: Is there a one-time-binding parameter? Such ill trigger table refresh only when data changes, and there will not be $$watchers all the time?
If not, can the devs add it? I get really slow performance from just 300 rows and 20 columns.

Thanks

**Comment by ceolter** [comment]
if you mean pinned columns (you say floating columns), then this changed in 2.7. please see docs:
https://www.ag-grid.com/angular-grid-pinning/index.php

"My second question is: Is there a one-time-binding parameter?" -> the grid doesn't use angular, so question about one-time-binding doesn't make sense.

ps in future, please use the forum for issues, github should only be used for when grid needs fixing.
