### ISSUE TITLE
Docs: Default steps for version 30.0.0 for React.js generates fatal error using Next.js

### ISSUE THREAD

**Issue by icatu-izoton** [ceolter/ag-grid#6750]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
After installing the library with `npm i ag-grid-community ag-grid-react` and serving the project. I get the following error:

```
./node_modules/ag-grid-community/dist/ag-grid-community.esm.js:6:0
Module not found: Can't resolve '@ag-grid-community/client-side-row-model'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/ag-grid-react/lib/reactUi/agGridReactUi.js
./node_modules/ag-grid-react/main.js
...
```

**Expected behavior**
The project should run without any errors, like version **29.3.5**. When I downgrade this version, the project runs without any problems.

**Please tell us about your environment:**
Ubuntu 20 (WSL2), Visual Studio Code, npm and next.js

* **AG Grid version:** 30.0.0

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0

* **Language:** TypeScript 5.1.3

**Comment by seanlandsman** [comment]
Are you able to provide a reproducible example for this?

**Comment by KristjanVall** [comment]
+1

**Comment by seanlandsman** [comment]
Issue can be tracked via https://github.com/ag-grid/ag-grid/issues/6744
