### ISSUE TITLE
Default sort with enableServerSideSorting not working

### ISSUE THREAD

**Issue by Wykks** [ceolter/ag-grid#676]
When using `enableServerSideSorting: true` the column property `sort` doesn't set `params.sortModel` inside `getRows` (datasource)

**Comment by ceolter** [comment]
cannot reproduce.

i used this example:
https://www.ag-grid.com/angular-grid-virtual-paging/virtualPagingServerSide.html

and set:
        {headerName: "Athlete", field: "athlete", width: 150, suppressMenu: true, sort: 'asc'}

and the sorting worked fine on the server side.

**Comment by Wykks** [comment]
Indeed, I does work when setting `columnDefs` directly.

But not when using `$scope.gridOptions.api.setColumnDefs(columnDefs)` after a while

Example : http://plnkr.co/edit/b94R0e4lRSV5FQ5bmCi8

**Comment by Wykks** [comment]
After re-thinking about this, in doesn't make sense to ask ag-grid to properly sort after the datasource is set.
Because getRows is directly done even if there isn't any column defs.

The fix is to either be sure that we have a column defs before setting the datasource, or check in the getRows function if column defs are sets before anything.

Maybe a warning could be usefull if we are trying to getRow without column defs, what do you think ?

**Comment by ceolter** [comment]
yes that makes sense. setting columDefs should not trigger the datasource to fetch. even if you try to do 'getRow' without column defs, it still has the problem.

however not sure printing a warning message is correct, that's specific to you, for someone else (who is not doing server side filtering), doing a fetch without columns could make perfect sense.

can you change your code, so that if the column defs are not present, you don't do the fetch?

**Comment by Wykks** [comment]
But when doing a getRow without columns defs the grid doesn't know what to display. In which cases calling getRow without any column defs is valid ?

> can you change your code, so that if the column defs are not present, you don't do the fetch?

Yes, that's how I fixed it, thanks anyway :)

**Comment by ceolter** [comment]
could be - the data could be fetching in the background while the columns are being sought from someplace else. or the user could be adding / removing columns while the data is fetching. i'm thinking of a data analysis tool, there the data takes a while to come back.
