### ISSUE TITLE
setColumnsVisible errors if colId not in grid

### ISSUE THREAD

**Issue by sfescape** [ceolter/ag-grid#677]
I think setColumnsVisible should just ignore colIds that are not in the grid. The point of this call is to pass in an array of colIds, if you have to verify each one is in the grid you might as well set each one individually.

Now you get this error:

TypeError: Cannot read property 'getColDef' of null

I maintain a list of colIds the user has turned off, I don't care if any of the colIds are in the grid, but if they are I want to turn off visibility.

**Comment by ceolter** [comment]
not true for latest version.

this is the code (actionOnColumns method in columnController)
```
            keys.forEach( (key: Column|ColDef|String)=> {
                var column = this.getColumn(key);
                if (!column) {return;}
                action(column);
                updatedColumns.push(column);
            });
```
the magic bit:                 if (!column) {return;}

if it doesn't find the column, then return.

if you are on the latest, and still a problem, can you be so kind as to debug through this portion of code and see what's happening, as it's pretty simple code, i can't see where the bug might be.

ps closing, unless i can get to reproduce!

**Comment by sfescape** [comment]
Thanks, I didn't realize you were releasing so fast! I'll upgrade from 3.0 to 3.1.2 and retest.

Cheers!
