### ISSUE TITLE
add 'headerClass' for column header

### ISSUE THREAD

**Issue by ceolter** [ceolter/ag-grid#679]

**Comment by tatsujin1** [comment]
https://www.ag-grid.com/angular-grid-column-definitions/index.php

"headerClass	Class to use for the cell. Can be string, array of strings, or function."

Not what you're after?

**Comment by ceolter** [comment]
doesn't do it for the header groups.

**Comment by DominicTobias** [comment]
So there is no solution to adding a class to the column header only??

**Comment by 13sergy** [comment]
You can add parameter - headerClass: 'className'

**Comment by DominicTobias** [comment]
@13sergy that works for childless headers only unfortunately

**Comment by re5ive** [comment]
Hi, 

how do i style for group headerColumn?

when i group a column i want to highLight the columnHeader by styling the text color.. how do i do this?

**Comment by StanislavStadnyk** [comment]
I guess I found the solution how to manipulate the styles for header cells
use ATTR of header cell, in my case - http://prntscr.com/kvq6c2
SCSS part - http://prntscr.com/kvq6yo
It works and I tested in FF, Chrome, Edge
