### ISSUE TITLE
[header] Variable header height for different header rows

### ISSUE THREAD

**Issue by ceolter** [ceolter/ag-grid#680]

**Comment by ceolter** [comment]
So that each header row can be a different height.

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-104

**Comment by jfstephe** [comment]
Hi - can we get some visibility of if/when this may be implemented?

**Comment by makinggoodsoftware** [comment]
Hi,

Just to let you know that v10.0.0 has just been released and includes the fix that we discussed in this thread.

Thanks

**Comment by jfstephe** [comment]
awesome ta!

**Comment by rvberloo** [comment]
tested and works, nice!

**Comment by stile1201** [comment]
Hi.

I have a grid with 2 levels of column groups, in addition to the standard headers, and want to be able to set the height of each of them to be different. Is that covered by this issue? And if so, what is the fix that was "discussed in this thread"? I can't see anything here, and can't see anything in the docs that explain how to do this. I know there is groupHeaderHeight vs headerHeight, but that doesn't cover my use case with 2 levels of groups.

Thanks!

**Comment by stile1201** [comment]
Ok, I've looked at the code and I can see that I can't do what I want to do. It's a shame, but hopefully I'll get by without it.

**Comment by jfstephe** [comment]
I agree that this was suprising and feels a bit rushed. Having said that. When I reviewed our use cases, so far, we only need the 2 different types. Perhaps the suggestion is that having more than 2 levels with varying heights would mean a lot of header space and therefore be a sub-optimal UX - which is what we are starting to find. Dunno, just guessing. Some guidance may in the docs would have helped.

**Comment by DominicTobias** [comment]
I want to make the top row a normal height as the children can be multi line:

![headers](https://user-images.githubusercontent.com/760314/51049121-d9998100-15c4-11e9-821b-1cf891a01c04.jpg)

Saying as "discussed in this thread" doesn't help much. I know there is a `getRowHeight` but there doesn't seem to be a `getHeaderHeight`. Also I think it would have been simpler if either `rowHeight` or `headerHeight` could accept a function?

So is there a way to set a different header height on the top column row? Thanks!
