### ISSUE TITLE
using pinned columns misaligns other columns

### ISSUE THREAD

**Issue by ajgraham671** [ceolter/ag-grid#681]
I recently updated to the 3.1.2 version and noticed the change in how pinned columns are now set. I updated my gridOptions and columnsDefs to reflect this new change. Upon refreshing, I noticed that all the columns except for the left most pinned column was offset by the columnDef width of the pinned column. Disabling the style="margin-left:50px;" css property  on the ag-header-viewport div seems to fix the issue. In your examples on the ag-grid website everything seems to be working fine. Maybe this is more user error. 

Note: I also have colResize enabled.

**Comment by ceolter** [comment]
without been able to reproduce, there is not much i can do. you are the first to mention this, so i'm guessing it is user error, otherwise others would of complained. can you reproduce in a plunker? or tell me the steps to reproduce in one of my examples?

**Comment by ajgraham671** [comment]
After digging around for quite a while I finally figured out what was happening.
