### ISSUE TITLE
Build: Exported external package typings file is not a module.

### ISSUE THREAD

**Issue by Mithras** [ceolter/ag-grid#682]
After 
> Minor: Added 'typings' to package.json, so TypeScript can pick up typings from node module

I get this: https://gyazo.com/87c2d1fcc1c3b142206af3701cfdc758
I don't think you should specify 'typings' in package.json in case it's not a module.
And I don't know what's the correct way to fix it... Probably this helps: https://github.com/Microsoft/TypeScript/issues/2839

PS Before that I just used
`/// <reference path="../node_modules/ag-grid/dist/ag-grid.d.ts" />`

**Comment by ceolter** [comment]
I haven't tried TypeScript in anther ES6 module. I'll need to understand modules better.
