### ISSUE TITLE
gridSizeChanged event not working properly

### ISSUE THREAD

**Issue by gabrielenosso** [ceolter/ag-grid#683]
It seems that the gridSizeChanged event doesn't work as it should.
1) If I show the tool panel, it is invoked, but only after some time (it's not great...).
2) If I hide the tool panel, it is NOT invoked.
3) it is NOT invoked when row groups are changed (onColumnRowGroupChanged)
4) it is NOT invoked when changing the column visibility (onColumnVisible)
5) it is NOT invoked after resizing columns (onColumnResized with event.finished === true).

Morevoer, is there a way to invoke api.sizeColumnsToFit() everytime the data is shown?
I tried to put it in the onReady(), but it doesn't work.
(I'm using the React component since today)

**Comment by ceolter** [comment]
gridSizeChanged is for when the grid body changes size. so the following should never fire it:
3) it is NOT invoked when row groups are changed (onColumnRowGroupChanged)
4) it is NOT invoked when changing the column visibility (onColumnVisible)
5) it is NOT invoked after resizing columns (onColumnResized with event.finished === true).

if you want to know when columns change state, you need to register for the column events.

```
Morevoer, is there a way to invoke api.sizeColumnsToFit() everytime the data is shown?
```
-> what do you mean by "data is shown", if you mean whenever you set the data, then why don't you call it after you set the data?

i think maybe your expecting the girdSizeChanged to be something different to what i intended. the purpose of gridSizeChanged is to inform you of changes to the div size you placed the grid in. eg changes as a result of windows resize, or your app changing the grid size in some other way. if your looking to resize your cols after cols have changed, then this is not the right event.
