### ISSUE TITLE
Support customization in data export

### ISSUE THREAD

**Issue by grandtiger** [ceolter/ag-grid#685]
First of all, thanks a lot for this great product!

I have a suggestion to enhance data export feature. Currently Value getters are used to work out the value to export. However, the exported values look like "Thu Dec 17 2015 00:00:00 GMT-0500 (Eastern Standard Time)" for date objects, which Excel doesn't recognize as dates. Wouldn't it be better to export what's currently on the screen (using cell renders)? I think it's even better if we allow different renders for the export, e.g. a concise rendering for the display, and a more Excel friendly rendering for data export.

**Comment by ceolter** [comment]
can't use cellRenderer, as they can provide HTML, not just values. what would be needed is a new  'exportFormatter' function, which does exactly as you suggest.

**Comment by grandtiger** [comment]
@ceolter Thanks! Are you planning to implement 'exportFormatter' function soon?

**Comment by ceolter** [comment]
i'm undecided when. i might have a client willing to pay for things, if they do, then they will be getting preference.

**Comment by AkosLukacs** [comment]
Run into the same thing, and used the valueGetter to return a formatted date as a string for the value.
@ceolter would you accept a PR with this feature? (not sure I would have the time to do it, but theoretically speaking)

**Comment by ceolter** [comment]
i've added processCellCallback() for next release, allows formatting of data when doing csv export
