### ISSUE TITLE
Ready event is being triggered multiple times on window resize.

### ISSUE THREAD

**Issue by kayue** [ceolter/ag-grid#687]
I am using Angular 2 trying to set datasource when grid api is ready:

```html
<ag-grid-ng2 (ready)="onGridReady()">
</ag-grid-ng2>
```

However this `onGridReady` method is also being called on window resize...

**Comment by kayue** [comment]
Actually the ready event is triggered by zone.js. 

Both ag-grid and zone.js is sharing the same event.

**Comment by ceolter** [comment]
i didn't know this. yes ready is also fired by angular 2. to get around this, you can inspect the ready event. only the ag-Grid ready event will have the api parameter.

```
function onReady(event) {
  if (event.api) {
    // this is the grid ready event
  }
}
```

**Comment by kayue** [comment]
@ceolter Will you consider renaming it to `ag-ready`? At least there should be note somewhere in the site.

I was trying to set datasource on `(ready)="api.setDatasource(xxx)"` and it calls the datasource few hundreds times as I resize... :(

**Comment by ceolter** [comment]
ah crap, i didn't realise it was called more than once. so Angular is firing 'ready' every time you resize?

**Comment by kayue** [comment]
@ceolter Yes. 

Checking `event.api` did work, but I bet not many people will notice this.

**Comment by ceolter** [comment]
i've updated the docs. but it's not nice, as even if it's in the docs, most people will miss it. can you just confirm, 'ready' is called for ng2 every time the window resizes???
