### ISSUE TITLE
Typescript definition file error for ColDef

### ISSUE THREAD

**Issue by katonap** [ceolter/ag-grid#689]
ColDef.field is mandatory in the d.ts file, while the documentation says it is optional (and the grid is working without it):
Columns & Cells / Column Definitions / colId: '(...) If both field and colId are missing, a unique ID will be generated.'

**Comment by ceolter** [comment]
it's optional. this is the code:
```
        /** The field of the row to get the cells data from */
        field?: string;
```
https://github.com/ceolter/ag-grid/blob/master/src/ts/entities/colDef.ts

**Comment by katonap** [comment]
Oops, I found this in an older example. Sry
