### ISSUE TITLE
Tool panel hover Row Groupings destination hard-coded style

### ISSUE THREAD

**Issue by gabrielenosso** [ceolter/ag-grid#692]
Hi, there is a problem customizing the style of the tool panel.

When you drag a column name into the "Row Groupings" area, the background of this area becomes green. The problem is that this is hardcoded: it changes the style directly with JS.
Instead it should add just a CSS class, as it happens with the list items themselves (.ag-list-item, .ag-dragging, .ag-dragging, .ag-drop-target-below, etc.)

**Comment by ceolter** [comment]
noted. thanks.

**Comment by ceolter** [comment]
this has changed, background no longer changes color.
