### ISSUE TITLE
Dynamic Height on Virtual Pagination

### ISSUE THREAD

**Issue by jorgecuesta** [ceolter/ag-grid#693]
Hi! first of all, AWESOME GRID! Your work cover all most useful features wanted in a Grid Component.
I'm looking for a way to use getRowHeight callback on virtual pagination.
Can you say me if I can do this or not? If no, can you say me if you have a plan to implement it in a closet future?

Regard, Jorge! (sorry about my english skills)

**Comment by ceolter** [comment]
hi, no you can't do this, an no there is no plan, sorry :(

basically for the virtual rows to work, the grid has to be able to work out, using maths, what rows to display when you jump to a position. the only way to do this with differing row sizes would be to load back all the heights of all the rows in the dataset, which goes against the design of virtual pagination which only needs to know about the window of rows it is displaying.

**Comment by cletusw** [comment]
It appears `getRowHeight` works for floating rows, even with virtual paging (which makes sense since all floating rows are known at once). Unfortunately, if `rowHeight` is set, `getRowHeight` is never called. Shouldn't this still be called to allow dynamic heights on the floating rows?

**Comment by cletusw** [comment]
If we simply switch the order of the `if` and `else` [here](https://github.com/ceolter/ag-grid/blob/12bdfdfce5caac8d7ec2765f0a09174b4b8358df/src/ts/gridOptionsWrapper.ts#L406-L415), we get the desired behavior.

**Comment by ceolter** [comment]
why would you set both? just one or the other should be used. if you want to use getRowHeight, it doesn't make sense to provide the other.

**Comment by cletusw** [comment]
I'm using virtual paging, so getRowHeight is not called for the main rows, hence static rowHeight. I'm also using floating top rows that I want to be a different height, hence getRowHeight. If there were a separate floatingRowHeight property that would also work, but I figure other use cases may have different heights depending on the contents of each floating row. rowHeight for the paged data, getRowHeight for the known-at-once floating data.

**Comment by ceolter** [comment]
can you use getRowHeight() for both?

**Comment by cletusw** [comment]
It doesn't work for non-floating rows in the virtual paging case because it
needs to know the height before loading data. I could see it being
re-written to be called once before loading any data to get the
non-floating rows height. That would make more sense than requiring both
properties.

**Comment by ceolter** [comment]
understood. i have swapped the order of the if/else as suggested above. will be in next release.

**Comment by cletusw** [comment]
Thanks!
