### ISSUE TITLE
Ability to customize toolPanel

### ISSUE THREAD

**Issue by dnewbold89** [ceolter/ag-grid#694]
Hi,
Are you able to customize the toolPanel. Basically I only want the hide/show column function to appear in the toolPanel. Thanks

**Comment by scotthovestadt** [comment]
You can use the APIs directly and create your own tool panel. I don't think you can currently customize the existing one.

**Comment by ceolter** [comment]
you can hide the two bottom 'aggregation' and 'grouping' sections. other than that, nope, you have to build your own. it's my plan to soup up the tool panel in future releases, probably q3 this year.
