### ISSUE TITLE
Master detail accessibility issue

### ISSUE THREAD

**Issue by bhanu345-cmd** [ceolter/ag-grid#6948]
Details cell renderer is giving the below mentioned accessibility issues.
<img width="919" alt="image" src="https://github.com/ag-grid/ag-grid/assets/63151401/0e9928a3-e927-4d74-ae04-31a107465458">

Code sandbox: https://codesandbox.io/s/sparkling-firefly-kgwgv5?file=/src/App.tsx

Using **Accessibility insights for web** extension for checking accessibility issues

**Comment by zoheil-ag** [comment]
Thank you very much for raising this with us @bhanu345-cmd.

Currently there's no way to implement this behavior with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference and description:
AG-9086 [Accessibility] Allow elements with an ARIA role that require child roles to contain them

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
