### ISSUE TITLE
upgrade from 1.14 to 3.2 - click on sort icon does not respond

### ISSUE THREAD

**Issue by spfiedler** [ceolter/ag-grid#698]
I am in the midst of upgrading to ag-grid 3.2 (from 1.14).

Formerly, if I had a sort icon in my column header, I could click on it and it would respond, performing a sort.

After upgrading to 3.2, it no longer responds at all.  I can click on the column header and it works fine.

If this is a behavior change, does someone have a suggestion on a work around?

**Comment by ceolter** [comment]
the click is on the label, not the icon. so in the online example, eg if you click 'country', then the sort icon appears, clicking on the icon does nothing, but clicking on the country (again) will sort in the other direction.

**Comment by spfiedler** [comment]
This is what I'm saying.... it used to ALSO be on the icon, but no longer.

**Comment by Wykks** [comment]
+1
I also need to click on the icon; sometimes my column don't have labels.

**Comment by ceolter** [comment]
ok fixed. will be in next release. no you can click anywhere on the header (just not the menu or the resize) to get it to sort.

**Comment by Wykks** [comment]
Thanks ! :)

**Comment by spfiedler** [comment]
Ditto - thank so much.
