### ISSUE TITLE
Support angular2-universal

### ISSUE THREAD

**Issue by vaseker** [ceolter/ag-grid#699]
Thanks for `ag-grid-ng2`!
Rendering `ag-grid` on server causes `document` reference error:
> EXCEPTION: ReferenceError: document is not defined in [columnDefs in SampleComponent@1:53]
ORIGINAL EXCEPTION: ReferenceError: document is not defined
ORIGINAL STACKTRACE:
ReferenceError: document is not defined
    at DragAndDropService.init (./ng2/node_modules/ag-grid/dist/lib/dragAndDrop/dragAndDropService.js:21:9)
    at Grid.setupComponents (./ng2/node_modules/ag-grid/dist/lib/grid.js:164:28)

**Comment by ceolter** [comment]
it is not my intention to provide server side rendering for ag-Grid. it's intended to be used in internal financial applications, which do not require server side rendering.
