### ISSUE TITLE
CSS BUG - addition of position: absolute to .ag-cell causes all columns to collapse to the left

### ISSUE THREAD

**Issue by hunthunthunt** [ceolter/ag-grid#701]
https://github.com/ceolter/ag-grid/blob/3.3.0/src/styles/ag-grid.styl#L239
(Line 249 above)

See example of bug as rendered in Chrome:

![image](https://cloud.githubusercontent.com/assets/226283/12900923/a1565b46-ceb0-11e5-898e-fe71e0d0c02c.png)

**Comment by ceolter** [comment]
i don't understand what you meant, this is not happening in the examples on line??

**Comment by hunthunthunt** [comment]
I can see that is not happening in the examples online. Possibly a conflict with my applications CSS.

Note also I am using React, not sure if that's related.

**Comment by ceolter** [comment]
you need to make sure you are including the CSS for the grid.

**Comment by hunthunthunt** [comment]
yes, CSS for the gird was included. thanks

**Comment by ceolter** [comment]
i'm not sure what's happening then. the grid should lay out using the css. are you 100% sure the css is been used?

maybe you can inspect on of the grid elements, see if the ag-cell class has the following (just right click of the cells that are all bunched up on the left hand side):
```
.ag-cell
    display: inline-block
    white-space: nowrap
    height: 100%
    box-sizing: border-box
    text-overflow: ellipsis
    overflow: hidden
    position absolute
```

**Comment by hunthunthunt** [comment]
I think this was to do with a mis-match btw `ag-grid` and `ag-grid-react` packages - was accidentally importing the older `ag-grid-react-component`

**Comment by ceolter** [comment]
thanks for the update. ```ag-grid-react-component``` project is already removed from github, so nobody else should make this mistake.
