### ISSUE TITLE
How to correctly use 3.3.0 with modules?

### ISSUE THREAD

**Issue by Mithras** [ceolter/ag-grid#702]
At the moment write something like this https://gyazo.com/b1275804ef344b05cbf4456c37bf1fbe. Is it the correct way?
And I import interfaces to leverage typings like this https://gyazo.com/9db739408f52e36e116190bc4b67a284 everywhere else. That's how it's supposed to be?

**Comment by ceolter** [comment]
what you need is this:
```
import {initialiseAgGridWithAngular1} from 'ag-grid/main';
```

however i forgot to include this attribute in my CommonJS output. i've just fixed this and i'll be releasing in the next hour 3.3.1

yes you also import interfaces like that. but i have been lazy with the exports, it's on my todo list. this is the current list of exports:
https://github.com/ceolter/ag-grid/blob/master/main.d.ts

i need to spend 30min exporting everything when i get a chance.

**Comment by ceolter** [comment]
3.3.2 is released and has this fixed.
