### ISSUE TITLE
Request/Help :  'For Print' add option to duplicate headers on each page

### ISSUE THREAD

**Issue by dstackowiak** [ceolter/ag-grid#708]
First of all, thanks a lot for this great work with this component !

I've a request of users of my app, who print large grids : they would see the headers repeatead on top of each printed pages.

After somes searchs, this could be done with css  `@page` and `running-elements`  : [example](http://stackoverflow.com/questions/9729461/creating-page-headers-and-footers-using-css-for-print)
I tried this without success. Because of my low css skills and the 'running-element' must have an id attribute (If I understood correctly).  So i tried this unclean solution : change the dom with angular and add an id attribute to the div with 'ag-header' class : fail.

Maybe someone has already do this? 
Or maybe a solution could be provided by the component ?

**Comment by ceolter** [comment]
if you want to see the headers on each page, how about you split it out into different grids?

**Comment by dstackowiak** [comment]
Interesting idea.  
That implies that rowDaras are split by me (easy), the others gridOptions are shared by all grids.
And no need to handle sorting (i mean changing the sorting) because this is just for printing, no user interaction.

Ok, great idea. i'll try this.
Thanks :)

**Comment by ceolter** [comment]
don't share gridOptions!!! the grid puts the API on gridoptions, so it will get overridden if multiple grids sharing the options.

**Comment by renaudl** [comment]
Anyone doing this?

**Comment by jtkelling** [comment]
I REALLY need this exact feature.  When printing spans multiple pages, not having the headers at the top of each page, it makes it VERY difficult to tell what each column contains after the first page.
