### ISSUE TITLE
customization of  header's svg icon  to popup filter menu 

### ISSUE THREAD

**Issue by lblanquet** [ceolter/ag-grid#711]
I wanna first express my gratitude and respects to the author of this great product !

It would be great to allow some customization of the svg icon poping filter menu.
For instance :  
    **setFilterIcon(height, width,  [svg optionnal])**

**Comment by ceolter** [comment]
thanks for the kind words :)

you can already change the icon
https://www.ag-grid.com/angular-grid-icons/index.php

or you can change the whole header
https://www.ag-grid.com/angular-grid-header-rendering/index.php
