### ISSUE TITLE
Getting CSP issue with eval

### ISSUE THREAD

**Issue by ajayreddy002** [ceolter/ag-grid#7118]
https://github.com/ag-grid/ag-grid/issues/5371#issuecomment-1564005278
In the above ticket mentioned like we have removed use of eval on 30.0.0 to avoid csp issues with eval. But still i am getting csp issue eval after upgrading to 30.0.0. from 28.2.1. At which version this has been removed, and i don't want to use unsafe-eval in header. And also may i know is it block something when we block this csp ?
```
[] bug report => ag-grid-enterprise.auto.esm.js:13218 | script-src | blocked
```
/** @returns true if eval() is disabled in the current execution context. */
function evalAvailable() {
    try {
        eval('');
        return true;
    }
    catch (e) {
        return false;
    }
}
var EVAL_USEABLE = evalAvailable();

Getting CSP issues on this line of code which is a part ag-grid-enterprise.

**Comment by Wozniaxos** [comment]
For me that change does not do anything, CSP still treat it as eval, can we reopen the issue?

<img width="1276" alt="Image" src="https://github.com/user-attachments/assets/ee66ee4d-4543-4296-8c6c-ffbe76afd758" />

**Comment by AG-Zoheil** [comment]
We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by Wozniaxos** [comment]
But it is in the official documentation that it is also not allowed

<img width="909" alt="Image" src="https://github.com/user-attachments/assets/af152dcb-d41c-4f58-b356-c3690952f75f" />

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src

And this is the change that should've fix it.

https://github.com/ag-grid/ag-grid/commit/c0429fa8db62026d1c0b1cff1469c934d4e202ad
