### ISSUE TITLE
while loading, buttons and rows are still clickable

### ISSUE THREAD

**Issue by chiptus** [ceolter/ag-grid#715]
While loading, and overlay appears, the rows and pagination buttons are still clickable, which can cause a problem with repeated requests to server. Is there any way to disable everything while loading overlay appears?

Thanks for your work!

**Comment by ceolter** [comment]
no there is not. if you want to do this, you can place your own invisible overlay on the grid, preventing mouse clicks.

**Comment by chiptus** [comment]
and what about the pagination buttons?

**Comment by ceolter** [comment]
same
