### ISSUE TITLE
Typescript definitions missing?

### ISSUE THREAD

**Issue by hardcodet** [ceolter/ag-grid#717]
Hi there

First of all: Thanks for that control. Great, great work!

I switched from 2.x to 3.x for a new project, and ran into issues because the type script definitions on definitelytyped (as downloaded by the tsd command) seem to resolve to an outdated version of ag-grid, and I think the package doesn't contain a tsd file for the grid (main.d.ts doesn't seem to be the right thing to reference?).

I had quite a struggle around declarations (`new agGrid.Grid() `vs `new ag.grid.Grid()`) and the `grid.setRowData() `method (which doesn't show up in intellisense on the grid class but the api class. Would be great to get an updated definitions file.

Thanks,
Philipp

**Comment by ceolter** [comment]
why are you using definatly typed? the definitions are packaged with the grid.

i mention this here:
https://www.ag-grid.com/understanding-packaging-for-javascript-typescript-commonjs-and-everything-else/

**Comment by hardcodet** [comment]
Ok... I'm quite new to TS - could you provide some guidance here? If I look at the distribution (and not the sources), the only d.ts file I see is the main.d.ts, but the compiler doesn't seem to like this as an import. This is how I've importing ag-grid 2.x, other libs and my own ts files so far (Visual Studio):

    /// <reference path="../typings/jquery/jquery.d.ts" />
    /// <reference path="../typings/ag-grid/ag-grid.d.ts" />
    /// <reference path="../typings/knockout/knockout.d.ts" />
    /// <reference path="utils.ts" />
    /// <reference path="dtos.ts" />

    class Foo {
    ...
    }

What is the recommended file I'd import here? Did I just overlook something?

Thanks,
Philipp

**Comment by ceolter** [comment]
if you are using node, then you would reference like this:
```
/// <reference path="ag-grid/main.d.ts" />
```
personally i don't use 'reference path=', i have moved onto external modules for typescript. you can see how this is done by looking at the source code of ag-Grid.

also the ng2 example i provide is working (not sure if your using ng2, but the imports work the same), see this file:
https://github.com/ceolter/ag-grid-ng2-example/blob/master/app/app.component.ts
in that file, i'm able to use the library without having to specify the typings. I'm using Intellij, I cannot comment if what I am doing works with other IDE's.

**Comment by ninety7** [comment]
@ceolter I'm using the regular dist/ag-grid.js file but I don't see where the corresponding d.ts file is located. Typescript cannot find the name 'agGrid' so I can call the initialiseAgGridWithAngular1(..) function. Has anyone been able to use TypeScript definitions for us people that don't use external modules?

**Comment by ceolter** [comment]
what happens when you reference the ag-grid/main.d.ts file?

or if using npm, it's node_modules/ag-grid/main.d.ts

/// <reference path='./node_modules/ag-grid/main'/>

**Comment by ninety7** [comment]
Does not work, sorry. Do you have a solution for this?

**Comment by ceolter** [comment]
afraid not. the world of javascript and definitions etc is very messy, beyond the understand of us (we are a small team and are kept busy with the core grid items). the best i can do is explain what we did and why, and hopefully you can work it out.
https://www.ag-grid.com/understanding-packaging-for-javascript-typescript-commonjs-and-everything-else/

**Comment by dan-madaket** [comment]
Are there plans to provide typings for all ag-grid data structures?  There are still some important data structures throughout the project that are not typed. (ie. GridOptions.columnDefs, GridOptions.dataSource)

In a way, typings save documentation time.  The code becomes self-documenting.

Many thanks for what you and your team have done already, this is really impressive stuff, and I obviously understand that you only have so much capacity!

**Comment by ceolter** [comment]
@dan-madaket the typing's for what you ask already exists. i forgot to add them to gridoptions!!! have fixed for next release.

for example check here:
https://github.com/ceolter/ag-grid/blob/master/src/ts/entities/gridOptions.ts#L147

you can see what the typings are for the next release, but you can still use them now, ColDef, ColGroupDef and IDataSource all exists and can be used now.

**Comment by bala1723** [comment]
@ceolter You said "why are you using definatly typed?". Is there something wrong in using DT? 

I have a project that needs aggrid to be supported in power bi and in power bi external libraries should be installed using typings. When I try to do that it creates a DT structure. But when I try to use it is not working. Do I need to "reference" element to point to the "ag-grid/main.d.ts"?

**Comment by bala1723** [comment]
When I change typings/index.d.ts "**/// <reference path="../node_modules/ag-grid/main.d.ts" />**" and import "**import {Grid} from 'node_modules/ag-grid/main';**" it in my visual.ts file. I am getting an error like "**cannot compile modules using option 'out' unless the '--module' flag is 'amd' or 'system'**". 

Then I tried to change the module in typings.json to 'commonjs' but that is causing the power bi module to fail. 

Can you be able to help me on this?

**Comment by firestream99** [comment]
@bala1723 and @hardcodet This exactly what I'm dealing with also. Does anyone have a solutions?

Thx,

**Comment by bala1723** [comment]
@firestream99 have you solved the issue? Are you also working in the Power bi? I solved the issue by using requireJS instead of the typings and imported the aggrid library directly to solve the issue. 

Not sure that will help you but that solved the issue for me and it worked well with the power bi.
