### ISSUE TITLE
Webpack problems with initialiseAgGridWithAngular1

### ISSUE THREAD

**Issue by Mishurin** [ceolter/ag-grid#718]
I am duplicatig a question on the forum https://ag-grid.com/forum/showthread.php?tid=3020

I noticed that using ag-grid and webpack with new 3.3.3 version I can not run agGrid.initialiseAgGridWithAngular1(angular) since agGrid is not defined. My previous configuration for vendors was:
require('lodash');
require('angular');
require('angular-ui-router');
require('ag-grid');
require('ag-grid/dist/styles/ag-grid.css');
require('ag-grid/dist/styles/theme-blue.css');
require('angular-ui-bootstrap');

Actually I noticed that ag-grid.com is using webpack for pages with examples. 
Does anybody have any information how documentation pages configured?
Thank you in advance

**Comment by Mishurin** [comment]
I found out that using 
import * as agGrid from 'ag-grid'  
makes it working 
Then
agGrid.initialiseAgGridWithAngular1(angular);
:)

**Comment by Mishurin** [comment]
Make shure to resolve path to main.js file of node_modules like 
import * as ag from '../node_modules/ag-grid/main';

**Comment by ceolter** [comment]
thanks for the feedback. is there something wrong with one of my examples or documentation that I need to change? or was this just user error? (sorry in advance, so many build tools etc to keep on top of, I can get mixed up)

**Comment by priyanka813** [comment]
@ceolter /all

I am using 
aurelia version : 0.17.0
npm version : 3.10.3
node version : 4.4.7 

Ag-Grid is only rendering when it is  5.2.0 version.
Not with 5.4.0 and 5.3.1 version.
Why it is not supported to latest version 5.4.0 of ag-grid.

**Comment by priyanka813** [comment]
@ceolter 

I am still waiting for your reply.
Please reply early as possible.

I am using 
aurelia version : 0.17.0
npm version : 3.10.3
node version : 4.4.7
aurelia-skeleton-navigation-webpack version : 1.0.1

Ag-Grid is only rendering when it is install with 5.2.0 version.
Not with 5.4.0, 5.3.1, 6.0.0, 6.1.0  version.
Why it is not supported to latest version 6.1.0 of ag-grid ?

**Comment by priyanka813** [comment]
It is working properly after setting height in "`px`",  but why it is not working with "`%`"  in latest version.

**Comment by ceolter** [comment]
@priyanka813 i do not know. % height is working in all my examples where i use it.

others have reported similar - i think it's because for % height to work, the parent contain of your div needs a height. without this, it won't size right. the grid fills the div you give it - so it's the div you give it that isn't sized right.

**Comment by blowsie** [comment]
For those reading this, I took this approach for using ag grid with webpack. 
'Im sure it will be useful to someone
```
import angular from 'angular';
import * as agGrid from 'ag-grid';
import * as agGridE from 'ag-grid-enterprise';

import Common from './common/common';
import Components from './components/components';
import AppComponent from './app.component';

agGridE.LicenseManager.setLicenseKey(
 'xxx'
);
agGrid.initialiseAgGridWithAngular1(angular);

angular
  .module('app', [
    'agGrid',
    Common,
    Components
  ])
  .component('app', AppComponent);
```
