### ISSUE TITLE
Built in date filter needed or custom filters should be reusable

### ISSUE THREAD

**Issue by RobHarrisAZ** [ceolter/ag-grid#719]
I've implemented a date filter using the custom filter example.  I have two columns that both need to be filterable by date independently and the only option I see is to duplicate the date filter code.  After making selections in the first column, when I open the filter ui for the second column, the inputs are already filled out with column 1's filter criteria.  Shouldn't they be independent of each other?

**Comment by RobHarrisAZ** [comment]
It looks like my issue can be resolved by making the $scope that is created and passed into the init function of the filter be isolate.  When they aren't they are sharing the same scope even though they are for different columns.

In FilterManager.prototype.createFilterWrapper:
```javascript
    if (typeof colDef.filter === 'function') {
        // if user provided a filter, just use it
        // first up, create child scope if needed
        if (this.gridOptionsWrapper.isAngularCompileFilters()) {
           filterWrapper.scope = this.$scope.$new(true);//pass in true for isolate scope
        }
        // now create filter (had to cast to any to get 'new' working)
        this.assertMethodHasNoParameters(colDef.filter);
        filterWrapper.filter = new colDef.filter();
    }
```

**Comment by ceolter** [comment]
```
filterWrapper.scope = this.$scope.$new(true);/
```
this creates a child scope, so you shouldn't need isolated. isolated scope causes other issues, such as if your filter wants to access items from the parent scope.

**Comment by RobHarrisAZ** [comment]
I found what I was doing that was causing the bleed over of the scopes.  In my parent scope, I put all of my objects and values on an object named 'vm'.  I was using that same name in the filter.  Making it a different name got back to the filters being independent.  Thanks.
