### ISSUE TITLE
Multiple calls to agGrid.initialiseAgGridWithWebComponents(); causes exception

### ISSUE THREAD

**Issue by milesburton** [ceolter/ag-grid#720]
Less of a bug as I'm sure it was intentional. If the app calls initialiseAgGridWithWebComponents more than once (for example, where grids are componentised) it will trigger an exception.

I've handled this app side for the moment, but it maybe useful to make this idempotent 

Code location
Within agGridWebComponent:
    // finally, register
    document.registerElement('ag-grid', { prototype: AgileGridProto });

**Comment by ceolter** [comment]
in for next release
