### ISSUE TITLE
column header tooltip (title) default value

### ISSUE THREAD

**Issue by mghaly** [ceolter/ag-grid#722]
- in the previous version (version v2.3.1) there was no default value for the column header tooltip, only explicit assignment for headerTooltip. 
in the latest version, the properity headerTooltip is deleted and replaced by title proprty with implicit default value of headerName and cannot be changed through the column definition as you can see in the below code quoted from the latest version
// add tooltip if exists
this.eHeaderCell.title = colDef.headerName;

here is my recommended behavior:
1- provide an API in the column definition to set the title/tooltip
2- if title is not provided, use the headerName as the default value
3- an option to disable the default value in both grid level and column definition level.
this.eHeaderCell.title = colDef.headerTooltip || colDef.headerName;

**Comment by ceolter** [comment]
bug not correct. see example: https://www.ag-grid.com/example.php
the language column has a tooltip, the other columns don't.

**Comment by mghaly** [comment]
ok, sorry i got the point, Thanks.
but for the point number 2, Kindly support it if you can.
2- if headerTooltip is not provided, use the headerName as the default value.

Thanks for your support.

**Comment by ceolter** [comment]
now your making me feel bad by apologising!!!

re point no 2, i can't do that, that's circumstantial, other people would rather no tooltip at all.

however it's easy to work around, you can just provide the tooltip yourself.

**Comment by santosh-k1** [comment]
I try to use tooltipField and headerTooltip in @version v2.3.5 but it's not working .. ?

**Comment by ceolter** [comment]
you can check the old documentation here: https://www.ag-grid.com/archive/2.2.0/

if it's not part of that release, then there is no way.

**Comment by Ram-SR** [comment]
Please tell me a way by which I can add a tooltip to header cells. I added tooltip to body cells using cellRenderer method. I didn't find a way to add tooltip to header cells.

**Comment by pranaygupta08** [comment]
how to apply tooltip to each cell using cellRenderer? can anyone provide reference code

**Comment by nagulapallinaveen** [comment]
Using the below method we can get tooltip on ag-grid header:    
  {
        headerName: 'Policy Number',
        headerTooltip: 'Policy Number'
      },

**Comment by nagulapallinaveen** [comment]
> how to apply tooltip to each cell using cellRenderer? can anyone provide reference code
    this.columnDefs = [
      {
        headerName: 'Policy Number',
        field: 'PolicyNumber',
        width: 150,
        cellRenderer: this.tooltipRenderer,
        filterParams: { apply: true, newRowsAction: 'keep', clearButton: true },
        headerTooltip: 'Policy Number'
      }];

  private tooltipRenderer(params) {
    if (params.value === undefined || params.value === null) {
      return 'N/A';
    }
    return '<span title="' + params.value + '">' + params.value + '</span>';
  }

**Comment by DroidUnknown** [comment]
can we make this tooltip html=true or similar? I have custom styled information that i want to display on the tooltip of header.
