### ISSUE TITLE
Problem with column width when using sizeColumnsToFit with setColumnVisible

### ISSUE THREAD

**Issue by buremba** [ceolter/ag-grid#723]
When I toggle the visibility of a column and call sizeColumnsToFit, the width of column that is toggled keeps getting smaller in each toggle action. I expect ag-grid to preserve the initial width of column when I enable visibility again.

Here is a test case: https://jsfiddle.net/p0c2uxah/  Click toggle button repeatly and you will see that the width of age column will keep getting smaller after each turn.

**Comment by ceolter** [comment]
can't fix this, it's just how it works.

the grid works with what you give it. at the time of calling 'sizeColumnsToFit', then it reduces (or increases) all columns based on their CURRENT width, not their initial width. i could change it, but then that will cause a bug in the other direction.

the way for you to get around this is to reset the widths before making the call to sizeColumnsToFit.

columnApi.resetState(); // however this resets everything, including visibility, pinned etc
columnApi.sizeColumnsToFit();

if you don't want everything reset, then call setState and only provide widths
