### ISSUE TITLE
Rendering cells from data nested in row

### ISSUE THREAD

**Issue by noherczeg** [ceolter/ag-grid#726]
Hey!

I'm struggling with the following issue:

In our case each row is an object it self, and has a list attribute which contains the cells inside it. My problem is that when I define a seemingly proper cellRenderer() then in the rendered table, only the cells inside the last header are rendered in each column.

My row model looks like this:
```
{
    key: 'r1',
    expressions: [
        {id: 1, x: 'etc...'},
        {id: 1, x: 'etc...'}
    ],
    ...
}
```

I went into debugging mode in Chrome, and checked, and every valueGetter() retrieves the proper cell, that works fine. Also every cell renderer gets the proper cell, but the table it self renders only cells for the last column.

Sample image (the first table is hand crafted, the bottom one uses ag-grid, hader labels differ, but it's just obtained from a different attribute that's all):
![ag-grid_column_bug](https://cloud.githubusercontent.com/assets/1084847/13176923/030ca59e-d716-11e5-896f-21b48b46310a.png)

The code:
```
this.lodash.forEach(this.dtData.headers, function (header) {
	var columnDef = this.judoGridColumn.fromJson({
		headerName: header.key + ' (' + header.type.value + ')',
		metaId: null,
		colId: header.id
	});
	columnDef.valueGetter = function (params) {
		return vm.lodash.find(params.data.expressions, {header: {id: params.colDef.colId}});
	};
	columnDef.cellRenderer = function(params) {
		params.$scope.ruleExpression = params.value;
		return '<div ng-include="\'modules/framework/table/table-ow/expression-cell.template.html\'"></div>';
	};
	res.push(columnDef);
}, this);
```

Has anyone got into this before?

Thanks in advance!

**Comment by noherczeg** [comment]
It's almost as if you would be using a for loop incorrectly somewhere: http://www.mennovanslooten.nl/blog/post/62

**Comment by jonrimmer** [comment]
The problem is the line:
```js
params.$scope.ruleExpression = params.value;
```

From [the documentation](https://www.ag-grid.com/best-angularjs-data-grid/index.php):

> Each cell within the row does not get a new child scope. So if placing item inside the child scope for the row, be aware that it is shared across all cells for that row. If you want a cell to have it's own private scope, consider using a directive for the renderer that will introduce a new scope.

**Comment by noherczeg** [comment]
My bad, thank you @jonrimmer !

**Comment by noherczeg** [comment]
@jonrimmer What is the proper way of adding the values in question to to said directive? I created a directive with isolated scope but I still keep getting the same last column data on every row.

How is it possible to pass them if I can't use .$scope?

```
columnDef.cellRenderer = function(params) {
	params.$scope.cellExpression = vm.cellGetter(params, header);
	params.$scope.cellOperators = vm.dtData.operators;
	return '<expression-cell operators="cellOperators" expression="cellExpression"></expression-cell>';
};
```

**Comment by jonrimmer** [comment]
@noherczeg Because the scope is shared, your only option to supply configuration to the directive is via text attributes. One simple way to do it would be to have the valueGetter return the index of the expression the column is for, and have the cellRenderer supply this as an index parameter to your directive:

```js
vm.gridOptions.columnDefs = this.dhHeaders.map(header => ({
    headerName: header.key + ' (' + header.type.value + ')',
    metaId: null,
    colId: header.id,
    valueGetter: params => params.data.expressions.findIndex(exp => exp.header.id == params.colDef.colId),
    cellRenderer: params => `<expression-cell index="${ params.value }"></expression-cell>`;
});
```

The directive controller would have to lookup the expression on the $scope's data property, something like this:

```js
function ExpressionCellController($scope, $attrs) {
    const vm = this;
    const expression = $scope.data[$attrs.index];
    ...
}
```

**Comment by noherczeg** [comment]
@jonrimmer Thanks for your cooperation! Thanks to you I managed to make it work.
