### ISSUE TITLE
Minor bug in angular getting-started example

### ISSUE THREAD

**Issue by mischahaenen** [ceolter/ag-grid#7307]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
1. Start Getting Started: https://www.ag-grid.com/angular-data-grid/getting-started/
2. Fail because rowData is defined as a type but it should be the value (= not :)

Current behaviour.
[Expected behaviour. If possible back this up with our docs/examples if possible](https://github.com/ag-grid/ag-grid/blob/b4884a80f5c31fb1db3f2d540d65fc2e2c326636/grid-packages/ag-grid-docs/documentation/doc-pages/getting-started/index.md?plain=1#L103)

**Current behavior**
The example in getting started does not work.
https://github.com/ag-grid/ag-grid/blob/b4884a80f5c31fb1db3f2d540d65fc2e2c326636/grid-packages/ag-grid-docs/documentation/doc-pages/getting-started/index.md?plain=1#L103

**Expected behavior**
rowData should be defined as a value (= instead of :)

* **AG Grid version:** 31.0.0

* **Browser:** Independend

* **Language:** [all]

**Comment by StephenCooper** [comment]
Thanks! I have fixed this now but it would go live until we next push an update to the docs. I have closed the PR as it wasn't the right location. 

Hope you like the new getting started guide!
