### ISSUE TITLE
Event gridSizeChanged wasn't sent when the grid grows

### ISSUE THREAD

**Issue by romain-cadet** [ceolter/ag-grid#732]
The event gridSizeChanged wasn't sent when the grid grows except in full size.
This issue is present at least since 3.2.0.

**Comment by otabekgb** [comment]
I can confirm this issue for version 3.3.3. It only fires when shrinks, not when stretches.

**Comment by ceolter** [comment]
i go to main demo page, turn on console, then whenever grid changes (shrinks or grows) the event is fired.
