### ISSUE TITLE
Can not run project tests using grid version 3.3.0

### ISSUE THREAD

**Issue by noherczeg** [ceolter/ag-grid#734]
I can not run our unit test with Karma since ag-grid 3.3.0. 

Karma produces the following error (**applyToTag(styleElement, obj)** method):
```
TypeError: 'undefined' is not an object (evaluating 'obj.css')
at http://localhost:9876/base/bower_components/ag-grid/dist/ag-grid.js?e9b234d5ba7ffe29ab52a98bb8b14b9978a97f75:13402
```
If I go into test debug mode in webstorm then the "obj" param gets its values. Seems as if it needs just a little bit of time to boot up properly. Is there a workaround for this? The grid is working fine in the app it self, but I can not merge my feature unless test are runnable again.

**Comment by AkosLukacs** [comment]
Maybe related: v.3.3 also breaks module-less typescript projects (yay for somewhat-legacy apps). The actual error I get when upgrading to 3.3.3 and changing the d.ts file to `/bower_components/ag-grid/dist/lib/grid.d.ts` is: `Cannot compile modules unless the '--module' flag is provided.` file: `bower_components\ag-grid\dist\lib\entities\rowNode.d.ts`

**Comment by noherczeg** [comment]
My problem still exists in version 3.3.3

**Comment by ceolter** [comment]
@noherczeg i don't know what is happening here, nobody else has reported it. what line of code is causing the problem?

@AkosLukacs ah crap. is turning on --module flag an issue? using modules is the future, and what the other 'big projects' appear to be doing.

**Comment by noherczeg** [comment]
@ceolter It's https://github.com/ceolter/ag-grid/blob/master/dist/ag-grid.js#L13532

**Comment by AkosLukacs** [comment]
@ceolter Actually working on moving to full typescript and replacing the
current bundling-stuff with "proper" modul system, but that takes time.
Priority of new features is usually higher than the priority of clean up
that may break working stuff...

**Comment by noherczeg** [comment]
It's odd though, can not find a single line of matching functions in the /src folder.

**Comment by ceolter** [comment]
@noherczeg that line of code is not ag-Grid, it's the css style loader. the function applyToTag is put in during the webpack stage, so i'm guessing it's to do with the webpack loader 'style-loader'

can you use the non-css version of ag-Grid (dist/ag-grid.noStyle.js) for your tests?

alternatively can you google this problem with regards style-loader and see if a solution is there?

**Comment by ceolter** [comment]
@AkosLukacs 
can you not just rung on --module flag?

**Comment by noherczeg** [comment]
@ceolter Will try with the non styled version right now.

**Comment by ceolter** [comment]
right, i need to start working, will be leaving github issues for rest of the day (sorry, otherwise i get stuck here for half a day)

**Comment by noherczeg** [comment]
Problem solved by the following:
- using dist/ag-grid.noStyle.js
- including dist/styles/ag-grid.css

This way the grid has it's proper format, and works. Tests run as well.

Thanks @ceolter !

**Comment by noherczeg** [comment]
@AkosLukacs If your problem still exists, please open another ticket for it. I didn't wanted to keep this one open because it would be misleading.

**Comment by AkosLukacs** [comment]
@noherczeg Sorry for disturbing your issue in the first place. Thought these are related somehow...

@ceolter Surprisingly, looks like it's working. Just expected that everything would just blow up...

**Comment by noherczeg** [comment]
@AkosLukacs No problem! :+1:
