### ISSUE TITLE
ForPrint : error with pinned column

### ISSUE THREAD

**Issue by dstackowiak** [ceolter/ag-grid#735]
Hi,

You can find an example here : https://jsfiddle.net/3fpkz992/2/

The use case is :
- forPrint: true
- a "simple" column (ie. with no children) is pinned (pinned: 'left')  

The error : `Uncaught TypeError: Cannot read property 'appendChild' of undefined` `ag-grid.js:7357`

**Comment by ceolter** [comment]
fixed. will be in next release.

**Comment by dstackowiak** [comment]
Thanks :) :+1: 

Meanwhile, a workaround is to programmatically disable the  pinned column if forPrint is true
