### ISSUE TITLE
Virtual Scrolling - Performance Consideration

### ISSUE THREAD

**Issue by roy46** [ceolter/ag-grid#741]
Hi,

 Firstly, great product all my grid worries have been resolved with this project :). This isn't really an issue and more of a consideration, which you may have already tried but I wanted to check. 

 So the question: 

 I have been looking through some of the source and from what I gather the rows are destroyed and recreated during scrolling. I was wondering if you have tried row/cell reuse. Whereby you would replace the innerHtml of the cells that are currently in the DOM?

If the rows weren't recreated each time you could take advantage of translate3D() or more specifically translateY() to position the rows in the container. Thus enabling some hardware acceleration and potentially a less intensive repaint.

 I can see that this could be quite a fundamental change as the RowRenderer builds a row as a Html string. Admittedly I can see the advantage of doing this. Accessing the DOM once per row in order to render it may be faster than once per cell of a row already in the DOM. Still I was wondering if this had been considered/tested?

**Comment by ceolter** [comment]
yup i've considered this. see here:
https://www.youtube.com/watch?v=gNhPeLCBbE0

btw, I have taken the virtual DOM out of my upcoming release, so if you want to try it yourself after that release, be my guest! however i'm not going to spend time on this as i don't see the performance as an issue. my next things to do with performance is column virtualisation (if user has say 100 cols) and possibly (very possibly, not decided) a canvas 2d version of the grid.

but yup, as you ask, i've considered and coded and tested what you say - (although i didn't use the translate function, no sure if that makes a big difference)

**Comment by roy46** [comment]
Cool. Thanks for the reply. interesting talk. 

Thinking about it I think the translate would only have significant effect if it was an animation.

In regards to the new release... why the change from virtual DOM given what you said in the video?

**Comment by ceolter** [comment]
```
 why the change from virtual DOM given what you said in the video
```
because it only makes a significant difference with IE, however for IE I also use the delayed scrolling, so it's two solutions covering the same problem, only one solution is needed. if using Chrome (which most people are that are using the grid) then it makes pretty much no difference.

on a benefit side, the virtual dom complicates things, so with it gone, the code base is cleaner, easier for me and you (as your cellRenderers are working with a real dom node now)

btw, the new IE in Windows 10 (called Edge) is able to handle the grid fine without the delayed scrolling.

**Comment by kirillonufreinko** [comment]
From the end-user point of view delayed scrolling looks quite inconsistent. It would be really cool to add at least optional support for virtual scrolling.
