### ISSUE TITLE
headerHeight issue

### ISSUE THREAD

**Issue by axelex** [ceolter/ag-grid#742]
Hello,

If I set a default headerHeight, and then set groupHeaders to true, the height of the header should double or triple it's height depending on how many groups I'm having, instead it's doing everything depending on it's default value of 25 and table body covers the text from the header because of that.
I've set for my table the headerHeight of 45 and it's not behaving correctly.
Can you give me a tip of how should I handle this or make some adjustments to the code?

Thanks!

**Comment by Wingie** [comment]
you can use
gridOptions.headerHeight = 50;

**Comment by ceolter** [comment]
latest version of grid does as you expect. sounds like your using an old version.

**Comment by axelex** [comment]
Yes, I was using an older version, but that is because of the drastically changes that are made from a version to another... Now because I upgraded to the last version nothing works on my app... I made an upgrade to 3.2.0 but still I have to remake the code used for handling grid data...

**Comment by tahirawais1** [comment]
my headerHeight is changing but its line-height is 56 default and this is not what i want how can i over write the line-height?
