### ISSUE TITLE
Codemod not applying the changes.

### ISSUE THREAD

**Issue by melon2504** [ceolter/ag-grid#7423]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
I'm using Ag Grid as part of a reusable library which I install as a dependency in my react projects.
In the component library, I have updated ag grid packages to 31.0.0 and then ran the following command as per docs
_npx @ag-grid-community/cli@31.0 migrate_

https://www.ag-grid.com/react-data-grid/upgrading-to-ag-grid-31/#codemods

It processed all the files but didn't make any changes to files with Ag Grid code.
![IMG_20240111_154943](https://github.com/ag-grid/ag-grid/assets/77911765/f7dfc457-676e-45aa-aae4-a9574e3f77b9)
![IMG_20240111_154957](https://github.com/ag-grid/ag-grid/assets/77911765/03b703c8-b9e2-440c-bc45-355794327e3b)

Kindly assist.

* **AG Grid version:** 
30.2.0

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
React 18.2.0 + TypeScript 4.9.5

**Comment by timkendrick** [comment]
Thanks for the bug report. I'll need to know some more details about your use case to help fix your issue.

Can you copy/paste a block of source code that you would have expected to be transformed by the codemod, but was not?

(Bear in mind the codemod only transforms source files that use deprecated features from the [breaking changes in the v31 release](https://www.ag-grid.com/react-data-grid/upgrading-to-ag-grid-31/#breaking-changes), so if you aren't currently making use of any of those APIs your source code will be unaffected)
