### ISSUE TITLE
how can i abort(stop propagate)  grid's sort event in beforeSortChanged?

### ISSUE THREAD

**Issue by changchengqin** [ceolter/ag-grid#744]
when i use follow event beforeSortChanged and afterSortChanged ,these event's parameter which is object type without any properties.
![image](https://cloud.githubusercontent.com/assets/3336443/13387802/6a89038e-def5-11e5-87ca-da5ac6fc8afc.png)
![image](https://cloud.githubusercontent.com/assets/3336443/13387813/7e55102e-def5-11e5-9758-76939f40ecab.png)
how can i abort(stop propagate)  grid's sort event in beforeSortChanged?

**Comment by ceolter** [comment]
you cannot.
