### ISSUE TITLE
Showing "Loading.." text while waiting for server to return rows during virtual pagination + infinite scroll

### ISSUE THREAD

**Issue by Wingie** [ceolter/ag-grid#745]
right now, there is only blank rows being displayed when the user scrolls over after the last row has loaded..
the loading rows text doesnt show at all..
this is the gridoptions that i have
```
$scope.gridOptions = {
            columnDefs: [],  // will get filled in on first call from server
            enableFilter: true, 
            rowData: null,
            rowSelection: 'multiple',
            rowDeselection: true,
            enableColResize: true,
            angularCompileRows: true,
            rowHeight:65,
             virtualPaging: true,
             rowSelection: 'multiple',
             suppressMenuHide: true,
             // suppressRowClickSelection: true,
            enableServerSideSorting: true,
            enableServerSideFilter: true,
            headerHeight:50,
            overflowSize:5,
            maxConcurrentRequests:2,
            isExternalFilterPresent: true,
            doesExternalFilterPass: doesExternalFilterPass
            // datasource: $scope.dataSource
        };
```

**Comment by ceolter** [comment]
that's by design. the  virtual pagination doesn't show loading, as you can be viewing one portion of data, while another portion is loading in the background for some data not on the screen.

**Comment by Wingie** [comment]
hmm,
i tried controlling it  by  overflowSize:5,
is it possible for the virtual pagination to always keep on fetching data?
essentially i scroll down and when i reach the last elements, the call is sent to the server for the next page,
can we send the call for the next batch while i'm halfway through the element list?

**Comment by ceolter** [comment]
not directly. however you could code something into your datasource to eager fetch blocks.

**Comment by Wingie** [comment]
Yeah? Is there a way I can control the eager fetching from the getRows()?

**Comment by ceolter** [comment]
just based on the requests, so if you are called for page 10, then also grab pages 11 and 12 and keep them cached in your datasource. if the grid calls for 11 or 12 before they come back, store the grid callback somewhere and call it when 11 or 12 returns.
