### ISSUE TITLE
selectNode api method not working as expected

### ISSUE THREAD

**Issue by ninaneter** [ceolter/ag-grid#746]
Hi,

i'm trying to mark a row as selected once the grid is ready.
for some reason this doesn't work. 
the model seems to be correct, but the row is not marked in the ui
this is my code:
[https://jsbin.com/fifiluqahe/edit?html,js,output](url)

is this the right way to set a selected row?

thanks!

**Comment by ceolter** [comment]
i got errror 404 when i clicked on your link.

**Comment by ninaneter** [comment]
sorry, please try again:
https://jsbin.com/fifiluqahe/edit?html,js,output

**Comment by ceolter** [comment]
this is NOT what you do ```his.api.selectNode(rowData[1]);```

the nodes are not rowData, each rowData item gets wrapped into a node.

see https://www.ag-grid.com/angular-grid-model/index.php
