### ISSUE TITLE
api.setFocusedCell required colId but searches for column by index

### ISSUE THREAD

**Issue by roy46** [ceolter/ag-grid#747]
Hi,

 Since I upgraded to verison v3.3.3 I have noticed that the call to the `setFocusedCell` function on the api requires the colId, which is used by `GridPanel.prototype.ensureColumnVisible`. However, the nested call to `RowRenderer.prototype.setFocusedCell` requires the colIndex:

`var column = this.columnModel.getAllDisplayedColumns()[colIndex]);`

 Is it possible to add a fix for this? If i'm am using the api incorrectly please let me know. This is my use case (after selecting a row I want to focus on the cell below):

```
onSelectionChanged: function () {
    var that = this;
    var currentCell = that.api.getFocusedCell();
    that.api.setFocusedCell(currentCell.rowIndex + 1, currentCell.colId);
}
```

This was working in previous versions with the following:

```
onSelectionChanged: function () {
    var that = this;
    var currentCell = that.api.getFocusedCell();
    that.api.setFocusedCell(currentCell.rowIndex + 1, currentCell.colIndex);
}
```

n.b. colIndex was an available property on the currentCell in previous versions.

Thank,

**Comment by ceolter** [comment]
this is reworked (and fixed) in the latest, so fix will be included in the next release.
