### ISSUE TITLE
Bug: suppressNoRowsOverlay forces the grid to display loading message on empty list

### ISSUE THREAD

**Issue by noherczeg** [ceolter/ag-grid#749]
Given when:
- suppressNoRowsOverlay is set to true
- there is a custom dataSource defined
- the datasource returns an empty list

The Loading message gets stuck.

Plunker sample: http://plnkr.co/edit/To95etEiENmSh3y6fP5b?p=preview

Grid version is 3.3.3 (noStyle), but I tried with all version above 3.3.0 and the defect is there also.

**Comment by noherczeg** [comment]
On my local project the following seemingly fixed the issue:

https://github.com/ceolter/ag-grid/blob/master/src/ts/grid.ts#L557

```
if (rowData && Array.isArray(rowData)) {
	this.hideOverlay();
	if (rowData.length === 0 && !this.gridOptionsWrapper.isSuppressNoRowsOverlay()) {
		this.showNoRowsOverlay();
	}
}
```

**Comment by ceolter** [comment]
thanks. i've it fixed now locally. will be in next release.
