### ISSUE TITLE
[FEAT] Dynamic Row Attributes

### ISSUE THREAD

**Issue by ftorghele** [ceolter/ag-grid#752]
It would be great if there were not only the possibility to dynamically add classes or styles but also attributes to the rows.

I need it to assign a drag and drop directive (angular) to each row so I can drag the row out of the grid for further use.

I already implemented it and will send you a pull request.

**Comment by ceolter** [comment]
i have just added 'processRowPostCreate' callback, will be in next release. this will give you access to each row right after it's put into the dom, allowing you to add attributes or do whatever else trickery you want.
