### ISSUE TITLE
Support subgrid

### ISSUE THREAD

**Issue by Feiyang1** [ceolter/ag-grid#755]
I found a year old thread in the forum requesting for this feature, but it doesn't seem to be implemented yet. It is the last feature I need to start using aggrid in my project. 

The use cases can be:
1. expanding the master row to see the detail. the detail can be in a grid with different headers, or just a paragraph, an image or anything else. User should be able to customize the detail panel. 
2. clicking on a cell to see details of data pertaining to that cell.

In general, I would like to have the ability to show a detail panel below the master row and be able to customize what goes into the detail panel.
something like this: http://dhtmlx.com/docs/products/dhtmlxGrid/samples/07_extended_modes/03_pro_subgrids.html

thanks !

**Comment by ceolter** [comment]
this is a very big change an unlikely to get done unless someone funds it.

**Comment by ceolter** [comment]
done.
