### ISSUE TITLE
Mixing grouped and non-grouped columns not working

### ISSUE THREAD

**Issue by SamD** [ceolter/ag-grid#757]
Do you have a simple working example of mixing non-grouped and grouped columns (has children property) ? I am upgrading from 1.7 where the group property was used and haven't been successful in my testing to get both working. If I remove the grouped column my non-grouped will show, as soon as I add it they do not. There is an element where the header should be but its text is empty where I suspect there should be an inner div containing the label something like the group case?

```html
<div class="ag-header-group-cell ag-header-group-cell-no-group" style="width: 82px;"><div class="ag-header-cell-resize"></div></div>
...
<div class="ag-header-group-cell ag-header-group-cell-with-group" style="width: 400px;"><div class="ag-header-cell-resize"></div><div class="ag-header-group-cell-label"><span class="ag-header-group-text">builders</span></div></div>
```

**Comment by ceolter** [comment]
the examples are just what i have online in the docs. i'm pretty confident the grid is working as lots of people are using the groups. ps this isn't an issue with the grid so closing, github issues just for things wrong with the grid.

**Comment by SamD** [comment]
Yeah thanks I figured out the issue it was tied to another which I guess wasn't reported but later fixed.

I believe it was a 3.x version where the grouped columns were showing as children of each other instead of just one level so basically it ended up where if you had 2 columns grouped the 2nd column in the DOM ended up being a child of the 1st. With a later update this went away.
