### ISSUE TITLE
[filter] Hide search box in the default filter for checkboxes.

### ISSUE THREAD

**Issue by anupmalhan** [ceolter/ag-grid#759]
I need to know if there is any possibility to hide the search box present in the filter.Is there any property available which could be set to false so that the text box for search in the filter shall disappear OR we need to write custom logic ( custom filter ) for the same.

**Comment by ceolter** [comment]
currently not a feature.

**Comment by anupmalhan** [comment]
Ok, Thank you.

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-110

**Comment by makinggoodsoftware** [comment]
There is a new filterParam for the setFilter. suppressMiniFilter, if set to true, the search box won't be displayed. This will be available in the next release
