### ISSUE TITLE
PopupService.ts should be renamed

### ISSUE THREAD

**Issue by maxired** [ceolter/ag-grid#765]
Hi,

when using a case sensitive file system, the import of popupService in [grid.ts](https://github.com/ceolter/ag-grid/blob/afa20562e5ec271e2080aec5acb1f19ecc299c6c/src/ts/grid.ts#L27) fails, because the [PopupService.ts](https://github.com/ceolter/ag-grid/blob/afa20562e5ec271e2080aec5acb1f19ecc299c6c/src/ts/widgets/PopupService.ts) should be renamed `popupService.ts`

**Comment by ceolter** [comment]
thanks!

**Comment by ceolter** [comment]
fixed.

**Comment by maxired** [comment]
@ceolter thanks. Any plan for releasing a new version ?

**Comment by ceolter** [comment]
yes. next two days. i've a few cleanup issues since the last release, including this.
