### ISSUE TITLE
columnApi.setColumnState() should return something when failing

### ISSUE THREAD

**Issue by Wykks** [ceolter/ag-grid#766]
Currently, `setColumnState()` log a message `ag-grid: column coldef not found` but instead of a console warning, it would be more usefull if this function return something else.
https://github.com/ceolter/ag-grid/blob/52863382b095aa722ee7e9f7240a64fab3c5d7fc/src/ts/columnController/columnController.ts#L624

**Comment by ceolter** [comment]
not sure. insn't this a bug in your code that your calling it with invalid col id's?

 . . . . . the other option is i through an exception, but i know there will be someone out there who gets upset that it breaks under this scenario, trying to set columns that don't exist on purpose for some reason, eg if they are reading in col ids' from a stored user preference and the col they are interested in doesn't exits.

otherwise, if it is a use case i am not thinking of, can you explain?

**Comment by Wykks** [comment]
If the state is stored somewhere and the initial column def is updated (e.g code update), it would be usefull to detect that the new col def and the user stored state doesn't match and then override the old state.
As a matter of fact, storing a column version can also solve this problem too. But it would require to update the column version each time column defs are changed which is not ideal.

**Comment by ceolter** [comment]
what about a validate method, you pass in a list of col id's, it returns true if they all exist?

or even better, you pass in a list of colIds, it returns back all the cols it finds that are missing?

that would then help your console error message.

it would also be reusable anywhere your code needs this, not just when setting columns. thoughts?

**Comment by Wykks** [comment]
Yes, that's what I've done. But this logic is already done in `setColumnState` (which cause a console.warn). I thinks it's better to have this test in ag-grid only instead of doing it 2 times in a row.

**Comment by ceolter** [comment]
ok convinced! i've just changed it. now this method returns false if one or more cols not found

**Comment by Wykks** [comment]
Cool thanks ! :)

**Comment by Wykks** [comment]
The change isn't correct because it leads to `TypeError: Cannot read property 'setVisible' of undefined` since you removed the return.
https://github.com/ceolter/ag-grid/blob/master/src/ts/columnController/columnController.ts#L629

**Comment by ceolter** [comment]
fixed. again. sorry. will be in next release (but might be a while, i've a lot going in and trying to stop with the delta releases)

**Comment by Wykks** [comment]
Again, the fix is not correct : https://github.com/ceolter/ag-grid/commit/275125592f312bc37a0a18f14573435ebfe5e1ae
`return success;` or `return false;` but not just `return;` :smile:

**Comment by ceolter** [comment]
@Wykks i'm not sure if you commented on this or not - github gave me a notification you think the error isn't fixed but i'm not sure if you did....

**Comment by Wykks** [comment]
Yes my bad, sorry !
