### ISSUE TITLE
Adding set for coloumnDef field

### ISSUE THREAD

**Issue by Am1rr3zA** [ceolter/ag-grid#767]
Hi @ceolter,

Could you please add support so instead of having one on one mapping between field and column def  we could have array/set of fields.
let's say in response we have array of objects and in each object either we have call_id or ticket_id right now we need to transform them when we get the response to the same key so we can use them with ag-grid, I think it would be nice if we have the option so say ag-grid maps this field either with call_id or ticket_id.

Something like this 
```
var coldef = [{
    displayName: 'ID',
    field: ['call_od', 'ticket_id']
}]
```

**Comment by ceolter** [comment]
you can do that with valueGetter's:

```
var coldef = [{
    displayName: 'ID',
    field: 'call_od', // this will be ignored for rendering, but if you update the value, it will get stuck here
    valueGetter: 'data.call_od ? data.call_od : data.ticket_id'
}]
```
