### ISSUE TITLE
Number filter api not working with angularjs

### ISSUE THREAD

**Issue by sasikumar25** [ceolter/ag-grid#768]
This is my code:

var columnDefs = [
     {headerName: "Age", field: "age", width: 90, filter: 'number'
];

$scope.filterByCountry = function(value)
{
		var ageFilterApi = $scope.gridOptions.api.getFilterApi('age');
		agefilterApi.setType(1);
		agefilterApi.setFilter(value);
                $scope.gridOptions.api.onFilterChanged();
}

$scope.gridOptions = {
    columnDefs: columnDefs,
    rowData: null,
    enableFilter: true,
    enableSorting: true
};

when i enter the number in    text filed  i'm expecting this grid will filter by given value but i get nothing 
all value are gone only header alone displaying.
Text filter is working fine with out any issue. did i missed anything ?

**Comment by sasikumar25** [comment]
Sorry guys it is my mistake only. before filtering by age i did some filtering on other fields. it is working fine thanks much.

**Comment by ceolter** [comment]
thanks for posting your update.
