### ISSUE TITLE
Trying to use global event object ? 

### ISSUE THREAD

**Issue by maxired** [ceolter/ag-grid#769]
Hi,

in https://github.com/ceolter/ag-grid/blob/ec08a09ff499d95506f6184815d21eb34e0f378a/src/ts/rendering/renderedCell.ts#L487,
looks like you are trying to use the global `event` object, or maybe something with should be given in parameter.

Anyway, in Firefox and others browsers, there is no global `event` object and it lead to a JS error.

Prior to https://github.com/ceolter/ag-grid/commit/507325860ac0df3a945521d4de11c7f6d6db2e7f , 
there was always a provided `event` object given in arguments before calling `this.createEvent(event, this);`

**Comment by ceolter** [comment]
thanks. will be releasing later today all going to plan. this bug slipped in during my refactoring.
