### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by maxired** [ceolter/ag-grid#770]
Hi,

when creating an issue, github now show 

> Please review the [guidelines for contributing](https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md) to this repository.</div>

Content of `CONTRIBUTING.md`is radically different from what is inside `readme.md` and so should be updated to reflect current state of the project.

**Comment by ceolter** [comment]
thank you.
