### ISSUE TITLE
Allow custom filtering on Set filter - allow user to provide filter function

### ISSUE THREAD

**Issue by mario-jerkovic** [ceolter/ag-grid#771]
My problem is that I am using server side pagination, and server side filtering.
The filtering popup from (example: Assigned accounts) need to be filled with all possible account because on the client side I have only 50 rows.

This way I create and array that contains ids of all accounts.

``` javascript
const assignedFilter = this.props.rootField.accountConnection.edges.map((item) => item.node.id),
```

Column definition for assigned author is like in the snippet below.
Inside filterParams the cellRender function is searching for each id corresponding account fullName and its displaying them correctly on the filter popup, but the problem is while the popup has account fullnames, the search box is inside filter popup will only work if I search for the id's I have placed inside the assignedFilter variable. So my question is, is there any way to search for account fullname's even if they are set trough cellRender function.

``` javascript
{
                headerName: 'Assigned',
                field:"node.assignedAccount.fullName",
                suppressMenu: false,
                filterParams: {
                    cellRenderer: (params) => {
                        const data = this.props.rootField.accountConnection.edges;
                        for (let index = 0; index < data.length; index++) {
                            if (data [index].node.id === params.value) {
                                return `${data [index].node.fullName}`;
                            }
                        }
                    },
                    values: assignedFilter,
                    newRowsAction: 'keep' ,
                    apply: true
                }
            }

         //When user chooses an account and presses apply I am getting this filterModel
         /*
            {
                node.assignedAccount.fullName: ["YWNjb3VudDo0"]
            }
           */

```

The main reason i am asking is that I want to get the id of the account that user has picked for filtering.

**Comment by ceolter** [comment]
nope. but good idea. will stick in on my (very long) list.

**Comment by ceolter** [comment]
going back through this - and i believe you can achieve this now with keyCreator. please check keyCreator here:
https://www.ag-grid.com/javascript-grid-set-filtering/

basically the key is what should be used for the comparison. then if you want to render something different in the set filter (not the key), then use the cellRenderer for the set filter.
