### ISSUE TITLE
Angular import 'ag-grid-enterprise' not working

### ISSUE THREAD

**Issue by ghost** [ceolter/ag-grid#7719]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Added import 'ag-grid-enterprise'; to my angular application as indicated in the guide. 
I added it to both app.component and project.config, neither work

**Expected behavior**
It's suppose to work, but I am getting message : 
```
ag-grid-community.auto.esm.js:799  AG Grid: unable to use AG Grid 'filter' component: agSetColumnFilter as the SetFilterModule is not registered. Check if you have registered the module:
           
    import { ModuleRegistry } from '@ag-grid-community/core';
    import { SetFilterModule } from '@ag-grid-enterprise/set-filter';
    
    ModuleRegistry.registerModules([ SetFilterModule ]);

For more info see: https://www.ag-grid.com/javascript-grid/modules/
```

**Please tell us about your environment:**
Angular 17.10
Windows 10

* **AG Grid version:** X.X.X
Ag-Grid Enterprise 31.1.1

* **Browser:**
Edge 122.0.2365.80

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by avrahamappel-humi** [comment]
Also seeing this. I am trying to set up using packages and do not expect to be seeing this warning

Angular 17.2.1
Ag-Grid 31.0.2
Chrome 122.0.6261.129
MacOS Sonoma

**Comment by HKshaligraminfotech** [comment]
main-routing.module.ts:19 AG Grid: unable to use AG Grid 'filter' component: agSetColumnFilter as the SetFilterModule is not registered. Check if you have registered the module:
           
    import { ModuleRegistry } from '@ag-grid-community/core';
    import { SetFilterModule } from '@ag-grid-enterprise/set-filter';
    
    ModuleRegistry.registerModules([ SetFilterModule ]);

For more info see: https://www.ag-grid.com/javascript-grid/modules/

**Comment by potnuruvarun** [comment]
main-routing.module.ts:19 AG Grid: unable to use AG Grid 'filter' component: agSetColumnFilter as the SetFilterModule is not registered. Check if you have registered the module:
           
    import { ModuleRegistry } from '@ag-grid-community/core';
    import { SetFilterModule } from '@ag-grid-enterprise/set-filter';
    
    ModuleRegistry.registerModules([ SetFilterModule ]);

For more info see: https://www.ag-grid.com/javascript-grid/modules/

Angular 17.10
"@ag-grid-community/angular": "^32.1.0",
    "@ag-grid-community/client-side-row-model": "^32.1.0",
    "@ag-grid-enterprise/set-filter": "^32.1.0",
    "@angular/animations": "^17.3.12",
    "@angular/cdk": "^17.3.10",
    "@angular/common": "^17.2.0",
    "@angular/compiler": "^17.2.0",
    "@angular/core": "^17.2.0",
