### ISSUE TITLE
use multiple columns for ordering

### ISSUE THREAD

**Issue by jogibear9988** [ceolter/ag-grid#773]
Maybe it will be possible to order by multipe columns (also using server side sorting). And display it like this? 
<img width="399" alt="bildschirmfoto 2016-03-10 um 21 29 44" src="https://cloud.githubusercontent.com/assets/364896/13683492/3b38546c-e707-11e5-93e3-2578543c399c.png">

**Comment by ceolter** [comment]
you an already order by multiple columns. hold down shift while clicking the column header.

**Comment by jogibear9988** [comment]
Yes, ok! But we don't see the order!

**Comment by ceolter** [comment]
yup, having this nicer is on my todo list.
