### ISSUE TITLE
How to reload localeTextFunc

### ISSUE THREAD

**Issue by Rogerio-Soares** [ceolter/ag-grid#775]
Hi!

I have an application using angular and translation.
I whant to trigger ag-grid to apply again the localeTextFunc when my user change his culture

Is there a way accomplish that ?

`
    var listener = $rootScope.$on('$translateChangeSuccess', function () {
        //vm.gridOptions.api.???();
    });

    $scope.$on('$destroy', function () {
        listener();
    });
`
Best regards,

Rogerio

**Comment by ceolter** [comment]
nope. you cannot change the text after the grid is initialised. if the user changes the language, you will need to create a new grid.

**Comment by hollanderbart** [comment]
can this function been implemented. Creating a new grid just to change some strings is not functional.

**Comment by ceolter** [comment]
it's a chunk of work for me and not hight on my list of priorities.

**Comment by karmis** [comment]
its function need me too
https://github.com/ceolter/ag-grid/issues/1286
