### ISSUE TITLE
Memory leaks on show/hide column

### ISSUE THREAD

**Issue by vitvad** [ceolter/ag-grid#776]
Most probably in header cell renderer
https://github.com/ceolter/ag-grid/blob/master/src/ts/headerRendering/renderedHeaderCell.ts#L113

you not clean up old DOM and event listeners

in case of angular and custom renderer function - significantly leak memory because of undestroyed watchers.

Will update this ticket if find reason

**Comment by ceolter** [comment]
headers have gotten mostly rewritten since this post was raised, should be no memory leaks now.
