### ISSUE TITLE
How hard would it be to implement drag and drop for the file directory example?

### ISSUE THREAD

**Issue by thinkpadder1** [ceolter/ag-grid#777]
1. Go to https://www.ag-grid.com/
2. Scroll to the bottom for the example with the file directories.
3. How hard would it be to implement drag and drop for that (for React)? Any hints or tips for getting started? Not asking for a general solution... just for file directories like the example.

Thank you.

**Comment by ftorghele** [comment]
It should not be that hard (I've done it using an angular d&d directive which I put on the rows using the processRowPostCreate callback, not sure how it's working using react).

In each case I think #780 needs to be merged because you are not able to get the 'dragstart' event otherwise.

**Comment by ceolter** [comment]
agreed, nothing difficult, standard practices should apply. i'll be released with #780 in a few hours.
