### ISSUE TITLE
DOM focused cell and FocusedCellController selectedCell out of sync

### ISSUE THREAD

**Issue by roy46** [ceolter/ag-grid#778]
1 - select cell (1, 1)
2 - set selected cell via api.
```
var currentCell = this.api.getFocusedCell();
this.api.setFocusedCell(2, currentCell.column.colId);
```
3 - Hit space (select row)

Excepted: row 2 becomes selected
Actual: row 1 becomes selected

In a bit of a rush atm but i'll be happy to provide better example code if required.

Thanks

**Comment by roy46** [comment]
Below is an example that shows the issue best. On keydown of the space bar the current row should be selected and the next row down should the be in focus.

```
onSelectionChanged: function (params) {
    var currentCell = this.api.getFocusedCell();
    this.api.setFocusedCell(currentCell.rowIndex + 1, currentCell.column.colId);
    that.$rootScope.$digest();
}
```

**Comment by gerardqueralt** [comment]
Hi,
We also have the same problem. At the moment, We have this workaorund:
`(<agGrid.FocusedCellController>(<any>this.DataGridOptions.api).focusedCellController).setFocusedCell(focusedCell.rowIndex, focusedCell.column.getColId(), null, true);`

**Comment by ceolter** [comment]
fixed. will be in next release. in the mean time, do this workaround:
api.focusedCellController.setFocusedCell(rowIndex, colKey, floating, true);
