### ISSUE TITLE
e.preventDefault(); breaks scrolling when columns are pinned right

### ISSUE THREAD

**Issue by esbenp** [ceolter/ag-grid#781]
I am trying to pin some columns to the right, however this line https://github.com/ceolter/ag-grid/blame/a8c8914faf85cebef217e5f18bd4d7a80960c463/src/ts/gridPanel/gridPanel.ts#L729 seems to be breaking scrolling.

I am unable to scroll horizontally+vertically when my outer most container is high enough to contain the table. The container I talk about is the one I have marked in the picture below) 

![screen shot 2016-03-14 at 14 51 41](https://cloud.githubusercontent.com/assets/934819/13746590/6104e864-e9f4-11e5-8fea-06d8bc54ce88.png)

If the outer most container is not high enough to contain the table (e.g. all rows are not visible and must be scrolled into view), then I am unable to scroll horizontally (but vertically works).

Removing the `e.preventDefault();` makes the scrolling work perfectly except in the second case when some of the table is hidden. In that case when I scroll horizontally it will scroll to the bottom vertically (I suspect this is why you have added it in the first place).

I use Chrome Version 48.0.2564.116 (64-bit)
I scroll using Mac trackpads

**Comment by esbenp** [comment]
Possibly related: #419
Possible fix: #733

**Comment by esbenp** [comment]
I just tested, #733, fixes the problem. Is this planned for any release soon?

**Comment by ceolter** [comment]
yes, i'm going to try and get PR in soon.

**Comment by ceolter** [comment]
i've taken #733, so this problem should be fixed in next release. i plan to release in a few hours.

**Comment by esbenp** [comment]
So, this is still causing me issues. The reason being I have ag-grid within a scrollable container. `e.preventDefault();` will cause the event to stop bubbling up to the parent container (the scrollable container). I am therefore unable to scroll down the table.

**Comment by esbenp** [comment]
ping @ceolter

**Comment by ceolter** [comment]
@esbenp sorry, incredibly busy days right now,

think i'm getting confused with all the related items.

are you saying that when you mouse wheel on a pinned column, that it works. however you want the div the grid is in to scroll instead? maybe when you have come to the last row and not more to scroll?
