### ISSUE TITLE
import fails after renaming "PopupService" to "popupService"

### ISSUE THREAD

**Issue by Son-Lam** [ceolter/ag-grid#784]
Hi ceolter,

After you renamed the file, all of the code I have was broken because the imports still link to "PopupServer" not "popupService". I am running on Linux so the code is case-sensitive.

I patched temporary so I can run my code.

I would greatly appreciate if you could file the case-sensing issue.

Best Regard,

**Comment by ceolter** [comment]
please advise, where is it referencing PopupService? (and not popupService)

btw, the class is PopupService and the file is popupService

**Comment by ceolter** [comment]
are you looking at the latest?

as this was a problem i fixed a few days ago i though.

**Comment by Son-Lam** [comment]
Hi Niall,

There are two files were renamed:

1. .../widgets/popupService (from PopupService)
2. .../dist/lib/interfaces/iMenuFactory (from IMenuFactory)

You need to also change the case in all the files which refer to the files.
It works in Windows as the OS is case-insensitive for file names. But Mac
and Linux do.

Thanks a lot,

Son Lam.

*Sơn Quang Lâm*

*Cell: 408-3682972*

**Comment by ceolter** [comment]
yes i understand what you are saying. my point is, i cannot see where in my code this is still a problem. can you advise if you are looking at the latest code, and if so, which file has the issue?

**Comment by jkyoutsey** [comment]
headerRendering\standardMenu.d.ts:
`import { IMenuFactory } from "../interfaces/iMenuFactory";`
but \interfaces contains `IMenuFactory.d.ts`

**Comment by jkyoutsey** [comment]
So, it appears that your code is correct, but you may not be updating the dist folder with the changes.  The npm package for ag-grid ends up with a node_modules/ag-grid/dist/lib/interfaces/IMenuFactory.d.ts instead of iMenuFactory

**Comment by Son-Lam** [comment]
Hi Niall.

You need to rename to file from "PopupService" to "popupService" and
"IMenuFactory" to "iMenuFactory" then it will be OK. Just change the first
letters from-upper case to lower-case.

Thanks,

*Sơn Quang Lâm*

*Cell: 408-3682972*

**Comment by ceolter** [comment]
all renamed now to start with lower case.

**Comment by jkyoutsey** [comment]
Is this in 4.0.5 or 4.0.6?

**Comment by ceolter** [comment]
@jkyoutsey 
this is where i'm looking
https://github.com/ceolter/ag-grid/tree/4.0.5/src/ts/widgets
