### ISSUE TITLE
Import Filenames Exact Case 

### ISSUE THREAD

**Issue by jcmoore0** [ceolter/ag-grid#785]
Hi Niall -  Keep the great work!
Would you please make the filenames exact case on the imports?
Linux is case sensitive for filenames and Windows is not.

Example:
import {PopupService} from "./widgets/popupService";
filename: PopupService

Best regards,
John

**Comment by ceolter** [comment]
thanks for the feedback!! this should be fixed - i renamed the file PopupService back to popupService, so the imports should work.

are you using the latest? and if so, can you advise which file you are looking at?

**Comment by oberhauser** [comment]
Hi,

I stumbled upon the same problem. jspm build works fine on a windows machine, but fails on linux:

`Error: ENOENT: no such file or directory, open '/var/lib/jenkins/.../jspm_packages/npm/ag-grid@4.0.0/dist/lib/widgets/popupService.js'`

In ClientExports.js the file is referenced as `require("./widgets/popupService");` but actually is 'widgets/**P**opupService.js'.

**Comment by ceolter** [comment]
should be fixed in the latest release and latest in trunk.
