### ISSUE TITLE
Not able to integrate highcharts(graphs) in cells of ag-grid for angular 2.

### ISSUE THREAD

**Issue by anupmalhan** [ceolter/ag-grid#786]
Hi ,

I am trying to integrate highcharts(graphs) in cells of ag-grid for angular 2.I am not able to do that.
Unfortunately I am getting "**EXCEPTION: TypeError: Cannot read property '$apply' of null **" error all the times.
Just want to know that whether its possible to integrate highcharts in ag-grid or not?

Thanks in Advance 
Anup Malhan

**Comment by ceolter** [comment]
this happens when you have angularCompileRows = true and you are not using the angularJS 1 directive.

to fix, either take out angularCompileRows=true,
or start using the angularjs version of the grid
