### ISSUE TITLE
setVisibleColumn would not re-compile angular template with angularCompileRows:true

### ISSUE THREAD

**Issue by jackysee** [ceolter/ag-grid#787]
With `angularCompileRows:true`, calling `grid.columnApi.setVisibleColumn` would not re-render the cell in the angular context. e.g.

```
    this.grid = {
      columnDefs:[
        {headerName:'code', field:'code'},
        {headerName:'desp', field:'desp', template:'<input ng-model="data.desp" />'}
      ],
      angularCompileRows: true,
      rowData: [
        {code:'AAA', desp:'aaa desp'},
        {code:'BBB', desp:'bbb desp'}
      ]
    };
```

calling `setVisibileColumn` to hide and show `desp` column again, the input would become empty.

example: http://plnkr.co/edit/GGhk2rNtpXxav5rE4q1u?p=preview

**Comment by ceolter** [comment]
thanks for raising. someone also raised this on the forum. i don't understand why this is happening, have not been able to fix yet.

in the mean time, the workaround is to not use angular in your cellRenderer if at all possible.

if anyone else knows how to fix this, please advise. basically when change the code to compile the row after the column is set visible, it's just not compiling it correct.

**Comment by jackysee** [comment]
The workaround I used now is to `setRowData()` again.

**Comment by ceolter** [comment]
if you want a workaround, call api.refreshView(), calling setRowData() seems a bit heavy

**Comment by ceolter** [comment]
this was fixed last year.
