### ISSUE TITLE
node.setSelected(false) is not a function

### ISSUE THREAD

**Issue by rcholic** [ceolter/ag-grid#790]
I am trying to customize a data table using ag-grid in my Angular 1.x based project. The customization is that the user is allowed to select a maximum number of rows in the table, for example, the maximum is 2. I have the following code by using `node.setSelected(false)` that I found in the documentation page, but I got the error: `node.setSelected is not a function` when the selection exceeds the maximum of 2.

**Code for the onRowSelected function**:
```
function onRowSelected(event) {
                var curSelectedNode = event.node;
                var selectionCounts = vm.gridOptions.api.getSelectedNodes().length;
                if (selectionCounts > 2) {
                    var oldestNode = vm.gridOptions.api.getSelectedNodes()[0]; // get the first node, to be popped out
                    oldestNode.setSelected(false); // causes the above 'not a function' error
                 }       
            }
```

Or is there any other better way to do this customization? I am all ears. Thanks!

**Comment by PhiLhoSoft** [comment]
I have a similar issue (AngularJS 1.x, ag-Grid 3.3.3):

                    ctrl.gridOptions.api.forEachNode(function select(node, idx)
                    {
                        var select = _.some(ctrl.preselected, { name: node.data.name });
                        node.setSelected(select);
                    });

After loading the rows, I try to set a number of them as pre-selected, according to some row data state.
The nodes delivered by forEachNode() don't have the setSelected() function, neither directly nor in the prototype.

Is it a bug? A limitation? A misunderstanding of the documentation?
Is there a way to do this, otherwise?

Thanks for your awesome library!

**Comment by PhiLhoSoft** [comment]
Ah, according to the [changelog](https://github.com/ceolter/ag-grid/releases), setSelected is actually a 4.x feature! :disappointed: 
Sorry for the noise.
Perhaps @rcholic has the same issue than me (remaining at 3.x) or perhaps not...

**Comment by PhiLhoSoft** [comment]
OK, for the record, looking at the source code, I found the following solution:

                    ctrl.gridOptions.api.forEachNode(function select(node, idx)
                    {
                        var select = _.some(ctrl.preselected, { name: node.data.name });
                        if (select)
                        {
                            ctrl.gridOptions.api.selectNode(node, true, true);
                        }
                    });

Too bad v. 3 docs are no longer available... (Are they?)

**Comment by rcholic** [comment]
Thanks @PhiLhoSoft ! your information also helps me solve the problem. It turns out that I can use `deselectNode()` method in the latest API. 

```
if (selectionCounts > 2) {
                    var oldestNode = vm.gridOptions.api.getSelectedNodes()[0]; // get the first node, to be popped out
                   // oldestNode.setSelected(false); // causes the above 'not a function' error
                   vm.gridOptions.api.deselectNode(oldestNode, true); // This works!
                 }
```

**Comment by rcholic** [comment]
Even though 'vm.gridOptions.api.deselectIndex(0, true); ' seems to solve my problem, but the deselected node is no longer selectable. So still need to re-enable its selectable state.

**Comment by PhiLhoSoft** [comment]
I wrote:
> Too bad v. 3 docs are no longer available... (Are they?)

Well, the whole site is available in the archive files (and the Git history) of the 3.3.3 tag...

**Comment by ceolter** [comment]
archive docs available here:
https://www.ag-grid.com/archive/

there is a link to this in the main documentation pages, at the very bottom of the left hand side menu.

i believe all the conversation above was a confusion with the versions??? so closing this issue.

**Comment by PhiLhoSoft** [comment]
Ah, that's the Archive Docs link I missed! Thanks.
Note: confusion over versions is mostly mine, which hijacked the thread. Sorry for that.
rcholic might still have an issue. Either he will reopen this one, or open a new one with his new problem...
I will no longer comment here... :smile_cat:
