### ISSUE TITLE
Prevent row selection from cells

### ISSUE THREAD

**Issue by Tsyklop** [ceolter/ag-grid#7909]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Example: [https://stackblitz.com/edit/vitejs-vite-qlpegv](https://stackblitz.com/edit/vitejs-vite-qlpegv) (do not work on plunker)

I have event prevention, but it do not work

```
onCellClicked={(event) => {
        console.log(event);
        if (
          event.colDef.colId === 'actions' ||
          event.colDef.colId === 'selection'
        ) {
          event.event?.stopPropagation();
          event.event?.preventDefault();
          return;
        }
      }}
```

**Current behavior**
When I clicked on checkbox - row select.
When I clicked on **A** button in the end of row - row select.

**Expected behavior**
When I clicked on checkbox - row do not select.
When I clicked on **A** button in the end of row - row do not select.

**Please tell us about your environment:**
Windows 11, WebStorm, pnpm, vite

* **AG Grid version:** 31.3.1

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

* **Language:**
TypeScript 5.4.5
ES6/7

**Comment by vardhan03** [comment]
Hey @Tsyklop,
We have fixed this issue via suppressRowClickSelection grid property earlier, but in the new ag-grid 32 version, this property is deprecated.
Can you let me know if you have any fix for this? I see you have closed this issue.

**Comment by 5te1n** [comment]
Due to the depreciation of suppressRowCkickSelection i have the same problem now. The workaround doesn't work for me if I use the new rowSelection.enableClickSelection api.
