### ISSUE TITLE
Configurable Tool Panel Icons

### ISSUE THREAD

**Issue by nabeezy** [ceolter/ag-grid#795]
Feature Request: Configurable Tool Panel Icons similar to the column icons noted at https://www.ag-grid.com/angular-grid-icons/index.php

**Comment by ceolter** [comment]
thanks for raising.

**Comment by axelex** [comment]
Is there any update on this issue?

**Comment by ceolter** [comment]
nope, still on the todo list.

**Comment by seminull** [comment]
Does this also refer to the context menu built in items? i.e. copy

**Comment by ceolter** [comment]
icons in toolpanel are now configurable
