### ISSUE TITLE
When using dotNotation, data value of 0 or false does not show up on grid

### ISSUE THREAD

**Issue by llkyull** [ceolter/ag-grid#796]
I believe the fix should be:

From ValueService.ts
line 73 should be changed from
if (!currentObject)
to
if (currentObject == undefined)

If this was intentional can you please explain use

**Comment by scotthovestadt** [comment]
You need to use triple equal sign with undefined or you have the same exact bug.

**Comment by llkyull** [comment]
thanks scott

**Comment by ceolter** [comment]
thanks. fixed.
