### ISSUE TITLE
ag-grid column width should be based on it's contents length 

### ISSUE THREAD

**Issue by sasikumar25** [ceolter/ag-grid#797]
Hi All,

My grid column should be based on its contents length for eg if column 1 having a test like
 "this is sample text" column 1 width should be based on this text (150px).
 column 2 having a value like 2 then his column width should be like 10px i don't want all column will be in same width of 150.

I tried sizeColumnsToFit() but this will apply the avg column width.

http://plnkr.co/edit/kveA78BUA8iXNZbb8usa?p=preview

in above example after re size column width will be  89px.

**Comment by vamsikrishnamannem** [comment]
Use the `autoSizeColumns` columnApi for auto resize the columns based on the content.
For reference see the example [here](https://www.ag-grid.com/angular-grid-resizing/index.php)

**Comment by sasikumar25** [comment]
while using  "autoSizeColumns" header values are hidden.

in above example  gold, silver, bronze and total are partially displaying

**Comment by ceolter** [comment]
regarding the specific issue here "ag-grid column width should be based on it's contents length" this is solved via ```autoSizeColumns```

correct it doesn't use the header. if you don't want the header hidden, then set min widht for the col.

**Comment by tamarshankolevsky** [comment]
but if the content less than the column i want it to be more to divide the extra width
