### ISSUE TITLE
Allow changing of set filter values, and / or to reset the filter

### ISSUE THREAD

**Issue by Wingie** [ceolter/ag-grid#798]
I have an ag-grid setup with filter values (set) being populated from a server side application.

on every call, i want the all of the filters (except the one which is opened) to update their set filters according the values in setcolumn def.

however, if one opens a filter and closes it without changing anything, then it already has a `filterWrapper` in ` FilterManager.prototype.getOrCreateFilterWrapper` and so when the filters are changed by another filter on the grid, the filters on this column do not update.

to attempt to fix said issue, i've tried the following code

```
 FilterManager.prototype.getOrCreateFilterWrapper = function (column) {
	        var filterWrapper = this.allFilters[column.getColId()];

	        if (!filterWrapper) { 
	            filterWrapper = this.createFilterWrapper(column);
	            this.allFilters[column.getColId()] = filterWrapper;
	        }else if(filterWrapper.filter.model){
	        	var filterUnchanged = (filterWrapper.filter.model.selectedValuesCount == filterWrapper.filter.model.availableUniqueValues.length);
	        	console.log('***filterUnchanged',filterUnchanged)	
	        	console.log('***coldef',column.getColDef().filterParams,filterWrapper)
	        	if (filterUnchanged) {
	        		filterWrapper.filter.colDef.filterParams = column.getColDef().filterParams;
	        		// filterWrapper = this.createFilterWrapper(column);
	        			
		        	// console.log('***creategui',filterWrapper.filter.createGui())
	        	}
	        	console.log('***gui',filterWrapper.filter.getGui())
	        }
	        
	        return filterWrapper;
	    };
```

i can update the filterparams but that is not affecting the already rendered GUI.
is there a way i can re-render the updated filter params onto the gui?

**Comment by ceolter** [comment]
```
is there a way i can re-render the updated filter params onto the gui?
```
i think the answer is now. but i'm not fully understanding the question.

are you trying to update the available values in the filter?

**Comment by Wingie** [comment]
Yeah - my filter values are coming from the server, and when other filters are updated, i need to reupdate the filters that havent been changed yet with the new values from the server

**Comment by ceolter** [comment]
yea that's a problem. i'm going to change the name of the issue to be more specific.

**Comment by ceolter** [comment]
new method implemented 'destroyFilter'.

if you call this, then setModel, it will do as you require.
