### ISSUE TITLE
e.preventDefault(); breaks scrolling when table is inside scrollable container

### ISSUE THREAD

**Issue by esbenp** [ceolter/ag-grid#800]
If a table is placed within a scrollable container (like in a web app), then [this](https://github.com/ceolter/ag-grid/blame/a8c8914faf85cebef217e5f18bd4d7a80960c463/src/ts/gridPanel/gridPanel.ts#L729) breaks scrolling if the table is 100% height.

When the table is 100% height, then vertical scrolling is the job of the scrollable container and not ag-grid. e.preventDefault(); will prevent the scrolling event from bubbling up to the scrollable container.

Related #781

**Comment by ceolter** [comment]
100% height means the gird will be the height of the containing div.

eg lets say containing div is 100px, and then say each row is 10px high, you will only be showing 10 rows, and the grid will have scrolls for the the other rows, even if grid has 100000 rows.

if you are describign a grid with no vertical scrolls, then you have to set it's height to the height of all the rows, and not 100%???

**Comment by esbenp** [comment]
Okay, I have tried to illustrate it to make it more clear.

![asdasd](https://cloud.githubusercontent.com/assets/934819/14112347/aca70c3a-f5ce-11e5-84fe-e2b99e6bff66.png)

So I have made a div that is `overflow:auto` (the green one). It is important to underline that this is not a div made by ag-grid. It is a div I have made which is part of my design.

Inside this div I have an ag-grid. Let us imagine the table has 10 rows, each row is 50 px high. Now imagine my ag-grid container is `height:1000px`. This means ag-grid does not create a vertical scrollbar, since the table is smaller than the container.

As shown on the picture a part of the ag-grid is outside the viewport. I therefore scroll, however I expect to scroll to happen by the green box (not ag-grid). However when I scroll the `e.preventDefault();` will prevent the event from bubbling up to the green box.

Does it make sense now?

**Comment by ceolter** [comment]
yes understood. sorry for asking explicitly, but i can get different issues mixed up. so to be clear, will the following fix it: 

Have option in grid to not preventDefault on mouse wheel events?

This will have unexpected behaviour if the grid has scroll bars (as when you mouse wheel, the grid will scroll and the webpage will scroll) - however we don't care about this, if you set the switch, it's assuming you don't want scrolls in the grid.

**Comment by esbenp** [comment]
Yes, I guess a good option would be to have an option to disable scrolling. This would also solve #801. However, I think it is important that we distinct between horizontal and vertical scrolling. I.e. you should be able to toggle horizontal and vertically scroll separately. 

Should we close #801 and merge it into this issue?

**Comment by kaelhem** [comment]
What about adding a delay on mouseEnter before applying preventDefault on scroll ?
Or, another 2 cents idea, why do not allow scroll when scroll was already performing before mouseEnter ?
I think this way, all use cases should be covered.

**Comment by ceolter** [comment]
@esbenp trying to look at this now, did you know at what parts of the code exactly we need to 'prevent default' ?

**Comment by ceolter** [comment]
@esbenp i asked to soon, i see you referenced the line of code in the above. will look again. thanks.

**Comment by ceolter** [comment]
i have surrounded the said code with the following:
```
        // allow the option to pass mouse wheel events ot the browser
        // https://github.com/ceolter/ag-grid/issues/800
        // in the future, this should be tied in with 'forPrint' option, or have an option 'no vertical scrolls'
        if (!this.gridOptionsWrapper.isSuppressPreventDefaultOnMouseWheel()) {
            // if we don't prevent default, then the whole browser will scroll also as well as the grid
            event.preventDefault();
        }
```
in other words, set the property suppressPreventDefaultOnMouseWheel=true and then the grid will not prevent default on the mouse wheel event. we plan to release this week so you should have this fix soon.
