### ISSUE TITLE
[autoheight grid] Disable vertical scrolling

### ISSUE THREAD

**Issue by esbenp** [ceolter/ag-grid#801]
Is there no option for disabling vertical scrolling i.e. just displaying the table's contents as-is?

As far as I can tell all that is needed is to remove [this line](https://github.com/ceolter/ag-grid/blob/259048f2276a6b87e1f964a43a9e6a022a06863e/src/ts/layout/borderLayout.ts#L224), but I am not sure if that will have unwanted repercussions?

**Comment by ceolter** [comment]
there is no option for this.

some people use 'forPrint', this does something similar.

it's my plan to implement 'auto row height' but it's not done yet.

**Comment by esbenp** [comment]
Okay, but for `forPrint` will disable horizontal scroll, yes?

In estimation, do you see any issue with outcommenting [this line](https://github.com/ceolter/ag-grid/blob/259048f2276a6b87e1f964a43a9e6a022a06863e/src/ts/layout/borderLayout.ts#L224) ?

Then we could just make a setting. Something a long these lines

```javascript
if (!this.options['auto_height']) {
   this.eCenterRow.style.height = centerHeight + 'px';
}
```

**Comment by ceolter** [comment]
```Okay, but for forPrint will disable horizontal scroll, yes?``` -> yes

```In estimation, do you see any issue with outcommenting this line ?``` -> no, seems fine

your right, the grid is very close to having an auto-height feature, would be small code required on my side to get it in

**Comment by esbenp** [comment]
I will open a PR, if you are busy?

**Comment by ceolter** [comment]
sure you can open a PR. i spent 20min just now looking at implementing 'auto height', but it's a tricky bugger, i'll need to give it a good two hours on undistracted time - so had to back out (i'm on client site currently, so not as much time to do larger items). if you can do a PR then i will take a look. i will do full review of the PR (make sure i understand it) before merging, so please be patient after you create the PR.

**Comment by wymmeroo** [comment]
This feature is for us as well critical. We use aggrid with bootstrap and as a tablet version. It's unusable if you have two scrollbars on a tablet version. The height is taken by ag grid, but there's always 1-2 rows which are invisible and thats why the scrollbar is shown. When do you guys is that feature available. It is really critical for our application.

**Comment by ceolter** [comment]
```When do you guess is that feature available``` I have a lot of other work that I am doing at the moment, so won't be spending time on this in the next two weeks. Maybe after that.

**Comment by drawyan** [comment]
Would love to have this feature, currently we are setting the grid height to be the total of all rows plus some paddings to remove the vertical scroll bar in mobile view. But the code is not that clean due to the resize sensor logic.

**Comment by zaktimson** [comment]
+1 Is there any progress?

**Comment by ceolter** [comment]
tracked by https://ag-grid.atlassian.net/browse/AG-114

**Comment by lipedeitos** [comment]
For those who are still searching for an answer for this, this could be an emergency solution, hope this helps. I guess I solved this using only css. Obviosly some features lose sense without vertical scroll (floating top and bottom rows).
I did not tested all features, but i guess this works in a lot of cases.

    .ag-scrolls {
        height: auto !important;
    }

    .ag-body {
        position: relative !important;
        top: auto !important;
        height: auto !important;
    }

    .ag-header { 
        position: relative !important;
    }

    .ag-floating-top {
        position: relative !important;
        top: auto !important;
    }

    .ag-floating-bottom {
        position: relative !important;
        top: auto !important;
    }

    & > div,
    .ag-bl-normal-east,
    .ag-bl-normal,
    .ag-bl-normal-center,
    .ag-bl-normal-center-row,
    .ag-bl-full-height,
    .ag-bl-full-height-center,
    .ag-pinned-left-cols-viewport,
    .ag-pinned-right-cols-viewport,
    .ag-body-viewport-wrapper,
    .ag-body-viewport {
        height: auto !important;
    }

**Comment by rymk** [comment]
We have a need for this feature as well.

We are currently implementing a workaround where we calculate the height each time it is changed, apply that height to the gridOptions containing div, and then call doLayout() _(forPrint seems almost identical)._ 

A concerning negative side effect to setting the height to fit all containing rows is that the rendering time in IE is quite awful. We are seeing this lag when setting the data source on page load and anytime we change column visibility to true.  I assume this is related to row virtualization and IE managing memory and drawing DOM elements quite poorly. 

**Example:** With about 320 rows __(height: 7000px)__ and ~20 columns the below calls takes about 2seconds to execute and an additional 3-6seconds for IE to stop drawing and give control back to the user.
``$scope.gridOptions.columnApi.setColumnsVisible(['streetAddress', 'district', 'city', 'region', 'country', 'latitude', 'longitude', 'collapseAddressDetail'], true);``

This is not scalable. With a test of 1000s of records we've seen nearly exponential slowness in IE; Chrome works great :) 

**It would ideal if the implemented solution was able to maintain the row virtualization when vertical scrolling is disabled.** I believe this would eliminate slowness in IE, like when the grid has a reasonable height set.

Thanks!

**Comment by davidmcooper** [comment]
This is an issue for our use-case as-well.  Essentially, we'd like the ability to toggle the grid's vertical scrolling on or off at-will.  The specific use-case is that we need the ability to scroll the page that the grid lives in up until the grid reaches the top of the browser window, then "sticky" the grid at the top so that we're using the full browser window for displaying our grid.

As mentioned by @rymk, we can achieve this behavior by setting the height of the outer div to a height greater than the height necessary to present our data in the grid, but this definitely impacts performance.

API access to enable or disable vertical scrolling of the grid's viewport would seem to solve this.

**Comment by 6220119** [comment]
We also need this feature.
Also `ag-grid` should maintain the row virtualization when using the `<html>` element's (or any specified container element's) scrollbar.
Checkout `react-virtualized`'s WindowScroller example
https://bvaughn.github.io/react-virtualized/#/components/WindowScroller

**Comment by sjain-mi9** [comment]
If we can have height as a property instead of defining it in css, it can be resolved by calculating it as gridHeight = headerHeight + (rows.length * rowHeight)

**Comment by makinggoodsoftware** [comment]
Hi,

Just to le you know that as of 10.1.0 this is available.

Please check the changelog

Thanks

**Comment by sjain-mi9** [comment]
@makinggoodsoftware , not sure how we have auto height. Can you please provide us an example for that or redirect to a link if that's updated in your documentation.

**Comment by hallids** [comment]
- [Changelog](https://www.ag-grid.com/change-log/changeLogIndex.php)
- [Auto height grid](https://www.ag-grid.com/javascript-grid-width-and-height/#autoHeight)

**Comment by joincamp** [comment]
@makinggoodsoftware

I see the auto-height feature, but it does not appear to virtualize the rows like @6220119 brought up. Is this in the works, or just not a supported use case?

**Comment by yehudahkay** [comment]
+1, I tried setting the height to 100vh - 100px but it's not working

**Comment by fyidev** [comment]
@joincamp did you find a solution for this? Dealing with same issue

**Comment by samsaid** [comment]
@hallids do you know if there is a way to solve this using CSS? I've been looking into the ag-grid link you provided however haven't found a solution yet.

**Comment by raylight75** [comment]
Just add  in corresponding theme (in my case is balham);
`.ag-theme-balham {  
  --ag-list-item-height: 20px;
  height: 1200px  !important;
  overflow: hidden  !important;
}`
