### ISSUE TITLE
getNodeChildDetails callback can't be passed as a React prop

### ISSUE THREAD

**Issue by jenrzzz** [ceolter/ag-grid#804]
It looks like `getNodeChildDetails` isn't included in [componentUtil's list of function properties](https://github.com/ceolter/ag-grid/blob/master/src/ts/components/componentUtil.ts#L46), so it only works  when passed in gridOptions.

**Comment by ceolter** [comment]
thanks. will be in next major release. as you say, workaround is gridoptions. sorry if you lost time on this.
