### ISSUE TITLE
Issue with Copying and Pasting from Excel to ag-Grid

### ISSUE THREAD

**Issue by ashoknokiaa** [ceolter/ag-grid#8062]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Steps to Reproduce:**
- Open Excel and enter data in two rows of a single column (e.g., A1 and A2).
- Copy these two cells.
- Open the ag-Grid and select a starting cell for pasting.
- Paste the copied cells into the grid.

**Current behavior**
The data from Excel is pasted into the two rows, but an additional row is also replaced with an empty one.

**Expected behavior**
The data from Excel should be pasted into the selected cells in ag-Grid without affecting other cells.

**Please tell us about your environment:**

* **AG Grid version:** 31.3.2

* **Browser:** All

* **Language:** TypeScript

**Comment by sabahang** [comment]
Hi 

Is it possible that you have flag `copyHeadersToClipboard`to true? 

There are various options that could affect the result of pasting into the Grid. We need a live example to be able to investigate this .

Please provide the following (as per our bug template in Github):
1. A live example (plunker, stackblitz, etc) or link to a repo showing the issue
2. A list of steps to follow to reproduce the issue
3. Descriptions of current behavior and expected behavior

We're looking forward to your response to we can investigate this further.

Thank you!

**Comment by ashoknokiaa** [comment]
I have verified that the copyHeadersToClipboard option is true. The issue persists regardless of this setting.

### A live example:
I have created a Plunker to demonstrate the issue: 
[https://plnkr.co/edit/Vs18TcsP1yulaJuH?open=app.component.ts](url)

Steps to reproduce the issue:

- Open the provided Plunker link.
- In Excel, enter data in two rows of a single column (e.g., cells A1 and A2).
- Copy these two cells.
- In the ag-Grid example, select a starting cell for pasting.
- Paste the copied cells into the grid.

Current behavior:
When pasting the copied data from Excel, it pastes into two rows but also replaces an additional row with an empty one.

Expected behavior:
The data from Excel should be pasted into the selected cells in ag-Grid without affecting other cells.

Thank you for your assistance in resolving this issue.

**Comment by sabahang** [comment]
Hi @ashoknokiaa 

When I follow your steps I don't get the additional empty cell. See below:
![Kapture 2024-06-12 at 11 58 57](https://github.com/ag-grid/ag-grid/assets/2657540/d3ffe5c6-a74e-498e-8d85-9cbeca90d44f)

This might be something in your environment setup. If you pasted the cells in a plain notepad document do you get any extra characters? Can you try the same with google sheets? A recording like above might help better investigate

Thanks

**Comment by jaaywags** [comment]
> @ashoknokiaa it seems that on Windows the behaviour is different. The GIF above is from MacOS.
> 
> Please try to use the following flag to address the issue on Windows: https://ag-grid.com/javascript-data-grid/grid-options/#reference-clipboard-suppressLastEmptyLineOnPaste

This worked! Adding the following to gridOptions

```typescript
suppressLastEmptyLineOnPaste: true,
```
