### ISSUE TITLE
Sorting and Filtering works only on selected page index 

### ISSUE THREAD

**Issue by BeingDev** [ceolter/ag-grid#807]
When I attempt to sort or filter on a table, I am not able to do it on the entire data set.
For example in this page: [https://www.ag-grid.com/angular-grid-pagination/index.php](https://www.ag-grid.com/angular-grid-pagination/index.php) when i select page size in the example as **10** rows and do sorting, it sorts only that page index and not on the entire data set. Same with filtering.

Is there any way I can achieve sorting and filtering on entire data set when I am NOT using virtual pagination. 

If this issue has been raised already, would be great if you can route me to it.

Thanks.

**Comment by ceolter** [comment]
yes has been raised before. at the moment, if you want to do this, you have to implement your own 'server side sorting' in the client. ie assuming you are loading all the data into browser memory, then do the same technique as 'server side sorting / filtering' but implement the sorting and filtering in you datasource - similar to what the ag-grid examples do (there is no server in the example, the server is mocked out in javascript in the browser)

**Comment by BeingDev** [comment]
Thanks for quick reply. Do you have live examples to implement custom filter and sorting events on ag-grid?

Thanks again.

**Comment by ceolter** [comment]
the second example on this page.
https://www.ag-grid.com/angular-grid-pagination/index.php

it reads in the same data in one go, and then chops it into pages. the filtering and sorting is done inside the datasource.
