### ISSUE TITLE
npm error on enterprise installation

### ISSUE THREAD

**Issue by erezcohen** [ceolter/ag-grid#809]
Trying to evaluate the enterprise edition. I ran "npm i ag-grid-enterprise -S" and received:

npm WARN saveError peer invalid: ag-grid@4.0.x, required by ag-grid-enterprise@4.0.7
├── UNMET PEER DEPENDENCY ag-grid@4.0.x
└── ag-grid-enterprise@4.0.7

However the documentation clearly says that ag-grid shouldn't be manually installed when using enterprise.

**Comment by ceolter** [comment]
ag-grid-enterprise not needing ag-grid only applies when you are using the ag-grid-enterprise.js bundles file.

under normal operation, ag-grid-enterprise depends on ag-grid, there is no duplication of code. ag-grid-enterprise injects functionality into ag-grid. so if you are using commonjs (what ag-grid is modelled on), then you use both projects.

however if you are using the bundles version of ag-grid or ag-grid-enterprise, then you only need dist/ag-grid.js (for free version) or dist/ag-grid-enterprise.js (for enterprise).

so it depends on what tools your using.

if you are using bundles, and only need ag-grid-enterprise,js, then node will still need to download both to satisify the commonjs dependency the projects have on each other.
