### ISSUE TITLE
Sort state being lost on coldefs when using setColumnDefs

### ISSUE THREAD

**Issue by Wingie** [ceolter/ag-grid#810]
in my use case, i am updating setColumnDefs so that the set filters can get updated  with new values from the backend.
unfortunately this has the side effect of clearing out the sort icon on the header.
if i use setSortModel() then another backend call is sent with the sort model (and we will enter an infinite loop)
if there an API to set the sort model without  making another call to datasource (because the entries are sorted.. only the icon on the header needs to be updated.

**Comment by ceolter** [comment]
just not how things are designed, if you set the sort model, then that implies the sort has changed and the grid reloads.

however that's where you can create your own header template - so you can have your own logic in your own header, separated from the grid's functionality???
