### ISSUE TITLE
Not getting width of an ag-grid

### ISSUE THREAD

**Issue by abhimunna** [ceolter/ag-grid#811]
I found how to get width of columns in ag-grid using getColumnState()  which is in Column API, but i am trying to get width of an ag-grid using API functions but i cant find it, can anyone help me  is there any approach to find width of an grid.

**Comment by ceolter** [comment]
api doesn't have method for returning width of entire grid. i suggest you look up the dev using a query selector and query it's width.

document.querySelector('.ag-body').clientWidth

**Comment by abhimunna** [comment]
I have already tried using queryselector, But when i am using onGridReady property to call queryselector, it's not working. Can you give me any suggestion, is there any other solutions to get it. @ceolter

**Comment by ceolter** [comment]
i don't know what's wrong, however querySelector is nothing to do with the grid. when onGridRead is called, the grid is in the dom - so why it's not working is a standard javascript / dom question. maybe inspect the dom, look for the div in question, verify it's there, and double check your css selector.
