### ISSUE TITLE
autoSizeColumns() doesn't account for cell padding

### ISSUE THREAD

**Issue by mpetkov** [ceolter/ag-grid#812]
I was trying to use autoSizeColumns() to get the cell width to auto size to the cell content and I found an issue.  It turns out that the padding of the cell is not taken into account so the content is being cut off.  Can this functionality be updated to behave correctly?

Here is example:
http://plnkr.co/edit/wNSPC2Gnagf2Z6u6TdXg?p=preview

**Comment by mpetkov** [comment]
One solution could be to just expose a new padding parameter for each column where the user can specify the padding to add to the width of content?

**Comment by ceolter** [comment]
noted.

**Comment by ceolter** [comment]
new property autoSizePadding was put in last year
