### ISSUE TITLE
buttons created using cell-rendering doesn't fire event which are written outside the cellrenderer function

### ISSUE THREAD

**Issue by abhibly** [ceolter/ag-grid#813]
Hi i am creating buttons in every row using cell-renderers like this->
{headerName: "Gold", field: "gold", width: 100,  cellRenderer: this.ageCellRendererFunc }

This is how i am attaching the click event to the buttons that are created ->
    ageCellRendererFunc(params) {
        var eSpan = document.createElement('button');
        eSpan.innerHTML = 'Del';
        eSpan.addEventListener('click', () => {
            this.raiseevent();
        });
        return eSpan;
    }
And this is the event i want to raise on button click
raiseevent(){
console.log('it worked');
}

But it is showing a error like this-> cannot read property raiseevent of undefined...How can i solve this issue? I am binding the event correctly but it is throwing the error.How to resolve that...Somebody please help...

**Comment by ceolter** [comment]
can tell by the code you have shown, not clear if the methods are part of a class or not. you would need to post fuller code.

it's just a TypeScript question though, nothing to do with grid. it's as if the 'this' pointer is not pointing to where you think it is pointing.

try using non-Typescript eg:
```
var that = this.
eSpan.addEventListener('click', function() {
  that.raiseevent();
});
```

**Comment by ceolter** [comment]
ps closing as it's not an issue with the grid.

**Comment by abhibly** [comment]
I tried many ways to raise an event which is part of class but i am not successful...please can you share any example to raise the event which is part of a class from the elements that are created using cell renderer?

**Comment by ceolter** [comment]
this should work:
```
ageCellRendererFunc(params) {
  var eSpan = document.createElement('button');
  eSpan.innerHTML = 'Del';
  eSpan.addEventListener('click', function() {
    console.log('button clicked');
  });
  return eSpan;
}
```

**Comment by kulbir21** [comment]
This is working for me but now I want to raise that event using tab and enter ,tab to set the focus and enter as click on that event to raise event

**Comment by kulbir21** [comment]
Currently not able to set the focus on the button on tab press focus is going to cell not on button please help in the same

**Comment by kulbir21** [comment]
Currently not able to set the focus on the button on tab press focus is going to cell not on button please help in the same
