### ISSUE TITLE
ag-grid  autosizecolumns not considering floating rows values 

### ISSUE THREAD

**Issue by sasikumar25** [ceolter/ag-grid#814]
while auto size columns floating rows values getting hidden if its length is greater than its body contents.

autosizecolumns api not considering header and floating rows values. since i can't able to set min width because columns def are getting dynamically in my project.

**Comment by ceolter** [comment]
noted. thanks.

**Comment by Julzk** [comment]
solved?

**Comment by Julzk** [comment]
rowRenderer.js

RowRenderer.prototype.getAllCellsForColumn = function (column) {
        var eCells = [];
        utils_1.Utils.iterateObject(this.renderedRows, callback);
        utils_1.Utils.iterateObject(this.**renderedBottomFloatingRows**, callback);
        utils_1.Utils.iterateObject(this.**renderedBottomFloatingRows**, callback);
        function callback(key, renderedRow) {
            var eCell = renderedRow.getCellForCol(column);
            if (eCell) {
                eCells.push(eCell);
            }
        }
        return eCells;
    };

**Comment by ceolter** [comment]
ah, good catch. thanks. i've checked this change in. just missed the 6.2.0 release, will be in the next one.
