### ISSUE TITLE
How to set rowModelType: 'pagination' dynamically

### ISSUE THREAD

**Issue by itsmefirealex** [ceolter/ag-grid#815]
Dears,

I want to load blank grid without data. I want to load data based on button click. I can able to pull data by using datasource

var gridOptions = {
    // note - we do not set 'virtualPaging' here, so the grid knows we are doing standard paging
    enableSorting: true,
    enableFilter: true,
    rowSelection: 'multiple',
    enableColResize: true,
    columnDefs: columnDefs,
 };

gridOptions.api.setDatasource(dataSource);

but pagination is not displaying. so I used below statement to make pagination but pagination is not coming up.

gridOptions.api.rowModelType: 'pagination';

Need help. Please

Thanks,

**Comment by ceolter** [comment]
you need to specify pagination on the gridoptions at the start, you cannot change it after the grid is created. see examples here:
https://www.ag-grid.com/angular-grid-pagination/index.php
