### ISSUE TITLE
Selecting a node by Index and preventing the selection events in a Grid api appropriate way

### ISSUE THREAD

**Issue by killyosaur** [ceolter/ag-grid#817]
So I have been abusing the api.selectIndex function, and as of the current 4.x release, I am getting warnings stating not to use it. The issue is this, I have a situation where I have a tab situation where depending on the tab clicked, the data is different. I want to hold onto the selections for a given tab, but reuse the same grid on the page. I recognize that the message I am getting is just a warning and that currently there is nothing that prevents me from using it (and at this time, no way for it to be blocked). This may be an unnecessary ask, but it is something to keep in mind as you further improve the grid (and as JavaScript continues to evolve) that if the day comes where a true internal function is possible for a JavaScript module such as this, that there is a way to continue doing the above described actions. Thanks! :)

**Comment by ceolter** [comment]
preventing events is not normal, DOM elements (buttons etc) don't allow this. so the pattern I'd like to follow is the pattern in the rest of the web, which is unregister your listener if you don't want events.

with regards selecting by Index, you can easily get the node at the index, and then select the node. see here:
https://www.ag-grid.com/forum/showthread.php?tid=3571

**Comment by killyosaur** [comment]
On the event side of things: fair enough, I will look into a system that will allow me to register/unregister for the particular use case (when first loading, or reloading selections, I do not want to detect change events, once I have reloaded the selections, I would want to reload the events),

On the second point: I really need to check the forums more frequently :P Sorry about the noise.

**Comment by ceolter** [comment]
@killyosaur no worries!!! the forums are a mess of information to be fair.
