### ISSUE TITLE
Context in Custom Filter Failing

### ISSUE THREAD

**Issue by GeorgeNYCDA** [ceolter/ag-grid#818]
Hey Nialls, I've implemented a Custom Filter and i'm calling the context() function that's included in the params and this is causing an exception to be thrown.  This is an issue with 'this' referencing.  

What's i'm trying to accomplish is to create a filter for the 'selected/unselected' rows in the grid and I thought of getting a handle on the grid's api object in the custom filter by saving it in the context, but this is not currently possible.

**Comment by ceolter** [comment]
not enough information for me to help. if you can create a plunker, i could look?? however i'm trying to keep github for issues (ie bugs or missing features) with the grid, this is looking for help?? so best place is to post in the forum.

**Comment by GeorgeNYCDA** [comment]
It is a bug...calling the params.context() function in a CustomFilter.prortotype.init function causes an exception to be thrown.

**Comment by ceolter** [comment]
params.context is not necessarily a function. it is whatever you set as the context in the gridoptions.

so if you set gridOptions.context = 'a string' then trying params.context() will fail as it's not a function.

are you setting the context to a function in gridOptions?

**Comment by GeorgeNYCDA** [comment]
That's what I was expecting, but I was looking through the stack trace and found that the context is a function on the GridOptionsWrapper class.  Take a look at one of your custom filters

https://www.ag-grid.com/angular-grid-filtering/index.php

and try to pull in a custom context.  I'm on v3.3 so this might be resolved but you're free to check.

**Comment by ceolter** [comment]
emm, the gridOptionsWrapper is an internal class, it doesn't have a context attribute, however it does have a getContext() method that returns the context.

this is the code that creates the params for the filter. see it calls getContext() on gridOptionsWrapper
```
        var params = {
            column: column,
            colDef: colDef,
            rowModel: this.rowModel,
            filterChangedCallback: filterChangedCallback,
            filterModifiedCallback: filterModifiedCallback,
            filterParams: filterParams,
            localeTextFunc: this.gridOptionsWrapper.getLocaleTextFunc(),
            valueGetter: this.createValueGetter(column),
            doesRowPassOtherFilter: doesRowPassOtherFilters,
            context: this.gridOptionsWrapper.getContext(),
            $scope: filterWrapper.scope
        };
```

**Comment by ceolter** [comment]
i just tested, using the custom filter example, context is getting passed in fine for me. if you can create a plunker i can take a look, otherwise i can't reproduce.

**Comment by GeorgeNYCDA** [comment]
Ahh ok I'll see if I have time to make a plunker...for me the code that is being executed is the following


	    FilterManager.prototype.createFilterWrapper = function (column) {

                 .......

	        var params = {
	            colDef: colDef,
	            rowModel: this.rowModel,
	            filterChangedCallback: filterChangedCallback,
	            filterModifiedCallback: filterModifiedCallback,
	            filterParams: filterParams,
	            localeTextFunc: this.gridOptionsWrapper.getLocaleTextFunc(),
	            valueGetter: this.createValueGetter(column),
	            doesRowPassOtherFilter: doesRowPassOtherFilters,
	            context: **this.gridOptionsWrapper.getContext,**


the getContext function isn't being called, but being passed by reference

**Comment by GeorgeNYCDA** [comment]
http://plnkr.co/edit/p5vJD9GbLB6rsDhjIAc9?p=preview

**Comment by GeorgeNYCDA** [comment]
I just used the most recent version of the grid, and this problem has been fixed...sorry for the trouble...Thanks.  It's broken in version 3.3

**Comment by ceolter** [comment]
you will need to upgrade then, i'm not in the game of providing patch releases.
