### ISSUE TITLE
Add Label to Column Name in Tool Panel for Selection

### ISSUE THREAD

**Issue by EricByers** [ceolter/ag-grid#820]
In the Tool Panel when hiding/showing columns, the icon is the only location that you can click/tap.  Would be nice to have a label on the column name as well so clicking/tapping the column name would also toggle the hide/show selection.

Thank for all the good work on ag-grid.

**Comment by aaronjhiggins** [comment]
Here is a working less hack. Tested in chrome.

.ag-tool-panel-container {
    #borderLayout {
      #centerRow {
        #center {
          .ag-list-selection {
            .ag-list-item {
              height: 36px;
              line-height: 36px;
              .ag-visible-icons {
                width: 100%;
                display: block;
                position: relative;
                z-index: 2;
              }
            }
            .ag-list-item>span>span:last-child {
              position: relative;
              z-index: 1;
              top: -36px;
              left: 20px;
            }
          }
        }
      }
    }
  }

**Comment by ceolter** [comment]
thanks for the feedback. i have big plans for the sidebar - so i will be keeping from the finer details you mention as it's not ready for polishing. on item i want to do is allow multi select, and then action on a group (eg pick 10 cols and set them visible all at once, or drag 10 cols onto the grid at the same time, or drag a group of cols at the same time). i want to get all these bigger features in first as they will impact then the smaller user interaction details.

**Comment by ceolter** [comment]
clicking the label now shows / hides the column
