### ISSUE TITLE
Saving columns for next time

### ISSUE THREAD

**Issue by AmitMY** [ceolter/ag-grid#823]
I am using the ag-grid for angular1, (and loving it), and I want my users to be able to reorgenize columns, change sortings, and everything, and that it will stay after a refresh.
It should not be very hard, except that the columns are circular (contains pointers to themselves), and thus I cannot parse them.

Code:
```
    var columnDefsKey = "columnDefs["+$rootScope.page+"]";
    var savedColumns = localStorage.getItem(columnDefsKey);
    function saveColumnsState() {
        var currentCol = vm.gridOptions.columnApi.getAllColumns();
        if (!angular.equals(currentCol, savedColumns))
            try {
                localStorage.setItem(columnDefsKey, JSON.stringify(currentCol));
            } catch (ex) {
                log(ex);
                log(currentCol);
            }
    }
```

And:
```
        onColumnEverythingChanged: saveColumnsState,
        onColumnVisible: saveColumnsState,
        onColumnPinned: saveColumnsState,
        onColumnResized: saveColumnsState,
        onColumnRowGroupChanged: saveColumnsState,
        onColumnValueChanged: saveColumnsState,
        onColumnMoved: saveColumnsState,
        onColumnGroupOpened: saveColumnsState,
```

It fails on the "try" every time:
TypeError: Converting circular structure to JSON(…) [Column, Column, Column, Column, Column, Column, Column, Column, Column, Column]

How can I do that?

**Comment by AmitMY** [comment]
Solved using specific column parameters and not copying all.

**Comment by ceolter** [comment]
you cannot save the Column objects, they contain functions, they are not simple objects you can convert to JSON.

to save state, use the api method getState and setState

**Comment by AmitMY** [comment]
I can, and I did :) Risking XSS, but it is a closed system so its kind of OK. (because I also allow adding custom columns to the tables)

**Comment by waheedahmed55** [comment]
I have ag-grid in which when user move a column let says from 3rd position to 1st position it stays there but upon refreshing the page it goes back to 3rd postion. I want somehow it to retain the position.

**Comment by AmitMY** [comment]
@waheedahmed55 As ceolter said, you can just use `getState` on every state change, and to save it to localstorage or whatever, then on first entry do `setState`

I can't share my code with you as I don't have it anymore, but my code was actually taking the entire state of the columns and grid, reducing it to what I need, then saving it to JSON (Even the functions)

**Comment by reshmip** [comment]
I am trying to save my column state of the ag-grid. so when I click on a save button or something, using gridOptions.columnApi.setColumnState(colState). But after the page refreshes it is reloading the previous default state.
How did it persist your column state?

**Comment by AmitMY** [comment]
I don't have the code, as it belongs to a company now, I can just tell you what I did.
After you get the column state, map it to a smaller version of it, keeping most of the essentials (essentials=keys you defined, not stuff that was added automatically).
Then, you can stringify that object as JSON, following: https://stackoverflow.com/questions/36517173/how-to-store-a-javascript-function-in-json

and save it to local storage.

When the user refreshes the page, get that stored state, and set columns state.

**Comment by arunkotagiri** [comment]
@AmitMY This one is working. Why do we need to stringify that object as JSON while saving state and parse JSON back to like object when we retrieve ?

Why getState() directly storing in localStorage & setState() directly from localStorage is not working ?

**Comment by AmitMY** [comment]
Local storage is a key-value dictionary where both the key and the value are strings.
You can't store something that is not a string, and definitely not functions.

**Comment by arunkotagiri** [comment]
@AmitMY / @ceolter 

I did as below to save column group state & restore column group state. Its not working some how. Any thoughts on what I am missing ?

**Save Logic to Local Storage:**
var columnGroupState = JSON.stringify(self.gridOptions.columnApi.getColumnGroupState(), function(key, value) {
										        			  if (typeof value === "function") {
										        			    return "/Function(" + value.toString() + ")/";
										        			  }
										        			  return value;
										        			});

localStorage.setItem("columnGroupState", columnGroupState);

**Retrieve Logic to Restore**

self.gridOptions.columnApi.setColumnGroupState(localStorage.getItem("columnGroupState"));

**Comment by AmitMY** [comment]
json parsing whem u get the item

**Comment by arunkotagiri** [comment]
@AmitMY I did that JSON parse too. But I missed code above.

Anyway i found issue. 

Initially I tried with ColumGroupState, so thought if that one works I wanted to use ColumnState, SortModel and FilterModel. It didn't if I use just ColumnGroupState.

Then I figured out that ColumnGroupState doesn't work as standalone. Then You need to set the ColumnState also along with ColumnGroupState .

One more thing to mention: We don't need to do use replacer/reviver as you mentioned at  [ https://stackoverflow.com/questions/36517173/how-to-store-a-javascript-function-in-json](url)

For these ColumnGroupState, ColumnState, SortModel and FilterModel, API returns JSObject with no functions in it. 

`self.saveState = function() {
        	if (typeof(Storage) !== "undefined") {
        		localStorage.setItem("columnGroupState", JSON.stringify(self.gridOptions.columnApi.getColumnGroupState()));
        		localStorage.setItem("columnState", JSON.stringify(self.gridOptions.columnApi.getColumnState()));
        	    localStorage.setItem("sortModel", JSON.stringify(self.gridOptions.api.getSortModel()));
        	    localStorage.setItem("filterModel", JSON.stringify(self.gridOptions.api.getFilterModel()));
        	} else {
        	    console.log("Sorry, your browser does not support Web Storage...");
        	}
        }
        
        self.restoreState = function() {
        	if (typeof(Storage) !== "undefined") {
        		self.gridOptions.columnApi.setColumnGroupState(JSON.parse(localStorage.getItem("columnGroupState")));
        	    self.gridOptions.columnApi.setColumnState(JSON.parse(localStorage.getItem("columnState")));
        	    self.gridOptions.api.setSortModel(JSON.parse(localStorage.getItem("sortModel")));
        	    self.gridOptions.api.setFilterModel(JSON.parse(localStorage.getItem("filterModel")));
        	} else {
        	    console.log("Sorry, your browser does not support Web Storage...");
        	}
        }`

**Comment by reshmip** [comment]
So, whenever I am pinning a column, I am trying to save the column state like below:

function onColumnPinned(params){
	colId = params.column.colId || undefined;		
	console.log("Column : "+colId+" is pinned to left");
	
	var currentColumnState = params.column.gridOptionsWrapper.gridOptions.columnApi.getColumnState();
	if(localStorage.getItem("columnDefsKey") == "null" || localStorage.getItem("columnDefsKey")=='undefined'){
		localStorage.setItem("columnDefsKey", "");
	}
	else{
		var savedColumnState = JSON.parse(localStorage.getItem("columnDefsKey"));
		
		if(!currentColumnState.equals(savedColumnState)){

			localStorage.setItem("columnDefsKey", JSON.stringify(currentColumnState));
			console.log("save column state");
	}
		else{
			console.log("no change in column state");
			}
	}
	
	
	params.column.gridOptionsWrapper.gridOptions.columnApi.setColumnState(JSON.parse(localStorage.getItem("columnDefsKey")));
	params.column.gridOptionsWrapper.gridOptions.api.setRowData(params.column.gridOptionsWrapper.gridOptions.rowData);
	
};

And when I load my grid I am checking for the local storage:

if(localStorage.getItem("columnDefsKey") != null){
			columns = JSON.parse(localStorage.getItem("columnDefsKey"));
			result.api.setRowData(result.rowData);
			result.columnApi.setColumnState(JSON.parse(localStorage.getItem("columnDefsKey")));

		} 

This works great as expected. But unfortunately, it is overriding the default settings like cellrenderes - cellRendererParams": {
        "checkbox": true
      }
or 
if (columns[i].colId === 'Name' || columns[i].field === 'Name') {
			    columns[i].headerCheckboxSelection = true;
			    columns[i].checkboxSelection = true;
			    
			
			  }
When I debug I found that getColumnState doesn't actually all the attributes in the columnDefs which is why it is overriding. Is there any way I can not loose this data.
@AmitMY  - "After you get the column state, map it to a smaller version of it, keeping most of the essentials (essentials=keys you defined, not stuff that was added automatically)." - smaller versions in the sense do I have to maintain multiple items in the local storage or are you appending all the essentials into a single string?

**Comment by shaziyali8** [comment]
Hello, everyone, I want to achieve a column state, 
The requirement is to save the state in the web API and restore it when the stored state is clicked.
So can anyone help me please, @AmitMY @arunkotagiri @waheedahmed55 @ceolter, please?
