### ISSUE TITLE
Virtual Pagination Only Shows 3 Rows

### ISSUE THREAD

**Issue by jhinckel** [ceolter/ag-grid#824]
Hi,

I have 2 tables. The first one contains cities. The second one contains addresses from selected city.
There is a button where I swap between tables (after I have selected the city, I click on addresses and the table change to addresses). I have one gridOptions for each table and I change the datasource when the city changes.
The problem appear where the list of addresses is less than pageSize (in my case 50). The table shows only 3 rows and show more only when I click to sort or roll scroll to down.

My config:

dataSource = {
	rowCount: null, // behave as infinite scroll
	pageSize: 50,
	overflowSize: 2,
	maxConcurrentRequests: 1,
	maxPagesInCache: 50
};
gridOptions = {
	columnDefs: this.retrieveColumnsHeader(tableView),
	enableColResize: true,
	virtualPaging: true,
	enableServerSideSorting: true,
        rowSelection: 'single',
	enableSorting: true,
	onSelectionChanged: gridOptionsOnChangeFunction,
	unSortIcon: true,
	suppressHorizontalScroll: true,
	minRowsToShow: 50,
	headerHeight: 30
}; 

Anyone known what is happening?

**Comment by ceolter** [comment]
please keep with github for issues with the grid (ie grid is broke), for help using the grid, please use the forum on www.ag-grid.com

regards teh question, i don't see anything wrong. if you can in plunker then someone could look.

**Comment by ceolter** [comment]
closing, as it's not an issue with the grid, but more likely user looking for help.

**Comment by smelyakov** [comment]
I've also run into this. It seems like it's connected with changing display property. Here is the plunk https://plnkr.co/edit/WLinh55zkE0T4JQeiBoV?p=preview (fork from another issue, if anyone cares)

**Comment by smelyakov** [comment]
@ceolter 
I've tried some of previous releases. The issue has been there since 3.3.0-alpha.1
