### ISSUE TITLE
[component header] allow headerCellRenderer and headerTemplate to work for column groups

### ISSUE THREAD

**Issue by HowCome** [ceolter/ag-grid#825]
[If](url) you specify  headerCellRenderer either in the columnDefs for individual columns or in gridOptions for all columns it is called instead of the default header renderer. Everything is nice and dandy. However when a column is a group column i.e has children this option is ignored and the rendering always go to the internal ag-grid renderer. Seems like a very major issue unless I am missing something.

Here is sample code to demonstrate it. Despite the custom header renderer is set for the entire grid if a column has children it ignores it:

[http://jsfiddle.net/HowCome/8chz9cne/)

**Comment by pauljoey** [comment]
I am having a similar issue whereby sorting markers (up/down arrows) are not injected/shown if I specify a `options.getHeaderCellTemplate` function (even if it returns an exact copy of the default template).

**Comment by HowCome** [comment]
Yes neither renderer function nor header template works for columns with children, so basically there is no straightforward way to change the the header look or add some functionality. I would be interested to see a workaround if there any short of finding the header HTML element and modifying it.

**Comment by pauljoey** [comment]
In my case, it is applicable to all column headers regardless of their grouping status.

**Comment by pauljoey** [comment]
Upon further investigation, the issue that I'm experiencing is that `#agSortDesc` inside of the template returned by `getHeaderCellTemplate()` is not being populated with the sort icon SVG. On reflection, that's probably the intended and preferable behaviour - that I embed the icon SVG into the template returned by `getHeaderCellTemplate()` directly.

**Comment by HowCome** [comment]
The point of this issue is that getHeaderCellTemplate does not work for group columns at all. See the jsfiddle in the OP.

**Comment by hank7444** [comment]
+1, I tried add headerCellRenderer for my grouping columns but it doesn't work

**Comment by guygervais** [comment]
Same here.

We'd like to use the custom cell renderer to allow toggling between languages without having to go to the server... everything works fine (so far), except for the header group cells.

**Comment by ceolter** [comment]
tracked by AG-117
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by ceolter** [comment]
now done. next release will have new Header Component and Header Group Component - allowing the header and header groups to work similar to how cellRenderer is currently working
