### ISSUE TITLE
setFilterModel is broken in Angular2

### ISSUE THREAD

**Issue by icnec** [ceolter/ag-grid#826]
the setFilterModel api call does not work in angular2.  The column shows the 'filter' icon, but upon clicking the filter button of the column, the type and textbox are the default values that the grid loads with.  The grid is also not filtered.

Repro steps
1. setup a grid in angular2 that allows for filtering.  Capture the aftersorted event for storage of the api.getFilterModel() object.  Attempt to set this object on a fresh grid and you will see the behavior listed above.  On the plus side....getsortmodel and setsortmodel are working perfectly.

**Comment by fluky** [comment]
I am also seeing this behavior.

**Comment by fluky** [comment]
Ok, I managed to get this working.  Looks like the data load clears the filters (but not the icon) so if you load the filters on gridReady and you're loading data via Ajax the data load will clear the filters.

I had to to move the setFilterModel call to the function that sets the row data and use a timer to make sure it happens after the digest.

**Comment by ceolter** [comment]
when you load data into the grid, the filters are reset.

to stop this, update the property on the filter as follows, the item of note is 'newRowsAction':
```
columnDefinition = {
    headerName: "Athlete",
    field: "athlete",
    filter: 'text',
    filterParams: {newRowsAction: 'keep'}
}
```

this property is mentioned in docs
http://localhost/javascript-grid-filtering/index.php

**Comment by fluky** [comment]
@ceolter it would be nice to have this settable for the entire grid rather than have to set it for every column

**Comment by ceolter** [comment]
true. thanks for feedback.
