### ISSUE TITLE
Group cell edit

### ISSUE THREAD

**Issue by jlame** [ceolter/ag-grid#828]
I'm trying to find a way to display rows which can expand and show other rows, for that i used the treedata example (grouping) but something is missing for it to fully meet my need : 
I need the first row (the group row) to be editable too.

This might be a feature request though ...

So i need the first line of each group (the group line) to be editable and if possible to fill the group column with a value. 
Maybe that's not possible by using groups, in that case is there anyway to achieve something like this ?

Thanks.

**Comment by ceolter** [comment]
what your cells do is up to you. so provide your own cellRenderer to do whatever you want.

the grid can help by using a combination of these:
+ provide floating row, so the first row is not part of your group. then the grid can do it's grouping and not use this row.
+ provide a different cellRenderer for the floating row. this can help with your edit feature. alternatively, you can see what the row is in your cellRenderer and render differently if it's the first row.
+ if not using floating for first row, then don't use grid grouping, provide the data already grouped, which will then let you have the first row 'not in a group' if you wish.

full row editing is something i plan to do, but no release date yet.
