### ISSUE TITLE
Easier and better access to older versions documentations

### ISSUE THREAD

**Issue by lucaspmarra** [ceolter/ag-grid#8282]
**I'm submitting a ...**
```
[] bug report => see 'Providing a Reproducible Scenario'
[X] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Expected behavior**
A dropdown button for version select of ag-grid in documentation page. Currently, in order to access older versions of the documentation, the user has to search on google to land on the Archive page: https://www.ag-grid.com/documentation-archive/
It would be wise to make access easier - something that is not the case in the Ag-Grid documentation.

**Comment by AG-Zoheil** [comment]
Hi @lucaspmarra,

Thanks for getting in touch about this.

The documentation archive can be directly accessed via the footer on our website.

Thanks!

**Comment by lucaspmarra** [comment]
Hey @AG-Zoheil 
Search for specific data or function in documentation archive is not working, that is the correct behavior?

**Comment by AG-Zoheil** [comment]
Hi @lucaspmarra,

Currently this is the expected behaviour. We are in touch with our search engine provider to see if this is something that can be changed but it's not directly in our hands here in AG Grid I'm afraid.

Thanks!
