### ISSUE TITLE
Add property to disable 'dragging column out of grid removes from grid'

### ISSUE THREAD

**Issue by light049** [ceolter/ag-grid#829]
Is there way to disable drag leave to column header?
Coz this behavior would make column remove which I don't want.
I just need column reorder behavior but it seems unavailable to just disable drag column leave.

Thanks~

**Comment by ceolter** [comment]
no such property. i've change the title and will try and get this done.

**Comment by daljeetsingh1985** [comment]
When can we expect this property to be implemented? Is there any other way to implement this in meantime?

**Comment by ceolter** [comment]
it's done. will be in next release. the property is suppressDragLeaveHidesColumns

next release should be next week.

**Comment by daljeetsingh1985** [comment]
Can we disable column drop outside the grid area? currently, if i drop column anywhere grid area on BODY, columns gets hidden. Can we have a property which will only allow to move and reorder the columns but not allow to drop the column by drag and drop feature?

**Comment by ceolter** [comment]
@daljeetsingh1985 see above
```
it's done. will be in next release. the property is suppressDragLeaveHidesColumns, next release should be next week.
```

**Comment by cc1000** [comment]
Is there any way to suppress the remove (minus sign) icon that shows when dragging? With this `suppressDragLeaveHidesColumns` set to true this still appears.

**Comment by ceolter** [comment]
@cc1000 no - but you could provide your own 'empty' icon, see how to configure icons in the docs

**Comment by AnaSofiaGrilo** [comment]
Hello!

I'm trying to use this property, but its not working ....
In columnDefs, I had setted all columns with suppressDragLeaveHidesColumns: true and yet they continue to disappear when dragged out of the grid.

I tried the demo in your website (https://www.ag-grid.com/example.php) and also have this problem.

**Comment by ceolter** [comment]
@AnaSofiaGrilo suppressDragLeaveHidesColumns is a grid property, not a column property.

**Comment by AnaSofiaGrilo** [comment]
@ceolter Thanks! It's working ;)

**Comment by ShinShil** [comment]
Would be good to have such property for ColDef and ColGroupDef
