### ISSUE TITLE
Grid-Grouping: Change background of grouped column in grouping

### ISSUE THREAD

**Issue by shivekundefined** [ceolter/ag-grid#832]
How to change the background color of grouped column in amazing-grid? I have gone through each and everything on [https://www.ag-grid.com/angular-grid-grouping/index.php](url) but did not find what I wanted to generate. Please see the Image below.

![data browser - mapped data](https://cloud.githubusercontent.com/assets/17401303/14464136/4d6fb6ae-00eb-11e6-902e-549064965ba5.png)

I am able to achieve this for the individual records by using cellrender but not for grouped records.

**Comment by ceolter** [comment]
use getRowClass callback.
```
gridOptions.getRowClass = function(params) {
  if (params.node.group) {
    return 'background-green';
  }
}
```

**Comment by shivekundefined** [comment]
Thanks for your reply..
I have used 

`gridOptions.cellStyle = function( params ) {`
`       return $scope.getColor(params.node.key); // function will returns the inline CSS `
     `        //OR return ' background : green ' ;` 
	`},`

which also worked..
Thanks BTW..

**Comment by ceolter** [comment]
getRowClass mentioned here:
https://www.ag-grid.com/javascript-grid-callbacks/index.php

am not sure if it's in an example
