### ISSUE TITLE
How to add new Custom column in ag-grid

### ISSUE THREAD

**Issue by shivekundefined** [ceolter/ag-grid#834]
Hoe to add Custom columns dynamically in ag-grid. I have tried following approach.
`additionalCol = { field:'SOME RANDOM', headerName: 'SOME RANDOM' };`
`$scope.gridOptions.columnApi.addValueColumn(additionalCol);`

I have also tried
`$scope.columns.push(additionalCol);`
`$scope.gridOptions.api.refreshView();`
but didn't get success. I even tried to add columns that exist in Data but failed.

Below is Image for what I wanted.
![customcol](https://cloud.githubusercontent.com/assets/17401303/14491194/0c4a119c-0195-11e6-8e3c-ef36d7cd5d5b.png)

As shown in image "**% dev**" is Custom column which I need to add dynamically with dynamically calculated values.

**Comment by ceolter** [comment]
you need to set the set of columsn again, eg api.setColumnDefs()

if you don't want all columns appearing initially, then set them to not be visible

**Comment by shivekundefined** [comment]
I have done same thing.. Thanks..

**Comment by Lazarencjusz** [comment]
Setting columnsConf again cause group back to collapse/expand state (depend on init conf), at least for react app.

**Comment by tncho** [comment]
@Lazarencjusz  have you managed to keep the column state the same while adding a column? Do you mind sharing your solution? Thanks in advance 👨‍💻

**Comment by shwetamukta** [comment]
Hi, I want to replace field: 'broadcastHtml' to a variable here like field:this.tempVar.broadcastHtml (This vlue this.tempVar.broadcastHtml I am getting from program which is an array.)
Is it possible do it as I see no data is being rendered.
Here is my .ts file. Don't worry about NxAgGridModule. (This is our internal ag-grid)

import { Component,ViewChild } from "@angular/core";
import { NxAgGridModule } from 'nx-components/nx-ag-grid';
import { NgModule } from "@angular/core";
import { GridOptions } from 'ag-grid-community';
import { BroadcastService } from "../../service/yte-pl.broadcast.service"

import {
    NxAgGridAction,
    NxAgGridComponent,
    NxAgGridActionsRendererComponent,
    NxAgGridSettings,
    NxPdfOptions
} from 'nx-components/nx-ag-grid';

@Component({
    selector: "broadcast-message",
    styleUrls: ["./broadcast-message.css"],
    templateUrl: "./broadcast-message.html"
})

@NgModule({
    imports: [
        NgModule,
        NxAgGridModule,
    ]
  })

export class BroadcastMessageComponent {

    @ViewChild(NxAgGridComponent) _grid: any;
    complexRowdata: any;
    testVar:any;
    testVar1:any;
    tempVar:any;
    makeCol:any;
    columnDefs :any;
    gridOptions:any;
    frameworkComponents:any;
    selectedRows: any = [];
    selectedRowActions: Array<NxAgGridAction> = [];

    customExport(){
    }
    
    myPdfOptions: NxPdfOptions = new NxPdfOptions({
        title: 'development-app-gird.pdf',
        header: 'Development Application - Activity',
    });

    complexColumnDefs = [
        this.agGridSettings.SELECTION_COLUMN,
        {
            headerName: 'broadcast Count',
            field: 'broadcastCount',
            width: 200,
            enableRowGroup: true,
            enablePivot: true,
            filter: 'number'
        },
        {
            headerName: 'Broadcast Service',
            field: 'broadcastService',
            width: 200,
            enableRowGroup: true,
            enablePivot: true,
            filter: 'text'
        },
        {
            headerName: 'Broadcast Message',
            field: 'broadcastHtml',
            width: 200,
            enableRowGroup: true,
            enablePivot: true,
            filter: 'text'
        }
    ];

    public messages:any = [];
    constructor(private agGridSettings: NxAgGridSettings,
                private broadcastService:BroadcastService) 
        {
        this.gridOptions = <GridOptions>{};
        this.frameworkComponents = {
            actionsRenderer: NxAgGridActionsRendererComponent
        };
    }

    ngOnInit() {
        this.broadcastService.getMessages()
            .subscribe(result => {
                this.complexRowdata = result;
                this.testVar = this.complexRowdata[0].broadcastHtml;
                this.testVar1 = this.testVar.split("|");
                this.testVar1.forEach(element => {
                    this.tempVar = {
                        "broadcastCount":"",
                        "broadcastService":"",
                        "broadcastHtml":this.testVar1
                };
             });
             console.log("Temp Var",this.tempVar.broadcastHtml); --> I want to render this value for the value of field in complexColumnDefs (field: '**broadcastHtml**')
             //return this.tempVar;
        }); 
    }
<img width="957" alt="ag-grid" src="https://user-images.githubusercontent.com/15328724/50493244-40764200-09ea-11e9-91ac-5d8241cb2c64.PNG">


    // handle setting selected items
    onSelection() {
        this.selectedRows = this._grid.gridApi.getSelectedRows();
    }
}

**Comment by shwetamukta** [comment]
Here is my Json.
{
  "messages": [
    {"broadcastCount":11,
	"broadcastService":"",
	"broadcastHtml":"First Service Message|Test Message|Test Message|Test|Broadcast Message 1290|Broadcast Message - Account Recon|Broadcast Message - Balance Reporting|Test Message|Broadcast message - Balance Reporting 12/14|33669 Test Message|Test Msg from development"}
	]
}
