### ISSUE TITLE
cellRenderer (mouseenter)="changeClass" not firing in angular2

### ISSUE THREAD

**Issue by kedomonzter** [ceolter/ag-grid#836]
Im trying to add a mousenter event in a cellRenderer and it doesnt fire.
```ssh
tooltipRenderer(params)
    { 
return '<a href="#" (mouseenter)="changeClass" [ngClass]="{open: isOn, disabled:isDisabled}">params.value</a>';
}
```

**Comment by ceolter** [comment]
ag-grid does not support angular 2 templates.

see the note on angular compiling here:
https://www.ag-grid.com/best-angular-2-data-grid/index.php
