### ISSUE TITLE
BUG: Selection count wrong after ungrouping

### ISSUE THREAD

**Issue by ivanbaj** [ceolter/ag-grid#838]
1. https://ag-grid.com/example.php
2. Group by Language
3. Click + in front of English
4. Select "Sophie Beckham" (Log: Callback selectionChanged: selection count = 1)
5. Ungroup Language ("Sophie Beckham" shows as selected)
6. Select "Isabelle Black" 

(Log: Callback selectionChanged: selection count = 1)

UI shows "Sophie Beckham" and "Isabelle Black" selected.

gridOptions.api.getSelectedNodes().length is 1 should be 2.

**Comment by ceolter** [comment]
this is fixed in the most recent. i'm planning on next major release next week.
