### ISSUE TITLE
[Feature] suppressRowCopy - so ctrl+c will always copy range, never the rows

### ISSUE THREAD

**Issue by AmitMY** [ceolter/ag-grid#840]
I dont like/need that when a row is selected, and I am focused on a cell, I copy the row and not the cell, it is confusing for me, and I built a copy just to go around it that forcely copies the cell, and does not work 100% of the time.

I would suggest a SuppressRowCopy to be added to the clipboard API, and when set to "true", will just not copy rows, ever.

What do you think?

**Comment by ceolter** [comment]
sounds fair

**Comment by AmitMY** [comment]
@ceolter I don't wanna be a jerk, but is there a time-frame? I use a custom copy function for now that... does not work 100%

**Comment by ceolter** [comment]
@AmitMY sorry for asking, but are you an enterprise customer? which company are you with?

**Comment by AmitMY** [comment]
I was sure a trial license exists, and I see it still does.
Anyway, just now moving to approval on buying the enterprise version. What is "customer number"? That is not clear at all..

**Comment by ceolter** [comment]
you email accounts@ag-grid.com with your order, they give you a customer number with the invoice

**Comment by AmitMY** [comment]
Closed for being an enterprise feature. Reopened https://github.com/ceolter/ag-grid-enterprise/issues/30
