### ISSUE TITLE
Empty space at the bottom of the grid.

### ISSUE THREAD

**Issue by HowCome** [ceolter/ag-grid#842]
When a grid height is not specified it grows to accommodate all rows plus some empty space at the bottom about 8 pixels or so. For example if the table has 3 rows the size is 83 pixels despite only 75 is needed.  If I go dig out the html element of the grid and set style height to 75 pixels the grid has the exact size to show all information but unfortunately displays a scrollbar even though it is not needed.
This is problematic if you have several small grids above each other.

**Comment by ceolter** [comment]
the grid is not designed to be 'auto height'. you set the height via css.

there is another issue already opened for auto-height.
