### ISSUE TITLE
[Bug/Feature] Filtering and Grouping on Combined Columns

### ISSUE THREAD

**Issue by mucellid** [ceolter/ag-grid#843]
When use cellrenderer, filtering and grouping don't work.
For example, I want to display first name and last name in the same column. Or I want list person's hobbies in a single column like;
     'Name',                            'Hobbies'
'Josh Edwards',      'Football, Basketball, Tennis' 
 
However, if I use object.firstname + object.lastname to display the Name in a single column or combine the person's hobbies in a single column, filtering and grouping don't work.

**Comment by AmitMY** [comment]
I encountered this bug too.
Its not that it doesnt do what you want it to, it just throws errors in console.

The solution I got (for now) is use valueGetter: String to do your cellrendering. You can have if/else using ?: operator, and it is ugly, but it works.

**Comment by ceolter** [comment]
for grouping to span columns, use valueGetter, cellRenderer is not used in the grouping process.

same will work for filtering. however if that default result doesn't work, you can provide your own filter.
