### ISSUE TITLE
from moving from 3.x to 4.x set data source not working

### ISSUE THREAD

**Issue by Wingie** [ceolter/ag-grid#845]
````
if (!$scope.gridOptions.datasource) { // must attach datasource only once
        $scope.gridOptions.datasource = $scope.dataSource;
        console.log($scope.gridOptions)
        $scope.gridOptions.api.onNewDatasource();
      }
````
i'm getting an error 

````
build.min.js:25996 TypeError: Cannot read property 'onNewDatasource' of undefined
    at init_datasource (build.min.js:131911)
    at new SearchResultProjectsCtrl (build.min.js:131633)
    at Object.invoke (build.min.js:17364)
    at extend.instance (build.min.js:22615)
````

to note that i did not need the ` $scope.gridOptions.api.onNewDatasource();` when i was on 3.0.3
just updated now and went through documentation and found this change.
without the `.api.onNewDatasource();` the issue was that nothing was displayed on the screen

**Comment by ceolter** [comment]
onNewDatasource() is not used in the new version. please check the docs.

**Comment by GustavSt** [comment]
In the [Datasource section](https://www.ag-grid.com/angular-grid-datasource/index.php) of the docs it says this is possible way to add datasource.

```
// way 1 - set the the datasource using the API
gridOptions.api.setDatasource(myDataSource);

// way 2 - set the the datasource directly and inform the grid a new datasource is there
gridOptions.datasource = myNewDatasource;
gridOptions.api.onNewDatasource();
```

**Comment by ceolter** [comment]
sorry for this. docs are out of date. i've fixed and they will be updated with the next release.

**Comment by dtslvr** [comment]
Could you please share the solution with us?

**Comment by ceolter** [comment]
use:

```
// way 1 - set the the datasource using the API
gridOptions.api.setDatasource(myDataSource);
```
