### ISSUE TITLE
Drag and drop column to reorder them cause all other elements bellow the table to be highlighted (blue)

### ISSUE THREAD

**Issue by BesatZardosht** [ceolter/ag-grid#846]
when I move a column it highlights every elements in the page including page footer!!

any help is appreciated!

**Comment by BesatZardosht** [comment]
![screen shot 2016-04-19 at 10 50 51 am](https://cloud.githubusercontent.com/assets/9285802/14644118/ec60c11c-061e-11e6-80c3-4eb230c21ee2.png)

**Comment by ceolter** [comment]
without an example of it broken, can't say what's wrong.

do you have steps on how to reproduce in an online example?

**Comment by BesatZardosht** [comment]
Unfortunately I cant provide an online example. but as soon as I drag a column to move it every other element in the page get highlighted and when I click anywhere on the page it goes away (deselected).
I added the simplest table with just few columns and few rows. nothing complicated.

**Comment by etiennecrb** [comment]
I have the same issue...

**Comment by BesatZardosht** [comment]
I fixed it:
in your body add this class:
`unselectable`

and then in your css add the class:

```
.unselectable {
   -moz-user-select: -moz-none;
   -khtml-user-select: none;
   -webkit-user-select: none;

   /*
     Introduced in IE 10.
     See http://ie.microsoft.com/testdrive/HTML5/msUserSelect/
   */
   -ms-user-select: none;
   user-select: none;
}
```

**Comment by smelyakov** [comment]
@BesatZardosht 

Well, that's not a solution actually as you are not able to select anything now.

**Comment by BesatZardosht** [comment]
Yes. it's just a workaround.. but I have no other solution yet

**Comment by ceolter** [comment]
something i could do is add callbacks, so you can listen for 'drag start' and 'drag stop' or the grid, so you only apply the hack when the grid is dragging.

however you guys have to be doing something in your apps that noone else is doing, as this isn't a common problem. can idea what you have that is causing the conflict??? i'm guessing it's a CSS style or something you have set???

**Comment by hesselmeulenbeld** [comment]
Here is a plunker which shows this: [plunker](http://plnkr.co/edit/T9HIClbuhH7qrw23zl6V?p=preview)
It occurs at least when using chrome Version 51.0.2704.79 (64-bit)

**Comment by ceolter** [comment]
just implemented - i add / remove the class to body when dragging starts / stops. will be in the next release (will be about two weeks, i want to finish pivoting first)
