### ISSUE TITLE
Row Selection during grouping not working properly.

### ISSUE THREAD

**Issue by crushikesh** [ceolter/ag-grid#848]
Hi,

The Row Selection style is not working properly during group By specific column using option in column filter menu in enterprise version. Grid Property is RowSelection: 'Single' 

Scenario: Suppose i have a grid with selected single row. When i drag a column in group then its apply grouping and showing selected row as last one. but once if i change the row selection their then it persist last one and select other. I need to release the previously selected row.
Please help me.

**Comment by crushikesh** [comment]
Here the codepen for the above scenario  [http://codepen.io/crushikesh/pen/bpKMJL](url)

And references screenshots by steps 
![1](https://cloud.githubusercontent.com/assets/16801373/14675146/63e4d942-06bc-11e6-8fb6-5ee8846599cd.jpg)
![2](https://cloud.githubusercontent.com/assets/16801373/14675154/6908bede-06bc-11e6-94d2-0c07dba45c5a.jpg)
![3](https://cloud.githubusercontent.com/assets/16801373/14675157/6d9ce8da-06bc-11e6-9d72-c1f1459dab5f.jpg)
![4](https://cloud.githubusercontent.com/assets/16801373/14675162/7070d9a4-06bc-11e6-8a49-880e3cfdc52a.jpg)

**Comment by ceolter** [comment]
not sure i fully understand, however there was an issue with grouping and selection that i now fixed. it will be in the next release next week.

is it related to this:
https://github.com/ceolter/ag-grid/issues/838
(the one i fixed)

**Comment by crushikesh** [comment]
Hi,

Please take a look at  [http://codepen.io/crushikesh/pen/jqKxXK
](url), Which describes the above scenerio. Thanks

**Comment by ceolter** [comment]
i'm emailing crushikesh directly, so closing here to remove duplication.
