### ISSUE TITLE
headerCellTempate not parsing angular directive

### ISSUE THREAD

**Issue by itsmefirealex** [ceolter/ag-grid#850]
Please let me know that headerCellTemplate will parse angular directive

Grid header :
-----------------

{ headerName: '', width: 30, checkboxSelection: true, suppressSorting: true, suppressMenu: true, pinned: true,   	headerCellTemplate : '<select-all-directive />' }

Directive :
-------------
angular.module ('app').directive ('selectAllDirective', function () {
		return {
			replace : true,
			restrict: 'E',
			scope : {},
			template : '<input type="checkbox" id="checkall" />'
		};

**Comment by ceolter** [comment]
not possible, including angular in the headerCellTemplate is not supported.
