### ISSUE TITLE
Invalid column state seems improperly handled in `setColumnState`

### ISSUE THREAD

**Issue by remibd** [ceolter/ag-grid#851]
Hi!
In the following snippet of code, extracted from `dist/ag-grid.js` lines 3239 to 3254, the variable `oldColumn` is sometimes undefined, and `oldColumn.setVisible(…)` raises an exception:

```javascript
ColumnController.prototype.setColumnState = function (columnState) {
    var oldColumnList = this.allColumns;
    ...
    if (columnState) {
        columnState.forEach(function (stateItem) {
        var oldColumn = utils_1.Utils.find(oldColumnList, 'colId', stateItem.colId);
        if (!oldColumn) {
            console.warn('ag-grid: column ' + stateItem.colId + ' not found');
            success = false;
        }
        oldColumn.setVisible(!stateItem.hide); // EXCEPTION HERE!
        ...
```
It looks like it is not the desired behavior, since it might simply cut off the grid generation (and pollutes the console with big flashy red exceptions just after the more tactful `console.warn`).

Is it the expected behavior?

Thanks in advance

**Comment by ceolter** [comment]
code above is wrong, it's actually:
```
                if (!oldColumn) {
                    console.warn('ag-grid: column ' + stateItem.colId + ' not found');
                    success = false;
                    return;
                }
```
it you are missing the return statement. maybe you are on an older version, what you describe doesn't happen in the latest.

**Comment by remibd** [comment]
Haven’t you added that `return` statement [yesterday](https://github.com/ceolter/ag-grid/commit/eb3fe1c4e675fcb077aa4b114fa4b4730d9bc6c0#diff-793f63d92e43d8941bd40a9954715d80R566)?

**Comment by ceolter** [comment]
i released yesterday. i can't remember when i actually added it!!
