### ISSUE TITLE
setDatasource(dataSource) doesn't give you datasource on gridoptions

### ISSUE THREAD

**Issue by GustavSt** [ceolter/ag-grid#854]
Before when adding the datasource through the function it was added to the gridOptions. Currently it is not.

If it shouldn't, what is the intended way of getting a grids datasource?

**Comment by ceolter** [comment]
there is no way of getting the datasource.

if you need it, i suggest you keep a local reference to it. or you can set it into gridOptions yourself (the grid will ignore it) when you call the api.
