### ISSUE TITLE
[Feature] Expand row to see a list of its details

### ISSUE THREAD

**Issue by johnib** [ceolter/ag-grid#857]
Hi,

I've been examining the set of features this grid offers.
For starters, it looks pretty amazing and gives the feeling that what can be done with it is limitless.

Yet, I'm missing one important feature, expanding rows to see a list of the rows properties and values.
As you can see in the following two images, I have a set of rows, which one of them is expanded in the second image, showing me all the columns' values in a list.
![unexpanded](https://cloud.githubusercontent.com/assets/5327862/14785399/3cc247aa-0b03-11e6-8c0f-cdbef7f8524e.png)

![expanded](https://cloud.githubusercontent.com/assets/5327862/14785398/3ca23776-0b03-11e6-907a-edd0aeb7eca9.png)

I'm looking for something like this in Ag-gird.
I was wondering if this can be accomplish using the current features and if not, at least see if this feature is planned for the near future.

Thanks a lot.

**Comment by ceolter** [comment]
you can do this, but you will have to provide the data to the grid already grouped.

look at the file explorer example or the tree example for providing already grouped data.
https://www.ag-grid.com/javascript-grid-tree/index.php
https://www.ag-grid.com/example-file-browser/index.php

the grid will not the grouping or aggregation for you. but it does give you full control on what's in each row.

**Comment by balguri23** [comment]
Some details can be showed on expanding the row. Can we acheive this with out grouping the data. As we need to pass the same row as child if we go with current implementation. Can someone please help on this requirement? Just like selection we can have a button column to show and hide the detail template.
