### ISSUE TITLE
`setRowNodeExpanded` does not work as expected in `Tree Data` mode

### ISSUE THREAD

**Issue by Laxy317** [ceolter/ag-grid#8573]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
I have some rowData both group by row and column, such as:
```
{
      orgHierarchy: ["rowA"],
      colA: "row1 colA total",
      colB: "row1 colB total",
  },
 {
      orgHierarchy: ["rowA", "colA"],
      colA: "aaa",
  },
  {
      orgHierarchy: ["rowA", "colB"],
      colB: "bbb",
  }
``` 
I want display group rows `orgHierarchy: ["rowA", "colA"]` while click the `row1 colA total` cell; So I added `onCellClicked` event, filtered current child nodes and call `api.setRowNodeExpanded`, but nothing happened. Why there is no node expand?

You can try: https://codesandbox.io/p/sandbox/group-selects-children-forked-rrjxwl?file=%2Fmain.ts%3A43%2C15-43%2C33

**Expected behavior**
Expand all `orgHierarchy: ["rowA", "colB"]` rows, while clicked the `row1 colA total` cell

**AG Grid version:** 
32.1.0

**Comment by ava-utting** [comment]
Hi,

Thanks for reaching out.
I noticed in your sample you had set **groupDisplayType: 'custom'** which was preventing the data from being shown in the tree data structure.
Here is an altered sample: https://codesandbox.io/p/sandbox/group-selects-children-forked-4jzkpc?file=%2Fmain.ts%3A32%2C5

You should be able to expand the rows without having to use the onCellClicked event.

Best,

**Comment by Ardear** [comment]
> Hi,
> 
> Thanks for reaching out. I noticed in your sample you had set **groupDisplayType: 'custom'** which was preventing the data from being shown in the tree data structure. Here is an altered sample: [codesandbox.io/p/sandbox/group-selects-children-forked-4jzkpc?file=/main.ts:32,5](https://codesandbox.io/p/sandbox/group-selects-children-forked-4jzkpc?file=%2Fmain.ts%3A32%2C5)
> 
> You should be able to expand the rows without having to use the onCellClicked event.
> 
> Regards, Ava

Sorry, for reasons, I want to hidden the colomun `Organisation Hierarchy`, and I just want to expand on some of these lines. 
Like `orgHierarchy: ["rowA", "colA"]`,not both `orgHierarchy: ["rowA", "colA"]` and `orgHierarchy: ["rowA", "colB"]`(Beacuse autoGroupColumn will open the group "rowA")
