### ISSUE TITLE
Pagination control persists on Ang state change

### ISSUE THREAD

**Issue by will-tr** [ceolter/ag-grid#859]
Not sure if this bug is appearing based on my setup, however I have 2 grids, each on 2 separate angular(1.x) routes.

Grid 1 is using data source and pagination.
Grid 2 is using the normal rowModelType.

When I load grid 1 first, pagination controls show correctly.
When i load grid 2 first, pagination controls are hidden correctly.

If I load grid 1 first, then change states to grid 2, grid 2 now shows pagination controls.

Is there an option or api call I can use to force hide pagination controls or refresh the table?  I tried api.refreshView but that didn't seem to work.

Thanks and great work btw.

**Comment by ceolter** [comment]
no idea what's happening, haven't heard of anything like this.

i suggest you debug through the ag-grid code. look for method 'createSouthPanel' and see why it's not putting in the pagination panel. maybe it's not picking up the property.

to 'reset' the grid, you could put an ng-if on the div, and then toggle it on and off in two timeouts. it's a tick to get the grid to destroy and recreate itself.

**Comment by will-tr** [comment]
@ceolter Thanks for your help.  I followed your advice and followed the breadcrumbs starting from createSouthPanel method and get the issue fixed.

Turns out I didn't explicitly set gridOptions.rowModelType to null on the other view (non-paginated), so it must have picked up pagination from the other view.
