### ISSUE TITLE
Disable access to ToolPanel

### ISSUE THREAD

**Issue by mikeerickson** [ceolter/ag-grid#861]
Looking for a way to complete disable access to the ToolPanel?   The only thing I can find is the ability to control its display (showToolPanel) but nothing to complete remove access?

Is this possible and I am missing something?  I have scoured the docs and have not found anything

**Comment by ceolter** [comment]
the only way to show it is via the menu, and you can customise the menu to remove this item.

**Comment by mikeerickson** [comment]
@ceolter Awesome, that is what I wanted to know.,
