### ISSUE TITLE
Blank filter is not working for agNumberColumnFilter in tree data.

### ISSUE THREAD

**Issue by sathyaNarayanC** [ceolter/ag-grid#8629]
Reproducible Scenario
- Click the Size column filter icon, select the 'Blank' filter from the dropdown list.
- https://plnkr.co/edit/0gYLJmtjPxf9nQXu?open=app.component.ts

Issue Description:
Blank filter is not working for agNumberColumnFilter and agSetColumnFilter in tree data.

![image](https://github.com/user-attachments/assets/6bbafdc7-31e7-44d0-bdf7-c4863ca5fd3a)

Click the Size column filter icon, select the 'Blank' filter from the dropdown list.
Current behavior.
Grid is not filtering the blank data upon applying blank filter.
 - Shows all the data after applying the blank filter (Documents, Music, temp.text)
Expected behavior. 
Grid should filter only the blank data upon applying blank filter. 
 - Should show only blank data (Music, temp.text)

* **AG Grid version:** 32.1.0

* **Browser:** Chrome 125.0.6422.77
* **Language:** [all | TypeScript 4.9.5 | ES6]

**Comment by AG-Zoheil** [comment]
Hi,

Please see the description provided at the start of this section regarding parent rows and child rows when filtering: https://www.ag-grid.com/javascript-data-grid/tree-data-filtering/#filtering
