### ISSUE TITLE
warning when setting rowModelType : 'normal'

### ISSUE THREAD

**Issue by GustavSt** [ceolter/ag-grid#864]
In 4.0.x this works fine but in 4.1.x the console spits out
`ag-Grid: count not find matching row model for rowModelType normal` when normal is explicitly set.

The documentation state this should be a valid value to set.

My set up is I have "default"-gridoptions where I set 'pagination' which is the case for most of my grids, so in a few places I need to override my default back to normal, but then this warning shows up.

[plunker](https://plnkr.co/edit/USrHovbAwj4sUXOzkHJ6?p=preview) and if you open the console you will se the error/warning

**Comment by ceolter** [comment]
can you set it to undefined?

**Comment by GustavSt** [comment]
That worked!

Usually I prefer to set stuff to null and not undefined, which worked fine in this case as well. Do you think there is any difference?

**Comment by ceolter** [comment]
i'll fix it so 'normal' doesn't throw an error.

no real different, i shouldn't be making the differentiation in the grid code.

**Comment by zatziky** [comment]
Hi @ceolter, we are still experiencing this issue in version `6.2.1`. We've been waiting for warning to be remove since versoin 4.0. Has it ever been fixed or is it something in our settings?

**Comment by zatziky** [comment]
Ok, setting it to `undefined` from `'normal'` solved it. I hope we will not find any issues when it's not explicitly set to `'normal'`...
