### ISSUE TITLE
Auto size row height?

### ISSUE THREAD

**Issue by mikeerickson** [ceolter/ag-grid#865]
Does ag-grid have the ability to autosize row height based on displayed data?

**Comment by mikeerickson** [comment]
Found this in documentation in case you are wondering

https://www.ag-grid.com/javascript-grid-row-height/index.php

**Comment by skmohsin** [comment]
Same issue I face, I am using ag-grid version 3.3.0 and there is no such provision to set auto height.
How could I achieve autoheight as latest ag-grid provide??
