### ISSUE TITLE
[4.1.x] Inconsistent injection of custom Editor/Filter/Renderer params.

### ISSUE THREAD

**Issue by DChau10** [ceolter/ag-grid#866]
I find it to be very inconsistent that for custom renderers and custom editors, the original **cellRendererParams** and **cellEditorParams** are flattened onto the 'params' object that is passed into the **init** method, while a custom filter has its **filterParams**

**Column Defintion**

``` javascript
columnDefinition = {
  headerName: "Foo"
  field: "foo"
  editable: true
  cellEditor: CustomEditor,
  cellEditorParams: { bar: "hello world"}
  cellRenderer: CustomRenderer,
  cellRendererParams: {bar: "hello world"},
  filter: CustomFilter,
  filterParams: {bar: "hello world"}
};
```

**Custom Editor**

``` javascript
let CustomEditor = function () {};
CustomEditor.prototype.init = function (params) {
  let bar;
  let colDef;
  bar = params.cellEditorParams.bar; // Cannot read property 'bar' of undefined
  bar = params.bar; // This works
  colDef = params.colDef; // undefined
  colDef = params.column.getColDef(); // This works
};
```

**Custom Renderer**

``` javascript
let CustomRenderer = function () {};
CustomRenderer.prototype.init = function (params) {
  let bar;
  let colDef;
  bar = params.cellRendererParams.bar; // Cannot read property 'bar' of undefined
  bar = params.bar; // This works
  colDef = params.colDef; // This works
  colDef = params.column.getColDef(); //This works
};
```

**Custom Filter**

``` javascript
let CustomFilter = function () {};
CustomFilter.prototype.init = function (params) {
  let bar;
  let colDef;
  bar = params.filterParams.bar; // This works
  bar = params.bar; // Cannot read property 'bar' of undefined
  colDef = params.colDef; // This works
  colDef = params.column.getColDef(); // This works
};
```

I'm still not sure why the colDef is redundantly exposed on the 'params' object. I feel like accessing it from params.column.colDef would be safer, and would allow the user to also access any params.

Below are some suggestions:

**_Example of Consistency**_

``` javascript
let Custom = function() {};
Custom.prototype = function (params) {
  let bar;
  bar = params.column.getColDef().filterParams.bar; // If 'Custom' is a filter
  bar = params.column.getColDef().cellRendererParams.bar; // If 'Custom' is a cellRenderer
  bar = params.column.getColDef().editorParams.bar; // If 'Custom' is an editor.
  /*
    This method reduces redundancy, but at the cost of having a deeper nested structure.
    That being said, this is far safer than flattening any of the filterParams, cellRendererParams, 
    and editorParams objects onto the 'params' object.
  */
}
```

**Comment by ceolter** [comment]
thanks for highlighting. i'll come back to this soon.

**Comment by ceolter** [comment]
thanks for raising, and i agree, it's wrong to have them different. the target state is the cell renderer and editor. however for now i'm going to leave the filter as i am not 100% sure of the final state and i plan to do a lot of reworking in this area so won't want to change things to many times.

basically under the hood i'm building out a UI framework. the approach in the cell renderer / editor are my newest ideas. in a few months (two or three?) I'll have all the ideas finished and then i'll refactor everything in a big release and also release the new framework for anyone to use, maybe call it ag-stack. but during this process, i don't want to be changing everything all the time as i go. when things are ready i'll revisit the filters and bring them up to date.

**Comment by DChau10** [comment]
Thanks. Yes, I really just wanted to highlight the inconsistencies that I noticed so that way you could improve on the framework. As I find things like this, I'll be sure to create issues for them. I definitely like the improvements you've made, so thank you!

Would definitely love to see Angular 2 component integration for these!

**Comment by ceolter** [comment]
this was fixed a few months back, filters are now consistent with cellEditors and cellRenderers
