### ISSUE TITLE
Navigating by tab breaks when on last/first cell

### ISSUE THREAD

**Issue by fabiogallo-blueprint** [ceolter/ag-grid#867]
When:
- focus is on last cell and user click the tab key
- focus is on first cell and user clicks shift + tab

Error in console: `Uncaught TypeError: Cannot read property 'floating' of undefined`
This can be reproduced on any example grid on ag-grid.com

**Comment by ceolter** [comment]
will be fixed in next relese

**Comment by fabiogallo-blueprint** [comment]
Thanks!
