### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by HowCome** [ceolter/ag-grid#868]
Each instance of ag-grid launches a timer and calls periodicallyDoLayout every half second. Leaving out the fact that practice of setting frequent timer for maintenance of the object just in case some condition change (which may never happen) should be frown upon, I suspect there is some leak in these calls. 
I have a rather simple web application with four  instances of the grid and if left overnight chrome browser  consumes all available resources from one CPU core. Checking in the debugger the only code that is being executed is in periodicallyDoLayout. 
Instead of calling doLayout periodically the call should be triggered by the events that could change the layout, for example size or data change.

**Comment by ceolter** [comment]
```
Instead of calling doLayout periodically the call should be triggered by the events that could change the layout, for example size or data change.
```
there is no event for 'dom object resized', only winder resized, and this is not the case.

with regards the high cpu, it's not dolayout, i tested this and it makes little difference when no resize is happening.

you can check this using chromes task manager, detailed here:
http://www.laptopmag.com/articles/how-to-use-chromes-built-in-task-manager
on my machine, the ag-grid website with the main example is taking 0% when open

**Comment by vlodko** [comment]
@HowCome , @ceolter having same issue. After analyzing a few dev tools profile, it seems that `periodicallyDoLayout` is the root of issue.

**Comment by harrychou** [comment]
In angular, this periodicallyDoLayout call causes change detection to happen frequently and can cause performance issue.

**Comment by monis001** [comment]
any update on this? I have faced similar issues when I am having 7 grids and in my case getting data from web-sockets.
more on this here : 
[browser-hang](https://stackoverflow.com/questions/62632840/multiple-ag-grid-tables-causing-browser-to-hang)

**Comment by chanakyachatterjee** [comment]
any update on this please? facing the same issue with ag-grid 22.1.1.

**Comment by junilo** [comment]
We are also encountering this high cpu usage specially after leaving the grid for more than an hour, we're using `ag-grid-vue`
