### ISSUE TITLE
How to customize the group header text

### ISSUE THREAD

**Issue by mikeerickson** [ceolter/ag-grid#871]
I have tried a myriad of callbacks (from documentation) but cant see to figure out which one to use to make it work.   In addition, how is it possible to change the group icon (as I have been able to do with header sort icons, etc)

We have an existing grid UI that I need to replicate to a T (or as close as possible)  

Can someone please give me a lead to an example of how I can customize the grouped item (already figured how how to style, now just need to customize the actual text

**Comment by ceolter** [comment]
not possible to customize the group header text - you need to set the group name accordingly.

it is the plan to provide templates for the group headers similar to that of the normal headers, it's in the pipeline tracked by another issue, so will close this issue.

**Comment by mikeerickson** [comment]
@ceolter My apologies, I phrased my questions all wrong (I was actually referring to the row grouping text).  But, I have figured it out so all is good :-)

**Comment by dereklin** [comment]
@mikeerickson How did you change the text?  I want to get just use the normal hearderName instead of sum(headerName)

**Comment by dereklin** [comment]
suppressAggFuncInHeader=true
