### ISSUE TITLE
Changing group row height

### ISSUE THREAD

**Issue by mikeerickson** [ceolter/ag-grid#872]
In addition to customizing the text of grouped row, I also need to adjust the group row height (just the part which has the group text).

I have tried to edit various CSS parameters, but nothing seems to work (it can be applied to the actual text, but not the actual grid row)

**Comment by ceolter** [comment]
use getRowHeight() callback
http://localhost/javascript-grid-callbacks/index.php

then something like:
```
if (params.node.group) {
 return 20;
} else {
 return 20;
}
```
(i didn't test the above, but you should know what i'm getting at)

**Comment by mikeerickson** [comment]
@ceolter Awesome, thank you very much.  Sorry for so many questions... There is so much to this awesome component, sometimes hard to find the answers.  The documentation is a good first step, but often dont find what I need ;-(

More examples would be awesome!

**Comment by mikeerickson** [comment]
@ceolter Do, threw me a look for a moment (reference to localhost above)

I found it at :-)

https://www.ag-grid.com/javascript-grid-callbacks/index.php
