### ISSUE TITLE
How to override header menu

### ISSUE THREAD

**Issue by mikeerickson** [ceolter/ag-grid#875]
When clicking the hamburger, where does one go about customizing this menu (I need to remove access to the Panel).   

I have been able to customize row contextual menu, but not finding anything for the header menu text.

**Comment by mikeerickson** [comment]
Found it in docs :-)

**Comment by mikeerickson** [comment]
@ceolter  Note:  On this page, the description for `getMainMenuItems` is incorrect (has same description from above)

https://www.ag-grid.com/javascript-grid-callbacks/index.php

**Comment by mikeerickson** [comment]
@ceolter One thing I cant find in documentation is how to remove the last button (info from ToolPanel)

![columns](https://cloud.githubusercontent.com/assets/183153/14999439/2c7afe50-113e-11e6-8cda-3dac0df3eba7.png)

**Comment by ceolter** [comment]
@mikeerickson 
re docs inconsistency, i've changed, will be in next release.
re hiding last tab, see https://www.ag-grid.com/javascript-grid-column-menu/index.php
suppressMenuFilterPanel: Set to true to not show filter panel.
suppressMenuMainPanel: Set to true to not show main panel.
suppressMenuColumnPanel: Set to true to not show column selection panel.

**Comment by mikeerickson** [comment]
@ceolter Yet again, much appreciated for your quick response.  I am on a tight deadline (as usual) and your promptness is greatly greatly appreciated.

**Comment by mrinalsing** [comment]
@ceolter, sorry to comment on this closed thread, but I found this question apt and linked to my question.

How can we customize "columnsMenuTab" in the header context menu? Actually I am trying to provide a search box in the "columnsMenuTab" to search from the list of columns (as the list of columns is large) to select or deselect individual columns to be displayed in the grid.

Thanks.

**Comment by dalevfenton** [comment]
Is there any way to customize the list of columns shown in the columnsMenuTab, we have a checkbox column that it should not be possible to turn off, so I need to be able to filter it out of the columns that get shown in the columnsMenuTab

**Comment by sairam96766** [comment]
Is there any way to customize columnsMenyTab, so that I need to remove columns from columnsMenuTab for hiding:true. Currently, I can able to see the column names in columnMenuTab for columns as hide: true

**Comment by JosKariuki** [comment]
You can add:
`menuTabs: []` to your column as a property to hide the tabs
So you'll add it this way
`{ headerName: 'Test', field: 'Test', menuTabs: []}`

**Comment by GingertronMk1** [comment]
Is there any way to adjust the order that the columns appear in the `columnsMenuTab`? I have an instance where I would like them to appear in alphabetical order within the menu but not in the table itself
