### ISSUE TITLE
Demo Source Available?

### ISSUE THREAD

**Issue by mikeerickson** [ceolter/ag-grid#876]
I am having a tough time getting my grouping to work (and maintain sort order).   When reviewing the demo, all works as I would expect.   Is the source code for the demo available for review?  It would surely go a long way to helping me get some of my issues figured out.

**Comment by ceolter** [comment]
view the source from your browser.

or alternatively, the entire website is here:
https://github.com/ceolter/ag-grid-docs

**Comment by genyded** [comment]
For anyone else that may be looking, found it at https://github.com/ag-grid/ag-grid-docs/blob/master/src/example.js (and example.php in the same location loads it)

**Comment by h1v3m1nd** [comment]
im quite new so sorry for asking but how do you bind this in? (i have to show some different demos of different frameworks so im not much into angular right now) I created example.php and example.js within the basic demo file.  Put it into index.html? appreciate an answer a lot!

**Comment by spencermefford** [comment]
If you're looking for this in 2023, you'll now find it here: https://github.com/ag-grid/ag-grid/blob/latest/grid-packages/ag-grid-docs/src/example-rich-grid/example.js.

**Comment by ginny100** [comment]
> If you're looking for this in 2023, you'll now find it here:
> 
> * https://github.com/ag-grid/ag-grid/blob/latest/grid-packages/ag-grid-docs/src/example-rich-grid/example.js
> * https://github.com/ag-grid/ag-grid/blob/c33462cb586fcc86a59c6a982c997b212efe872c/grid-packages/ag-grid-docs/documentation/src/mainPageDemo/Example.jsx.

Super helpful! Thank you so much for sharing these! 💯
