### ISSUE TITLE
Procedurally move column into view

### ISSUE THREAD

**Issue by mikeerickson** [ceolter/ag-grid#877]
I have a table with some 25 columns and I need to figure out a method to procedurally move the grid into view based on user entry (custom find).  If user is looking for a column which is not in view, how can I "scroll" the entered column into view?

See the attached screenshots

Screen 1 - Default display
Screen 2 - Where I need to scroll to (based on user input)

![screen1](https://cloud.githubusercontent.com/assets/183153/14996811/b39c6bd4-1130-11e6-9d5f-465c5618a1ed.png)
![screen2](https://cloud.githubusercontent.com/assets/183153/14996816/b85a13ec-1130-11e6-80c6-657365b02f33.png)

**Comment by ceolter** [comment]
see the grid api, there are methods to scroll row into view and col into view

**Comment by mikeerickson** [comment]
@ceolter Awesome, thx!
