### ISSUE TITLE
[Angular] [Selection] [RefreshCells] Refreshing Cells does not call isRowSelectable

### ISSUE THREAD

**Issue by christiantweed-oc** [ceolter/ag-grid#8771]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Providing a Reproducible Scenario**
Plunkr does not provide a modern Angular version, so here is a stackblitz.
https://stackblitz.com/edit/stackblitz-starters-kugent?file=src%2Fapp%2Fdemo%2Fdemo.component.ts

**Current behavior**
When I call `event.api.refreshCells({force: true})` it does not actually call `selection.isRowSelectable()` again to check if the row is selectable. It does work with `event.api.redrawRows()`, but this is expensive and in a table with a few hundred records there is noticeable lag on the checkboxes popping in and out.

**Expected behavior**
I expect that when I call `event.api.refreshCells({force: true})` it would call the `selection.isRowSelectable()` for the rows again 

**Please tell us about your environment:**
MacOS, VSCode, NPM

* **AG Grid version:** 32.2.0

* **Browser:**
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36'

* **Language:**  TypeScript ~5.3.3

**Comment by AG-Zoheil** [comment]
Hi @christiantweed-oc,

Please note we do not provide support on GitHub, however to demonstrate that this is not a bug with the grid we can provide a simple scenario showing the desired behaviour here: https://plnkr.co/edit/STsZaDMfrQPIvhSx?open=main.js.

Kind regards,
Zoheil
