### ISSUE TITLE
[React] [onColumnHeaderClicked] onColumnHeaderClicked Triggered when filter icon pressed, Filter Icon should have stop propagation.  

### ISSUE THREAD

**Issue by Idan-D-Placer** [ceolter/ag-grid#8772]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Couldn't reproduce in docs 

**Current behavior**
When adding a listener to onColumnHeaderClicked upon clicking the filter icon, onColumnHeaderClicked is called. 

**Expected behavior**
filter icon should stopPropagation 

**Please tell us about your environment:**

Operating System: Windows 10
IDE: VS Code
Package Manager: npm
HTTP Server: Localhost (Node.js)

* **AG Grid version:** X.X.X
AG Grid version: 31.1.0

* **Browser:**
Browser: Chrome 116.0.5845.96 (Official Build) (64-bit)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Language: TypeScript 4.8
React

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this. If you are unable to reproduce this issue (as your comment "Couldn't reproduce in docs" seems to indicate) it would be very difficult for us to investigate if a bug is existent here.
We're looking forward to your response.

Kind regards,
Zoheil

**Comment by Idan-D-Placer** [comment]
@AG-Zoheil Thank you for the fast response 
Here is a [plunker](https://plnkr.co/edit/XSlKN7qxcSlnsbLy), I've forked someones already working pluker so the title is wrong.

thanks

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-11724**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
