### ISSUE TITLE
Filtering date with time with equals

### ISSUE THREAD

**Issue by yehudahkay** [ceolter/ag-grid#8773]
Hi by default the grid doesn't properly compare dates with times if you use the equals filter. This seems like a bug but in any case also the code on https://www.ag-grid.com/javascript-data-grid/filter-date/ doesn't fix this either. Thanks to Ofer Gal for the following code which helps:

```
 comparator: (filterLocalDateAtMidnight, cellValue) => {
      const dateAsString = cellValue.toLocaleDateString();
        if (dateAsString === null) return -1;
        const cellDate = new Date(dateAsString);
        if (filterLocalDateAtMidnight.getTime() === cellDate.getTime()) {
            return 0;
        }
        if (cellDate < filterLocalDateAtMidnight) {
            return -1;
        }
        if (cellDate > filterLocalDateAtMidnight) {
            return 1;
        }
        return 0;
    },
```

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-304**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
