### ISSUE TITLE
ag-arid how replace default scrollbar

### ISSUE THREAD

**Issue by dearyangyu** [ceolter/ag-grid#8777]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[√] support request => see 'Requesting Community Support'
```
**Expected behavior**

I would like to know how to replace the default scroll bar in vue3. What scroll bar am I using now perfect-scrollbar.

**Please tell us about your environment:**

* **AG Grid version:** 32.1.0

* **Browser:**

* **Language:** [all | TypeScript Vue

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
