### ISSUE TITLE
agRichSelectCellEditor value list sometimes covers value depending on browser size

### ISSUE THREAD

**Issue by dwilt** [ceolter/ag-grid#8781]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

We do have an enterprise license but I'm unable to find where on your [Enterprise Support page](https://ag-grid.zendesk.com/hc/en-us) I can sign up so I'm going to file the bug here.

**Providing a Reproducible Scenario**

I'm using one of the preview links from your `Rich Select Editor` Codesandbox demo: https://mjvr7x.csb.app/

1. Go to your demo link above
2. Resize the browser vertically so it's very short
3. Click into one of the fields to start editing and you'll notice how the dropdown covers the value

![image](https://github.com/user-attachments/assets/fa94e85b-43c0-4c1e-9634-473483fcd6bd)

I'm sure you're doing this intentionally to make more room for the dropdown but if the page isn't that small but there are a lot of options in the dropdown, this can happen in a lot of scenarios - especially if the editor is in the middle or towards the bottom of the page. See below how it's happening in our application:

![image](https://github.com/user-attachments/assets/79e09821-83b0-4b93-9c7f-4d9a348fe05a)

I think there should be an option to have it go to max-height or have an internal scrollbar instead. Our clients are complaining that the value is being blocked.

Watch this gif below as I slowly resize the browser vertically (this is also happening when applying a `valueListMaxHeight`). As it gets close to the max height size, once it reaches it, it starts moving the value list up instead of just allowing it to scroll more:

![2024-09-20 12 04 18](https://github.com/user-attachments/assets/6ef40afa-a581-47b5-8458-1c76ab7c3f76)

**Current behavior**
Open up any `agRichSelectCellEditor` editor that is close to the bottom of the page and notice how the dropdown covers the value

**Expected behavior**
I think I would expect it to scroll internally at certain points instead of covering the value - or even force the page to scroll.

**Please tell us about your environment:**
Chrome, VSCode, Mac OSX

* **AG Grid version:** X.X.X
```
    "ag-grid-community": "^32.1.0",
    "ag-grid-enterprise": "^32.1.0",
    "ag-grid-react": "^32.1.0",
    ```

* **Browser:**
```
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36'
```

* **Language:**
All

**Comment by dwilt** [comment]
Was thinking more on this, maybe a `valueListMinHeight` could be applied by the dev and it would always scroll if this height wasn't hit yet. If it was, then you could move it up vertically like you have now.

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-9166**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
