### ISSUE TITLE
agRichSelectCellEditor with multiSelect: true should allow option to trigger change event on every selection

### ISSUE THREAD

**Issue by dwilt** [ceolter/ag-grid#8782]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

We do have an enterprise license but I'm unable to find where on your [Enterprise Support page](https://ag-grid.zendesk.com/hc/en-us) I can sign up so I'm going to file my request here.

**Providing a Reproducible Scenario**
I forked your [Multi Selection](https://www.ag-grid.com/javascript-data-grid/provided-cell-editors-rich-select/#multi-selection) CodeSandbox and just added a console log to `onCellValueChanged` that logs out that value:

https://codesandbox.io/p/sandbox/rich-select-editor-forked-jwlzzz?workspaceId=4ac65209-8ebd-4fd3-b4dd-fe689f506d09

**Current behavior**
1. Go to the preview link: https://jwlzzz.csb.app/
2. Start editing one of the cells in the "Multi Select" column:
3. Notice that the console.log (the `onCellValueChanged` event) only fires onces the user stops editing. The average user does not understand this editing/not editing state change intuitively. If you change a value on a `agRichSelectCellEditor` where `multiSelect: false`, the `onCellValueChanged` fires immediately but not when `multiSelect: true`. You have to hit enter, or click another cell to fire the change event. Even if I click outside of the editor, just some where else on the page, it doesn't fire the `onCellValueChanged` event.

![2024-09-20 12 32 15](https://github.com/user-attachments/assets/a1843cd4-5c1f-4e65-94c7-0e05d3ff8337)

**Expected behavior**
If you think this is the behavior you want by default, I'm proposing adding another property to `cellEditorParams` that would allow the `onCellValueChanged` be able to fire whenever a value is edited while `multiSelect: true`. I think the user can continue editing but the value would just change on every selection/deselection. Maybe call it `fireChangeOnEdit: boolean`?

**Please tell us about your environment:**
Mac OSX, VSCode, Chrome

* **AG Grid version:** X.X.X
    "ag-grid-community": "^32.1.0",
    "ag-grid-enterprise": "^32.1.0",
    "ag-grid-react": "^32.1.0",
```

* **Browser:**
```
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36'
```

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
```
alll
```

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-12945**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
