### ISSUE TITLE
Server side pagination with React: grid is re-rendered when an item is selected

### ISSUE THREAD

**Issue by smaestri** [ceolter/ag-grid#8783]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Please go to [this codesandbox example](https://codesandbox.io/p/sandbox/server-side-pagination-forked-zx6cpk) to reproduce the issue below.

**Context**
I am using Ag Grid to do server side pagination on a public paginated API (Pokemon one) as explained [here](https://www.ag-grid.com/react-data-grid/server-side-model-pagination/), and display results in the ag-grid table. Moreover, I want to be able to select an item in the table, and display all selected items at the top (stored in React state).

**Issue**
My issue is : if you change the page (for example 2nd one), and THEN select an item in the table by clicking on it, the Grid component is re-rendered, and you are redirected to the first page! We should stay on the second page, no reason to re-render whan selecting an item in the table.

**Attemp to fix**
I have managed to prevent re-rendering by using `useCallback()` on `addItem()` function, with an empty dependency array, and using `memo()` on `Grid` component. 
But 2 new issue arises : 
- we can have duplicated in the selected items list if you select an item twice (becasue of the empty array of `useCallback`);
- eslint rule "exhaustive deps" is broken (eslint complaining we must add `selectedItems` in the dependency array)
![image](https://github.com/user-attachments/assets/f0512300-d469-4fb4-a79f-a5859ddf4ef8)

Any ideas how to handle that issue properly in React? Thank you!

* **AG Grid version:** 32.2.0

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by AG-Zoheil** [comment]
Hi @smaestri,

Thank you for submitting this on Github.

SSRM is an enterprise feature. As we do not provide support on Github, I would encourage you to raise this via our [support portal](https://ag-grid.zendesk.com/hc/en-us) if you do have an active AG Grid Enterprise licence.

That would be the most efficient way for you to get assistance with this.

In light of the above, I will be closing this issue here.

Kind regards,
Zoheil
