### ISSUE TITLE
[React] Tests broken since upgrading from 32.1.0 to 32.2.0

### ISSUE THREAD

**Issue by eero-dev** [ceolter/ag-grid#8791]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

This affects our tests as they have started failing since upgrading from ag-grid 32.1.0 to 32.2.0

**Customers of AG Grid**

We have purchased enterprise licenses, however not sure if they are still active. (https://pinja.com/ organisation)

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**

Run the following react+vite project following the steps

[ag-grid-bug.zip](https://github.com/user-attachments/files/17096768/ag-grid-bug.zip)

1. unzip
2. npm install
3. npm run test
4. test fails

Change ag-grid version to 32.1.0 and repeat steps, test will pass

**Current behavior**
Test fails with the following error

```
 FAIL  src/status-history/Machine.statusHistory.unit.test.tsx > Render ag-grid and pass > Renders ag-grid and passes
TypeError: Cannot read properties of undefined (reading 'getGridId')
 ❯ node_modules/@ag-grid-community/react/dist/package/index.esm.mjs:2640:40
    2638|       apiRef.current = void 0;
    2639|     });
    2640|     gridIdRef.current = apiRef.current.getGridId();
       |                                        ^
    2641|   }, []);
    2642|   const style = useMemo12(() => {
 ❯ commitAttachRef node_modules/react-dom/cjs/react-dom.development.js:23689:18
 ❯ commitLayoutEffectOnFiber node_modules/react-dom/cjs/react-dom.development.js:23542:9
 ❯ commitLayoutMountEffects_complete node_modules/react-dom/cjs/react-dom.development.js:24727:9
 ❯ commitLayoutEffects_begin node_modules/react-dom/cjs/react-dom.development.js:24713:7
 ❯ commitLayoutEffects node_modules/react-dom/cjs/react-dom.development.js:24651:3
 ❯ commitRootImpl node_modules/react-dom/cjs/react-dom.development.js:26862:5
 ❯ commitRoot node_modules/react-dom/cjs/react-dom.development.js:26721:5
 ❯ finishConcurrentRender node_modules/react-dom/cjs/react-dom.development.js:26020:9
 ❯ performConcurrentWorkOnRoot node_modules/react-dom/cjs/react-dom.development.js:25848:7
```

**Expected behavior**
Test passes without error

**Please tell us about your environment:**
VSCode, Node 20 LTS

* **AG Grid version:** X.X.X
Broken in 32.2.0, suspecting https://github.com/ag-grid/ag-grid/pull/8655
Works in 32.1.0

* **Browser:**
Havent observed it in the browser yet, not sure what other effects this has beside the failing test.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
React 18, Typescript 5.6.2

**Comment by StephenCooper** [comment]
I see in your repo that with v32.1 you get the following error in the console despite the passing status. 

```
stderr | src/status-history/Machine.statusHistory.unit.test.tsx > Render ag-grid and pass > Renders ag-grid and passes
Store does not have a valid reducer. Make sure the argument passed to combineReducers is an object whose values are reducers.
AG Grid: AG Grid: unable to use rowModelType = 'clientSide' as package 'ag-grid-enterprise' has not been imported. Check that you have imported the package:
            
    import 'ag-grid-enterprise';
AG Grid: Failed to create grid.
```

If you fix this by providing a row model such as ClientSideRowModel then the test passes in both 32.1 and 32.2.

```
import { ClientSideRowModelModule } from '@ag-grid-community/client-side-row-model'

const renderStatus = () => {
  const data = renderWithRedux(
    <MemoryRouter initialEntries={[`/machine/1/statushistory`]}>
      <Routes>
        <Route path="/machine/:machineId/statushistory" element={<AgGridReact modules={[ClientSideRowModelModule]} />} />
      </Routes>
    </MemoryRouter>,
```

Are you able to replicate this fix?

**Comment by eero-dev** [comment]
> I see in your repo that with v32.1 you get the following error in the console despite the passing status.
> 
> ```
> stderr | src/status-history/Machine.statusHistory.unit.test.tsx > Render ag-grid and pass > Renders ag-grid and passes
> Store does not have a valid reducer. Make sure the argument passed to combineReducers is an object whose values are reducers.
> AG Grid: AG Grid: unable to use rowModelType = 'clientSide' as package 'ag-grid-enterprise' has not been imported. Check that you have imported the package:
>             
>     import 'ag-grid-enterprise';
> AG Grid: Failed to create grid.
> ```
> 
> If you fix this by providing a row model such as ClientSideRowModel then the test passes in both 32.1 and 32.2.
> 
> ```
> import { ClientSideRowModelModule } from '@ag-grid-community/client-side-row-model'
> 
> const renderStatus = () => {
>   const data = renderWithRedux(
>     <MemoryRouter initialEntries={[`/machine/1/statushistory`]}>
>       <Routes>
>         <Route path="/machine/:machineId/statushistory" element={<AgGridReact modules={[ClientSideRowModelModule]} />} />
>       </Routes>
>     </MemoryRouter>,
> ```
> 
> Are you able to replicate this fix?

Thanks it works, is there a reason it seemed to work without it before?

**Comment by StephenCooper** [comment]
Yes, the change you linked to did introduce a new expectation that the grid was correctly setup. 

We may be able to soften this expectation to avoid this issue happening.
