### ISSUE TITLE
Custom message for zero rows in the grid.

### ISSUE THREAD

**Issue by vivektodi** [ceolter/ag-grid#88]
It would be great if we can give a custom message like _"No records found"_ or maybe even show an image to user if the grid has zero rows because there is no underlying data.

**Comment by JimmyBoh** [comment]
Anybody find an implementation or workaround for this?

**Comment by amcdnl** [comment]
Ideally you would be able to include a template for no results. thoughts @ceolter ?

**Comment by ceolter** [comment]
Yup I agree, I will get this in soon. Something easy to unblock this. Then in the future, a template.

**Comment by jovana** [comment]
+1

**Comment by jaggernoth** [comment]
+1

**Comment by scotthovestadt** [comment]
+1

**Comment by ceolter** [comment]
today's release has this. there is an overlay that can be overridden with your own template for 'no rows'. works in same way as template for 'loading'. explained in the docs.

**Comment by carloshpds** [comment]
You can use `overlayNoRowsTemplate`  ;)

**Comment by VINNI-999** [comment]
is there any option to display no data found when you not found anything in filter...?

**Comment by bowlereggs-edi** [comment]
this.gridOptions = <GridOptions>{
      localeText: { noRowsToShow: 'Put your message here ' },
}

**Comment by avinash84** [comment]
const overlayNoRowsTemplate= "<span>No record found</span>";

**Comment by bmarvinb** [comment]
> is there any option to display no data found when you not found anything in filter...?

Do we have any solution to this?

**Comment by MoritzMeinhardt** [comment]
Our use case it that we use the externalFilter api of ag grid. And we would like to display some text 'All rows filtered' in case that all rows are filtered.
