### ISSUE TITLE
Great Project ! ! !

### ISSUE THREAD

**Issue by mikeerickson** [ceolter/ag-grid#880]
For those who are just checking into this project, stop looking at others and start using agGrid.

This is an amazing piece of work and the api is so deep, you will be thrilled to find out all it is capable of doing. 

Thanks to @ceolter for his efforts, you have helped improve our application with agGrid

T H A N K   Y O U ! ! !

**Comment by supersabillon** [comment]
+1

**Comment by ceolter** [comment]
+1
do you want to give me a testimonial for the website?

**Comment by mikeerickson** [comment]
@ceolter Sure!  I will send it over this evening when I get home
