### ISSUE TITLE
how can i disable the copy feature in enterprise 

### ISSUE THREAD

**Issue by wjljan** [ceolter/ag-grid#8803]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

In the clipboard documention it says "Copying from the grid is enabled by default for enterprise users.", so how can i disable it.
Can not find grid option to disable copying from the grid when import enterprise.

**Expected behavior**

There is a grid option or column conf can allow me to disable/suppress the copying from cell for row.

**Please tell us about your environment:**

win11

* **AG Grid version:** X.X.X

v30.2.0

* **Browser:**

chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As you've mentioned you are an enterprise client I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/hc/en-us) for issues or suggestions. That would be the quickest and most efficient route for you to get your question answered.

Regarding the issue/question above, we have a feature request to implement a suppress property for the copy function under AG-12954.

In the meantime, you could use the following workaround: https://plnkr.co/edit/AObRAuFuI11o5Fqz?open=main.js.

Or alternatively suppress keyboard navigation via https://www.ag-grid.com/javascript-data-grid/keyboard-navigation/#example-suppress-keyboard-navigation if your requirement is predominantly about the `CTRL + C` key combination.

Kind regards,
Zoheil
