### ISSUE TITLE
Regression with new selection API: deselection not possible with click

### ISSUE THREAD

**Issue by uncaught** [ceolter/ag-grid#8804]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[ ] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[ ] support request => see 'Requesting Community Support'
```

**API change**

With the previous selection API, which was deprecated with 32.2, the following configuration allowed for selecting **and deselecting** rows with a single click:

```js
{
    rowMultiSelectWithClick: true,
    rowSelection: 'single',
}
```

Switching to the new API, it is no longer possible to deselect with a click:

```js
{
    selection: {
        checkboxes: false,
        enableClickSelection: true,
        mode: 'singleRow',
    },
}
```

In fact it seems the `enableDeselection` option for `enableClickSelection` doesn't work at all. I've tried all combinations with `singleRow` and `multiRow`, but neither `onRowSelected` nor `onSelectionChanged` is called when clicking a 2nd time to deselect.

**Current behavior**

Deselection is not possible with a click.

**Expected behavior**

Deselecting should be possible with a click.

**Please tell us about your environment:** irrelevant

* **AG Grid version:** 32.2.0

* **Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36

* **Language:** [TS 5.6.2]

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-12902**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
