### ISSUE TITLE
Access to RowRenderer instance

### ISSUE THREAD

**Issue by lzl19971215** [ceolter/ag-grid#8809]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

* **AG Grid version:** 32.2.0

Hi, how can I get access to RowRenderer instance of each row? I need to get cell control directly, is there an elegant way to do this?

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
