### ISSUE TITLE
fps drops when enabled columndef.checkboxselection & custom floating filter using ag-grid@30.2

### ISSUE THREAD

**Issue by Turtletles** [ceolter/ag-grid#8811]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**
Yes, employee of ssnc. currently we are not able to get in ZenDesk.

**What**
we are using ag-grid to display portfolio and securities and data amount could be as much as 10K or more. Currently, we are using ssrm to display those data. But we found when we rapidly scroll down and up(grid initialized and data loaded), the scrolling becomes kinda  choppy. we are using requestAnimationFrame() to calculate the fps. And we have already done a certain improvements regarding to scrolling perfoemance, such as disable animiation, replace custom cellrenderers with valueGetters, enable valueCache etc.
The grid features we are using:
* checkbox selection
* filter & floating filter (custom logic)
* range selection
* **SSRM**
* value getter(for most columns) & js cell render function(no custom cell render component, normally less than 2 cols), value cache
* custom header component
* row hover highlight, sorting, pin, other....

we have done lots of test.
1.  the fps recorded when enable checkboxSelection decreased by 5 comparing to disabling checkboxSelection(see the grid bellow, this is too much for a single feature). 
2. And this also happens in custom floating filter(we don't see how this is related to grid scrolling, there's not filtering field by default).  

Me and my team are shocked by the test results. **So we need your help. We want to know if there are ohter ways to improve the scrolling smoothing relates to checkboxSelection and floating filter or can we have a investigation on it?** 

RapidMouseWheelDown - normally this behaviour lasts for 10s or more for each case. Each case we could get hundreds or 1k+ fps and then calculates the avg number and repeats for 5 times. Here's one of our recent results.

Features  | Case | RapidMouseWheelDown AVG(5 times) | AVG(of 5 times)
-- | -- | -- | --
All features(features that we are using) | Security grid | 15.77, 15.47, 15.27, 15.35, 15.21 | 15.41
features without custom header | Security grid | 24.14, 25.44, 25.11, 24.62, 23.85 | 24.63
All features + header + disableHeaderText | Security grid | 14.6, 16.87, 16.06 13.26, 13.45 | 14.85
All features + header + disableHeaderFilter | Security grid | 22.57, 21.29, 23.82, 26.14, 25.4 | 23.84
All features + header + disableHeaderText + disableHeaderFilter | Security grid | 24.80, 23.5, 26.42, 23.44, 27.3 | 25.1
features without checkbox | Security grid | 20.85, 18.36, 18.75, 19.31, 21.87 | 19.83
All features + checkbox + disableCheckboxOtherStuff | Security grid | 13.41, 14.44, 14.73, 16.25, 15.59 | 14.88
Benchmark(only for displaying, not checkboxselection and other features) | Security grid | 43.58, 38.73, 42.20, 38.69, 39.55 | 40.55

One grid in our app that using floating filter:
![image](https://github.com/user-attachments/assets/bc0fffbd-12e6-448a-bee1-80e2446fd34f)

Env:
angular: 15.2
ag-grid: 30.2

Thanks.

**Comment by AG-Zoheil** [comment]
Hi @Turtletles,

Thank you for submitting this on Github.

As you are using enterprise features and we do not provide support on Github, I would encourage you to raise this via our [support portal](https://ag-grid.zendesk.com/hc/en-us) if you do have an active AG Grid Enterprise licence.

That would be the most efficient way for you to get assistance with this.

Especially as this seems like a very specific use case to your code and discussing this on private channels would be better. Please ask your account manager to get in touch with us if you are still unable to access ZenDesk.

In light of the above, I will be closing this issue here.

Kind regards,
Zoheil
