### ISSUE TITLE
data:font/woff2;char... file is showing stalled in network tab

### ISSUE THREAD

**Issue by vidhyatr** [ceolter/ag-grid#8812]
Hi,

This data file is  went to stalling , some times ,it stalling state went to long time even though the  priority is high.
![image](https://github.com/user-attachments/assets/ccff9422-30db-4191-9591-a3bc33b29ac5)

![image](https://github.com/user-attachments/assets/9c76e04c-ec79-47af-95d8-178252983a95)
Why the data file is stalled ?
Did this stalled state will cause any performance issue. ?

**Comment by vidhyatr** [comment]
any update on this issue ?

**Comment by AG-Zoheil** [comment]
Hi,

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
