### ISSUE TITLE
autosizecolumns ag grid working when one row data is present,  for more than one rows column content width is getting multiplied with row data length

### ISSUE THREAD

**Issue by nageswariajitha** [ceolter/ag-grid#8817]
Before resize button click
![image](https://github.com/user-attachments/assets/09a96116-6c4c-40ec-9435-85d941ab4cfe)
After resize button click
![image](https://github.com/user-attachments/assets/f37b299e-839b-4fc5-8917-2b37153bbe79)

AG Grid Community Version: 32.2.0
Angular Version: 18

Below code is triggered on button click and i have not mentioned autoSizeStrategy for grid
 const rendererNames = ['iconRenderer', 'actionRenderer'];
      const allColumnIds: string[] = [];
      this.gridApi.getColumns()!.forEach((column) => {
        if (columnResizeApplied && this.columnData.find(x => x.field === column.getColId())) {
          this.columnData.find(x => x.field === column.getColId()).actualWidth = column.getActualWidth();
        }
        if (!rendererNames.includes(column.getColDef().cellRenderer)) {
          allColumnIds.push(column.getId());
        }
      });
      this.gridApi.autoSizeColumns(allColumnIds);

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
