### ISSUE TITLE
Reset or Update GridOptions

### ISSUE THREAD

**Issue by mikeerickson** [ceolter/ag-grid#882]
Does a method exists which allows me to update gridOptions en mas?

Due to the issue I am having with React and Maximum Call Stack 

```
gridOptions={this.gridOptions}
```

I am trying to figure out a different way to either initialize the react grid, or somehow update after it has been initially created.   I have  my gridOptions object to contain all the information I need, however, the above assignment doesn't work correctly 

If anybody has a sample using React version of agGrid, I would greatly appreciate having a look at what you have done.  I am 90% there with what I need, but some features can't be implemented without using gridOptions

Thanks in advance!

**Comment by ceolter** [comment]
https://github.com/ceolter/ag-grid-react-example

**Comment by mikeerickson** [comment]
@ceolter Awesome sauce, thx
