### ISSUE TITLE
Incorrect Checkbox Icon Rendering for Boolean Values in Grouped Columns

### ISSUE THREAD

**Issue by christophkiser** [ceolter/ag-grid#8821]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

YES

**Providing a Reproducible Scenario**
I'm referencing a previous issue reported as [#7972](https://github.com/ag-grid/ag-grid/issues/7972), which was assigned ID AG-11649[Row Grouping]. According to the user [sabahang](https://github.com/sabahang), it was added to the backlog. However, I have noticed that this issue has not been addressed in subsequent updates and is no longer visible in the backlog or the release notes.

Could you please confirm its status and consider re-adding it to the backlog if it was inadvertently removed or overlooked? This feature is critical for our implementation, and we would appreciate any updates or timelines you could share regarding its resolution.

Thank you for your attention to this matter.

When grouping a column that contains boolean values, the icons in the group node are not rendered correctly. Specifically, instead of displaying a checkbox with a check mark for TRUE values and an empty checkbox for FALSE values, the grid renders an empty checkbox for both TRUE and FALSE values.

[Plunker-Link](https://plnkr.co/edit/ZjzcvcNWJnFuevFB?open=app.component.ts&preview)

**Current behavior**
If I group a column that contains boolean values, the checkbox icon for 'TRUE' and 'FALSE' are both rendered as empty checkboxes (FALSE) in the grouping node.

<img width="379" alt="Screenshot 2024-09-26 at 07 57 47" src="https://github.com/user-attachments/assets/6124c05e-dbea-4ac7-97db-6df17b40c482">

**Expected behavior**
The grouping node for the booleans of 'TRUE' should show an checkbox with an check mark in it. The same way as it is shown if the column is not grouped.

<img width="543" alt="Screenshot 2024-09-26 at 07 57 55" src="https://github.com/user-attachments/assets/28b1549f-6de5-4040-bd51-b94ddd89cceb">

**Please tell us about your environment:**

AG Grid version: 32.0.2

Browser:
Chrome, Safari, Firefox

Language:
TypeScript (Angular)

**Comment by AG-Zoheil** [comment]
Hello 

Looks like it was tagged with an incorrect reference. The correct reference is **AG-12238** and this was rectified in version `32.1.0`.

Please upgrade to benefit from the fix.

Thank you for following up on this.

Kind regards,
Zoheil
