### ISSUE TITLE
Column comparator crashes when using filter set model

### ISSUE THREAD

**Issue by magnusjtvisma** [ceolter/ag-grid#8835]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

- Add a column with a Set Filter
- Add a custom comparator, using nodeA and nodeB
- Open the filter. Now comparator crashes because nodeA and nodeB are undefined

I believe the problem is in this line:

https://github.com/ag-grid/ag-grid/blob/82bf0884f29b5c44f7b469daa8daced150587b32/packages/ag-grid-enterprise/src/setFilter/setValueModel.ts#L149

The column def comparator does not only take valueA and valueB. It also takes nodeA and nodeB.

**Expected behavior**

It should be possible to use nodeA and nodeB in comparator and still use setFilter

* **AG Grid version:** 32.1

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36

* **Language:** TypeScript 5.6

**Comment by AG-Zoheil** [comment]
Hi @magnusjtvisma,

Thanks for getting in touch.

I understand you are describing what seems to be a straightforward issue, however from experience and as the grid can be configured in so many different ways the most efficient way for us to look into this would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. We'd happy to look into this thereafter. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by magnusjtvisma** [comment]
Example here:

https://plnkr.co/edit/futGqKQcl8HcxfZX?open=main.ts

See line 34. Sorting works fine, but opening the set filter crashes because nodeA and nodeB are undefined

**Comment by AG-Zoheil** [comment]
Hi @magnusjtvisma,

Thank you for providing the example.

Your colDef comparator relies on rowData - in this case you need to supply a comparator for the setFilter.

You can read more about this in this section of our documentation:
https://www.ag-grid.com/javascript-data-grid/filter-set-filter-list/#sorting-filter-lists

Kind regards,
Zoheil

**Comment by magnusjtvisma** [comment]
@AG-Zoheil Thanks for pointing me to a fix. But you should fix the typescript types as well. I clearly showed you code that does dirty casting, and the result is that users of this library is tricked into thinking this is supported, and the only solution is to find some obscure note in the documentation.
