### ISSUE TITLE
Row selection still triggered by Space key when enableClickSelection=false

### ISSUE THREAD

**Issue by leey0818** [ceolter/ag-grid#8845]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**
https://plnkr.co/edit/y2iQwazwqCTcpMNv?open=main.ts&preview

**Current behavior**
When enableClickSelection=false, pressing the "Space" key still selects the row.
Additionally, checkboxes in disabled rows are also being selected.

**Expected behavior**
https://www.ag-grid.com/javascript-data-grid/row-selection-multi-row/#enable-click-selection--deselection

- The space key should not select rows when enableClickSelection=false.
- Disabled rows' checkboxes should not be selectable.

**Please tell us about your environment:**

* **AG Grid version:** 32.2.1

* **Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36

* **Language:** ES6

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

Regarding the disabled checkboxes being selected:
Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-9871**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Regarding the `enableClickSelection={false}`, this is an accessibility requirement that we cannot remove. Setting this to false is to suppress the mouse click, not the space bar.

Thanks again for bringing this up with us.

Kind regards,
Zoheil
