### ISSUE TITLE
Documentation for ag-grid versions below v23 have been removed

### ISSUE THREAD

**Issue by itskishankumar** [ceolter/ag-grid#8856]
https://www.ag-grid.com/archive/
https://www.ag-grid.com/documentation-archive/

Documentation for ag-grid versions below v23 have been removed.
They used to available previously.

Also checked https://web.archive.org/ and https://cachedview.com/, couldn't find it.

We are still using ag-grid v19 and this has halted development for some, including me.

Please help me out here.

**Comment by AG-Zoheil** [comment]
Hi @itskishankumar,

Thanks for your comment.

We will be dropping some of our documentation but this will be for anything below v18. We will add the remainder back (v18-23).

Apologies for the inconvenience.

Kind regards,
Zoheil

**Comment by itskishankumar** [comment]
Sure @AG-Zoheil . 

Can I know why you're dropping any documentation at all?

Thanks.
