### ISSUE TITLE
Unable to track AG-8276

### ISSUE THREAD

**Issue by melon2504** [ceolter/ag-grid#8859]
With respect to  #6365 , unable to find request  **AG-8276**  neither in Pipeline nor in Changelog:

![image](https://github.com/user-attachments/assets/711126f4-34f7-4f7e-9413-02fae7e270d4)

![image](https://github.com/user-attachments/assets/1ff689f9-ea6d-4b42-9b1b-382d839c6caf)

**Comment by AG-Zoheil** [comment]
Hi @melon2504,

Thank you for raising this. A tag was missing that has now been added, should show up in the pipeline soon.

Kind regards,
Zoheil
