### ISSUE TITLE
Tracking latest selected row (aka current row)

### ISSUE THREAD

**Issue by mikeerickson** [ceolter/ag-grid#888]
I am trying to build an interface whereby the last selected row (we call it current row) is styled differently that rest of selected row.

I tried to add this styling to the `.ag-row-focus` and everything works as expected (I remove the styling in `.ag-row-no-focus` style)

However, once the grid is stored, these classes don't stay with associated rows, but instead stick to the last rowIndex.  What I am looking for is a class which will "stick" the appropriate row so it is carried around when sorting (ala the `.ag-row-selected` class

**Comment by ceolter** [comment]
use gridOptions.getRowClass(params) callback.
