### ISSUE TITLE
Pinning a row results in duplicates

### ISSUE THREAD

**Issue by a6datta** [ceolter/ag-grid#8898]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Steps to reproduce**
   ```
gridOptions: GridOptions = {
    rowModelType: 'infinite',
    cacheBlockSize: 20,
    cacheOverflowSize: 2,
    maxConcurrentDatasourceRequests: 1,
    infiniteInitialRowCount: 100,
    maxBlocksInCache: 20,
    pagination: true,
    paginationPageSize: 20,  
    suppressMultiSort: true,
    pinnedTopRowData: [],
    pinnedBottomRowData: [],
  };
 triggerGridResize() {
      window.dispatchEvent(new Event('resize'));
    }

  pinRow(rowNode: any, position: 'top' | 'bottom') {
    const rowData = rowNode.data;
  
    if (position === 'top') {

      this.gridOptions.pinnedTopRowData = [...(this.gridOptions.pinnedTopRowData ?? []), rowData];
    } else if (position === 'bottom') {

      this.gridOptions.pinnedBottomRowData = [...(this.gridOptions.pinnedBottomRowData ?? []), rowData];
    }    
    this.triggerGridResize();

  }
  
  unpinRow(rowNode: any) {
    const rowData = rowNode.data;

    this.gridOptions.pinnedTopRowData = this.gridOptions.pinnedTopRowData?.filter(row => row.id !== rowData.id) ?? [];
    this.gridOptions.pinnedBottomRowData = this.gridOptions.pinnedBottomRowData?.filter(row => row.id !== rowData.id) ?? [];

    this.triggerGridResize();
  } 
```

**Current behavior**
When pinning a row in AG Grid using pinnedTopRowData or pinnedBottomRowData, the row is displayed in the pinned section, but it is not removed from the main grid, resulting in the row appearing twice (once in the pinned section and once in the original data set).

**Expected behavior**
When pinning a row, it should be removed from the main dataset and only appear in the pinned rows section (either at the top or bottom). Upon unpinning, it should be restored to the main dataset.

**Please tell us about your environment:**
Windows 10, VS Code, Angular 16.2.10

* **AG Grid version:** X.X.X
32.2.1

* **Browser:**
All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
5.1.6

**Comment by AG-Zoheil** [comment]
Hi,

This seems to be working in our examples: https://www.ag-grid.com/angular-data-grid/row-pinning/.

If it's not working after you are making adjustments to the code, please fork the plunker and send it to us and we'd be happy to look into it.

Thank you!

**Comment by haddad5** [comment]
Good afternoon,

I know this is an old post, but I believe the response is missing the main point of the discussion.  As you can see here in the Ag Grid Pinned Rows examples, you do end up having those "duplicate" rows as the OP mentioned.  Aleksey Nemov and Missy Franklin appear in two places.  First, in the pinned rows section, which is expected because they are pinned, but they are also appearing in the main body of the grid, which I believe is not desired behavior:

<img width="1040" height="647" alt="Image" src="https://github.com/user-attachments/assets/291260fb-81de-44cc-8449-4b65cfe530cf" />

If an additional option could be added in order to remove the "duplicates" (by that I mean the rows in the main body that are identical to the pinned rows), that would lead to more flexibility with this feature that I think a lot of developers would appreciate.

**Comment by AlejandroSanchez90** [comment]
> Good afternoon,
> 
> I know this is an old post, but I believe the response is missing the main point of the discussion. As you can see here in the Ag Grid Pinned Rows examples, you do end up having those "duplicate" rows as the OP mentioned. Aleksey Nemov and Missy Franklin appear in two places. First, in the pinned rows section, which is expected because they are pinned, but they are also appearing in the main body of the grid, which I believe is not desired behavior:
> 
> <img alt="Image" width="1040" height="647" src="https://private-user-images.githubusercontent.com/31868827/510407164-291260fb-81de-44cc-8449-4b65cfe530cf.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzE1Mjc5MjksIm5iZiI6MTc3MTUyNzYyOSwicGF0aCI6Ii8zMTg2ODgyNy81MTA0MDcxNjQtMjkxMjYwZmItODFkZS00NGNjLTg0NDktNGI2NWNmZTUzMGNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjE5VDE5MDAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExZTMxZjJiMjIwZGM4ZTNlMDEzODY5ZWQ4ZjJjNmUxODg5MmNjNmZlODQ3ZTI3ZDU0MDhkZGJhZTA4ZTk2NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.00vtW6tM1_Pu0VugKBpdAZGhGU8rfYVV2MrWWtIH3K4">
> If an additional option could be added in order to remove the "duplicates" (by that I mean the rows in the main body that are identical to the pinned rows), that would lead to more flexibility with this feature that I think a lot of developers would appreciate.

hey you ever got a fix for this ?
