### ISSUE TITLE
Bug - Set Filter reset between renders

### ISSUE THREAD

**Issue by fkul** [ceolter/ag-grid#8900]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

This is a followup to [7876](https://github.com/ag-grid/ag-grid/issues/7876).
I'm creating a new issue since my comment seems to have been missed. Feel free to close if needed.

**Providing a Reproducible Scenario**

Codesandbox: [link](https://codesandbox.io/p/sandbox/ag-grid-set-filter-bug-with-client-mode-forked-ygg9qk)

**Current behavior**
If the `keyCreator`, `comparator` or `valueFormatter` are defined within the column definitions, the filter for the column is reset when the grid re-renders.
A workaround is to define the functions outside the definitions.

Steps to reproduce:

1. Open the above codesandbox link.
2. Filter the column using the configured set filter.
3. Once rows are filtered, click the button on the grid to trigger a re-render.

**Expected behavior**
The filter for the column should be persisted between re-renders.

* **AG Grid version:**
32.2.1

* **Browser:**
any

* **Language:**
all

**Comment by AG-Zoheil** [comment]
Hi @fkul,

Thanks for raising this, your comment was indeed missed.

However, please note that the filter model is based on the keys. And if you provide a new key creator we don’t know whether the new keys match the old keys, so we reset the filter.

Therefore this is actually the correct behaviour.

Kind regards,
Zoheil
