### ISSUE TITLE
New checkbox selection stays on left

### ISSUE THREAD

**Issue by csicky** [ceolter/ag-grid#8907]
Since the new version, I see that `checkboxSelection` is deprecated. The new approach involves adding the checkbox selection directly in gridOptions instead of colDef. However, this causes an issue for our project because it restricts the checkbox position to only the left side.

In the previous version, I could place the checkbox anywhere I wanted. With the new approach, it seems locked on the left. I attempted various methods (`gridApi.moveColumns`, `gridApi.moveColumnByIndex`, etc.) to adjust its position, but none worked. There are no errors or warnings in the console.

How it is in previous version:
![image](https://github.com/user-attachments/assets/a6b2c5cc-7a77-4092-be11-ef55e97f239b)

I tried changing things in the colDef of this special column, but I can't move it to the right in any way:

```
selectionColumnDef: {
  width: 100,
  colId: 'joe', // changing colId is not possible
  maxWidth: 100,
  initialSortIndex: 2,
  sortingOrder: 2,
  sortIndex: 2,
  initialSort: 2,
  suppressHeaderMenuButton: false,
  headerTooltip: 'Cannot move this column to the right'
},
```

How I set the column order to make sure checkbox is after the dropdown:

```
//some more code before
// in a loop over array of columns named 'merged'
  if (col.colId === 'checkboxSelection' || col.colId === 'ag-Grid-ControlsColumn') {
    col.sortOrder = -2
  }
  if (col.colId === 'dropdownMenu') {
    col.sortOrder = -3
  }
//some more code after

//when all done, we apply column state
merged.sort((a, b) => compareNumbers(a.sortOrder, b.sortOrder))
this.gridApi.applyColumnState({ state: merged, applyOrder: true }) 

```

`applyOrder: true` means `ag-Grid-ControlsColumn` needs to come after `dropdownMenu`

![image](https://github.com/user-attachments/assets/768703ad-a42f-4d7f-b947-df2aeee1d272)

**Comment by wrm192** [comment]
I think this is a great example of the drawbacks of moving the checkbox from the column level to the row level. On one hand it makes logical sense that a row is checkable, but coldef seemed to provide more freedom. For me, I had a custom component that was using the checkbox property on the column to determine if a 'Select All' checkbox should be presented.  I see in this new approach this could be accomplished using 'multiRow' for the mode, but this doesn't play nicely with pagination and SSRM, as it will select all even off screen (also ignores filtering, and a slew of other issues).

**Comment by csicky** [comment]
The idea is not bad, you need checkbox selection on the row, set it in options, done.

However when we need customization, everything must be working on the special `colDef` provided. Including `colId`, order, any valid option. Maybe it was not fully understood the impact of this change. Probably `applyColumnState` is not working because there is no column, it is just injected later. 
At this point I think AG Grid team should just remove the deprecated flag from the old way and we can move on.
As it is now I am blocked. We'll have to sit on the previous version forever. I just don't understand why no response from the AG Grid team yet.

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for your feedback and comments.

Currently [grid state](https://www.ag-grid.com/javascript-data-grid/grid-state/) does not work with the `selectionColumn`. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-13121**. The order of the column will be controllable via state.

Regarding the SSRM comment, please note that this is something independent of the checkbox column and a feature request for this already exists: **AG-8980**.

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by Finton140** [comment]
@AG-Zoheil I see this ticket has been completed, but I can't find any docs on how to set the `selectionColumn` to a designated position. Could you advise?

**Comment by AG-Zoheil** [comment]
Please use gridstate for this: https://www.ag-grid.com/react-data-grid/grid-state/

Kind regards,
Zoheil

**Comment by Finton140** [comment]
@AG-Zoheil I understand that I have to use `gridState`, but there are no examples on how to set ordering using this, nor any examples of using this with `selectionColumn`

**Comment by Finton140** [comment]
Now solved.

for anyone else stumbling across this thread, it was solved on `v33.0.3` by passing the following `gridState` (or as the `initialState` prop if using React):
```js
{
    columnOrder: {
        // Make the selection column the second column
        // This is a workaround for the fact that the selection column is always first
        // and we can't change the order of the columns in the columnDefs
        orderedColIds: ['0', 'ag-Grid-SelectionColumn']
    },
    partialColumnState: true,
}
```

**Comment by JoelWaechter** [comment]
> Now solved.
> 
> for anyone else stumbling across this thread, it was solved on `v33.0.3` by passing the following `gridState` (or as the `initialState` prop if using React):
> 
> {
>     columnOrder: {
>         // Make the selection column the second column
>         // This is a workaround for the fact that the selection column is always first
>         // and we can't change the order of the columns in the columnDefs
>         orderedColIds: ['0', 'ag-Grid-SelectionColumn']
>     },
>     partialColumnState: true,
> }

I stumbled across this thread after noticing that an AG-Grid update broke some of our business applications using checkbox selection. Currently trying to avoid major refactoring, I attempted the suggested workaround but had no success. I also forked a StackBlitz example from the AG-Grid documentation ([Source](https://www.ag-grid.com/angular-data-grid/grid-state/)) and implemented the workaround there, but it didn’t work either.
What am I doing wrong?


[Code-Sandbox](https://codesandbox.io/p/sandbox/grid-state-forked-jtggg3)

**Comment by AG-Zoheil** [comment]
Hi,

As this has also been raised via our enterprise support portal addressing it there. Thanks

**Comment by JoelWaechter** [comment]
Thank you very much for the quick support — really impressive response time (<24h) by the AG-Grid-Team, chapeau!

After your reply on Zendesk, I tested the provided example and can confirm that it works.
The key difference compared to my initial implementation is the usage of:

```ts
selectionColumnDef: {
    lockPosition: undefined,
  },
```
in the GridOptions.

However, it's worth noting that this solution is version-dependent.
It does not work with version 33.0.2, but after upgrading to 33.2.4, it worked as expected.

For anyone who stumbles across this thread and is looking for a working example, here is the corresponding [Plunker](https://plnkr.co/edit/pj1xL1A7JIeLcHTj?open=main.js&preview)

Thanks again for the great support!
