### ISSUE TITLE
[Feature] Allow colDef.editable to be defined also per row

### ISSUE THREAD

**Issue by m4urer** [ceolter/ag-grid#891]
colDef.editable could be a boolean or a function right now, but it's only at coldef level.
I was wondering if you could add a row level function, like rowClass so it's not necessary to repeat the colDef.editable per column.
For example, I have a status in the row that determines if the columns are editable or not, and right now what I did is call the same editable() function in each colDef. So I think it would be great to have it at rowLevel. 
So I guess  that you could have any combination:
- Only define it at row level which would make all columns editable
- Define it only at column level if you don't want it to have it depend on the row
- Define it at row and column level: in order to have an editable column the rowLevel editable must be true and the column level editable could depend on each column data for that row.

Does it make sense?
Thanks in advanced!

**Comment by ceolter** [comment]
makes sense, but low priority, as there is a workaround

**Comment by noherczeg** [comment]
@ceolter what workaround is that? I'm curious, because we currently are hacking our way to glory right now, but if there is a somewhat reasonable workaround for this we might be interested as well.

We are working our way towards row level editing where if toggled all editable columns turn into edit mode at once, and not just as a per cell basis.

**Comment by ceolter** [comment]
```We are working our way towards row level editing where if toggled all editable columns turn into edit mode at once, and not just as a per cell basis.``` that's going to be impossible with the grids built in editing unless i specifically code it in, as the grid works like excel, it only allows once cell to be editable at any given time.

in the original request in this issue, i took it as wanting to allow editing on all the cells, but not editing them at the same time.

**Comment by noherczeg** [comment]
My understanding  was that a cell's edit mode should be triggered by row, column, and in mixed modes as well simultaneously.

**Comment by marc314** [comment]
Interested in hearing about this workaround as well. I have requirements where specific cells within a column are not editable as well as specific rows being completely uneditable.. Any advice would be appreciated

**Comment by stephanjust** [comment]
> Interested in hearing about this workaround as well. I have requirements where specific cells within a column are not editable as well as specific rows being completely uneditable.. Any advice would be appreciated

As mentioned in the first post colDef.editable can be a function that receives a param object to check whether a clicked cell is editable. While this function is defined on the column level, nothing stops you from adding arbitary values to a row and check for these in the editable function. We're currently doing exactly that and it works great.

**Comment by marc314** [comment]
https://github.com/ceolter/ag-grid/blob/d60dec55225eb3da16a64dd829f8fb4c06ab46c8/dist/lib/entities/column.js#L115

Found it :)

**Comment by ceolter** [comment]
you can now set default values for the colDefs using grid property defaultColDef, so this covers the original question of having it definable per row. if you just define 'editable' once in defaultColDef, it gets applied to all columns.

**Comment by tkssharma** [comment]
How to switch between editable or non-editable
my case - if I change the value of one column it should disable all other columns in the same row.. is this possible with the current implementation

**Comment by stephanjust** [comment]
You know that this is a 2 year old discussion, right? ;)
Anyway, what you're asking is possible - we're doing it in our project. As colDef.editable is allowed to be a function, define an editable function that checks for a flag in the row (e.g. "isEditable"). Then when editing one of your colums, set "isEditable" in your row to false. Afterwards force Ag-Grid to redraw the row with one of the methods mentioned here: https://www.ag-grid.com/javascript-grid-refresh/

**Comment by awaisaly** [comment]
you can achieve it by using editable property in colDefinition and play around with the row data to make it either editable or not.

```
colDef:[
    { 
       headerName: 'XYZ',
       field: 'xyz',
       editable: ({ data: { anyRowAttribute } }) => anyRowAttribute
    }
]
```
