### ISSUE TITLE
multiRow + enableClickSelection only single selects on clicks

### ISSUE THREAD

**Issue by juliancarrivick** [ceolter/ag-grid#8911]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
In a grid with `rowSelection: { mode: 'multiRow', enableClickSelection: true }, if you click the checkboxes then multiple rows can be selected, if you click anywhere on the row then it behaves like `singleRow` is specified. See plunkr [here](https://plnkr.co/edit/3cvY3gBtQF5IDMdW?open=main.js). 

**Expected behavior**
I would expect clicking the row to have the same behaviour as clicking a checkbox. i.e. Use `multiRow` behaviour.

**Please tell us about your environment:**
Angular 18.3 in the browser.

* **AG Grid version:** 32.2.1
* **Browser:** `Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"`
* **Language:** TypeScript 5.5

**Comment by AG-Zoheil** [comment]
Hi,

Thank you for raising this. Please see this part of our documentation to help you achieve your desired behaviour: https://www.ag-grid.com/javascript-data-grid/row-selection-multi-row/#selecting-multiple-rows-without-ctrl-key.

Kind regards,
Zoheil

**Comment by juliancarrivick** [comment]
Ah, that's great, thanks @AG-Zoheil!

**Comment by Nirmal314** [comment]
I faced the same issue, fixed it thanks for the direction @AG-Zoheil @juliancarrivick
