### ISSUE TITLE
AG-grid Responsiveness

### ISSUE THREAD

**Issue by lawaldare** [ceolter/ag-grid#8913]
I just need the best way to make the Ag-grid table responsive. Using `flex:1` for the Coldef will make the columns filled the table container, but would not make the table responsive, but if I used specific width for the coldef, it is quite tedious and sometimes on a bigger screen, it won't fill the width of the container.

Using `Flex` filled the width the container but won't be responsive - Using specified `width` will be responsive but won't filled the width of the container.

I set Ag-grid width 100% of the container - which has specified width.

**Comment by MudulOzan** [comment]
if you are looking responsiveness for columns ag grid has autosize property https://www.ag-grid.com/react-data-grid/grid-api/#reference-columnSizing-autoSizeAllColumns @lawaldare

**Comment by lawaldare** [comment]
> if you are looking responsiveness for columns ag grid has autosize property https://www.ag-grid.com/react-data-grid/grid-api/#reference-columnSizing-autoSizeAllColumns @lawaldare

![Screenshot 2024-10-08 at 12 38 45](https://github.com/user-attachments/assets/4361e0ab-5211-4ee0-ace7-49b4de8e401b)

Using that with or without `flex:1` still some space on the table

**Comment by lawaldare** [comment]
Setting `flex:1` in the defCol definitions work perfectly, as it takes all the width and divide the columns equally
![Screenshot 2024-10-08 at 12 40 48](https://github.com/user-attachments/assets/ea489cc8-2962-4a79-bcb1-5e2f34149621)

But issue is responsiveness
![Screenshot 2024-10-08 at 12 41 02](https://github.com/user-attachments/assets/5404f86c-c26b-466b-858e-12c705a49bc4)

**Comment by MudulOzan** [comment]
as far I understand you want table to fill the page and columns to be responsive, in that case make it autosize and have flex on ag grid container, not columns. That would result a full page table with autosized columns

**Comment by lawaldare** [comment]
> as far I understand you want table to fill the page and columns to be responsive, in that case make it autosize and have flex on ag grid container, not columns. That would result a full page table with autosized columns

Thanks @MudulOzan

**Comment by MudulOzan** [comment]
@lawaldare did it solve ur problem?

**Comment by lawaldare** [comment]
> @lawaldare did it solve ur problem?

Actually it did not. I decided to give width to all the columns so it could full fit the container on desktop view and be responsive on mobile

**Comment by sushiltechnex** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by lawaldare** [comment]
I also noticed we can only set a fixed height for ag-grid, what if we only have 1 or 2 row like in the image

![Screenshot 2024-11-10 at 21 59 38](https://github.com/user-attachments/assets/68fe9754-4d3d-4076-9bd7-1f2cb4366370)

Lots of spaces, I set `height:500px` for the container `div`. Using `min-height` or `max-height` didn't work

**Comment by lawaldare2024** [comment]
> I also noticed we can only set a fixed height for ag-grid, what if we only have 1 or 2 row like in the image
> 
> ![Screenshot 2024-11-10 at 21 59 38](https://private-user-images.githubusercontent.com/17833317/384728918-68fe9754-4d3d-4076-9bd7-1f2cb4366370.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MDYyNDgsIm5iZiI6MTczMjcwNTk0OCwicGF0aCI6Ii8xNzgzMzMxNy8zODQ3Mjg5MTgtNjhmZTk3NTQtNGQzZC00MDc2LTliZDctMWYyY2I0MzY2MzcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDExMTIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlZGRmNGJhM2YyYzM0OTU1NmYwMTRmY2NkMjFhMTZiMjJhOTIwNDEzZjEyOTFhNjBhODgzZjIwZThhYmViZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MFlKS-FvNmb3JbdK6XjlIT6h4feZfmMkd577mtVDGFE)
> 
> Lots of spaces, I set `height:500px` for the container `div`. Using `min-height` or `max-height` didn't work

I noticed this too, there are times data won't be as much as the height of the table

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
