### ISSUE TITLE
Cell Editor on group

### ISSUE THREAD

**Issue by soloveynchub** [ceolter/ag-grid#8914]
Hello!

I have a big problem with Cell Editor Params.
If I enabled cell editor only on group this dose not work. 

I try enabled editable params on this place `editable: (paramses) => paramses.node.group`, but this not work too.

Pls, help me, or if this have a bug, pls fix it.

```
columnDefs.push({
          headerName: 'Руководитель отдела',
          field: 'Руководитель отдела',
          cellRenderer: (paramses) => {
            // Проверяем, является ли строка группирующей
            if (paramses.node.group) {
              const value = paramses.value || 'Руководитель не выбран';
              const className = value === 'Руководитель не выбран' ? 'no_head' : 'have_head';
              return `<span class="${className}">${value}</span>`;
            }
            return paramses.value; // Не отображаем поле "Руководитель отдела" для сотрудников
          },
          editable: (paramses) => paramses.node.group, // Разрешаем редактирование только для групп
          cellEditor: 'agRichSelectCellEditor',  // Используем agRichSelectCellEditor для автопоиска
          cellEditorParams: {
            values: departmentHeads, // Динамически загруженные ФИО
            searchEnabled: true,  // Включаем функцию поиска
            cellEditorPopup: true, // Попап для выбора из списка
            allowTyping: true,
            filterList: true,
            highlightMatch: true
          }
        });
```

**Comment by csicky** [comment]
I am not sure you can have cells editable on groups, but you can always build a custom cell, have that be the group cell and inside you can do whatever you want. It is just more work.

https://www.ag-grid.com/javascript-data-grid/group-custom-group-comp/

**Comment by soloveynchub** [comment]
@csicky thank you for the solution to this problem. At the moment, there are no other options. But I saw that there was a similar request and it was resolved in update 32.0.2 under the number AG-12410, but for some reason it is not in the official change history.

**Comment by soloveynchub** [comment]
Now, I close this issue, b-cose, it is not possible.
I create custom component

**Comment by AG-Zoheil** [comment]
Hi @soloveynchub,

Thank you for your comment. Please note that we've consolidated our backlog and **AG-12410** can now be tracked under **AG-12283**.

Kind regards,
Zoheil
