### ISSUE TITLE
Ag grid cell renderers with action button are not accessible through key board click

### ISSUE THREAD

**Issue by ChithiraMG** [ceolter/ag-grid#8916]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

In ag grid , action buttons added through celle renderer are not accessible through keyboard hence not able to perform any action through keyboard

**Providing a Reproducible Scenario**
https://www.ag-grid.com/react-data-grid/component-cell-renderer/
https://www.ag-grid.com/examples/component-cell-renderer/cell-renderer-summary/modules/reactFunctionalTs/
Here "Launch" action is not clickable through keyboard

**Expected behavior**
All action buttons inside ag grid should be accessible through keyboard

**Please tell us about your environment:**

* **AG Grid version:** X.X.X
"ag-grid-community": "^30.0.0",
    "ag-grid-enterprise": "^30.0.0",
    "ag-grid-react": "^30.0.0",

* **Browser:**
Chrome, edge

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by AG-Zoheil** [comment]
Hi,

Please see this section of our documentation: https://www.ag-grid.com/javascript-data-grid/keyboard-navigation/#custom-cell-component.

Kind regards,
Zoheil

**Comment by ChithiraMG** [comment]
Still action button is not clickable, we can only navigate with tab
