### ISSUE TITLE
Select only visible rows

### ISSUE THREAD

**Issue by realavaloro** [ceolter/ag-grid#892]
The documentation for the grid API says the following for `selectAll()`:
> Select all rows (even rows that are not visible due to grouping being enabled and their groups not expanded).

How to select only the visible ones?
```
gridOptions.api.forEachNode((node: any) => {
         node.setSelected(true);
});
```
node does not seem to have any property such as `isVisible` which would be useful unless there is some other way to select only visible ones?

**Comment by ceolter** [comment]
you can iterate through the visible rows with:
```
var model = api.getModel();
for rowCount = model.getRowCount();
for (var i = 0; i<rowCount; i++) {
  var rowNode = model.getRow(i);
  rowNode.setSelected(true);
}
```

**Comment by Jamuna-Devi-Vijayan** [comment]
I want to get the first visible row to the user. For my case rows on screen to user is 17 but medel.getRowCount() on this.getModel returns 43

**Comment by bilalqureshi10p** [comment]
I can confirm the upper behavior

**Comment by dereklin** [comment]
I am looking for a reliable way to get the truly visible rows in the viewport to work around the ensureIndexVisible problem.  Right now, ensureIndexVisible scrolls my grid even when the row is already visible.

**Comment by dbetts** [comment]
You can do this to get the first visible and the last visible row. If you don't have any filtering, and can trust that the row IDs are ordered from smallest to greatest, this can work:

        var firstRow = options.api.getFirstDisplayedRow();
        var lastRow = options.api.getLastDisplayedRow();

        for(var i=firstRow; i<=lastRow; i++) {
            var node = options.api.getRowNode(''+i+'');
            node.setSelected(true);
        }

May not be the best option, but it may work in some cases.

**Comment by mblataric** [comment]
> This will return the first row and last row in the buffer (rows hidden above and below your viewport), so if you don't want that, you will either need to offset the selected rows by the buffer amount, or set your buffer in the gridOptions to zero. I chose the latter as I'm using a client-side rowModel:

What does that mean "offset the selected rows by the buffer amount"?
Also, wouldn't it be reasonable to expect that grid does that in a function named getFirst**Displayed**Row and actually returns first VISIBLE row?

It is not called getFirstLoadedRow ...

**Comment by AnthonyGio** [comment]
@mblataric 
Too true, this was very confusing when I encountered it. But anyway, you can easily resolve this by doing getFirstDisplayedRow() + (rowbuffer / 2) so +10 by default.

**Comment by talkwithus** [comment]
this.gridApi.getRenderedNodes().forEach(node => node.setSelected(true))

**Comment by jfstephe** [comment]
@AnthonyGio - How does that work?
Your rowBuffer is 100.
You have 50 items.
The visible area can hold 5 rows.
I scroll half-way down the list (e.g. rows 50 - 54 visible)
getFirstDisplayedRow() would be 0, rowBuffer = 100 so using the formula provided this would give 50. Cool, but if I scroll to row 40 I'm going to get the same result :-(.

**Comment by jfstephe** [comment]
FYI I've raised ticket 5540 in ZenDesk asking for [this ](https://github.com/ag-grid/ag-grid/issues/2097) related issue to be resolved.

**Comment by argarner** [comment]
@jfstephe is the ZenDesk ticket something unpaid users can see? I couldn't find it and your link is closed...

[Here's a solution to obtaining the visible selected rows based on the current API](https://stackoverflow.com/questions/43542110/how-to-get-filtered-rows-in-ag-grid/59658591#59658591)

**Comment by akashsolanki** [comment]
I used a dirty workaround to get the visible rows - https://stackoverflow.com/a/63597163/3503019

But I still think ag-grid should provide an api to find visible rows. At least for Enterprise users.

**Comment by ryarasi** [comment]
This is the closest I have come to an elegant solution:-

`      function onSelectionChanged(event) { 
        let selectedNodes = gridOptions.api.getSelectedNodes();
        // Detecting if the selected rows are more than page size
        if (selectedNodes.length > pageSize) {
          // if yes, first deselect everything...
          gridOptions.api.deselectAll();
          // ... then only selecting the visible rows
          gridOptions.api
            .getRenderedNodes()
            .map((node) => node.setSelected(true));
        }`

This implementation was for plain JS, you might have to adapt it for your use case.

**Comment by veltenguilherme** [comment]
solved to me with angular 14 and newest ag-grid version:

 this.gridApi.getRenderedNodes().map((node) => node.setSelected(true));
