### ISSUE TITLE
AgGrid React: Grid not getting rendered on columnDef state update to hide: undefined

### ISSUE THREAD

**Issue by Yaminim07** [ceolter/ag-grid#8926]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Used AgGridReact to render the grid. Sending initial columnDef as below,
`[
    { field: "make" },
    { field: "model" },
    { field: "price" },
    { field: "electric" },
  ]`

Updating the visibility of columns using checkbox and setting "hide" property in the columnDefs. Resetting the visibility of columns by sending the same initial columnDef on reset button click. Grid is not getting updated in reset button click. 

Sample codesandbox: https://codesandbox.io/p/sandbox/quick-start-example-forked-l2qxdp?file=%2Fsrc%2Findex.js%3A31%2C42-36%2C4&workspaceId=5223eb75-00da-40f4-a9bd-c352d3050a0c

Steps to reproduce:
1. Toggle the visibility of columns using the checkbox
2. Click on reset button
3. Grid not going to initial state
 
**Expected behavior**
Grid should re-render on reset button click.

***Note***
If hide: false is passed explicitly while updating columnDef then reset works.

**Comment by AG-Zoheil** [comment]
Hi @Yaminim07,

Thank you for getting in touch.

Please view the third bullet point in this section of our documentation: https://www.ag-grid.com/javascript-data-grid/column-updating-definitions/#changing-column-definition.

`Note that any resizing, sorting etc of the Columns is kept intact between updates to the Column Definitions.`

To override this behaviour you would have to explicitly set the desired colDef.

I hope this helps.

Kind regards,
