### ISSUE TITLE
LLM Sheets

### ISSUE THREAD

**Issue by ockhamlabs** [ceolter/ag-grid#8947]
Is it possible to enable LLM Sheets where a column (or set of columns) values are based on LLM call that takes inputs from other columns in a row? Similarly can we do anything where a function is called used to finish the rest of columns (it could be vlookup etc).

**Comment by AG-Zoheil** [comment]
Hi @ockhamlabs,

Thanks for getting in touch via GitHub.

We are currently not considering feature requests via GitHub.

We appreciate your time for raising this and hope you can continue to use the current functionality available in AG Grid Community.

Kind regards,
Zoheil
