### ISSUE TITLE
why the rendered columns have an additional blank column at the far right?

### ISSUE THREAD

**Issue by rcholic** [ceolter/ag-grid#895]
I use `ag-grid` with Angular 1.5 and I have defined 5 columns in the following format in an array:
```
[
{headerName: 'Username', width: 150, field: 'username'},
{headerName: 'Full Name', width: 150, field: 'full_name'},
{headerName: 'Location', width: 150, field: 'location'},
{headerName: 'Email', width: 150, field: 'email'},
{headerName: 'Check In Comment', width: 370, field: 'comment'},
];
```

The rendering shows 6 columns with the right-most one being blank. I've tried everything, but I cannot still remove the blank column. See the below screenshot:
![screen shot 2016-05-10 at 11 26 40 am](https://cloud.githubusercontent.com/assets/135060/15152283/aa8be462-16a2-11e6-92b1-a27d533e81f1.png)

*gridOptions:*
```
options = {
                rowData: dataArray,
                rowModelType: 'pagination',
                columnDefs: getColumnDefs(),
                enableColResize: true,
                enableSorting: false,
                enableFilter: true,
                rowHeight: 25,
                angularCompileRows: true,
                suppressRowClickSelection: true
            };
```

*The html code:*
```
<div style="width: 100%;"
                     ag-grid="vm.gridOptions"
                     class="ag-fresh ag-basic">
                </div>
```

**Comment by ceolter** [comment]
this is not a problem with the grid, so should be on the forum, github is for tracking changes the grid needs.

however, i don't see anything wrong with the above. maybe your data?
