### ISSUE TITLE
AG-GRID Changing Data Format When Edit a Cell

### ISSUE THREAD

**Issue by igorcrivellari** [ceolter/ag-grid#8950]
Dear team,

We are currently using AG-GRID to test its efficiency as a data visualization component for tables. However, when loading data into the table, if the first row contains null values in date fields, AG-GRID somehow loses the date format (dd/mm/yy). While the dates are displayed correctly, when editing a cell, the date field shows in the (yyyy-mm-dd) format as an input instead of opening the calendar modal. We are using agDateColumnFilter in the column to specify that it is a date field.

Does anyone know how we can prevent null date values in the first row from affecting the date format in the remaining rows?

**Issue view table:**
![image](https://github.com/user-attachments/assets/7b8014dc-2ac9-4e96-95db-17dba1ebe522)

**Issue Edit table with de problem with the data-type** 
![image](https://github.com/user-attachments/assets/ff785518-bfff-47af-aa34-96a20fd995fc)

Best regards,

**Comment by sushiltechnex** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
