### ISSUE TITLE
Last row group column is turned to flat column in pivot mode

### ISSUE THREAD

**Issue by ppatliak** [ceolter/ag-grid#8956]
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```
Hello AgGrid Team,

I`m using Grid with pivoting and my last row grouping column becomes a flat column, it loses collapse/expand button. Is there any way to suppress this behavior? Thanks in advance!

Plunker - https://plnkr.co/edit/RdgSF4GKCZ53KuNa?open=index.tsx 

**Please tell us about your environment:**
Windows 11, Visual Studio Code, yarn

* **AG Grid version:** 31.1.0+

* **Browser:**
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'

* **Language:** [all | TypeScript 5.3 | ES6/7 | ES5]

**Comment by sushiltechnex** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
