### ISSUE TITLE
Class for row group doesn't change when the row is expanded contracted

### ISSUE THREAD

**Issue by fabiogallo-blueprint** [ceolter/ag-grid#896]
Tested on https://www.ag-grid.com/example-file-browser/index.php

When I close (or open) any of the "folders" in the example, the classes for the related row doesn't change from "ag-row-group-expanded" to "ag-row-group-contracted" (and vice-versa).

**Comment by ceolter** [comment]
thanks, will take a look

**Comment by randdusing** [comment]
The group row doesn't get redrawn on expand/collapse. Try this code below to force redrawing:

```javascript
gridOptions.onRowGroupOpened = function (params) {
  gridOptions.api.refreshRows([params.node]);
}
```

**Comment by ceolter** [comment]
fixed. will be in next release. thanks.
