### ISSUE TITLE
No single pointer mode of operation is provided to adjust the pane after expanding column/filter button in Windows.

### ISSUE THREAD

**Issue by msftedad** [ceolter/ag-grid#8962]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'

```

**Providing a Reproducible Scenario**

1. Hit the URL: [React Grid: Quick Start | AG Grid (ag-grid.com)](https://www.ag-grid.com/react-data-grid/getting-started/) in Browser.
2. Press tab key to reach to "Demos" control and activate it using enter key.
3. Press tab key to reach till "Columns/Filters" controls and activate it using enter key.
4. Verify whether any alternative is provided for single pointer mode of operation to adjust the pane after expanding column/filter button or not.

**Current behavior**
No single pointer mode of operation is provided to adjust the pane after expanding column/filter button in windows.

[230475 [AG Grid] [Dragging Movements].webm](https://github.com/user-attachments/assets/07285c96-3a02-465b-9ab5-8f430b949674)

<img width="954" alt="230475_ AG Grid   Dragging Movements  No single pointer mode of operation is provided to adjust the pane after expanding column or filter button in windows" src="https://github.com/user-attachments/assets/3c427ada-45fe-4305-950e-2a336f29aadc">

**Expected behavior**
Single pointer mode of operation should be provided to adjust the pane after expanding column/filter button in windows.

**Please tell us about your environment:**
OS: Windows 11 Version 24H2 (OS Build 26100.1742)
Browser: Microsoft New Edge (Version 129.0.2792.65) (Official build) (64-bit)
Chrome version: Version 129.0.6668.71 (Official Build) (64-bit)

* **AG Grid version:** 
32.2.0
* **Browser:**
Browser: Microsoft New Edge (Version 129.0.2792.65) (Official build) (64-bit)
Chrome version: Version 129.0.6668.71 (Official Build) (64-bit)

**Comment by AG-Zoheil** [comment]
Hi @msftedad,

Thanks for raising this.

I'm afraid we are not clear on the issue that is being reported.

Can you please clarify what you think is missing with more detailed steps? Your video shows the demo page but the link you've pasted goes to Quick start.

Also you are using a single-pointer gesture/operation to resize the sidebar - so we are not clear what is missing?

Looking forward to hearing back from you.

**Comment by msftedad** [comment]
Hi @AG-Zoheil, As mentioned in step 2 of the repro steps, tab to the 'Demos' control and activate it. This will take you to the page shown in the attachments. Alternatively, you can directly access the page using this link:
[https://www.ag-grid.com/example/.](https://www.ag-grid.com/example/)
While we can resize, the sidebar using a mouse, there is currently no single-pointer alternative available for resizing the sidebar. 
Please let us know if any further information is required.

**Comment by AG-Zoheil** [comment]
Hello @msftedad,

Thank you for the clarification.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-13141**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
