### ISSUE TITLE
[Pivot] moving columns between 'Row groups' 'Values' and 'Column Labels' is not possible when there is only 1 column in all those fields

### ISSUE THREAD

**Issue by Xefram** [ceolter/ag-grid#8963]
When in pivot mode, moving columns between  'Row groups' 'Values' and 'Column Labels' fields is not possible when there is only one column in those fields. For example, when 1 column is there, moving it from 'values' to 'Row groups' results in column being turned off from pivot mode. Attached video to showcase the issue.
[Screencast 2024-10-10 11-19-01.webm](https://github.com/user-attachments/assets/bb00dded-87f6-4a2e-a5b8-ac0aa1690cc1)

**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- Turn on pivot mode for the table
- Turn on 1 column for pivot mode- it lands in value field
- Move the column from 'values' to 'Row groups'-> column is turned off
- Check 2 columns for pivot mode
- Move 1 of the columns from 'values' to 'Row groups'-> In this case column is moves from 1 field to another

**Current behavior**
User can move columns betweend fields when there is more than 1 column checked for pivot mode

**Expected behavior**
User should be able to move columns between fields when there is only 1 column checked for pivot mode

**Please tell us about your environment:**
yarn 1.22.22

* **AG Grid version:** 
ag-grid-community 32.1.0
ag-grid-enterprise 32.1.0
ag-grid-react 32.1.0

* **Browser:**
Chrome 129.0.6668.90

* **Language:** 
 typescript 5.5.4

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by sushiltechnex** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
