### ISSUE TITLE
Method does not exist: showLoading(show)

### ISSUE THREAD

**Issue by AmitMY** [ceolter/ag-grid#897]
In your API documentation you specified:

> showLoading(show)
> Show or hide the loading icon. Pass either true or false. If the method setRowData is called, the loading icon is automatically hidden.

This function did not work for me, and I could not find this function in the source code.

To show loading, I still can use showLoadingOverlay
But there is no method that I found to hide it, except for the one above, which does not exists in:

> ag-grid/dist/ag-grid.js
> f8e67d4  13 days ago
> release of 4.1.5

Is that documentation of v4.1.6? If so, do you have a release time frame? It's a bit confusing..

I love this table very much, especially the always continued support and new releases.
Thanks!

**Comment by ceolter** [comment]
docs are wrong, i've updated them (will be in next release).

what you want are the methods:
showLoadingOverlay()
showNoRowsOverlay()
hideOverlay()

**Comment by AmitMY** [comment]
Thanks!
