### ISSUE TITLE
header column data apply 

### ISSUE THREAD

**Issue by swethadmurthy2024** [ceolter/ag-grid#8979]
Hi Team, 
     In angular for AG-grid, do you have feature as below
     user select a dropdown from table column and that data selected is applied to all column rows.
       
Thanks,
Swetha

**Comment by sushiltechnex** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
