### ISSUE TITLE
ag-grid-aurelia Compatibility with Latest ag-grid Versions

### ISSUE THREAD

**Issue by XmasCarola** [ceolter/ag-grid#8980]
Hi team,

I'm submitting a... [x] **feature request**.
It would be great to have an update for the ag-grid-aurelia package to ensure full compatibility with the latest versions (32.2) of ag-grid. The deprecated ag-grid-aurelia library does not fully align with the recent improvements and, as a user of ag-grid in the Aurelia ecosystem, I am going through a rough patch with the migration process.

Since I am also a contributor of Aurelia 2, I would like to be involved in the development process to ensure the update aligns with the latest framework version and functionalities.

Let me know.
Thanks.

**Comment by AG-Zoheil** [comment]
Hi @XmasCarola,

Thank you for getting in touch.

At this point in time our focus is on other projects and parts of the AG Grid ecosystem and therefore we are not in a position to provide an update for the ag-grid-aurelia package.

Thank you for understanding!

Kind regards,
Zoheil
