### ISSUE TITLE
V30.2.1 Vulnerabilities

### ISSUE THREAD

**Issue by mnmz81** [ceolter/ag-grid#8983]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Requesting Community Support**
There is a security vulnerability for version 30.2.1, see here:
https://security.snyk.io/package/npm/ag-grid-community/30.2.1
I have no problem making a PR with a fix for the issue (I managed to compile the product)

**Comment by AG-Zoheil** [comment]
Hi @mnmz81,

Thank you for your comment. As indicated in the synk link please upgrade to version `31.3.4` to benefit from the already existing fix for this issue.

Kind regards,
Zoheil
