### ISSUE TITLE
Server Side Aggregation etc .. 

### ISSUE THREAD

**Issue by erfangc** [ceolter/ag-grid#899]
Hi Team,

We are evaluating whether to purchase the **agGrid **enterprise license. Could you let me know if **agGrid** supports Server Side subtotaling? 
(ex: what if I wanted to render 10mm rows and allow users to drilldown to the individual rows)

Would **agGrid** have support for all features such as subtotal collapse / expand through a complex REST API. (to clarify, we would host and implement the API, agGrid only define the contract)

Sorry if GH issues is not he best place to ask these questions, but it appears the free forum is not monitored.

**Comment by ceolter** [comment]
```but it appears the free forum is not monitored.``` -> i clear up github and the free forum at the same rate!!! which is i visit each every few days.

if you are doing side, then you are on your own with regards subtotaling. but also depends on what you are trying to do.

are you expecting the grid to lazy load nodes, so each time you click, it does a server side call? if so, then that's not supported. a good idea though, so maybe in a future release. if a big company wants to sponsor this development, it can be pushed up the list.

what you can do is use viewport (the new model introduced last month, that allows the 'pushed updates). that gives you complete control, so you can create your own cellRenderer for groups, and provide your own logic. that is what i am currently doing with a large client (the viewport was designed with that in mind).

**Comment by erfangc** [comment]
@ceolter Understood thank you
