### ISSUE TITLE
Icons Not Rendering in Tool Panel After NuxtUi Update

### ISSUE THREAD

**Issue by luacooli** [ceolter/ag-grid#8999]
![Captura de tela 2024-10-14 165456](https://github.com/user-attachments/assets/dc3cbe03-1891-4cd6-b38b-66649ca84d0e)

**I'm submitting a ...
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behavior in one of our examples in the docs.
- A plunker

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
After updating nuxt-ui to 2.18.6, the icons inside the tool panel of the AG Grid framework are no longer rendering as expected

**Expected behavior**
After any update, the icons in tool panel should be rendered as expected

**Please tell us about your environment:**
- Operating System: Windows_NT
- Node Version:     v20.9.0
- Nuxt Version:     3.13.1
- CLI Version:      3.14.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@8.10.5

* **AG Grid version:** 32.2.2

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36'

* **Language:** [all | TypeScript 5.6.3| ES6/7 | ES5]

**Comment by AG-Zoheil** [comment]
Hi,

Thanks for getting in touch.

It looks like you're using a custom tool panel by rendering a custom component.

This is very likely an issue with NuxtUI not with the grid, but one way to narrow this down is to set up a test page that renders the custom tool panel component without a grid. If the same issue appears, it's an issue with your component or a library you're using. If the icons render fine when the component is outside the grid and don't render when they're moved into the grid, that may be something we need to look into.

Please review the above before any further action.

I'll close this issue in the meantime.

Kind regards,
Zoheil
