### ISSUE TITLE
Volatile Display on setRowData

### ISSUE THREAD

**Issue by JonahJ** [ceolter/ag-grid#900]
Related to issue on enterprise version [here](https://github.com/ceolter/ag-grid-enterprise/issues/16)

When I call setRowData the currently selected row and filtered column are reset. I'm getting around this with the following code (below), but this should probably be an option in setRowData.

```
var selected_currently = $scope.gridOptions.api.getSelectedNodes()[0];
var previous_filter_model = $scope.gridOptions.api.getFilterModel();

$scope.gridOptions.api.setRowData(orders.get());

if (selected_currently) $scope.gridOptions.api.selectNode(selected_currently, true, true);
if (previous_filter_model) $scope.gridOptions.api.setFilterModel(previous_filter_model);
```

**Comment by ceolter** [comment]
for filter, see property newRowsAction

for selection, your right, it looses selection, however that is by design, as the 'new rows' are probably different rows. the workaround you have is the intention.
