### ISSUE TITLE
Pivot Total Column Sums Up Multiple Value Columns

### ISSUE THREAD

**Issue by gikoifma** [ceolter/ag-grid#9002]
**I'm submitting a support request ** 

I'm using pivotColumnGroupTotals with multiple value columns.

The Total column sums up all of the value columns, same when collapsing.

On the contrary, when pivotColumnGroupTotals is false, after collapsing, it doesn't sum up the different value columns together. It keeps them separated.

How can I achieve a total column for each value column? I don't want them to be summed up together.

https://codesandbox.io/p/sandbox/tool-panel-simple-forked-gts6tz?file=%2Fmain.ts%3A66%2C3

**Please tell us about your environment:**
Windows

* **AG Grid version:** 32.2.2

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36

**Comment by sushiltechnex** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
