### ISSUE TITLE
valueGetter and cellRenderer not waiting for asynchronous function completion in ag-Grid

### ISSUE THREAD

**Issue by snawar92** [ceolter/ag-grid#9008]
I'm submitting a ...
[x] bug report

Current behavior
When using valueGetter and cellRenderer with asynchronous operations (like API calls or complex computations), the grid is not waiting for the function to finish before rendering the cell. This results in cells showing intermediate or incorrect values instead of the final computed result.

Specifically:
1. The valueGetter returns before the asynchronous operation completes.
The cellRenderer renders with incomplete data.
Cells show 'Processing...' or undefined values even after the async operation finishes.

Expected behavior
1. The valueGetter should wait for the asynchronous operation to complete before returning a value.
The cellRenderer should render only after the final value is available.
Cells should show the correct, computed value once the async operation finishes.

Reproducible Scenario
Here's a minimal example to demonstrate this issue:

    <div id="myGrid" style="height: 200px; width: 100%;" class="ag-theme-alpine"></div>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const gridOptions = {
                columnDefs: [
                    { field: 'id', headerName: 'ID' },
                    {
                        field: 'asyncData',
                        headerName: 'Async Data',
                        valueGetter: async (params) => {
                            // Simulate an API call
                            const result = await new Promise(resolve => 
                                setTimeout(() => resolve(`Data for ${params.data.id}`), 1000)
                            );
                            return result;
                        },
                        cellRenderer: (params) => {
                            if (params.value instanceof Promise) {
                                return 'Loading...';
                            }
                            return params.value;
                        }
                    }
                ],
                rowData: [
                    { id: 1 },
                    { id: 2 },
                    { id: 3 }
                ]
            };

            const gridDiv = document.querySelector('#myGrid');
            new agGrid.Grid(gridDiv, gridOptions);
        });
    </script>

In this example, cells initially show 'Loading...', but they don't update to the final value once the promise resolves.

Please tell us about your environment:
AG Grid version: [current]
Browser: [chrome mac]
Language: JavaScript (ES6)

Additional context
This issue is critical for applications that need to display data that requires asynchronous computation or fetching. It affects the accuracy and reliability of the displayed information.
Potential workarounds like manually refreshing cells or using setInterval to check for updates are not ideal solutions as they can lead to performance issues or unnecessary complexity.

Any guidance on how to properly handle asynchronous operations in valueGetter and cellRenderer, or if there are plans to support this natively in ag-Grid, would be greatly appreciated.

**Comment by ockhamlabs** [comment]
Would be great to have inputs on this as this is relevant for us as well

**Comment by sadath-12** [comment]
was this resolved ?

**Comment by snawar92** [comment]
Can you help me on this ?
@taktran @peterjrreynolds @SalvatorePreviti @markdurrant @AndrewGlazier

**Comment by AG-Zoheil** [comment]
Hi @snawar92,

Thank you for raising this.

I'm afraid this is not supported. You can see this based on the return types in our docs: https://www.ag-grid.com/react-data-grid/column-properties/#reference-columns-valueGetter.

Kind regards,
Zoheil
