### ISSUE TITLE
Need to bump up HEADLESSUI.

### ISSUE THREAD

**Issue by NPJigaK** [ceolter/ag-grid#9009]
https://github.com/tailwindlabs/headlessui/pull/3494

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-12287**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
