### ISSUE TITLE
A scroll bar appears after a click on #agMenu

### ISSUE THREAD

**Issue by Matheo13** [ceolter/ag-grid#901]
After a click on an #agMenu (a filter icon)in order to display the filter, a scroll bar appears then disappears.
You can see it directly in the doc:
https://www.ag-grid.com/javascript-grid-filtering/index.php
(I didn't investigated yet)

Thank you verry much for your work.

**Comment by rafaelcorreiapoli** [comment]
Any updates on this? I'm also facing this issue

**Comment by ceolter** [comment]
popup is no placed before adding to dom. originally it was place after the grid (which showed popup) and the positioned where menu should appear (actually i set it to location 0,0 before adding, which prevents popup, as the position logic is after that)

**Comment by rafaelcorreiapoli** [comment]
@ceolter I'm still having this issue, i'm using
    "ag-grid": "^4.2.7",
    "ag-grid-react": "^4.2.0",

**Comment by ceolter** [comment]
fixed in v5.0
