### ISSUE TITLE
valueFormatter doesnt work propertly with custom value renderer during cell edit

### ISSUE THREAD

**Issue by VolTab** [ceolter/ag-grid#9010]
I'm submitting a ...
[x] bug report

Current behaviour.

When using custom value renderer for valueGetter which renders a value from one object and start addition of cell  [Object object] is  shown instead of rendered value. If move the focus away from cell without changing a value [Object object] stays in cell.  The valueFormattter doesnt work during  starting of  edition or moving away from the cell without changes.

Small example with incorrect behaviour is here: [https://codesandbox.io/p/sandbox/ag-grid-colvalue-render-issue-8q6tcv](https://codesandbox.io/p/sandbox/ag-grid-colvalue-render-issue-8q6tcv)

**Steps to reproduce**
* Loading of table
** correct value is shown in cell
* Double click on field"Auto"  to start edit the field value
**  [Object object] is shown
* Click somewhere outside of field "Auto"
** [Object object] remains

Ag Grid Version : 32.x.x

**Comment by AG-Zoheil** [comment]
Hi,

Thanks for getting in touch.

This is not a bug, please see cellDataTypes which should help you achieve your desired result: https://www.ag-grid.com/javascript-data-grid/cell-data-types/.

If you don't wish to use cellDataTypes and use custom rendering/editing logic you are in full control and will have to set the editor value formatting yourself.

Kind regards,
Zoheil

**Comment by VolTab** [comment]
Hi, thanks for clarification!

AG-Zoheil ***@***.***> schrieb am Di., 22. Okt. 2024, 14:37:
