### ISSUE TITLE
Cannot use both `alignedGrids` and `initialState` with React

### ISSUE THREAD

**Issue by nddery** [ceolter/ag-grid#9019]
**I'm submitting a bug report.**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
When using **React** (I've not tested with Angular and Vue), using [aligned grids](https://www.ag-grid.com/react-data-grid/aligned-grids/) along with [initial state](https://www.ag-grid.com/javascript-data-grid/grid-state/) leads to a `TypeError`:

> Cannot read properties of undefined (reading 'isVerticalScrollShowing')

See this here: [codesandbox](https://codesandbox.io/p/sandbox/aligned-grids-forked-w236qr?file=%2Fsrc%2Findex.tsx&workspaceId=e0a1b4a7-a38d-4e17-9f43-65b7f15b216a).

Setting `initialState` on a single grid "resolves" the bug, but the state is not applied to the other aligned grids.

Note that this seems to work fine when using vanilla JavaScript: https://codesandbox.io/p/sandbox/aligned-grids-forked-t6263j?file=%2Fmain.ts%3A66%2C5

**Expected behavior**

I would expect to be able to use the [aligned grids](https://www.ag-grid.com/react-data-grid/aligned-grids/) and [initial state](https://www.ag-grid.com/javascript-data-grid/grid-state/) features together without any errors being throw.

**Please tell us about your environment:**

* **AG Grid version:** 32.2.2

* **Browser:** Chrome 129.0.6668.90

> 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36'

* **Language:** React

**Comment by AG-Zoheil** [comment]
Hi @nddery,

Thank you for raising this on GitHub.

Please note that the React codesandbox you've provided does not work.

"Sandbox not found. It's likely that the Sandbox you're trying to access doesn't exist or you don't have the required permissions to access it."

Please double check the link and we can have a look.

Kind regards,
Zoheil

**Comment by nddery** [comment]
@AG-Zoheil sorry about that - I've just made both Codesandbox public so you should be able to access them now.

**Comment by AG-Zoheil** [comment]
Hello @nddery,

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-13218**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by nddery** [comment]
@AG-Zoheil as noted in the issue description, this does seem to work in the vanilla JavaScript version of AG Grid (see this [codesandbox](https://codesandbox.io/p/sandbox/aligned-grids-forked-t6263j?file=%2Fmain.ts%3A66%2C5)). For this reason, I believe it should be possible to achieve the same in the React version, and may point to a bug, specifically in the React implementation.

**Comment by AG-Zoheil** [comment]
Hi @nddery,

Thank you - that has been noted. As vanilla JS and React work differently this is not something that was originally planned to be supported in React. However a feature request has been raised as per above comment.

Thanks!
