### ISSUE TITLE
option to keep grid dimensions "fit" automatically

### ISSUE THREAD

**Issue by cfator** [ceolter/ag-grid#902]
Currently on window.resize and on visibility toggle (some grids being hidden at init time) I am calling sizeColumnsToFit().  Would be nice to have an option to have the grid keep itself "fit" automatically.

The challenge I might be running into with this is I must instantiate some grids while their containers are hidden and getting the available width isn't possible.

**Comment by buddyp450** [comment]
Seconded that this should be automatic with the option to toggle it off if doing something super custom. Getting a flicker effect in React from having to auto size.

**Comment by ceolter** [comment]
```while their containers are hidden```
=> this is the problem. if container is hidden, grid cannot find out it's width. so sizeColumnsToFit() fails
