### ISSUE TITLE
During first call to getRows for "infinite" rowModalType, sort model is empty

### ISSUE THREAD

**Issue by UndefinedLuka** [ceolter/ag-grid#9029]
**I'm submitting a ...** 
```
[x] bug report 
[] feature request 
[] support request 
```

**Current behavior**
If we set initialSort and initialSortIndex  for a column in the AgGrid with "infinite" row type model, these initial sort parameters are not passed to getRows function during first call (we get empty list in IGetRowsParams.sortModel). After that, sort modal gets updated (with the correct sort model values, that are specified in the initialSort and initialSortIndex) and calls getRows function once again. This causes two calls to the API where the first one is not relevant and should probably be avoided.   

**Expected behavior**
First call to the function getRows in the datasource should be made once the initial sort modal is set up, so we avoid calling the API twice.
 

**Please tell us about your environment:**

* **AG Grid version:** 31.1.1

* **Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0

* **Language:** TypeScript 4.3.5

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil
