### ISSUE TITLE
Conflict between editable cell and custom renderer

### ISSUE THREAD

**Issue by jlame** [ceolter/ag-grid#903]
Since 4.1.X i had a strange behaviour where i couldn't type anything in my custom cell renderer's input. 
I find out that was because i didn't set the editable flag = true on my column definition.
After doing so, when double clicking or pressing enter, f2, the agGrid default cell editor appears instead of my angular component's input (in fact it replaces all the ag-cell dom with the default editor).

By stopping the event propagation on doubleclick i managed to make it work, but can't do it on keypress (enter, f2). 
I know that i could have used the agGrid cell editor or create a new cell editor, but i wanted all of the behaviour to be located in my angular component ...

Is there any simple way to keep custom cell renderer's input editable without having the default editor interfer ? (like deactivate it somehow ?).
I can always go back to 4.0.5 but i need the viewportChanged event which is part of 4.1.X.

Thanks !

**Comment by ceolter** [comment]
```editable flag = true```
this is not needed. if you want to control the cell yourself, and not use the grids editing, then leave this as false.

if you want to pick up 'enter' or 'f2' events, add a listener to the eGridCell component that is passed to the cellRenderer.

**Comment by jlame** [comment]
Thanks for your reply !
My initial problem was that i couldn't type in the input which was returned from my cell renderer.
I made a jsFiddle to illustrate my issue : 

http://jsfiddle.net/8tbog06x/1/

On this example, editable is set to false. In that case, none of the input coming from my angular directive are editable (is it a normal behavior ?). 
When i set the flag to true, they become editable.

**Comment by Navdeep-Nurpuri** [comment]
Hi,

I've been facing a similar issue as OP. I am using ag-grid with anuglarJs, where for each cell I am using cellRenderer with a textbox in it. But I am only able to enter the values into the textbox after the editable flag in the columnsDef is set to true.

It would be great if you could look into this issue.

**Comment by jlame** [comment]
Hi @Navdeep-Nurpuri, if you set it on the columnsDef the default editor will be enable on click/enter/f2 and you won't have your own textbox anymore and will need to override the previous event i guess.

**Comment by Navdeep-Nurpuri** [comment]
@jlame I did just cross check and yes the click event does replace the textbox I had used in the cell renderer with the default editor. 

My use case is something like this  

https://jsfiddle.net/bn92dav4/

It would be great if you could help/guide me on how to the editing for this would be done.

**Comment by jlame** [comment]
In my opinion if the problem we're facing is an issue, the best way would be to fix have it fix. Cause having to enable editable on the columnsDef makes it more complicated to disable the default behaviour ...

@ceolter could you please confirm if the case represented in my jsffidle is an agGrid bug or not ? 
http://jsfiddle.net/8tbog06x/1/

Thanks !

**Comment by Navdeep-Nurpuri** [comment]
@jlame here is a workaround that I just did, not sure if this would be helpful for you but for now this is the best I could come up with.

https://jsfiddle.net/navdeepz/bn92dav4/1/

I added a keypress and blur event in the cellRenderer function.

**Comment by jlame** [comment]
@Navdeep-Nurpuri the problem with your work around is that the default action on an input are not possible (like ctrl + A).

**Comment by ceolter** [comment]
is this still a problem with v4.2.x? i change the handling of the editors slightly for another problem that this could be related to.

**Comment by Navdeep-Nurpuri** [comment]
Hi @ceolter 
The version I am currently working on is v4.1.4 (which had this issue), but will have to check for v4.2.x

**Comment by Navdeep-Nurpuri** [comment]
@ceolter 
I have just updated the jsfiddle with the new code and commented the key press and blur events and  I believe it works now. 

https://jsfiddle.net/bn92dav4/2/

But the issue with default action like (ctrl + A) still dont work.

**Comment by ceolter** [comment]
first issue fixed then.

second issue, ctrl+A, the grid behaves like excel, when you ctrl+A, it range selects the whole grid. this is an ag-Grid Enterprise feature (range selection is enterprise) so maybe you don't see if.

**Comment by jlame** [comment]
Ctrl + A when an input is focused should just select its content. But I think this behavior is different of range select.

Anyway I'll try with 4.2.x with column def editable false to type something in the input of my custom renderer and give you a feedback. Thanks a lot !

**Comment by Navdeep-Nurpuri** [comment]
Hi @ceolter,

Thanks alot for all this support and a wonderful tool, but unfortunately with the release of 5.0.0 the first issue has reopened. 

http://jsfiddle.net/8tbog06x/1/

Can you please look into this.

**Comment by jlame** [comment]
Thank you for notifying it  @Navdeep-Nurpuri, Too bad i was going to switch to version 5.X in order to get a fix which was in recent release.

**Comment by Navdeep-Nurpuri** [comment]
@jlame -- I've tried most of the versions (including 5.x) i personally feel 4.2.5 is the most stable one.

**Comment by ceolter** [comment]
@Navdeep-Nurpuri  fixed it again. sorry, someone asked or something else around this code, which broke it.

however, i do wonder, why not use the grid built in rendering? that would have better cell navigation support. there is also a property for enabling single click edit - so user doesn't have to double click. plus the clipboard will work for copying into / out of excel (last bit is enterprise feature only).

i plan to release tomorrow a small update on v5 to include this.

**Comment by jlame** [comment]
@ceolter because in my case (and surely in @Navdeep-Nurpuri  case too), i need to have very specific behaviour on the cell itself which are implemented in an angular component. So the built in renderer isn't enough for my usecase. 

Thanks for the fix ! Going to try it right now.
