### ISSUE TITLE
Integrating Angular forms and ag-Grid

### ISSUE THREAD

**Issue by amic81** [ceolter/ag-grid#9037]
**I'm submitting a support request**
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```

**Current behavior**
Is there any documentation or examples for integrating Angular forms and ag-Grid that is more recent than https://blog.ag-grid.com/using-angular-forms-with-ag-grid/?

**Expected behavior**
Latest documentation or examples for integrating Angular forms and ag-Grid

* **AG Grid version:** 32.2.2

* **Browser:**
Chrome 129.0.6668.101

* **Language:** [Angular]

**Comment by AG-Zoheil** [comment]
Hi @amic81,

Thanks for getting in touch.

At this point in time there aren't any more recent examples. If you do have an active AG Grid Enterprise licence I would encourage you to raise this via our [support portal](https://ag-grid.zendesk.com/hc/en-us) where more support regarding this can be provided.

That would be the most efficient way for you to get assistance with this.

Kind regards,
Zoheil
