### ISSUE TITLE
When soft refreshing the grid, the grid changes the focus of the browser

### ISSUE THREAD

**Issue by killyosaur** [ceolter/ag-grid#905]
This is a very odd and very particular issue. I have only seen this on IE 11. So I have an app that opens up windows from the grid. The new child windows then have the ability to update data and these updates need to be reflected on the grid. When I do a soft refresh of the grid, the parent page pops into focus, effectively hiding the child window. This is a bug that started with the 4.x version of the grid (did not happen before). I have attached an example of what I am talking about. Have not checked to see if this happens in Firefox, this only occurs when the child window opens in a new window.
[testapp.zip](https://github.com/ceolter/ag-grid/files/263854/testapp.zip)

**Comment by killyosaur** [comment]
As an fyi, this happens with a hard refresh as well.

**Comment by killyosaur** [comment]
I realized you've been busy dealing with other issues, wondering if you've looked at this and/or the pull request (https://github.com/ceolter/ag-grid/pull/906). I realize this may not be a major issue for other users (not sure if many are opening windows that cause data changes on the main grid) but it would be nice to know if I need to look at a more permanent solution (one external to the grid) such as overriding internal calls so I can avoid this issue and any possible future conflicts when upgrading). I'd like to move to a version of the grid with shift-click for multi selection of items, but not sure if I will need to replicate my changes every time I do this or if I should find a way to replicate the changes such that an upgrade won't simply strip my changes out of the code. Thanks for the amazing grid!

**Comment by killyosaur** [comment]
One last statement, My pull request allows the user to stop the cell focus from happening. A better way is to actually test in the code that the browser is in focus which your code currently does not do.
currently the code that gets the focused cell, "getFocusCellIfBrowserFocused" does not actually check if the browser is focused. This may work in chrome alright, but it does not work well in IE 11 where an explicit check that the browser is in focus should be done. Thanks!

**Comment by ceolter** [comment]
yes i am incredibly busy! haven't had a chance to go through github in over a week.

with regards the cellFocus, the grid checks if it has browser focus before forcing the focus again.

see the 'browserFocusedCell' check below. with this in place, the grid will not try and set the focus unless the grid already has browser focus. maybe are you on an earlier grid version that is missing this?

```
    public getFocusCellIfBrowserFocused(): GridCell {
        if (!this.focusedCell) {
            return null;
        }

        var browserFocusedCell = this.getGridCellForDomElement(document.activeElement);
        if (!browserFocusedCell) {
            return null;
        }

        var gridFocusId = this.focusedCell.createId();
        var browserFocusId = browserFocusedCell.createId();

        if (gridFocusId === browserFocusId) {
            return this.focusedCell;
        } else {
            return null;
        }
    }
```

**Comment by killyosaur** [comment]
I'll recheck, but I did attach an example that shows that the grid fails to take browser focus into consideration as of version 4.2.6. I have a pull request that (eventually :P ) added a line to the start of that class to check if the browser is even in focus before doing anything that fixes this issue. Thanks for looking into this and keep up the good work!

**Comment by killyosaur** [comment]
Also should mention that this issue is only a problem in IE 11 as far as I know. I have tested this in Chrome and Firefox and everything works as expected. The test app that is attached shows the issue.

**Comment by ceolter** [comment]
ah penny drops - it's another browser the popup is in - i assume you were using some sort of HTML popup inside the same browser.

i have just added suppressFocusAfterRefresh property, should do the trick.
