### ISSUE TITLE
Loading Spinner dipalys in filtered row in React AG Grid

### ISSUE THREAD

**Issue by hamidseta** [ceolter/ag-grid#9058]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[-] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

I have an AG Grid that is bound using a server-side datasource with infinite scrolling implemented. After fetching records from the server, I want to apply filters to some of the data and then display the filtered data in the grid. However, after binding the filtered data to AG Grid, a loading spinner still appears in some of the filtered rows.

https://plnkr.co/edit/b073YHguPH9UV0Rz

![image](https://github.com/user-attachments/assets/cad8a1c5-d15e-4e59-ac01-64cac2d8b72d)

How to resolve above issue when filtering data without displaying loading spinner ?

**Comment by tonioss22** [comment]
This is most likely a row id issue or the grid is not returning the proper data i would say, the grid is trying to rerender those rows because it does not know that they exist. If you verify the network tab, you should see requests going out to the server, make sure the data returned is what was requested in the body of the request and then make sure that row ids are not duplicate.

**Comment by tonioss22** [comment]
Sorry about my previous comment, i just verified your plunker, this is not how filtering works for server side, your server side request must respond with what was requested in the params. You can't remove some rows on the server side like this, if you would want to remove some rows on the server side, your request still needs to provide the number of rows it requested, in your example the front end sends a request for 50 rows but the backend only returns 45 rows, so the grid sends more requests to try to render the 5 missing rows.

**Comment by sushiltechnex** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by tonioss22** [comment]
> maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

This is like a virus, don't do what the captcha says^^

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
