### ISSUE TITLE
how to force the ag-grid to scroll to the selected row programmatically

### ISSUE THREAD

**Issue by amolpshinde07** [ceolter/ag-grid#907]
i am using below code to set Selected row programmatically but unable to scroll to that row.
`if (this.api.rowModel.allRows.length > rowNo) {
                var node = this.api.rowModel.allRows[rowNo];
                node.setSelected(true);
                this.api.setFocusedCell(rowNo, 'start', 'top');
            }`
Where start is one of column's id from Table.
Please help me out.

**Comment by ceolter** [comment]
check the documentation, there is an api you can call for showing a row.

**Comment by amolpshinde07** [comment]
i didn't find it in documentation. Can you please provide me actual link or short code?

**Comment by edwinyxc** [comment]
i have the same problem. Especially when using server side filtering, how can we find the right page and SCROLL to the specified row?

**Comment by amolpshinde07** [comment]
hi @edwinyxc did you find any solution?

**Comment by ceolter** [comment]
see the api at https://www.ag-grid.com/javascript-grid-api/index.php
ensureIndexVisible(index) - Ensures the index is visible, scrolling the table if needed.
ensureColumnVisible(colId) - Ensures the column is visible, scrolling the table if needed.
unless i'm mistaken, this is what you want?

**Comment by amolpshinde07** [comment]
Thank you So much @ceolter :)

**Comment by LuisPalacios** [comment]
Hi, ensureIndexVisible(index) works given the row is in memory. In my case I'm using infinite scroll, with i.e. paginationPageSize: 100. I'm seeing row 1000, click on it, a modal module shows, edit (update) the data and exits, on the grid I need to call setDatasource() which triggers API calls, retrieves udpated data and moves into row 0. If I call ensureIndexVisible(1000) it doesn't work (invalid row index for ensureIndexVisible: 1000). 

What would be the appropiate way of moving into "any" row?

Thanks,
Luis

**Comment by dharric** [comment]
In order to use ensureIndexVisible how does one get the index of the row

**Comment by ceolter** [comment]
rowIndex is an attribute of the row node.

**Comment by dereklin** [comment]
Can the row of the rowIndex be the first row of the viewport instead of the last?

**Comment by jfstephe** [comment]
From https://www.ag-grid.com/javascript-grid-api/:
ensureIndexVisible(index, position) | Ensures the row index is visible by vertically scrolling the grid. The valid values for positions are {'top', 'middle', 'bottom', undefined/null}. If top, middle or bottom, the grid will scroll the row to place the row at top, middle or bottom. If undefined or null then grid will do the minimum scrolling to show the row, ie if grid needs to scroll up then it will scroll so that the row is at the top, if the grid needs to scroll down then it will scroll so that the row is at the bottom, if the row is already in view then the grid will do nothing.
-- | --

...so I think so, yes.

**Comment by ManojR1066** [comment]
I have a Sidenav on the right that's covering the cells right behind it. **ensureColumnVisible(colId)** api forces the column to be visible but there is no attribute/option to position that column(like we have for row positioning ensureIndexVisible(index, position)).How can I force the column to be at the centre of the table?

**Comment by DominicTobias** [comment]
It doesn't work very well, even without position specified it jumps the item to the top

**Comment by DominicTobias** [comment]
I find that documentation pretty unclear as to weather you're supposed to pass an object or not, but either way it is unreliable and scrolls to whatever position it feels like, I've tried both `ensureNodeVisible(event.node, 'top');` and `ensureNodeVisible(event.node, { position: 'top' });`

**Comment by Huaoe** [comment]
for Redux users , I ended up with this solution

`useEffect(() => {
    if (!!gridApi) {
      gridApi.ensureIndexVisible(gridApi.getDisplayedRowCount() - 1, "bottom");
    }
  }, [rows]);`

**Comment by Dhruv1993** [comment]
> for Redux users , I ended up with this solution
> 
> `useEffect(() => { if (!!gridApi) { gridApi.ensureIndexVisible(gridApi.getDisplayedRowCount() - 1, "bottom"); } }, [rows]);`

Sorry, I am a bit late to the party. I am dealing with AG Grid in one of the projects and found that the previous developer stored the whole ag-grid api in the store (we have multiple grid views) which is against the redux rules of storing non-serializable entities. Did you store the grid api locally in the ag-grid component and only stores the row ids or something like that in the redux ?

**Comment by ustaalon** [comment]
> for Redux users , I ended up with this solution
> 
> `useEffect(() => { if (!!gridApi) { gridApi.ensureIndexVisible(gridApi.getDisplayedRowCount() - 1, "bottom"); } }, [rows]);`

I must say - it so not obvious that this code will be used for "scroll-to-bottom" or "scroll-to-top" (in my case). I looked everywhere in their API and I did not think about this logic for doing that. Well, thanks to your comment I just did 😊

Scroll-to-top:
`this.gridApi.ensureIndexVisible(0, 'top');`

**Comment by nika1974** [comment]
Sorry to awake such an old thread, but I got stuck... I use `this.gridApi.ensureColumnVisible(colId, 'start');` to scroll to the column, but I also have this feature > if the column is hidden I should unhide it first and then scroll to it. Once I do `this.gridOptions.columnApi.setColumnVisible(filter, true);` and then try to execute `ensureColumnVisible` function, it surely unhides the column, BUT it scrolls to the different position. Someone before me had the same issue, but admins didn't let the thread be... DUNNO WHY. Anyways thanks, have a good week!
