### ISSUE TITLE
setDatasource() should accept a second argument for arbitrary params to pass to getRows()

### ISSUE THREAD

**Issue by onlywei** [ceolter/ag-grid#908]
Right now, calling `.setDatasource(newDatasource)` will automatically execute the data source's `getRows()` function. It would help me very much if this method accepted a second argument, such that it can be used like this:

```
const ds = {
  getRows(params) {
    // params.foo is now accessible as 5
  }
};

gridOptions.api.setDatasource(ds, {foo: 5});
```

**Comment by drawyan** [comment]
I also would love to have this second param very much.

**Comment by ceolter** [comment]
isn't this unnecessary?

why not just provide the data to the datasource yourself before you pass the datasource to the grid?

```
function MyDatasource(foo) {
  this.foo = foo;
}

MyDatasource.prototype.getRows = function(params) {
  console.log(this.foo);
}
```

**Comment by drawyan** [comment]
This is what's currently being done as an alternative to pass the second param, but since the `foo` is not available when DataSource being constructed, and it's quite ugly to dynamically append some random event data to the dataSource instance. Providing it as the second param will make much cleaner code.

**Comment by ceolter** [comment]
i have added context to the datasource getRows params. so just items into the gridOptions.context object and you will be able to access now. this is in line with how other parts of the grid work.

**Comment by drawyan** [comment]
Great! Thank you @ceolter, will wait for the next release version.
