### ISSUE TITLE
[component pagination] Custom pagination panel template

### ISSUE THREAD

**Issue by EndarValuk** [ceolter/ag-grid#909]
For now its not possible to implement custom template for "footer panel" (control marked as id="south").
Would be nice to have such feature.
Usage, e.g. reload button, export button.
![untitled](https://cloud.githubusercontent.com/assets/4099836/15348750/a69d3e6a-1ce6-11e6-932c-3068202a2dec.png)

**Comment by rsauget** [comment]
+1

**Comment by anton-chernov** [comment]
+1

**Comment by sasivarnan** [comment]
+1

**Comment by agatsoh** [comment]
+1

**Comment by adrianMaersk** [comment]
+1

**Comment by chemicalbr** [comment]
+1

**Comment by deepakjan** [comment]
+1

**Comment by BoyceLyu** [comment]
+1

**Comment by donduni** [comment]
+1

**Comment by MehdiSaeedifar** [comment]
+1

**Comment by naveenballa** [comment]
+1

**Comment by seanlandsman** [comment]
tracked by AG-126
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by ceolter** [comment]
duplicate of https://github.com/ceolter/ag-grid/issues/530
closing

**Comment by iosifpetre18** [comment]
so is there a way to do a custom pagination?

**Comment by EliGitHub1** [comment]
There's actually a way to custom ag-grid pagination:

simply use( on the component js) styled component( I use react) as I show below:

const wrapper = styled.div`
.ag-paging-button {
border:none;
}
`;

**Comment by gokilagithub** [comment]
> There's actually a way to custom ag-grid pagination:
> 
> simply use( on the component js) styled component( I use react) as I show below:
> 
> const wrapper = styled.div`
> 
> .ag-paging-button {
> border:none;
> }
> 
> `;

Could you please tell me where to use this..How to achieve the custom pagination.

I have attached the screens.I want to bring the page size input box in the same row of pagination.how to achieve it ?pls help
![table](https://user-images.githubusercontent.com/56433118/66639614-cccdba80-ec34-11e9-98a0-24a9311cca7c.png)

**Comment by Guima21dv** [comment]
> I have attached the screens.I want to bring the page size input box in the same row of pagination.how to achieve it ?pls help

anyone know how i do this?
