### ISSUE TITLE
Sorting doesn't work when groups have no data

### ISSUE THREAD

**Issue by ceolter** [ceolter/ag-grid#91]
there seems to be a problem with the sorting functionality whenever a grid is grouped. The problem occurs because the grid is trying to sort the grouped rows, which don't have a data attribute associated with them (at least that I'm aware). Therefore, when the Utility class is used to get the value for the column an error is thrown because you are trying to get a property off of the data object, but it doesn't exist.

**Comment by ruratnayake** [comment]
I checked the grid functionality with the latest script but still not working :( .... its added to script ?

**Comment by ceolter** [comment]
yes i updated the script. i recreated and fixed the problem. so i'm surprised it's not working. i'll check it again when i get a chance (i'm in work now so can't)

**Comment by ruratnayake** [comment]
hi, were you able to check on it :) ?

**Comment by ceolter** [comment]
i have just tested now (on what i have checked out) and it is working.

to test, i commented out this in the 'test drive':
        groupAggFunction: groupAggFunction,
(ie so no aggregation)

then i grouped, and tried sorting, and it worked!!

i'm working of latest (unreleased master). are you working off of this? if not, i'll be doing another release probably tomorrow, you can try with that.

**Comment by ruratnayake** [comment]
thanks for the update, ill check this tomorrow and let you know :)

**Comment by ceolter** [comment]
no update, so closing.

**Comment by HariBabuThubati** [comment]
@ceolter : We are using ag-grid-enterprise 9.1.0 version and i used row group index and i am using valueGetter but when i am doing sorting i am getting an error "Cannot read property 'testname' of null".
how can i skip the header in sorting or how can i resolve the same.
