### ISSUE TITLE
How to get an account for enterprise support access

### ISSUE THREAD

**Issue by benjamincharity** [ceolter/ag-grid#9100]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

We recently purchased an enterprise license but we didn't get an account to log into Zendesk for support. How can I get Zendesk access for enterprise support?

**Comment by AG-Zoheil** [comment]
Hi @benjamincharity,

Please email info@ag-grid.com who will be able to help setting you up on ZenDesk.

Kind regards,
Zoheil
