### ISSUE TITLE
Release seems to contain source code

### ISSUE THREAD

**Issue by Alexander-Ruedi** [ceolter/ag-grid#9105]
https://github.com/ag-grid/ag-grid/releases/tag/v32.3.0

I didn't check in detail - but you might want to look into it

**Comment by seanlandsman** [comment]
hi - do you mean this at the bottom of the release?

![image](https://github.com/user-attachments/assets/130174c5-b62a-4a8e-bca8-877732e12c4c)

**Comment by Alexander-Ruedi** [comment]
exactly

**Comment by seanlandsman** [comment]
Thanks for letting us know but this is standard for a github release - it captures the open source code at the time the release is created.

Thanks

**Comment by Alexander-Ruedi** [comment]
Maybe I wasn't clear. The source code contains the enterprise modules. If that's on purpose, why is it hidden in github and npm?
