### ISSUE TITLE
Cell editor popup enhancement

### ISSUE THREAD

**Issue by dzonatan** [ceolter/ag-grid#911]
I'm missing three things related with cell editor:

1. "ag-popup-editor" class element would have exactly the same size (width & height) as the cell because I need to fill the cell with my component (input, dropdown or any other comp.).
2. Anchor popup editor to the cell that it would move together with the cell when viewport is scrolled.
3. API method to programmatically close the active cell editor. Currently it auto-closes if you only click somewhere in the grid context but it does **not** if you click outside grid - in the page. So if user after editing the cell (but still in active state) directly clicks the button somewhere in page I want to make sure that last changes were applied  (so before doing any further steps I would first call .api.stopCellEditing()).

**Comment by ceolter** [comment]
1. then don't use popup editor, that's for when you don't want it in the cell.
2. that's tricky to do. so not sure if i'll get to do it :( - basically if you put the popup as a child of the scroll-able part, it will get clipped to it's boundaries.
3. api.stopEditing() is now implemented. will be in next release.

**Comment by dmngu9** [comment]
Regarding to @dzonatan ag-popup-editor issue, I encountered the same problem when implement angular strap datepicker. Also, when I chose a date on the datepicker, the ag-popup-editor doesnt call destroy() until i clicked again outside of that cell. Is the fix implemented yet?

**Comment by aherlihy** [comment]
Hi @ceolter - I'm looking for a solution for your point # 2. I need my popup editor to take about 2-cells worth of space but I also need it anchored so that it doesn't move when scroll. Are you aware of any workarounds or if this is even possible?

Thank you!

**Comment by bkmorimoto** [comment]
We came up with a solution with callback hooked into the onBodyScroll event.
A few things to note:
* Using version 13.1.0
* All our custom cell editors (Angular 2) are pop ups EXCEPT DefaultCellEditor, which is why you see that logic in the isPopup piece
* Access the private rowRenderer off the api to get the cellComp. This may cause issues in the future if the ag-grid team decides to move things around
* This will stop editing if more than half of the editor scrolls off the screen (either horizontally or vertically)
* This is not anchoring, but rather trying to reposition the editor as you scroll
```javascript
(event) => {
	let cell = options.api.getFocusedCell();
	if (cell) {
		let rowIndex = cell.rowIndex;
		let colId = cell.column ? cell.column.getColId() : '';
		let isPopup = cell.column ?
			cell.column.getColDef() ?
				cell.column.getColDef().cellEditorFramework ?
					cell.column.getColDef().cellEditorFramework.name !== 'DefaultCellEditor' : false
				: false
			: false;
		if (rowIndex > -1 && colId && isPopup) {
			let cellComp = (<any>options.api).rowRenderer.rowCompsByIndex[rowIndex].cellComps[colId];
			let $grid = $(cellComp.eHtmlElement).closest('ag-grid-angular');
			let gridRect = $grid[0].getBoundingClientRect();
			let cellRect: ClientRect = cellComp.eHtmlElement.getBoundingClientRect();
			let cellHeightBuffer = cellRect.height / 2;
			let cellWidthBuffer = cellRect.width / 2;
			if (gridRect.bottom < (cellRect.top + cellHeightBuffer)
				|| gridRect.top > (cellRect.bottom - cellHeightBuffer)
				|| gridRect.left > (cellRect.right - cellWidthBuffer)
				|| gridRect.right < (cellRect.left + cellWidthBuffer)
			) {
				options.api.stopEditing()
			} else if (cellComp.cellEditor) {
				cellComp.beans.popupService.positionPopupOverComponent({
					column: cellComp.column,
					rowNode: cellComp.node,
					type: 'popupCellEditor',
					eventSource: cellComp.eHtmlElement,
					ePopup: cellComp.cellEditor.getGui(),
					keepWithinBounds: false
				});
			}
		}
	}
}
```
