### ISSUE TITLE
How to set default series when create integrated chart

### ISSUE THREAD

**Issue by mengyaow** [ceolter/ag-grid#9126]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
For integrated chart, is there a way to set default series? 
Currently it seems that it picks the very first colDef which has chartDataType: 'series', is it possible to assign one?
Alternatively, if I recreate a chart, is it possible to extract chart config, like type, selected category and series and apply these configuration when creating new integrated chart when I need to reload the data of table?

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

Integrated Charts is an enterprise feature. As we do not provide support on Github, I would encourage you to raise this via our [support portal](https://ag-grid.zendesk.com/hc/en-us) if you do have an active AG Grid Enterprise licence.

Kind regards,
Zoheil

**Comment by sushiltechnex** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
