### ISSUE TITLE
Pinning Columns Returns Incorrect Information To Screen Readers

### ISSUE THREAD

**Issue by jwentling78** [ceolter/ag-grid#9129]
**I'm submitting a ...** 
```
[x] bug report 
[] feature request 
[] support request
```

I want to note I considered this an issue with the screen readers, but it turns out others I've spoken to noticed this issue with multiple screen readers.
I also want to note that when I inspect the AG Grid cells in the browser, I see they have the correct row and column numbers, so I don't know why pinning any column causes the grid to return the wrong information.

**Providing a Reproducible Scenario**
- Go to [https://www.ag-grid.com/example/](https://www.ag-grid.com/example/)
- Open any Screen Reader (I've used JAWS and NVDA)
- Click a cell and note what the screen reader says its column and row are.
- Tab or Arrow into an adjacent cell and note its column and row specified by the screen reader. Repeat and note everything works.
- Now pin a column and click a cell in that column and note its column and row by the screen reader.
- Tab or Arrow into an adjacent cell and note its column and row specified by the screen reader. Repeat and note with the column or row numbers are out of order of what's expected..

**Current behavior**
When pinning any column and using a screen reader to listen to the cells' column and row numbers, the column and row numbers are returned incorrectly. If there are no pinned columns, the screen reader receives the correct numbers.

**Expected behavior**
Whether or not the column is pinned, the grid should return the correct column and row numbers.

**Please tell us about your environment:**

* **AG Grid version:** 32.2.0

* **Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36

* **Language:** TypeScript 5.3.3

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-3357**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
