### ISSUE TITLE
use wrapText and autoHeight in colDef,  pinnedBottomRowData multi rows do not position correct

### ISSUE THREAD

**Issue by GitHub-Ronald** [ceolter/ag-grid#9133]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- set column wrapText=true and autoHeight=true
- set multi rows pinnedBottomRowData

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
<img width="543" alt="image" src="https://github.com/user-attachments/assets/87748951-2fc8-4a3e-a4a8-8d1be90e1ddb">
<img width="555" alt="image" src="https://github.com/user-attachments/assets/db4441f8-7d45-4f27-9977-6f98113ea2e7">
<img width="324" alt="image" src="https://github.com/user-attachments/assets/953b6a20-56c8-4628-9ca7-1e1efe181645">

the two rows are overlap
**Expected behavior**
position bottom value should contain the auto height 

**Please tell us about your environment:**

* **AG Grid version:** 32.3.0

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36'
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
vue3

**Comment by AG-Zoheil** [comment]
Hi,

This seems to work as expected: https://plnkr.co/edit/nKATmq2NSN0FWvF2?open=main.js.

Please provide a working example by forking and saving the above plunker if you still see any issues and we'd be happy to look into it.

Thanks!

**Comment by GitHub-Ronald** [comment]
https://plnkr.co/edit/T5Gvdm6PDeiGgaTy?open=main.js. the pinned bottom row overlap&nbsp;


罗勇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月28日(星期一) 下午5:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ag-grid/ag-grid] use wrapText and autoHeight in colDef,  pinnedBottomRowData multi rows do not position correct (Issue #9133)





 
Hi,
 
This seems to work as expected: https://plnkr.co/edit/nKATmq2NSN0FWvF2?open=main.js.
 
Please provide a working example by forking and saving the above plunker if you still see any issues and we'd be happy to look into it.
 
Thanks!
 
&mdash;

**Comment by GitHub-Ronald** [comment]
> Hi,
> 
> This seems to work as expected: https://plnkr.co/edit/nKATmq2NSN0FWvF2?open=main.js.
> 
> Please provide a working example by forking and saving the above plunker if you still see any issues and we'd be happy to look into it.
> 
> Thanks!

https://plnkr.co/edit/T5Gvdm6PDeiGgaTy?open=main.js. the pinned bottom row overlap&nbsp;

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-4447**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
