### ISSUE TITLE
 How to call aggFuncs of columns manually from api ? 

### ISSUE THREAD

**Issue by SrikanthP0548** [ceolter/ag-grid#9134]
**I'm submitting a ...**  (check one with "x")
```
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

* **AG Grid version:** 31.2.0

Can someone help me on how to call aggFunc from the gridAPI ?

**Comment by nltheme** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
