### ISSUE TITLE
[SUGGESTION] GridOptions doc update

### ISSUE THREAD

**Issue by noherczeg** [ceolter/ag-grid#914]
Hey!

When we migrated from 3.3.3 to 4.x our grid did not initialize. They didn't call the REST endpoints.

Our solution and someone else's problem is mentioned here: https://www.ag-grid.com/forum/showthread.php?tid=3638

Maybe the docs should be extended with this info as well?

**Comment by seanlandsman** [comment]
We've updated the docs - they should be updated in the next release

Thanks!
