### ISSUE TITLE
ag grid dropdown style broken after upgrade

### ISSUE THREAD

**Issue by hikizume976** [ceolter/ag-grid#9141]
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```

I've updated ag-grid from 22.1.1 to 28.2.1, everything seems to be fine, except the dropdowns. The look and feel of the dropdowns is completely messed up now. I've attached a before and after screenshots.

I saw a post pointing to  https://www.ag-grid.com/javascript-grid-themes-v23-migration/, however this page is not there anymore.


before:
![aggrid_before](https://github.com/user-attachments/assets/a135af4e-3328-47c5-bef7-4db2f418f0eb)
![aggrid_after](https://github.com/user-attachments/assets/0b588965-e1d2-4fd3-b65a-c36874e7ce0f)

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by hikizume976** [comment]
Hi Zoheil,

thanks for your reply. 

I found a stackblitz where the dropdowns at the bottom grids expand upwards and all the content is visible. This one has version 18 installed. 

https://angular-ag-grid-button-renderer-dropdown-gpdjtk.stackblitz.io

Here's another stackblitz with Version23 installed. Notice how the dropdown doesn't expand upwards when it's at the bottom of the screen, and the data si wrapped like on an excel cell, as opposed to displaying all the data. Also, the cell needs to be clicked twice, which wasn't the case on v18.

https://stackblitz.com/edit/angular-ivy-ywautd?file=src%2Fapp%2Fapp.component.ts

Something happened on version 23 that broke this behaviour and the documentation does not seem to be there anymore (https://www.ag-grid.com/javascript-grid-themes-v23-migration/)

What would be required to migrate this grid with a dropdown from version 22 to version 28 without any styling issues?

thanks

**Comment by hikizume976** [comment]
![stackblitz after](https://github.com/user-attachments/assets/6ff604a5-e18e-4d64-8996-616654375475)
![stackblitz before](https://github.com/user-attachments/assets/ca5084a9-66fa-4b84-9250-8d2501a38821)

**Comment by AG-Zoheil** [comment]
Hi @hikizume976,

I can't get your v18 example to run.

However it looks as though in both of your screenshots the dropdown expands downwards?

Are you able to supply two like-for-like examples otherwise it becomes difficult to decipher what's going on from screenshots?

You can access an archived copy of the page you are referencing to here: https://web.archive.org/web/20200812002243/https://www.ag-grid.com/javascript-grid-themes-v23-migration/

Please also note this in regards to styling: https://www.ag-grid.com/archive/28.2.1/javascript-data-grid/global-style-upgrading-to-v28/.

This page may also be of use as it contains several dropdown editors from v28.2.1: https://www.ag-grid.com/archive/28.2.1/javascript-data-grid/provided-cell-editors/.

I hope this helps.

Kind regards,

**Comment by hikizume976** [comment]
Hi Zoheil,
Here's an updated version of the stackblitz using V18
https://stackblitz.com/edit/angular-ag-grid-button-renderer-dropdown-gpdjtk?file=src%2Fapp%2Fapp.component.ts

If you go to the bottom grid and you click on the first dropdown of the last row you will see:
*It opening upwards
*It shows the entire content of the dropdown options, despite of the column header width.
*You only need to click it once for it to display the information

![stackblitz before2](https://github.com/user-attachments/assets/8b4089fd-f46e-4ef3-94be-cfbed83922e5)

thanks

**Comment by hikizume976** [comment]
thanks for sharing the links.

The grid on this one behaves similarly as I would like it. On the last row of the select editor it expands upwards.

https://www.ag-grid.com/archive/28.2.1/javascript-data-grid/provided-cell-editors/#select-cell-editor

However, the source code is incomplete, for example, it's missing "editable: true," in the column definitions, otherwise the dropdown doesn't even open. 

If you could please point me in the right direction as to what else is missing from the source code from the example above
so that the dropdown shows all the data in it and it opens upwards as it's the last row on the grid, that'd be amazing

thanks

**Comment by AG-Zoheil** [comment]
Hi @hikizume976,

You can get the code directly off the example.
See in the image below. Underlined red shows you the code and underlined yellow opens it up in a plunker.

![image](https://github.com/user-attachments/assets/906940eb-4248-4cea-8ac8-92e550b730e9)

I hope this solves your issues!

Kind regards,
Zoheil

**Comment by hikizume976** [comment]
Hi @AG-Zoheil,
Almost there, but not quite, still.
The +V23 does not display the complete content of the select cell by default as the previous version did. 

before (ag grid V19 https://stackblitz.com/edit/angular-ag-grid-button-renderer-dropdown-zbbyan?file=package.json):
![stackblitz before3](https://github.com/user-attachments/assets/5fd93761-f45b-48c3-bcb2-d349e5bc6a1c)

after (ag grid V8 https://stackblitz.com/edit/finitelooper-ng16-dmbxnj?file=src%2Fapp%2Fapp.component.ts)
![stackblitz after3](https://github.com/user-attachments/assets/ee0564ec-e350-4da1-80c9-560fb52180be)

Is there any additional styling that needs to be applied to achieve this?

thanks

**Comment by AG-Zoheil** [comment]
Hi @hikizume976,

I'm afraid this is beyond the remit of support we can offer on GitHub. We'd advise to check styling information on our documentation or general queries regarding styling online.

Kind regards,
Zoheil
