### ISSUE TITLE
Blank space appears after merging rows, cell is a custom component

### ISSUE THREAD

**Issue by lijia-bb** [ceolter/ag-grid#9144]
![20241029-154016](https://github.com/user-attachments/assets/5571bae2-2bd6-43fa-a887-182b26338ee4)

**Comment by lijia-bb** [comment]
rowSpan: (params) => {
            // 根据某些条件返回行跨度
            if (params.node.rowIndex % 2 === 0) {
              return 2 // 合并两行
            }
            return 1
          }

**Comment by lijia-bb** [comment]
The test result shows that the height calculation is incorrect. The parent level has not set z-index: 1, so it cannot overwrite the second row of data. I don't know what's going on

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by lijia-bb** [comment]
https://plnkr.co/edit/6T7jBg82wZU0lszP?open=main.js

**Comment by AG-Zoheil** [comment]
Hi @lijia-bb,

The plunker you shared does not load and throws Vue errors, please review.

Thanks!

**Comment by lijia-bb** [comment]
![image](https://github.com/user-attachments/assets/0e185937-5477-4e82-aab7-880055608474)
![image](https://github.com/user-attachments/assets/c96fb923-7c5d-4ced-9ce8-f842eb9f44ce)
Has it been upgraded? Because of this, after the merger, other merged content was not overwritten

**Comment by lijia-bb** [comment]
ag-grid 32.2.2

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
