### ISSUE TITLE
Why does cellRender not support slot format

### ISSUE THREAD

**Issue by lijia-bb** [ceolter/ag-grid#9146]
Why does ”cellRender“ not support slot format, similar to #headerCell in antdv
![image](https://github.com/user-attachments/assets/03a97b98-1202-4ee7-af0d-3b31b7522654)

**Comment by AG-Zoheil** [comment]
Hi @lijia-bb,

Thanks for getting in touch via GitHub.

This approach is not supported as you've stated and we are currently not considering feature requests via GitHub.

We appreciate your time for raising this and hope you can continue to use the current functionality available in AG Grid Community.

Kind regards,
Zoheil

**Comment by vad1ym** [comment]
Hi, for everyone who is still looking for slot support, I created a simple wrapper - check out my repo:
https://github.com/vad1ym/ag-grid-vue3-slotted
