### ISSUE TITLE
I have used AgGrid and when i edit my grid that time i want this grid is in scoll and edit row comes to top.

### ISSUE THREAD

**Issue by sagar-more7396** [ceolter/ag-grid#9148]
my code - 

 <AgGrid
                id="grid_sales_medicine"
                ref={medicineGridRef}
                defaultColDef={defaultColDef}
                onGridReady={onGridReady}
                rowData={gridRowData} //productRowData}
                animateRows={false}
                frameworkComponents={{
                  cellTextEditor: CellTextEditor,
                  cellGridAutocomplete: CellGridAutocomplete,
                  cellNumberEditor: CellNumberEditor,
                }}
                onSelectionChanged={(params) => {
                  if (params.api.getSelectedNodes()[0]?.rowIndex) {
                    setCurrentProduct(params.api.getSelectedNodes()[0].data);
                  } else {
                    setCurrentProduct(null);
                  }
                  params.api.resetRowHeights();
                }}
                getRowClass={(params) => {
                  let returnClass = "";
                  if (params.data.error) returnClass += "ag-row-error ";
                  if (params.data.isH1 || params.data.isTB) {
                    returnClass += "dark-mode h1NRx-row ";
                  }
                  if (params.rowIndex === 0 && returnMode)
                    returnClass += "dark-mode return-mode ";
                  if (params.data.checked) {
                    returnClass += "checked ";
                  }
                  if (params.data.isReturn) {
                    returnClass += "dark-mode return ";
                  }
                  if (
                    params.data.batchExpiry &&
                    moment(params.data.batchExpiry).diff(moment(), "days") <
                      EXPIRY_ALERT_IN_DAYS
                  ) {
                    returnClass += "isNearExpiry";
                  }
                  return returnClass;
                }}
                onCellFocused={(params) => {
                  if (
                    showMedicineAutocomplete ||
                    autocompleteOpen ||
                    commonModalOpen
                  ) {
                    return;
                  } else {
                    // if (params.column.colDef.editable) {
                    //   cellClicked(params.api, params.rowIndex, params.column);
                    // } else {
                    //   cellClicked(
                    //     params.api,
                    //     params.rowIndex,
                    //     params.columnApi.getColumn("medicineNameDetailed") //any editable column or null if no editable columns
                    //   );
                    // }
                    focusField(
                      "grid_sales_medicine",
                      true,
                      params.rowIndex,
                      params.column?.colId
                    );
                  }
                }}
                onColumnMoved={(params) =>
                  updateColumnDefsHandler(params.api.getColumnDefs())
                }
                onColumnResized={(params) => {
                  updateColumnDefsHandler(params.api.getColumnDefs());
                }}
                onCellValueChanged={(params) => {
                  cellValueChanged(params.node, params.column);
                }}
              />

beacause in edit case my grid is sink some size and another component will be open that time this essue is occurs.

return (
    <>
      <div
        id="sale_medicine_container"
        className={`${classes["medicine-grid-parent"]} ${
          showBill ? classes["sales-bill-show"] : classes["sales-bill-hide"]
        }`}
      >
        <div
          className={`${showMedicineAutocomplete ? classes["minimized"] : ""} ${
            classes["medicine-grid-sales-bill-container"]
          }`}
        >
          <div className={`${classes["medicine-grid-container"]}`}>
            <div className={classes["medicine-grid"]}>
              <Drawer
                position="left"
                show={showColumns}
                width="220px"
                drawerStyles={{
                  borderRight: "1px solid black",
                  borderBottom: "1px solid black",
                  overflow: "hidden",
                }}
              >
                <ColumnFilters
                  columnDefs={api?.getColumnDefs()}
                  onChange={updateColumnDefsHandler}
                />
              </Drawer>
              <AgGrid
                id="grid_sales_medicine"
                ref={medicineGridRef}
                defaultColDef={defaultColDef}
                onGridReady={onGridReady}
                rowData={gridRowData} //productRowData}
                animateRows={false}
                frameworkComponents={{
                  cellTextEditor: CellTextEditor,
                  cellGridAutocomplete: CellGridAutocomplete,
                  cellNumberEditor: CellNumberEditor,
                }}
                onSelectionChanged={(params) => {
                  if (params.api.getSelectedNodes()[0]?.rowIndex) {
                    setCurrentProduct(params.api.getSelectedNodes()[0].data);
                  } else {
                    setCurrentProduct(null);
                  }
                  params.api.resetRowHeights();
                }}
                getRowClass={(params) => {
                  let returnClass = "";
                  if (params.data.error) returnClass += "ag-row-error ";
                  if (params.data.isH1 || params.data.isTB) {
                    returnClass += "dark-mode h1NRx-row ";
                  }
                  if (params.rowIndex === 0 && returnMode)
                    returnClass += "dark-mode return-mode ";
                  if (params.data.checked) {
                    returnClass += "checked ";
                  }
                  if (params.data.isReturn) {
                    returnClass += "dark-mode return ";
                  }
                  if (
                    params.data.batchExpiry &&
                    moment(params.data.batchExpiry).diff(moment(), "days") <
                      EXPIRY_ALERT_IN_DAYS
                  ) {
                    returnClass += "isNearExpiry";
                  }
                  return returnClass;
                }}
                onCellFocused={(params) => {
                  if (
                    showMedicineAutocomplete ||
                    autocompleteOpen ||
                    commonModalOpen
                  ) {
                    return;
                  } else {
                    // if (params.column.colDef.editable) {
                    //   cellClicked(params.api, params.rowIndex, params.column);
                    // } else {
                    //   cellClicked(
                    //     params.api,
                    //     params.rowIndex,
                    //     params.columnApi.getColumn("medicineNameDetailed") //any editable column or null if no editable columns
                    //   );
                    // }
                    focusField(
                      "grid_sales_medicine",
                      true,
                      params.rowIndex,
                      params.column?.colId
                    );
                  }
                }}
                onColumnMoved={(params) =>
                  updateColumnDefsHandler(params.api.getColumnDefs())
                }
                onColumnResized={(params) => {
                  updateColumnDefsHandler(params.api.getColumnDefs());
                }}
                onCellValueChanged={(params) => {
                  cellValueChanged(params.node, params.column);
                }}
              />
            </div>
            <div className={classes["medicine-grid-cta-container"]}>
              <div
                className={`${classes["column-cta"]} ${
                  showColumns && classes["visible"]
                } ${showColumns && classes["drawer-opened"]} `}
              >
                <Button
                  label="Columns"
                  startIcon={<Shortcut keys={["Alt", "O"]} />}
                  onClick={() => setShowColumns((prev) => !prev)}
                />
              </div>
              <div className={classes["row-level-ctas"]}>
                <div className={classes["row-level-cta"]}>
                  <Button
                    label="ADD"
                    ref={addProductRef}
                    onClick={addMedicine}
                    startIcon={<Shortcut keys={["+"]} />}
                    isAccessible={
                      isEditBill ? hasProductEditAccess.current.value : true
                    }
                  />
                  <div className={classes["cta-divider"]} />
                </div>
                <div className={classes["row-level-cta"]}>
                  <Button
                    label={`Delete${
                      productRowData.some((item) => !!item.checked)
                        ? " Selected"
                        : ""
                    }`}
                    startIcon={<Shortcut keys={["Del"]} />}
                    onClick={removeMedicine}
                    isAccessible={
                      isEditBill ? hasProductEditAccess.current.value : true
                    }
                  />
                  <div className={classes["cta-divider"]} />
                </div>
                <div className={classes["row-level-cta"]}>
                  <Button
                    label="Substitutes"
                    startIcon={<Shortcut keys={["Alt", "S"]} />}
                    ref={substituteRef}
                    onClick={() => {
                      let rowIndex = api.getSelectedNodes()[0]?.rowIndex;
                      if (!rowIndex) {
                        displayToast({
                          type: "warn",
                          title: "Please add a product to view Substitutes",
                        });
                        return;
                      }
                      setShowSubstituteAutocomplete(true);
                      setShowMedicineAutocomplete(true);
                    }}
                    isAccessible={
                      api?.getRowNode(api?.getSelectedNodes()[0]?.rowIndex)
                        ?.data?.isReturn
                        ? false
                        : isEditBill
                        ? hasProductEditAccess.current.value
                        : true
                    }
                  />
                  {ALLOW_RETURN_IN_SALES && (
                    <div className={classes["cta-divider"]} />
                  )}
                </div>
                {/* <div className={classes["row-level-cta"]}>
                  <Button
                    disabled
                    label="Promise Order"
                    startIcon={<Shortcut keys={["Ctrl", "O"]} />}
                    onClick={() => {
                      let rowIndex = api?.getSelectedNodes()[0]?.rowIndex;
                      if (rowIndex) {
                        api.getRowNode(rowIndex).data.isPromise =
                          !api.getRowNode(rowIndex).data.isPromise;
                        api.redrawRows({
                          rowNodes: [api.getRowNode(rowIndex)],
                        });
                        cellValueChanged(api.getRowNode(rowIndex));
                        focusCell(
                          api,
                          rowIndex,
                          columnApi.getColumn("medicineNameDetailed")
                        );
                      }
                    }}
                  />
                  <div className={classes["cta-divider"]} />
                </div> */}
                {ALLOW_RETURN_IN_SALES && (
                  <div className={classes["row-level-cta"]}>
                    <Button
                      label="Return"
                      ref={returnRef}
                      startIcon={<Shortcut keys={["Ctrl", "R"]} />}
                      onClick={() => {
                        let rowIndex = api?.getSelectedNodes()[0]?.rowIndex;
                        if (isZero(rowIndex)) {
                          setReturnMode((prev) => {
                            displayToast({
                              type: "info",
                              title: `Return Mode is ${!prev ? "ON" : "OFF"}`,
                            });
                            return !prev;
                          });
                          api.redrawRows({
                            rowNodes: [api.getRowNode(rowIndex)],
                          });
                          setTimeout(() => {
                            selectRow(api, rowIndex);
                            focusCell(
                              api,
                              rowIndex,
                              columnApi.getColumn("medicineNameDetailed")
                            );
                          }, 10);
                          return;
                        }
                        if (stopEditing(api)) {
                          if (!rowIndex) return;
                          api.getRowNode(rowIndex).data.isReturn =
                            !api.getRowNode(rowIndex)?.data?.isReturn;
                          api.redrawRows({
                            rowNodes: [api.getRowNode(rowIndex)],
                          });
                          cellValueChanged(
                            api.getRowNode(rowIndex),
                            columnApi.getColumn("quantity")
                          );
                        }
                        // todo @Abhi check with alston for focus issue

                        setTimeout(() => {
                          focusCell(
                            api,
                            rowIndex,
                            columnApi.getColumn("quantity")
                          );
                          api.ensureColumnVisible("custom_sr_no");
                        }, 300);
                      }}
                      isAccessible={hasProductEditAccess.current.value}
                    />
                  </div>
                )}
              </div>
              <div
                className={`${classes["show-details-cta"]} ${
                  showBill && classes["visible"]
                } ${showBill && classes["drawer-opened"]}`}
              >
                <Button
                  label={showBill ? "Less Details" : "More Details"}
                  onClick={() => setShowBill((prev) => !prev)}
                  startIcon={<Shortcut keys={["Alt", "F"]} />}
                />
              </div>
            </div>
          </div>
          <div className={classes["sales-bill-container"]}>
            <SalesBill />
          </div>
        </div>

        <div className={classes["medicine-grid-infobar-total-container"]}>
          <div className={classes["medicine-grid-infobar"]}>
            {checkedItemCount === 0 && (
              <div className={classes["infobar-left-container"]}>
                {currentProduct && currentProduct.medicineId && (
                  <div
                    className={`${classes["medicine-grid-infobar-inner-container"]} ${classes["productId"]}`}
                  >
                    <div className={classes["medicine-grid-infobar-inner-key"]}>
                      P. Id :
                    </div>
                    <div
                      className={classes["medicine-grid-infobar-inner-value"]}
                    >
                      {currentProduct.medicineId}
                    </div>
                  </div>
                )}
                {currentProduct && currentProduct.medicineBarcode && (
                  <div
                    className={`${classes["medicine-grid-infobar-inner-container"]} ${classes["barcode"]}`}
                  >
                    <div className={classes["medicine-grid-infobar-inner-key"]}>
                      EAN:
                    </div>
                    <div
                      className={classes["medicine-grid-infobar-inner-value"]}
                    >
                      {currentProduct.medicineBarcode}
                    </div>
                  </div>
                )}
                {currentProduct && currentProduct.rack && (
                  <div
                    className={`${classes["medicine-grid-infobar-inner-container"]} ${classes["rack"]}`}
                  >
                    <div className={classes["medicine-grid-infobar-inner-key"]}>
                      Rack 1 :
                    </div>
                    <div
                      className={classes["medicine-grid-infobar-inner-value"]}
                    >
                      {currentProduct.rack}
                    </div>
                  </div>
                )}
                {currentProduct && currentProduct.rack1 && (
                  <div
                    className={`${classes["medicine-grid-infobar-inner-container"]} ${classes["rack"]}`}
                  >
                    <div className={classes["medicine-grid-infobar-inner-key"]}>
                      Rack 2 :
                    </div>
                    <div
                      className={classes["medicine-grid-infobar-inner-value"]}
                    >
                      {currentProduct.rack1}
                    </div>
                  </div>
                )}
                {currentProduct && currentProduct.hsnCode && (
                  <div
                    className={`${classes["medicine-grid-infobar-inner-container"]} ${classes["hsn"]}`}
                  >
                    <div className={classes["medicine-grid-infobar-inner-key"]}>
                      HSN :
                    </div>
                    <div
                      className={classes["medicine-grid-infobar-inner-value"]}
                    >
                      {currentProduct.hsnCode}
                    </div>
                  </div>
                )}
                {currentProduct && currentProduct.manufacturerName && (
                  <div
                    className={`${classes["medicine-grid-infobar-inner-container"]} ${classes["mfg"]}`}
                  >
                    <div className={classes["medicine-grid-infobar-inner-key"]}>
                      MFG :
                    </div>
                    <div
                      className={classes["medicine-grid-infobar-inner-value"]}
                    >
                      {currentProduct.manufacturerName}
                    </div>
                  </div>
                )}
                {currentProduct && currentProduct.genericDosage && (
                  <div
                    className={`${classes["medicine-grid-infobar-inner-container"]} ${classes["composition"]}`}
                  >
                    <div className={classes["medicine-grid-infobar-inner-key"]}>
                      Composition :
                    </div>
                    <div
                      className={classes["medicine-grid-infobar-inner-value"]}
                    >
                      {currentProduct.genericDosage}
                    </div>
                  </div>
                )}
              </div>
            )}
            {checkedItemCount > 0 && (
              <div className={classes["infobar-checked-details"]}>
                <div
                  className={`${classes["medicine-grid-infobar-inner-container"]} ${classes["checked"]}`}
                >
                  <div className={classes["medicine-grid-infobar-inner-key"]}>
                    Selected Items/Qty :
                  </div>
                  <div className={classes["medicine-grid-infobar-inner-value"]}>
                    {checkedItemCount !== null &&
                      checkedItemQuantity !== null &&
                      ` ${checkedItemCount}/${checkedItemQuantity}`}
                  </div>
                </div>
                {checkedItemsTotal && (
                  <div
                    className={`${classes["medicine-grid-infobar-inner-container"]} ${classes["checked"]}`}
                  >
                    <div className={classes["medicine-grid-infobar-inner-key"]}>
                      Total :
                    </div>
                    <div
                      className={classes["medicine-grid-infobar-inner-value"]}
                    >
                      {checkedItemsTotal !== null &&
                        `${formatNumber(
                          parseFloat(checkedItemsTotal),
                          2,
                          true,
                          "INR"
                        )}`}
                    </div>
                  </div>
                )}
                {SHOW_MARGIN_ON_SALES && (
                  <div
                    className={`${classes["medicine-grid-infobar-inner-container"]} ${classes["checked"]}`}
                  >
                    <div className={classes["medicine-grid-infobar-inner-key"]}>
                      Margin(%) :
                    </div>
                    <div
                      className={classes["medicine-grid-infobar-inner-value"]}
                    >
                      {formatNumber(parseFloat(checkedItemsMargin), 2)}
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>
          <div className={classes["medicine-grid-total"]}>
            <div className={classes["medicine-grid-total-label"]}>Total</div>
            <div className={classes["medicine-grid-total-value"]}>
              {billTotal !== null &&
                `${formatNumber(billTotal, 2, true, "INR")}`}
            </div>
          </div>
        </div>
      </div>
      <Autocomplete
        show={showMedicineAutocomplete}
        closeAutoComplete={closeMedicineAc}
        height={"80%"}
      >
        {showMedicineAutocomplete && (
          <MedicineAutocomplete
            searchTerm={searchTerm}
            medicineGridRef={medicineGridRef}
            medicineSelected={(product) => {
              setShowSubstituteAutocomplete(false);
              productSelectedHandler({
                ...product,
                orderItemId: currentProduct?.orderItemId,
              });
            }}
            onEscape={closeMedicineAc}
            onSave={(data) => {
              saveBatchHandler(data);
            }}
            showSubstituteAutocomplete={showSubstituteAutocomplete}
            currentProduct={currentProduct}
          />
        )}
      </Autocomplete>
      <Autocomplete
        height="70%"
        width="75%"
        closeAutoComplete={() => {
          setShowAddBatchAutocomplete(false);
          if (api.getSelectedNodes()?.length > 0)
            setCurrentComponent("grid_sales_medicine");
        }}
        show={showAddBatchAutocomplete}
      >
        <AddBatch
          medicine={currentProduct}
          onSave={useCallback(
            (medicine, data) => {
              setCurrentComponent("grid_sales_medicine");
              setShowAddBatchAutocomplete(false);
              saveBatchHandler(medicine, data);
            },
            [saveBatchHandler, setCurrentComponent, setShowAddBatchAutocomplete]
          )}
          onEscape={() => {
            setShowAddBatchAutocomplete(false);
            if (api.getSelectedNodes()?.length > 0)
              setCurrentComponent("grid_sales_medicine");
          }}
        />
      </Autocomplete>
      <Autocomplete
        show={showPromiseOrderAutocomplete}
        closeAutoComplete={() => {
          setShowPromiseOrderAutocomplete(false);
        }}
        height="70%"
        width="50%"
      >
        <PromiseOrderAutocomplete
          onEscape={() => {
            setShowPromiseOrderAutocomplete(false);
          }}
          product={
            (api?.getSelectedNodes()[0]?.rowIndex !== 0 &&
              api?.getSelectedNodes()[0]?.data) ||
            null
          }
        />
      </Autocomplete>
      <Autocomplete
        show={barcodeAutocomplete}
        height="55%"
        width="100%"
        closeAutoComplete={() => {
          closeBarcodeAc();
        }}
      >
        <BarcodeSelectAutocomplete
          rowData={barcodeRowData}
          onSelection={async (productSelected) => {
            await selectedProductByBarcode(
              productSelected,
              api?.getRowNode(0),
              barcodeRowData
            );
            closeBarcodeAc();
          }}
          onClose={() => {
            closeBarcodeAc();
          }}
        />
      </Autocomplete>
    </>
  );

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Comment by sagar-more7396** [comment]
Thank you for your response and for closing the issue. Unfortunately, the
issue has not been resolved yet, and I am still encountering the problem.
Could you kindly provide further support or guidance on how to address this?

If more information is needed from my side to help resolve the issue,
please let me know.

I appreciate your time and assistance.

Kind regards,
Sagar More.

**Comment by AG-Zoheil** [comment]
Hi @sagar-more7396,

please note that we do not provide support via GitHub.

However if you believe a bug is present in AG Grid we'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil
