### ISSUE TITLE
agGrid filter only return one value

### ISSUE THREAD

**Issue by xopxop** [ceolter/ag-grid#9150]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

Filterring for the date which using filterValueGetter only show one value, it will work normally when there is valueFormatter function.
Version is not effecting 28.0.0, version affected most updated version

**Expected behavior**

It has to show more than one value

This is the code

import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { ColDef, SideBarDef } from 'ag-grid-community';
import { AgGridAngular } from 'ag-grid-angular';
import 'ag-grid-enterprise';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, AgGridAngular],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent {
  title = 'date-type';

  getRandomDate(): Date {
    const start = new Date(2000, 0, 1);
    const end = new Date();
    return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
  }

  rowData = [
    { make: "Tesla", date: this.getRandomDate() },
    { make: "Ford", date: this.getRandomDate() },
    { make: "Toyota", date: this.getRandomDate() },
  ];

  colDefs: ColDef[] = [
    {
      field: "make", 
      filterValueGetter: params => params.data.date.toString()
    },
    {
      field: "date",
      // valueFormatter: params => params.data.date.toDateString(),
      filterValueGetter: params => params.data.date.toString()
    }
  ];

  defaultColDef: ColDef = {
    filter: true,
    menuTabs: ['filterMenuTab', 'generalMenuTab', 'columnsMenuTab'],
  };
}

You see in the picture, there is only one value in the filter, especially if it is a Date object
<img width="547" alt="Screenshot 2024-10-29 at 20 28 05" src="https://github.com/user-attachments/assets/f5ead803-731e-4151-bc2c-c3a70eef7287">

* **AG Grid version:** 32.3.1

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
I am using aggrid in an Angular app

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
