### ISSUE TITLE
headerCheckboxSelection deprecation and new default value not listed in migration doc

### ISSUE THREAD

**Issue by skondrashov** [ceolter/ag-grid#9151]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Doesn't quite qualify as a bug, so not sure which to check.

**Current behavior**
After upgrading from a 30.x version to 32.3.0, the following warnings appear in the browser console:
```
AG Grid: As of v32.2, headerCheckboxSelection is deprecated. Use `rowSelection.headerCheckbox = true` in `GridOptions` instead.
AG Grid: As of v32.2, headerCheckboxSelectionFilteredOnly is deprecated. Use `rowSelection.selectAll = "filtered"` in `GridOptions` instead.
```

and, I assume related to that, every grid seems to default to having both header checkboxes and checkboxes on every row since `rowSelection.headerCheckbox` defaults to `true` but I believe `headerCheckboxSelection` defaulted to `false`, based on the fact that our grids did not have the checkboxes before.

I can open new issues but two other things:
1) The filter menu now shows up at the top of every column by default, this also doesn't seem to be in the migration docs for the previous 2 major versions.
2) Rows without checkboxes can no longer be selected by clicking on them without setting `enableClickSelection`, which was not the case before.

**Expected behavior**
This should be documented at https://www.ag-grid.com/javascript-data-grid/upgrading-to-ag-grid-32-2/ presumably, or whichever versions introduced these changes.

* **AG Grid version:** 32.3.0

**Comment by AG-Zoheil** [comment]
Hi @skondrashov,

Thank you for getting in touch via GitHub.

Both your observations regarding the migration guide for selection are valid and we are already planning to update this with our next release.

As for the column menu this was changed in v32 - see here: https://www.ag-grid.com/javascript-data-grid/upgrading-to-ag-grid-32/#column-menu

Kind regards,
Zoheil
