### ISSUE TITLE
I want to add a nested table like this to my react project, and they can be added, deleted and modified. Is there such a component?

### ISSUE THREAD

**Issue by changmen1** [ceolter/ag-grid#9152]
![table](https://github.com/user-attachments/assets/7ba64cf1-1da5-4324-b4d7-c273dccd8547)

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
