### ISSUE TITLE
 Excel export merged cells

### ISSUE THREAD

**Issue by DavidWuJay** [ceolter/ag-grid#9153]
I have purchased the commercial version and now I have a problem that cannot be solved. Can you help me? The row merging has been completed on my page, but the exported Excel is not merged. How can I achieve this? Is there a case review and corresponding solution? This problem affects our renewal of ag-grid.
![image](https://github.com/user-attachments/assets/6665bc33-8c09-4fae-97fb-3186f4786053)
![image](https://github.com/user-attachments/assets/61c1b04b-2ca0-4803-b2e0-aa9969ade2b4)

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As you've mentioned you are an enterprise client I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/hc/en-us) for issues or suggestions. That would be the quickest and most efficient route for you to get your question answered.

If you are unable to access your ZenDesk account please get in touch with our support team via info@ag-grid.com who can help with this.

Kind regards,
Zoheil

**Comment by gairon** [comment]
@DavidWuJay, have you found the solution?
