### ISSUE TITLE
AG-Grid: Header Menu Button Not Displaying in Parent Column Groups

### ISSUE THREAD

**Issue by trivip2000** [ceolter/ag-grid#9154]
I'm experiencing an issue with AG-Grid where the header menu button is not appearing in parent column groups (group headers), while it's visible in child columns.

Current Behavior:
  - Child columns show header menu buttons
  - Parent column groups (like 'Athlete') do not display header menu buttons

Expected Behavior:
 - Header menu buttons should be visible in both parent column groups and child columns

![image](https://github.com/user-attachments/assets/1f6d0de2-ecca-40c7-9016-ad515fd281a5)

**Comment by AG-Zoheil** [comment]
Hi @trivip2000,

It looks like you've raised this on ZenDesk with us as well (which is the right approach for our enterprise users) but please refrain from raising things on two channels as it causes confusion and duplicate work for us.

In light of this I'll be closing this issue now.

Thank you for understanding!

**Comment by Meghavardhan7498** [comment]
Hi @trivip2000 have you found a solution for this issue?
