### ISSUE TITLE
Avg Column Aggregation 

### ISSUE THREAD

**Issue by JonahJ** [ceolter/ag-grid#916]
Right now `aggFunc` can be sum, first, last, min, max. Could there be avg added?

If not maybe we could pass a callback which would compute custom to whatever we would like?

**Comment by ceolter** [comment]
latest release allows custom agg functions for the col. i also give an example of doing average (which gets tricky btw if you are grouping multiple levels, as the non-leaf levels have to be weighted averages as the child groups will have differing numbers of rows)
