### ISSUE TITLE
Is it possible to add blank space at the bottom of the last row and to the right of the last column?

### ISSUE THREAD

**Issue by adrian-amigues** [ceolter/ag-grid#9161]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

I'm trying to make it so that the user can scroll past the last row and last column in order to have more breathing room.
This is for the normal layout with a fixed set of rowData.

I haven't found any grid options to handle that so I tried tinkering with the styles: 
* I managed to add a bottom margin to `.ag-center-cols-viewport` to leave some space at the bottom, so it works well enough for now but seems a bit hacky
* I haven't yet found a similar way to be able to scroll past the last column. 

Has anyone managed to have that effect?

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Comment by adrian-amigues** [comment]
Really no one has had that need ? :/ 

I'll try to find a way, if I do I'll try to post my solution here

**Comment by adrian-amigues** [comment]
So I find a way, it's hacky. I tried a few things but this seemed to be the easiest and most reliable way, even though I may yet find issues with it coming in the future.

It consists in adding a "fake" column, added after all the other ones in the column definitions. 
Its parameters look like this, everything is done to prevent interactions with it and make it look like blank space:
```
export const SPACER_COLUMN_DEF: ColDef = {
  // Columns: Base options
  colId: SPACER_COLUMN_ID,
  cellDataType: false,
  suppressNavigable: true,
  suppressPaste: true,
  suppressFillHandle: true,
  contextMenuItems: [],
  cellAriaRole: 'none',
  // Columns: Width
  width: SPACER_COLUMN_WIDTH,
  minWidth: SPACER_COLUMN_WIDTH,
  maxWidth: SPACER_COLUMN_WIDTH,
  resizable: false,
  suppressSizeToFit: true,
  suppressAutoSize: true,
  // Columns: Display
  lockVisible: true,
  lockPosition: 'right',
  suppressMovable: true,
  // Columns: Editing
  editable: false,
  cellEditor: null,
  // Columns: Filter
  filter: false,
  suppressFiltersToolPanel: true,
  // Columns: Header
  headerClass: 'spacer-header',
  headerComponent: CustomColumnHeader,
  headerComponentParams: {
    isSpacer: true,
  },
  mainMenuItems: [],
  suppressHeaderMenuButton: true,
  suppressHeaderFilterButton: true,
  suppressHeaderContextMenu: true,
  suppressFloatingFilterButton: true,
  // Columns: Rendering and Styling
  cellStyle: {
    border: 'none',
    cursor: 'default',
  },
  // Columns: Sort
  sortable: false,
  // Columns: Spanning
  rowSpan: () => 9999999,
};
```

I have a custom header in place which made it easy to hide stuff, but in addition to that I also needed to change the css of its parent which still had a hover effect, so in my table css file I added: 
```
.spacer-header {
    &:hover {
      background-color: inherit;
    }
  }
```

Since I was already using some auto-sizing on my normal columns, I needed this fake one to not interfere with it. 
The solution I found was to add it to the colDefs after everything was rendered to the table and auto sized.

For that I plugged into the `onRowDataUpdated` (because I also needed that spacer column to stay through the table data updates), the method looks like this:
```
const handleRowDataUpdated = useCallback(({ api }: RowDataUpdatedEvent) => {
    // Add the spacer column after the table has updated if it is not already there
    setTimeout(() => {
      const colDefs = api.getColumnDefs();
      if (
        !colDefs ||
        colDefs.find((col) => 'colId' in col && col.colId === SPACER_COLUMN_ID)
      ) {
        return;
      }

      const colDefsWithSpacer = [...colDefs, SPACER_COLUMN_DEF];
      gridRef.current?.api.setGridOption('columnDefs', colDefsWithSpacer);
    }, 0);
  }, []);
```

Finally the last issue I had to solve was preventing cell selection in that column, which was still happening (unfortunately I didn't find a colDef property to prevent selection of cells in that column). 
So here is my `onCellSelectionChanged` callback:
```
export const handleCellSelectionChanged = ({
  api,
}: CellSelectionChangedEvent) => {
  const selectedCellRanges = api.getCellRanges();

  const containtsSpacerCells = selectedCellRanges?.some((range) =>
    range.columns.some((column) => column.getColId() === SPACER_COLUMN_ID),
  );

  if (containtsSpacerCells) {
    const filteredCellRanges = selectedCellRanges?.map((range) => ({
      ...range,
      columns: range.columns.filter(
        (column) => column.getColId() !== SPACER_COLUMN_ID,
      ),
    })) as CellRange[];

    api.clearCellSelection();
    filteredCellRanges?.forEach((range) => {
      api.addCellRange({
        ...range,
        rowStartIndex: range.startRow?.rowIndex ?? null,
        rowEndIndex: range.endRow?.rowIndex ?? null,
      });
    });
  }
};
```

It's very recent so I'm not yet sure of how robust this solution is. It is also tailored to my current needs and setup. But I hope it can be useful to someone if they end up with the same issue.

**Comment by adrian-amigues** [comment]
And for the space underneath the last row, for now the easy fix I am using is to plug into the css and add
```
.ag-center-cols-viewport {
    margin-bottom: 70vh;
  }
```
We don't have any infinite scroll or pagination yet, I guess it could become more complicated then, but it works well enough for now
