### ISSUE TITLE
Poor Performance for 200+ nodes: setNodesSelected()

### ISSUE THREAD

**Issue by bmbell** [ceolter/ag-grid#9162]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```

**Current behavior**
The gridApi.setNodesSelected() and IRowNode.setSelected() methods both introduce very poor performance issues when called on 200+ items.  The browser will freeze and be unresponsive for 10+ seconds.

**Expected behavior**
I would not expect performance issues, especially from the setNodesSelected() method, since it selects multiple nodes in bulk.

**Please tell us about your environment:**
Windows, NPM, Chrome Browser

* **AG Grid version:** 31.1.0

* **Browser:**
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36'

* **Language:**
TypeScript/Angular 18

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We've tried to reproduce your described behaviour but have been unable to do so: https://plnkr.co/edit/X1VDVrlDXAYXpiZj?open=main.js.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue. 

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

Please also note that we've made some major improvements to our selection model in the versions of `32` so I'd suggest upgrading first and checking if that solves your issues.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
