### ISSUE TITLE
Excel export how to merged cells ？？

### ISSUE THREAD

**Issue by extreme-cyj** [ceolter/ag-grid#9165]
Excel export how to merged cells ？？

**Comment by AG-Zoheil** [comment]
Hi @extreme-cyj,

Thanks for getting in touch with us. This functionality is only available in the enterprise version of our datagrid. On our documentation page you can identify enterprise features by the red _**e**_ sign next to them.

You can read about getting started with both community or enterprise versions of our grid on [this page](https://ag-grid.com/javascript-data-grid/getting-started/). Further information about AG Grid licences can be found [here](https://ag-grid.com/license-pricing/).

Do let us know if you have any other questions.

Kind regards,
Zoheil

**Comment by extreme-cyj** [comment]
This feature is not in the documentation

**Comment by gairon** [comment]
@extreme-cyj, have you found the solution?
