### ISSUE TITLE
Automatic columns starting from leftmost element instead of rightmost one

### ISSUE THREAD

**Issue by giacomo-galliano** [ceolter/ag-grid#9169]
**I'm submitting a ...**  
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

I'm referring to the behavior described here [Resizing Pinned Sections](https://www.ag-grid.com/angular-data-grid/column-pinning/#resizing-pinned-sections) 
When the size limit is reached, AgGrid starts unpinning elements form the leftmost element instead of starting from the rightmost one. 

**Providing a Reproducible Scenario**
It is possible to reproduce this scenario using the [demo](https://www.ag-grid.com/angular-data-grid/column-pinning/#example-pinning) on the AgGrid website.

**Current behaviour**
If I pin multiple columns and I reach a situation where, for example, following ones are pinned:

![image](https://github.com/user-attachments/assets/6f0c45ad-f5e1-4b33-9266-6aa6fd2beee3)

When i zoom-in, the `#` column will be automatically unpinned.

![image](https://github.com/user-attachments/assets/12960754-b00a-4468-8997-8546c036a07b)

**Expected behaviour**
Wouldn't be better if AgGrid started unpinning columns from the rightmost element?

Leaving these columns pinned

|#|Athlete|Country|Year|Date|
|---	|---	|---	|---	|---	|

Or even better, having the possibility to configure this behavior.

Thanks

* **AG Grid version:** 32.3.2

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-12249**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
