### ISSUE TITLE
BUG: SuppressSizeToFit does not work

### ISSUE THREAD

**Issue by k290** [ceolter/ag-grid#9178]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Forked the existing "AutoSize columns to fit cell contents". All I did is made the "athlete" column width much higher to make the issue more apparent:

https://plnkr.co/edit/E0wKyUlyZX5TcYPN?open=app.component.ts

**Current behavior**
Athlete column is sized to cell contents

**Expected behavior**
When using `autoSizeStrategy` and/or `gridApi.autoSizeColumns` and/or `gridApi.autoSizeAllColumns` the width should be set to the `width` and/or `initialWidth` when `suppressSizeToFit` is true on the column. The column should not be autosized.

From the docs here: https://www.ag-grid.com/angular-data-grid/column-sizing/#auto-size-columns-to-fit-grid

> If you don't want a particular column to be included in the auto-resize, then set the column definition suppressSizeToFit=true. This is helpful if, for example, you want the first column to remain fixed width, but all other columns to fill the width of the table.

**Please tell us about your environment:**
Windows 11

* **AG Grid version:** 32.3.2

* **Browser:**
Chrome  130.0.6723.92

* **Language:** Typescript latest, angular 17

**Comment by k290** [comment]
I am temporarily closing this issue as I can only reproduce this some of the time

**Comment by k290** [comment]
Reopening: The issue only occurs when the autosizestrategy is set to  "fitCellContents",

**Comment by hammad-awan** [comment]
Is this fixed? Because it still doesn't appear to be working.

**Comment by hammad-awan** [comment]
Is this fixed? This appears to still not work in the latest 33.0.0 version. Also, it appears that initial grid state is ignored, i.e., the latter should be applied after any auto resize of columns to content.
