### ISSUE TITLE
Ability to save col states

### ISSUE THREAD

**Issue by JonahJ** [ceolter/ag-grid#918]
When a user customizes their grid, with aggregations, sorting, filtering, etc - there is no single event to listen to. Would it be possible to add a `columnAnythingChanged` much like `columnEverythingChanged`.

Ideally we could then push this into LocalStorage or save into preferences, then reapply after refresh so the user always gets the same view.

Is it possible to add a `setAllColumns` type method, maybe I'm missing this in the documentation.

Thank you!

**Comment by mikeerickson** [comment]
+1

I have implemented this functionality myself, but it would be nice to have getConfigInfo() and setConfigInfo() out of the box.  Surely missing something with my custom implementation.

**Comment by ceolter** [comment]
regards the setAllColumns, what is the difference between this and columnApi.getState() and columnApi.setState()?

regards the events, this is to specific. someone else will want to listen to another group of events for another reason. i'm keeping with how standard dom event work - and there is no 'listen for this group of events' methods there. so keeping with best practice, you are going to have to listen for the events you need :(

you could trying using addGlobalListener - this will add an event listener to ALL events, providing you with the event and the event name. you can then filter on the event name.

**Comment by JonahJ** [comment]
@ceolter Thanks for advice. Unfortunately this does not appear to be working as intended.

I have a button which sets the grid to predefined states (groupings, aggregations, etc). I'm able to set it correctly via ```$scope.gridOptions.api.setColumnDefs(columns);```.

The ```$scope.gridOptions.columnApi.getColumnState();``` does not return the groupings. I can see an internal function ```getColumnDefs();``` and wondering if you could expose this?

Goal is for a user to set their grid to have their own aggregations and groupbys + pivots (which we cannot wait for!). Then save those states and quickly change views.

**Comment by ceolter** [comment]
when you say ```The $scope.gridOptions.columnApi.getColumnState(); does not return the groupings.```, if you are talking about the rowGroups (not column groups for the header) then it does, that is what the rowGorupIndex is. in v5 (beta we released last week) you can also see pivotIndex in there which is set if the column is a pivot column.

unless i am missing something, i think you can do what you are asking for?

**Comment by waheedahmed55** [comment]
I have ag-grid in which when user move a column let says from 3rd position to 1st position it stays there but upon refreshing the page it goes back to 3rd position. I want somehow it to retain the position. Can you tell me how can i do that?
