### ISSUE TITLE
SSRM initial page

### ISSUE THREAD

**Issue by EhsanKhalili** [ceolter/ag-grid#9181]
Hi,
Is there a way to set page number using server side row model?
with **paginationGoToPage** data will be loaded twice.

thanks

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
