### ISSUE TITLE
Auto width

### ISSUE THREAD

**Issue by terslada** [ceolter/ag-grid#9186]
Hello, 

I have a use case where I want to show the grid inside a modal and allow the grid to actually resize the modal. Id like to have it to fit the content of the cells and that should dictate how wide the whole grid should be (without scrollbar). It feels strange that I have to set some predefined size to the modal and then when the grid fits content, there might be a scrollbar/blank space for no reason. 

Thanks

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
