### ISSUE TITLE
target.__agBeanMetaData 'undefined' is not an object

### ISSUE THREAD

**Issue by noherczeg** [ceolter/ag-grid#920]
Hey!

I've upgraded our ag-grid version to 4.1.5 and since then, our karma tests don't run anymore.

We are injecting 'bower_components/ag-grid/dist/ag-grid.noStyle.js' which worked in version 3.3.3.

The error is:

```
TypeError: 'undefined' is not an object (evaluating 'target.__agBeanMetaData')
at http://localhost:9876/base/bower_components/ag-grid/dist/ag-grid.noStyle.js?a85c4693cb44744c8456bfc0352952bd2f98c0fd:1186
```

Which refers to: src/ts/context/context.ts:315

Is there a migration step which we forgot about or has anyone come across this?

Thanks in advance!

**Comment by ceolter** [comment]
i've not come across this before. we also don't use karma. __agBeanMetaData is something we use internally for annotations.

**Comment by noherczeg** [comment]
@ceolter Is something I can help you with investigating this issue? I'm puzzled that no one else came across this before :S

**Comment by ceolter** [comment]
you could see why the code is not executing in the way it should. what should happen:
1) we use TypeScript for creating the annotations. the annotations execute when the library loads and create the __agBeanMetaData on the objects on the classes. for example, the ```Bean``` function gets called as the ```@Bean``` annotation is used.
2) the __agBeanMetaData is then used by the grid when the classes are used.

so you could put a breakpoint into the Bean function, you can verify it is called before the error method when using the grid normally. then see why that path is not following in your test?

i think the test is not executing the script first and allowing initialisation of the annotations before using the classes defined.

**Comment by noherczeg** [comment]
I'll look into it again, when I'll need to take care of tests again. Thanks!

**Comment by ceolter** [comment]
no update, closing.
