### ISSUE TITLE
Printer Friendly Layout printing problem: clipped columns

### ISSUE THREAD

**Issue by a11y1** [ceolter/ag-grid#9200]
**I'm submitting a ...**  (check one with "x")
![Screenshot 2024-11-06 at 11 19 21 AM](https://github.com/user-attachments/assets/b1c450a5-d9c5-4743-992e-bb14bc431512)
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs: 
- Go to the plunker, below. Expand the preview to open in a new window. Click button "Printer Friendly Layout". The print preview shows 3 columns clipped (Price, Year, Country columns). 
- A plunker: https://plnkr.co/edit/JX5Jp5gzFv3Fs2rQ?open=main.ts&preview

Current behaviour: When printing, the right-most columns on the grid are clipped. 

Expected behaviour: When printing, either the grid is formatted to print on one page or multiple pages in such a way that all columns are included. 

**Current behavior**
- Go to the plunker in Chrome
- Print the grid in the current view (at the url), or you can also open the preview in a new window and attempt to print that view.

**Expected behavior**
- All columns should be formatted for printing, and not omitted from the printing version. 

**Please tell us about your environment:**
- Chrome browser Version 130.0.6723.59 (Official Build) extended (x86_64)
- MacOS Sonoma 14.7

* **AG Grid version:** X.X.X
    "ag-grid-community": "32.3.2"
    "ag-grid-enterprise": "32.3.2"
    "ag-grid-react": "32.3.2"

* **Browser:**
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36'

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-13419**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
