### ISSUE TITLE
When editing cell, keyboard navigation shall be disabled

### ISSUE THREAD

**Issue by xwb1989** [ceolter/ag-grid#921]
When editing a cell, keys like left and right arrow are not moving the cursor between characters within the cell, instead, it just move the focus to the neighbor cell. Shall keyboard(left,right,up,down arrows) navigation be disabled when editing a cell? Or is there a way to do so in current version?

**Comment by noherczeg** [comment]
You can override this behaviour in 

Example pulled from our source and stripped for brevity:
```
var row = this.gridOptions.api.rowModel.getRow(rowIndex);
var columnController = row.columnController;
var columns = columnController.getAllColumns();
for (var idxC = 0; idxC < columns.length-1; idxC++) {
    var column = columns[idxC];
    var nextColumn = findNextEditableColumn(columns, idxC, idxC);
    // Prevent "mutable variable is accessible from closure":
    (function (column, nextColumn, rowIndex, columnController) {
            var renderedCell = columnController.context.beans.rowRenderer.beanInstance.renderedRows[rowIndex].getRenderedCellForColumn(column);
            renderedCell.onNavigationKeyPressed = function (event, key) {
                // your stuff
            };
    })();
}
```

See: renderedCell.ts:436

**Comment by xwb1989** [comment]
Looks like this solution is a deep diving into the code! Thanks for sharing!

**Comment by noherczeg** [comment]
@xwb1989 We had to because row level editing is not supported. I would like to thank the person who disliked it for doing so without any reason. It is very constructive! Not.

P.S.: I stated that this isn't live code, it's a stripped out version which I showed only to help out solving the problem, and showing where to search for possible solutions.

**Comment by ceolter** [comment]
fixed in current version. left and right arrow keys now move cursor within the cell. i didn't change up and down arrow keys as i don't see the point in allowing this in a text field.

**Comment by GurjitDrish** [comment]
Do the following changes in ag grid js file


RenderedCell.prototype.onNavigationKeyPressed = function (event, key) {
if (!this.editingCell) {
//this.stopRowOrCellEdit();
this.rowRenderer.navigateToNextCell(key, this.rowIndex, this.column, this.node.floating);
event.preventDefault();
}
};

**Comment by prabhakerb** [comment]
@ceolter I don't see this working in latest ag-grid. do I need to use any grid options?

**Comment by eikishi01** [comment]
@ceolter @prabhakerb I'm in the editing [page of the wiki](https://www.ag-grid.com/javascript-grid-cell-editing/), and when using the quick editor it works, but when implementing a custom editor like the Numeric Editor the left/right arrows go back to cell navigation.

**Comment by ceolter** [comment]
this is the key: ```event.stopPropagation();```
you need to block the kev events from getting to the grid if you dont' want the default navigation.

**Comment by LucasSeveryn** [comment]
> fixed in current version. left and right arrow keys now move cursor within the cell. i didn't change up and down arrow keys as i don't see the point in allowing this in a text field.

Agree up and down arrow keys dont make sense - how do we achieve same behaviour as excel? That is, when cell is being edited, and down arrow key is pressed, editing is finished and the cell below is selected
