### ISSUE TITLE
Changing rowSelection causes all cells to be remounted

### ISSUE THREAD

**Issue by masterYi2333** [ceolter/ag-grid#9212]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
[https://codesandbox.io/p/sandbox/customising-checkbox-column-forked-8j6pvr?workspaceId=73c61546-ef54-4872-a879-ce4ae5f797ad](url)

**Current behavior**
![iShot_2024-11-09_10 25 47](https://github.com/user-attachments/assets/3969a06d-7580-4cd1-8944-2ccb3de9d39f)

Changing rowSelection causes all cells to be remounted

**Expected behavior**
Custom components for all cells should not be forcibly refreshed.

* **AG Grid version:** 32.3.2

**Comment by vardhan03** [comment]
Hi @masterYi2333, please try memoizing the 'rowSelection' value setting it as a constant.

**Comment by AG-Zoheil** [comment]
Hi,

Thank you for your comments. Yes, please memoize and/or alternatively upgrade to version 33.

Kind regards,
Zoheil
