### ISSUE TITLE
Will support for Vue 3 be enhanced

### ISSUE THREAD

**Issue by masterYi2333** [ceolter/ag-grid#9213]
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

We are in the process of selecting a table library. After using this library for less than a week, I’ve already encountered several Vue 3-related bugs (issues have been submitted). Additionally, I noticed that ag-grid-vue3 still relies on version 3.0, and support for the Composition API is lacking. I’d like to ask about the future support plan for Vue 3. Will there be dedicated time to work on Vue 3-related improvements? This is a key factor in my decision to use and potentially purchase this library.

**Comment by seanlandsman** [comment]
Hi - we're in the middle of re-writing the vue 3 side of things and are due to release it at the end of the month.

This will include better support across the board, including better Composition API support.

thanks

**Comment by lucaspmarra** [comment]
Support in general could be improved, there's not much on StackOverflow, there's no Discord, there's no help forum... nothing.
The documentation is difficult and complex to understand - a lot is not explained properly. When we need help - especially for Vue - there simply isn't any, the questions are all old or nobody can answer them.

It's simply terrible to work with Ag-grid in this way.
