### ISSUE TITLE
Input field doesn't work in the ROW

### ISSUE THREAD

**Issue by knonginda** [ceolter/ag-grid#923]
Hello! I added an input field to the rowData and I typed in any character, it doesn't work, seems something was blocked it. is it a bug?

For example:
var gridOptionsRowData = [
    { title: '<input type="text" /> }
];
var gridOptions = {
        ....
        rowData: gridOptionsRowData,
        ....
};

**Comment by ceolter** [comment]
yes, but it's fixed now. will be in next release, probably within 24hrs.
