### ISSUE TITLE
Column groups not working in v32.3.3

### ISSUE THREAD

**Issue by gespinha** [ceolter/ag-grid#9237]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
After configuring a grid with some columns and placing a column group, I don't see the option to collapse/expand the column group.

Working example: https://codesandbox.io/p/sandbox/78k37h

In this example column `tester` is a column group but doesn't display any collapse/expand controls.

**Expected behavior**
After configuring a column group I should see the collapse/expand option button in the column group header.

**Please tell us about your environment:**
Using `ag-grid-vue3` package (v32.3.3) on a VueJS app.

* **AG Grid version:** X.X.X
v32.3.3

* **Browser:**
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0`

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Javascript ES6

**Comment by cseickel** [comment]
@gespinha I'm struggling with this too. Can you tell me why you closed this issue? Did you figure out how to make it work?

**Comment by gespinha** [comment]
> @gespinha I'm struggling with this too. Can you tell me why you closed this issue? Did you figure out how to make it work?

I closed the ticket because I realized I was applying the `columnGroupShow` property incorrectly.

I my example above I have the `columnGroupShow` property set on the column group:
```

  {
    headerName: "Col Group",
    columnGroupShow: "open",
    children: [
      {
        field: "price"
      },
      {
        field: "electric"
      }
    ],
  },
```

But it should be set on each column individually, so that you're defining which columns should be expanded or collapsed. The column group visibility toggle will only show up if any columns in the group are set with this property.

This is the correct way to do it: [Example](https://codesandbox.io/p/sandbox/ag-grid-example-forked-swfhrf?workspaceId=ws_6cVBPY4dVunM2X8FFTe7Ya)

**Comment by cseickel** [comment]
Thanks for replying @gespinha. Unfortunately, that's not what my problem is. I'm still trying to figure out why it doesn't work.

**Comment by cseickel** [comment]
I finally figured it out. Maybe someone else will make this mistake:

**You have to have at least one column where `columnGroupShow` does not equal `"open"` or the feature will be disabled.** I guess the logic is that it must have something to collapse down to, and there is no UI for a closed column group that is not showing any columns.
