### ISSUE TITLE
cellRenderer component using typescript

### ISSUE THREAD

**Issue by jebravos** [ceolter/ag-grid#924]
Hi! 

Im working on a project using ag-grid and typescript. I am trying to use a cellRender component in one of my cells but I haven't been able to make it work, so, I wonder if you have an example of how to use a cellRenderer component defined in a typescript class.

thanks

**Comment by ceolter** [comment]
sorry, we don't. however typescript vs javascript shouldn't be an issue, you should be able to create it using the JavaScript examples we provide.
