### ISSUE TITLE
How to get sortModel when I click header cell?

### ISSUE THREAD

**Issue by hank7444** [ceolter/ag-grid#925]
Hi @ceolter 

I found I can get sortModel from callback of gridOption.datasource, or api.setDatasource 

but I need to set new Data from params.successCallback(),

I use React-Flux structure, I would like to update my rowData base on flux flow, not the successCallback()

====

I tried these event as follow but they return nothing:

sortChanged
beforeSortChanged
afterSortChanged

Have a good idea?

**Comment by ceolter** [comment]
i don't understand the question.

**Comment by hank7444** [comment]
@ceolter 

sorry I did't describe it clearly,

I mean, have any way to get sort status callback?

the scenario:
1. click header
2. get callback,  get name & type(asc || desc || null), and ag-grid does't sort automatically

maybe like this:

```
this.gridOptions = {
  sortCallback: (name, type) => {
      // do something here
  } 
}

...

 render() {
     return (
        <AgGrid className="ag-fresh" gridOptions={gridOptions} />
     );
 }
  
```

**Comment by ceolter** [comment]
"have any way to get sort status callback"
=> that's what sortChanged is for

btw i'm not a React developer, so maybe i just don't get what you are trying to do :( 

"and ag-grid does't sort automatically"
=> that's not possible if you are using the default inMemoryRowModel (the enterprise viewport row model allows this, but that's s different story)

maybe you just implement your own custom header? sounds like you don't want to use the grid sorting buy you want to keep the sort interaction and icons.

**Comment by hank7444** [comment]
yes, I want to control my data flow using react flux,
I have tried the exterprise viewport row model, but it needs to input new data from ajax to params.successCallback()

but I want to update rowData by react component prop "rowData"

it is useful for pagination from server & keep data source purely(always from flux store)

**Comment by hank7444** [comment]
@ceolter 
I tried rowModelType="viewport"

your document said:

```
Sorting
Only server side sorting is supported, if you want sorting you have to do it yourself on the server side. This is done by listening for the sortChanged event and then calling setRowData() with the new data when it arrives.
```

I tried receive sortChanged callback but I got nothing, has any good idea?

**Comment by ceolter** [comment]
after sort has changed, the api.getSortModle() returns the sort model. i'm using it in an app and working for me.

**Comment by hank7444** [comment]
OK, I will try soon
