### ISSUE TITLE
theme quartz patches related to sorting

### ISSUE THREAD

**Issue by ogim** [ceolter/ag-grid#9251]
I'm submitting a  bug report for issues with sorting using theme quartz. I have not checked other themes

I am using version 32.3.3

**Current behavior**
1) Sorting does not work when clicking the header

Here is the fix

`
.ag-header-cell::before,
.ag-header-group-cell:not(.ag-header-span-height.ag-header-group-cell-no-group)::before {
    z-index: 1;
    display: none;
}
`

2) Sorting icons seem to be switched., or I must be really mistaken but ascending is shown as arrow pointing upwards currently.

here is a fix
`
  .ag-icon-asc::before {
      mask-image: url('data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20class%3D%22ag-icon%20ag-icon-desc%22%20fill%3D%22none%22%20stroke-linecap%3D%22round%22%20stroke-linejoin%3D%22round%22%20stroke%3D%22black%22%20stroke-width%3D%221%22%20viewBox%3D%220%200%2024%2024%22%3E%3Cstyle%3E*%20%7B%20vector-effect%3A%20non-scaling-stroke%3B%20%7D%3C%2Fstyle%3E%3Cpath%20d%3D%22M12%205v14%22%2F%3E%3Cpath%20d%3D%22m19%2012-7%207-7-7%22%2F%3E%3C%2Fsvg%3E')!important;
  }
  .ag-icon-desc::before {
      mask-image: url('data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20class%3D%22ag-icon%20ag-icon-asc%22%20fill%3D%22none%22%20stroke-linecap%3D%22round%22%20stroke-linejoin%3D%22round%22%20stroke%3D%22black%22%20stroke-width%3D%221%22%20viewBox%3D%220%200%2024%2024%22%3E%3Cstyle%3E*%20%7B%20vector-effect%3A%20non-scaling-stroke%3B%20%7D%3C%2Fstyle%3E%3Cpath%20d%3D%22m5%2012%207-7%207%207%22%2F%3E%3Cpath%20d%3D%22M12%2019V5%22%2F%3E%3C%2Fsvg%3E')!important;
  }
  
`

* **AG Grid version:** 32.3.3
Here is my setup
{
       theme: themeQuartz.withPart(iconSetQuartzLight).withParams({}),
        loadThemeGoogleFonts: true,
        defaultColDef: {
          editable: false,
          filter: "agTextColumnFilter",
          sortable: true,
          resizable: true,
          unSortIcon: false,
          flex: 1,
          suppressHeaderFilterButton: false,
          suppressHeaderMenuButton: true,
          comparator: (a, b) => naturalSort.compare(a, b)
        },
        accentedSort: true,
        suppressMenuHide: false,
        suppressCellFocus: true,
        suppressScrollOnNewData:true,
        cacheQuickFilter:true,
        includeHiddenColumnsInQuickFilter:true,
}
`
No external ag-grid css is loaded

* **Language:** [ES6 js version ice lit / web-components]

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
