### ISSUE TITLE
Scroll issue in the data view

### ISSUE THREAD

**Issue by necessarius03** [ceolter/ag-grid#9266]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**

When I scroll down, a blank space appears. See below:
![ezgif-7-865c66f31c](https://github.com/user-attachments/assets/1150ffeb-1870-4d48-a385-d7ffe8d7488f)

**Expected behavior**

It must be adjacent to the title bar

**Please tell us about your environment:**

* **AG Grid version:** 31.2.1

* **Browser:** Chrome

* **Language:** Confirmed on React and TS

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
