### ISSUE TITLE
Status of AG-13076

### ISSUE THREAD

**Issue by melon2504** [ceolter/ag-grid#9267]
Is there any update on **AG-13076** raised in #8905 ?

Since this bug might have been a result of previously released version as per following comment, can we expect it to be released at least in next minor/patch version ?

![image](https://github.com/user-attachments/assets/d1aa3889-b822-44e7-8045-dc6f59bde827)

**Comment by AG-Zoheil** [comment]
Hi @melon2504,

Thank you for getting in touch. This bug will be fixed in our next minor version which will be 33.1.0.

Kind regards,
Zoheil
