### ISSUE TITLE
getNextTabbedCell ignores editable flag/callback

### ISSUE THREAD

**Issue by noherczeg** [ceolter/ag-grid#927]
When the code calls moveFocusToNextCell() in the row renderer it calls:
```
this.cellNavigationService.getNextTabbedCell(nextCell, shiftKey)
```

v4.1.5

This is not good because it after that calls getDisplayedColAfter() internally which ignores the editable flag/callback. The reason why this is bad is, that we can set that flag but it will ignore it therefore it will select the next cell no matter what.

**Comment by ceolter** [comment]
maybe i don't understand, but if i do understand, then i think it's working as expected.

in ```moveFocusToNextCell``` here is this check:
```
if (startEditing && !nextRenderedCell.isCellEditable()) {
    continue;
}
```

in other words, the editable flag is checked only if we are trying to edit the cell.

so if you are in edit more, tab will move between editable cells.

if not in edit mode, then tab will go to all cells, as all cells can be focused if not editing.

if i got it wrong, then kindly explain and reopen the issue.
