### ISSUE TITLE
Use of global built-in function type-of in scss is deprecated

### ISSUE THREAD

**Issue by jornaresk** [ceolter/ag-grid#9270]
Building scss with Angular 19 throws a warning on this line:

https://github.com/ag-grid/ag-grid/blob/72787b8601827e245ec8ab1454ec1c0bd6a48736/community-modules/styles/_index.scss#L399

I believe it is just a line that has skipped qc, as the rest of the file uses the updated meta.type-of mixin.

**Comment by BernieSumption** [comment]
Thanks for raising this with us, we've made a fix which will be available in the next release.
