### ISSUE TITLE
Full release notes

### ISSUE THREAD

**Issue by AmitMY** [ceolter/ag-grid#928]
Is there a full release notes for 4.2.X? Can't find it on ag-grid.com, and really interested to know which features were implemented in this version

**Comment by ceolter** [comment]
just finishing the release, had some problems!!! so had to redo the release a few times, but i think i'm all done now with github releases. updating the website now.

**Comment by abdulhaq-e** [comment]
Shouldn't this:
> 24th April 2016
Be:
> 25th May 2016

I was searching for the release notes and every time I look at the release box my mind dismisses it because of the date ^_^.

**Comment by AmitMY** [comment]
Thanks!
For whoever wondering - https://www.ag-grid.com/change-log/changeLogIndex.php
