### ISSUE TITLE
The problem of automatic sorting of int type

### ISSUE THREAD

**Issue by lzz-orz** [ceolter/ag-grid#9285]
![image](https://github.com/user-attachments/assets/62cad408-8ee6-4517-a7d8-40a5d0ba5bb1)
As shown in the figure, when I was sorting the ID column, I found that it was not sorted correctly by number size, but by the first character of the string? May I ask if this issue has been fixed in a future version.

* **AG Grid version:** 30.2.1

* **Browser:**

* **Language:** vue

**Comment by AG-Zoheil** [comment]
Hi @lzz-orz,

This works fine in our examples.

Please see https://www.ag-grid.com/javascript-data-grid/cell-data-types/ and https://www.ag-grid.com/javascript-data-grid/row-sorting/.

If you are still having issues, please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by lzz-orz** [comment]
I have identified and resolved the issue. My backend used database/SQL to query data, and the default data fields returned were all strings, resulting in abnormal sorting. Thank you.
