### ISSUE TITLE
Custom tree structured data does not support global search

### ISSUE THREAD

**Issue by Zhaohanqi12** [ceolter/ag-grid#9286]
PR  address

**Comment by Zhaohanqi12** [comment]
https://codesandbox.io/p/sandbox/zpq9gl

**Comment by Zhaohanqi12** [comment]
https://codesandbox.io/p/sandbox/tree-data-forked-wc33c4?file=%2Fsrc%2Findex.tsx%3A112%2C10

**Comment by AG-Zoheil** [comment]
Hi,

Currently the Quick filter does not support custom tree data structures out of the box.

We are currently not considering feature requests via GitHub, however we appreciate your time for raising this and hope you can continue to use the current functionality available in AG Grid Community.

Kind regards,
Zoheil
