### ISSUE TITLE
Example stopped working

### ISSUE THREAD

**Issue by AmitMY** [ceolter/ag-grid#929]
https://www.ag-grid.com/best-javascript-grid/index.php
html5grid.js:172 Uncaught ReferenceError: ag is not defined

**Comment by mikeerickson** [comment]
+1

**Comment by ceolter** [comment]
how did you get that link??!!! it's very old. this is the page you should be looking at:
https://www.ag-grid.com/best-javascript-data-grid/index.php

maybe you have the old page saved as a shortcut.

**Comment by AmitMY** [comment]
Yep
You should redirect from the old one to the new if possible

**Comment by ceolter** [comment]
yup i know, just extra work and i have other things higher priority to do!!

**Comment by gayathri-menath** [comment]
I got the same issue for the examples defined in ag-grid.
"ReferenceError: agGrid is not defined"
