### ISSUE TITLE
Ctrl+Left/Ctrl+right does not respect suppressNavigable column option

### ISSUE THREAD

**Issue by chwzr** [ceolter/ag-grid#9297]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
When the first or last column has `suppressNavigable: true` it selects these column when ctrl+left or ctrl+right is pressed.

**Expected behavior**
When the first or last column has `suppressNavigable: true` ctrl+left/right does not select these columns and instead selects the first/last column which is navigable.

**Please tell us about your environment:**
Forked Codesandbox of the Basic Example from getting-started  guide and added `suppressNavigable: true` to the first and last entry in colDef.
[CodeSandbox to Reproduce](https://codesandbox.io/p/sandbox/quick-start-example-forked-95jsn5)

* **AG Grid version:** 32.3.3

* **Browser:**
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36'
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15"

* **Language:** [all]

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

Currently there's no way to implement this behaviour with AG Grid. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-13764**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
