### ISSUE TITLE
GrandTotalRow Showing CheckBox with RowSelection

### ISSUE THREAD

**Issue by tsafadi** [ceolter/ag-grid#9308]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

**Current behavior**
- Use grid row `rowSelection`
- Use grid with `grandTotalRow`
- Grid shows a selection CheckBox in the `grandTotal` row

CodeSandBox: https://codesandbox.io/p/sandbox/2nkqrc
Copied from docs: https://www.ag-grid.com/react-data-grid/row-selection-single-row/

**Expected behavior**
- Use grid row `rowSelection`
- Use grid with `grandTotalRow`
- Grid should not show a selection CheckBox in the `grandTotal` row or at least provide an option to disable the behavior

**Please tell us about your environment:** Windows, Webstorm

* **AG Grid version:** 32.3.3

* **Browser:** 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'

* **Language:** TypeScript 5.6.3

**Comment by tsafadi** [comment]
Maybe a similar param like the `headerCheckbox` in the `rowSelection` property could be implented. Something like `totalCheckbox`. However, I do not really see a point of a total row showing a checkbox in the first place.

**Comment by AG-Zoheil** [comment]
Hi @tsafadi, 

Thanks for getting in touch via GitHub.

We are currently not considering feature requests via GitHub and we do not believe there is an underlying issue with this feature from a UX perspective. Some of our users prefer having the checkbox there to make selections e.g. for copying the row.

We appreciate your time for raising this and hope you can continue to use the current functionality available in AG Grid Community.

Kind regards,
Zoheil

**Comment by tsafadi** [comment]
Hello @AG-Zoheil,
I am an enterprise customer so where do I put this request.
I can in no way think of any reason why there should be a selection for the totals row. Doesn’t make any sense to me at all and I am pretty sure most users would agree on this.

**Comment by AG-Zoheil** [comment]
Hi @tsafadi,

I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/hc/en-us) for issues or suggestions. That would be the quickest and most efficient route for you to get your question answered.

If you haven't got an account please contact us via info@ag-grid.com.

Kind regards,
Zoheil

**Comment by tomisme** [comment]
Anyone else stuck on this your best bet is to use css: 

```
.ag-sticky-bottom-container .ag-selection-checkbox {
    display: none;
}
```

**Comment by sventore** [comment]
> Anyone else stuck on this your best bet is to use css:
> 
> ```
> .ag-sticky-bottom-container .ag-selection-checkbox {
>     display: none;
> }
> ```

Thanks for the tip, but for me I needed to change the class names:
```
/* Issue with AG grid showing checkbox on summary row */
.ag-row-footer .ag-selection-checkbox {
    display: none;
}
```
