### ISSUE TITLE
"Select All" Filter Bug on Numeric Columns

### ISSUE THREAD

**Issue by AzorianMatt** [ceolter/ag-grid#9326]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[] feature request
[] support request
```

**Current behavior**
I have not been able to find any open/closed issue history or other references on the web to an existing bug report for this.

This is a very weird behavior that I have yet to nail down a specific reproduction scenario in terms of potential causes or triggers. I have a number of scenarios where attempted use of the "Select All" filter on columns containing numeric values, results in emptying the grid when unchecking the filter, but then immediately re-applying it, thus undoing the filter instantaneously. This does not occur in any of the scenarios, when applying the filter to string based columns. The problem also seems to occur no matter if a value formatter is present on the column.

Unfortunately, I have found the problem to be present in a subset of scenarios with otherwise identical implementation where the only thing changing, is the data / columns. The two scenarios easiest for analysis, contain a simple data set where each row has a numeric `id` field, a string label / name field (using `broker` and `symbol` respectively), and a couple of string date/time fields (only present on one of the two data sets). The way the grid is implemented (including how data is loaded / fed as well as columns defined, is a duplicate between the two scenarios with only a couple of references changing to the underlying data source (which itself uses a shared implementation).

It does not seem to matter whether I have the use of value formatters in play, whether there are enough rows to create scrolling, or any other factor I have tried to isolate. For every scenario I have where the behavior is present, I have at least one scenario following the same implementation where it does not occur. Truly a very hard bug seemingly to nail down a trigger for.

**Expected behavior**
The expected behavior is for the "Select All" filter on numeric columns, to remain unchecked / applied when clicking on the otherwise checked instance of the input.

**Please tell us about your environment:**
JetBrains WebStorm IDE
Nginx HTTP Server
Deployed via custom Docker Compose / containers
Vite client base

**AG Grid version:** 32.3.3
`ag-grid-enterprise@32.3.3`
`as-grid-react@32.3.3`

**Browser:**
- Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
- There are others as well, but I don't have the ability to obtain those UA strings currently.

**Language:** ES6/7

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd recommend you upgrade to our latest released version as we've made some improvements to selection and this may have been resolved. 

If you do still have an issue please let us know and we'd be happy to look into this.

However as you can imagine if it is this difficult for you to pin this down as the reporter, it will be highly difficult for us. The most efficient way for us to investigate this would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AzorianMatt** [comment]
Hi Zoheil,

I will work on getting a live example going for you. In the mean time if it helps, I did the upgrade to which there is resolution on the bug as it relates to numeric values. However, it appears the bug still happens on date/time columns, which I'm discovering the previous version did as well. Hope this helps! :-D
