### ISSUE TITLE
Server-Side Row Model: "Select All" visual state persists across pages despite selectAll: 'currentPage' when header checkbox selection is made

### ISSUE THREAD

**Issue by srujana-kalluru** [ceolter/ag-grid#9327]
When using the Server-Side Row Model with pagination and `selectAll: 'currentPage'`, the visual selection state of rows incorrectly persists across pages. Even though the actual selection is correctly limited to the current page (code snippet below)

```
public onSelectionChanged(params: any) {
    const selectedRows = this.agGrid.api.getSelectedRows().map((row) => row.id);
    if (selectedRows.length == 0) {
      this.selectedRows = [];
      params.api.forEachNode(
        (node: { group: boolean; selected: boolean; id: number }) => {
          if (node.selected) {
            this.selectedRows.push(node.id);
          }
        },
      );
    } else {
      this.selectedRows = selectedRows;
    }
  }
```

This issue specifically affects the Server-Side Row Model. The Client-Side Row Model handles this case correctly with `selectAll: 'currentPage'`.

Reproduced below
https://plnkr.co/edit/FiJ36mRed1vH545i?open=main.ts

**Comment by matthieu-cryptio** [comment]
Can you fix it please ? I have the same issue

**Comment by AG-Zoheil** [comment]
Hi,

Please note the info box at the bottom of this section:
https://www.ag-grid.com/javascript-data-grid/server-side-model-selection/#selecting-all-rows

When using header checkbox selection with the server-side row model, you should not use the api functions getSelectedNodes() or getSelectedRows(). See the [API Reference](https://www.ag-grid.com/javascript-data-grid/server-side-model-selection/#api-reference) section below for suggested alternatives.

Kind regards,
Zoheil

**Comment by srujana-kalluru** [comment]
The issue remains the same even without using getSelectedNodes() or getSelectedRows(). When I click on the select all header, there is no way to select only the rows in the current page.
