### ISSUE TITLE
Minor bug introduced with processCallback

### ISSUE THREAD

**Issue by axmichail** [ceolter/ag-grid#933]
Hi, 

First, many thanks for this component. 

https://github.com/ceolter/ag-grid/commit/f325e4f1b2905186622a9d45fdc68b40687a7cc8 

In the above commit for the file src/ts/csvCreator.ts  line 77 - a regression bug was introduced due to the new functionality: the processCallback expects the params object to be always there, which is not consistent with the previous code lines nor compatible with previous usages of the function that did not pass an object when calling exportDataAsCsv, and it forces existing code to add a blank params entry as a work-around just to allow it to work rather than throwing an exception about the undefined object that does not have a processCallback parameter. 

browser_adapter.js:77 TypeError: Cannot read property 'processCellCallback' of undefined
    at CsvCreator.getDataAsCsv (csvCreator.js:64)
    at CsvCreator.exportDataAsCsv (csvCreator.js:26)
    at GridApi.exportDataAsCsv (gridApi.js:59)

Thought to let you know.

Thanks again
Mike

**Comment by ceolter** [comment]
fied. will be in next release. thanks.

**Comment by atmd83** [comment]
Hi, I am currently still seeing this issue in version 8.0.1
(Cannot read property 'processCellCallback' of undefined) when calling `getDataAsCsv()`
