### ISSUE TITLE
gridOptions.d.ts seems to be incorrectly using Tuple type as Array type

### ISSUE THREAD

**Issue by xwb1989** [ceolter/ag-grid#934]
Seems in multiple places this definition has been using Tuple type decl as Array type decl.

For example, line 193-195

    export interface GetContextMenuItems {
        (params: GetContextMenuItemsParams): [string | MenuItem];
    }
Based on the [documentation](https://www.ag-grid.com/javascript-grid-context-menu/index.php), the return type should be 

> a list with each item either a) a string or b) a MenuItem description

However, the type decl here:

    [string|MenuItem]

means "a tuple whose first element is of type either string or MenuItem", see [here](https://www.typescriptlang.org/docs/handbook/basic-types.html#tuple). 
The correct decl should be:

    (string|MenuItem)[]

**Comment by ceolter** [comment]
fixed it. thanks for pointing out. i'll try and get it right going forward. let me know if you find any others.
