### ISSUE TITLE
AgGrid blocking main thread

### ISSUE THREAD

**Issue by nikolastojanovictt** [ceolter/ag-grid#9349]
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

Issue tested with AgGrid React v32.3.3. React version 18.
No antivirus, no browser extensions, tested on two different computers

# Example 1
In your performance demo:
https://www.ag-grid.com/example/?theme=balham

Chrome browser:
1. open inspect
2. choose "Performance" tab
3. click record button in top left corner
4. in web page, change "Data size" combo box to any value
5. stop performance recording

Table rendering takes 470ms.

This example was chosen just for the convenience, real case scenario is rendering 6 tables from an array of table settings, on a single page. When you navigate to the page, each table takes about 300ms to render, blocking main thread which has UX impact.

# Example 2
Here is another example: https://plnkr.co/edit/92owMwLJbkRnlpKP?open=index.tsx
Plunker, 3 simple tables: 160-175ms
Same code with clean local build (Vite react-ts): 375ms

# Conclusion
It seems that new version of AgGrid combines all tasks related to a single table, thus creating a bigger blocking task, while older versions had smaller tasks which execute faster and async (below 50ms).
[v32_performance.jpg](https://drive.google.com/file/d/1VDgJ1drBIjOWZHmPuPDXbGtjGofx5FLH/view?usp=sharing)
[v25_performance.jpg](https://drive.google.com/file/d/1eiuJ392zGjzHRPTCR3hw8BbWXTRCu4F0/view?usp=sharing)

# Question
Are these expected values? Is there a way to render an array of AgGrid tables and not be affected by this?

**Current behavior**
Rendering of table blocks main thread for longer time than in old versions of Ag Grid (v25).

**Expected behavior**
Rendering of table behaves as in old versions of Ag Grid.

**Please tell us about your environment:** OS Win10, Ryzen 5 1600 16GB

* **AG Grid version:** 32.3.3

* **Browser:** Chrome Version 131.0.6778.109 (Official Build) (64-bit)

* **Language:** all

**Comment by nikolastojanovictt** [comment]
Do you have any feedback regarding this matter?

**Comment by p1pah** [comment]
I am also curious about this, lighthouse scores get affected dramatically from this..

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for the suggestion.

We agree this would be a valuable investigation into the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-13744**

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
