### ISSUE TITLE
How to change the plus, move and pinned icons?

### ISSUE THREAD

**Issue by hank7444** [ceolter/ag-grid#935]
as title

![image](https://cloud.githubusercontent.com/assets/4727090/15696455/fed2bc48-27e2-11e6-8b43-9ad17a5e4335.png)

**Comment by AmitMY** [comment]
In your grid options, add this code:
(This uses font awesome icons, you can use whatever you like)

Official page:
https://www.ag-grid.com/javascript-grid-icons/index.php

```
icons: {
    menu: '<i class="fa fa-bars"/>',
    columnVisible: '<i class="fa fa-eye"/>',
    columnHidden: '<i class="fa fa-eye-slash"/>',
    columnRemoveFromGroup: '<i class="fa fa-remove"/>',
    filter: '<i class="fa fa-filter"/>',
    sortAscending: '<i class="fa fa-sort-alpha-asc"/>',
    sortDescending: '<i class="fa fa-sort-alpha-desc"/>',
    groupExpanded: '<i class="fa fa-minus-square-o"/>',
    groupContracted: '<i class="fa fa-plus-square-o"/>',
    columnGroupOpened: '<i class="fa fa-minus-square-o"/>',
    columnGroupClosed: '<i class="fa fa-plus-square-o"/>'
},
```

**Comment by hank7444** [comment]
@AmitMY  
I know that, but it can't set move & pin icon

**Comment by AmitMY** [comment]
Oh, sorry, thought they existed....

After further check, there are more icons that are not changeable:
- Group icon (in the group row / menu)
- Tool panel shown (eye)
- Too panel hidden (minus)
- Menu settings (3 lines)
- Menu filter (funnel)
- Menu settings & Menu icon for 'tool panel' are different. one is 'check' and one is 'grid', also unchangeable

**Comment by ceolter** [comment]
i've just stuck this in. will be in the next release. new overrides will be:

```
    columnMovePin // when column is to the left, before it gets pinned
    columnMoveAdd // when adding a column
    columnMoveHide // when removing a column
    columnMoveMove // when moving a column
    columnMoveLeft // when moving and scrolling left
    columnMoveRight // when moving and scrolling right
    columnMoveGroup // when about to drop into group panel
```

**Comment by hank7444** [comment]
@ceolter  thx a lot!!, it will be very helpful for customization 👍
