### ISSUE TITLE
Pinned row no longer updates in v32.3.3 (when using getRowId)

### ISSUE THREAD

**Issue by JasonTheProgrammer** [ceolter/ag-grid#9358]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
[Plnkr using JS v32.3.3](https://plnkr.co/edit/9rktaMKKnbldh4RI?open=main.ts)
Click "Click Me" button at top, which should change the athlete name in the top pinned row to "banana", but it does not refresh the cell.

It only exhibits this behaviour if `getRowId` is specified in the grid options, remove that and clicking "Click Me" does update the cell to "banana".
Alternatively, a call to gridApi.refreshCells() immediately after the call to gridApi.setGridOption('pinnedTopRowData', ..) refreshes the cell to correctly show "banana".
So it looks like the data is being set as intended in the model, just not redrawn / refreshed in the DOM.

The symptom is identical to that reported in #8319 , but while that is reported as being fixed by AG-12193 in v32.1.0, the issue is definitely still present in v32.3.3 using TS / JS version. That original report linked Plnkr's using the React version. I discovered this issue while upgrading from v31.3.1 which did _not_ exhibit the issue.

**Expected behavior**
Refresh the cell to show "banana" while still specifying a callback for `getRowId`, and without having to manually call `refreshCells()`.

**Please tell us about your environment:**

* **AG Grid version:**
32.3.3

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0

* **Language:**
TypeScript

**Comment by PavloTrofymovES** [comment]
Hi!

Try to remove 'getRowId' function or change this function to provide really unique row ids.

Thank you,

**Comment by StephenCooper** [comment]
Here is an updated plunker that works.

https://plnkr.co/edit/URXMbLoIHiiUXEnq?open=main.ts

The key part is treating the rows as immutable, when updating via rowData as outlined in the docs.

https://ag-grid.com/javascript-data-grid/data-update-row-data/#how-it-works
