### ISSUE TITLE
Performance issue (4.1.X+)

### ISSUE THREAD

**Issue by AmitMY** [ceolter/ag-grid#937]
Tried on the latest version (4.2.X), and on 4.1.5.

This is weird, and I don't understand how that happens, but will explain what happened anyway:

If, using AngularJS onclick, I run "gridOptions.api.selectAll()", it works fine. Takes a second, but works.
If I have this header code, for a checkbox to select all (not realy relevant, but Ill add it the the end anyway).

If I click on the checkbox, it executes:
`params.api.selectAll();`

From 100MB of memory my program takes, it slowly going up to 500MB. Then, after 30-40 seconds of window freeze, it frees, and selects all. And the RAM goes back to a 100.

Why/How can such thing happen? it is the same function...

**EDIT:**
On worse computers, the page fully crashes.

```
function headerCellRendererFunc(params) {
    if (params.colDef.field != "checkbox")
        return params.colDef.headerName;

    var cb = document.createElement('input');
    cb.setAttribute('type', 'checkbox');

    var eHeader = document.createElement('label');
    var eTitle = document.createTextNode(params.colDef.headerName);
    eHeader.appendChild(cb);
    eHeader.appendChild(eTitle);

    cb.addEventListener('change', function (e) {
        if ($(this)[0].checked)
            params.api.selectAll();
        else
            params.api.deselectAll();

        $rootScope.$safeApply();
    });
    return eHeader;
}
```

**Comment by ceolter** [comment]
cannot reproduce.

i updated my main test page by inserting the following:
```
setTimeout( function() {
    for (var i = 0; i<10; i++) {
        var start = new Date().getTime();
        gridOptions.api.selectAll();
        console.log('selectAll took ' + (new Date().getTime() - start));

        start = new Date().getTime();
        gridOptions.api.deselectAll();
        console.log('deselectAll took ' + (new Date().getTime() - start));
    }
}, 10000);
```

when the page loaded, i quickly set the row count to 100k rows (hence the 10 second wait in the timeout about). then it select / deselect 10 times in a row. take about 200ms to do each selection / deselection. the browser doesn't suffer.

done on chrome, w10, very fast new laptop.

**Comment by AmitMY** [comment]
Yeah.. I said that calling the function works correctly, but for some reason calling it from the header "params" kills the browser.
Do you have any default testing plunker to create ag-grid examples/tests?
(If not, Ill create one and try to replicate the performance issues im facing)

**Comment by ceolter** [comment]
nope no default plunker.

but where you call the function from is nothing to do with the grid.

**Comment by AmitMY** [comment]
Sorry for your time, here is an explenation, for generations to come:
After failing to reproduce with a plunker, I used the timeline CPU record to see what is going on.
I have near the table a counter: {{gridOptions.api.getSelectedRows().length}}
When selecting a row, or the entire table, it does not update, and stays 0, thats OK, with angular I have to call the $digest to run.
I called it from the function onRowSelected, meaning that It ran for a thousand rows, something like 50,000 times (just the way the digest works..)
I fixed it using a safe way for each digest to wait if there are digest requests in queue.
After checking the entire table, it runs 1 digest and that fixes it.

You should know however, that for a table 1000 rows * 15 columns, with 'angularCompileRows' on, takes alot of time. you should (if not curently) consider to parse only cellRenderer cells, or valueGetter, not any of the fields. (Again, maybe you already do it and I am a spoon)
