### ISSUE TITLE
Aggregating footer?

### ISSUE THREAD

**Issue by AmitMY** [ceolter/ag-grid#940]
Is there a way to create a floating footer that will use the aggregation functions for the columns?

I know I can create a custom floating footer row, like [here ](https://www.ag-grid.com/angular-grid-floating/index.php) - but was interested to know if there is a thing made just for it, to use sums, averages, etc, and not to calculate myself for every table needing this.

**Comment by ceolter** [comment]
not possible, you will have to do the aggregations yourself. it's not an often asked for feature so low on my priority, especially given it's not necessary, just a nice to have given you can do the aggregations yourself.
