### ISSUE TITLE
Row group expanded flag doesn't update the data

### ISSUE THREAD

**Issue by mpetkov** [ceolter/ag-grid#941]
When we are using a tree-view to display the data, such as this example: https://ag-grid.com/example-file-browser/index.php, the rows expand/contract just fine.  However, since the expanded toggle is kept in the rowNode, instead of the actual row data, if the data is updated to have more rows it will lose its expanded state.  So the question is if the user passes the expanded state with the data to render the tree, why is the data expanded node not being updated?  So right now we pass the node one way and the state is updated in a different location.

The code can be seen in the groupCellRenderer the function is:

        public onExpandOrContract(): void {
        this.rowNode.expanded = !this.rowNode.expanded;
        var refreshIndex = this.getRefreshFromIndex();
        this.gridApi.onGroupExpandedOrCollapsed(refreshIndex);

        this.showExpandAndContractIcons();

        var event: any = {node: this.rowNode};
        this.eventService.dispatchEvent(Events.EVENT_ROW_GROUP_OPENED, event)
    }

The fix that I am proposing is to have an addition line that does this:
`this.rowNode.data.expanded = !this.rowNode.data.expanded;`

Or if there is another solution please let me know.

**Comment by ceolter** [comment]
the answer is that the grid will never update your data. this is by design.

you can, if you wish, update it yourself. you can add a listener for the event ```rowGroupOpened``` and do something like this:

```
api.addEventListener('rowGroupOpened', function(event) {
  var data = event.node.data;
  data.expanded = event.node.expanded;
});
```
