### ISSUE TITLE
rowDataChanged(rows)

### ISSUE THREAD

**Issue by adrianromanko** [ceolter/ag-grid#942]
rowDataChanged(rows) -- update rows that are visible
refreshRows(row) -- code practically does the same thing as rowDataChanged(rows)

How could I get acccess to the inMemoryRowModel and update a row that is not currently rendered? The use case is that the user will eventually scroll to the row's location and should be able see the updated row without the call to setRowData() and refresh the entire grid.

**Comment by arkon** [comment]
+1

I would assume that updating the in-memory row model would be reflected in the following ways:
- If the row isn't being rendered, nothing special happens. The updated data would show up the next time it's rendered.
- If the row is currently being rendered, refresh that row.

Would that not be better expected behaviour?

**Comment by adrianromanko** [comment]
Other desired behavior

- Add a single row to the in-memory model and make sure the viewport is updated if currently rendered, otherwise silently update all states.

Although one would need to also update all the states in arrays.

State 1: Row Data: Row data the application provides.
State 2: All Rows: Each data item the application provides wrapped in a rowNode object.
State 3: Rows after Group: After grouping applied to the rowNodes.
State 4: Rows after Filter: After filtering applied to the rowNodes.
State 5: Rows after Sort: After sort applied to the rowNodes.
State 6: Rows after Map: After mapping applied to the rowNodes.

**Comment by ceolter** [comment]
that's funny! i had no idea ```rowDataChanged(rows)``` and ```refreshRows(row)``` did almost the exact  same thing almost! i developed them at different times and for different reasons. one works with data, the other with rowNodes. arkon is right though, they are only needed if the rows are currently displayed and hence the GUI needs to refresh. you can update the data at any point, and next time it is displayed, the correct data will be used.

if you want to be 'correct', there are methods now on rowNode called ```setData``` and ```setDataValue```, the first replaces the data, the second updates a value on the data. each will then redraw the grid cells if required.

with regards adding / removing rows dynamically, that's a great idea and i want to do it. it's high on my list. but as you point out, with the internal structure, there is a lot to be considered. there is already an issue open to implement this so closing this issue.
