### ISSUE TITLE
Unexpected result in 4.2.X

### ISSUE THREAD

**Issue by AmitMY** [ceolter/ag-grid#944]
In 4.1.X `columnsApi.getAllColumns()` returned all of the columns, in order, even if hidden, excluding group columns.
Now, it returns all of the columns, without order.

Because I need order (I have a directive to save the table's state, for people's customization - columns, groups, sorting, etc) , I now use `getAllDisplayedColumns`. Obviously, this one does not return the hidden columns, and weirdly it does return the group columns, and not the grouped columns (If I group 'Country', it has a column called 'Group', and not a column called 'Country')

Is there a way to get all of the columns, in order?
Was it intended to change 'getAllColumns' this way?

Thanks!

**Comment by ceolter** [comment]
the method ```columnsApi.getAllColumns()``` didn't return in order of displayed, it returned in order of what you provided. so it hasn't changed between versions. i just checked the code of 4.1.5 and am pretty sure of this.

you can use ```getAllDisplayedColumns``` if you like.

**Comment by AmitMY** [comment]
Well, I just tested my code on both versions. in 4.1.X it does return the correct order.
I explained why getAllDisplayedColumns does not fit my needs, and I can't work with it.
If not intended to get it back to what it was, Ill create it specifically.
Please let me know what you decide
Thanks

**Comment by ceolter** [comment]
my mistake, ```columnsApi.getAllColumns()``` did get the order changed.

```Was it intended to change 'getAllColumns' this way?```
=> yes i intended to change it, this is a side effect. basically i've reworked the columns to pave the way for pivoting. with pivoting, there is an extra 'jump' as the pivot step can introduce columns.

```Is there a way to get all of the columns, in order?```
=> try ```api.getAllGridColumns()```, when you are not pivoting (which you are not, as this isn't exposed yet as I'm still working on it) then this should be what allColumns used to be.

**Comment by AmitMY** [comment]
Undefined method.. Also not documented in the website
`TypeError: self.grid.api.getAllGridColumns is not a function`

**Comment by ceolter** [comment]
you right, it's not exposed. i've just exposed it. in the mean time, you can use this undocumented way of doing it (ie change to the correct way when it's available)
```api.columnController.getAllGridColumns()```
