### ISSUE TITLE
Bug? Cannot use controller as syntax

### ISSUE THREAD

**Issue by AmitMY** [ceolter/ag-grid#945]
I have a grid, with `angularCompileRows: true`.

When having a cellRenderer: (for example)

```
function renderViewButton(params) {
    return '<span ng-click="open()"><i class="fa fa-eye"></i></span>';
}
```
And not using the `controller as` style, but using $scope, it triggers open.

When using the controller as style (As needed from 1.3.X I think), and doing `ng-click="vm.open()"` it does nothing. Even if you create a $scope, and add a function `open` to it, it will not trigger.

Am I missing an option in the doc, or is 'controller as' syntax not supported?

**Edit**
Apparently I did not use it right.
In the example ag-grid.com has for angular, they also do:
params.$scope.ageClicked = ageClicked;
to ensure it has the function, not just the general scope. smart.

**Comment by ceolter** [comment]
thanks for taking the time to close :)
