### ISSUE TITLE
AG Charts - update error TypeError: value is null

### ISSUE THREAD

**Issue by j-mcgregor** [ceolter/ag-grid#9451]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

Plunker

https://plnkr.co/edit/gHQ01raDQybPiB5D?open=index.tsx&preview

Steps to reproduce

1. Go to Plunker
2. Open console with errors selected
3. Set cell to empty
![image](https://github.com/user-attachments/assets/43d9f2d8-9d37-429a-99d4-2f2ceb814003)
4. Click and drag selection around empty cell and select bar chart
![image](https://github.com/user-attachments/assets/8d265a24-8c16-4529-8ac6-15f959dd43d2)
5. Edit the chart and select the 100% stacked bar chart option
![image](https://github.com/user-attachments/assets/d4137f7c-baa9-4ea7-b6bc-1d49cda5ad53)

6. You should see the following error in the console
<img width="1189" alt="image" src="https://github.com/user-attachments/assets/483917ab-3f29-40e4-b6c3-befcaae64df2">

I first picked this up in React Enterprise version, and discovered its a bug on the charts in your demos. In Plunker it doesn't crash the page. In React it does.

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

When applying a stacked bar chart, if a value is null then the page breaks

**Expected behavior**

Bar Chart should handle null values

**Please tell us about your environment:**

React

* **AG Grid version:** X.X.X

32.2.3

* **Browser:**

All, but Safari gives a slightly better error

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

Typescript latest

**Comment by AG-DavidG** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-13341 - [Charts] Regression: Chart does not render when `null` value in normalised stacked series

We try to fix bugs from one release to the next, and this will be included in version 11 which is due out tomorrow.

The best way to track this is to sign up for AG Charts new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/15387001154205-How-do-I-Sign-Up-For-AG-Charts-Release-Notifications). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://ag-grid.com/charts/changelog/).

Thanks again for bringing this up with us.

Kind regards,

David
