### ISSUE TITLE
Why can't we select entire groups now?

### ISSUE THREAD

**Issue by TFrascaroli** [ceolter/ag-grid#946]
Hey @ceolter, you just killed me :disappointed:
You just implemented this:
```javascript
    // we do not allow selecting groups by clicking (as the click here expands the group)
    // so return if it's a group row
    if (this.rowNode.group) {
        return;
    }
```
and I really don't get the reasoning behind it. So what if it's a group? `dblclick` expands it, yes, but why can't we select an entire group?
I really need this to be re-enabled, or at least allow us to enable it throw the grid's options.
My application needs to be able to select whole groups, and opening them and doing `click + shift + click` is **not** an option.

I'm removing those 3 lines for the time being from the source code, please tell me your thoughts about it and maybe your reasoning, so I can understand and try to come up with a solution.

Thanks, and keep up the good work!

**Comment by TFrascaroli** [comment]
An image is worth a thousand words they say.... maybe this illustrates better the **why** behind my request.

![image](https://cloud.githubusercontent.com/assets/9716061/15820261/9af165da-2be8-11e6-91a0-ff837ac861f9.png)

**Comment by ceolter** [comment]
this is not new:
```
    // we do not allow selecting groups by clicking (as the click here expands the group)
    // so return if it's a group row
    if (this.rowNode.group) {
        return;
    }
```

i can't remember exactly the scenario, however you can select groups when it's checkbox selection, you can see this on the main demo page.

i don't think this was working as you expected before

**Comment by TFrascaroli** [comment]
Well, it was.... I've been working like this for like 6 months :smile: 
Yes, I just saw the problem (I tried to open a group and selection went to trash). I've replaced those lines above with this:
```javascript
var targ;
if (event.target) targ = event.target;
else if (event.srcElement) targ = event.srcElement;
targ = targ instanceof HTMLSpanElement ? targ : targ.parentNode;
if (utils_1.Utils.containsClass(targ, 'ag-group-expanded') || utils_1.Utils.containsClass(targ, 'ag-group-contracted')) {
    return;
}
```
And no, checkbox selection = not cool (I can't make use of the `shift` and `ctrl` + `clicks` commands, which are already working like a charm).
I can understand if you don't want to change this, I'll just keep using the new lines I've come up with. Thanks for the really quick reply

**Comment by Shrulik** [comment]
I agree with @TFrascaroli, this would be a very nice feature.

**Comment by RobertDiPaolo** [comment]
I've just hit this issue! Our app uses click selection everywhere, so using checkbox selection for one grid that's using the server side Tree Model would look very odd. How about making this behaviour configurable, via the GridOptions, `enabledGroupClickSelection`? I'm happy to submit a pull request if it will be accepted, @ceolter ?

**Comment by Huiet** [comment]
@RobertDiPaolo Let me know what becomes of this if you can. We are have the same issue for ux on our application!
