### ISSUE TITLE
[FEAT] Custom header row

### ISSUE THREAD

**Issue by de-git** [ceolter/ag-grid#948]
I can see that columns can have children for grouping and they can have filters appearing in the menu.
I can also see other feature requests regarding header template (and a footer row).
What I would like to add as well is a custom header row (underneath the main header). So that I could add my own always present filters for example.

Assuming that this isn't currently possible, will that be implemented?

Thank you

**Comment by ceolter** [comment]
you can achieve this with floating rows
https://www.ag-grid.com/javascript-grid-floating/index.php

then create floatingCellRenderer to customise what gets rendered. you do not have to use the underlying floating row data, you can ignore this and render whatever you want.
