### ISSUE TITLE
[docs] vue 3 documentation doesn't mention module imports correctly

### ISSUE THREAD

**Issue by Narretz** [ceolter/ag-grid#9492]
https://www.ag-grid.com/vue-data-grid/getting-started and https://www.ag-grid.com/vue-data-grid/modules/ don't mention the module `@ag-grid-community/vue3` at all.

I was trying to update my usage from the normal imports to scoped imports, and got stuck here a bit because I couldn't find how to import the vue package without it requiring `ag-grid-community`

**Comment by AG-Zoheil** [comment]
Hi @Narretz ,

Thank you for getting in touch.

You can see this has been deprecated in our migration guide here: https://www.ag-grid.com/vue-data-grid/upgrading-to-ag-grid-33/#migrating-from-modules.

Also note https://www.ag-grid.com/vue-data-grid/getting-started/#your-first-vue-data-grid mentions ag-grid-vue3.

Kind regards,
Zoheil

**Comment by Narretz** [comment]
Ok, thanks, but that's still confusing.

Because I was on this page before telling me to use modules instead of packages to reduce the bundle size https://www.ag-grid.com/javascript-data-grid/modules/ I know it's not vue specifc, but shouldn't this be updated too to tell you that you should use the unscoped packages?

Plus, I cannot replicate the smaller bundle size I had with using scoped packages when I use the unscoped packages.

e: ok wow so v33 has just been released. I will test with that if the bundle size is smaller.
