### ISSUE TITLE
Help how to update all the grid data dynamically

### ISSUE THREAD

**Issue by BuddyWork** [ceolter/ag-grid#950]
I have a service that is publishing data to the Grid and would like to refresh all or specific rows, do you have an example that shows me how to do this?

Its a lovely grid by the way.

**Comment by ceolter** [comment]
options for refresh are available here
https://www.ag-grid.com/javascript-grid-refresh/index.php

**Comment by BuddyWork** [comment]
How do I reset the rowdata

**Comment by ceolter** [comment]
api.setRowData()

**Comment by BuddyWork** [comment]
Thanks

**Comment by ceolter** [comment]
welcome!

**Comment by GuruSBM** [comment]
Hi @ceolter Please help me on this!

how to update multiple cells.  i can update only the selected row at a time in grid.  Please assist.
