### ISSUE TITLE
TypeScript: Theme type conflict between @ag-grid-community/theming and ag-grid-react

### ISSUE THREAD

**Issue by joshling1919** [ceolter/ag-grid#9506]
- [x] bug report 
- [ ] feature request
- [ ] support request

**Current behavior**
When using a custom theme with AG Grid React and TypeScript, there's a type conflict between the Theme types from different AG Grid packages. Specifically, when trying to pass a theme created with `themeQuartz.withParams()` to the AgGridReact component's `theme` prop, TypeScript gives the following error:

```typescript
Type 'Theme' is not assignable to type 'Theme | "legacy" | undefined'.
Property 'withoutPart' is missing in type 'Theme' but required in type 'Theme'.
```

**Expected behavior**
The Theme type from @ag-grid-community/theming should be compatible with the theme prop type expected by AgGridReact, allowing us to pass custom themes created with `themeQuartz.withParams()` without type errors.

**Please tell us about your environment:**
* **AG Grid version:** 
  - ag-grid-react: 33.0.1
  - @ag-grid-community/theming: 32.3.3
* **Language:** TypeScript 5.7.2

Steps to reproduce:
1. Create a custom theme using themeQuartz:
```typescript
import { themeQuartz } from "@ag-grid-community/theming";
import { AgGridReact } from "ag-grid-react";

const myTheme = themeQuartz.withParams({
  accentColor: "#0E74A1",
  // other theme params...
});

// This causes the type error:
<AgGridReact theme={myTheme} />
```

**Comment by StephenCooper** [comment]
Following the upgrade to v33 the `@ag-grid-community/theming` is now included inside of `ag-grid-community` which is a dependent of `ag-grid-react`.

Then your updated code can be as follows.

```
import { themeQuartz } from "ag-grid-community";
import { AgGridReact } from "ag-grid-react";

const myTheme = themeQuartz.withParams({
  accentColor: "#0E74A1",
  // other theme params...
});

// This causes the type error:
<AgGridReact theme={myTheme} />
```

You  may want to use the v33 code Mod tool, as this will have automatically updated your import paths for you. 

Specific part from the migration guide about the modules changes. 

https://ag-grid.com/javascript-data-grid/upgrading-to-ag-grid-33/#migrating-from-modules
