### ISSUE TITLE
Refresh rowdata

### ISSUE THREAD

**Issue by BuddyWork** [ceolter/ag-grid#951]
How do I refresh the rowdata

**Comment by ceolter** [comment]
stop creating duplicate issues!!!!! :)

**Comment by BuddyWork** [comment]
Sorry but that did not resolve what I was looking for, let me explain, I have signalr service that is receiving updates so I need to send the updates to the grid and sometimes may need to load the grid again with a new rows which means I want to throw existing and add new.

Sorry again but you closed the other issue before I could reply.

**Comment by ceolter** [comment]
the grid doesn't support adding or removing rows (yet), just updating individual rows.

if you want to update an individual row's details, use one of the refresh options you can read about on the refresh page.

if you want to reset all the rows, thats where you use api.setRowData()

**Comment by BuddyWork** [comment]
Thanks

**Comment by ceolter** [comment]
:)
