### ISSUE TITLE
Breaking changes in 33

### ISSUE THREAD

**Issue by eugeniobet** [ceolter/ag-grid#9510]
https://www.ag-grid.com/react-data-grid/upgrading-to-ag-grid-33/

Seriously?

**Comment by Narretz** [comment]
What's your point? That there are too many breaking changes?

**Comment by eugeniobet** [comment]
I've been through this:
https://github.com/ag-grid/ag-grid/issues/8283

and this:
https://github.com/ag-grid/ag-grid/issues/8957

in a very short span of time.
The former breaking ALL our grids while the latter breaking every excel export (we have skipRowGrous defaulting to true which is integral to how we operate the grid, this one I had to patch it myself) no matter what (not exactly two uncommon features to say the least).

Being this a paid grid (at least for us it is), how can I possibly trust this not to break anything else (and I'm not talking about some random color somewhere deep down).
How can I go and iterate every single breaking change? Should I trust the codemod? How can I possibly trust the codemod given the premises?

**Comment by AG-Zoheil** [comment]
Hi @eugeniobet,

Thank you for your feedback.

As you've mentioned you are an enterprise client I would encourage you to contact us via our dedicated [support portal](https://ag-grid.zendesk.com/hc/en-us) for issues or suggestions. That would be the quickest and most efficient route for you to get your questions answered or raise any issues.

We'd be very keen to provide support and answer any questions you may have in regards to upgrading to newer versions.

Looking forward to hearing from you.

Kind regards,
Zoheil

**Comment by eugeniobet** [comment]
It's really not about the support, it's about the needing of it itself.
How is it that you guys don't have tests checking out whether a simple excel export actually doesn't result in a blank file?
You can bear with me and recognize the frustration when such a list of breaking changes is presented.
