### ISSUE TITLE
Rows don't render if grid is hidden and then shown

### ISSUE THREAD

**Issue by AmitMY** [ceolter/ag-grid#952]
I have a table, showing only **AFTER** it was loaded.
Meaning - If I don't have data, I don't show a table.

It seems like ag-grid thinks it is hidden (and it is), so it renders just the first few rows, and stops after 6.
If I am already scrolled down, it does not show a thing (because it renders the first rows)

Is there a way to implement an event for "when ag-grid visibility changes" and reload the view?
(I see a lot of implementations online, most suck)

Here are the two cases, in video form:
https://www.youtube.com/watch?v=qjvlmxW_KJg

I have a fix, and it is dumb.
```
showGrid();
$timeout(function() {grid.api.setRowData(my_data);});
```

This garanties at least one $digest cycle, making the grid visible, then adding the rows. (And it is dumb)

I don't think I am the only one who encountered this, that's why I don't implement it myself..

**Comment by ceolter** [comment]
this shouldn't be necessary. the grid has a timer, that checks the grid's height every 300ms. if it finds a change in height, then it renders any missing rows (or removes rows if to many). i'd need to know why this isn't working . . . . . . can you check? or reproduce in a plunker?

**Comment by AmitMY** [comment]
Could not reproduce - Here is my test http://plnkr.co/edit/sYAvw3rDLwHb8INQBo8A?p=preview
So, do you have a method to dump all the grid's config? if so I could send you the output.
Also, in the plunker, it seems like (in chrome) middle click is not usable

**Comment by ceolter** [comment]
do you have a method to dump all the grid's config
=> nope. but i don't think that would help. my gut feeling with his is it's clashing with something in your app. the fact you can't reproduce in plunker suggests this also.

**Comment by smelyakov** [comment]
@AmitMY Is this the issue you have? https://plnkr.co/edit/WLinh55zkE0T4JQeiBoV?p=preview

**Comment by AmitMY** [comment]
@smelyakov Yep, thanks! How did you reproduce?
@ceolter This is a major problem for me, don't know why but it happens a lot for my tables..

**Comment by smelyakov** [comment]
@AmitMY That happened to my tables too. It was mentioned here https://github.com/ceolter/ag-grid/issues/824

**Comment by ceolter** [comment]
with the example, i was able to troubleshoot and fix. it happens when you try and initialise the grid with ng-show=false

now, my timer picks it up, so after 500ms, the grid fixes itself.

to get around this in ng1, have a watch on the 'show' flag, and when it gets set to true, call gridApi.refreshView() or gridApi.doLayout() in a timeout of zero milliseconds (ie after the angularjs VM turn has finished)

**Comment by AmitMY** [comment]
No built in solution for NG1? (do we need to implement every time, or did you make it global somehow?)

**Comment by ceolter** [comment]
there is a built in solution, it checks for grid visible every 500ms, same way as it checks for grid resizing every 500ms.

**Comment by riteshwaghela** [comment]
I have similar kind of issue with ag-grid-angular. There are two tabs and one of them (fist) is having grid. By default the first tab is active and I see the grid being rendered properly, now when I navigate to 2nd tab and come back to first tab it shows the overlay and never renders the rows.

**Comment by AmitMY** [comment]
Which overlay? Loading/no rows?

**Comment by riteshwaghela** [comment]
I have given a custom overlay for the grid to show loading message. I am using overlayLoadingTemplate property for the same. Loading.

**Comment by AmitMY** [comment]
So imo, it is a users logic issue. Can you please reproduce on plunker or something?
btw, this is not related to this issue, but a new issue/support request.

**Comment by riteshwaghela** [comment]
I don't think it is a user logic issue. The issue I am facing is quite close to your issue. The only difference is the use case. In your scenario it was hidden and then shown and in my scenario it is show-hide-show and the grid don't load. I have opened a new issue. Thanks.

**Comment by Thiru0808** [comment]
Did this issue has any fix ?

**Comment by fedia1994** [comment]
@riteshwaghela  did you find a solution for your problem ?
