### ISSUE TITLE
allow angular 2 bindings inside the grid

### ISSUE THREAD

**Issue by vknaveenkumar** [ceolter/ag-grid#953]
can any say how to use checkbox in cell template ? and how to bind checkbox to the function ?

**Comment by AmitMY** [comment]
For the column that you want to have the checkbox, you can do:
`checkboxSelection: true`
Or if you want to do it dinamically, you can do something like this:
```
checkboxSelection: function (params) {
    return params.columnApi.getRowGroupColumns().length === 0;
}
```
The checkbox is already bound to the row select/deselect function..

----
If I did not understand correctly, and you want a checkbox header, you can do something like this:
```
function headerCellRendererFunc(params) {
    if (params.colDef.field != "checkbox")
        return params.colDef.headerName;

    var cb = document.createElement('input');
    cb.setAttribute('type', 'checkbox');

    var eHeader = document.createElement('label');
    var eTitle = document.createTextNode(params.colDef.headerName);
    eHeader.appendChild(cb).appendChild(eTitle);

    cb.addEventListener('change', function (e) {
        if (this.checked)
            params.api.selectAll();
        else
            params.api.deselectAll();
    });

    $rootScope.$safeTimedApply();

    return eHeader;
}
```

**Comment by vknaveenkumar** [comment]
Good....
how to use button in cell template ? and how to call button function to the component ?

**Comment by AmitMY** [comment]
Angular/react/js?

**Comment by vknaveenkumar** [comment]
Angular 2

**Comment by vknaveenkumar** [comment]
how to check the mutiple checkbox?

**Comment by AmitMY** [comment]
You use a cellRenderer to create buttons - https://www.ag-grid.com/javascript-grid-cell-rendering/index.php
I don't know how to detect clicks in ng2, here is a code for ng1 I use.
```
function renderHideButton(params) {
    params.$scope.hideClient = vm.hideClient;
    return '<button class="btn btn-danger btn-small" ng-click="hideClient(data.client_ID)">' +
        '<i class="fa fa-times"></i>' +
        '</button>';
}
```
----
What do you mean by 'check the multiple checkbox'? The header one?

**Comment by vknaveenkumar** [comment]
i am asking in angular2?

**Comment by vknaveenkumar** [comment]
that ng-click is on angularjs

**Comment by AmitMY** [comment]
@ceolter is the developer. What should they do for ng2?

**Comment by vknaveenkumar** [comment]
i have grid which contains check box in one coloumn .As per document we would not select the mutiple check box .can u say how to select multiple checkbox ?

**Comment by ceolter** [comment]
grid doesn't support angular2 bindings yet. we don't know how to do it, if someone can tell us, then we can implement it.

ps closing issue, as original question was answered. thanks Amit for answering above.

**Comment by vknaveenkumar** [comment]
is there is any idea for future release? for binding

**Comment by ceolter** [comment]
we are looking into it - if anyone can tell us how to implement bindings in ng2 when not inside an ng2 component please tell us and we will implement it.

**Comment by vknaveenkumar** [comment]
look forward for your next release for angular 2 bindings inside the grid

**Comment by ceolter** [comment]
@vknaveenkumar we still need to figure out how to do it!!!

**Comment by rwilliams-scottlogic** [comment]
Is there any discussion online with the Angular2 team about what's needed to allow compiling & binding to be implemented? I can't find anything on their GitHub. I'm new to Angular2 so not well placed to start such a discussion.

**Comment by ceolter** [comment]
no resource that i know about.

**Comment by seanlandsman** [comment]
ag-grid-ng2 fully supports two way binding, as well as AOT. Closing this
