### ISSUE TITLE
paginationPageSizeSelector is not working propertly. 

### ISSUE THREAD

**Issue by martinmanriquezleon** [ceolter/ag-grid#9531]
I want to display page size drop-down in my angular ag grid and found that we can do this by using

But if I add this in my ag-grid, it is throwing an error as below :

`ag-grid: invalid gridOptions property 'paginationPageSizeSelector' did you mean any of these: paginationPageSize, paginationAutoPageSize, suppressPaginationPanel, onPaginationChanged, pagination, onPaginationPixelOffsetChanged, enableRangeSelection, paginationNumberFormatter`

I am using ag-grid-angular version: 28.2.1

### HTML :
 `<ag-grid-angular
[pagination]="true"
[paginationPageSize]=10
[paginationPageSizeSelector]="paginationPageSizeSelector"
/* other grid options ... */>`

### Typescript:
` 
 public paginationPageSizeSelector = [10, 20, 50, 100];
`

**Comment by AG-Zoheil** [comment]
Hi @martinmanriquezleon,

This has been added in version 31. Please upgrade your application to use this property.

Kind regards,
Zoheil
