### ISSUE TITLE
Usage of cellRenderer animateShowChange in the Free Edition

### ISSUE THREAD

**Issue by BuddyWork** [ceolter/ag-grid#954]
Is it possible to use animateShowChange where the bid and ask price changes are shown for a short time, just like your example but in the free version?

**Comment by ceolter** [comment]
should be - they are part of the free version.

**Comment by BuddyWork** [comment]
I've added the following

        {
            headerName: "Position",
            field: "Position",
            width: 100,
            cellClass: 'cell-number',
            cellRenderer: 'animateShowChange'
        },

and I don't see the rendering happening, do I need to do anything else?

**Comment by ceolter** [comment]
just make sure your using it right, you will have to call rowNode.setDataValue() for the animation to happen, et

```rowNode.setDataValue(change.columnId, change.newValue)```

**Comment by BuddyWork** [comment]
ok thanks
