### ISSUE TITLE
onColumnHeaderClicked is not working

### ISSUE THREAD

**Issue by meghna786** [ceolter/ag-grid#9542]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Providing a Reproducible Scenario
I am trying to use the onColumnHeaderClicked event, but it is not triggering as expected. I followed the documentation and added:

`
onColumnHeaderClicked: (event) => {
                debugger
            }
`
This was added to both the columnDef and gridOptions. However, the event does not fire when clicking on a column header.

For your reference, I am attaching my gridOptions and columnDef objects in a text file.
I suspect there might be a property I am missing or a conflicting property that is overriding the onColumnHeaderClicked event.

Versions:

Adaptable Grid: 17.0.6
AG Grid: 30.2.1
Please find the relevant configurations attached:

[New Text Document.txt](https://github.com/user-attachments/files/18145531/New.Text.Document.txt)

**Comment by AG-Zoheil** [comment]
Hi @meghna786,

The event works as displayed in this example: https://plnkr.co/edit/tlPU5A4BT2BqirkG?open=main.js.

If there is a certain scenario you believe it doesn't trigger, please fork the above Plunker, adjust it as desired, save it and share for us to investigate.

Much appreciated.

Kind regards,
Zoheil
