### ISSUE TITLE
Is there a way to expand a group from the api?

### ISSUE THREAD

**Issue by albertoacuna** [ceolter/ag-grid#956]
I want to expand a group node programatically from the api when I know the row index. Is there a way to do this using an api method call? I don't see anything in the documentation.

**Comment by albertoacuna** [comment]
Nevermind. I have found the method I was looking for, onGroupExpandedOrCollapsed. Thanks

**Comment by DzmitryShylovich** [comment]
@albertoacuna how do u use it? it doesn't work for me
