### ISSUE TITLE
Row Selection groupSelects descendants does not select parent node

### ISSUE THREAD

**Issue by evkw** [ceolter/ag-grid#9565]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
[Plunker](https://plnkr.co/edit/4lFAFxZSjSXjWS70?open=app.component.ts)

![image](https://github.com/user-attachments/assets/1aa0d1b1-53f7-4ebf-a4f8-41ee2908eb9b)

In the above example I have no way to select 'Troy Walsh'

**Repro Steps **
- Tree list grid with the following row selection config rowSelection = { mode: 'multiRow', groupSelects: 'descendants'}
- Select a parent node

**Current behavior**
- Only descendants are in the api.getSelectedNodes()

**Expected behavior**
- Parent node and descendants are in the api.getSelectedNodes()

**Note**
In version 30.2.0 a tree list with groupSelectsChildren = true and rowSelection="multiple" will select parent node and descendants. I found this issue from a failing e2e test when updating ag-grid version. Here is an example [plunker](https://plnkr.co/edit/DKgXMvSNlvIaXc2j) of the same set up in v30 with the expected behavior.

* **AG Grid version:** 33.0.2

* **Browser:**
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0'

**Comment by Zain-Bin-Arshad** [comment]
Facing similar issues where I am not able to accomplish the selection in a way that I want, somewhat similar to what has been pointed out above.

**Comment by AG-Zoheil** [comment]
Hi,

Thanks for getting in touch. This is not a bug however the old behaviour was due to an inconsistency between tree data and row grouping. We fixed this via **AG-11658** so that now both row grouping and tree data only return the child rows. 

Depending on your specific use case you could use getBestCostNodeSelection.
You can see an example of this here: https://plnkr.co/edit/j1og7Rp6uqNyLLZd?open=app.component.ts

Kind regards,
Zoheil

**Comment by evkw** [comment]
That function only seems to work for the nearest parent. If you choose a parent further up the tree, you end up missing a bunch of selections.

In the example below:
- If I click on 'Troy Walsh' I correctly get that node and its children. 
- If I click on 'Addie Myer' the selection does not include 'Troy Walsh' or the other group node at the same level as 'Troy'
- If I click the top node i assume all the grouped nodes underneath are not selected (the data set is abit unwieldy to verify this assumption though)

Is there no way to introduce a 'SelfAndDescendants' to the group selects options?

https://plnkr.co/edit/V3kZCq2hxYgiD8Uw

![6EBE49E9-926D-4B26-9DD6-830E0BAB89CB](https://github.com/user-attachments/assets/7275b324-38cb-4139-b59e-692eb238b278)

I debugged that function and once it sees a node 'isSelected' it doesnt check the childrenAfterGroup.

![image](https://github.com/user-attachments/assets/fb7bb776-8a19-45e6-9a13-5e9befe8c3d6)

**Comment by AG-Zoheil** [comment]
Hi @evkw,

Thank you for the feedback. It seems like your use case can be achieved with the following approach: https://plnkr.co/edit/Fr9dexi4FzuD3KtI?open=main.js.

In any case please note that we do not provide support via GitHub and therefore cannot comment further.

Kind regards,
Zoheil

**Comment by evkw** [comment]
I was able to use your example to make a workable solution.

Thanks for your assistance!
