### ISSUE TITLE
[Feature] Linked Tables

### ISSUE THREAD

**Issue by AmitMY** [ceolter/ag-grid#957]
Here is a problem every front end developer encountered:

> Showing a list of lets say users, and needing to show the country, but unfortunately the back end does not join the countries's table, and is busy right now, or adding that specific join makes everything slower. (Yes, they need to optimize, but sometimes they are assholes), or the back end was made a long time ago, and cannot be changed

The solution so far (with a table library, not simple code):

> Send request 1 (async), get a list of users
> Send request 2 (async), get a list of countries
> Wait for both to finish, using a flag or something, and when both do, create a hash table of the countries, then go over the users, and do 
> `users[i].country_name = countries[users[i].country_code].country_name;`

And if you have 3-4 linked tables required, it gets more complicated quickly

---
There is a better solution. I tried to implement myself, but failed to understand the scope of variables, so couldn't, you'll understand in a second.

- Pass to the gridOptions a parameter linkedTables, which must be an object. The key is the table's index, the value is an array or a promise.
For example:
```
linkedTables: {
    "country_code": new Promise(function (resolve, reject) {
        dataFactory.getCountries().done(function (response) {
            resolve(response.data);
        });
    }),
    "language_code": [
        {"language_code": "EN", "language_name": "English"},
        {"language_code": "IT", "language_name": "Italian"},
    ]
}
```
- have a variable. lets say tableTables which is an empty object, not exposed!
- have a variable, lets say agTables, which is exposed to valueGetter, and is a function.
- Go over the linkedTables. If array, construct a table** from the array and the key. If promise, do a 'then' or something, and then construct the tables. After constructing a table, put it in tableTables[key]
- On valueGetter, allow writing `agTables("country_code", data.country_code, "country_name")` (valueGetter/different thing, Not cellRenderer)
- If the table did not load yet, return the key.
- On promise finish, reload the volatile columns (all columns using agTables are volatile)

Complexity: O(1)

Here is the agTables function:
```
function agTables(table, index, value) {
    if(tableTables[table] === undefined)
        return index;

    return tableTables[table][index][value];
}
```

Here is the hash tables building function:
```
function buildHashTable(array, key) {
    var table = {};
    for (var x in array) {
        if (array[x][key] !== undefined)
            table[array[x][key]] = array[x];
    }
    return table;
}
```

---
This seems quite simple to implement.
So why am I asking you to add as a feature?

- I don't think I am the only one needing something like this
- It is too complex when you have a report for all of your clients for example, with 15 linked tables in O(1), or sending 15 requests and managing their flags..
- Main reason? I did not understand what is the scope of valueGetter, therefor, I couldn't get to the agTables function, as much as I tried.

---
**Sorry for the long post, thought it would help if I lay everything down for you guys, so you will understand it is probably a work for an hour.**

Also, It looks like you aspire to be the Excel of the web. Excel has linked tables, but it is slow because it does not create indexes. Here we do create indexes, for NO PERFORMANCE IMPACT.

**Comment by ceolter** [comment]
will have to come back to this Amit, my brain is pretty fried getting the pivoting working, so any issue that's not easy for me to understand i'll have to part :(

**Comment by AmitMY** [comment]
No problem. It shouldn't be difficult, I laid all the logic down, just need to find the right scope to put it in :)

**Comment by AmitMY** [comment]
Hi again @ceolter . Now that pivot is released, can you please go over this and see if this is something you would want in the grid?

**Comment by ceolter** [comment]
hi @AmitMY, this to me sounds like a non-grid problem - the grid assumes the data you give it is complete.

if it is now, and you need to 'add' in elements to the row data, then you can do it by calling ```setData(data: any)``` or ```setDataValue(colKey: string|ColDef|Column, newValue: any)``` - the first sets the whole row data, the second sets specific columns. the grid will work out what needs to be refreshed when this happens.

putting the logic into the grid to me seems wrong place to put this responsibility.

**Comment by ceolter** [comment]
ps - nobody else has asked for this - which is another reason to keep the complexity out of the grid - it sounds specific - so it could cause more issues for more people who don't need it than problems is solves!!

**Comment by AmitMY** [comment]
Oh ok... thanks anyway
I think it is very useful, because for me data comes from many sources, not one.
Ill try to implement it again soon, if Ill get stuck again Ill ask in the forum for help :)
