### ISSUE TITLE
What about cellContextMenu?

### ISSUE THREAD

**Issue by srccircumflex** [ceolter/ag-grid#9576]
The event **cellContextMenu** is no longer emitted as of **version 33**. 
Comparison of the files _dist/ag-grid-community.js_ from **version 32** x **version 33**:
A rough overview of the files reveals that the `handleContextMenuMouseEvent` method is no longer implemented in `RowContainerEventsFeature` in **version 33**. Instead, an attempt is made to reach `this.beans.contextMenuSvc?.handleContextMenuMouseEvent`.

**Comment by sabahang** [comment]
Hello 

Please see if you can get around this by adding ContextMenuModule into your project. However we have already raised a ticket to include this event by default with the following tracking number: AG-13705

Hope this helps

**Comment by srccircumflex** [comment]
Many thanks for the integration (v33.0.3). This saves me some workarounds.
