### ISSUE TITLE
fitCellContents only works for columns within viewport only

### ISSUE THREAD

**Issue by tom10271** [ceolter/ag-grid#9587]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid** No
**Requesting Community Support** No
**Providing a Reproducible Scenario** https://codesandbox.io/p/sandbox/quick-start-example-forked-sh769n?workspaceId=ws_YN8LW72BbH1UyGtugpXeoy

**Current behavior** fitCellContents only works for columns within viewport only
Working within initial viewport
<img width="615" alt="Screenshot 2024-12-19 at 6 23 51 PM" src="https://github.com/user-attachments/assets/d3f286c6-efad-478c-b083-91f8deaefa7d" />

Columns remains original width which is too wide
<img width="610" alt="Screenshot 2024-12-19 at 6 25 16 PM" src="https://github.com/user-attachments/assets/ebf028c7-54b2-4dcd-aadc-68cffd9b784f" />

**Expected behavior** It works

**Please tell us about your environment:** macOS Version 15.2 (24C101)

* **AG Grid version:** ^33.0.2

* **Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36

* **Language:** TS ~4.5.5

**Comment by tom10271** [comment]
btw if I set to fitProvidedWidth, the result looks buggy. It seems all columns jammed into the same place

<img width="1208" alt="Screenshot 2024-12-19 at 6 28 28 PM" src="https://github.com/user-attachments/assets/4011292a-d69d-4169-a03c-27a4c2474155" />

**Comment by sabahang** [comment]
Hi,

This is due to Column Virtualization. Please see here: https://ag-grid.com/vue-data-grid/dom-virtualisation/

Please see a modified version of your code here: https://codesandbox.io/p/sandbox/quick-start-example-forked-l6ksr6?workspaceId=ws_QY3r1GqFDkiEPMdhYVPBdd

Hope this helps
