### ISSUE TITLE
Unusual behavior with ag-grid

### ISSUE THREAD

**Issue by Dauth** [ceolter/ag-grid#959]
I'm using this with react and I'm not sure why regardless if the data is or isn't empty the table keeps increasing in height. 
[Increasing height
](https://openload.co/f/121dogfuoy8/increasing.avi)

**Comment by AmitMY** [comment]
Can you please reproduce in a plunker?
Here is a base plunker: http://plnkr.co/edit/IWn5IDBa9roECqcv36Fv?p=preview

**Comment by ceolter** [comment]
ditto with Amit - need more info!!

**Comment by ceolter** [comment]
no response, so closing
