### ISSUE TITLE
Following up on #7782

### ISSUE THREAD

**Issue by shivanip9** [ceolter/ag-grid#9592]
Hi, could you please provide an ETA for this bug fix? I searched for it in the changelog and the backlog but couldn’t locate it.

_Originally posted by @shivanip9 in https://github.com/ag-grid/ag-grid/issues/7782#issuecomment-2556146661_

**Comment by AG-Zoheil** [comment]
Hi @shivanip9,

The bug was not showing up in your view of the pipeline due to a missing label. This has now been rectified. Thank you for letting us know.

Kind regards,
Zoheil
