### ISSUE TITLE
ERROR TypeError: Cannot add property __NG_ELEMENT_ID__, object is not extensible when using custom components

### ISSUE THREAD

**Issue by moodyVlad** [ceolter/ag-grid#9597]
I am using AG Grid v33, and AG Grid Angular. Angular version is 19.
If I am using custom components, either in the cell renderer, floating filter or filter values I get the following error:
TypeError: Cannot add property __NG_ELEMENT_ID__, object is not extensible when using custom components

<img width="807" alt="image" src="https://github.com/user-attachments/assets/f4829b48-8bc7-4f7b-9fbf-124bd626c40d" />

**Comment by sabahang** [comment]
Hi @moodyVlad 

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

**Comment by OmarMtya** [comment]
What did you do to fix it? or what was the issue? I can't find what I'm doing wrong

**Comment by o-in25** [comment]
I am having the same issue

**Comment by OmarMtya** [comment]
> I am having the same issue

For my issue, I was using ngrx to get the data, so basically is because you're trying to mutate an object that came from a selector (which breaks the principle of redux pattern). The solution I found was to create a deep copy of the objects with lodash and load it into the aggrid after.

Good luck
