### ISSUE TITLE
 checkboxSelection

### ISSUE THREAD

**Issue by vknaveenkumar** [ceolter/ag-grid#961]
When a checkboxSelection column is included in a grid . clicking in the checkbox cell  clears other selected cell .is there is any properties?

**Comment by ceolter** [comment]
that's not what happens, eg check the main online demo, it supports multi-row selection.

ensure property rowSelection='multiple'

**Comment by urielz1987** [comment]
Add the property  - 
`suppressRowClickSelection: true`

and it will stop to clear the other selected rows.
