### ISSUE TITLE
Bad practice?

### ISSUE THREAD

**Issue by AmitMY** [ceolter/ag-grid#962]
I'm using ag-grid with angular1, as a directive.
That means, the API only loads after the first digest cycle, or in some cases a couple of cycles.
So if I want to show a grid, instantly loading data, on my data getting function, I'm calling this function:

```
function showLoading() {
    if (vm.grid.api === undefined)
        $timeout(showLoading);
    else
        vm.grid.api.showLoadingOverlay();
}
```

If it is the page full refresh, it calls this function 3 times.
If it is just a location change, usually 2 times.
If I just call the function after the grid's loading, like with free-text server-side text search, it calls only once.

On the one hand I feel dumb for doing so, but on the other I see no alternative.
Is this the correct way?

**Comment by ceolter** [comment]
use the gridReady callback.

used in lots of my examples, such as the one on this page:
https://www.ag-grid.com/javascript-grid-value-getters/index.php
