### ISSUE TITLE
Unclear documentation regarding filters

### ISSUE THREAD

**Issue by GustavSt** [ceolter/ag-grid#964]
Looking specifically on the function `doesFilterPass`, where to me it seems the parameter sent to it contains a node-property and a data-property (looking at filterManager.ts row ~160), but the documentation says differently. 

> The grid will ask each active filter, in turn, whether each row in the grid passes. If any filter fails, then the row will be excluded from the final set. The method is provided the value (the value to be checked), the row node, the row data and the filter model (for the filter, as provided by the 'get model' below - for now, the model can be ignored).

It would be nice if the documentation was more specific here.

noticed [this issue](https://github.com/ceolter/ag-grid/issues/191) but the documentation doesn't seem to be updated entirely.

**Comment by ceolter** [comment]
look like the doesFilterPass gets a params object with node and data as follows:

```
var params = {
  node: node,
  data: data
};
filter.doesFilterPass(params)
```

i'll update the docs

**Comment by ceolter** [comment]
i have updated the docs to:
```
The grid will ask each active filter, in turn, whether each row in the grid passes. If any
                filter fails, then the row will be excluded from the final set. The method is provided a
                params object with attributes node (the rodNode the grid creates that wraps the data) and data
                (the data object that you provided to the grid for that row).
```
will be in next release

**Comment by GustavSt** [comment]
That was fast! Thanks!

**Comment by ceolter** [comment]
i was in the mood!
