### ISSUE TITLE
After api.setFilterModel call, filterModel is reset immediately in Angular1

### ISSUE THREAD

**Issue by drawyan** [ceolter/ag-grid#966]
The behavior seems happening only when using with angular1, the native one seems worked fine.

Use serverSideFiltering, and call api.setFilterModel to filter the grid, and the filter worked and new data fetched and displayed, but immediately the internal filterModel is reset to empty object. So we api.getFilterModel() is called immediately, you can see it's being correctly set, but right after that, it's reset.

Here is a demo that reproduce this issue: https://jsbin.com/resume/edit?html,js,output

**Comment by drawyan** [comment]
Seems related to this ticket: https://github.com/ceolter/ag-grid/issues/572

**Comment by ceolter** [comment]
can you tell me what i am meant to be looking at in the fiddle?

when i click the filter button, it does filter, from your description i'd expect it to not filter???

**Comment by drawyan** [comment]
Yes, it filters, but right after that, the api.getFilterModel is returning empty object, instead of persisting the filterModel just being set, because there's nothing else happening to reset the filterModel again, so the filterModel should stay as the new value.

**Comment by ceolter** [comment]
how are you including ag-grid?

i see the piece that references the script is commented out

**Comment by ceolter** [comment]
sorry, ignore, i see it
```
  <script src="https://cdnjs.cloudflare.com/ajax/libs/ag-grid/4.2.6/ag-grid.min.js"></script>
```

**Comment by drawyan** [comment]
It was included after angular, initially I thought it was the enterprise version that might be the difference from our dev environment, so I left it commented out. But included the non-enterprise version, this is what we are using at the moment.

**Comment by ceolter** [comment]
enterprise vs non-enteprise will make a difference, as the default filter is 'set' for enterprise, and 'text' for non-enterprise

anyway, am looking...

**Comment by drawyan** [comment]
Right, this is why I tried my best to reproduce it without any of the enterprise feature, as close as to our issue. Thank you!

**Comment by ceolter** [comment]
ok i have it, here is the workaround:

```
{headerName: "Make", field: "make", filterParams: {
      newRowsAction: 'keep'
    }},
```

basically, the grid is coded to clear the filters when you load new data. it's getting confused with the pagination and server side filtering, it thinks you are loading new rows.

still looking into it, but the above will get you unblocked

**Comment by drawyan** [comment]
Great! Thank you so much, I'll go with that first and update the library later when totally fixed.

**Comment by ceolter** [comment]
looking at the example online https://www.ag-grid.com/javascript-grid-pagination/index.php
it  uses ```newRowsAction: 'keep'``` there also, so that looks like the intended usage. can you advise if this is acceptable?

looking at it now myself, i'm not happy with it, but it is what it is. rather than spend 1hr on it now and hack something in, i'd rather keep this open and revisit next time we do a revision of this part of the code - where we will take a step back an improve the whole area at once spending a few days on it.

**Comment by drawyan** [comment]
I think it will solve the problem that we had, and I'll put this `newRowsAction: 'keep'` as our default column definition.

Thank you for the help, I think we are good for now. You can close this ticket if you like.
