### ISSUE TITLE
React agGrid - on new data sort is reset

### ISSUE THREAD

**Issue by ballwood** [ceolter/ag-grid#967]
Hi,

I'm using the react version of the agGrid library with redux. When I update the state it causes a refresh of the table and removes the currently selected sort option. Is there an option similar to newRowsAction for sorting that keeps the sort order?

**Comment by ceolter** [comment]
the grid does not loose sort when you update the rows. you must be completely destroying the grid and creating it again from scratch.

**Comment by ballwood** [comment]
Worked out what it was - Inside my react component I was creating a new object inside the render method to represent the columns of the grid. Every time it was rendered the reference was changing and agGrid thought that the column definitions were changing.

**Comment by ceolter** [comment]
yes if set in new columns, that resets the sort, as the sort is tied to the column.

**Comment by ShrikaranKanagaraj** [comment]
> I am facing the same issue, is there any solution for this?

could you review your code once for any manipulation on grid column functions and grid reference? if any that might be the root cause for it. earlier i had a similar issue.
