### ISSUE TITLE
Columns disappear issue

### ISSUE THREAD

**Issue by m-nagy** [ceolter/ag-grid#970]
When drag a column and drop outside the grid, the column disappeared from the grid and there is no way to return it unless refreshing the page.

This issue is applied to all demos on the grid's website. ex. [https://www.ag-grid.com/javascript-grid-sorting/index.php](url)

**Comment by ceolter** [comment]
if you don't want the column to dissappear, set suppressDragLeaveHidesColumns=true

**Comment by lisaanjuli** [comment]
I have the same problem, but I want it to have the drag and drop functionality. The columns should appear in the Column Menu to select it again. The columns is just shown again by refreshing the page.

**Comment by anton6** [comment]
@ceolter thanks that did the trick

Here is the full list of properties for reference: https://www.ag-grid.com/javascript-grid-properties/
