### ISSUE TITLE
ag-grid 1.13 get rows after filter

### ISSUE THREAD

**Issue by dhintze** [ceolter/ag-grid#972]
I need to continue to use ag-grid 1.13 (for now).  I need to be able to take some action on the rows, AFTER the filter is applied.  I am using the docs, but gridOptions.api.forEachNodeAfterFilter throws "is not a function" error.  and gridOptions.api.getModel().rowsAfterFilter is always undefined.

Surely there's a way to do this in older versions of ag-grid, right?

**Comment by AmitMY** [comment]
If you will provide a working plunker, using 1.13, I can try to figure it out.
Here is a 4.2 plunker, change what's needed to make it 1.13 http://plnkr.co/edit/IWn5IDBa9roECqcv36Fv?p=preview

**Comment by dhintze** [comment]
Ok, I think I've got it.  How does this work:  http://plnkr.co/edit/LJhpIiUdf10VWX6nWqcW?p=preview

**Comment by AmitMY** [comment]
These are your filter changed options:
```
filterModified: () => alert(1),
beforeFilterChanged: () => alert(2),
afterFilterChanged: () => alert(3),
```
They execute in order of the numbers I wrote.

For executing after, and just getting the filtered rows, I then just do:
`afterFilterChanged: () => console.log(gridOptions.api.inMemoryRowController.rowsAfterFilter),`

And it shows the filtered rows in console

Here is a plunker:
http://plnkr.co/edit/jGFRAzzLTPuGZ6AHJ0oJ?p=preview

Please tell me if this is what you wanted

**Comment by dhintze** [comment]
Beautiful... THANK YOU!!

**Comment by ceolter** [comment]
thank you @AmitMY
