### ISSUE TITLE
Get aggregated row

### ISSUE THREAD

**Issue by AmitMY** [ceolter/ag-grid#974]
Is there an API method to get the aggregated row?

Meaning, return a row with the aggregated data, according to aggFunc.

**Comment by ceolter** [comment]
not now, but you can hack it by grabbing the root node. just get any node, and follow the 'parent' attribute up until you get to the last one, which will be a non-displayed rootNode (which coincidentally will be displayed when you enter pivot mode in the future when that gets released)

**Comment by AmitMY** [comment]
Will do! Thanks a lot
