### ISSUE TITLE
Class level sorting on columns

### ISSUE THREAD

**Issue by a497988** [ceolter/ag-grid#979]
I am wondering if it is possibe/something being worked on to allow us to sort the columns based not only on the data, but also on a particular class that is applied to the cells within a column?

I want to be able to assign priority to the cells based on a class and a color, and then when a user clicks to sort the column in asc/desc order be able to pass in a class name to pre-sort them on, or sort them on first. I think this would be a very useful item.

Does something like this already exist? Do you think this is something that could be implemented/will be implemented anytime in the near future?

**Comment by AmitMY** [comment]
I'm not sure I fully understand what you mean, but you should read about the 'comparator' function, it may help.

> comparator(valueA, valueB, nodeA, nodeB, isInverted) - Comparator function for custom sorting.

**Comment by a497988** [comment]
Essentially I would like to be able to do a multi-sort on one column, but using separate identifiers to sort. So the first sort I would like to do is say based on the CSS class assigned to it (just an example)
and the second sort to sort the values.

The idea:
I have 9 rows, 
1 - cell class (RED), Value 1
1 - cell class (RED), Value 1
1 - cell class (RED), Value 1

**Comment by AmitMY** [comment]
That's no problem using a comparator function.
Lets say your data model is this: {class: 'RED', value: 1}
So your function should be:

    function customComparator(value1, value2) {
        if(value1.class != value2.class) {
            var classes = {
                'RED': 1,
                'YELLOW': 2,
                'GREEN': 3
            };
            return classes[value1.class] - classes[value2.class];
        }
        return value1.value - value2.value;
    }

And of course you should declare the classes as a global variable, otherwise it will always need new memory

**Comment by a497988** [comment]
How would I get my data object to look like that? When we use the comparator it passes back the value of the columns only. So if I had an object like you described wouldn't it pass back only the value of 1, instead of the whole object?

**Comment by AmitMY** [comment]
It will.
However, you can model your data to look like the object I described, and then use cellRenderer to print just the number.

This is just my help as a guy who works with the grid for quite some time now... Maybe @ceolter has a better answer, though it seems he is busy these days so I wouldn't count on a swift answer

**Comment by a497988** [comment]
Thank you for the help, it sets me off in a direction at least to look at. If @ceolter has a better way or maybe a native way to the grid then I can use than. But for now this looks like a good approach.

Thank you!

**Comment by ceolter** [comment]
@a497988 @AmitMY yes all the above makes sense.

if you want to sort any way other than what the grid does, comparator is the way to go.

with regards manipulating the data before it gets rendered, yes you can use cellRenderer.

normally i would suggest using valueGetter as cellRenderer should really be for GUI DOM type stuff. valueGetter is executed first, and value passed to cellRenderer - valueGetter is also used for filtering, csvExport, sorting - and that's the issue here, sorting is passed the value from valueGetter, so chicken and egg.

thanks again Amit for helping out, and yes i'm pretty busy these days!!
