### ISSUE TITLE
[Feature] OnMoving and OnMoved

### ISSUE THREAD

**Issue by killyosaur** [ceolter/ag-grid#980]
It would be nice if the OnMoved event fired only when the column was dropped into its destination location and then you could have an OnMoving event when the column is being moved to a location. Currently, OnMoved fires when the column is moving, and as such I have no easy way of detecting when the move is finished. Plus the name is deceptive as it does not actually describe what is happening. This is largely an issue when moving a column by dragging and dropping it to a new location.

**Comment by killyosaur** [comment]
Should have deep dived a bit more, found the currently undocumented (as far as I can tell) Drag Stopped event :) Sorry for the noise!

**Comment by ceolter** [comment]
yes that event will work. getting another event for 'moving stopped' isn't possible without a lot of rework, as the columnController (that sends out the column events) is not aware when dragging stops after columns were moved. it is also not aware when a column is moved, if it is the last move.

**Comment by killyosaur** [comment]
Yeah, with the dragging events, there is no need for the on moving. Thanks for looking into it though!
