### ISSUE TITLE
Shift click does not cause SelectionChanged event to fire.

### ISSUE THREAD

**Issue by killyosaur** [ceolter/ag-grid#981]
http://plnkr.co/edit/Y9RI3c9Cc8jD5lUK84AQ?p=preview

It fires for individual clicks, but does not fire for a shift + click.

**Comment by pccjamie** [comment]
+1

**Comment by ceolter** [comment]
will be fixed in next relese

**Comment by pccjamie** [comment]
@ceolter  - Thanks for the fix! Unfortunately, the new release (5.0.0-alpha.3) seems to have another bug. SHIFT select works now, but the selection doesn't highlight any columns that are pinned.

We're evaluating the enterprise version so I'll post the issue on that repo.

**Comment by ceolter** [comment]
fixed. check alpha4.

**Comment by killyosaur** [comment]
Thanks for the fix!
