### ISSUE TITLE
[Feature] allow group reordering in column drop panel

### ISSUE THREAD

**Issue by Roman-K93** [ceolter/ag-grid#983]
I would like to request a feature to change the order of grouping new added columns on drop panel.
![untitled](https://cloud.githubusercontent.com/assets/7987856/16301091/165e505a-394c-11e6-9d92-78978e3ac087.png)

**Comment by ceolter** [comment]
yes i'd like to have this to, for the next big pivot release, as it would be good for pivoting also

**Comment by Roman-K93** [comment]
Can we expect this feature also with pivoting in 5.0.0?

**Comment by ceolter** [comment]
very likely

**Comment by ceolter** [comment]
this was put in end of last year
