### ISSUE TITLE
iAggFuncService missing from dist/lib/interfaces

### ISSUE THREAD

**Issue by mpetkov** [ceolter/ag-grid#984]
In this file: https://github.com/ceolter/ag-grid/blob/master/main.d.ts
Line 52 states:
```
export * from './dist/lib/interfaces/iAggFuncService';
```

However when you go here: https://github.com/ceolter/ag-grid/tree/master/dist/lib/interfaces
That file is missing.  This is causing Typescript errors and preventing the build from completing.

**Comment by ceolter** [comment]
fixing now

**Comment by ceolter** [comment]
try now. 5.0.0-alpha.2
