### ISSUE TITLE
IMenuFactory class name should have a lowercase i

### ISSUE THREAD

**Issue by mpetkov** [ceolter/ag-grid#985]
Line 57 in this file: https://github.com/ceolter/ag-grid/blob/master/main.d.ts
is looking for './dist/lib/interfaces/iMenuFactory'.

However the files here: https://github.com/ceolter/ag-grid/tree/master/dist/lib/interfaces
Have a capital I instead of lowercase i.

**Comment by ceolter** [comment]
fixing now

**Comment by ceolter** [comment]
try now. 5.0.0-alpha.2
