### ISSUE TITLE
document virtual mode behaviour: you must not call successCallback in your getRows function directly

### ISSUE THREAD

**Issue by kbdguy** [ceolter/ag-grid#986]
ag-grid v4.2.7

error thrown using virtual mode while scrolling; results in row not being rendered properly.

see: https://plnkr.co/RvBbhIlKM2tS0UlcIxf3

Just scroll down  with the browser console open. At row 20, the error is thrown, and the row is not rendered properly.

**Comment by ceolter** [comment]
does this break the grid? or just give error message but grid works fine? need to understand the severity. looks to me like grid works fine with error so lower severity.

**Comment by kbdguy** [comment]
In this example, every 20th row is rendered with all blank cells (presumably because 20 is the page size). So, yeah, I think that's a bit broken.  If you scroll back and forward again, the error doesn't happen and then the 20th row is rendered properly (presumably because the data was cached properly.

The error is happening in RowRenderer.prototype.unbindVirtualRow(), 2nd line: renderedRow.destroy().  because renderedRow is undefined.

**Comment by kbdguy** [comment]
Aha... i found the solution. In my "getRows" method, I called successCallback directly.  When i change it to ` setTimeout(()=> params.successCallback(newRows, lastRow),0);`, the problem disappears.  For an infinite grid, it makes sense to expect the successCallback to happen async, but I was taking an incremental approach to test it out first without going to the server.  I think it would be good if you would document that the successCallback must be called async.

**Comment by ceolter** [comment]
ah yes, that problem :(

i've just fixed this, the call to getRows() is now async, so this problem will never happen.
