### ISSUE TITLE
How to pass param in cell template

### ISSUE THREAD

**Issue by ajaysattikar** [ceolter/ag-grid#987]
Is there any way through which I can pass "param" in cell template?
So that I can use just a reusable function and call it through a template in the multiple columns instead of passing the HTML markup for every column.
```
var tplFn = function(param) {
			return '<span title="' + param.value + '">' + param.value + '</span>';
		};
var columns = [ {
			field: "guid",
			headerName: "GUID",
			template: tplFn
		}]
```
I am already using cellRenderer property for some other unavoidable requirement, so preferably want to avoid the replacement. Kindly suggest.

**Comment by AmitMY** [comment]
The only way I know how to do so is using cellRenderer. If you already have one for that column, you can extend the function. (call the other cellRenderer from a new one, and wrap it or replace in it)

**Comment by ceolter** [comment]
if your using cellTemplate - then your using AngularJS right? in which case, stick what you need onto your rowData, which will then be available through the scope?

Amit - thanks again +1:
