### ISSUE TITLE
Cells not flashing on update

### ISSUE THREAD

**Issue by Ventajou** [ceolter/ag-grid#988]
Hi,

I've got the grid working great on an Angular 1 project. I'm running `softRefreshView()` after updating some data on my rows and I have `enableCellChangeFlash: true` in the grid options.

After looking through the source, it seems that the following CSS classes are used for the flashing: `ag-cell-data-changed` and `ag-cell-data-changed-animation` so I set those up with some test rules.

However nothing happens when the data gets updated. Am I missing something or is it broken?

**Comment by AmitMY** [comment]
Please try running `gridOptions.api.refreshView();`
If that gives you the result you want, then you can look here for the best refresh method for you:
https://www.ag-grid.com/javascript-grid-refresh/index.php

(You are using soft refresh, that works only for volatile columns)

**Comment by Ventajou** [comment]
I tried both ways, neither worked...

**Comment by ceolter** [comment]
use a) rowNode.setData(data) or b) rowNode.setDataValue(colKey, value)

a for when you are changing all the data for the row.

b for changing just one attribute of the row.

this feature, although works, was designed with a particular customer in mind, really it should work for the api refresh calls also, but it doesn't :(

**Comment by thegonks** [comment]
Is colKey the same as colId?

**Comment by ceolter** [comment]
```Is colKey the same as colId```

any part of the API that takes a colKey, you can give it any of Column object, ColDef object or ColId

**Comment by a497988** [comment]
@ceolter - do you plan to make this work with the api refresh calls?

**Comment by Kishoreinline** [comment]
@ceolter When I'm using community edition, cell flashing used to work as expected. Now I have updated to the Enterprise Edition ag-grid-enterprise": "^26.0.1" after that, flashing is happening to all the cells even if the value is not updated. By the way, my current enterprise edition is a trial version.
