### ISSUE TITLE
style causes grid to grow longer

### ISSUE THREAD

**Issue by tonyeung** [ceolter/ag-grid#989]
```
.ag-fresh .ag-root {
  border: 1px solid #808080;
}
```

This particular rule in the ag-fresh theme (theme-fresh.css) is causing my grid to grow longer (vertically). Please see the recording below.

[![enter image description here][2]][2]

  [2]: http://g.recordit.co/KS42SaMdhN.gif

I was just able to narrow down the problem to this rule, so I don't have a repro, yet. I'll try to get it added to this issue in the next couple days. My setup is angular 1.5, angular material, and ag-grid 4.2.7. Posting this now in case anyone else has encountered this or might know why a border would cause the grid to grow little by like this.

**Comment by tonyeung** [comment]
while working on another problem, it seems if one of the ancestors between <html> and the grid doesn't have flex, then the grid will have the same behavior.

See this pen: http://codepen.io/tonyeung/pen/rLyvEm?editors=0100

**Comment by tonyeung** [comment]
The grid will grow if every ancestor sans `html` doesn't have the flex style applied. When I applied `display:flex` as well as `flex: 1`;

**Comment by ceolter** [comment]
thanks for feedback the the solution to others. i would not of got this, i don't use flex.

**Comment by tonyeung** [comment]
no problem, glad I could help.
