### ISSUE TITLE
selectionChanged callback not called when selecting multiple lines using shift

### ISSUE THREAD

**Issue by jlame** [ceolter/ag-grid#990]
I've noticed that the selectionChanged callback is not called when doing a multiple selection using shift.

After looking into the code i think that the dispatch of a EVENT_SELECTION_CHANGED is missing in the on doRowRangeSelection callback.
I added it and seems like it works now.

Is it the right way of doing it ?

**Comment by jlame** [comment]
This is the same as #981, sorry didn't saw it before creating the issue ...

**Comment by pccjamie** [comment]
@jlame - where did you add it?

**Comment by pccjamie** [comment]
@jlame - Never mind. Temporary dyslexia. Going to check it out now.

**Comment by ceolter** [comment]
fix now, will be in next release.
