### ISSUE TITLE
setRowData and Filters

### ISSUE THREAD

**Issue by a497988** [ceolter/ag-grid#994]
Hi,
I noticed that in the column filters, if a user changes the dropdown from contains to equals, and doesn't enter anything into the search field before setRowData is called, the dropdown reverts back to contains, instead of keeping the state of the dropdown selection.

I am saving/restoring the filter state using the get/set filter models. It works fine if there is something in the text field, but if there isn't, the dropdown value doesn't save. My data is refreshing every 3 seconds, so if a user hesitates at all the drop down will revert.

Is there a fix or something that I can do to prevent this?

**Comment by ceolter** [comment]
if you don't want the filter to change between loads, use:

```
filterParams: {newRowsAction: 'keep'}
```

https://www.ag-grid.com/javascript-grid-filtering/index.php
