### ISSUE TITLE
exportDataAsCsv

### ISSUE THREAD

**Issue by msio777** [ceolter/ag-grid#995]
Hi,
I 'm using angular 1.4.9 and If I use this function without params
`$scope.gridOptions.api.exportDataAsCsv()` I got this kind of error

> TypeError: Cannot read property 'processHeaderCallback' of undefined

but I If pass empty object {} `$scope.gridOptions.api.exportDataAsCsv({})` everythink works out 
Thanks 
Best Regards 
Michal

**Comment by ceolter** [comment]
already fixed in latest, if you want to try the v5 alpha, it is fixed there.
