### ISSUE TITLE
IE11: onGridReady callback invoked when ag-grid is not so ready still.

### ISSUE THREAD

**Issue by DOrlov77** [ceolter/ag-grid#997]
Hi Niall,
I got a next issue:

In Chrome and FF the next code works fine:
```
private onGridReady: Function = () => {
    // resize the grid to fit the page
    this.gridOptions.api.sizeColumnsToFit();
...
}
```

But in IE11 I should to use delay like
```
this.$timeout(() => this.gridOptions.api.sizeColumnsToFit(), 500, true);
```

tested with ag-grid 4.2.5 and 4.2.7

**Comment by DOrlov77** [comment]
In IE log you can find the next warning:
```
ag-Grid: tried to call sizeColumnsToFit() but the grid is coming back with zero width, maybe the grid is not visible yet on the screen?
```

**Comment by ceolter** [comment]
that's exactly what it says - IE is reporting back the grid with zero width - if I cannot find out the width of the grid at this point, then cannot work out the width the columns need to be.

**Comment by ceolter** [comment]
this seams fine to me:
```this.$timeout(() => this.gridOptions.api.sizeColumnsToFit(), 500, true);```

however i'd just do:
```setTimeout( ()=> this.gridOptions.api.sizeColumnsToFit(), 0 );

**Comment by DOrlov77** [comment]
Dear Niall,
If ```setTimeout( ()=> this.gridOptions.api.sizeColumnsToFit(), 0 );``` was working, I would prefer
```this.$scope.$applyAsync(() => this.gridOptions.api.sizeColumnsToFit());``` And that is what I've used till latest IE upgrade, but unfortunately the 0ms - 300ms time range is not enough to latest IE11 to make ag-grid ready to fit, so I use 500ms as workaround.

From other side, according to ag-grid documentation:
![image](https://cloud.githubusercontent.com/assets/7703176/16482811/423e72cc-3eba-11e6-84e4-4d10c4330f14.png)
so as an ag-grid user I expect that grid is READY to be resized on that event ("gridReady") 
:)

**Comment by ceolter** [comment]
not really true - the grid IS ready - but the DOM is not - is there anything else in your app that is stopping the grid from been displayed? maybe it is in a tab that is not yet visible?

**Comment by DOrlov77** [comment]
Agree - that is the reason I think the "gridReady" event need to be sync with DOM as well. Your grid is too quick for IE! :) The issue could be related to flex layout implementation in IE11...
And adding to the grid style ```min-height: 100px; min-width: 100px;``` fix that behavior too!

**Comment by DOrlov77** [comment]
Yep. I agree with you. The grid shouldn't care of the parent size but it
may be useful to have an event when grid are rendered and have non zero
size.

Also, have you a plan to add "autofit" option for grid?

_________
Thanks,
Dmitry

**Comment by ceolter** [comment]
```Also, have you a plan to add "autofit" option for grid?```
=> yes, it's on my long list. however it's not something someone who pays me is looking for, so it's not near the top of the list. something to consider when i have spare time.
