### ISSUE TITLE
setRowData(data) does not update more than one grid

### ISSUE THREAD

**Issue by jerz9017** [ceolter/ag-grid#998]
Hello,

I am initializing AgGrid as a WebComponent (using initializeAgAgridWithWebComponents()).

I have to include several ag-grids in the same page, in this way:

```
<ag-grid id="a"></ag-grid>
<ag-grid id="b"></ag-grid>
```

Each ag-grid component has a method called populate where I am setting the grid options and refreshing the data when is needed.

The initial data is being populated as expected, but when I refresh the data using this.options.api.setRowData(data) is just updating the last grid in the dom...

Any idea of what could be the reason?

Thanks,

Jorge

**Comment by ceolter** [comment]
one gridOptions per grid. you cannot share grid options.

then call gritOptions.api.setRowData() on each grid separatly.

**Comment by jerz9017** [comment]
Hi,

I am not sharing the gridOptions, I am handling that as a Polymer Object property, so its definition is specific to the grid instance.

**Comment by ceolter** [comment]
i can't think of any other reason about from 'shared state' that would be causing this.

if you can recreate in a plunker, i can take a look. however nobody else has reported this problem, so i'm tending towards something particular you have in your setup that is allow the grids to somehow interfere with each other.

**Comment by jerz9017** [comment]
I solved this just using api.destroy() if the grid was already initialized (if setGridOptions was already used), if not, define the grid options with the columnDefs and rowData desired.

**Comment by Bhawna14** [comment]
Hi All,

i need some help for below issue..
i have scenarios where my grid should change data as per the response object.
i tried using this.gridOptions.api.setRowData(this.rowDataGrid); but i got a error as "Cannot read property 'setRowData' of undefined"
So i tried using 
this.gridOptions.api.setRowData(this.rowDataGrid);
        this.gridOptions = {
                  onGridReady: function() {
                     this.gridOptions.api.setRowData(this.rowDataGrid);
                  }
          }
with this i got error as "Cannot read property 'api' of undefined"


Please help i am very new to angular 2

**Comment by Bhawna14** [comment]
@ceolter hey could you please help on this
